#import "../../../../shared/environments.typ": *

*Abbreviations used in this section:*

/ *5-HTP*:  5-hydroxytryptophan; serotonin precursor
/ *AAb*:  autoantibody
/ *AADC*:  aromatic L-amino acid decarboxylase; converts L-DOPA to dopamine
/ *ACh*:  acetylcholine
/ *AChE*:  acetylcholinesterase
/ *ALA*:  alpha-lipoic acid; antioxidant and pyruvate dehydrogenase cofactor
/ *AMPK*:  AMP-activated protein kinase; cellular energy sensor
/ *AQP2*:  aquaporin-2; renal collecting duct water channel
/ *ATP*:  adenosine triphosphate
/ *BBB*:  blood-brain barrier
/ *BP*:  blood pressure
/ *CK*:  creatine kinase; phosphocreatine buffer enzyme
/ *CNS*:  central nervous system
/ *COMT*:  catechol-O-methyltransferase; catecholamine degrading enzyme
/ *CoQ10*:  coenzyme Q10; ubiquinol/ubiquinone
/ *COX-2*:  cyclooxygenase-2
/ *CRP*:  C-reactive protein
/ *CYP*:  cytochrome P450
/ *DA*:  dopamine
/ *DAT*:  dopamine transporter
/ *DBH*:  dopamine-beta-hydroxylase
/ *DCA*:  dichloroacetate; pyruvate dehydrogenase kinase inhibitor
/ *DHEA*:  dehydroepiandrosterone; neurosteroid and androgen precursor
/ *DMF*:  dimethyl fumarate
/ *DNRI*:  dopamine-norepinephrine reuptake inhibitor
/ *DORA*:  dual orexin receptor antagonist
/ *DPP-4*:  dipeptidyl peptidase-4; incretin-degrading enzyme
/ *DRG*:  dorsal root ganglion
/ *DTBZ*:  dihydrotetrabenazine; vesicular monoamine transporter 2 PET ligand
/ *EBV*:  Epstein-Barr virus
/ *ET-1*:  endothelin-1; potent vasoconstrictor
/ *ETC*:  electron transport chain
/ *GABA*:  gamma-aminobutyric acid
/ *GAD*:  glutamate decarboxylase; gamma-aminobutyric acid synthesis enzyme
/ *GI*:  gastrointestinal
/ *GLP-1*:  glucagon-like peptide-1; incretin hormone
/ *GLP-1R*:  glucagon-like peptide-1 receptor
/ *GPCR*:  G protein-coupled receptor
/ *GSH*:  glutathione; primary intracellular antioxidant
/ *HHV-6*:  human herpesvirus 6
/ *HIF-1α*:  hypoxia-inducible factor 1 alpha
/ *HIT*:  histamine intolerance
/ *HPA*:  hypothalamic-pituitary-adrenal axis
/ *HR*:  heart rate
/ *HRV*:  heart rate variability
/ *HSC*:  haematopoietic stem cell
/ *HTN*:  hypertension
/ *H₂S*:  hydrogen sulfide; gaseous vasodilator and mitochondrial electron donor
/ *IA*:  immunoadsorption
/ *IDO*:  indoleamine 2,3-dioxygenase
/ *IgG*:  immunoglobulin G
/ *IL*:  interleukin
/ *IMPase*:  inositol monophosphatase; lithium target in phosphatidylinositol 4,5-bisphosphate resynthesis
/ *iNOS*:  inducible nitric oxide synthase
/ *IVIG*:  intravenous immunoglobulin
/ *KYNA*:  kynurenic acid; N-methyl-D-aspartate receptor antagonist
/ *LC-NE*:  locus coeruleus-norepinephrine
/ *LDN*:  low-dose naltrexone
/ *LTD4*:  leukotriene D4; bronchoconstrictor and mast cell activation syndrome mediator
/ *MAO-B*:  monoamine oxidase B; degrades dopamine
/ *MCAS*:  mast cell activation syndrome
/ *MMP*:  matrix metalloproteinase
/ *MRS*:  magnetic resonance spectroscopy
/ *mTORC1*:  mechanistic target of rapamycin complex 1
/ *mTORC2*:  mechanistic target of rapamycin complex 2; regulates cell survival and cytoskeleton
/ *NAC*:  N-acetylcysteine
/ *NAD⁺*:  nicotinamide adenine dinucleotide
/ *NE*:  norepinephrine
/ *NMDA*:  N-methyl-D-aspartate
/ *Nrf2*:  nuclear factor erythroid 2-related factor 2; antioxidant master regulator
/ *NRI*:  norepinephrine reuptake inhibitor
/ *NSAID*:  non-steroidal anti-inflammatory drug
/ *OH*:  orthostatic hypotension
/ *PDH*:  pyruvate dehydrogenase
/ *PDK*:  pyruvate dehydrogenase kinase
/ *PEA*:  palmitoylethanolamide; PPAR-alpha agonist
/ *PEM*:  post-exertional malaise
/ *PFC*:  prefrontal cortex
/ *PGD2*:  prostaglandin D2; mast-cell-derived prostaglandin
/ *PGDS*:  prostaglandin D2 synthase
/ *PGE2*:  prostaglandin E2
/ *PIP2*:  phosphatidylinositol 4,5-bisphosphate
/ *POTS*:  postural orthostatic tachycardia syndrome
/ *QUIN*:  quinolinic acid; N-methyl-D-aspartate receptor agonist from kynurenine pathway
/ *RAAS*:  renin-angiotensin-aldosterone system
/ *RLS*:  restless legs syndrome
/ *ROS*:  reactive oxygen species
/ *SC*:  supercomplex
/ *SFN*:  small-fiber neuropathy
/ *SIBO*:  small intestinal bacterial overgrowth
/ *SSRI*:  selective serotonin reuptake inhibitor
/ *SV2A*:  synaptic vesicle glycoprotein 2A; levetiracetam binding site
/ *TCA*:  tricarboxylic acid cycle
/ *TLR4*:  Toll-like receptor 4
/ *Treg*:  regulatory T cell; CD4+CD25+FoxP3+
/ *TRPM3*:  transient receptor potential melastatin 3; non-selective cation channel
/ *TRPV1*:  transient receptor potential vanilloid 1; capsaicin receptor; mediates heat/pain and arteriolar vasoconstriction
/ *VMAT2*:  vesicular monoamine transporter 2
/ *WASF3*:  Wiskott-Aldrich syndrome protein family member 3; respiratory supercomplex assembly inhibitor


=== Synthesis: Response + Reaction = Bidirectional Probe

The therapeutic response tells you which node in the cascade is *broken* — the drug compensated for a deficit, localizing the lesion. The side-effect profile tells you which nodes are *intact enough to react* — and which are so damaged they cannot even produce the expected adverse response. Together, the response and the reaction bracket the lesion:

| Drug | Positive response tells you | Side effect tells you |
|---|---|---|
| LDN | Neuroinflammation/TRPM3 present | Sedation → orexin critically low. Dysphoria → opioid-dependent homeostasis. No response to either → TLR4/opioid systems non-functional or non-contributory |
| Lithium (microdose, 2--20 mg elemental) | PIP2 cycle is the bottleneck; lesion at or above PIP2 | Polydipsia/polyuria at 2 mg elemental → occult nephrogenic DI vulnerability (AQP2 hypersensitivity); Tremor at 2 mg → cerebellar NE sensitivity (hyperadrenergic POTS); Nausea at 2 mg → slow gastric emptying (vagal dysfunction). No polydipsia/tremor/nausea at 20 mg elemental → renal, cerebellar, GI PIP2-gated systems all functional; lithium's IMPase effect is target-selective |
| Midodrine | Vasculature α1-responsive | Hypertension at minimal dose → denervation hypersensitivity (neuropathic POTS). No piloerection → length-dependent sympathetic neuropathy. No BP response at all → α1 receptors absent/blocked (GPCR AAb) |
| Pyridostigmine | Cholinergic signaling intact at ganglia | Severe GI cramping → gut muscarinic hypersensitivity (enteric denervation). No HRV improvement → vagal efferent pathway non-functional |
| Aripiprazole | Dopamine D2/D3 signaling rate-limiting | Akathisia at microdose → severe dopamine deficiency with supersensitive receptors. No response AND no side effects → D2/D3 system is neither deficient nor responsive (off-target lesion) |
| Pramipexole | RLS relief → D2/D3 postsynaptic receptors intact and responsive | Nausea + dizziness at RLS dose → D2/D3 supersensitivity in area postrema + cardiovascular centres (chronic DA deficiency → receptor upregulation). If nausea without dizziness → D2 receptors supersensitive in area postrema only; cardiovascular D2/D3 desensitized (atypical dissociation). If no nausea AND no dizziness at full dose → D2/D3 in area postrema and cardiovascular centres are too damaged to respond (Pattern 5 — D2 agonism ineffective in this patient for any indication) |
| Beta-blockers | HR reduction without fatigue worsening → sympathetic overactivation isolated to HR, not metabolism | Fatigue worsens → β2-AR lipolysis was metabolic fallback. Implies PDH/ETC glucose-to-ATP impairment |
| Fludrocortisone | Hypovolemia present (RAAS paradox) | Worsening orthostasis → venous pooling dominant (CT laxity), not hypovolemia. Hypokalemia at standard dose → renal aldosterone sensitivity intact despite central RAAS paradox (RAAS defect localized to renin) |
| Memantine | NMDA excitotoxicity rate-limiting | Sedation at low dose → basal glutamate tone already low. Implies kynurenic acid dominance, not quinolinic acid excess |
| Ketamine (sub-anesthetic) | NMDA excitotoxicity (QUIN-driven) rate-limiting for pain/cognition | Psychotomimetic at 0.1 mg/kg → severe NMDA hypofunction (KYNA dominance, not QUIN excess). Rapid pain relief without psychotomimesis → QUIN-driven NMDA excitotoxicity. Rapid mood without pain relief → mTORC1/BDNF synaptogenesis, not NMDA block. Null for all → NMDA system not rate-limiting |
| Celecoxib/Etoricoxib | COX-2-driven inflammation rate-limiting | Fatigue worsening at 100 mg BID → COX-2-derived PGE2 was maintaining cerebral perfusion, mitochondrial biogenesis, and/or HPA axis drive. Three-pathway ceiling: cerebral vasodilation, PGC-1α mitochondrial, and CRH/ACTH/cortisol axis. Symptom improvement without fatigue → COX-2-driven neuroinflammation dominates; tissue PGE2 function intact. Null → COX-2 not rate-limiting |
| Caffeine | — | No tachycardia → central sympathetic activation failure (CNS NE deficiency). No alertness → adenosine A2A receptors desensitized |
| Antihistamines (H1: cetirizine, fexofenadine, loratadine, rupatadine) | MCAS symptom reduction → mast cell degranulation is rate-limiting for flushing, pruritus, GI, rhinitis | No sedation at 4× dose → CNS H1 receptors desensitized from chronic mast cell histamine exposure (MCAS with CNS involvement). Dose-dependent somnolence → H1 receptors are intact and responsive; MCAS is peripheral-only (BBB intact). Rupatadine response at standard dose where other H1s require 4× → PAF antagonism component is providing benefit → PAF is rate-limiting for mast-cell-driven symptoms, not histamine alone |
| Ketotifen | Mast cell degranulation rate-limiting for MCAS symptoms | Severe sedation at 0.5 mg → histaminergic wakefulness depends on mast-cell-derived histamine (patient is "held awake" by MCAS). No sedation + MCAS improvement → H1 receptors intact but ketotifen benefits via mast cell stabilization, not H1 block. No effect at all → mast cells not rate-limiting |
| Niacin (50--500 mg) | — (pure side-effect probe; therapeutic niacin for NAD⁺/lipids is separate) | Severe flush at 25--50 mg → dermal mast cell PGD2 hyper-reactivity (severe cutaneous MCAS). Flush only at 250+ mg → mild or absent skin MCAS. No flush at 500 mg → HCA2 desensitization or PGD2 synthase deficiency. Flush prevented by aspirin → confirms PGD2 pathway (COX-1 → PGDS → PGD2). Flush prevented by antihistamines → histamine-mediated MCAS, not PGD2. Low-cost OTC MCAS diagnostic |
| Famotidine/Cimetidine | H2 receptor-blocked → gastric histamine or T-cell modulation (cimetidine) is rate-limiting | Depression/suicidal ideation → "paradoxical reactor" phenotype extended to histaminergic system. If famotidine causes depression but cimetidine does not → off-target effect, not H2 class effect. If cimetidine causes depression but famotidine does not → CYP450-mediated drug interaction (endogenous steroid or antidepressant metabolism altered) |
| Cromolyn sodium | Gut mast cell degranulation rate-limiting for GI symptoms | No GI benefit → gut mast cells are not the dominant source of systemic MCAS (CNS or systemic mast cells dominate), or cromolyn cannot access the relevant mucosal layer. No GI side effects at all → gut mucosa is either intact and non-reactive, or so damaged it cannot mount a response to the topical agent |
| DORA (daridorexant) | Suppress pathological nocturnal orexin surges → sleep maintenance | Sleep paralysis at low dose → orexin tone critically low (borderline narcolepsy); DORA contraindicated — need orexin agonism. No effect on sleep → orexin tone already at floor (severe deficiency). No sleep paralysis + improved maintenance → orexin tone normal |
| Trazodone | 5-HT2A blockade → slow-wave sleep enhancement → glymphatic support | Next-day sedation at 50 mg → H1 supersensitivity or slow CYP2D6 metabolism. OH at 25 mg → α1 adrenergic dependence for BP (neuropathic POTS). No next-day sedation → H1 desensitized (MCAS); CYP2D6 normal |
| Doxepin (low-dose) | Pure H1 antagonism → sleep maintenance | Excellent sleep at 3 mg → histaminergic arousal is dominant cause of awakenings (MCAS with CNS involvement). No effect → awakenings are non-histaminergic (orexin, adrenergic, or pain-driven). Next-day sedation at 3 mg → H1 supersensitivity; histaminergic insufficiency, not excess |
| Prazosin (0.5--1 mg bedtime, α1 antagonist, glymphatic probe) | NE-mediated vasoconstriction was suppressing glymphatic flow → improved morning symptoms | Severe OH at 0.5 mg → standing BP depends on α1-mediated vasoconstriction for every mmHg of orthostatic tolerance (neuropathic POTS). Glymphatic benefit inaccessible behind OH ceiling. Morning benefit at 0.25 mg strict supine → glymphatic window exists but requires 8h supine post-dose — can't stand. No OH at 1 mg → BP is not α1-dependent (hyperadrenergic POTS or adequate reserve). OH pattern distinguishes neuropathic POTS (α1 block OH) from hyperadrenergic POTS (central α2 crash with clonidine — clonidine-sensitive, prazosin-tolerant pattern) |
| Melatonin | Circadian phase advancement → sleep latency | Paradoxical alertness → severely delayed circadian phase or CYP1A2 ultra-rapid metabolism. Vivid nightmares → REM sleep disinhibition (α-delta sleep). No effect at 3 mg → sleep-onset insomnia is hyperarousal-driven (not circadian), pineal output already maximal, or MT1/MT2 downregulated |
| 5-HTP (50--100 mg) | Serotonin synthesis is rate-limiting (IDO tryptophan drain → serotonin depletion) | GI distress at 50 mg → gut serotonin hypersensitivity (5-HT3/5-HT4 upregulation from chronic peripheral serotonin depletion; confirms severity of IDO drain). Serotonin syndrome at 50--100 mg → high AADC activity or impaired MAO-A (oxidative-stress-mediated degradation failure). No GI distress at 100 mg → peripheral serotonin reserve adequate (mild or absent IDO drain) |
| Methylphenidate | Cognitive benefit → NE deficiency rate-limiting (DBH/LC-NE pathway) | Tachycardia ceiling → hyperadrenergic POTS; atomoxetine preferred (pure NRI). Crash ceiling → DA depletion + mitochondrial ATP deficit; add CoQ10/NADH. Insomnia ceiling → DAT occupancy too high for orexin drive; switch to modafinil |
| Amantadine | Presynaptic DA release → DA stores are intact but release is impaired (functional presynaptic lesion, not terminal loss) | Livedo reticularis at 100 mg → peripheral sympathetic vasomotor fragility (neuropathic POTS with dermal involvement). Confusion at 100 mg → NMDA hypofunction confirmed (same pattern as ketamine sensitivity — two structurally different NMDA antagonists produce the same cognitive ceiling at subtherapeutic doses). No benefit despite no side effects → presynaptic DA stores are empty (VMAT2 terminal loss); try L-DOPA or pramipexole. Improvement + no livedo/confusion → presynaptic DA release is the bottleneck; peripheral sympathetic and NMDA systems have adequate reserve |
| NAC (N-acetylcysteine) | Glutathione synthesis → oxidative stress is rate-limiting and GSH system is functional | Worsening fatigue at 600 mg → thiol-radical burst depletes GSH before synthesis completes, or cysteine diverted from transsulfuration (H₂S vasodilation lost → tissue perfusion drops), or copper chelation impairing DBH (anhedonia → NE synthesis failure, speculative at standard doses). Worse at 600 mg, better at 1,200 mg → initial radical burst cleared by higher GSH synthesis — confirms high oxidative stress AND functional GSH machinery. Worse at all doses → chronic thiol stress or H₂S pathway dependence. NAC + selenium prevents worsening → selenium deficiency bottleneck in GSH recycling |
| Amphetamines | Immediate cognitive/energy response → VMAT2-dependent DA release intact | Severe post-dose crash (PEM-like, weeks-long) → VMAT2 terminal compromise; confirms Liu 2026 DTBZ PET pattern. Never re-challenge. No response + no crash → DAT absent/saturated or DA system not rate-limiting |
| Modafinil/Armodafinil | DAT-mediated DA increase | Insomnia ceiling → orexin/histamine axis intact + DA-sensitive; try pitolisant. Next-day fatigue ceiling → energy reserve is bottleneck. No response → DAT dysfunctional (absent/blocked/AAb) |
| Solriamfetol | DA component of DNRI → cognitive benefit | BP/HR ceiling with no cognitive benefit → prefrontal α2A desensitization (NE available but PFC cannot use it); try guanfacine. Cognitive benefit with no BP/HR → DA system is the bottleneck, not NE |
| Pitolisant | Histaminergic anti-inflammatory (M1→M2) + cognitive | Insomnia ceiling → histaminergic system on hair trigger (consistent with orexin suppression model). Headache ceiling → histamine-mediated vasodilation (MCAS vascular hyper-reactivity). No response → histaminergic system not bottleneck (H3 downregulation or histamine depletion) |
| IVIG | GPCR AAb present + rate-limiting | Transient flare (48--72h) → confirms AAb neutralization + complement activation; flare persistence >7 days → complement-MCAS amplification loop. No flare + no response → no AAb, AAb not rate-limiting, or profound immune exhaustion |
| Rituximab | B-cell depletion effective → AAb from dividing plasmablasts | No response → AAb from long-lived plasma cells (rituximab-spared); try daratumumab. Transient response (weeks→relapse) → B-cell repopulation re-drives AAb; AAb are rate-limiting but source regenerates |
| Valacyclovir | Herpesvirus reactivation is rate-limiting → viral DNA polymerase active | No renal/CNS side effects despite high doses → renal clearance + BBB intact. If no response despite adequate dose/duration → EBV/HHV-6 reactivation is not rate-limiting for this patient OR virus is in sanctuary site (CNS, DRG) not accessible to oral acyclovir. Renal toxicity at standard dose → renal function severely impaired; switch to foscarnet (non-renal clearance) if antiviral trial essential |
| Valganciclovir | Broad-spectrum antiviral response (HHV-6, CMV, EBV) → herpesvirus replication is rate-limiting. Response where valacyclovir failed → EBV/HHV-6 in tissue sanctuary accessed by ganciclovir but not acyclovir | Bone marrow suppression (neutropenia, anemia, thrombocytopenia) at subtherapeutic doses → bone marrow reserve is already exhausted (consistent with chronic inflammation-driven myelosuppression or HSC exhaustion). Severe GI at standard dose → gut mucosa is inflamed/reactive (MCAS or enteric viral replication). No bone marrow suppression despite high doses → bone marrow reserve intact, HSC pool preserved — excludes HSC-level pathology. No response after 12-week trial → herpesvirus replication is not rate-limiting in this patient, regardless of PCR/HIT status |
| Gabapentin/Pregabalin | Neuropathic pain relief → α2δ-CaV channels functional + rate-limiting for pain | Severe sedation/cognitive at minimal dose → central sensitization so severe that minimal CaV blockade collapses CNS activation; α2δ channels upregulated from chronic calcium dysregulation. Paradoxical agitation → GAD dysfunction (glutamate accumulation). Tolerability ceiling → consider PEA, LDN, or ketamine instead |
| Duloxetine | NE/5-HT reuptake beneficial → noradrenergic or serotonergic deficiency is rate-limiting for pain/cognition/mood | Anticholinergic symptoms (not expected from duloxetine) → subclinical AChE deficiency or undiagnosed Sjögren's. Severe nausea at 30 mg → 5-HT3 receptor hypersensitivity in gut (serotonergic gut hypersensitivity; consistent with 5-HT depletion peripherally + receptor upregulation gut). No response + no side effects → NE/5-HT systems are neither deficient nor responsive; lesion is non-monoaminergic |
| Amitriptyline | NE/5-HT reuptake + H1 + M1 antagonism → pain, sleep, glymphatic benefit | Severe sedation at 5--10 mg → H1 receptor supersensitivity; histaminergic wakefulness drive is fragile (consistent with orexin/histamine dysfunction). Anticholinergic at low dose → M1 receptor supersensitivity (compensatory upregulation from low basal ACh). No sedation at 25 mg → H1 receptors desensitized (chronic histamine exposure from MCAS) |
| Atomoxetine | Pure NE reuptake inhibition → cognitive benefit | Tachycardia/BP increase with cognitive benefit → NE deficiency confirmed; prefrontal α2A intact. No cognitive benefit despite BP/HR → prefrontal NE system is postsynaptically desensitized (α2A downregulated); lesion is at receptor, not at NE synthesis. Guanfacine should work |
| Clonidine (0.05--0.1 mg, central α2 agonist) | Central sympathetic output is suppressible → sympathetic drive is load-bearing; compensatory sympathetic dependence consistent with neuropathic-hypovolemic POTS | Hypotensive crash at 0.05 mg → minimal sympathetic reserve; midodrine MUST precede clonidine. Controlled reduction at 0.1 mg → some reserve; central α2 agonism accessible. No BP change at 0.1 mg → α2 autoreceptors are desensitized (hyperadrenergic POTS pattern — chronic NE overstimulation). Dose at which BP drops is an ordinal readout of sympathetic reserve. Crash distinguished from prazosin OH: clonidine crash = central α2 suppression, sympathetic-dependence pattern; prazosin OH = peripheral α1 block, neuropathic POTS pattern — different POTS subtypes |
| Droxidopa | NE synthesis from precursor → orthostatic improvement | No orthostatic benefit + midodrine works → presynaptic NE synthesis/storage deficit (AADC or VMAT2). Confirms catecholamine synthesis deficit model. Supine HTN without orthostatic benefit → postsynaptic α1 desensitization (hyperadrenergic POTS). Midodrine + droxidopa together: presynaptic vs postsynaptic noradrenergic lesion resolved |
| L-DOPA/Carbidopa | DA synthesis from L-DOPA → cognitive/motor benefit | Severe nausea/OH at 1/4 tablet → D2 supersensitivity (same pattern as pramipexole and aripiprazole); DA deficiency confirmed across multiple drug classes. No cognitive benefit → lesion not at DA synthesis; D2/D3 absent/desensitized or cognitive dysfunction is non-dopaminergic |
| Corticosteroids | Broad anti-inflammatory response → inflammation is rate-limiting | Rapid improvement → inflammation drives symptoms (does not distinguish viral/autoimmune/mast cell). Crash on taper → HPA axis fragile; iatrogenic adrenal insufficiency. No improvement → steroid-resistant inflammation (inflammasome, complement, mast cell) or inflammation is downstream, not causal |
| CoQ10 / L-carnitine / D-ribose (mitochondrial supplements) | Mitochondrial substrate supplementation → ATP improvement | Worsening, not improvement → downstream ETC bottleneck; substrate flux increases ROS, not ATP. CoQ10 worsen → Complex III block. Carnitine worsen → lipid peroxide overload (low glutathione). D-ribose worsen → hypoglycemia (insufficient gluconeogenesis). Absence of benefit → bottleneck not at supplemented node |
| NADH (5--20 mg/day, Complex I electron donor) | Complex I electron deficiency is rate-limiting → NADH directly feeds electrons into the ETC, bypassing substrate-level dehydrogenases | Worsening fatigue at 5 mg → Complex I electron flux increases but the bottleneck is downstream (Complex III or IV blocked) → electrons leak before reaching Complex IV → superoxide production → oxidative stress worsens. Same mechanism as CoQ10 worsening but at a different node — NADH worsen = Complex I functional, Complex III+ blocked; CoQ10 worsen = Complex I/II functional, Complex III blocked. The divergence (NADH worsen + CoQ10 neutral = Complex I lesions; CoQ10 worsen + NADH neutral = Complex II lesions) maps the ETC block site. Improvement on NADH → Complex I electron deficiency confirmed; the ETC is functionally intact downstream of Complex I. No effect → Complex I is not the rate-limiting electron donor; or the ETC is globally defective (NADH cannot fix a broken chain) |
| Creatine (3--5 g/day, phosphocreatine ATP buffer) | ATP buffering capacity is the bottleneck — ATP is produced but consumed faster than the mitochondria can regenerate it; creatine provides an immediate phosphate donor pool | Creatinine elevation causing anxiety about renal function → creatinine is the normal breakdown product of creatine AND also the serum marker used to estimate GFR. In a patient taking 3--5 g/day of creatine monohydrate, a serum creatinine of 1.3 mg/dL is expected even with perfectly normal renal function — but triggers unnecessary nephrology consults and anxiety. Diagnostic: the creatinine elevation is a pharmacokinetic artifact, not renal toxicity — it confirms the creatine is being absorbed and converted to creatinine (functional creatine kinase pathway). However, exceeding 1.5 mg/dL at 3 g/day → either (a) pre-existing renal impairment (creatinine clearance is genuinely reduced, and the exogenous creatine load reveals it), or (b) very low muscle mass (less muscle to take up creatine → more spills into serum). GI cramping at standard dose → gastric or enterocyte ATP dependence — the GI mucosa requires ATP for active transport and tight junction maintenance; if creatine osmotically draws water into the gut lumen faster than the enterocytes can pump it out (ATP-dependent), cramps result → gut epithelial ATP deficit confirmed. Improvement in muscle fatigue within 5--7 days → ATP buffering is the bottleneck; the mitochondria produce ATP but cannot buffer demand spikes. No improvement despite elevated muscle creatine (verified by MRS) → the bottleneck is ATP production (not buffering), or the creatine kinase reaction is impaired (PCr + ADP → Cr + ATP is slow due to low CK activity). No improvement + no creatinine elevation → creatine was not absorbed (poor GI uptake), or endogenous creatine synthesis is already maximal and supplementation adds nothing |
| BC007 / Immunoadsorption (IA) | GPCR AAb removal → autoimmune component rate-limiting | Complete non-response → GPCR AAbs absent or not rate-limiting. BC007 works where IA fails → AAb subtype not removed by protein A (IgG3, IgA) or synthesis outpaces IA clearance. IA works where BC007 fails → AAb target not among BC007 aptamers |
| DMF (dimethyl fumarate) | Nrf2 activation → antioxidant/anti-inflammatory | Severe flushing at 120 mg → mast cell hyper-reactivity. Flushing prevented by aspirin → confirms PGD2-mediated MCAS (distinct from histamine-mediated MCAS). GI persists >2 weeks → gut mucosa cannot adapt to Nrf2 shift |
| Aspirin / NSAIDs | COX-1/COX-2 inhibition → pain/inflammation reduction | Worsening of MCAS symptoms → COX inhibition triggers mast cell histamine release (HIT/MCAS patients). Flushing prevented by aspirin before DMF → confirms mast cell PGD2 pathway. No pain benefit → pain is non-inflammatory (neuropathic, central sensitization) |
| Minocycline / Doxycycline | Anti-microglial, anti-astrocyte, MMP-9 inhibition | Severe vestibular symptoms (minocycline) → CNS vestibular system vulnerable (consistent with brainstem neuroinflammation). Photosensitivity (doxycycline) → intact drug metabolism, skin photosensitivity. No anti-inflammatory benefit at subantimicrobial doses → MMP-9 or microglial activation is not rate-limiting |
| Low-dose IL-2 | Treg expansion → autoimmune pathology is Treg-suppressible | Transient flare (24--48h) → effector T-cell activation precedes Treg expansion; autoimmune process includes activated effector T cells. Flare resolves with sustained improvement → Tregs expanded and functional. No flare + no improvement → Tregs not the autoimmune bottleneck (B-cell-driven or Treg-resistant). Improvement without flare → pure Treg deficiency with quiescent effectors |
| Rapamycin | mTORC1 inhibition → autophagy/mitophagy restoration. Metabolic/mitochondrial pathology is mTORC1-driven (@sec:aimm-cascade F4) | Immunosuppression at low dose (under 3 mg/week) → mTORC1/mTORC2 selectivity narrow; rapamycin not viable for chronic metabolic use. Hyperlipidaemia at low dose → hepatic mTORC1 particularly sensitive. Impaired wound healing → mTORC2-mediated repair is ceiling. No immunosuppression at 3 mg/week with metabolic benefit → mTORC1 selectivity confirmed |
| Fluvoxamine (low-dose, 25--50 mg) | σ1R agonism → ER stress reduction, autophagy restoration. Low-dose works where high-dose SSRIs fail → σ1R mechanism, not 5-HT | GI distress (5-HT3 activation) → off-target serotonergic effect at doses where σ1R benefit is expected. High-dose (100+ mg) losing benefit → serotonergic component becomes dominant, σ1R selectivity lost (Pattern 3). No benefit at any dose → neither σ1R nor 5-HT reuptake is rate-limiting |
| Z-drugs (zolpidem/eszopiclone) | GABA-A α1-mediated sleep initiation → GABA-A system intact and responsive | Paradoxical excitation / complex sleep behaviours → GABAergic inversion (NKCC1/KCC2 imbalance, GABA excitatory). Absent amnesia at standard dose → hippocampal GABA-A α1 desensitized. Complex behaviours only → striatal/motor GABA-A dysregulation. Normal sedation + amnesia → GABA-A α1 intact; sleep initiation is GABA-A-dependent |
| Pregnenolone (sulfate) | TRPM3 positive allosteric modulation restores channel function (@sec:trpm3-cascade A2) | Agitation/insomnia at 25--50 mg → TRPM3 functional and hypersensitive + GABA-A NAM tips E/I balance. Sedation (unexpected) → NMDA negative modulation dominates, consistent with QUIN-driven excitotoxicity. No CNS effect at any dose → TRPM3 absent, desensitized, or already saturated (Pattern 5) |
| Aspirin (low-dose, antiplatelet) | COX-1 inhibition → PGD2-mediated MCAS is prostaglandin-buffered | Worsening MCAS → PGD2 was mast-cell-stabilizing; prostaglandin brake removed. Bleeding at antiplatelet dose → haemostatic reserve narrow. Niacin flush prevented by aspirin → cutaneous PGD2 hyper-reactivity. No MCAS worsening → prostaglandin-independent MCAS |
| Nattokinase/Lumbrokinase | Fibrinolytic activity → microclot pathology rate-limiting for PEM/perfusion | Bleeding (epistaxis, bruising) at fibrinolytic doses → haemostatic reserve narrow; microclots are degradation-resistant. No bleeding even at high doses → wide fibrinolytic reserve. Neither bleeding NOR benefit → microclots not rate-limiting for PEM |
| Levetiracetam | SV2A binding → anti-kindling effect reduces PEM frequency/severity; PEM is a neuroplastic (kindling) process | Psychiatric adverse effects at low dose (250--500 mg) → limbic neurotransmitter reserve minimal (DA/5-HT deficiency). Sedation at low dose → global cortical suppression in hypometabolic brain. No effect on PEM → kindling not SV2A-mediated, or PEM is metabolic, not neuroplastic |
| Daratumumab (anti-CD38) | Plasma cell depletion → AAb from CD38+ long-lived plasma cells; works where rituximab (anti-CD20) fails | Infusion reactions → intact immune recognition of therapeutic antibody. Neutropenia → bone marrow CD38+ myeloid precursors affected; marrow reserve limited. No response + rituximab null → AAb source not accessible to B-cell or plasma-cell depletion |
| Ginkgo biloba | Platelet inhibition → microvascular platelet aggregation is rate-limiting | Bleeding at high dose → platelet function probe: if no bleeding at 240+ mg/day → platelet count and function are intact (Pattern 5). Bleeding at standard dose → pre-existing platelet dysfunction or thrombocytopenia |
| Montelukast | Leukotriene receptor antagonism → leukotrienes are the dominant MCAS mediator (improvement where antihistamines fail) | Psychiatric adverse effects (depression, agitation, suicidal ideation) → paradoxical reactor in CNS leukotriene pathways; LTD4 receptors in limbic system are involved in mood regulation. If improves MCAS symptoms where antihistamines failed → leukotrienes, not histamine, are dominant mast cell mediators |
| Metformin | AMPK activation → AMPK pathway rate-limiting for metabolic dysfunction | GI side effects ceiling before metabolic benefit → gut AMPK activation or mitochondrial complex I inhibition in enterocytes; GI intolerance identifies gut mitochondrial vulnerability. Lactic acidosis risk (rare) → pre-existing mitochondrial dysfunction increases metformin-associated lactic acidosis risk |
| Berberine (500--1,500 mg/day) | AMPK activation + mitochondrial complex I inhibition → same probe as metformin with additional lipid-lowering | Severe GI (cramping, diarrhoea) at 500 mg → gut AMPK hypersensitivity or enterocyte mitochondrial vulnerability (same as metformin GI ceiling but with the additional mechanism of berberine disrupting gut microbiota via bile acid modulation — and berberine's poor oral bioavailability means most stays in gut lumen, concentrating the GI effect). Hypoglycemia at 500 mg → gluconeogenesis is already impaired; AMPK activation suppresses hepatic gluconeogenesis, and in a patient with impaired glucose production (consistent with PDH dysfunction and low glycogen stores), even mild suppression tips glucose below threshold. No GI at 1,000+ mg → enterocyte AMPK system has adequate reserve; gut mitochondria resilient. No effect on fatigue despite AMPK activation → AMPK pathway is not rate-limiting for systemic energy metabolism; the bottleneck is downstream of AMPK (mitochondrial, not signaling) |
| GLP-1 agonists (semaglutide) | Anti-inflammatory (CRP reduction) + metabolic benefit | Unacceptable lean mass loss → metabolic cost exceeds anti-inflammatory benefit; contraindicated in sarcopenic ME/CFS. Severe GI/gastroparesis → pre-existing gastric dysmotility (vagal/enteric neuropathy). No anti-inflammatory benefit → GLP-1R pathway not rate-limiting for inflammation |
| DCA (dichloroacetate) | PDK inhibition → PDH activity restored; PDH phosphorylation rate-limiting (@sec:pdh-cascade E2) | Peripheral neuropathy at low cumulative dose → pre-existing peripheral nerve vulnerability (SFN). No lactate reduction → PDH not rate-limiting; block downstream of PDH. Neuropathy-free PDH benefit → therapeutic window accessible |
| Bromocriptine / Rotigotine | D2 agonism → same probe as pramipexole for DA deficiency | Same patterns as pramipexole (Pattern 1: nausea/OH from D2 supersensitivity; Pattern 5: absent expected side effects). Rotigotine patch offers continuous delivery → distinguishes pharmacokinetic from pharmacodynamic ceiling |
| Rasagiline / Selegiline (MAO-B inhibitor) | MAO-B inhibition → DA degradation reduced; DA half-life is rate-limiting for synaptic DA | DA degradation is the dominant DA clearance mechanism — synaptic DA is short-lived. If works where L-DOPA or aripiprazole fail → DA synthesis is intact (L-DOPA convertable) and D2/D3 receptors are intact (aripiprazole-responsive), but DA is catabolized too rapidly for either to sustain effect. Confirms accelerated DA turnover as the bottleneck (@sec:dopamine-convergence) | Serotonin syndrome at ≤10 mg/day + prior SSRI → CYP2D6 poor metabolizer (MAO-B selectivity lost at low dose due to accumulation). Serotonin syndrome despite 14-day SSRI washout → fluoxetine/norfluoxetine ultra-long half-life. No effect on cognition → DA degradation is not rate-limiting; DA synthesis, release, or postsynaptic signaling is the bottleneck. MAO-B inhibition near-ceiling without DA benefit → the MAO-B enzyme is not the dominant DA clearance pathway in this patient (COMT, DAT, or diffusion dominates) |
| Ambroxol | TRPV1 antagonism + mucolytic (Guaifenesin-like) | TRPV1-mediated pain or PEM reduction → confirms TRPV1 involvement in arteriolar vasoconstriction or sensory fibre pain (@sec:trpv1-cascade B1). Mucolytic effect improves airway clearance → if improves PEM, airway mucus/ventilation may be a PEM contributor (rare). If works where capsaicin fails → TRPV1 antagonism (ambroxol blocks) is more effective than desensitization (capsaicin depletes); the TRPV1 channels are constitutively active, not just sensitized | GI upset at low dose → TRPV1-expressing enteric afferents are hypersensitive; consistent with visceral hypersensitivity (IBS overlap). No PEM reduction → TRPV1 is not rate-limiting for PEM; or ambroxol does not reach arteriolar smooth muscle TRPV1 at oral doses. No mucolytic effect despite bronchial symptoms → mucus is not the dominant airway issue; consider MCAS-driven bronchoconstriction instead |
| PEA (palmitoylethanolamide) | PPAR-α agonism → microglial M1→M2 phenotype shift; anti-inflammatory through endocannabinoid-like mechanism | Mild GI (rare, usually well-tolerated even at 1,200 mg/day). No effect → PPAR-α pathway not rate-limiting for microglial phenotype; or microglial phenotype is not the bottleneck (consistent with LDN+/minocycline+ but PEA null — microglial activation is present, but phenotype shift alone is insufficient; ongoing TLR4/P2X7/C5aR activation overrides PPAR-α-mediated M2 polarization). Works where gabapentinoids fail → pain is glial-driven (PPAR-α), not α2δ-CaV-channel-driven. Null result is low-information because PEA has no distinctive side-effect pattern — only therapeutic response is diagnostic |
| Devil's claw (harpagoside) | COX-2 inhibition + iNOS suppression → herbal anti-inflammatory with broader mechanism than NSAIDs | GI irritation (COX-1 cross-inhibition at high doses, >2,400 mg/day) — same issue as NSAIDs but milder. No GI irritation → COX-1 reserve adequate; herbal COX inhibition is COX-2 selective at standard doses. No anti-inflammatory effect → COX-2/iNOS inflammatory pathway not rate-limiting. Low pharmacodiagnostic specificity — positive response cannot distinguish COX-2 from iNOS from placebo |
| Quercetin (500--1,000 mg/day) | Mast cell stabilization + COMT inhibition → dual MCAS + catecholamine probe | Quercetin inhibits COMT (catechol-O-methyltransferase), the enzyme that degrades dopamine and NE. If quercetin improves cognition + MCAS symptoms → dual mechanism: mast cell stabilization AND catecholamine prolongation. If quercetin improves cognition but ketotifen/cromolyn do not → the cognitive benefit is COMT-mediated (DA/NE half-life extension), not mast-cell-mediated. Anxiety/insomnia at 500 mg → COMT inhibition has pushed catecholamine tone above the inverted-U optimum (consistent with Met/Met COMT genotype — already low COMT activity, further inhibition = excessive catecholamines). Null result non-informative — no distinctive side-effect pattern to distinguish mast cell from COMT from absorption failure |
| ALA (alpha-lipoic acid, 300--600 mg/day) | Mitochondrial antioxidant + glucose uptake enhancer | Rare hypoglycemia in susceptible individuals (ALA activates GLUT4 translocation) — if hypoglycemia at 300 mg → impaired gluconeogenesis confirmed (same pattern as D-ribose hypoglycemia). No effect common — ALA's therapeutic window in ME/CFS has never been established. Low pharmacodiagnostic specificity |
| NR/NMN (nicotinamide riboside/mononucleotide, 250--1,000 mg/day) | NAD⁺ precursor through salvage pathway → if works, NAD⁺ depletion is rate-limiting and NAMPT/NMNAT salvage pathway is functional | No effect → either NAD⁺ not rate-limiting, or salvage pathway enzymes (NAMPT/NMNAT) are deficient (consistent with oxidative-stress-mediated NAMPT inactivation). Distinguish from niacin: NR/NMN null + niacin benefit → salvage pathway defective but Preiss-Handler pathway (niacin → NAD⁺) intact. NR/NMN benefit + niacin null → salvage pathway intact but Preiss-Handler blocked. Both null → NAD⁺ not rate-limiting, or both pathways require functional enzyme below what either precursor can overcome. Low side-effect profile — null result more informative than positive result |
| D-ribose (5--15 g/day) | Purine salvage pathway rate-limiting for ATP regeneration → bypasses de novo purine synthesis | Hypoglycemia at 5 g → impaired gluconeogenesis (D-ribose stimulates insulin release; without adequate hepatic glucose output, blood glucose drops). GI distress at 5 g → rapid small-intestine absorption with osmotic diarrhea — gut carbohydrate tolerance is narrow (consistent with SIBO or rapid transit). No effect → purine salvage is not rate-limiting (ATP regeneration is limited by mitochondrial function, not ribose availability). No hypoglycemia despite 10+ g → hepatic gluconeogenesis intact; insulin sensitivity normal. Low specificity — null result is non-informative because adequate purine salvage may still not fix a downstream mitochondrial bottleneck |
| Vitamin C + NAC (timed, HIF-1α CT remodeling probe) | ROS-mediated PHD inhibition is rate-limiting for acquired CT weakness → antioxidant combination restores PHD activity → HIF-1α degradation → reduced WASF3 → restored mitochondrial supercomplex assembly (@sec:hif1a-ct-cascade, @sec:wasf3-cascade) | GI distress from high-dose vitamin C (osmotic diarrhea at >2,000 mg) → gut carbohydrate/acid tolerance low; use liposomal vitamin C. If vitamin C + NAC improve exercise tolerance → HIF-1α-driven WASF3 upregulation is present and rate-limiting; the CT weakness is acquired (ROS-driven), not genetic (EDS). If null + EDS diagnosis confirmed → CT weakness is genetic, not redox-reversible. Low side-effect diagnostic yield beyond GI tolerance of vitamin C |
| Oxaloacetate (100--500 mg/day) | Anaplerotic TCA cycle substrate → if mitochondrial TCA flux is substrate-limited, oxaloacetate provides additional catalytic capacity | No side-effect diagnostic pattern — oxaloacetate has no known dose-limiting toxicity in humans at these doses. Null result is non-informative (may be absorption-limited, may be that TCA cycle is not the bottleneck, or may be that the TCA cycle bottleneck is at a different substrate). Low pharmacodiagnostic yield |
| DHEA (25--50 mg/day) | Neurosteroid precursor → if works, neurosteroid deficiency is rate-limiting for neuroprotection/mood/cognition | Androgenic side effects (acne, hirsutism in females; aggression/irritability) at 25 mg → androgenic conversion is active (functional 3β-HSD and 17β-HSD) → confirms intact peripheral steroidogenesis; DHEA is being converted to testosterone. If cognitive benefit + no androgenic SE → CNS neurosteroid conversion dominates over peripheral androgenic conversion — DHEA is selectively metabolized to neurosteroids (consistent with brain-selective sulfatase or aromatase expression). Null → neurosteroid deficiency not rate-limiting, or DHEA-S levels are already normal (and supplementation adds nothing). Low specificity — androgenic side effects trace peripheral steroidogenesis but not CNS pathology |
| DPP-4 inhibitors (sitagliptin, 25--100 mg/day) | DPP-4 inhibition → GLP-1 half-life extension → mild metabolic + anti-inflammatory benefit without the GI/lean-mass cost of GLP-1 agonists | No distinctive side-effect diagnostic — DPP-4 inhibitors are exceptionally well-tolerated. Null → GLP-1R pathway not rate-limiting. Works where GLP-1 agonists cause GI → DPP-4 inhibitors preserve endogenous GLP-1 without supraphysiologic levels. Low yield as a standalone probe but useful as a comparator to GLP-1 agonists |
| Ambrisentan (endothelin receptor antagonist) | Endothelin-1-driven vasoconstriction rate-limiting → if ambrisentan improves perfusion/PEM, ET-1-mediated microvascular dysfunction confirmed | Fluid retention at standard dose → pre-existing endothelial dysfunction (ET-1 is vasoconstrictive but also natriuretic — blocking it unmasks sodium retention). Hypotension at 5 mg → vascular tone is ET-1-dependent. Liver enzyme elevation → pre-existing hepatic vulnerability. Null → ET-1 not rate-limiting for perfusion. Low-use drug limited to specialist pulmonary hypertension management — high pharmacodiagnostic specificity but narrow clinical accessibility |
| Epoprostenol (IV prostacyclin) | Prostacyclin synthase deficiency → if epoprostenol reverses vasoconstriction, PGI₂ deficiency is rate-limiting for perfusion | Severe hypotension at low infusion rate → prostacyclin receptor supersensitivity (upregulated from chronic PGI₂ deficiency). Flushing + headache → PGI₂-mediated vasodilation intact; confirms receptor functionality. Jaw pain (classic prostacyclin side effect) → confirms drug delivery and receptor activation. Null → PGI₂ pathway not rate-limiting. Hospital-only probe, impractical for outpatient pharmacodiagnostics but highest-specificity microvascular probe available |

*Consequence:* Every medication trial in ME/CFS should track not just "did it work?" but also "what side effects appeared and at what dose?" and "what expected side effects were ABSENT?" The pattern of which systems react and which don't is as informative as the therapeutic response. A patient who gets severe akathisia at 0.5 mg aripiprazole has just had their dopamine receptor sensitivity measured without a PET scan. A patient who gets no piloerection from midodrine has just had their peripheral sympathetic nerve fiber integrity tested without a skin biopsy. This is pharmacology as functional neurophysiology — the drug IS the diagnostic test.

*Origin:* mechanistic-pathway-tracing, prompted by user question 2026-07-21.
