#import "../../../../shared/environments.typ": *

=== Emerging Metabolic Mechanisms: 2026 Update


#hypothesis(title: [ATG13 as Circulating Inflammatory Signal and Autophagy/Mitophagy Dysregulation in ME/CFS])[
*Certainty: 0.42.* Gottschalk et al. reported ATG13 — an autophagy protein essential for autophagosome initiation — markedly elevated in ME/CFS serum across independent cohorts, with exogenous ATG13 triggering inflammatory signaling in vitro. This is significant because ATG13 is not normally circulating at high levels; its presence extracellularly may function as a DAMP (damage-associated molecular pattern), activating pattern recognition receptors (TLRs, RAGE) and amplifying the Cell Danger Response independently of ongoing viral protein production. @Watton2026unified

The upstream mechanism controlling ATG13 availability is now well-characterized: mTORC1 phosphorylates ATG13 at Ser258 (pSer258-ATG13), preventing assembly of the ULK1/ATG13/FIP200 complex required for autophagosome initiation (Section @sec:mTOR-AMPK-autophagy-balance). Thus, the elevated circulating ATG13 documented in ME/CFS likely reflects mTORC1-driven disassembly of the autophagy initiation complex, with non-complexed ATG13 accumulating intracellularly before extracellular release. This interpretation is supported by the Drosen et al.\ (2025) murine model, in which mTOR-driven ATG13 inactivation triggered M1 macrophage infiltration, IL-6/RANTES production via STAT3, and PEM-like exercise intolerance @Drosen2025ATG13. Ruan et al.\ reported reduced pSer258-ATG13 following rapamycin treatment in their pilot study, consistent with mTORC1 de-repression of autophagy initiation @Ruan2025rapamycin.

Impaired mitophagy (mitochondrial autophagy) provides a biologically plausible pathway linking infection-triggered immune activation to sustained redox stress, reduced bioenergetic capacity, and amplified inflammatory signaling — without requiring major tissue damage or ongoing productive viraemia. When mitophagy is inefficient, damaged mitochondria accumulate, producing excess ROS and releasing mtDNA that activates innate immune pathways (cGAS-STING). This creates a self-reinforcing loop: immune activation impairs mitophagy → mitochondrial damage accumulates → mtDNA release amplifies immune activation → further mitophagy impairment. @Watton2026unified (Certainty: 0.42)

*Therapeutic implication.* Autophagy/mitophagy restoration may be a tractable therapeutic target. Hochecker et al. demonstrated that whole-body hyperthermia (WBH, 39°C) in ME/CFS patients (n=9) reduced autophagy marker LC3-II by 17.84% (p=0.0065) and improved mitochondrial respiratory capacity across all measures — basal respiration (+66.60%), ATP production (+61.41%), maximal respiration (+97.88%), and spare respiratory capacity (+112.35%) — in PBMCs @Hochecker2025HyperthermiaMECFS. HSPA5 (HSP70) mRNA increased 48.33%, suggesting that WBH acts through HSP70-mediated chaperone buffering that shifts resources from chronic autophagic quality control toward oxidative phosphorylation. Pharmacological mTORC1 inhibition (rapamycin/sirolimus) represents a direct approach: Ruan et al.\ (2025) reported improved fatigue and PEM in an uncontrolled pilot study (n=86, no control group) with exploratory biomarker changes (↓pSer258-ATG13, ↑BECLIN-1) @Ruan2025rapamycin. AMPK activators (metformin, berberine) offer an indirect route via mTORC1 inhibition; Brown et al.\ demonstrated AMPK rescue by metformin in ME/CFS myotubes @Brown2018AMPK, and Fineberg et al.\ (2025) propose metformin for ME/CFS and Long COVID via AMPK→mTOR→autophagy restoration @Fineberg2025Metformin. None of these approaches has been tested in a randomized controlled trial in ME/CFS. @Watton2026unified

*Falsifiable prediction.* pSer258-ATG13/total ATG13 ratio is elevated in ME/CFS vs control PBMCs at baseline (≥ 1.5-fold, n=30 per group); rapamycin exposure ex vivo (100 nM, 24h) reduces this ratio and restores autophagic flux (LC3-II turnover assay with bafilomycin A1 block) in ME/CFS but not control cells. Additionally, neutralizing ATG13 with specific antibodies in ex vivo ME/CFS PBMC cultures will reduce inflammatory cytokine production (IL-1$beta$, TNF-$alpha$) and shift mitochondrial morphology from fragmented to interconnected networks.
] <hyp:atg13-circulating-damp>

#speculation(title: [Nocturnal Autophagy Failure as the Cellular Basis of Unrefreshing Sleep])[
*Certainty: 0.45.* Autophagy is under strong circadian regulation, peaking during the overnight fasted period when mTORC1 activity is naturally suppressed by AMPK activation. In ME/CFS, if mTORC1 is constitutively active and AMPK is tonically suppressed by sympathetic PKA signaling (Section @sec:sns-ampk-suppression), the normal nocturnal autophagy surge would be blunted. The consequence is that cellular waste --- damaged proteins, dysfunctional mitochondrial fragments, aggregated protein complexes --- accumulates during the day (from normal metabolic activity) but is not cleared overnight. The patient wakes with the same cellular burden carried over from the previous day, creating the subjective experience of unrefreshing sleep despite adequate sleep duration and architecture.

This is distinct from sleep architecture theories of unrefreshing sleep (alpha-delta intrusions, reduced slow-wave sleep). Those theories explain why sleep quality may be objectively poor; this theory explains why even objectively adequate sleep fails to restore function. The two are compatible: disrupted sleep architecture reduces the time available for autophagy, while mTORC1 hyperactivation blunts the efficacy of whatever autophagy window exists. The prediction is that pSer258-ATG13 in PBMCs should fail to show the normal nighttime decline in ME/CFS (serial 24-hour sampling, inpatient setting), and that interventions restoring circadian autophagy (TRE, metformin, rapamycin) should improve subjective sleep recovery scores independently of changes in total sleep time or sleep stage distribution.

*Falsifiable prediction.* PBMC pSer258-ATG13 will show a normal nighttime trough (>40% decline from daytime peak) in healthy controls but a flattened rhythm (nocturnal decline < 20%) in ME/CFS during 24-hour inpatient sampling. Rapamycin (morning dosing, peak effect at night) will restore the nocturnal pSer258-ATG13 trough and improve subjective unrefreshing sleep scores (Visual Analogue Scale) by week 4 of treatment.
] <spec:nocturnal-autophagy-sleep>

#speculation(title: [mTOR Tone Index: pSer258-ATG13/Total ATG13 Ratio as mTORC1 Activity Biomarker])[
*Certainty: 0.50.* The phosphorylation state of ATG13 at Ser258 is a direct readout of mTORC1 activity at the autophagy initiation complex. Using the ratio of pSer258-ATG13 to total ATG13 normalises for individual-level expression differences and provides a single number reflecting mTORC1 "tone" --- the fraction of the autophagy gate that is actively held closed. A tone index exceeding 0.5 (more than half of ATG13 molecules phosphorylated) predicts non-functional autophagy initiation. Normalising to a post-24-hour-fasted ratio provides the "autophagy reserve" score: how much residual gate closure occurs after the strongest physiological stimulus (fasting), reflecting the depth of the mTORC1 lock.

This ratio has several properties making it suitable as a clinical biomarker: (a) it is mechanistically proximal (one step from functional autophagy), (b) it normalises inter-individual variation in ATG13 expression, (c) it is dynamic (changes within hours of mTORC1 modulation), and (d) it has preliminary clinical signal (Ruan et al.\ reported reduced pSer258-ATG13 after rapamycin @Ruan2025rapamycin). In practice, measurement requires paired PBMC immunoblotting for phospho- and total ATG13 --- a moderate-cost assay (USD 200--300 per sample) feasible in research labs but not yet standardized for clinical use.

*Falsifiable prediction.* The mTOR tone index (fed/fasted pSer258-ATG13 ratio) will discriminate ME/CFS from healthy controls with AUC > 0.75 in a blinded comparison (n=50 per group). Patients with tone index > 2.0 (i.e., more than twice the expected fasted ratio) will show ≥ 2-fold higher response rate to rapamycin or metformin compared to those with tone index ≤ 1.5. Tone index will show test-retest reliability with ICC > 0.7 over a 4-week interval in stable patients.
] <spec:mTOR-tone-index>

#speculation(title: [SMPDL3B: Lipid Raft--Mitochondrial Quality Control Bridge])[
*Certainty: 0.33.* Recent ME/CFS-specific work identifies SMPDL3B (sphingomyelin phosphodiesterase acid-like 3B), a membrane-associated regulator of sphingolipid balance, as a potential biomarker and mechanistic mediator. Altered SMPDL3B may change lipid raft fluidity and receptor organization, modifying immune responses to inflammatory and antiviral stimuli. @Watton2026unified

Convergent findings in ME/CFS and Long-COVID implicate membrane lipid organization in immune dysfunction. Lipid rafts function as signaling platforms that regulate receptor clustering and activation thresholds, including Toll-like receptor signaling. The lipid raft framework links commonly observed "omics-level" lipid abnormalities in ME/CFS to cellular immunophenotypes, since raft composition depends on sphingolipid and cholesterol handling and can be remodeled by systemic metabolic cues and chronic inflammatory signaling. @Watton2026unified

A critical theme emerges: lipid biology is not an adjunct topic in ME/CFS but a potential mechanistic substrate linking immune signaling, mitochondrial quality control, redox buffering, and endothelial stability. Lipids provide structure to membranes and substrates for inflammatory mediators; they govern receptor microdomains while regulating mitochondrial dynamics. Consequently, lipid dysregulation could plausibly yield a persistent "mis-set" immune state after infection. The SMPDL3B pathway offers a testable entry point for investigating this lipid-immune-mitochondrial axis. (Certainty: 0.33)

*Falsifiable prediction.* SMPDL3B knockdown or overexpression in primary immune cells will predictably alter (1) lipid raft receptor distribution (TRPM3 surface localization), (2) ceramide levels in mitochondrial membranes, and (3) mitophagy flux (LC3-II accumulation, PINK1/Parkin recruitment).
] <spec:smpdl3b-lipid-raft-mito>

#speculation(title: [Haptoglobin Proteoforms and PEM-Linked Oxidative Stress])[
*Certainty: 0.45.* Moreau's group identified haptoglobin (Hp) quantity and proteoform structure as relevant to core ME/CFS symptoms including PEM and cognitive dysfunction. Hp scavenges free haemoglobin released during hemolysis and thus buffers against heme-mediated oxidative stress and endothelial injury. Reduced functional Hp capacity permits exaggerated oxidative and vascular stress during or after exertion, with downstream effects on microvascular regulation and symptom relapse. @Watton2026unified

Taken together, ATG13/autophagy perturbation, SMPDL3B/lipid raft regulation, and haptoglobin proteoform variation converge on a common theme: lipid and protein quality control systems buffer physiological stress, and their impairment in ME/CFS creates vulnerability that becomes clinically apparent under exertion. This is consistent with the broader model of state-dependent, stress-revealed pathology described in Chapter @ch:integrative-models (Section @sec:unified-post-infectious-model). (Certainty: 0.45)

*Falsifiable prediction.* Specific Hp proteoforms will correlate with cognitive test scores (processing speed, working memory) during PEM, endothelial function markers (VCAM-1, E-selectin), and time to symptom resolution, independent of total Hp concentration.
] <spec:haptoglobin-pem>

