#import "../../../../shared/environments.typ": *

=== Speculative Metabolic Interventions
<sec:speculative-metabolic-interventions>

#speculation(title: [Mitophagy Enhancement via PINK1/Parkin Activation])[
*Certainty: 0.48. Probability of clinically meaningful efficacy in ME/CFS: 0.08.* PINK1/Parkin pathway activators (urolithin A, nicotinamide riboside) could enhance damaged mitochondria clearance, reduce oxidative burden, and allow metabolic recovery from the CDR state. Impaired mitophagy sustains redox stress and inflammation per the unified model. @Watton2026unified PINK1/Parkin activators are in preclinical/early clinical development for other conditions; no ME/CFS data exists. Urolithin A has human safety data from muscle aging trials. Falsifiable: mitophagy enhancer treatment of ME/CFS cells will increase LC3-II accumulation and PINK1/Parkin recruitment to mitochondria, reduce ROS, and improve OCR.
] <spec:mitophagy-enhancers>

#speculation(title: [Spermidine for Autophagy Enhancement and CDR Reset])[
*Certainty: 0.30. Probability of clinically meaningful efficacy in ME/CFS: 0.04.* Spermidine, a well-established dietary autophagy inducer, could pharmacologically recapitulate the hyperthermia effect demonstrated by Hochecker et al. (autophagy markers decreased 17.84%, mitochondrial respiration increased 61-112% @Hochecker2025HyperthermiaMECFS), potentially shifting cells from stalled CDR to adaptive metabolic state. Spermidine-induced autophagy is well-established in aging biology; no ME/CFS data exists. Falsifiable: spermidine supplementation in ME/CFS PBMCs will increase autophagic flux (LC3-II ratio, p62 degradation) and improve mitochondrial respiration.
] <spec:spermidine-autophagy>

#speculation(title: [Butyrate for Mitochondrial-Nuclear Crosstalk Restoration])[
*Certainty: 0.35. Probability of clinically meaningful efficacy in ME/CFS: 0.06.* Butyrate is an HDAC inhibitor that can epigenetically reprogramme mitochondrial gene expression. SCFA deficits (Chapter @ch:gut-microbiome) plus CDR-induced epigenetic silencing may be counteracted by butyrate supplementation, restoring PGC-1$alpha$ and NRF1-dependent mitochondrial biogenesis. Butyrate HDAC inhibition and mitochondrial biogenesis upregulation are established in vitro; no ME/CFS-specific data. Falsifiable: butyrate treatment of ME/CFS immune cells will increase histone acetylation at PGC-1$alpha$ promoters and upregulate TFAM/mtDNA copy number.
] <spec:butyrate-mitochondrial-reprogramming>

#speculation(title: [Taurine for Calcium Homeostasis and Mitochondrial Protection])[
*Certainty: 0.25. Probability of clinically meaningful efficacy in ME/CFS: 0.03.* Taurine modulates calcium signaling, stabilizes mitochondrial membranes, and reduces oxidative stress. Given TRPM3 dysfunction and calcium-mitochondria crosstalk deficits, taurine supplementation could support both calcium homeostasis and mitochondrial resilience. Taurine's calcium-modulating and mitochondrial-protective effects are well-characterized; no ME/CFS data. Falsifiable: taurine treatment of ME/CFS cells will normalise calcium influx kinetics, stabilize mitochondrial membrane potential, and reduce mPTP opening.
] <spec:taurine-calcium-mito>

#speculation(title: [N-Acetylcysteine for Thiol Redox Buffering and CDR Reset])[
*Certainty: 0.35. Probability of clinically meaningful efficacy in ME/CFS: 0.08.* CDR involves redox dysregulation. NAC replenishes glutathione, modulates redox-sensitive signaling (NF-$kappa$B, Nrf2), and may facilitate CDR resolution by restoring thiol redox balance. NAC's glutathione-replenishing effects are well-established clinically; no ME/CFS-specific trial data. The probability is higher than most nutraceuticals because NAC has demonstrated objective efficacy in related conditions (COPD, psychiatric disorders) via glutathione restoration. Falsifiable: NAC treatment will increase GSH/GSSG ratio in ME/CFS PBMCs, shift Nrf2-dependent gene expression, and reduce inflammatory cytokine production.
] <spec:nac-cdr-redox>

#speculation(title: [Controlled Cold Exposure for Mitochondrial Biogenesis Induction])[
*Certainty: 0.25. Probability of clinically meaningful efficacy in ME/CFS: 0.01. ⚠ THERMOREGULATORY SAFETY CAVEAT.* Cold exposure activates brown adipose tissue, increases mitochondrial biogenesis via PGC-1$alpha$, and modulates inflammatory signaling. However, ME/CFS patients have documented thermoregulatory dysfunction, autonomic instability, and cold hypersensitivity that contraindicate standard protocols. The existing cryotherapy literature shows 45% attrition in the only CFS whole-body cryotherapy study (Kujawski 2023), suggesting poor tolerability. Any protocol would require extremely gradual titration under clinical supervision. Falsifiable: gradual cold exposure will increase PGC-1$alpha$ and NRF1 expression in PBMCs and be tolerated without PEM at slow titration rates.
] <spec:cold-exposure-mitochondrial>

#speculation(title: [Spare Respiratory Capacity as Thermoregulatory Capacity Proxy in ME/CFS])[
*Certainty: 0.30.* Hochecker et al. (2025, n=9, within-subject pre-post, single center, unreplicated) demonstrated that WBH increases spare respiratory capacity by 112.35% in ME/CFS PBMCs @Hochecker2025HyperthermiaMECFS. Critical caveat: whether PBMC spare respiratory capacity correlates with thermoregulatory tissue (eccrine gland, skeletal muscle, brown adipose, vascular smooth muscle) capacity is entirely untested — PBMCs are immune cells, not thermoeffectors. The inference from cellular respirometry to whole-body thermoregulation is a major extrapolation. Thermoregulation is energetically expensive: sweating requires sustained ATP for eccrine gland ion transport, shivering requires burst mitochondrial output, and vasomotion requires constant smooth muscle ATP turnover. Spare respiratory capacity — the difference between maximal and basal respiration — theoretically represents the mitochondrial reserve available for these thermoregulatory demands, but this has never been measured in thermoeffector tissues. Predictions (a, b, c) are tentative and depend on the PBMC-to-thermoeffector extrapolation being valid. Falsifiable: spare respiratory capacity in ME/CFS PBMCs will correlate with heat tolerance time (r > 0.6) and cold tolerance time (r > 0.5); improving reserve via WBH will increase both tolerances.
] <spec:mitochondrial-reserve-thermoreg>

#speculation(title: [Heat-Induced Autophagy Switch: Selective-to-Bulk Transition via HSP70 Redistribution])[
*Certainty: 0.40.* LC3-II is elevated in ME/CFS PBMCs, suggesting chronic selective autophagy (mitophagy, ER-phagy) attempting to clear damaged organelles. Hochecker et al. showed that WBH reduces LC3-II by 17.84% (p=0.0065) while simultaneously increasing HSP70 and mitochondrial respiration @Hochecker2025HyperthermiaMECFS. This pattern suggests that heat shock triggers a switch from energy-intensive selective autophagy to more efficient bulk autophagy via HSP70 chaperone redistribution: HSP70 released from autophagosome membranes becomes available for mitochondrial protein import and folding support, simultaneously reducing selective autophagy markers and improving oxidative phosphorylation. This model explains the apparently paradoxical finding that decreasing autophagy (LC3-II) improves mitochondrial function — autophagy was not "good" autophagy clearing healthy mitochondria, but "stress" autophagy attempting to compensate for proteotoxic overload. Falsifiable: ME/CFS PBMCs will show elevated selective autophagy markers (Parkin, BNIP3) and reduced bulk autophagy flux (p62 degradation); WBH will decrease selective markers and increase bulk flux; HSP70 knockdown will block the WBH-induced switch.
] <spec:autophagy-switch-heat>

#speculation(title: [Normobaric Hypoxia Preconditioning for Mitochondrial Resilience])[
*Certainty: 0.40. Probability of clinically meaningful efficacy in ME/CFS: 0.10.* Hypoxia preconditioning upregulates HIF-1$alpha$, enhancing mitochondrial efficiency via PGC-1$alpha$ co-activation and improving stress tolerance. The HIF pathway is increasingly recognized as a central hub in ME/CFS pathophysiology: HIF-1$alpha$ stabilization drives the metabolic shift toward glycolysis at the expense of oxidative phosphorylation, while chronic HIF-2$alpha$ activation contributes to endothelial barrier dysfunction @Ribeiro2026HIF2alpha (Section @sec:hif2a-endothelial in @ch:cardiovascular for the expanded mechanism). Rather than avoiding hypoxia altogether, *controlled* brief hypoxic exposures may harness the HIF programme's adaptive arm — inducing EPO, VEGF, glycolytic enzymes, and mitophagy regulators — while avoiding the maladaptive persistence of HIF-mediated metabolic suppression that may underlie PEM @Kaczmarek2023miRNAhypoxia. The key distinction is *intermittency*: brief hypoxia cycles (3--5~min) with intervening normoxia may train the HIF response to activate and deactivate appropriately, restoring the dynamic range lost in ME/CFS. This framework integrates the HIF inertia hypothesis (@spec:hif-pathway-inertia) with intermittent hypoxic training data from other conditions @Gangwar2019IHTaltitude @JanssenDaalen2025hypoxicPD.

The mechanistic coherence is higher than the original estimate (0.25) because: (a) the HIF pathway now has direct ME/CFS relevance via miRNA and ECM evidence, (b) intermittent hypoxic training has demonstrated safety and efficacy in Parkinson's disease, and (c) the dual-face of HIF (adaptive vs maladaptive) provides a clear framework for distinguishing beneficial from harmful protocols. However, clinical efficacy probability remains modest (0.10) pending direct ME/CFS data. Hypoxia still carries risks of triggering PEM in metabolically fragile patients, and the protocol parameters (FiO#sub[2], cycle timing, session frequency) are entirely untested in ME/CFS.

*Falsifiable predictions:*
    + Normobaric hypoxia preconditioning (FiO#sub[2] 0.16, 5~min cycles × 6, 3×/week × 4 weeks) increases HIF-1$alpha$ protein by $>=1.5$-fold and PGC-1$alpha$ mRNA by $>=2$-fold in PBMCs vs sham
    + Dynamic HIF response range (peak-to-baseline fold-change of HIF target gene expression after acute hypoxia challenge) increases by $>=50$% vs pre-training baseline
    + Peak work rate on CPET increases by $>=10$% without $>=2$-point increase in PEM incidence at 48~h vs sham

*Limitations.* No ME/CFS preconditioning data exist. Protocol parameters are extrapolated from neurorehabilitation literature. Individual variation in hypoxic ventilatory response and baseline HIF activity may determine responders vs non-responders. The risk of PEM induction cannot be eliminated without empirical dose-finding.
] <spec:hypoxia-preconditioning>

#open-question(title: [PBMC Mitochondrial Morphology as Quantitative Disease Activity Biomarker])[
Mitochondrial fragmentation is central to ME/CFS (Section @sec:mito-evidence). High-content imaging of PBMC mitochondria — morphology, membrane potential, respiration — could provide quantifiable biomarkers of CDR state, track disease activity during PEM cycles, and assess treatment response objectively. Existing mitochondrial fragmentation assays (MitoTracker, Seahorse) are mature technologies; the open question is whether PBMC mitochondrial morphology produces clinically useful disease-activity metrics. Falsifiable: PBMC mitochondrial fragmentation indices will correlate with disease severity and change detectably during PEM cycles before symptom-scale changes. Probability of diagnostic utility: 0.15.
] <oq:pbmt-mitochondrial-morphology>

#open-question(title: [ATG13 Interaction with Conventional DAMPs])[
Does ATG13 utilize distinct receptors from HMGB1/mtDNA, or does it synergise with conventional DAMPs to amplify inflammatory signaling @Ibrahim2026HMGB1Neuroinflammation @Chen2026HMGB1pCTSLAxis? Characterising ATG13 receptor usage (TLRs, RAGE, STING) and downstream pathway convergence (NF-$kappa$B, cGAS-STING) will clarify its unique contribution to CDR amplification and whether ATG13 neutralization would produce effects additive to or redundant with standard anti-inflammatory approaches. Falsifiable: ATG13 will utilize distinct receptors from HMGB1/mtDNA and synergise with conventional DAMPs to amplify cytokine production via converging on NF-$kappa$B and STING pathways. Probability of novel therapeutic target: 0.10.
] <oq:atg13-damp-interactions>

#hypothesis(title: [HIF-1alpha-Mitochondria-ECM Pathogenic Triad])[
*Certainty: 0.60.* Moschini et al. demonstrated that HIF-1alpha drives tendinopathy independently of VEGF in a murine model, establishing HIF-1alpha as a direct mechanistic driver of connective tissue pathology @Moschini2026HIFTendinopathy. @Sahin2012HIFTendon This finding, when integrated with established ME/CFS findings on mitochondrial dysfunction and HIF-1alpha elevation, suggests a self-reinforcing pathogenic triad.

*Mechanism.* HIF-1alpha suppresses mitochondrial oxidative phosphorylation and shifts metabolism toward glycolysis—the "Warburg-like" metabolic phenotype documented in ME/CFS immune cells (Chapter @ch:immune-dysfunction) and muscle. That infection can trigger host HIF-1$alpha$ stabilisation has an _in vitro_ proof-of-principle: _Bartonella henselae_ stabilises HIF-1$alpha$ in cell lines, producing cellular hypoxia and decreased ATP @Kempf2005BartonellaHIF1 — the first such demonstration in a bacterial infection, though it is a single unreplicated cell-line study and does not by itself establish the effect in primary cells or in ME/CFS. miRNA-mediated silencing of HIF target genes may further impair the adaptive transcriptional response to tissue hypoxia, blunting EPO and VEGF induction and locking the system in a maladapted state @Kaczmarek2023miRNAhypoxia. Mitochondrial dysfunction increases reactive oxygen species (ROS) production, which stabilizes HIF-1alpha through prolyl hydroxylase inhibition, creating a vicious cycle. Both HIF-1alpha-driven metabolic shift and mitochondrial ROS impair extracellular matrix homeostasis: HIF-1alpha directly upregulates matrix metalloproteinases (MMPs) and downregulates collagen synthesis, while ROS damages existing ECM components and fibroblasts. The triad becomes self-reinforcing: HIF-1alpha drives ECM pathology; mitochondrial dysfunction impairs ECM repair; ROS from mitochondria stabilizes HIF-1alpha.

*ME/CFS context.* ME/CFS tissue samples should show correlated abnormalities in HIF-1alpha, mitochondrial function, and ECM markers. The high prevalence of hypermobility syndromes (hEDS, HSD) in ME/CFS—up to 70% in some cohorts—may represent the clinical manifestation of this triad operating in connective tissue. @Ganesh2024LongCOVIDHSD @Ramirez-Paesano2023CCI

*Cross-references.* Chapter @ch:integrative-models synthesizes cross-system pathophysiological loops from HIF-1alpha elevation documented in ME/CFS stress response studies.

*Falsifiable prediction.* ME/CFS tissue samples (muscle biopsy, skin, or tendon when clinically indicated) will show: (1) elevated HIF-1alpha protein levels compared to controls; (2) correlated mitochondrial dysfunction (reduced oxidative phosphorylation, elevated ROS); (3) ECM abnormalities (elevated MMP-3/MMP-9, abnormal collagen/elastin ratios). Within ME/CFS patients, HIF-1alpha levels will correlate with both mitochondrial dysfunction severity and hypermobility scores (Beighton, GJH).

*Limitations.* Moschini 2026 is a murine tendinopathy model; human tendon data are limited. Tissue sampling in ME/CFS is rare; skin or muscle biopsy may not fully recapitulate tendon pathology. The directionality of the triad components in established disease is unclear—any node could be primary in individual patients.
] <hyp:hif1alpha-mito-ecm-triad>

#hypothesis(title: [ARB-Mediated Capillary Basement Membrane Restoration])[
*Certainty: 0.45.* Angiotensin II receptor blockers (ARBs; losartan, telmisartan) may restore capillary basement membrane structure and improve microcirculation in ME/CFS by reducing TGF-$beta$ signaling, which drives excessive ECM production at capillary basement membranes. @Wust2024capillary @Wirth2026CTDMECFS

*Mechanism.* Wust et al. demonstrated massive collagen IV deposition and basement membrane thickening in ME/CFS muscle capillaries via electron microscopy—a structural abnormality that creates a mechanical bottleneck independent of mitochondrial function @Wust2024capillary. Basement membrane thickening impairs oxygen and nutrient diffusion, creating pre-mitochondrial hypoxia. ARBs reduce TGF-$beta$ signaling and ECM production, with demonstrated efficacy in diabetic nephropathy where they normalize glomerular basement membrane thickness and preserve filtration function. In ME/CFS, ARBs could thin basement membranes, restore diffusion gradients, and improve microcirculation without directly targeting mitochondria.

*Clinical rationale.* ARBs are well-tolerated, widely available, and have favorable safety profiles. The TGF-$beta$ elevation documented in ME/CFS (Chapter @ch:immune-dysfunction) provides mechanistic support. The bidirectional connective tissue disorder-ME/CFS relationship established by Wirth et al. suggests that connective tissue pathology is not merely a comorbidity but may contribute to disease maintenance @Wirth2026CTDMECFS.

*Dose titration requirement.* The hypothesis requires careful dose titration: low-dose ARBs may reduce TGF-$beta$ without clinically significant blood pressure effects, while standard antihypertensive doses may cause orthostatic intolerance in POTS-comorbid patients. Telmisartan has partial PPAR-$gamma$ agonism, providing additional anti-inflammatory benefit; losartan has stronger uric acid-lowering effects relevant to metabolic comorbidities.

*Falsifiable prediction.* ME/CFS patients treated with low-dose ARBs will show: (1) reduced basement membrane thickening on serial muscle biopsy (feasible in interventional trials with pre/post sampling); (2) improved capillary diffusion metrics (oxygen microsensor, contrast-enhanced ultrasound); (3) reduced exercise-induced lactate at given workloads (reflecting improved oxygen delivery); (4) symptom improvement correlating with basement membrane thinning rather than blood pressure changes.

*Limitations.* Basement membrane measurements require muscle biopsy—feasibility limited to interventional trials. TGF-$beta$ has pleiotropic functions; systemic reduction may have unintended consequences. Not all ME/CFS patients may have basement membrane pathology; the hypothesis predicts subgroup specificity.
] <hyp:arb-capillary-restoration>

#speculation(title: [Fibroblast Glycogen Metabolism and ECM Production])[
*Certainty: 0.30.* ME/CFS metabolic dysfunction may impair fibroblast glycogen storage and utilization, reducing ECM quality and contributing to connective tissue pathology. This novel connection links the metabolic trap hypothesis (Chapter @ch:energy-metabolism) to connective tissue pathophysiology.

*Mechanism.* Fibroblasts store glycogen as an energy reserve for ECM synthesis—collagen, elastin, and proteoglycans are energetically expensive to produce. Glycogen provides local ATP for the extensive protein synthesis and crosslinking required for ECM assembly. If ME/CFS metabolic dysfunction impairs fibroblast glycogen storage or utilization—through impaired glycolysis, glycogen synthase dysfunction, or abnormal glycogen branching—fibroblasts may produce reduced quantities or structurally abnormal ECM. This could explain the high prevalence of hypermobility, skin hyperextensibility, and tissue fragility in ME/CFS.

*Connection to metabolic trap.* Phair's metabolic trap hypothesis—impaired CD39/CD73 activity reducing adenosine production—creates a systemic bioenergetic deficit that would disproportionately affect fibroblasts, which are long-lived, slowly-proliferating cells with limited regenerative capacity compared to immune cells. Fibroblasts cannot rapidly compensate for chronic energy deficit through proliferation; instead, they would downregulate energy-intensive ECM synthesis, producing progressive connective tissue weakness.

*Tissue specificity.* Different fibroblast populations may be differentially affected based on glycogen content and turnover rates: skin fibroblasts (high glycogen, visible as PAS-positive granules in normal histology) may show early abnormalities; tendon fibroblasts (low baseline glycogen) may be more vulnerable to minor deficits; vascular adventitial fibroblasts may contribute to capillary basement membrane pathology when glycogen-depleted.

*Falsifiable prediction.* ME/CFS fibroblasts (skin biopsy, easily accessible) will show: (1) reduced glycogen content compared to controls (PAS staining quantification, biochemical glycogen assay); (2) impaired glycogen synthase or branching enzyme activity; (3) reduced collagen production in culture (hydroxyproline assay) that normalizes when supplemented with pyruvate or other ATP precursors; (4) abnormal collagen crosslinking patterns (enzymatic vs. non-enzymatic crosslinks).

*Limitations.* This is a novel, speculative connection with no direct ME/CFS data. Fibroblast glycogen measurement is not routine; methodology would need development. The metabolic trap hypothesis itself remains untested. Alternative explanations for connective tissue abnormalities in ME/CFS include genetic collagen defects (hEDS) or immune-mediated ECM degradation.
] <spec:fibroblast-glycogen-ecm>

#speculation(title: [cGAS-STING Chronicity Loop: NAD Depletion-Driven mtDNA Release])[
*Certainty: 0.40.* NAD depletion is documented in ME/CFS (Chapter @ch:energy-metabolism, Section @sec:step6-cofactors). Reduced NAD impairs mitophagy via SIRT1-PINK1/Parkin deacetylation failure, leading to mitochondrial depolarization and mtDNA release into the cytosol. Cytosolic mtDNA activates cGAS-STING, producing type I interferons (IFN-$beta$). IFN-$beta$ induces indoleamine 2,3-dioxygenase (IDO), which consumes tryptophan along the kynurenine pathway, further depleting NAD via nicotinamide phosphoribosyltransferase (NAMPT) upregulation — a futile compensatory loop that accelerates NAD consumption.

*Mechanism.* Step 1: NAD deficiency impairs SIRT3-mediated deacetylation of mitochondrial proteins, reducing complex I and complex III activity (documented in ME/CFS muscle). Step 2: Impaired electron transport chain increases ROS and triggers mitochondrial permeability transition pore (mPTP) opening. Step 3: mPTP opening releases fragmented mtDNA into the cytosol. Step 4: Cytosolic mtDNA engages cGAS, producing cGAMP which activates STING. Step 5: STING-TBK1-IRF3 signaling drives IFN-$beta$ transcription. Step 6: IFN-$beta$ upregulates IDO, shunting tryptophan to kynurenine and reducing NAD salvage synthesis. Step 7: NAD drops further, worsening mitophagy failure — loop closes.

*ME/CFS context.* Elevated IFN signatures are documented in ME/CFS (Chapter @ch:immune-dysfunction). Kynurenine pathway activation is reported. NAD levels are low in ME/CFS muscle and PBMCs. cGAS-STING activation has been demonstrated in post-COVID syndromes. The loop explains chronicity: once initiated, it is self-sustaining because each arm (NAD deficit, mtDNA release, IFN production, IDO activation) reinforces the next.

*Falsifiable predictions.* (1) ME/CFS PBMCs will show elevated cytosolic mtDNA levels (quantitative PCR for mtDNA-encoded genes in cytosolic fractions). (2) STING phosphorylation (p-STING Ser366) will be elevated in ME/CFS immune cells and correlate with NAD/NADH ratio. (3) IDO activity (kynurenine/tryptophan ratio) will correlate inversely with cellular NAD levels. (4) Pharmacological STING inhibition (H-151) in ME/CFS PBMC cultures will reduce IFN-$beta$ production and partially restore NAD levels within 48 h.

*Limitations.* The complete loop has not been demonstrated in any single ME/CFS study — the components are assembled from separate studies across different tissues and cohorts. cGAS-STING in ME/CFS has not been directly measured. mtDNA in cytosol is technically challenging to quantify without artefacts from cell fractionation. The loop may operate in some tissues (immune cells) but not others (muscle, neurons), with measurement compartment determining detectability.
] <spec:cgast-sting-loop>

#speculation(title: [Iron Dysregulation: Hepcidin Setpoint Shift and the Hypoferremia-Ferroptosis Trap])[
*Certainty: 0.50.* Chronic inflammation in ME/CFS raises hepcidin via IL-6-STAT3 signaling (documented elevated IL-6, Chapter @ch:immune-dysfunction), shifting the iron homeostasis setpoint toward functional iron deficiency. This produces a hypoferremic state that limits erythropoiesis (contributing to anemia of chronic disease) and impairs mitochondrial respiration (iron-sulfur cluster biogenesis for complexes I–III), while simultaneously trapping iron in macrophages and hepatocytes. Macrophage iron retention promotes intracellular oxidative stress and inflammatory polarization (M1 skewing), creating a two-compartment problem: insufficient iron for energy metabolism in muscle and brain, excessive iron driving oxidative damage in immune cells.

*Mechanism.* IL-6 induces hepcidin transcription via STAT3 binding to the hepcidin (HAMP) promoter. Elevated hepcidin binds ferroportin (FPN1) on enterocytes, macrophages, and hepatocytes, triggering its internalization and degradation. Enterocyte FPN degradation blocks dietary iron absorption. Macrophage FPN degradation traps recycled iron from senescent RBCs inside the phagolysosome. The resulting low serum iron (hypoferremia) starves muscle mitochondria of iron-sulfur cluster substrates (reduced aconitase activity, complex I/II/III dysfunction — documented in ME/CFS). Simultaneously, macrophage iron overload drives Fenton chemistry, producing hydroxyl radicals that oxidize membrane lipids → ferroptosis in iron-loaded cells. Ferroptotic cell death releases DAMPs (HMGB1, mtDNA) that amplify inflammation @Ibrahim2026HMGB1Neuroinflammation, further raising IL-6 and hepcidin — a self-sustaining iron trap.

*Bridge to ferroptosis.* The hypoferremia-ferroptosis trap connects two previously separate observations in ME/CFS: (1) functional iron deficiency (low ferritin in some, elevated soluble transferrin receptor indicating cellular iron need) and (2) oxidative stress markers (elevated malondialdehyde, F2-isoprostanes, 4-HNE). If iron is sequestered in macrophages while muscles are iron-starved, serum markers would paradoxically show low iron availability while tissue markers show iron-driven oxidative damage — reconciling apparently contradictory findings.

*Falsifiable predictions.* (1) ME/CFS patients will show elevated hepcidin (serum ELISA) correlating with IL-6 levels and inversely with serum iron and transferrin saturation. (2) Macrophages isolated from ME/CFS PBMCs will show elevated intracellular iron (ferritin heavy chain, labile iron pool by calcein-AM fluorescence) and increased lipid peroxidation (C11-BODIPY) compared to controls. (3) Muscle biopsies from ME/CFS patients will show reduced iron-sulfur cluster proteins (aconitase, SDHB) despite normal total muscle iron — indicating functional iron deficiency within the myocyte despite adequate total tissue iron. (4) In vitro, IL-6 treatment of healthy macrophages induces hepcidin-dependent iron retention; ME/CFS patient macrophages will show blunted ferroportin expression and heightened sensitivity to ferroptosis inducers (erastin, RSL3).

*Limitations.* Hepcidin has not been systematically measured in ME/CFS. Macrophage iron content has not been assessed. Ferroptosis markers in ME/CFS tissue are absent. The model predicts a compartment-specific iron paradox that may not be detectable in standard serum iron panels, explaining why routine iron studies in ME/CFS are often normal. The prediction that muscle is iron-deficient while macrophages are iron-loaded requires direct tissue measurement, which is invasive.
] <spec:iron-dysregulation-hepcidin-ferroptosis>
