#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Interoceptive Accuracy-Sensibility Dissociation in ME/CFS])[
ME/CFS patients are predicted to exhibit a characteristic interoceptive dissociation: elevated _interoceptive sensibility_ (heightened subjective body awareness, hypervigilance to internal signals) alongside reduced _interoceptive accuracy_ (impaired objective performance on heartbeat detection and other interoceptive tasks) and reduced _interoceptive awareness_ (poor metacognitive insight into their interoceptive performance). This dissociation, operationalized by the Garfinkel et al.\ tripartite interoceptive framework @Garfinkel2015interoceptionAccuracy, would distinguish ME/CFS from: (a) healthy controls (normal accuracy, low-normal sensibility), (b) anxiety disorders (elevated accuracy, elevated sensibility, with high awareness), and (c) developmental ASD (elevated accuracy, low or high sensibility, variable awareness). The ME/CFS-specific pattern—high sensibility, low accuracy, low awareness (metacognitive)—is computationally consistent with the predictive coding model: when interoceptive afferent signals are corrupted (by cytokine effects at vagal paraganglia, autonomic instability, metabolic signal noise), the brain increases precision-weighting on interoceptive channels (→ high sensibility, hypervigilance) but cannot resolve prediction errors (→ low accuracy, low awareness). (Origin: brainstorm)

The Quadt, Critchley, and Garfinkel (2018) comprehensive review establishes interoception as a transdiagnostic mechanism across psychiatric and neurological conditions, with the insula as the core interoceptive hub @QuadtCritchleyGarfinkel2018interoception. The theoretical infrastructure for applying this framework to ME/CFS therefore exists; the gap is empirical.

The interoceptive accuracy-sensibility dissociation has been partially demonstrated in fibromyalgia—a condition highly comorbid with ME/CFS—where Valenzuela-Moguillansky et al.\ (2017) found elevated body attention (sensibility) alongside decreased tactile localization accuracy (body representation accuracy), providing indirect evidence for a similar dissociation in ME/CFS @ValenzuelaMoguillansky2017bodyAwarenessFM.

(Certainty: 0.45. The Garfinkel tripartite framework is well-replicated in general and clinical populations, and the FM evidence provides indirect support, but the specific ME/CFS pattern has NOT been directly tested. No Garfinkel-validated heartbeat detection study with TAS-20 (alexithymia) and MAIA (sensibility) has been conducted in an ME/CFS population. *Falsification condition:* If a heartbeat detection task (HBDT) with confidence ratings reveals that ME/CFS patients have normal or elevated accuracy alongside elevated sensibility—i.e., true interoceptive hyper-acuity rather than dissociation—the corrupted-afferent model is not supported. If accuracy and sensibility are both normal in ME/CFS, the predictive coding model lacks psychophysical support altogether. *Pre-registration target:* This is one of the most tractable testable predictions from the interoceptive model — a single-session psychophysics study could resolve it.)
] <hyp:ch15-interoceptive-dissociation>
