#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Feeling More but Sensing Less — The Interoceptive Gap])[
ME/CFS patients are predicted to show a specific pattern: they are intensely aware of their body (every heartbeat, every gut sensation feels amplified and hard to ignore), yet when tested objectively—for example, counting their own heartbeats without touching their pulse—they perform worse than healthy people. They _feel_ more body sensation but _perceive_ it less accurately.

This dissociation is defined by the Garfinkel et al.\ (2015) framework, which splits body-sensing into three layers @Garfinkel2015interoceptionAccuracy: (1) interoceptive accuracy (how well you actually detect internal signals), (2) interoceptive sensibility (how much body sensation you subjectively feel), and (3) interoceptive awareness (how accurately you know whether you're good or bad at detecting signals—metacognitive insight). The predicted ME/CFS pattern—high sensibility, low accuracy, low metacognitive awareness—distinguishes it from anxiety (where accuracy tends to be high alongside elevated sensibility) and from healthy people (low-normal sensibility, high accuracy).

Why would this happen? When inflammatory signals traveling up the vagus nerve corrupt the body's data stream, the brain compensates by turning up the volume on all body signals—producing hypervigilance—but the underlying data is too noisy to resolve, so accuracy and metacognitive insight remain poor. The review by Quadt, Critchley, and Garfinkel (2018) established that interoceptive dysfunction appears across many conditions, with the insula as the central hub @QuadtCritchleyGarfinkel2018interoception.

Partial evidence exists from fibromyalgia, a condition that frequently overlaps with ME/CFS: Valenzuela-Moguillansky et al.\ (2017) found that fibromyalgia patients show elevated body attention alongside decreased accuracy on body-localization tasks—the same dissociation pattern, but measured through touch rather than internal body signals @ValenzuelaMoguillansky2017bodyAwarenessFM. (Origin: brainstorm)

(Certainty: 0.45. The Garfinkel tripartite framework is well-validated in healthy and clinical populations, and the fibromyalgia data provides indirect support, but no study has directly measured this dissociation in ME/CFS using the standard heartbeat detection protocol combined with the TAS-20 alexithymia scale and the MAIA sensibility scale. *Falsification condition:* If ME/CFS patients show normal or elevated accuracy alongside elevated sensibility on the heartbeat task—meaning they really are hyper-accurate, not just hyper-aware—then the corrupted-signal model is wrong. If both accuracy and sensibility are normal, the entire interoceptive framework lacks psychophysical evidence in ME/CFS. *Note:* This is one of the most immediately testable predictions in the paper—a single-session study could resolve it.)
] <hyp:ch15-interoceptive-dissociation>
