#import "../../../../shared/environments.typ": *

=== Virtual Clinical Trials

The model enables in silico clinical trials: simulating the response of a virtual patient population to a candidate treatment. A virtual population is generated by sampling parameter vectors from distributions representing the known heterogeneity of ME/CFS. Each virtual patient is simulated under treatment and control conditions, generating predicted effect sizes, responder rates, and optimal trial designs (duration, endpoints, enrichment criteria).

Virtual trials are particularly valuable for ME/CFS because:

- Real clinical trials are expensive and slow to recruit
- The heterogeneity of ME/CFS means that average treatment effects may be small even when a subgroup responds dramatically---virtual trials can identify the responding subgroup and design enrichment strategies
- Ethical constraints limit the types of perturbation studies possible in patients---the model permits simulation of interventions that would be impractical to test in humans

#include "open-questions/digital-twins-for-mecfs.typ"

