#import "../../../../../shared/environments.typ": *

#limitation(title: [BioMapAI's Headline Accuracy Includes a Symptom-Circularity Component])[
The headline classification performance of BioMapAI (AUC=0.99) requires careful interpretation. The model's twelve output heads are the twelve scored clinical symptoms — the same symptoms a clinician uses to establish the ME/CFS diagnosis. A model trained to reconstruct the very symptom set that defines the diagnosis will trivially separate cases from controls if it learns those symptom patterns, independent of any underlying biology. This is a partial circularity: the symptom-based head is partly restating the diagnostic criteria.

The honest test of biological signal is performance on the non-symptom omics layers — the metabolome, microbiome, and immune profiles — both alone and in the integrated model, plus external-cohort validation on omics data (Guo, Raijmakers microbiome; Germain, Che metabolome). We cannot quote a single pure-omics or external-cohort AUC here because our sources do not report one; that absence is itself a methodological gap — the chapter leans on an "omics signature" whose numeric strength the paper does not disclose, so its magnitude is undetermined rather than "real but modest." Two cautions follow. First, the study's PCoA shows no single omics layer separates patients from controls, which is consistent with the signal being distributed — but it does not quantify how much of the integrated performance reflects genuine cross-layer biology versus the technical gain any multi-feature ensemble gets from additive weak main effects (see @hyp:coordination-signature-defines-mecfs). Second, it is possible the omics-only integrated signal is substantially weaker than the headline; the paper does not establish otherwise.

A second, related limitation: the symptom-specific biomarker attributions (which feature drives which symptom) were computed on the full dataset and explicitly *not validated on held-out data* in the paper. They are exploratory, not established.

Certainty: n/a — methodological caveat. Severity applicability: n/a — model-design concern.

*Consequence:* Do not quote "AUC 0.99" as if it were a blood test. The defensible content is the negative result that no single omics layer separates patients from controls, the external-cohort validation, and the explainable connectivity map as a *hypothesis generator* — but the 0.99 figure is inflated by the model learning the diagnostic symptoms it was built around, the pure-omics integrated strength is not reported, and the connectivity-map attributions were not held-out validated. Readers and clinicians should rely on independently-replicated non-symptom results, which are not yet established.
] <lim:biomapai-symptom-circularity>
