#import "../../../shared/environments.typ": *

#speculation(title: [Oral Micronized Progesterone as Immunological and Neurosteroid Bridge Therapy in ME/CFS])[
If the ~30% symptom improvement during pregnancy in ME/CFS @Schacterle2004pregnancy reflects progesterone-mediated immune modulation, oral micronized progesterone (100–200 mg/day; Prometrium or Utrogestan) may partially replicate this effect outside pregnancy via two pharmacologically validated pathways. (Certainty: 0.25 — complete evidence chain is indirect; no ME/CFS trial data exist; not replicated in this population.)

*Mechanism 1 — Progesterone-Induced Blocking Factor (PIBF).* Progesterone induces PIBF, which mediates a Th2 cytokine shift (elevated IL-4, IL-10) and inhibits NK cell degranulation @SzekeresBartho2019progestogens @Raghupathy2009PIBF. ME/CFS features elevated NK cytotoxicity and Th1-skewed immune responses; PIBF-driven reversal could reduce immune-driven symptom burden. Critical gap: PIBF induction was absent in non-pregnant controls in one in vitro study @Raghupathy2009PIBF — whether ME/CFS patients outside pregnancy produce sufficient PIBF in response to exogenous progesterone is unknown.

*Mechanism 2 — Allopregnanolone.* Oral micronized progesterone is converted to allopregnanolone (a GABA-A positive allosteric modulator) via first-pass hepatic metabolism @AndreenBackstrom2006pharmacokinetics. Allopregnanolone suppresses CRH/ACTH secretion, improves slow-wave sleep architecture, and has anti-inflammatory properties @MeltzerBrodyKanes2020allopregnanolone. Proof of concept: brexanolone (IV synthetic allopregnanolone) produced clinically significant, rapid effects in postpartum depression in phase 3 RCTs ($n = 246$) @MeltzerBrody2018brexanolone, validating the GABA-A pathway. ME/CFS features HPA hypocortisolism, non-restorative sleep, and autonomic dysregulation—all of which allopregnanolone physiologically addresses.

*Pharmacological distinctions critical to the hypothesis.* Micronized progesterone specifically is required: medroxyprogesterone acetate (MPA) and most synthetic progestins do not induce PIBF @SzekeresBartho2019progestogens. The oral route is required for allopregnanolone production via first-pass metabolism—vaginal progesterone (commonly used in IVF) bypasses this conversion @AndreenBackstrom2006pharmacokinetics. Cyclic dosing (e.g., 2–3 weeks on, 1 week off) is pharmacologically preferable to continuous dosing, which may downregulate progesterone receptors @Zhao2012continuousProgesterone.

*Evidence base.* ME/CFS is not a progesterone-deficiency state: two independent cross-sectional studies found normal baseline progesterone in CFS cohorts ($n = 176$ @Gur2004fibromyalgiaHormones; $n = 43$ @Cevik2004CFShormones). The rationale is pharmacological—supraphysiological concentrations producing immune and neurosteroid effects—not hormonal replacement.

*Testable Predictions.*
- Oral (not vaginal) micronized progesterone 200 mg/day will increase allopregnanolone to luteal-phase equivalent concentrations and improve PSQI sleep quality in ME/CFS patients in a crossover RCT
- Responders will be enriched in the autoimmune-dominant phenotype (anti-β2-adrenoceptor or anti-M3-AChR positive), consistent with the proposed subtype-response mapping (@spec:pregnancy-subtype-stratifier)
- If serum PIBF does not rise after oral progesterone in ME/CFS patients, the immune route is not operative and the allopregnanolone/neurosteroid pathway remains the sole candidate mechanism

*Safety — not a benign intervention.* Allopregnanolone shows a biphasic dose-response at GABA-A receptors: low concentrations paradoxically worsen anxiety and mood instability, particularly in women with premenstrual dysphoric disorder sensitivity @AndreenBackstrom2009negMood. Titration must start low (100 mg) with monitoring for paradoxical worsening. Progesterone causes sedation (often favorable in ME/CFS but a concern for function) and breast tenderness. Patients on fludrocortisone require monitoring for aldosterone receptor cross-reactivity. Contraindicated in active thromboembolic disease, hormone-sensitive cancers, and unexplained vaginal bleeding.

*Limitations.* The brexanolone proof of concept is IV, acute-infusion, and in postpartum depression—not oral, chronic dosing, and not ME/CFS. The PIBF mechanism may not operate outside the pregnancy immune context. No long-term safety data in immune-dysregulated populations exist. This is a research-stage hypothesis; clinical use without trial evidence is not warranted.
] <spec:micronized-progesterone-bridge>
