#import "../../../shared/environments.typ": *

== Buspirone Challenge Replication: A Modern Test of the Exaggerated Prolactin Response
<sec:buspirone-challenge-replication>

The historical literature reviewed in Chapter @ch:endocrine (@sec:prolactin-buspirone) describes a replicated but abandoned finding: ME/CFS patients show an exaggerated prolactin response to an oral buspirone challenge despite normal baseline prolactin. Because this line was never re-tested with modern diagnostic criteria — and because the ME/CFS-versus-depression comparison has never been performed with buspirone at all — an adequately powered replication is a high-value, low-cost next study: feasible for an interested research physician with access to an endocrine clinic and a handful of otherwise-standard blood draws.

#prediction(title: [Reproducible Prolactin AUC Gradient: ME/CFS > Healthy > Depression])[
The replication is designed to test the core, falsifiable prediction that motivated this topic (@pred:prolactin-buspirone-replication @cf:prolactin-buspirone-exaggerated): under a standardized oral buspirone challenge, the prolactin area-under-curve (AUC) will be significantly larger in ME/CFS than in major depression, with healthy controls intermediate, at normal baseline prolactin. This ME/CFS-versus-depression contrast has never been measured with buspirone — the historical depression data come from a d-fenfluramine probe — so the prediction extends, rather than merely re-tests, the historical finding. It is falsified if a modern IOM-criteria ME/CFS cohort shows no difference from depression or from healthy controls, if the historical effect disappears once medication washout, fasting, time-of-day, sex, and menstrual phase are controlled, or if it proves to be an epiphenomenon of differential nausea after adjusting for emetic symptoms.

*Consequence:* If confirmed, this one cheap study would establish a candidate biological test that distinguishes ME/CFS from depression and justify the follow-up mechanistic work — though an independent-group replication would still be required before any clinical use; if it fails, it would retire a notable but unverified lead.
] <pred:buspirone-challenge-replication>

=== Rationale

The finding has three properties that make it unusually worth replicating: it was reproduced by an independent group (Bakheit 1992 @Bakheit1992Buspirone; Sharpe 1996 @Sharpe1996Buspirone from separate research teams), a related serotonergic-probe study found prolactin responses *contrasting* across diagnoses — lowest in depression, highest in CFS (@Cleare1995DepressionCFS; from an author cluster overlapping the fenfluramine-null group, so not independent corroborations of each other) — and, per secondary accounts of the era, the finding was not anticipated in advance, which reduces (though cannot eliminate) concern that it is a confirmatory-bias artifact. Yet every historical study was small (n = 11–20 per arm), used Fukuda or pre-Fukuda criteria, and the line was abandoned around 2001. No post-2010 replication exists. The null fenfluramine results @Yatham1995Fenfluramine @Bearn1995Fenfluramine argue against a purely global serotonergic mechanism and constrain the signal toward pathways buspirone engages but fenfluramine does not — without localizing it (@oq:prolactin-buspirone-mechanism).

=== Design Overview

    - *Design:*: Cross-sectional neuroendocrine challenge, three arms — ME/CFS (IOM/CCC criteria), major depression (DSM-5), healthy controls.
    - *Intervention:*: Single oral buspirone dose (0.5 mg/kg, as in the Sharpe protocol @Sharpe1996Buspirone) administered on a standardized morning after overnight fasting; serial plasma prolactin sampling (baseline and post-dose timepoints to capture AUC).
    - *Sample:*: n ≈ 25–30 per arm. The historical effect was large but its estimate is highly uncertain (small n, single era, nausea-confound risk), so the power calculation must use conservative effect-size assumptions and pre-specify whether a subset-only effect would be interpretable.
    - *Confounder control:*: same hour of day, overnight fasting, ≥4–6 week medication washout, sex- and menstrual-phase-matched analysis (men and women analyzed separately; premenopausal women tested in the same phase).
    - *Co-primary measures:*: prolactin AUC and peak; secondary: baseline prolactin, cortisol (since cortisol modulates the buspirone-prolactin response @Dinan2001Buspirone), growth hormone, and *rated nausea/emetic symptoms at each timepoint* — so the hormonal signal can be tested against, and adjusted for, differential drug tolerability (the key unexamined confound; Sharpe's CFS group reported more nausea @Sharpe1996Buspirone).
    - *Feasibility:*: relatively quick and cheap — one visit, standard endocrine assays, a drug already in clinical use; within scope for a research physician without a large grant. The challenge is acutely unpleasant for some participants (nausea in the historical studies), so observation and participant-support provisions belong in the protocol.

=== If Confirmed

A positive replication would (a) establish a candidate objective challenge-test discriminator between ME/CFS and depression — with the nausea-adjusted analysis showing the signal is hormonal rather than a tolerability artifact — (b) revive the mechanistic question of whether the exaggerated response reflects reduced dopaminergic inhibitory tone, serotonergic or estradiol modulation, or none of these (@oq:prolactin-buspirone-mechanism), and (c) justify the follow-up mechanistic and biomarker work, after independent-group replication. It would also argue for sex-stratifying the test, potentially connecting to the ~80% female predominance (@spec:fra-estradiol-prolactin-link).

=== If Null

A null result — no difference between ME/CFS and depression or healthy controls once modern criteria and confounders are controlled — would retire a notable but abandoned line and prevent decades more of interest in a lead that may reflect pre-Fukuda diagnostic heterogeneity, uncontrolled confounders, an era-specific effect, or differential nausea. Either outcome is scientifically informative.

=== Comparator Probes to Isolate the Dopamine Component

Because buspirone is multi-receptor (5-HT1A agonist + D2 blocker), a *pure* D2-antagonist comparator (e.g., metoclopramide or domperidone, which block D2 without meaningful 5-HT1A agonism) and a *pure* 5-HT1A comparator would help localize whether an exaggerated response traces to the dopaminergic or serotonergic component (@spec:prolactin-dopamine-window @spec:prolactin-msn-link). Haloperidol has also been suggested as a central D2-antagonist probe, but it is a first-generation antipsychotic with QT-prolongation, extrapyramidal, and neuroleptic-malignant-syndrome risk — a research-protocol option only under specialist supervision, never for off-label or self-initiated use. This is a diagnostic/research-design refinement, not a treatment: these agents would be used as single controlled challenge probes by a research physician. *Interaction/safety note:* all comparator probes named here — metoclopramide, domperidone, and haloperidol — are proposed strictly for a supervised single-dose challenge in a research protocol; none is recommended as an ME/CFS treatment. They carry their own acute hazards (QT prolongation with domperidone and haloperidol; extrapyramidal effects and hypotension) that are of particular concern in a population with documented dysautonomia, and their interaction profile with common ME/CFS co-prescriptions has not been checked in this integration — any clinical use requires prior specialist review of drug interactions and contraindications. (Origin: brainstorm ideas 3.1/3.2 — metoclopramide/domperidone and haloperidol as D2-antagonist probes.)

=== Limitations

The replication tests a small historical effect from a single diagnostic era; a null result cannot fully exclude a real effect present only in a subset (e.g., a particular severity or onset subgroup — the historical cohorts were ambulatory and not severity-stratified, so nothing is known about applicability to severe/very-severe patients, for whom a fasting, serial-venipuncture challenge is itself a significant burden), and a positive result would require replication by an independent group before clinical use. Buspirone is multi-receptor, so the probe does not isolate a single pathway, and the peripheral prolactin read-out is an indirect measure of one dopaminergic subsystem only.
