#import "../../../../shared/environments.typ": *

==== Cascade: Microglial priming → four-region neuroinflammatory consequences

*Cascade:*
- Triggering infection → microglial priming (TLR4, DAMPs, epigenetic marks) → primed microglia
- Chronic low-grade IL-1β, TNF-α, PGE2 → four downstream regions:
- (a) Hypothalamic → orexin neuron suppression → fatigue, unrefreshing sleep
- (b) Basal ganglia → DA synthesis (BH4-dependent TH) and VMAT2 impairment → anhedonia, bradykinesia
- (c) Brainstem → NTS/VLM/DMV dysfunction → autonomic instability, reduced HRV
- (d) Prefrontal cortex → impaired working memory, executive dysfunction, brain fog

*Step K1:* Microglial TLR4/P2X7/DAMP activation (the priming step)
- *Mechanism:* Resting microglia become "primed" when TLR4 (recognizing LPS, DAMPs like HMGB1, heat shock proteins, fibronectin fragments), P2X7 (ATP released from damaged cells), and C5aR (complement activation) are chronically stimulated. Primed microglia do not produce full-blown inflammation — they produce a low-grade, sustained cytokine release (IL-1β, TNF-α) that alters neuronal function without causing overt tissue damage. This is "neuroinflammation without neurodegeneration" — the pattern seen on TSPO-PET in ME/CFS.
- *Intercept:* LDN (low-dose naltrexone, 0.5--4.5 mg; TLR4 antagonist, opioid receptor antagonist) — TLR4 antagonist, blocks the primary activation pathway for danger-signal-driven microglial priming; Minocycline (50--100 mg BID; tetracycline antibiotic, microglial inhibitor at subantimicrobial dose) — inhibits microglial activation through non-TLR4 pathways (P2X7, C5aR, IFN-γR, and MMP-9 inhibition); PEA (palmitoylethanolamide, 300--1200 mg/day; PPAR-α agonist, endogenous fatty acid amide) — PPAR-α agonist, promotes microglial M2 (anti-inflammatory) phenotype; Luteolin + quercetin (flavonoids; mast cell and microglial inhibitors, NF-κB/AP-1 blockade) — inhibit mast cell and microglial activation through multiple pathways (NF-κB, AP-1). Ibudilast (PDE4 inhibitor; microglial TNF-α/IL-1β suppression) — suppresses microglial TNF-α and IL-1β production; available in Japan and Australia.
#finding(claim: [TLR4-mediated microglial activation is rate-limiting], explanation: [LDN response onset latency distinguishes mechanism: within 48 hours suggests TRPM3 ion channel (non-microglial), while 2-4 weeks suggests TLR4 antagonist effect requiring gene expression changes for microglial phenotype shift. Placebo and expectation effects also onset within the 48h window, limiting specificity.], certainty: [Low], level: [Partial root cause])
#finding(claim: [TLR4 is one of multiple microglial activation pathways], explanation: [LDN produces partial response (~30% improvement at 4 weeks then plateaus). Remaining activation through P2X7 (ATP from damaged mitochondria), C5aR (complement), or IFN-γR (T-cell driven). Adding minocycline can probe non-TLR4 pathways. The sum of LDN + minocycline improvement estimates total neuroinflammatory contribution.], certainty: [Medium], level: [Partial root cause])
#finding(claim: [Microglial activation is through non-TLR4 pathways (P2X7, C5aR, IFN-γR)], explanation: [Minocycline works but LDN does not, ruling out the danger-signal DAMP/TLR4 pathway as the driver. Implicates complement (AAb + complement activation on microglia), ATP from mitochondrial damage (metabolic pathology driving neuroinflammation), or T-cell-driven microglial activation (IFN-γ from autoreactive T cells).], certainty: [Medium], level: [Partial root cause])
#finding(claim: [Microglial activation is absent, epigenetically locked, or not rate-limiting], explanation: [Neither LDN nor minocycline works. Possible explanations: (a) neuroinflammation is astrocytic, not microglial; (b) microglial population is epigenetically locked in primed state requiring HDAC inhibitor; (c) neuroinflammation is in a brain region inaccessible to oral LDN/minocycline (brainstem behind intact BBB); or (d) symptoms are driven by non-inflammatory pathology (metabolic, channelopathy, structural).], certainty: [Low], level: [Partial root cause])
#finding(claim: [Microglial phenotype dysregulation is rate-limiting], explanation: [PEA works where LDN/minocycline do not. The microglia are not hyper-activated — they are stuck in the wrong phenotype. PEA's PPAR-α agonism shifts them from pro-inflammatory M1 (producing IL-1β, TNF-α) to anti-inflammatory M2 (producing IL-10, TGF-β) without blocking activation pathways. This is a distinct pathology: phenotype dysregulation, not activation excess.], certainty: [Medium], level: [Partial root cause])

*Step K2a:* Hypothalamic inflammation → orexin neuron suppression
- *Mechanism:* The lateral hypothalamus contains orexin (hypocretin) neurons — the brain's primary wakefulness-promoting neurons. They project to the entire cortex, brainstem arousal centres (LC, raphe, TMN), and autonomic nuclei. Microglial release of IL-1β and TNF-α in the lateral hypothalamus directly suppresses orexin neuron firing and reduces orexin gene expression. The result: reduced wakefulness drive → fatigue, excessive daytime sleepiness, unrefreshing sleep (insufficient orexin to maintain consolidated wakefulness during the day, and insufficient orexin to suppress REM during sleep → REM intrusion into NREM).
- *Intercept:* OX2R agonists (danavorexton — intravenous, TAK-861/oveporexton — oral; selective orexin OX2 receptor agonists, narcolepsy trials) — directly stimulate postsynaptic orexin OX2 receptors, bypassing orexin neuron suppression entirely; Pitolisant (H3 inverse agonist, 4.5--36 mg/day; histaminergic arousal enhancer) — increases histamine release from tuberomammillary nucleus (TMN), which is one synapse downstream of orexin neurons → partial compensation for orexin deficiency through the histaminergic arousal pathway; Modafinil/Armodafinil (DAT inhibitor; wakefulness-promoting agent) — increases synaptic dopamine, which stimulates orexin neurons through D1/D2 receptors on orexin cells; Solriamfetol (DNRI; dopamine-norepinephrine reuptake inhibitor) — increases NE and DA, indirectly activating orexin and histaminergic arousal pathways.
#finding(claim: [Orexin neuron suppression is the rate-limiting bottleneck for wakefulness], explanation: [OX2R agonist response confirms orexin neuron cell bodies are intact but tonically suppressed by hypothalamic microglial inflammation. Receptors intact — deficiency is functional (cytokine-suppression), not structural (neuron loss, as in narcolepsy type 1). Treat neuroinflammation (LDN, minocycline) to restore endogenous orexin while using OX2R agonists symptomatically.], certainty: [Low], level: [Symptom management])
#finding(claim: [Arousal deficit is histaminergic, not dopaminergic], explanation: [Pitolisant works but modafinil does not. Pitolisant releases endogenous histamine — the histaminergic system is intact but suppressed. Modafinil's DAT block fails because DA cannot sufficiently activate the hypothalamic arousal system when histaminergic tone is the bottleneck. Consistent with orexin→histamine pathway: orexin suppresses histamine release; restoring histamine compensates; increasing DA does not.], certainty: [Medium], level: [Partial root cause])
#finding(claim: [Orexin/histamine axis is hypersensitive, not suppressed], explanation: [Modafinil works but causes insomnia — even small DA increases fully activate the arousal axis. The orexin neurons are primed to over-respond to any excitatory input. Consistent with microglial activation in VLPO (sleep-promoting nucleus), not lateral hypothalamus. LDN should still work but pitolisant may worsen insomnia.], certainty: [Low], level: [Symptom management])
#finding(claim: [Orexin neurons are structurally lost, receptors are desensitized, or fatigue is metabolic], explanation: [All wakefulness-promoting agents fail. Possible explanations: (a) orexin neurons structurally lost — CSF orexin-A would confirm, distinguishing functional suppression (LDN-responsive) from neuron loss (irreversible); (b) postsynaptic orexin and histamine receptors desensitized from chronic overstimulation; (c) fatigue is metabolic (insufficient ATP to sustain wakefulness regardless of arousal signal), not neuroinflammatory.], certainty: [Low], level: [Partial root cause])

*Step K2b:* Basal ganglia inflammation → dopamine synthesis/transport impairment
- *Mechanism:* The substantia nigra pars compacta (SNc) and ventral tegmental area (VTA) contain dopamine neurons. Microglial release of IL-1β and TNF-α in the striatum and midbrain: (a) depletes tetrahydrobiopterin (BH4) — the essential cofactor for tyrosine hydroxylase, the rate-limiting enzyme in dopamine synthesis; (b) downregulates VMAT2 — the vesicular transporter that packages dopamine into synaptic vesicles for release; (c) promotes oxidative stress in dopamine neurons (dopamine auto-oxidation produces quinones and ROS, and dopamine neurons have low antioxidant capacity — inflammation tips them over the edge). The result: reduced dopamine synthesis AND reduced dopamine storage → dopamine deficiency → anhedonia, reduced motivation, effort-allocation deficit (the "I want to do it but I can't make myself" feeling), and cognitive slowing.
- *Intercept:* Aripiprazole (low-dose, 0.25--2 mg; D2/D3 partial agonist, atypical antipsychotic at microdose) — D2/D3 partial agonist, provides tonic low-level dopamine receptor stimulation in a dopamine-deficient system; Methylphenidate (DAT/NET inhibitor, 5--20 mg; NDRI) — blocks dopamine reuptake, increasing synaptic DA concentration; Bupropion (DNRI + anti-inflammatory, 150--300 mg; dopamine-norepinephrine reuptake inhibitor) — increases synaptic DA and NE while reducing TNF-α production; Amantadine (100--200 mg; dopamine releaser, NMDA antagonist) — increases dopamine release from remaining vesicles and has NMDA antagonist properties; Pramipexole (D2/D3 agonist, 0.125--0.5 mg; direct dopamine receptor agonist) — direct D2/D3 receptor agonism, bypassing dopamine synthesis and release entirely; Rasagiline/Selegiline (MAO-B inhibitor, 0.5--1 mg; dopamine degradation blocker) — prevents dopamine degradation, increasing synaptic DA half-life.
#finding(claim: [Dopaminergic dysfunction in basal ganglia/PFC is rate-limiting], explanation: [Aripiprazole response confirms lesion at D2/D3 receptor signaling, with dose-response slope mapping receptor sensitivity: 0.1 mg → catastrophic DA deficiency; 0.5 mg → severe; 2 mg → moderate; no response below 5 mg → mild or absent.], certainty: [Medium], level: [Partial root cause])
#finding(claim: [Dopamine signaling is not the rate-limiting bottleneck], explanation: [Aripiprazole does not work. Possible explanations: (a) noradrenergic system selectively deficient while dopamine preserved (DBH failure); (b) lesion upstream of dopamine — TPJ dysfunction impairs cortical effort-worth signal; (c) lesion below D2/D3 — VMAT2 terminal loss means dopamine cannot be packaged; (d) cognitive dysfunction is glutamatergic, cholinergic, or inflammatory. Pattern: aripiprazole null + guanfacine positive → PFC NE deficiency; aripiprazole null + memantine positive → glutamatergic dysfunction; aripiprazole null + LDN positive → inflammatory mechanism.], certainty: [Low], level: [Partial root cause])
- *Critical differential — VMAT2 deficiency:* If aripiprazole null BUT methylphenidate works → dopamine IS rate-limiting, but the deficit is presynaptic (DA reuptake is excessive, methylphenidate blocks it), not postsynaptic (D2/D3 receptors are functional, aripiprazole should work). If methylphenidate works within 30 minutes → DA reuptake is the problem — DA is released but cleared too fast. If methylphenidate works within hours but produces a severe crash → DA was released, reuptake was blocked, but the vesicular stores were depleted (consistent with VMAT2 deficiency — limited DA storage). If amphetamines produce a single-day benefit followed by weeks-long crash → VMAT2 terminal loss confirmed (amphetamine releases DA from vesicles through VMAT2; a patient with few vesicles depletes them all in one dose → crash that lasts until VMAT2 protein is resynthesized). Never re-challenge with amphetamines — the crash IS the VMAT2 diagnosis.

*Step K2c:* Brainstem inflammation → autonomic instability
- *Mechanism:* Microglial activation in the dorsolateral medulla (NTS, VLM, DMV) impairs the brainstem autonomic nuclei that regulate blood pressure, heart rate, and baroreflex gain. NTS is the primary baroreflex integration centre — inflammation here resets the baroreflex set-point. VLM is the primary sympathetic output nucleus — inflammation alters sympathetic tone. DMV contains vagal motor neurons — inflammation impairs vagal efferent output.
- *Probes integrated into @sec:brainstem-cascade.* Brainstem-specific microglial activation has distinct pharmacology: LDN may have limited brainstem access (BBB is tighter in medulla than cortex), minocycline has better brainstem penetration. LDN null + minocycline positive specifically suggests brainstem neuroinflammation without cortical neuroinflammation — the dissociation localizes the neuroinflammation to the brainstem.
- *Consequence:* If LDN improves cognitive symptoms (cortical) but not autonomic symptoms (brainstem) → the neuroinflammation is cortical, not brainstem — the brainstem is either intact or inaccessible to oral LDN. If minocycline improves autonomic symptoms where LDN does not → brainstem neuroinflammation confirmed; minocycline has superior brainstem penetration.

*Step K2d:* Prefrontal cortex inflammation → cognitive dysfunction
- *Mechanism:* The dorsolateral prefrontal cortex (dlPFC) is essential for working memory, executive function, and top-down regulation of pain and emotion. Microglial inflammation in dlPFC: (a) impairs pyramidal neuron dendritic spine density (synaptic loss); (b) reduces gap junction coupling between GABAergic interneurons (impaired gamma oscillations → working memory failure); (c) disrupts NE and DA signaling by downregulating postsynaptic receptors (α2A, D1) and increasing reuptake transporter expression. The result: brain fog — the sense that "thinking takes effort," working memory capacity is reduced, and cognitive tasks that were automatic become effortful.
- *Intercept:* Guanfacine (α2A-adrenergic receptor agonist, 0.5--2 mg; central sympatholytic, PFC connectivity enhancer) — directly stimulates postsynaptic α2A receptors on prefrontal pyramidal neurons, strengthening PFC network connectivity by closing HCN channels (hyperpolarization-activated cyclic nucleotide-gated channels — cation channels that open on hyperpolarization, producing a depolarizing current that weakens synaptic inputs; α2A activation closes them, strengthening PFC connectivity); Memantine (NMDA antagonist, 5--20 mg; glutamatergic modulator) — reduces glutamatergic excitotoxicity if quinolinic acid from kynurenine pathway is driving PFC NMDA overactivation; Low-dose amitriptyline (5--10 mg; tricyclic antidepressant at microdose, NMDA/NE/5-HT effects) — enhances NE and 5-HT, improves sleep architecture (slow-wave sleep enhancement → glymphatic clearance → reduced PFC inflammation); Donepezil (AChE inhibitor, 5--10 mg, CNS-penetrant unlike pyridostigmine; central acetylcholinesterase inhibitor) — enhances cholinergic transmission in basal forebrain → PFC projection, improving attention and working memory in cholinergic-deficient states.
#finding(claim: [PFC noradrenergic deficit is the cognitive bottleneck], explanation: [Guanfacine response confirms PFC circuits are intact (pyramidal neurons and synaptic inputs present) but not receiving adequate NE tone. The postsynaptic machinery (α2A receptors, HCN channels, cAMP signaling) is functional. Neuroinflammation has reduced NE signaling but left the postsynaptic apparatus responsive.], certainty: [Medium], level: [Partial root cause])
#finding(claim: [PFC NE deficit is presynaptic], explanation: [Guanfacine works but atomoxetine does not — PFC α2A receptors are intact and responsive but endogenous NE cannot reach them at adequate concentration. Confirms the NE deficit is presynaptic: either synthesis failure or excessive reuptake that atomoxetine at standard doses cannot overcome.], certainty: [Medium], level: [Partial root cause])
#finding(claim: [PFC circuits are not noradrenergically responsive], explanation: [Guanfacine does not work. Either (a) α2A receptors downregulated from chronic inflammation; (b) PFC pyramidal neurons have lost dendritic spines — structural synaptic loss; (c) cognitive deficit from white-matter disconnection; or (d) cognitive dysfunction is glutamatergic (memantine-responsive), cholinergic (donepezil-responsive), or inflammatory (LDN-responsive).], certainty: [Low], level: [Partial root cause])
#finding(claim: [Dual NE/glutamate PFC dysfunction — two-hit model], explanation: [Both guanfacine AND memantine work. One drug insufficient — both systems must be addressed simultaneously. If combined LDN + guanfacine + memantine produces response where any pair fails → triple pathology: neuroinflammation, NE deficiency, and glutamatergic excitotoxicity are all rate-limiting.], certainty: [Medium], level: [Partial root cause])
#finding(claim: [Cognitive dysfunction is cholinergic — basal forebrain pathology], explanation: [Donepezil works where guanfacine, memantine, and LDN do not. Basal forebrain cholinergic neurons projecting to PFC are impaired. Donepezil enhances ACh at both basal forebrain→PFC and brainstem→thalamus synapses. If donepezil produces GI side effects → gut cholinergic system is hypersensitive (Pattern 3).], certainty: [Medium], level: [Partial root cause])

*Consequence:* The microglial cascade is the most clinically accessible hypothesis in the chapter — LDN is already widely used, and its response pattern (onset latency, magnitude, which symptoms improve, which do not) provides an entry point into the four-arm diagnostic tree. LDN tells you microglia are primed (or not). The hypothalamic arm (orexin) is probed by pitolisant and modafinil. The basal ganglia arm (dopamine) is probed by aripiprazole, methylphenidate, and amphetamines. The brainstem arm (autonomic) is probed by pyridostigmine and midodrine — but brainstem specificity requires minocycline confirmation. The PFC arm (cognition) is probed by guanfacine, memantine, and donepezil. The pattern of which downstream arms respond — and which are silent — maps which brain regions bear the neuroinflammatory burden in that patient. A patient with LDN+, aripiprazole+, guanfacine null, pitolisant null → basal ganglia is the dominant neuroinflammatory site; PFC and hypothalamus are relatively spared. This regional specificity determines treatment: dopamine support (aripiprazole) for basal ganglia-dominant, wakefulness support (pitolisant/modafinil) for hypothalamus-dominant, cognitive support (guanfacine/memantine) for PFC-dominant, autonomic support (pyridostigmine/midodrine) for brainstem-dominant.
*Origin:* mechanistic-pathway-tracing.
