#import "../../../shared/environments.typ": *

#speculation(title: [Salivary Metabolomic Profiling Distinguishes ME/CFS Sleep Phenotypes])[
*Certainty: 0.20.* The primary evidence is Scholz et al.@Scholz2026SleepMetabolome (n=20 healthy males, 24h total sleep deprivation vs control, cross-over RCT, LC-HRMS, F0.5=0.90 with 12 molecular features). Oishi et al.@Oishi2025ChronicSleepSaliva provides secondary chronic sleep disorder evidence (n=100, PSQI-defined poor vs good sleep, 13 metabolites altered, 86.6% classification accuracy). No ME/CFS data exist. Directly relevant because unrefreshing sleep is reported by 91--100% of ME/CFS patients @Maksoud2021MECFSSleepReview.

The most informative finding from Scholz et al. is a negative one with direct ME/CFS implications: acute 24h sleep deprivation produced a robust metabolic fingerprint, but *four nights of chronic sleep restriction to 6h produced no exploitable metabolic changes*. ME/CFS unrefreshing sleep is a chronic state (months to decades), not acute deprivation. The Scholz chronic restriction result therefore constitutes the primary constraint: if mild chronic restriction produces no detectable signal after 4 days, ME/CFS chronic unrefreshing sleep (months to years) may produce *no peripheral metabolic signature* due to homeostatic adaptation. Oishi et al.'s chronic poor-sleep finding suggests that salivary metabolomic changes *can* occur in chronic conditions, but this evidence is cross-sectional, PSQI-based (not objective sleep measures), and derives from a general population without ME/CFS-like metabolic derangements. Oishi is supportive but non-definitive; it does not override the Scholz chronic null finding.

*Prediction.* If salivary metabolomic profiling is applied to ME/CFS patients versus healthy controls versus primary insomnia controls, the metabolic fingerprint of unrefreshing sleep will differ from both the healthy rested profile and the acute sleep deprivation profile, and will most closely resemble the chronic sleep disruption profile. *Alternative outcome*: if the ME/CFS pattern is indistinguishable from rested controls, this *does not* support a central perception model unless the CNS model makes independent falsifiable predictions (e.g., orexin deficiency correlates with unrefreshing sleep severity). A null result may instead indicate homeostatic adaptation to chronic sleep disturbance or that peripheral metabolic signatures wash out with disease chronicity.

*Feasibility.* Saliva collection is non-invasive, requires no clinic visit, and can be performed at home by severely ill patients — a critical practical advantage over blood-based metabolomics for ME/CFS biomarker research. The LC-HRMS analytical workflow is established. The planned international validation cohort (1,000+ samples including women and shift workers) will address the current n=20 all-male limitation.

*Limitations.* Certainty 0.20. All evidence from healthy populations; no ME/CFS salivary metabolomics study exists. The Scholz chronic restriction null is the most directly relevant experimental constraint and may predict a null ME/CFS outcome. Oishi et al. used PSQI self-report, not objective sleep measures, and the 13-metabolite chronic pattern may reflect confounders (depression, medication, metabolic syndrome) correlated with self-rated poor sleep. The 12-metabolite Scholz panel is not yet identified at compound level (features, not named metabolites). No replication in independent lab.
] <spec:saliva-sleep-metabolomic-biomarker>
