#import "../../../../shared/environments.typ": *

==== Boundary Conditions on Interpretation

- *The same drug may have different mechanisms at different doses in different patients:* LDN is TLR4 antagonist at 0.5--4.5 mg in most patients, but in a patient with OPRM1 polymorphism, it may be primarily an opioid antagonist. The diagnostic inference from LDN response depends on which mechanism is dominant in that patient — which is unknown without genotyping or mechanistic dissection.
- *Disease fluctuations produce false positives and negatives:* ME/CFS symptoms fluctuate day-to-day and week-to-week. A drug started during a spontaneous improvement will produce a false positive; a drug started during a spontaneous flare will produce a false negative. The framework requires baseline stability assessment before interpreting any probe result.
- *The order of probing affects the results:* A drug trialed after another drug has been stopped may produce a different response than if trialed first — because the first drug modified the system (receptor regulation, immune memory, epigenetic marks). The framework assumes probes are independent, but they are not — the system has a memory of prior probes.
- *Cumulative iatrogenic effects:* Each drug trial adds to the patient's pharmacologic load — drug interactions, metabolic burden, psychological impact of failure. By trial 5, the patient's baseline may have shifted from the cumulative burden of trials 1--4. Trial 5's result is being measured from a different baseline than trial 1 — the probes are not run on the same system.

*Consequence:* The framework is a structured approach to diagnostic pharmacology, but it rests on assumptions that have not been validated. A null response does not guarantee the mechanism is absent — it may be present but hidden by network redundancy, drug access failure, or measurement error. Every diagnostic inference from this chapter should carry the chapter's certainty range (0.25--0.40 for mechanistic inference, 0.10 for Gerlier, and lower for the extensions in sections @sec:beyond-binary through @sec:metabolic-cost). The framework is a hypothesis generator, not a validated diagnostic system.
*Origin:* methodological audit of the chapter's logic.
