#import "../../../shared/environments.typ": *

#open-question(title: [Could LDN vs Metformin Ever Be a Phenotype-Guided First-Line Choice?])[

A proposed stratification framework suggests choosing between repurposed drugs by dominant mechanism: LDN for a neuroimmune/TRPM3-dominant phenotype, metformin for an immunometabolic phenotype (insulin resistance, AMPK/mTOR dysregulation). The current evidence base does not support this as a triage rule, and the two drugs are not equally evidenced: metformin has been tested in established disease and failed to show symptom benefit — one completed RCT was negative (@Lim2026MetforminPASC) and a second adaptive trial stopped its metformin arm for futility (@Reis2026fluvoxamine) — whereas LDN has never been tested in a completed placebo-controlled RCT for this endpoint at all. "Neither can be selected by validated biomarker" is therefore not a symmetric null: it reflects one drug that has been tested and not shown benefit, and one that remains untested.

The strongest case for metformin is not that it failed, but that the failed trials were *unselected*: Lim2026 and Reis2026 enrolled established-disease patients without stratifying by insulin resistance, the exact design that can mask a true subgroup effect. Metformin's one positive RCT-level signal — COVID-OUT, acute-phase initiation, 41% relative reduction in Long COVID incidence (6·3% vs 10·4% by day 300, @Reis2023COVIDOUT) — arose in a defined metabolic/timing context, and post-infectious insulin resistance is documented in the same trigger population (@Sanhueza2026NETosisIR). A metabolically defined subgroup could therefore benefit even though unselected trials did not detect it. Against this, the mechanism-specific endpoints (REE, NETosis) have never been measured in ME/CFS, and no negative trial has been re-analysed by HOMA-IR subgroup — so the subgroup hypothesis is unverified, not refuted. (Absence of a *measured* response marker is also not proof that no responsive subgroup exists; the interaction may simply be unmeasured.)

On the LDN side, TRPM3 NK-cell dysfunction is a reproducible abnormality restored in vitro by naltrexone @Sasso2026trpm3 @Sasso2025LDNtrpm3LC, but restoration of channel function has never been shown to predict clinical response; metformin's immunometabolic reach (Th17/Treg balance, B-cell biology, flares in SLE/RA trials) is likewise real but modest and inconsistent @Ursini2018MetforminAutoimmunity @Sun2020MetforminSLE @Gharib2021MetforminRA. Neither mechanism has demonstrated clinical-response prediction, so for a given patient the choice between them is currently empirical rather than biomarker-guided. The two drugs could in principle act on different branches of the same process (@hyp:metabolic-immune-ldn), but no synergy mechanism or co-administration evidence exists.

*Falsifiable prediction:* Two designs could test the phenotype hypothesis. The cheaper first step is an *enrichment* trial — enrol only insulin-resistant (HOMA-IR-high) established ME/CFS patients and randomize to metformin vs placebo, with REE and NET/insulin endpoints alongside symptoms. Only if that shows signal is the fuller TRPM3 × HOMA-IR stratified randomization against LDN warranted (an interaction test needing several-fold the n of a main-effect trial). The joint prediction is that metformin benefits the HOMA-IR-high stratum and LDN the TRPM3-abnormal/insulin-sensitive stratum, with a significant phenotype × drug interaction. Indeterminate if subgroup signal appears on mechanism endpoints (REE, NETosis) without symptom improvement — that would establish metabolic modulation without clinical benefit, and would require a separate clinical-endpoint trial rather than declaring the hypothesis falsified.

*Consequence:* This is a research question, not a treatment protocol — no dose, monitoring schedule, or patient-selection rule is supplied here. No validated marker selects either drug today; for a patient who presents with post-viral fatigue and insulin resistance now, neither metformin nor LDN has demonstrated established-disease symptom benefit, and the choice is empirical — metformin's evidence is negative in unselected trials (with an untested subgroup hypothesis), and LDN's is mechanistic and untested in a completed RCT. The question defines what a future decision aid would need — validated response predictors — and warns against importing metformin into established ME/CFS on the strength of its acute-phase prevention signal. (Severity applicability: unknown — no severity-stratified data; this is a research question, not clinical guidance. Origin: brainstorm/assessment.) 
] <oq:ldn-metformin-phenotype-triage>
