#import "../../../../shared/environments.typ": *

=== Non-pharmacological Approaches

Non-pharmacological management is the foundation of orthostatic intolerance treatment and should be implemented before or alongside medications. A qualitative study by Uppal et al. (2026, Raj lab) found that POTS patients in their sample consistently reported modest medication effectiveness and valued non-pharmacological strategies (salt loading, compression garments, exercise within tolerance) as core components of their management @Uppal2026qualitative. Most patients had tried multiple medications with limited benefit — underscoring the importance of realistic expectations and that non-pharmacological strategies are essential complements, not alternatives, to pharmacotherapy. Qualitative studies capture patient experience, which may reflect suboptimal dosing, poor specialist access, or early discontinuation from side effects in addition to genuine pharmacodynamic limitation; these findings are formative rather than confirmatory regarding medication effectiveness.

    - *Fluid and salt intake*: 2–3 liters of fluid and 6–10 g of sodium chloride daily (unless contraindicated by renal or cardiac disease). Electrolyte solutions (oral rehydration salts) are more effective than water alone for plasma volume expansion. Salt tablets may be needed if dietary salt is insufficient
    - *Compression garments*: Waist-high compression stockings (30–40 mmHg) or abdominal binders are most effective, as lower-extremity-only compression fails to prevent splanchnic venous pooling. Compression should be donned before standing
    - *Physical countermanoeuvres*: Leg crossing, muscle tensing, squatting, and toe raises during prolonged standing increase venous return. These are immediate, cost-free interventions that patients can use in any setting
    - *Positional strategies*: Avoid prolonged standing; use a stool or perching seat for kitchen and bathroom activities. Elevate the head of the bed by 10–15 cm (not pillows alone, which flex the neck without changing hemodynamics) to reduce nocturnal natriuresis and improve morning orthostatic tolerance
    - *Graded reconditioning*: If tolerated within the energy envelope, recumbent exercise (recumbent cycling, swimming, rowing) can maintain cardiovascular function and prevent orthostatic deconditioning without the orthostatic stress of upright exercise. The Dallas/Leeds POTS protocol provides a clinical precedent from an adjacent condition: seated rowing, recumbent cycling, and swimming as starting modalities, with documented cardiovascular benefits in POTS patients @Fu2010DallasProtocol @Fu2018ExercisePOTS — however, the protocol has not been tested in ME/CFS, and community completion drops to 41 percent from 76 percent in research settings. The goal is maintenance, not fitness improvement — progression must be extremely gradual and must not trigger PEM (see Section @subsec:fitness-maintenance for the fitness-maintenance framework and Section @subsec:land-rowing for land-based rowing)

