#import "../../../../../shared/environments.typ": *

#limitation(title: [DTI-ALPS Signal May Reflect CSF Flow, Not Protein Clearance from Brain Parenchyma])[
Chayama et al.\ (2026) demonstrated that CSF-injected tracers distribute to fundamentally different anatomical compartments than endogenously produced neuronal proteins: 50--80% of ICM-injected tracers are recovered in cervical lymph nodes, while neuron-derived proteins drain primarily to dura, skull, and nasal cavity with minimal cervical lymph node representation @Chayama2026BrainClearance. This divergence persists even when matching tracer duration (14-day chronic CSF infusion produced the same lymph-node-dominated pattern). The implication: conventional glymphatic measurement techniques --- including DTI-ALPS, which measures water diffusion along perivascular spaces --- may reflect CSF flow dynamics rather than the actual clearance routes used by brain-derived proteins.

This does not invalidate existing fibromyalgia and Long COVID DTI-ALPS findings (Section @spec:ch15-neurodegeneration-risk), which show clinically meaningful correlations. But it means: (a) a normal DTI-ALPS index does not exclude impaired parenchymal clearance of neuronal waste --- proteins may accumulate in brain tissue while perivascular CSF flow appears normal; (b) the DTI-ALPS signal may be dominated by the fast CSF-to-lymph-node pathway that Chayama et al.\ show is minimally involved in neuronal protein clearance; (c) novel imaging methods that track endogenous protein movement (rather than CSF tracer flow) are needed for glymphatic assessment in ME/CFS; (d) blood-based measurement of brain-derived proteins (NfL, tau, amyloid-$beta$) may complement DTI-ALPS by directly measuring the output of parenchymal clearance rather than the proxy of perivascular fluid motion.

This limitation applies to all DTI-ALPS-based claims in this chapter. Until a method for tracking neuronal protein clearance in humans (analogous to the Syn-ZsG paradigm) is developed, all glymphatic imaging in ME/CFS should be interpreted with the caveat that the signal being measured may represent only a subset --- and possibly not the most functionally relevant subset --- of brain waste clearance pathways.
] <lim:ch15-dti-alps-caveat>
