#import "../../../shared/environments.typ": *

== Cross-Cutting Hypotheses
<sec:cross-cutting-hypotheses>

The failure cartography reveals several integrative hypotheses that connect multiple steps in the chain. Four are developed here. Note that these hypotheses are not strictly additive: the riboflavin master-rate-limiter, PDK pathological/protective, MnSOD-primary, and cardiolipin-convergence models each predict a largely overlapping metabolomic signature (reduced TCA intermediates, elevated lactate, altered acylcarnitines). A design that discriminates between them — rather than retaining all four as parallel candidates — would use a combination of EGRAC (riboflavin functional status), baseline MnSOD/GPX4, plasma oxidized cardiolipin, and PBMC PDK transcript levels measured in the same individuals, so that competing predictions can be tested against shared data rather than in isolation.

#speculation(title: [PDK Upregulation May Be Protective, Not Pathological])[
*Certainty: 0.45.*
PDK overactivation (Section @sec:step3-pdc) is routinely framed as a pathological lesion causing energy deficit. An alternative interpretation is that PDK upregulation is a *protective cellular response* to a downstream failure in ROS handling. If MnSOD and PRDX3 are impaired, increasing pyruvate flux through a leaky ETC would generate additional superoxide — worsening oxidative damage to iron-sulfur clusters, cardiolipin, and ETC proteins. PDK-mediated restriction of TCA substrate is then the cell's "dimmer switch," trading reduced ATP production for reduced oxidative injury.

This reinterpretation has a specific clinical consequence: PDK inhibition with dichloroacetate (DCA) *without* simultaneous antioxidant support could worsen ME/CFS by flooding an already-compromised ETC. The small DCA studies (Section @sec:step3-pdc) showing heterogeneous response are consistent with this: responders may be those with intact antioxidant systems; non-responders or worseners may have low MnSOD/GPX4.

*Testable prediction:* In a stratified DCA trial, patients with low baseline MnSOD and GPX4 activity will worsen (higher plasma F2-isoprostanes, worse PEM severity); patients with normal antioxidant status will improve (normalized lactate/pyruvate ratio, reduced PEM). DCA combined with NAC + CoQ10 + riboflavin will outperform DCA monotherapy.

*Limitation:* This remains entirely speculative pending direct evidence. The PDK-as-protective framing has not been tested in ME/CFS or any similar condition. The mechanism assumes a threshold beyond which additional TCA flux becomes net-harmful — a threshold that may vary widely between patients.
] <spec:pdk-protective>

#speculation(title: [Post-Exertional Malaise Timing Reflects Integrated Stress Response Kinetics])[
*Certainty: 0.40.*
The integrated stress response (ISR) --- a conserved cellular stress program governed by four eIF2α kinases (PERK, GCN2, PKR, HRI) --- is activated when mitochondrial proteostasis fails @CostaMattioli2020ISRReview. Exertion-induced cardiolipin peroxidation, iron-sulfur cluster damage, or ETC protein misfolding triggers OMA1 cleavage of DELE1, which activates the HRI kinase, which phosphorylates eIF2α, which initiates a 24--72 hour cellular reprogramming via ATF4 @CostaMattioli2020ISRReview . This reprogramming includes transient suppression of anabolic protein synthesis, amino acid redistribution, and the mitochondrial unfolded protein response (mtUPR). The characteristic 24--48 hour delay between exertion and PEM peak matches ISR kinetics precisely.

The only direct ISR-activation evidence in ME/CFS comes from the PERK arm: Wang et al.\ found elevated PERK markers in ME/CFS skeletal muscle, establishing that the ER-stress branch of the ISR is active in this tissue @wang2023wasf3. PERK is one of the four eIF2α kinases; its elevation confirms ISR engagement via the ER-stress route, consistent with WASF3-mediated ER dysfunction (@ach:wasf3-mechanism). Whether the HRI arm (mitochondrial stress), GCN2 arm (amino acid starvation), or PKR arm (viral dsRNA sensing) are also activated in ME/CFS remains unmeasured.

If PEM is mechanistically an ISR response to exertion-induced mitochondrial damage, then GDF15 and FGF21 (canonical plasma ISR biomarkers) should peak 24--48 hours post-exertion and track PEM severity @CostaMattioli2020ISRReview. ATF4-target gene expression in PBMCs should be elevated during PEM. This framing also predicts that protecting mitochondria from exertion-induced damage (antioxidants, cardiolipin stabilizers, pre-activity creatine loading) would attenuate PEM by reducing the ISR trigger.

*Testable prediction:* Plasma GDF15 and FGF21 will peak 24--48 h after a standardized exertion challenge in ME/CFS patients, correlating with symptom severity, and will not peak at comparable levels in healthy controls or in ME/CFS patients without PEM. The ISR inhibitor ISRIB (experimental) would attenuate PEM in an animal model if the mechanism is confirmed.

*Limitation:* Direct ISR measurement in ME/CFS is limited to PERK elevation in muscle (n=14, single study) @wang2023wasf3. Peripheral blood stress biomarkers showed no difference between long COVID and controls in one controlled study (n=48) , suggesting ISR signatures may be tissue-confined rather than circulating. GDF15 has other causes including cardiac and inflammatory conditions. The connection between ISR kinetics and PEM timing remains mechanistic reasoning without direct empirical support.
] <spec:pem-isr>

#speculation(title: [Riboflavin Deficiency as a Multi-Step Master Rate-Limiter])[
*Certainty: 0.42.*
FAD (flavin adenine dinucleotide, the active form of riboflavin) is an obligate prosthetic group or cofactor at eight or more distinct energy-chain steps: PDC E3 (dihydrolipoamide dehydrogenase), KGDHC E3 (same enzyme), all four acyl-CoA dehydrogenases in beta-oxidation (VLCAD, LCAD, MCAD, SCAD), the electron transfer flavoprotein (ETF) and ETF-QO that bridge beta-oxidation to the ubiquinone pool, and succinate dehydrogenase (Complex II) as FADH#sub[2] donor. A single cofactor thus gates simultaneously the carbohydrate-to-acetyl-CoA arm, the fatty-acid-to-acetyl-CoA arm, and one direct ETC entry point.

Marginal riboflavin status — common in Western diets and worsened by GI malabsorption, mast cell activation, or bile acid dysbiosis — would produce a metabolomic signature nearly indistinguishable from the combination of PDK overactivation plus beta-oxidation failure plus Complex II dysfunction: exactly the pattern reported across ME/CFS metabolomics studies  . Riboflavin-responsive multiple acyl-CoA dehydrogenase deficiency (MADD) produces exercise intolerance, myopathy, and elevated acylcarnitines indistinguishable from severe ME/CFS.

*Testable prediction:* Erythrocyte glutathione reductase activation coefficient (EGRAC, the gold-standard functional riboflavin biomarker) will be ≥1.3 in ≥30% of ME/CFS patients vs \<10% of matched controls. Patients with elevated EGRAC will show plasma C4--C18 acylcarnitine elevation (the MADD/ETF-QO signature). Riboflavin 400 mg/day for 12 weeks will normalise EGRAC and reduce lactate/pyruvate ratio in EGRAC-high responders.

*Limitation:* No ME/CFS study has measured EGRAC. Standard serum riboflavin may be misleading: Hypothesized impairment of riboflavin transporter (SLC52A2) or mitochondrial FAD loading means tissue-level FAD deficit could exist with normal serum riboflavin.
] <spec:riboflavin-master>

#speculation(title: [Cardiolipin Peroxidation as the Convergence Point of ROS Damage])[
*Certainty: 0.30* (reduced from an initial 0.40 to reflect the negative MMPOWER-3 Phase 3 result in primary mitochondrial myopathy, which provides a discouraging prior for cardiolipin-targeted intervention in adjacent mitochondrial indications).
Cardiolipin (CL), the mitochondria-specific phospholipid, is uniquely vulnerable to peroxidation: it contains four polyunsaturated fatty acid chains (vs two for other phospholipids) and sits directly adjacent to the principal superoxide generators at Complexes I and III. Oxidized cardiolipin (CLox) triggers: release of cytochrome c from Complex III (disrupting electron transfer), inflammasome activation, and disassembly of ETC supercomplexes. With MnSOD decreased and PRDX3 uninvestigated, CLox accumulation is a mechanistically predicted consequence of sustained elevated ROS in ME/CFS.

Elamipretide (SS-31/bendavia) is a mitochondria-targeted tetrapeptide that selectively binds cardiolipin, stabilizes its interaction with cytochrome c, and prevents peroxidation. It has completed Phase 3 trials in Barth syndrome (CL synthesis defect) and primary mitochondrial myopathy (MMPOWER-3); the MMPOWER-3 trial did not meet its primary endpoint (6-minute walk distance) at 24 weeks. This negative result in the closest analogous indication substantially tempers expectations for ME/CFS: even if cardiolipin peroxidation is confirmed in ME/CFS, elamipretide's clinical efficacy profile in a related mitochondrial disease is a discouraging prior, not a permissive one. Molnar et al.\ have specifically proposed it as a candidate for Long COVID mitochondrial dysfunction ; pursuing this rationale in ME/CFS requires first confirming CL oxidation in a ME/CFS cohort, and any eventual trial would need to pre-specify why it should succeed where MMPOWER-3 did not.

*Testable prediction:* Plasma oxidized cardiolipin (by LC-MS) will be >2× control in moderate-to-severe ME/CFS and will correlate with 4-HNE, F2-isoprostane, and MnSOD levels. A 12-week elamipretide open-label trial will reduce F2-isoprostanes and CLox, improve 6-minute walk distance, and reduce PEM frequency in responders with elevated baseline CLox. Non-response with normal baseline CLox would refute cardiolipin peroxidation as a driver.

*Limitation:* Plasma CLox may not reflect intramitochondrial CLox in muscle or brain. Elamipretide is injectable, limiting accessibility for severely ill patients.
] <spec:cardiolipin-peroxidation>

#speculation(title: [Irisin Signaling Resistance via TSP-1 as a Mechanism of Impaired Metabolic Adaptation in PEM])[
*Certainty: 0.45.*
Irisin, a PGC-1#sub[$alpha$]-dependent myokine released by exercised muscle @Bostrom2012Irisin, promotes mitochondrial biogenesis, oxidative phosphorylation, and glucose uptake, and signals through αV integrins (including αvβ5) in a manner requiring extracellular HSP90α @Kim2018IrisinIntegrin @A2023IrisinHsp90. A 2026 cross-sectional study of 92 ME/CFS patients (CCC criteria) and 44 sedentary controls found lower baseline plasma irisin and a blunted irisin response to a standardized 90-minute mechanical stress challenge in ME/CFS (Δirisin reduced, p = 0.034) @Souma2026IrisinSignalingResistance. In parallel, functional cellular-dielectric-spectroscopy assays showed that thrombospondin-1 (TSP-1) inhibits irisin signaling in a concentration-dependent manner, and that irisin signaling is markedly reduced by both αvβ5 blockade and HSP90α inhibition, while TSP-1 retains its inhibitory activity even when these components are disrupted @Souma2026IrisinSignalingResistance. Elevated TSP-1 also suppresses nitric-oxide signaling and angiogenesis via CD47, a pathway with documented vascular relevance @Rogers2014TSP1CD47 @Roberts2017MatricellularRedox. Together these findings support a model in which elevated TSP-1 acts as a dominant antagonist of irisin-mediated metabolic signaling, contributing to the impaired adaptive response to exertion that characterises PEM. (Evidence source: plasma + Jurkat-cell in vitro — inference target: skeletal-muscle and systemic metabolic signaling. Link is indirect and requires validation in primary human muscle/PBMC systems. Severity coverage: mild and moderate-to-severe per MFI-20 stratification in the primary cohort; very-severe not separately stratified. Translation gap: in vitro → human. Not yet validated in independent ME/CFS cohorts.)

*Testable prediction:* In ME/CFS patients, plasma TSP-1 (or the TSP-1:irisin ratio) will rise in proportion to the blunted irisin response and to PEM severity across repeated exertional challenges; PBMC or muscle-derived cells from ME/CFS patients with elevated TSP-1 will show attenuated irisin-stimulated signaling relative to cells from patients with low TSP-1. Falsified if irisin-stimulated signaling in patient-derived cells is normal despite elevated TSP-1, or if TSP-1 reduction restores no metabolic phenotype.

*Limitation:* The ME/CFS evidence is a single cross-sectional cohort from one laboratory (Moreau group, CHU Sainte-Justine) with no independent replication; the functional mechanism rests on Jurkat-cell assays, not primary muscle or endothelial cells — a cell-type gap (immune cell vs the myocyte that matters for PEM); TSP-1 is also a generic activation marker, so its elevation may reflect non-specific endothelial/platelet activation rather than a specific irisin-antagonist role; plasma irisin ELISAs have known cross-reactivity and kit-variability caveats @Elsen2014IrisinHumanCaveat; the irisin finding itself is not reproducible in adjacent conditions (unchanged in fibromyalgia @Ercan2026IrisinFMnull; poor diagnostic accuracy in sarcopenia @Lapauw2026IrisinSarcopeniaNull).

*Consequence:* If confirmed, this framework would reframe PEM not as simple muscle exhaustion but as a failure of a specific exercise-induced signaling pathway, pointing to a biomarker (TSP-1/irisin) and to testable targets (TSP-1 reduction, NO restoration, HSP90#sub[$alpha$] stabilization) — all currently hypothesis-stage with no human dosing or safety data.
] <spec:irisin-signaling-resistance>

#open-question(title: [The Irisin–TSP-1 Severity Paradox: Compensation or Distinct Biology?])[
In the Souma 2026 cohort, baseline irisin was an independent predictor of fatigue severity (β = 0.67, p = 0.021), and patients with moderate-to-severe fatigue showed elevated levels of *both* irisin and TSP-1 @Souma2026IrisinSignalingResistance. This is paradoxical: lower group-level irisin in ME/CFS yet higher irisin in the most severely affected. The authors interpret this as a compensatory but ineffective response overridden by a concurrent rise in the antagonist TSP-1. An equally-evidenced alternative is that the severity-stratified rise reflects a biologically distinct regulatory programme (e.g. different PGC-1#sub[$alpha$] or FNDC5 regulation, or a sex-specific effect — the irisin–PEM correlation held in male patients, R = 0.53, p = 0.01, but not females) rather than pure compensation @Souma2026IrisinSignalingResistance. (Evidence source: plasma ELISA; inference target: systemic metabolic signalling. Severity coverage: mild and moderate-to-severe; very-severe unknown. Cohort overlap: Moreau-group biobank — not independent of prior corpus cohort evidence. Certainty: 0.30.)

*Falsifiable prediction:* A longitudinal study measuring irisin and TSP-1 across PEM episodes will discriminate the two models: the compensation model predicts irisin and TSP-1 rise together before symptom recovery, whereas the distinct-biology model predicts a stable severity-associated set-point that does not track acute PEM state. Refuted if irisin and TSP-1 do not track the predicted temporal relationship.

*Consequence:* Resolving whether high irisin in severe ME/CFS is compensation or a distinct state determines whether TSP-1-suppressing or irisin-restoring therapies could help or could merely chase a compensatory signal — the answer is currently unknown and requires longitudinal biomarker studies.
] <oq:irisin-tsp1-severity-paradox>

#speculation(title: [TSP-1 as a Vascular–Metabolic Convergence Node])[
*Certainty: 0.40.*
Thrombospondin-1 (TSP-1) is already documented in this paper's corpus as an endothelial-activation marker elevated in ME/CFS: it appears in the Heng 2025 biomarker panel as the endothelial-activation arm @heng2025mecfs, and broader serum-proteome profiling documents intensified secretome vasculature interactions in ME/CFS @Hoel2026proteome. Souma 2026 adds a second, functionally distinct role for the *same molecule*: TSP-1 as a dominant antagonist of irisin signaling at the HSP90#sub[$alpha$]/αvβ5 axis, impairing metabolic adaptation to exertion @Souma2026IrisinSignalingResistance. The unifying hypothesis is that one upstream molecule may simultaneously drive (a) the documented vascular/endothelial dysfunction and (b) the impaired metabolic adaptation, via CD47-mediated NO suppression @Rogers2014TSP1CD47 @Roberts2017MatricellularRedox and via irisin-axis antagonism respectively. If true, two currently-separate findings (vascular and metabolic) become two faces of one matricellular-signaling lesion — and explain why TSP-1 elevation spans such different symptom domains. (Evidence source: plasma + Jurkat-cell in vitro; inference target: systemic vascular and metabolic signaling. Link indirect, requires primary human muscle/endothelial validation. Severity coverage: mild and moderate-to-severe; very-severe unknown. Translation gap: in vitro → human. Origin: brainstorm.)

*Testable prediction:* In a single cohort, plasma TSP-1 will correlate with BOTH endothelial markers (VWF, fibronectin) AND the blunted exertional irisin response simultaneously; the top TSP-1 quartile will show both the worst perfusion/endothelial measures and the worst metabolic adaptation. Falsified if TSP-1 elevation segregates with vascular but not metabolic dysfunction (the two defects are TSP-1-independent).

*Limitation:* TSP-1 is a generic platelet/endothelial/immune-activation marker elevated in injury, inflammation, cancer, and cardiovascular disease @Rogers2014TSP1CD47 @Roberts2017MatricellularRedox; its elevation in ME/CFS may reflect non-specific activation rather than a specific irisin-antagonist role. The convergence claim rests on two separate single-source observations (corpus vascular markers + Souma 2026), not yet demonstrated within one cohort.

*Consequence:* If one molecule already flagged in ME/CFS blood work as a blood-vessel-problem marker also blocks the muscle's adaptive "exercise-good" signal, then two of the disease's most disabling features — poor circulation and post-exertional crash — may share a single upstream cause, making it a more attractive drug target than either alone; this is currently a unifying hypothesis awaiting a combined vascular+metabolic cohort study.
] <spec:tsp1-vascular-metabolic-convergence>

#synthesis(title: [Irisin–TSP-1 Axis as a Model of Metabolic Signaling Resistance in PEM])[
The three hypotheses above jointly argue that a failure of the irisin signalling axis — a myokine pathway that normally transduces the adaptive, mitochondrial-supporting response to exertion — may contribute to the impaired metabolic adaptation and PEM of ME/CFS. @spec:irisin-signaling-resistance proposes that elevated TSP-1 antagonises irisin at the HSP90#sub[$alpha$]/αvβ5 axis, converting a physiological "exercise-good" signal into ineffective signalling; @spec:tsp1-vascular-metabolic-convergence ties this to the already-documented elevation of TSP-1 as a vascular marker, so that the same molecule may underlie both poor circulation and the metabolic defect; @oq:irisin-tsp1-severity-paradox flags the unresolved severity paradox — high irisin in the most severely affected patients — which distinguishes a compensatory-but-ineffective response from a distinct biology. What the evidence supports: a plausible, testable mechanistic framework grounded in one direct ME/CFS cohort plus well-established irisin and TSP-1 biology. What remains speculative: that TSP-1-mediated irisin resistance is a causal driver of PEM (single cross-sectional cohort, in vitro Jurkat mechanism), that irisin-TSP-1 profiling is a valid biomarker, and any therapeutic implication. The central open question is whether reducing TSP-1 or restoring irisin signalling would actually restore metabolic adaptation in patients, or merely chase a compensatory signal.

*Consequence:* A single blood-measurable pair — the "exercise signal" and its blocker — may capture why exertion fails to produce recovery in ME/CFS, offering a concrete biomarker and a testable target for future research, even though both remain hypothesis-stage today.
] <syn:irisin-tsp1-model>

