#import "../../../../../shared/environments.typ": *

#speculation(title: [Multi-Oscillator Phase-Lock Model of Sleep Physiology])[
The interactions among brain (delta/alpha EEG oscillators), autonomic (R-R interval oscillations), vascular (vasomotion oscillations), and respiratory (breathing rate oscillations) systems during sleep can be modelled as coupled oscillators in the Kuramoto framework, where each system $i$ has a natural frequency $omega_i$, and coupling strength $K_{i,j}$ determines how strongly system $i$ entrains to system $j$. In health, coupling strengths are high enough to maintain phase synchrony across systems at the infraslow ($<$0.1 Hz) range critical for glymphatic pumping. In ME/CFS, one or more coupling constants are pathologically reduced, causing partial or complete desynchronisation.

The model predicts: (a) system-level coupling loss propagates nonlinearly --- a 20% reduction in neural--vascular coupling $K_"nv"$ may reduce overall glymphatic clearance by >50% because the sequential coupling cascade (neural $arrow.r$ vascular $arrow.r$ CSF) amplifies upstream deficits; (b) partial restoration of any single coupling pathway (e.g., autonomic--neural via propranolol) will improve overall synchrony by less than the deficit implies, because phase coherence requires sufficient coupling strength across all connected pairs; (c) the most efficient coupling-restoration target depends on the specific decoupling phenotype: autonomic-decoupled patients require autonomic-targeted interventions, thalamocortical-decoupled patients require calcium-modulating interventions.

*Certainty: 0.25.* (0.20→0.25: SleepFM @Thapa2026sleepfm demonstrates cross-modal decoupling during sleep predicts disease onset across 130+ conditions, supporting the coupling-constant framework at the general-principle level; coupling constants not empirically characterised, no specific ME/CFS mechanism validated) The Kuramoto framework is well-established for biological oscillator systems (circadian biology, neural synchronisation), but has not been applied to multi-system sleep physiology in ME/CFS. Coupling constants for healthy sleep systems are not empirically characterised. The nonlinear clearance prediction is consistent with the Hauglund et al.\ demonstration that 50% NE oscillation suppression reduces glymphatic clearance proportionally @Hauglund2025neVasomotion.

*Falsifiable prediction:* A Kuramoto model with coupling constants fit to healthy control PSG data will reproduce ME/CFS decoupling patterns when coupling constants are reduced by 30--50%. The model will predict that a 20% increase in any single coupling constant improves overall phase coherence by $<$12%, but 20% increases across two coupled pathways produce $>$35% improvement.
] <spec:ch15-kuramoto-decoupling>
