#import "../../../../shared/environments.typ": *

=== Cross-Reference Matrix: Drug × Hypothesis × Diagnostic Inference
<sec:cross-reference-matrix>

*Certainty: 0.20--0.40, variable by drug-hypothesis pair.* This table consolidates the diagnostic logic scattered across all preceding cascade sections and the side-effect framework. Each cell is a shorthand diagnostic inference. For full logic, refer to the named section. Abbreviations: + = positive response, − = null response, SE = side effect pattern, Ø = no diagnostic inference.

#table(
  columns: 5,
  align: (left, left, left, left, left),
  table.header(
    [*Drug*],
    [*Hypothesis Node*],
    [*If + works*],
    [*If − null*],
    [*Side effect → diagnosis*],
  ),
  // Ion Channel
  [LDN], [TRPM3], [Channelopathy rate-limiting (@sec:trpm3-cascade A2)], [TRPM3 absent, non-responsive, or not rate-limiting], [Sedation → orexin low; Dysphoria → opioid-dependent (Pattern 1/2)],
  [Lithium], [PIP2 depletion], [PIP2 depletion rate-limiting; GPCR AAb upstream (@sec:trpm3-cascade A1)], [PIP2 not bottleneck; lesion downstream or channel defect is PIP2-independent], [Polydipsia/polyuria at 2 mg → occult nephrogenic DI; Tremor at 2 mg → cerebellar NE sensitivity (Pattern 3)],
  [Pregnenolone], [TRPM3 gating], [TRPM3 dysfunction rate-limiting (@sec:trpm3-cascade A2)], [TRPM3 not rate-limiting or not LDN/pregnenolone-responsive], [Ø],
  // Mitochondrial
  [CoQ10], [ETC efficiency], [ETC inefficiency functional (cofactor-compensable) (@sec:wasf3-cascade D2)], [SC disruption severe — cofactor flooding inadequate], [Worsening → Complex III block (ROS from electron leak); combined with carnitine worsening → lipid peroxide (Pattern 5)],
  [NMN/NR], [NAD⁺ depletion], [NAD⁺ deficiency rate-limiting (@sec:nad-cascade G2)], [NAD⁺ not rate-limiting; consumption excess (PARP/CD38) or ETC downstream], [Ø],
  [Thiamine (B1)], [PDH cofactor], [PDH cofactor deficiency; simple, reversible, nutritional (@sec:pdh-cascade E2)], [PDH block is not cofactor-dependent (PDK-driven phosphorylation)], [Ø],
  [Creatine], [ATP buffering], [ATP pool insufficient — consistent with reduced steady-state production (@sec:wasf3-cascade D3)], [Ø], [Ø],
  [L-carnitine], [FAO shuttle], [FAO is functional and rate-limiting for ATP (@sec:wasf3-cascade D2)], [FAO not bottleneck; PDH/ETC defect dominates], [Worsening → lipid peroxide (low glutathione); try NAC first (Pattern 5)],
  // Autoimmune
  [Immunoadsorption / BC007], [GPCR AAb], [AAb rate-limiting; PIP2 convergence if multi-channel (@sec:ion-channel-convergence)], [AAb absent, non-pathogenic, or not rate-limiting; or AAb not removed by IA column type], [BC007 vs IA dissociation → narrows AAb subtype; No flare + no response → profound immune exhaustion (Pattern 5)],
  [Rituximab], [B-cell AAb source], [B-cell-driven AAb pathogenic; if transient → plasma cells drive chronicity (@sec:gpcr-cascade I1)], [AAb from CD20− plasma cells (rituximab-spared)], [Transient response → B-cell repopulation confirms AAb source],
  [IVIG], [AAb neutralization + immunomodulation], [GPCR AAb present and rate-limiting (@sec:gpcr-cascade I1)], [No AAb, AAb not rate-limiting, or IgG/IgM mismatch], [Transient flare 48--72h → confirms AAb neutralization; Flare >7 days → complement-MCAS loop; No flare + no response → immune exhaustion (Pattern 2)],
  // Neuroinflammatory
  [Minocycline], [Non-TLR4 microglial], [Microglial activation through P2X7/C5aR/IFN-γR rate-limiting (@sec:microglial-cascade K1)], [Microglial activation absent or TLR4-dependent only], [Vestibular → brainstem vulnerable],
  [Memantine], [NMDA excitotoxicity], [Quinolinic acid-driven NMDA excitotoxicity rate-limiting (@sec:kynurenine-cascade H2b)], [Excitotoxicity not rate-limiting; glutamate tone may be low (kynurenic acid dominance)], [Sedation at low dose → basal glutamate tone low (Pattern 4)],
  [Guanfacine], [PFC α2A noradrenergic], [PFC NE deficiency rate-limiting for cognition (@sec:microglial-cascade K2d)], [PFC lesion is not NE-mediated; glutamatergic or circuit-level], [BP crash → sympathetically dependent; requires midodrine to access cognitive benefit (Pattern 4)],
  // Dopaminergic
  [Aripiprazole], [D2/D3 dopamine], [DA dysfunction rate-limiting; lesion at or above D2/D3 (@sec:dopamine-convergence)], [Lesion below D2/D3 (VMAT2, ATP-dependent release, non-dopaminergic)], [Akathisia at microdose → severe DA deficiency with supersensitive receptors (Pattern 3); No response + no SE → D2/D3 neither deficient nor responsive (Pattern 5)],
  [Methylphenidate], [DAT/NET reuptake], [NE/DA deficiency rate-limiting for cognition/fatigue], [DA/NE not rate-limiting; or cognitive lesion is postsynaptic, not presynaptic], [Tachycardia ceiling → hyperadrenergic POTS; Crash ceiling → DA depletion + ATP deficit; Insomnia ceiling → DAT occupancy too high (Pattern 4)],
  [Amantadine], [DA release (non-D2)], [Presynaptic DA release is the bottleneck — DA stores exist but release is impaired], [DA release machinery is intact; lesion is postsynaptic or non-dopaminergic], [Ø],
  [Pramipexole], [D2/D3 postsynaptic agonism], [D2/D3 receptors intact and responsive], [Lesion is not at D2/D3 — synthesis, storage, or downstream signaling], [Nausea at RLS dose → DA supersensitivity in area postrema; No nausea + no dizziness → D2/D3 too damaged to respond (Pattern 5)],
  [L-DOPA/Carbidopa], [DA synthesis (AADC-dependent)], [DA synthesis is the bottleneck; AADC functional, substrate-limited], [Lesion not at DA synthesis; postsynaptic D2/D3 absent/desensitized, or non-dopaminergic], [Nausea/OH at 1/4 tablet → D2 supersensitivity (same pattern as pramipexole/aripiprazole); No benefit → lesion not at DA synthesis],
  [Modafinil/Armodafinil], [DAT block + histamine/orexin], [DAT-mediated DA increase rate-limiting for cognition/wakefulness], [DAT absent, blocked (AAb), or non-functional; or DA not rate-limiting], [Insomnia ceiling → orexin/histamine intact + DA-sensitive; No response → DAT dysfunctional],
  [Solriamfetol], [Pure DNRI (DA+NE)], [DA/NE reuptake rate-limiting], [NE/DA reuptake not rate-limiting; or cognitive lesion postsynaptic], [BP/HR ceiling without cognition → PFC α2A desensitized (Pattern 4); Cognition without BP/HR → DA bottleneck, not NE],
  [Amphetamines (last resort)], [VMAT2 + DAT reversal], [VMAT2-dependent DA release intact], [VMAT2 terminals absent or depleted; or DA not rate-limiting], [Severe post-dose crash (PEM-like, weeks) → VMAT2 terminal compromise; never re-challenge; No response + no crash → DAT absent/DA not bottleneck],
  // Autonomic
  [Midodrine], [α1 adrenergic], [Vasculature α1-responsive; neuropathic POTS if supine NE low (@sec:pots-cascade Q1)], [α1 receptors absent, blocked (GPCR AAb), or vasculature structurally unresponsive], [HTN at 2.5 mg → denervation hypersensitivity (Pattern 1); No piloerection → length-dependent SFN (Pattern 5)],
  [Clonidine], [Central α2 agonist], [Central sympathetic overactivation is rate-limiting; brainstem baroreflex reset or GPCR AAb at area postrema (@sec:brainstem-cascade)], [Central sympathetic drive is NOT load-bearing; α2 autoreceptors desensitized (hyperadrenergic POTS)], [BP crash at 0.05 mg → zero sympathetic reserve (Pattern 1); No BP change at 0.1 mg → α2 desensitization (Pattern 5)],
  [Prazosin], [Peripheral α1 antagonist / glymphatic], [NE-mediated vasoconstriction was suppressing glymphatic flow; improved morning symptoms (@sec:glymphatic-cascade M2)], [Glymphatic flow not NE-mediated; or LC-NE vasomotion not the bottleneck], [OH at 0.5 mg → α1-dependent standing BP, neuropathic POTS (Pattern 1); No OH at 1 mg → BP not α1-dependent (hyperadrenergic POTS)],
  [Pyridostigmine], [Cholinergic/vagal], [Cholinergic signaling intact; improves preload, HRV, GI (@sec:aimm-cascade F1)], [Vagal efferent non-functional; DMV damage, ganglionic AChR AAb, or structural], [GI cramping at 30 mg → gut muscarinic hypersensitivity (Pattern 3)],
  [Fludrocortisone], [Volume/hypovolemic POTS], [Hypovolemia present (RAAS paradox) (@sec:pots-cascade Q3)], [Not hypovolemic; CT laxity or hyperadrenergic], [Worsening orthostasis → venous pooling (Pattern 2); Hypokalemia → RAAS defect localized to renin],
  [Ivabradine], [SA node / HR], [HR control without β2 blockade → rules out metabolic cost of beta-blockers], [SA node intrinsic dysfunction — chronotropic incompetence not autonomic], [Bradycardia ceiling → SA node lower limit reached (Pattern 4)],
  [Beta-blockers], [β1+β2 adrenergic], [Sympathetic overactivation rate-limiting for HR], [HR not the bottleneck; or β2 metabolic cost unacceptable], [Fatigue worsening → β2-AR lipolysis was fallback; PDH/ETC impairment (Pattern 1)],
  [Atomoxetine], [NE reuptake (pure NRI)], [NE deficiency rate-limiting (@sec:noradrenergic-node)], [NE not rate-limiting; lesion postsynaptic (α2A) or non-noradrenergic], [No cognitive benefit despite HR/BP → PFC α2A desensitized; try guanfacine],
  [Droxidopa], [NE synthesis (AADC-dependent)], [NE synthesis capacity intact; presynaptic NE stores loadable], [AADC deficient or VMAT2 cannot store NE; presynaptic lesion], [Supine HTN without orthostatic benefit → postsynaptic α1 desensitized; confirms hyperadrenergic POTS],
  [Pitolisant], [Histaminergic/orexin], [Histaminergic anti-inflammatory (M1→M2) or wakefulness benefit], [Histaminergic system not bottleneck; H3 downregulated or histamine depleted], [Insomnia ceiling → histaminergic on hair trigger; Headache ceiling → histamine-mediated vasodilation (Pattern 4)],
  // Pain / Neuropathic / Serotonergic
  [Gabapentin / Pregabalin], [α2δ-CaV channel], [α2δ-CaV channels functional + rate-limiting for neuropathic pain], [Central sensitization not α2δ-mediated; consider PEA, LDN, or ketamine], [Sedation at minimal dose → severe central sensitization (Pattern 4); paradoxical agitation → GAD dysfunction],
  [Duloxetine], [NE/5-HT reuptake (SNRI)], [NE or 5-HT deficiency rate-limiting for pain/cognition/mood], [NE/5-HT not rate-limiting; or lesion is postsynaptic], [Anticholinergic at low dose → subclinical AChE deficiency (Pattern 3); nausea at 30 mg → 5-HT3 gut hypersensitivity],
  [Amitriptyline], [NE/5-HT + H1 + M1], [H1 + M1 + NE/5-HT blockade provides pain/sleep/glymphatic benefit], [Pain/sleep not H1/M1/NE/5-HT mediated], [Sedation at 5--10 mg → H1 supersensitivity (Pattern 1); anticholinergic at low dose → M1 supersensitivity; no sedation at 25 mg → H1 desensitized (MCAS)],
  // Sleep
  [Shoe lift], [Skeletal asymmetry (Gerlier)], [Mechanical driver confirmed; PEM from asymmetry-driven ATP drain (@sec:gerlier-pathway1 G1a)], [Asymmetry non-contributory; direct to biochemical/autoimmune hypotheses], [Ø],
  [Cervical collar], [CCI / functional CCI], [CCI present and rate-limiting; if resolves dizziness but not POTS → non-cervical POTS mechanism (@sec:cci-cascade O1)], [CCI absent or not rate-limiting; if collar resolves nothing → non-mechanical], [Ø],
  [Vitamin C + NAC (timed)], [HIF-1α CT remodeling], [ROS-mediated PHD inhibition rate-limiting — acquired CT weakness, potentially reversible (@sec:hif1a-ct-cascade N1)], [CT weakness is genetic (EDS), not acquired; or ROS is not the CT lesion driver], [Ø],
  [Ketotifen], [Mast cell stabilization], [Mast cell degranulation rate-limiting (@sec:piezo2-cascade C2, @sec:gpcr-cascade I2)], [Mast cells not rate-limiting; or IgE-driven MCAS not ketotifen-responsive], [Sedation at 0.5 mg → histaminergic wakefulness depends on MCAS histamine (Pattern 1)],
  // Antiviral
  [Valacyclovir], [EBV/HHV-6 systemic], [Herpesvirus reactivation rate-limiting], [EBV not rate-limiting; or virus in sanctuary site (CNS/DRG)], [CNS effects at standard dose → subclinical renal impairment (Pattern 4)],
  [Valganciclovir], [HHV-6/CMV/EBV broad], [Broad-spectrum herpesvirus replication rate-limiting; active where valacyclovir failed], [Herpesvirus not rate-limiting (regardless of serology/PCR)], [Bone marrow suppression at subtherapeutic dose → marrow reserve exhausted (Pattern 4)],
  // Miscellaneous
  [DORA (daridorexant)], [OX1R/OX2R orexin], [Nocturnal orexin surges rate-limiting for sleep maintenance], [Orexin tone not rate-limiting; or already at floor], [Sleep paralysis at low dose → orexin critically low; DORA contraindicated. No effect → orexin already at floor (Pattern 5)],
  [Trazodone], [5-HT2A/H1/α1], [5-HT2A blockade → SWS → glymphatic benefit], [Sleep pathology not 5-HT2A/H1-mediated], [Next-day sedation → H1 supersensitivity; OH → α1 dependence (Pattern 4)],
  [Doxepin (low-dose)], [H1 antagonist (pure at 3--6 mg)], [Histaminergic arousal dominant cause of nocturnal awakenings], [Awakenings non-histaminergic (orexin, adrenergic, pain)], [Next-day sedation at 3 mg → H1 supersensitivity; no sedation → H1 desensitized (MCAS)],
  [Melatonin], [MT1/MT2 circadian], [Circadian phase disorder rate-limiting for sleep], [Sleep-onset insomnia hyperarousal-driven (not circadian)], [Paradoxical alertness → severely delayed phase or CYP1A2 rapid metabolism; nightmares → REM disinhibition],
  [Famotidine/Cimetidine], [H2 + T-cell (cimetidine)], [H2-mediated gastric histamine or T-cell modulation rate-limiting], [H2 not rate-limiting for gastric or immune symptoms], [Depression/suicidal ideation → paradoxical reactor (Pattern 2); famotidine worse depression than cimetidine → off-target; cimetidine worse depression than famotidine → CYP450 interaction],
  [Cromolyn sodium], [Gut mast cell], [Gut mast cell degranulation rate-limiting for GI symptoms], [Gut mast cells not dominant MCAS source], [No GI benefit → CNS/systemic mast cells dominate (Pattern 5)],
  [Aspirin/NSAIDs], [COX-1/COX-2], [Prostaglandin-driven inflammation is rate-limiting for pain], [Pain non-inflammatory (neuropathic, central sensitization)], [Worsening MCAS → COX inhibition triggers mast cell degranulation; MCAS contraindicated],
  [D-ribose], [ATP salvage (purine)], [Purine salvage pathway is rate-limiting for ATP regeneration], [ATP regeneration not purine-limited], [Hypoglycemia → impaired gluconeogenesis; GI symptoms → rapid absorption intolerance],
  [NAC], [Glutathione precursor], [Oxidative stress rate-limiting; glutathione deficiency], [Oxidative stress not rate-limiting; or glutathione not the bottleneck], [Ø],
  [Caffeine], [Adenosine/catecholamine], [Catecholamine release intact — presynaptic pool not exhausted], [CNS sympathetic activation failure (CNS NE deficiency @ach:catecholamine-deficit)], [No tachycardia → central sympathetic failure; No alertness → A2A desensitized (Pattern 5)],
  [Antihistamines (H1)], [MCAS peripheral/CNS], [Mast cell histamine is rate-limiting for symptoms], [Histamine not the dominant mast cell mediator — PGD2, tryptase, or leukotrienes dominant], [No sedation → CNS H1 desensitized from chronic MCAS histamine exposure (Pattern 5)],
  [Corticosteroids], [Inflammatory (broad)], [Inflammation is rate-limiting (does not ID source)], [Steroid-resistant inflammation (inflammasome, complement, mast cell); or inflammation is downstream, not causal], [Crash on taper → HPA axis fragile (Pattern 5)],
  [DMF], [HIF-1α → Nrf2], [HIF-1α-driven pathology rate-limiting (@sec:hif1a-ct-cascade, @sec:wasf3-cascade)], [HIF-1α not rate-limiting; or Nrf2 activation insufficient to overcome HIF-1α], [Severe flushing → mast cell hyper-reactivity; prevented by aspirin → PGD2-mediated MCAS (Pattern 3)],
  [Doxycycline (low-dose)], [MMP-9], [MMP-9-driven ECM degradation is rate-limiting (@sec:ecm-autoantibody-cascade J3)], [MMP-9 not rate-limiting for CT symptoms], [Ø],
  [Butyrate / tributyrin], [Enteric-vagal], [Enteric-chromaffin-vagal pathway functional; gut dysbiosis → low butyrate was vagal lesion (@sec:vagal-cascade R1)], [Enterochromaffin cells damaged (Long COVID pattern); or efferent lesion], [Ø],
  [LDN + midodrine (combo)], [Multi-system probe], [Both TLR4/TRPM3 + α1 adrenergic are rate-limiting (parallel)], [If each alone works but combo fails → antagonism (pyridostigmine bradycardia counteracts midodrine pressor; use ivabradine instead) (@sec:drug-drug-interactions)], [Ø],
  [LDN + aripiprazole (combo)], [Dual CNS probe], [Neuroinflammation + DA deficiency are independent co-rate-limiting mechanisms (@sec:drug-drug-interactions)], [If additive only → shared pathway (LDN reduces microglial TNF-α → partially restores DA synthesis; aripiprazole works downstream)], [Ø],
  // Group A — High pharmacodiagnostic value (Phase 4)
  [Low-dose IL-2], [Treg expansion (autoimmune)], [Treg deficiency drives autoimmunity; Treg-suppressible pathology], [Tregs not rate-limiting; B-cell-driven or Treg-resistant autoimmunity, or non-immune pathology], [Flare (24--48h) → effector T-cell activation precedes Treg expansion (Pattern 2); No flare + no improvement → Tregs not the bottleneck (Pattern 5)],
  [Rapamycin], [mTORC1/mitophagy], [mTORC1-driven metabolic pathology rate-limiting; mitophagy restoration needed (@sec:aimm-cascade F4)], [mTORC1 not rate-limiting; or mTORC2 side effects prevent titration], [Immunosuppression at under 3 mg/week → mTORC1/C2 selectivity narrow (Pattern 4); Hyperlipidaemia → hepatic mTORC1 sensitive],
  [Fluvoxamine (low-dose)], [sigma1R (ER stress/autophagy)], [Sigma1R agonism rate-limiting — ER stress and autophagy deficit; distinct from 5-HT mechanism], [Neither sigma1R nor 5-HT reuptake is rate-limiting], [GI distress at 25--50 mg → 5-HT3 hypersensitivity blocks sigma1R window (Pattern 3); Benefit lost at 100+ mg → sigma1R is dominant; 5-HT is counterproductive],
  [Z-drugs (zolpidem)], [GABA-A α1], [GABA-A α1 system intact and responsive; sleep initiation is GABA-A-dependent], [GABA-A system not rate-limiting for sleep], [Paradoxical excitation → GABAergic inversion (NKCC1/KCC2) (Pattern 2); Absent amnesia → hippocampal α1 desensitized; Complex behaviours → striatal GABA-A dysregulation (Pattern 5)],
  [Nattokinase], [Fibrinolytic/microclot], [Microclot pathology rate-limiting for PEM/perfusion], [Microclots not rate-limiting; PEM is metabolic, mitochondrial, or neuroinflammatory], [Bleeding at fibrinolytic dose → haemostatic reserve narrow; microclots degradation-resistant (Pattern 4)],
  [Levetiracetam], [SV2A/anti-kindling], [PEM is a kindling/neuroplastic process; SV2A binding reduces PEM frequency], [Kindling not SV2A-mediated, or PEM is metabolic, not neuroplastic], [Psychiatric at low dose → limbic DA/5-HT reserve minimal (Pattern 4); Sedation → cortical hypometabolism; No effect → PEM not neuroplastic],
  // Group B — Medium pharmacodiagnostic value (Phase 4)
  [Daratumumab (anti-CD38)], [Plasma cell depletion], [AAb from CD38+ long-lived plasma cells; works where rituximab (CD20) fails (@sec:gpcr-cascade I1)], [AAb source not accessible to B-cell or plasma-cell depletion], [Infusion reactions → intact immune recognition; Neutropenia → marrow CD38+ myeloid precursors affected],
  [Ginkgo biloba], [Platelet function], [Microvascular platelet aggregation is rate-limiting], [Platelet aggregation not rate-limiting], [No bleeding at 240+ mg/day → platelet count/function intact (Pattern 5); Bleeding at standard dose → pre-existing platelet dysfunction],
  [Montelukast], [Leukotriene receptor (CysLT1)], [Leukotrienes are the dominant MCAS mediator; improvement where antihistamines fail], [Leukotrienes not rate-limiting for MCAS symptoms], [Psychiatric (depression, agitation) → paradoxical reactor in CNS leukotriene pathways (Pattern 2)],
  [Metformin], [AMPK/mitochondrial], [AMPK pathway rate-limiting for metabolic dysfunction], [AMPK not rate-limiting; or GI side effects prevent titration], [GI ceiling before metabolic benefit → gut mitochondrial vulnerability (Pattern 4); Lactic acidosis risk → pre-existing mitochondrial dysfunction],
  [GLP-1 agonists], [GLP-1R/anti-inflammatory], [GLP-1R-mediated inflammation reduction is rate-limiting], [GLP-1R pathway not rate-limiting for inflammation], [Lean mass loss > anti-inflammatory benefit → sarcopenic ME/CFS, contraindicated (Pattern 4); Severe GI → pre-existing gastroparesis],
  [DCA], [PDK/PDH], [PDH phosphorylation rate-limiting for metabolic block (@sec:pdh-cascade E2)], [PDH not rate-limiting; metabolic block downstream of PDH], [Neuropathy at low cumulative dose → pre-existing SFN vulnerability (Pattern 4); No lactate reduction → PDH not bottleneck],
  [Bromocriptine/Rotigotine], [D2/D3 dopamine], [Same as pramipexole: D2/D3 postsynaptic receptors intact (@sec:side-effects-diagnostic Pattern 1)], [Same as pramipexole: lesion not at D2/D3], [Same as pramipexole: nausea/OH at RLS dose → D2 supersensitivity; rotigotine patch → continuous delivery to distinguish PK vs PD ceiling],
  // Group C — Supplements with low diagnostic value (Phase 4)
  [PEA (palmitoylethanolamide)], [PPAR-α/microglial], [PPAR-α-mediated microglial modulation rate-limiting], [PPAR-α pathway not rate-limiting], [Ø — minimal side effects; null non-informative],
  [Devil's claw (harpagoside)], [COX/TNF-α (herbal)], [COX/TNF-α-mediated inflammation rate-limiting], [COX/TNF-α not rate-limiting for pain], [Ø — mild GI; null non-informative],
  [Quercetin], [CD38/flavonoid], [CD38-mediated NAD⁺ degradation rate-limiting (@sec:nad-cascade G2)], [CD38 not the dominant NAD⁺ sink], [Ø — flavonoid supplement; combined with NMN/NR for CD38 probe],
  [ALA (alpha-lipoic acid)], [PDH cofactor + antioxidant], [PDH cofactor deficiency + oxidative stress rate-limiting (@sec:pdh-cascade E2)], [PDH cofactor/oxidative stress not rate-limiting], [Ø],
  [NADH], [ETC electron donor], [ETC Complex I electron donor deficiency rate-limiting], [NADH not rate-limiting; or ETC downstream block], [Worsening → Complex I electron flux increases ROS downstream of block (Pattern 5)],
  // NMN/NR and Creatine already in matrix (lines 1925, 1927); not duplicated here
  [Oxaloacetate], [TCA cycle intermediate], [TCA cycle flux limitation at oxaloacetate entry], [TCA cycle not rate-limiting], [Ø — nutraceutical; null non-informative],
  [DHEA], [Neurosteroid/androgen precursor], [Neurosteroid or androgen deficiency rate-limiting], [Androgen/neurosteroid axis not rate-limiting], [Ø — hormonal supplement; androgenic side effects possible but non-diagnostic],
  [DPP-4 inhibitors (sitagliptin)], [GLP-1/GIP preservation], [Endogenous incretin preservation rate-limiting], [Incretin axis not rate-limiting], [Ø — null non-informative at supplement-level dosing],
  [Ambrisentan], [Endothelin receptor (ETA)], [Endothelin-mediated vasoconstriction rate-limiting for PAH/POTS], [Endothelin not rate-limiting for vascular symptoms], [Ø — PAH-specific; minimal diagnostic value for ME/CFS],
  [Epoprostenol], [Prostacyclin (IP receptor)], [Prostacyclin deficiency rate-limiting for pulmonary vasodilation], [Prostacyclin pathway not rate-limiting], [Ø — PAH-specific; minimal diagnostic value for ME/CFS],
  [Berberine], [AMPK/mTOR (natural)], [AMPK/mTOR pathway rate-limiting (natural metformin analog)], [AMPK pathway not rate-limiting; or GI prevents titration], [GI ceiling → gut AMPK activation (Pattern 4)],
  [Rasagiline/Selegiline], [MAO-B / DA degradation], [DA degradation rate-limiting for synaptic DA; accelerated DA turnover confirmed (@sec:dopamine-convergence)], [DA degradation not rate-limiting; synthesis, release, or postsynaptic is bottleneck], [Serotonin syndrome → CYP2D6 poor metabolizer (selegiline) or idiosyncratic 5-HT sensitivity (rasagiline); Rasagiline-safe but selegiline-toxic → MAO-A crossover; No DA benefit → COMT/DAT dominates DA clearance],
  [Ambroxol], [TRPV1 antagonist + mucolytic], [TRPV1-mediated pain/PEM rate-limiting (@sec:trpv1-cascade B1); mucolytic benefit → airway clearance limits PEM], [TRPV1 not rate-limiting; or ambroxol does not reach arteriolar TRPV1], [GI upset → enteric TRPV1 hypersensitivity (visceral/IBS); No PEM reduction → TRPV1 not PEM bottleneck],
  [5-HTP], [Serotonin precursor (bypasses IDO)], [Serotonin synthesis is rate-limiting; IDO tryptophan drain confirmed], [Serotonin synthesis not rate-limiting; or IDO drain is absent], [GI distress at 50 mg → gut serotonin hypersensitivity (Pattern 3); Serotonin syndrome at 50-100 mg → MAO-A dysfunction],
  [Niacin], [Mast cell PGD2 (HCA2 activation)], [— (pure side-effect probe)], [— (not a therapeutic probe)], [Flush threshold at 25-500 mg → cutaneous MCAS PGD2 hyper-reactivity (Pattern 3); Flush prevented by aspirin → PGD2-mediated; prevented by antihistamines → histamine-mediated],
  [Ketamine (sub-anesthetic)], [NMDA antagonist], [NMDA-mediated excitotoxicity (QUIN-driven) rate-limiting for pain/cognition], [NMDA system not rate-limiting], [Psychotomimetic at 0.1 mg/kg → NMDA hypofunction (KYNA dominance, Pattern 4); Pain relief without SE → QUIN-driven excitotoxicity],
  [Celecoxib/Etoricoxib], [COX-2 selective], [COX-2-driven inflammation rate-limiting (@sec:trpv1-cascade B2)], [COX-2 not rate-limiting; inflammation COX-1/complement/mast-cell/non-inflammatory], [Fatigue worsening at 100 mg BID → COX-2-derived PGE2 maintaining perfusion/mitochondria/HPA axis (Pattern 4)],
)

*Consequence:* This matrix is the chapter's diagnostic logic condensed into lookup form. For each drug-hypothesis pair, it provides the positive inference, the null inference, and the side-effect inference. The matrix operationalizes the chapter's core claim: every drug trial — positive, null, or side-effect-producing — generates a diagnostic output. The output is this table's three columns of inference.
*Origin:* cross-reference synthesis across all preceding sections.
