#import "../../../../shared/environments.typ": *

==== Scope Gaps

The framework does not address:
- *Persistent viral replication in tissue sanctuaries (CNS, DRG, enteric nervous system):* Antivirals discussed are for systemic herpesvirus reactivation, not sanctuary-site replication. A null antiviral response does not rule out tissue-compartmentalized viral persistence — oral valacyclovir does not achieve therapeutic CNS concentrations.
- *Structural lesions (white-matter loss, neuronal dropout, fibrosis):* Some symptoms may be from irreversible structural damage, not ongoing dysfunctional signaling. No drug can restore lost tissue. The framework assumes the pathology is functional and reversible — a drug that fails may be targeting a node that is structurally absent.
- *Sleep architecture defects (alpha-delta sleep, absent slow-wave sleep, circadian disruption):* Sleep disorders are discussed as consequences of other mechanisms (glymphatic failure, hypothalamic inflammation), but primary sleep pathology (narcolepsy, circadian rhythm disorder, sleep-disordered breathing) is not in the cascade models. A null response across all probes may reflect undiagnosed primary sleep pathology.
- *Nutritional deficiencies and malabsorption:* CoQ10, vitamins, and amino acids are discussed as probes, but frank nutritional deficiency (thiamine deficiency from SIBO, B12 deficiency from autoimmune gastritis, iron deficiency from chronic inflammation) is not systematically excluded before probing. A null response to mitochondrial supplements may reflect substrate deficiency, not mitochondrial dysfunction.
- *Psychiatric comorbidity as confound:* Depression, anxiety, PTSD, and ADHD share symptoms with ME/CFS and alter drug responses (placebo response is higher in depression; stimulant response differs in comorbid ADHD). The framework does not adjust for psychiatric comorbidity, which may produce false positives and negatives.
- *Deconditioning as confound:* A patient who has been bedbound for years has cardiovascular deconditioning that produces orthostatic intolerance independent of autonomic pathology. Midodrine may partially work (increasing vascular tone in deconditioned vessels), but the response does not confirm neuropathic POTS — it may be compensating for deconditioning. The framework cannot distinguish deconditioning from primary autonomic failure.
- *Age and sex effects:* Drug metabolism, receptor density, and hormonal milieu differ by age and sex. The framework's dose assumptions are based on adult physiology. Pediatric, perimenopausal, and geriatric patients may have altered pharmacokinetics that produce false nulls or false positives at standard doses.
- *Non-pharmacological interventions:* Physical therapy, cognitive behavioral approaches, pacing, and graded exercise are not pharmacological probes — but their effects also carry diagnostic information that the framework does not capture. A patient who improves with pacing but not with any drug has a lesion that is behavioural/energetic, not pharmacological.
