#import "../../../../shared/environments.typ": *

==== Step L1: Brainstem microglial activation — drug accessibility problem

*Mechanism:* The BBB in the medulla is tighter than in cortex or hypothalamus — tight junctions between brainstem capillary endothelial cells have higher expression of occludin and claudin-5. Peripheral anti-inflammatory drugs may have limited brainstem penetration. LDN (small molecule, MW 341) crosses the BBB but brainstem concentration may be lower than cortical concentration. Minocycline (MW 458, lipophilic) has good BBB penetration and may achieve better brainstem concentrations than LDN.

*Probes for brainstem neuroinflammation — the brainstem vs. cortex dissociation:*
- *LDN improves cognitive symptoms (cortical) but NOT autonomic symptoms (brainstem):* The neuroinflammation is predominantly cortical — brainstem is either not inflamed or LDN cannot access it. This is a dissociation pattern (@sec:pattern-dissociation): the same drug works in one brain region but not another because of BBB penetrance, not because of different pathology.
- *Minocycline improves autonomic symptoms (brainstem) where LDN does NOT:* Brainstem neuroinflammation confirmed. Minocycline has better brainstem penetration. The dissociation (LDN → cortical benefit, minocycline → brainstem benefit) maps the regional distribution of neuroinflammation. Treatment: minocycline for brainstem, LDN for cortex.
#finding(claim: [Brainstem inflammation responsive to multiple drug classes — BBB not a barrier], explanation: [Both LDN and minocycline improve autonomic symptoms. The brainstem inflammation is responsive to both drug classes; the BBB is not a barrier for either drug in this patient. Neuroinflammation is the dominant mechanism.], certainty: [Medium], level: [Partial root cause])
#finding(claim: [Brainstem neuroinflammation is absent, inaccessible, or has caused irreversible damage], explanation: [Neither LDN nor minocycline improves autonomic symptoms. Possible explanations: (a) autonomic dysfunction is from non-inflammatory mechanisms (GPCR AAb directly blocking receptors, structural DMV/nerve damage, ganglionic AChR AAb); (b) drugs cannot access brainstem at adequate concentrations — consider IV immunomodulation; or (c) neuroinflammation has caused irreversible structural damage to brainstem neurons.], certainty: [Low], level: [Partial root cause])
