#import "../../../shared/environments.typ": *

== Medical Gaslighting: Systemic Diagnostic Dismissal
<sec:medical-gaslighting>

Medical gaslighting---the dismissal or minimisation of patient symptoms by healthcare professionals without adequate clinical investigation---is a pervasive problem in ME/CFS that extends beyond individual clinician behaviour to reflect systemic failures in medical education, time-constrained consultation models, and the legacy of the psychogenic framing discussed in preceding sections.
The phenomenon takes several characteristic forms in ME/CFS. Patients report being told their symptoms are caused by stress, depression, or deconditioning despite objective evidence of physiological dysfunction. Post-exertional malaise is frequently overlooked or dismissed, leading to exercise recommendations that worsen the condition (Section @sec:exercise-debates). Diagnostic investigations are curtailed because unremarkable standard laboratory results are interpreted as excluding organic disease, rather than as expected findings in a condition that affects systems not captured by routine panels.
Contributing systemic factors include limited ME/CFS content in medical training (most physicians receive no structured education on the condition), consultation time constraints that prevent thorough clinical evaluation, unconscious bias along gender and socioeconomic lines, and the historical psychogenic framing that positioned ME/CFS as a behavioural rather than biomedical condition. The gender dimension is particularly significant: ME/CFS disproportionately affects women, and a documented gender health gap means that women's symptoms are more likely to receive delayed or dismissive responses across medical specialties.
The consequences extend beyond diagnostic delay. Repeated dismissal produces measurable psychological harm: anxiety disorders, depression, deep distrust of medical institutions, and---in severe cases---medical post-traumatic stress that causes patients to avoid seeking care even when deteriorating. This avoidance creates a vicious cycle in which undertreated patients become more severely ill, reinforcing the perception that ME/CFS is intractable.
The historical parallel to multiple sclerosis is instructive. MS patients---particularly women---were historically diagnosed as hysterical, their motor symptoms attributed to psychological conversion disorder. The biological basis of MS was eventually established, but the decades of psychogenic dismissal caused preventable suffering. The 1984 Lake Tahoe ME/CFS outbreak was similarly dismissed as mass hysteria despite subsequently generating thousands of peer-reviewed publications validating the condition's biological basis. Whether ME/CFS is currently at the inflection point where MS was in the 1960s---accumulating biological evidence coexisting with institutional resistance to abandoning the psychogenic model---remains an open question (see Section @sec:psychosomatic-parallels).


