#import "../../../shared/environments.typ": *

#clinical-finding(title: [Environmental-Stimuli Reduction Is a Medical Necessity, Not Kindness])[

For people with severe/very-severe ME/CFS, reducing environmental stimuli and demands on exertion is not an act of accommodation or kindness — it is a protective medical intervention that prevents subsequent deterioration, which in some cases is long term and irreversible. The Science for ME (2026) factsheet, authored by Prof. Jonathan Edwards and S4ME members, states this explicitly: "the need for reduction in stimulation from exertion and environment for people with ME/CFS is a unique situation, being a medical necessity rather than a matter of kindness" @S4ME2026ManagementSevereVerySevere. Exertion or environmental stimuli can tip a person from a stable functional state into a very severe state for prolonged periods, and the mechanisms of this deterioration are not yet understood — but the consistent patient experience is that these exposures must be respected until effective treatment exists @S4ME2026ManagementSevereVerySevere.

- *Hospital admission adjustments:* Because hospital environments are rich in noise, movement, light, smells, and extra exertion, the factsheet specifies that planned admissions must build in reasonable adjustments: a single room; effective blinds to reduce light during the day and full darkness at night; freedom from intrusive noise; no use of scented cleaning products; communication aids including a staff-alert signaling system and written rather than spoken messaging when needed; and accompaniment by a person who understands the patient's needs (lying flat, sound protection, minimized stimuli) for any movement around the hospital for investigations @S4ME2026ManagementSevereVerySevere.
- *Stimulus control at home:* Lighting reduced with curtains or dimmable lights; sound reduced with ear defenders or earplugs and by reducing talking during visits; scented toiletries and cleaning products avoided; slow and gentle movements when adjusting bedding or giving care; the patient warned before movement or touch; a position-adjustable bed to optimise positioning for orthostatic intolerance and feeding; hoists and wheelchairs to reduce unnecessary exertion @S4ME2026ManagementSevereVerySevere.
- *Drug-withdrawal caution:* Drugs prescribed for symptomatic control with a doubtful evidence base should not be withdrawn at the time of a hospital admission, when withdrawal is likely to add to the stresses of the inpatient environment @S4ME2026ManagementSevereVerySevere.

*Certainty:* 0.40 (expert-consensus/advocacy clinical guidance from the S4ME factsheet; consistent with severe-care expert statements such as Montoya et al.\ 2021 @Montoya2021SevereCare; no controlled trial). *Evidence type:* expert-opinion clinical guidance. *Population:* severe/very-severe ME/CFS. *Severity:* severe and very severe.

*Limitations:* Consensus/advocacy rather than primary evidence; individual stimulus tolerance varies, and the factsheet itself notes requirements depend on the individual; the "irreversible deterioration" claim is grounded in clinical experience rather than a prospective study.

*Consequence:* For clinicians and hospital administrators, environmental-stimuli reduction must be treated as a medical order (single room, blackout, no scent, minimal noise) rather than a courtesy to be granted when resources allow — because failing to provide it risks provoking a severe, potentially irreversible deterioration in a patient who is already housebound or bedbound.
] <cf:environmental-stimuli-medical-necessity>
