#import "../../../../../shared/environments.typ": *

#speculation(title: [The EP3R "Stuck Switch" Hypothesis — a Candidate, Not a Demonstrated Mechanism])[
A speculation (not a finding) that a defective fever↔torpor toggle could, in principle, contribute to persistent low-energy fatigue in ME/CFS: preoptic EP3-receptor neurons route between fever (hypermetabolic) and torpor-like (hypometabolic) states in rodents @Machado2025PreopticSwitch. *If* that two-way switch could be left in the energy-conserving position after the acute infection — e.g., via EP3R desensitization, biased signaling, or failure of the fever arm to re-engage — it would offer one way to account for persistent low-energy symptoms with normal peripheral inflammatory markers, without requiring ongoing neuroinflammation @KomaroffDantzer2025SymptomPersistence. Note that this restates persistence in circuit vocabulary rather than identifying a demonstrated lesion: no EP3R desensitization, receptor bias, or switch-latch state has been shown in ME/CFS or even in the rodent model as a *persistent* (post-washout) state. A simpler rival reading must be stated plainly: the absence of peripheral inflammation in chronically-fatigued patients (Omdal null) may mean the sickness-behavior model simply does not extend to that inflammation-negative subset, whose symptoms may have a different cause @Omdal2026LCFatigueStress — the stuck-switch mechanism is needed only if the phenotype in that subset is to be retained within this framework. (Certainty: 0.25. The EP3R two-way switch is rodent-established; the persistent-switch-failure application to human ME/CFS has zero direct evidence and no demonstrated latch in any species.)

(Translation gap: animal (rodent) → human. No human evidence of EP3R desensitization or switch failure exists. Rodent torpor-with-hypothermia physiology is not reproduced in ME/CFS.)

(Severity applicability: unknown — not severity-stratified; presented as a general candidate without confirmed applicability to any severity subgroup.)

*Falsifiable prediction:* The discriminating prediction must target a reversible switch, not a permanently stuck one. If a transient PGE#sub[2] load can *latch* the EP3R switch into sustained torpor output after ligand washout (bistability — the property this hypothesis requires), the rodent model would first demonstrate a persistent, acute-challenge-reversible state; absent that, the human question never arises. In humans, the phenotype prediction is a persistently low defended temperature set-point with *acute disengageability* — i.e., normal physiology returns briefly under a strong thermoregulatory/arousal challenge, then reverts. Because a peripheral immune-cell (e.g., PBMC) EP3R measure cannot be assumed to report preoptic-neuron EP3R state, PBMC reads are not a valid proxy and are excluded from this prediction; a CNS-proximal readout (CSF or post-mortem marker, ultra-high-field imaging of the MnPO) would be required. The claim is falsified if no persistent, reversible latch is demonstrable in the rodent switch under PGE#sub[2] washout, or if ME/CFS patients show no maintained low set-point with acute disengageability.

*Origins:* brainstorm (re-run) — EP3R two-way-switch failure. This is a *hypothesis-generation* entry, not clinical guidance; no switch-resetting intervention exists or is in trials.

*Consequence:* If the brain's energy-saving switch can be temporarily stuck (and reversibly unlatched) rather than permanently broken, it would point toward a possible recovery mechanism — but this remains a target-identification hypothesis with no treatment pathway today, and no safe bedside test follows from it.
] <spec:ep3r-stuck-switch>
