#import "../../../../shared/environments.typ": *

#synthesis(title: [Orthostatic Dysautonomia May Form a Spectrum Below the HR Threshold, but the Recognition Claim Is Not Yet Validated])[

The convergent evidence suggests that the POTS heart-rate threshold does not reliably capture the burden of orthostatic dysautonomia in ME/CFS: an international expert consensus recognizes a "non-POTS dysautonomia" population below the $gt.eq 30$/$gt.eq 40$ bpm cutoff, and single-center data show the HR rise does not predict symptom burden (@cf:pots-hr-threshold-nonpredictive). This raises the possibility of treating orthostatic intolerance as a graded dysfunction rather than a pass/fail diagnosis, consistent with the finding that a large fraction of ME/CFS patients with orthostatic symptoms do not meet formal POTS criteria. (Overall certainty: 0.30 --- the recognition claim's strength. The 0.44 figure in @cf:pots-hr-threshold-nonpredictive is the discounted certainty of the underlying evidence; the operative certainty of the recognition *construct itself* is 0.30 per @lim:pots-threshold-recognition-limits, because it rests on consensus plus single-center registries with no prospective multi-center validation.)

The claim is conditional, not established. No prospective study shows that reclassifying subthreshold patients changes outcomes, and broadening recognition carries an unquantified over-diagnosis risk that could dilute a distinct syndrome (@lim:pots-threshold-recognition-limits). The HR threshold, whatever its flaws, currently enforces specificity against inappropriate sinus tachycardia and deconditioning. Until a multi-center, outcome-linked study exists, the honest position is to recognize the subthreshold population clinically while retaining diagnostic discipline (@lim:pots-threshold-recognition-limits).

*Implication (clinical decision path):* For a patient with orthostatic symptoms and functional impairment who does not meet the HR-rise cutoff, the practical first step is low-risk, symptom-driven management consistent with the "POTS as Primary" guidance above: salt and fluid loading, compression, and cautious pacing (see @req:orthostatic-testing). This is warranted on symptom burden alone, independent of the HR threshold. If symptoms persist despite these, reassess with formal autonomic testing (tilt/HUT, sudomotor) before escalating to prescription agents (e.g., fludrocortisone, ivabradine) or assigning a formal dysautonomia diagnosis — the threshold remains the guard against labeling deconditioning or inappropriate sinus tachycardia as disease. This discipline does not negate the HR axis as a therapeutic target: the one outcome-linked RCT in this area (Uppal et al. 2026) shows ivabradine and propranolol do lower orthostatic tachycardia, and symptom response is more selective than HR lowering @Uppal2026IvabradinePropranolol. Severity applicability is unknown for the subthreshold population, so the decision path above should be read cautiously in severe/very-severe ME/CFS, where salt loading and standing-based measures require individual tailoring. The recognition claim supports clinical awareness and first-line care, not premature drug escalation or a loosened formal diagnosis. For research, a prospective multi-center test is needed of whether threshold-free recognition changes outcomes and does not inflate false-positive diagnosis.

*Consequence:* Clinicians and researchers should treat orthostatic dysautonomia as a possibly graded problem -- many patients below the heart-rate cutoff may be genuinely affected -- while waiting for studies that prove recognizing them improves care before loosening the formal diagnosis.

] <syn:pots-consensus-recognition>
