#import "../../../../shared/environments.typ": *

#synthesis(title: [Lifetime Low-Energy Patients Are a Recognition Gap and a Near-Separatrix Population, Not a Categorically Distinct Disease — But PEM, Not Baseline Energy, Is the Discriminator])[

A convergent picture emerges from this integration: lifelong energy constraint is continuous with ME/CFS at the mild end rather than categorically opposed to it, and the mild/lifetime patient is systematically excluded by a diagnostic onset criterion that is hard to operationalize and non-discriminating (@lim:lifelong-onset-criterion). Severity-based clustering and childhood-onset chronic-disabling-fatigue data show a low-reserve, mild-end population that functions on a constrained daily energy envelope (@spec:mild-constitutional-energy-spectrum), and this is the same population the causal-hierarchy model calls the near-separatrix "subthreshold reservoir" — people sitting just below the disease threshold who may be pushed over by a second hit (@sec:subthreshold-reservoir). (Overall certainty: 0.45 for the continuous-spectrum claim; the recognition *construct* is weaker at ~0.30 once the over-broadening caveats are applied @lim:mild-lifetime-critical-caveats.)

The claim is conditional, not established. Broadening recognition carries a real over-diagnosis risk of capturing tired-but-well people with no PEM (@lim:mild-lifetime-critical-caveats), and the premorbid signal may be high-energy overactivity rather than low baseline energy (@spec:prodromal-syndrome). The discriminating feature is not the resting energy level but the presence of a new, definite post-exertional malaise (@lim:lifelong-onset-criterion). No longitudinal cohort has yet shown that mild/lifetime-energy patients actually transition to moderate or severe ME/CFS — that transition is the central unanswered question (@pred:mild-lifetime-transition-cohort).

*Implication (clinical decision path):* For a patient who reports having always been tired, do not treat "lifelong fatigue" as an exclusion. Screen baseline energy level and current PEM as two independent axes; where a new, definite PEM is present, proceed to a full ME/CFS assessment (@oq:mild-lifetime-case-recognition). Where PEM is absent, the label should not be applied — but low-harm energy-envelope/pacing care remains warranted on symptom burden alone, independent of diagnosis. Because the mild end may lack a reportable PEM signature (@lim:mild-lifetime-critical-caveats), a PEM-negative low-energy patient is best held in an observational/pending status — symptom-tracked and re-screened for PEM after exertion — rather than either diagnosed or dismissed, so the PEM gate does not silently re-exclude the very population the proposal aims to recognise. This discipline lets recognition improve access without loosening the formal diagnosis. For research, a prospective cohort tracking lifetime-low-energy individuals for emergence of PEM and severity transition is the decisive test.

*Consequence:* Clinicians should stop dismissing the "always tired" patient and instead look specifically for new-onset PEM — the feature that separates a tired constitution from mild ME/CFS — while reserving the diagnosis for those who have it.

] <syn:mild-lifetime-recognition>
