#import "../../../../../shared/environments.typ": *

#achievement(title: [Kerrebijn 2026 Fibromyalgia GWAS: 26 Risk Loci and Brain-Enriched Heritability])[
*Certainty: 0.68 (discounted from raw 0.85 by 0.80 population weight — fibromyalgia is a comorbid condition, not an ME/CFS cohort).* Kerrebijn et al.\ (2026, _Nature Medicine_) conducted the largest multi-ancestry genome-wide association study (GWAS) meta-analysis of fibromyalgia to date: 2,563,755 individuals (54,629 cases, 2,509,126 controls) from 11 cohorts, identifying 26 genome-wide-significant risk loci @Kerrebijn2026FibromyalgiaGWAS.

The strongest association was a coding variant in _HTT_, the causal gene for Huntington's disease (inframe glutamic-acid deletion, exon 58; OR 1.09). Gene prioritization implicated the _HTT_ regulator _GPR52_ alongside diverse neural genes (_DCC_, _DRD2/NCAM1_, _MDGA2_, _CELF4_). Fibromyalgia heritability (observed scale, 10.4%) was *exclusively enriched within brain tissues and neural cell types* (dentate gyrus, enteric neurons, interneurons, cortical and striatal projection neurons), with no immune or glial enrichment. (Note: this observed-scale figure is not directly comparable to the liability-scale ME/CFS SNP-heritability of 9.5% in Section @sec:snp-heritability.)

The study found strong, positive genetic correlation (rg > 0.7) with low back pain, post-traumatic stress disorder, and irritable bowel syndrome, as well as with musculoskeletal and joint-pain traits (myalgia, joint pain, hypermobility, cervicobrachial syndrome) relevant to the ME/CFS hypermobility comorbidity, and pervasive positive correlation with depression, somatoform/dissociative disorders, and migraine. Despite fibromyalgia's 87.7% female preponderance, the inter-sex genetic correlation was 1.03 — near-identical architecture in males and females. Critically, there was no significant MHC signal and no immune/glial heritability enrichment, providing genetic evidence against a primarily autoimmune architecture @Kerrebijn2026FibromyalgiaGWAS.

*Falsifiable prediction:* An independent multi-ancestry fibromyalgia GWAS will replicate the majority of the 26 loci (particularly _HTT_/exon-58 and _GPR52_) and confirm exclusive brain/neural-cell-type heritability enrichment. Falsified if replication shows peripheral (immune or glial) enrichment of comparable or greater magnitude.

*Consequence:* This gives fibromyalgia a robust, brain-enriched genetic basis consistent with a central-nervous-system (nociplastic) role, which matters for ME/CFS because the two conditions frequently co-occur and may share a central rather than peripheral genetic vulnerability — informing the comorbidity relationship, with the direct genetic correlation still to be measured. (Severity applicability: unknown — fibromyalgia GWAS cohorts not stratified by ME/CFS severity.)
] <ach:kerrebijn-fibromyalgia-gwas>
