#import "../../../../shared/environments.typ": *

=== Retinal and Corneal Imaging as CNS Windows
<sec:retinal-cns-window>

The retina is embryologically part of the central nervous system and the only CNS tissue accessible by non-invasive, high-resolution imaging. Recent Long COVID studies have demonstrated that retinal and corneal imaging can detect neuroinflammation, small fiber pathology, and protein aggregation — findings that may be relevant to ME/CFS where direct CNS tissue access is severely limited.

#speculation(title: [Retinal and Corneal Imaging May Detect CNS Pathology Invisible to Blood Tests in ME/CFS])[
*(Origin: literature synthesis.)* *(Certainty: 0.25.)* Three independent lines of evidence support the anterior visual pathway as a potential biomarker window into CNS pathology:

*Retinal Aβ pathology from viral exposure.* Miller et al. (2025, *Science Advances*) demonstrated that SARS-CoV-2 induces Alzheimer's disease-related amyloid-β (Aβ) pathology in ex vivo human retinal explants and iPSC-derived retinal organoids @Miller2025RetinalAmyloid. The Aβ accumulation was reversible with an NRP1 inhibitor (not clinically available). While this was an ex vivo study (not in living patients), it establishes that SARS-CoV-2 exposure can directly trigger amyloid pathology in CNS tissue — and that the retina is a visible readout. Baraniuk found amyloid products in ME/CFS as early as 2010, and Pretorius has documented fibrin amyloid microclots, suggesting amyloid pathology may be convergent across compartments.

*Retinal microcirculation correlates with fatigue.* Schlick et al. (2022, n=40) used optical coherence tomography angiography (OCT-A) to demonstrate that retinal microcirculation impairment correlates with chronic fatigue severity in post-COVID syndrome @Schlick2022RetinalMicrocirc. Reduced retinal vessel density and increased foveal avascular zone area — markers of microvascular dysfunction — distinguished fatigued from non-fatigued patients, independent of systemic inflammatory markers.

*Corneal nerve fiber loss as neuroinflammation marker.* Cañadas et al. (2023, n=50) used corneal confocal microscopy to demonstrate reduced corneal small nerve fiber density and increased immune cell (Langerhans cell) infiltration in Long COVID patients two years post-infection @Cañadas2023CornealConfocal. Corneal nerve fiber loss is a validated marker of small fiber neuropathy, and the presence of immune cells suggests ongoing local neuroinflammation at a CNS-adjacent site.

*Relevance to ME/CFS:* Small fiber neuropathy is documented in approximately 30% of ME/CFS patients. Retinal and corneal imaging could provide: (a) a non-invasive window into CNS neuroinflammation (retinal microglia are CNS microglia), (b) an objective correlate of the brain fog and cognitive dysfunction reported by patients, and (c) a longitudinal biomarker that can be repeated without radiation (unlike PET) or lumbar puncture. No retinal or corneal imaging study has been performed in ME/CFS.

*Falsifiable prediction:* A cross-sectional study of 100 ME/CFS patients versus matched controls would show: (a) reduced retinal vessel density on OCT-A correlating with cognitive dysfunction severity, (b) reduced corneal nerve fiber density on confocal microscopy correlating with SFN symptoms, and (c) retinal OCT markers of neuroinflammation (increased retinal nerve fiber layer thickness in acute-phase patients, thinning in chronic patients) that track with disease duration. Falsified if retinal and corneal parameters are indistinguishable from controls in patients with documented cognitive dysfunction and SFN.

*Consequence:* A 15-minute non-invasive eye scan could replace lumbar puncture or PET-MRI for CNS biomarker monitoring in ME/CFS — making repeated measurements feasible in clinical trials where serial CSF sampling or repeated PET scans would be impractical or unsafe.
] <spec:retinal-corneal-cns-window>

#open-question(title: [Can Retinal Aβ Imaging Distinguish Post-Infectious Neurodegeneration Risk from Protective Amyloid Response?])[
*(Origin: literature synthesis.)* Miller's finding that SARS-CoV-2 induces retinal Aβ @Miller2025RetinalAmyloid, combined with VanElzakker's 4-fold elevated p-tau217 in Long COVID @VanElzakker2024NeuroinflammationPASC, and the large epidemiological studies showing increased dementia risk in post-COVID populations (84% increased risk at 12 months in a systematic review covering 940,000 survivors), collectively raise the question of whether post-infectious syndromes accelerate neurodegenerative processes. However, there is an alternative hypothesis: Aβ may be an antimicrobial peptide produced as a protective response to infection, and its accumulation in post-infectious syndromes may represent a successful defense mechanism rather than early Alzheimer's pathology. Increased new-onset dementia in COVID-19 patients over 50 is driven primarily by respiratory and vascular problems, not by the Alzheimer's-associated amyloid/tau profile. The retinal Aβ paradigm could potentially distinguish between these two models — protective antimicrobial response vs pathological neurodegeneration — by tracking whether Aβ accumulation correlates with neurodegeneration markers (retinal nerve fiber layer thinning) or with infection resolution markers. No such study has been done.

*Consequence:* If retinal Aβ accumulation in post-infectious syndromes is protective rather than pathological, anti-amyloid therapies (which are being explored for Alzheimer's) would be contraindicated — they would remove a defense mechanism. Distinguishing between these models is essential before any anti-amyloid intervention is considered for ME/CFS or Long COVID.
] <oq:retinal-ab-protective-vs-pathological>
