#import "../../../../shared/environments.typ": *

=== Retinal and Corneal Imaging as CNS Windows
<sec:retinal-cns-window>

The retina is embryologically part of the central nervous system and the only CNS tissue accessible by non-invasive, high-resolution imaging. Recent Long COVID studies have demonstrated that retinal and corneal imaging can detect neuroinflammation, small fiber pathology, and protein aggregation — findings that may be relevant to ME/CFS where direct CNS tissue access is severely limited.

#speculation(title: [Retinal and Corneal Imaging May Detect CNS Pathology Invisible to Blood Tests in ME/CFS])[
*(Origin: literature synthesis.)* *(Certainty: 0.25.)* Three independent lines of evidence support the anterior visual pathway as a potential biomarker window into CNS pathology:

*Retinal Aβ pathology from viral exposure.* Miller et al. (2025, *Science Advances*) demonstrated that SARS-CoV-2 induces Alzheimer's disease-related amyloid-β (Aβ) pathology in ex vivo human retinal explants and iPSC-derived retinal organoids @Miller2025RetinalAmyloid. The Aβ accumulation was reversible with an NRP1 inhibitor (not clinically available). While this was an ex vivo study (not in living patients), it establishes that SARS-CoV-2 exposure can directly trigger amyloid pathology in CNS tissue — and that the retina is a visible readout. Baraniuk found amyloid products in ME/CFS as early as 2010, and Pretorius has documented fibrin amyloid microclots, suggesting amyloid pathology may be convergent across compartments.

*Retinal microcirculation correlates with fatigue.* Schlick et al. (2022, n=40) used optical coherence tomography angiography (OCT-A) to demonstrate that retinal microcirculation impairment correlates with chronic fatigue severity in post-COVID syndrome @Schlick2022RetinalMicrocirc. Reduced retinal vessel density and increased foveal avascular zone area — markers of microvascular dysfunction — distinguished fatigued from non-fatigued patients, independent of systemic inflammatory markers.

*Corneal nerve fiber loss as neuroinflammation marker.* Cañadas et al. (2023, n=50) used corneal confocal microscopy to demonstrate reduced corneal small nerve fiber density and increased immune cell (Langerhans cell) infiltration in Long COVID patients two years post-infection @Cañadas2023CornealConfocal. Corneal nerve fiber loss is a validated marker of small fiber neuropathy, and the presence of immune cells suggests ongoing local neuroinflammation at a CNS-adjacent site. Notably, Azcue et al. (2025) have already demonstrated increased corneal small fiber tortuosity in ME/CFS using the same technique @Azcue2025sfn, providing direct evidence of corneal-level pathology in ME/CFS itself — though retinal OCT-A has not yet been studied. This corneal-nerve arm is further corroborated by the symptom-linked post-COVID ocular syndrome described below (@cf:postcovid-ocular-syndrome); the retinal OCT-A arm, however, remains untested in ME/CFS, so the overall speculation certainty is unchanged.

*Relevance to ME/CFS:* Small fiber neuropathy is documented in approximately 30% of ME/CFS patients. Retinal and corneal imaging could provide: (a) a non-invasive window into CNS neuroinflammation (retinal microglia are CNS microglia), (b) an objective correlate of the brain fog and cognitive dysfunction reported by patients, and (c) a longitudinal biomarker that can be repeated without radiation (unlike PET) or lumbar puncture. Corneal confocal microscopy has already been performed in ME/CFS and shows increased small fiber tortuosity @Azcue2025sfn, but retinal OCT-A has not yet been studied.

*Falsifiable prediction:* A cross-sectional study of 100 ME/CFS patients versus matched controls would show: (a) reduced retinal vessel density on OCT-A correlating with cognitive dysfunction severity, (b) reduced corneal nerve fiber density on confocal microscopy correlating with SFN symptoms, and (c) retinal OCT markers of neuroinflammation (increased retinal nerve fiber layer thickness in acute-phase patients, thinning in chronic patients) that track with disease duration. Falsified if retinal and corneal parameters are indistinguishable from controls in patients with documented cognitive dysfunction and SFN.

*Consequence:* If validated (and this remains entirely unvalidated for ME/CFS — cert 0.25), a non-invasive eye scan could provide information currently only obtainable through invasive procedures — making repeated CNS biomarker measurements feasible in clinical trials. This is a research-tool proposal, not a clinical replacement for established diagnostics.
] <spec:retinal-corneal-cns-window>

#open-question(title: [Can Retinal Aβ Imaging Distinguish Post-Infectious Neurodegeneration Risk from Protective Amyloid Response?])[
*(Origin: literature synthesis.)* Miller's finding that SARS-CoV-2 induces retinal Aβ @Miller2025RetinalAmyloid, combined with VanElzakker's 4-fold elevated p-tau217 in Long COVID @VanElzakker2024NeuroinflammationPASC, and large epidemiological evidence of increased dementia risk in post-COVID populations, collectively raise the question of whether post-infectious syndromes accelerate neurodegenerative processes. However, there is an alternative hypothesis: Aβ may be an antimicrobial peptide produced as a protective response to infection, and its accumulation in post-infectious syndromes may represent a successful defense mechanism rather than early Alzheimer's pathology. Increased new-onset dementia in COVID-19 patients over 50 is driven primarily by respiratory and vascular problems, not by the Alzheimer's-associated amyloid/tau profile. The retinal Aβ paradigm could potentially distinguish between these two models — protective antimicrobial response vs pathological neurodegeneration — by tracking whether Aβ accumulation correlates with neurodegeneration markers (retinal nerve fiber layer thinning) or with infection resolution markers. No such study has been done.

*Consequence:* If retinal Aβ accumulation in post-infectious syndromes is protective rather than pathological, anti-amyloid therapies (which are being explored for Alzheimer's) would be contraindicated — they would remove a defense mechanism. Distinguishing between these models is essential before any anti-amyloid intervention is considered for ME/CFS or Long COVID.
] <oq:retinal-ab-protective-vs-pathological>

#clinical-finding(title: [Post-COVID Ocular Syndrome Directly Confirms the Dysautonomia–Neuropathy–Immune Triad in an Accessible Tissue])[
*(Evidence type: observational study — prospective cross-sectional.)* *(Certainty: 0.75.)* Moustardas et al.\ (2026, _Nature Communications_) examined 100 non-hospitalised patients with persistent ocular symptoms 3 months to 3 years after _mild_ COVID-19 against 32 mild-COVID controls without ocular symptoms @moustardas2026ocular. One in three affected patients was on full or part-time sick leave. The defining clinical observation is that _standard ophthalmic examination was normal_ — abnormalities emerged only on specialised testing, exactly the "normal routine workup, pathology on specialised assay" pattern that characterises ME/CFS itself.

Specialised testing revealed a convergent triad: (a) *peripheral neuropathy* — corneal neurodegeneration and chronic dendritic/T-cell activation on corneal confocal microscopy, extending the small-fiber findings of Cañadas et al.\ @Cañadas2023CornealConfocal and Azcue et al.\ @Azcue2025sfn from research biomarker to symptom-linked pathology; (b) *dysautonomia* — weakened autonomic pupillary reflexes (pupils admitting excess light, mechanistically explaining photophobia) and adult-onset strabismus attributed to oculomotor nerve involvement; and (c) *immune dysregulation* — a tear-fluid proteomic signature of CD4+ T-cell dysregulation that matched protein patterns previously reported in blood and tissue in _severe and fatal_ COVID-19. Two diagnostic models achieved 77% (instrument-only) to 91% (instrument + tear proteomics) accuracy.

This finding is *confirmatory* of the causal cascade developed in Chapter @ch:causal-hierarchy: a post-viral insult propagating through autonomic, small-fiber, and T-cell-mediated immune channels to produce organ-specific dysfunction. The eye is simply a tissue where all three channels are simultaneously and non-invasively measurable. It is _not_ evidence that post-COVID ocular syndrome is identical to ME/CFS — the Moustardas cohort was not screened against ME/CFS diagnostic criteria (see Limitation). The convergent argument assembling this finding with the SFN model and T-cell readout is synthesised in @syn:postcovid-ocular-triad-model.

*Consequence:* Patients whose eye symptoms after a mild infection are dismissed because routine eye exams look normal now have an objective explanation and a testable diagnostic pathway; for ME/CFS research, the same corneal-confocal and tear-proteomic tools offer an accessible window onto the dysautonomia and small fiber neuropathy the disease is thought to share.
] <cf:postcovid-ocular-syndrome>

#limitation(title: [Post-COVID Ocular Cohort Not Screened for ME/CFS])[
The Moustardas et al.\ cohort @moustardas2026ocular comprised post-COVID patients selected for ocular symptoms, not patients meeting ME/CFS diagnostic criteria. The mechanistic overlap (dysautonomia, small fiber neuropathy, T-cell dysregulation) is compelling, but the study does not establish that these patients have ME/CFS, nor that ME/CFS patients as a group exhibit this ocular syndrome. Severity applicability to the ME/CFS spectrum is unknown. Direct evidence would require applying the same multimodal ocular protocol to a criteria-defined ME/CFS cohort. The finding is single-study and not yet independently replicated. A literature search found no studies that examined and _failed_ to find post-COVID ocular abnormality, so publication bias toward positive findings cannot be excluded; dry-eye and convergence complaints also have mundane confounders (increased screen time during and after illness) that a symptom-selected cohort cannot separate from neuropathic causes.

*Consequence:* This result should be read as strong support for a shared mechanism, not as proof that ME/CFS patients have this eye syndrome — the honest current status is "highly suggestive, awaiting a direct ME/CFS study."
] <lim:postcovid-ocular-mecfs-gap>

Two additional open questions arise from this evidence but remain speculative. First, whether corneal Langerhans cell density tracks CNS microglial activation — shared myeloid origin does not establish functional equivalence, and no study has measured corneal LC density and TSPO-PET signal simultaneously in any disease. Second, whether the observed tortuosity-dominant CCM pattern in ME/CFS reflects systemic SFN, trigeminal-specific neuropathy, or dry eye secondary to autonomic dysfunction — concurrent IENFD and tear-film assessment could distinguish these, but the data do not exist. Both questions are discussed in detail in Chapter @ch:cardiovascular.

