#import "../../../../shared/environments.typ": *

=== Documented ME/CFS Findings and Failure Modes


Several cofactors are required by multiple steps in the chain simultaneously. Their depletion therefore impairs energy metabolism at several nodes at once.

*Coenzyme Q10 (CoQ10/ubiquinone).* CoQ10 is the mobile electron carrier between Complexes I/II and Complex III, and also a lipid-soluble antioxidant in the inner mitochondrial membrane. Reduced CoQ10 is among the most replicated findings in ME/CFS: Holden et al.'s systematic review of 19 studies identified it in every study that measured it @Holden2020mitosysrev. The inverse correlation between CoQ10 levels and fatigue/autonomic symptom severity has been documented , and a randomised controlled trial of CoQ10 combined with NADH showed improved heart rate recovery . CoQ10 deficiency thus simultaneously impairs electron transfer (reducing ATP yield), increases electron leakage at Complexes I and III (increasing ROS), and reduces membrane antioxidant protection.


#achievement(title: [High-Quality Evidence for CoQ10 Deficiency and Treatment])[
The Maes 2009 case-control study (n=58 ME/CFS, 22 controls) demonstrated that 44.8% of ME/CFS patients have plasma CoQ10 below the lowest control value (490 micro g/L), with lower levels correlating with fatigue, autonomic, and neurocognitive symptoms @Maes2009CoQ10. A 2022 meta-analysis of 13 RCTs (n=1,126) found CoQ10 significantly reduces fatigue (Hedges' g = -0.398, p = 0.001) with dose-dependent (coefficient = -0.0017 per mg, p < 0.001) and duration-dependent (coefficient = -0.0042 per day, p = 0.007) effects @Tsai2022CoQ10fatigue. Novel cocrystal ubiquinol formulations show 2.01-3.43x higher bioavailability vs standard ubiquinone @Mei2026UbiquinolBioavailability.
]


*Cardiolipin.* Cardiolipin is a phospholipid unique to the inner mitochondrial membrane, required for the structural stability of all five ETC complexes, ANT, and the cristae architecture that concentrates the proton gradient. Its oxidation by ROS impairs all IMM-dependent functions simultaneously. Historical data report anti-cardiolipin antibodies in ME/CFS , and Molnar et al.\ highlight cardiolipin-targeting elamipretide (the SS-31 peptide, currently in trials for Barth syndrome and heart failure) as an uninvestigated therapeutic candidate for Long COVID mitochondrial dysfunction  — with equivalent theoretical rationale in ME/CFS.

*NAD#super[+]/NADH ratio.* NAD#super[+] is required by the E3 subunits of both PDC and KGDHC, by isocitrate dehydrogenase (TCA step 3), by malate dehydrogenase (TCA step 8), by Complex I, and by the sirtuin family of metabolic regulators. Two independent mechanisms threaten NAD#super[+] availability in ME/CFS: the kynurenine pathway diverts tryptophan away from NAD#super[+] synthesis, and PARP overactivation (responding to oxidative DNA damage) consumes NAD#super[+] as a substrate. Germain et al.\ found nicotinate and nicotinamide metabolism — the NAD#super[+] precursor pathway — significantly disrupted at baseline in female ME/CFS plasma (KEGG $p = 0.0006$, $q = 0.04$; $n = 60 + 45$ controls), even before exercise challenge @Germain2022exercise. Groven et al.\ independently demonstrated that kynurenine metabolite profiles distinguish CFS from fibromyalgia and controls ($n = 49/57/54$, all female): the neuroprotective KA/QA ratio was specifically reduced in CFS ($p = 0.016$), suggesting condition-specific diversion of kynurenine toward the neurotoxic/NAD#super[+]-synthetic branch @Groven2021kynurenine. Neither PARP activity (poly-ADP-ribose quantification) nor CD38 expression has been directly measured in ME/CFS — both depletion mechanisms remain inferred from indirect evidence.

The picture is complicated by the only direct PBMC NAD#super[+] measurement in ME/CFS. Heng et al.\ ($n = 61 + 61$ controls) found NAD#super[+] _elevated_ in ME/CFS white blood cells (300.3 nM vs 257.7 nM), while the ATP/ADP ratio was simultaneously _reduced_ @heng2025mecfs. This pattern — substrate accumulation upstream of a processing block — is consistent with Complex I dysfunction: NAD#super[+] is present but cannot be efficiently reduced to NADH because the ETC cannot accept electrons. It does not refute systemic NAD#super[+] insufficiency: in energy-intensive tissues (skeletal muscle, neurons), PARP overactivation and kynurenine diversion could produce genuine depletion even if PBMCs show substrate backup. No muscle biopsy NAD#super[+] data exist for ME/CFS. An earlier, lower-resolution study found serum NAD(P)H reduced in CFS (8.0 vs 10.8 nmol/mL, $n = 44 + 30$ controls) by fluorescence emission, but the method does not distinguish individual nicotinamide adenine dinucleotides and has not been replicated @Mikirova2012NADPH.

Downstream of NAD#super[+] availability, Missailidis et al.\ reported SIRT3 and SIRT6 downregulation in ME/CFS lymphoblast cell lines (transcriptomics; $n = 23$ vs 17 controls), with SIRT2 upregulated @Missailidis2021substrates. SIRT3 is the principal mitochondrial deacetylase regulating oxidative metabolism; its downregulation is consistent with either reduced NAD#super[+] flux through the mitochondrial compartment or a compensatory transcriptional response to impaired electron transport. The EBV-immortalization caveat applies.

Therapeutically, the largest NAD#super[+] precursor trial to date — nicotinamide 1000 mg/day ($n = 900$, double-blind RCT in acute COVID-19) — accelerated clinical recovery and, in a post-hoc 6-month follow-up, reduced the burden of post-COVID symptoms (median symptom score 6.5 vs 10.5, $p = 0.010$) @Schreiber2025Nicotinamide. In established Long COVID, nicotinamide riboside (NR) 2000 mg/day ($n = 58$, double-blind RCT) raised blood NAD#super[+] 2.6--3.1-fold within 5 weeks but did not significantly improve the primary cognitive endpoint; secondary outcomes (fatigue, sleep, depression) improved after $≥$10 weeks on NR . No NR or NMN trial has been conducted specifically in ME/CFS. A mechanistic bridge between NAD#super[+] depletion and the persistent interferon-like immune signature observed in ME/CFS was provided by Chini et al., who demonstrated in vitro that chronic NAD depletion triggers mitochondrial DNA leakage into the cytoplasm via VDAC1, activating the cGAS-STING pathway and inducing a Type I interferon response indistinguishable from viral infection @Chini2025NADInterferon — a candidate explanation for why post-viral ME/CFS may sustain an innate immune activation state even after pathogen clearance.

*Riboflavin (FAD precursor).* FAD is required by Complex I (as FMN), Complex II, the E3 subunits of both PDC and KGDHC, all four acyl-CoA dehydrogenases in beta-oxidation, ETF, ETF-QO, and glutathione reductase. Three independent lines of evidence now converge on riboflavin pathway disruption in ME/CFS. First, Naviaux et al.\ identified riboflavin pathway dysregulation among the 20 abnormal metabolic pathways in their plasma metabolomics study, with FAD decreased in both male and female CFS patients . Second, Baraniuk found riboflavin and FMN levels lower in ME/CFS cerebrospinal fluid than in sedentary controls ($n = 45 + 20$), with Riboflavin Metabolism enriched among significantly different CSF metabolite pathways — extending the deficit from plasma to the central nervous system @Baraniuk2025CSFmetabolomics. Third, Heap et al.\ measured erythrocyte glutathione reductase (GTR) basal activity in CFS ($n = 12 + 18$ controls) and found it significantly reduced (6.13 vs 7.42 U/g Hb, $p < 0.04$) @Heap1999vitaminB — however, they measured basal enzyme activity only, not the activation coefficient ratio (EGRAC), so the result cannot distinguish between reduced enzyme protein mass and functional FAD depletion. The EGRAC assay (ratio of GTR activity with and without exogenous FAD) remains the gold-standard functional riboflavin biomarker and has never been performed in ME/CFS (G23).

Despite this converging evidence, riboflavin as a standalone intervention has never been formally trialled in ME/CFS  — an absence notable given three features that would make a pilot trial low-risk and potentially informative. First, riboflavin-responsive forms of multiple acyl-CoA dehydrogenase deficiency (RR-MADD, typically ETFDH mutations) produce a clinically similar syndrome of fatigue, exercise intolerance, and proximal myopathy that responds to riboflavin 100--400 mg/day; a fatigue-dominant MADD phenotype without overt myopathy has been reported in ETFDH c.1130T>C carriers. Second, riboflavin 400 mg/day is an evidence-based migraine prophylactic (59% responder rate vs 15% placebo, NNT = 2.3 @Schoenen1998riboflavinmigraine), and migraine is among the most common ME/CFS comorbidities — the proposed mechanism (mitochondrial energy reserve enhancement via FAD-dependent Complex I/II) is identical to the energy-deficit hypothesis in ME/CFS. Third, riboflavin is inexpensive, widely available, and has an excellent safety profile even at high doses.

#open-question(title: [Is Riboflavin Insufficiency in ME/CFS a Consumption Problem Rather Than a Supply Problem?])[
Glutathione reductase (GR) is FAD-dependent — it recycles GSSG back to GSH. Under the chronic oxidative stress documented in ME/CFS (elevated F2-isoprostanes @Kennedy2005isoprostanes @Robinson2010isoprostanes, depleted GSH, elevated 8-OHdG), GR turns over at abnormally high rates to maintain the GSH/GSSG ratio. This constitutes a potential "FAD sink": riboflavin may not be deficient in dietary supply but may be consumed faster than it can be replenished by the very redox-cycling machinery that defines oxidative stress. If so, EGRAC (G23) will correlate with F2-isoprostane and GSSG/GSH ratio: patients with the highest oxidative stress burden will have the worst functional riboflavin status. The therapeutic implication is that supplementation dose calculations must account for the consumption rate, and that co-administration of antioxidants (NAC, CoQ10) with riboflavin may be more effective than riboflavin alone — because reducing oxidative demand simultaneously reduces FAD consumption. This reframes the riboflavin question from "do ME/CFS patients get enough riboflavin?" to "do ME/CFS patients _use up_ riboflavin faster than they can replace it?"
] <oq:riboflavin-consumption-vs-supply>

*Thiamine (TPP precursor).* Thiamine pyrophosphate is the cofactor for the E1 subunits of both PDC and KGDHC. Functional thiamine deficiency (documented by elevated erythrocyte transketolase activation ratio in historical CFS series) would simultaneously impair pyruvate entry into the TCA cycle and reduce alpha-ketoglutarate oxidation. High-dose thiamine (600--1800 mg/day) is used in thiamine-responsive metabolic disorders and in POTS-adjacent autonomic conditions. It has not been tested in ME/CFS in a formal trial . The closest formal evidence is Bager et al.'s RCT of high-dose oral thiamine (600 mg TID) in IBD patients with chronic fatigue ($n = 40$), which showed significant fatigue reduction versus placebo @Bager2021thiamineIBD — but the IBD fatigue mechanism may differ from ME/CFS. A large patient-reported outcomes survey ($n = 3{,}925$) found that benfotiamine and TTFD (fat-soluble thiamine derivatives) showed statistically significant differential response rates between ME/CFS and Long COVID patients, suggesting disease-specific thiamine handling @Eckey2025PRO.


