#import "../../../../../shared/environments.typ": *

#synthesis(title: [Brain Clearance Architecture as an Integrative Framework for ME/CFS Neurological Symptoms])[
The environments in this chapter assemble the Chayama 2026 brain-clearance findings, the Toscano 2026 dual-speed glymphatic model, and the orexin–vasomotion literature into a single architectural framework for how waste-clearance failure could produce ME/CFS neurological symptoms — while keeping the large gap between the animal mechanisms and any human ME/CFS measurement in full view. The organising insight is that physiological brain clearance follows a *nearest-exit* principle to dura, skull, and nasal routes rather than the cervical-lymphatic route that CSF-tracer studies implied (@ach:ch15-brain-clearance-architecture), and that it operates in two regimes — fast perivascular advection driven by noradrenergic vasomotion and slow interstitial diffusion (@ach:ch15-mraiv-dual-speed). *If the rodent clearance anatomy translates to humans and if clearance is impaired in ME/CFS — both untested* — this architecture would make several otherwise-disconnected ME/CFS observations coherent. First, it distinguishes *two failure modes* with opposite biomarker signatures: inflammatory *rerouting* (proteins shunted to blood; predicted high plasma, low CSF) versus obstructive *trapping* (parenchymal retention; predicted low plasma, high CSF), a distinction proposed both as a disease-stage marker (@open:ch15-csf-blood-ratio, @lim:ch15-dti-alps-caveat) and as a possible axis separating Long COVID from chronic ME/CFS (@spec:ch15-longcovid-clearance-parallel). Second, it supplies a mechanistic route from inflammation to symptom via orexin: an inflammation→PGE2→orexin-suppression→reduced NE-vasomotion→impaired-clearance loop (@spec:ch15-orexin-vasomotion-triad, @spec:ch15-pge2-orexin-feedback), which — episodically amplified by exertion — yields a PEM "ratchet" (@spec:ch15-glymphatic-pem-ratchet) and a self-reinforcing sleep–clearance vicious cycle explaining unrefreshing sleep (@hyp:ch15-glymphatic-vicious-cycle). Third, the nearest-exit / compartment structure offers a candidate explanation for *why PEM symptoms are regionally heterogeneous* (cognitive vs sensorimotor), via compartment-specific clearance overload (@spec:ch15-pem-compartment-overload), and raises the possibility that chronic neuroinflammation breaks the skull-border B-cell tolerogenic checkpoint (@spec:ch15-skull-bcell-tolerance) — with skull-channel remodelling as a speculative structural biomarker (@spec:ch15-skull-channel-biomarker). Long-term, chronic clearance failure is proposed as a neurodegeneration risk factor (@spec:ch15-neurodegeneration-risk).

The framework's honest status is that its *mechanistic core rests on rodent work* (Chayama Syn-ZsG tracing; Toscano n=5 mice, unreplicated), while *every ME/CFS application is speculative* — the constructive symptom-linking speculations sit at certainty 0.15–0.35 precisely because glymphatic function has never been directly imaged in ME/CFS. DTI-ALPS, the most-cited human proxy, may reflect CSF flow rather than the parenchymal protein clearance Chayama shows drains to different compartments (@lim:ch15-dti-alps-caveat), so even the existing indirect human data may not measure what the model needs. No study has measured AQP4 polarization, dual-speed transport, or CSF:blood neuronal-protein ratios in ME/CFS patients. The central open question is therefore not whether brain clearance is biologically important — the rodent and neurodegeneration literature strongly suggest that — but whether clearance failure is a *causal driver* of ME/CFS symptoms or a *downstream consequence* of the sleep disruption and neuroinflammation documented elsewhere in this chapter; the single most decisive experiment is direct glymphatic imaging (MR-AIV or dynamic contrast MRI) in an ME/CFS cohort with paired CSF:blood neuronal-protein measurement.

*Consequence:* If waste-clearance failure genuinely drives ME/CFS brain symptoms, it would reframe unrefreshing sleep, brain fog, and post-exertional cognitive crashes as a plumbing problem — the brain generating waste faster than it can be flushed — which would make sleep-quality (not sleep-duration) interventions and clearance-preserving drug choices central to treatment, and would predict a specific blood-versus-spinal-fluid protein pattern that could stage the disease; but because the direct evidence is entirely from mice and no clearance measurement yet exists in ME/CFS patients, this is a well-organised research programme awaiting its first decisive human imaging study, not a basis for current clinical decisions.
] <syn:brain-clearance-architecture-model>
