#import "../../../../shared/environments.typ": finding

=== Low-Dose Aripiprazole (LDA)

LDA (1–2 mg/day) is a partial agonist at D2/D3 and 5-HT1A, antagonist at 5-HT2A. At microdose levels (≤1 mg/day), the pharmacologically dominant action is presynaptic D2/D3 partial agonism — insufficient for antipsychotic occupancy but adequate for microglial D2 receptor engagement. Carries significant risks: akathisia, serotonin syndrome, CYP2D6 variable exposure, and prediabetes/metabolic syndrome (@warn:lda-metabolic).

LDA acts at three levels relevant to ME/CFS: (1) microglial D2/D3 — suppressing pro-inflammatory cytokine release, raising the activation threshold of primed microglia; (2) mesocorticolimbic D2/D3 — restoring tonic dopamine signalling in prefrontal and hippocampal circuits; (3) 5-HT1A autoreceptors — reducing raphe serotonergic tone with downstream ANS stabilisation. The balance of these actions shifts with dose: microglial modulation dominates at ≤1 mg, postsynaptic D2 and 5-HT2A effects emerge above 1.5 mg.

==== If LDA works

#finding(claim: [Microglial activation threshold was pathologically low (PEM protection).], explanation: [Dopamine D2/D3 receptors are expressed on microglia. D2-like agonism suppresses pro-inflammatory cytokine release (TNF-α, IL-1β, IL-6), nitric oxide production, and reactive oxygen species from activated microglia. If LDA raises the microglial activation threshold, exertion signals (ATP, ROS, heat-shock proteins) that normally trigger a post-exertional neuroinflammatory cascade no longer cross into symptomatic territory. The drug acts as a threshold modulator, not a fuel replacement or linear anti-inflammatory. Crosby et al. (2021) reported PEM improvement at doses of 0.2–2 mg in a pilot study (n=25) @Crosby2021LDA.

*Synergy with mast-cell stabilisers.* Mast cells release histamine, tryptase, and PGD2, which activate microglia. Antihistamines (H1, H2) and leukotriene receptor antagonists reduce the *baseline pressure* on microglia. LDA raises the *activation threshold*. The two act on the same cell population at different nodes — pressure vs. gate — and the combination may create a wider operational window than either alone.

*Synergy with LDN.* LDN blocks TLR4 on microglia — a separate receptor from D2 on the same cell. D2 agonism + TLR4 antagonism are complementary, not redundant: they suppress microglial activation through different signalling pathways converging on the same cytokine-output machinery. A patient may be a full LDN non-responder while LDA is effective, because TLR4 antagonism alone does not raise the activation threshold — it only removes one input among many.], certainty: [Low — Crosby et al. (2021) pilot data only (n=25, no control group). Microglial D2 expression and D2-agonist suppression of microglial cytokines are well-established in neuroinflammatory models, but no study has measured microglial D2 tone before/after ≤1 mg aripiprazole in any clinical population. The non-linear threshold model is mechanistically coherent with D2 partial agonism pharmacology but prospectively unvalidated.], dntu: [whether microglial stabilisation, dopamine tone restoration, or 5-HT1A ANS stabilisation is the dominant mechanism — all three are plausibly involved; whether the mast-cell/LDA synergy is additive or multiplicative; whether PEM protection persists beyond the first weeks (receptor adaptation may alter the net effect).], action: [LDA at 0.2–2 mg/day is a rational probe for microglial-mediated PEM. Combined with mast-cell stabilisers, it tests whether microglial activation threshold is the rate-limiting node in PEM generation. Do not increase dose if PEM protection is already complete — higher doses shift into postsynaptic D2/5-HT2A range and may reverse benefit via U-shaped dose-response.], level: [Partial root cause — LDA raises the microglial activation threshold without removing the trigger that primed the microglia (autoantibodies, infection history, metabolic stress).])

#finding(claim: [Dopamine signalling was insufficient in cognitive circuits.], explanation: [LDA's partial agonism at presynaptic D2 autoreceptors and postsynaptic D2/D3 receptors restores tonic dopamine tone in prefrontal and hippocampal circuits. CSF catecholamine reduction is documented @Walitt2024NIH and stimulant surveys report 77.1% brain fog improvement @Vernon2025PNAS, supporting a dopaminergic component to cognitive symptoms. Crosby et al. (2021) reported cognitive improvement at doses of 0.2–2 mg in a pilot study (n=25) @Crosby2021LDA.

Domain dissociation is a testable diagnostic principle: if LDA fully resolves cognitive symptoms but leaves other symptoms untouched, the protected domains share a dopaminergic/microglial pathway while the resistant domain operates through a different mechanism (e.g., thalamo-cortical GABAergic filtering, vascular dysregulation). This domain dissociation is itself informative — it identifies which symptoms share a pathway and which do not, without requiring a biomarker.], certainty: [Low to Medium — CSF catecholamine reduction is documented @Walitt2024NIH, stimulant surveys 77.1% brain fog improvement @Vernon2025PNAS, but LDA specifically has zero controlled ME/CFS trials beyond the Crosby pilot.], dntu: [whether cognitive benefit is dopaminergic, serotonergic (5-HT1A), or from improved sleep architecture; whether the deficit is primary or secondary to neuroinflammation.], action: [cognitive/dopaminergic support is indicated. Domain dissociation between protected cognition and persistent non-cognitive symptoms means additional targets (GABAergic, vascular) should be probed separately — do not increase LDA dose chasing symptoms in a dopamine-resistant domain.], level: [Symptom management for cognition; partial root cause if acting through microglial stabilisation upstream of cognitive circuits.])

#finding(claim: [Serotonin modulation may contribute to ANS stabilisation.], explanation: [LDA is a 5-HT1A partial agonist. 5-HT1A activation in raphe nuclei reduces serotonergic tone. Downstream effects include autonomic nervous system stabilisation — potentially reducing the post-exertional sympathetic-parasympathetic crash that may contribute to PEM. This mechanism cannot be isolated clinically without a selective 5-HT1A probe, so its contribution relative to D2-mediated effects is unknown.], certainty: [Low — no way to distinguish from dopamine-mediated benefit with LDA alone. Selective 5-HT1A agonists (buspirone) could theoretically disentangle, but have not been studied in ME/CFS.], dntu: [whether serotonergic ANS stabilisation is a meaningful contributor vs. epiphenomenal; whether benefit is from pre- or post-synaptic 5-HT1A activation.], action: [If 5-HT1A contribution is suspected, a buspirone trial could isolate serotonergic effects without dopamine receptor engagement.], level: [Symptom management — modulates ANS output without correcting the underlying dysautonomia trigger.])


==== What a positive response does NOT reveal

A positive LDA response cannot distinguish whether the benefit is microglial (D2 → cytokine suppression), dopaminergic (mesocorticolimbic tone restoration), serotonergic (5-HT1A → ANS stabilisation), or a combination of all three — LDA acts at all targets simultaneously. It does not identify the upstream cause of microglial priming (autoantibodies, infection history, metabolic stress remain indistinguishable from LDA alone). It does not reveal which D2 population is responsible — microglial D2 and neuronal D2 are pharmacologically identical. Because no controlled ME/CFS trials of LDA exist, a genuine pharmacological effect cannot be separated from placebo or natural fluctuation.

==== If LDA does NOT work
- Microglial activation threshold may not be D2-responsive — other microglial activation pathways (P2X7, TREM2, C5aR) dominate.
- Dopamine deficit not the primary cognitive mechanism — glymphatic failure, direct cytokine effects, cerebral hypoperfusion, or neuronal mitochondrial failure do not respond to dopamine.
- Wrong dose — partial agonist net effect is dose-dependent and varies by regional dopamine tone. U-shaped dose-response curve means both too little and too much can fail.
- Dopamine receptors downregulated — chronic inflammation reduces D2 expression.
- Metabolic constraint limits neurotransmitter release even with receptor stimulation.
- CYP2D6 poor metabolizer status → drug accumulation → postsynaptic D2 antagonism dominates → paradoxical worsening or no net benefit.

==== How LDA combines with other medications
- LDA works + mast-cell stabilisers work → microglial activation is the central node: mast cells supply the baseline pressure (reduced by antihistamines) and D2 agonism raises the threshold (provided by LDA). Combined response is stronger evidence for microglial PEM generation than either alone.
- LDA works + LDN does not → microglial D2 pathway is the dominant activation route; TLR4 antagonism is insufficient alone. Does NOT imply neuroinflammation is absent — LDN may be blocking the wrong receptor on the same cell population.
- LDA works + LDN works → neuroinflammation confirmed; multi-receptor microglial involvement (TLR4 + D2). Treat neuroinflammation as upstream driver via multiple complementary targets.
- LDA works + specific symptom domain persists → domain dissociation: the persistent symptom operates through a non-dopaminergic mechanism (e.g., thalamo-cortical GABAergic filtering). Do not increase LDA — probe the resistant domain with a different drug class.
- LDA works + methylphenidate worsens → receptor-level support needed; stimulant side effects (noradrenergic POTS, +7% REE) intolerable.

==== Key caveat

Non-response is weaker evidence than response. LDA non-response does not exclude dopamine deficiency, microglial involvement, or cognitive-circuit pathology — D2 receptors may be downregulated from chronic inflammation, the dose may be outside the therapeutic window (U-shaped dose-response), or metabolic constraint may limit neurotransmitter release even with receptor stimulation.
