#import "../../../shared/environments.typ": *

== The Prolactin Axis and the Buspirone Challenge
<sec:prolactin-buspirone>

The prolactin axis offers a largely unexplored window into neuroendocrine regulation in ME/CFS. Prolactin is secreted by pituitary lactotrophs and is under tonic inhibition by dopamine through D2 receptors: dopamine reaching the anterior pituitary via the portal circulation suppresses prolactin release, while withdrawal of that dopaminergic brake allows prolactin to rise (Ben-Jonathan et al.\ 2001 @BenJonathan2001ProlactinDopamine; Fitzgerald and Dinan 2008 @Fitzgerald2008ProlactinDopamine; Qi, Lytle, and colleagues 2023 @QiLytle2023TIDA). Because several drugs can be used as controlled neuroendocrine probes that transiently release this brake, the prolactin response to such a probe acts as a read-out of central dopaminergic tone and of 5-HT1A receptor sensitivity.

Buspirone is such a probe: it is a 5-HT1A serotonin-receptor agonist that also blocks dopamine D2 receptors. When given as an oral challenge, it stimulates a transient prolactin rise whose magnitude reflects the balance of serotonergic drive and dopaminergic inhibition on the lactotroph. A small literature from the 1990s — one index study replicated by an independent group, plus a case series — found that this response is exaggerated in ME/CFS patients compared with healthy controls. A related but distinct probe study found that the direction of prolactin response *contrasts* across diagnoses — lowest in major depression, highest in CFS — though, importantly, that contrast was measured with the serotonergic releaser d-fenfluramine, not with buspirone: no study has ever tested CFS against depression on buspirone itself.

#clinical-finding(title: [Exaggerated Prolactin Response to Buspirone in ME/CFS, Replicated by an Independent Group])[
A series of small neuroendocrine challenge studies from 1992–2001 found that ME/CFS / chronic fatigue syndrome patients mount a *higher* prolactin response to buspirone than healthy controls despite normal baseline prolactin. Bakheit et al.\ (1992) first reported elevated buspirone-stimulated prolactin in post-viral fatigue syndrome, interpreted as possible upregulation of hypothalamic 5-HT receptors @Bakheit1992Buspirone. Sharpe et al.\ (1996), from an independent Oxford group, replicated this in 11 male CFS patients versus matched controls, finding significantly higher plasma prolactin after buspirone — with more nausea in the patient group, a confound not separable from the hormonal read-out in that design (see the mechanism question below) — while growth-hormone responses did not distinguish the groups @Sharpe1996Buspirone. Sharma et al.\ (2001) reported normalization of the neuroendocrine response associated with clinical recovery in a small case series, suggesting possible state-dependence @Sharma2001Buspirone. Two constraints on interpretation: challenge with the serotonin-releasing agent fenfluramine produced *null* results in CFS versus controls (Yatham et al.\ 1995 @Yatham1995Fenfluramine; Bearn et al.\ 1995 @Bearn1995Fenfluramine), which argues against a purely global serotonergic mechanism and constrains the abnormality toward pathways buspirone engages but fenfluramine does not (including D2) — without positively localizing it; and the reported ME/CFS-versus-depression contrast (prolactin responses lowest in depression, highest in CFS) comes from a *d-fenfluramine* study, not buspirone @Cleare1995DepressionCFS — the buspirone-versus-depression comparison has never been performed. (Certainty: 0.62 for the ME/CFS-versus-control finding — replicated by an independent group but small studies, all pre-2010, not yet re-tested with modern criteria; the ME/CFS-versus-depression discriminator is *untested on buspirone* and rests on a single serotonergic-probe study from a group sharing authors with the fenfluramine null; severity coverage: unknown — study populations were not stratified by severity; diagnostic criteria: Fukuda / pre-Fukuda clinical criteria; evidence source: serum prolactin — inference target: central dopaminergic/serotonergic regulation. The link from the peripheral hormone response to central dopamine tone is indirect.) (Replication status: replicated within era — one independent replication plus one case series — not yet re-replicated post-2010.)
*Consequence:* If this finding replicates in a modern study, a controlled buspirone challenge could become a candidate test separating ME/CFS from healthy physiology — and, if the never-tested buspirone-versus-depression contrast goes the way the d-fenfluramine study suggests, eventually a candidate discriminator from depression as well; the discriminator claim is itself part of what a replication must test, not an established fact.
] <cf:prolactin-buspirone-exaggerated>

#open-question(title: [What Explains the Exaggerated Prolactin Response — Dopamine, Serotonin, Estradiol, or Nausea?])[
The mechanism behind the exaggerated prolactin response is unresolved, and the leading candidates make competing, testable predictions.

    / *Reduced dopaminergic inhibitory tone (dopamine-D2 brake):*: Dopamine tonically inhibits prolactin through lactotroph D2 receptors (Ben-Jonathan 2001 @BenJonathan2001ProlactinDopamine). If ME/CFS involves reduced dopaminergic drive in the tuberoinfundibular (hypothalamic) system, then buspirone's D2 blockade would release a weaker brake, allowing a larger prolactin surge. This account is *constrained-in but not confirmed by* the probe data: the 5-HT releaser fenfluramine did not reproduce the exaggerated response (Yatham 1995 @Yatham1995Fenfluramine; Bearn 1995 @Bearn1995Fenfluramine), which argues against a purely serotonergic mechanism without positively localizing the defect to D2 — the broader evidence for dopaminergic dysfunction in ME/CFS (basal-ganglia reward-processing deficits; an open-label trial of the dopamine-stabilizer OSU6162 @Haghighi2021OSU6162) is suggestive but concerns other, anatomically distinct dopaminergic systems.
    / *Serotonergic 5-HT1A hypersensitivity:*: Buspirone is a 5-HT1A agonist, and the original Bakheit interpretation invoked upregulation of hypothalamic 5-HT receptors @Bakheit1992Buspirone. However, the null fenfluramine (a 5-HT releaser) result argues against a purely serotonergic explanation, and Sharpe et al.\ (1996) found growth-hormone (also 5-HT1A-mediated) responses did not distinguish CFS from controls @Sharpe1996Buspirone — a result that constrains the pure 5-HT1A-hypersensitivity model.
    / *Sex-hormone (estradiol) modulation:*: Estradiol regulates prolactin by modulating both the dopaminergic brake and lactotroph function (Ben-Jonathan 2001 @BenJonathan2001ProlactinDopamine; Qi, Lytle et al.\ 2023 @QiLytle2023TIDA). A sex-hormone-dependent component could in principle explain the strong female predominance of ME/CFS (~80%) — though the key replication (Sharpe 1996) studied men only — and no direct ME/CFS prolactin-by-sex (estradiol-stratified) study has been found; this remains a hypothesis, not established evidence.
    / *Differential emetic (nausea) response:*: The most parsimonious alternative: Sharpe's CFS group reported *more nausea* after buspirone than controls @Sharpe1996Buspirone, and nausea itself raises prolactin via the emetic/stress reflex. If ME/CFS patients simply react to buspirone with more nausea, the hormonal "signal" could be an epiphenomenon of differential drug tolerability rather than a specific neuroendocrine abnormality. No historical study measured nausea and prolactin so that the two could be disentangled; a replication must record emetic symptoms and test whether the prolactin difference survives adjustment for them.

These mechanisms are not mutually exclusive, and the current evidence cannot fully adjudicate between them. The decisive experiment is a modern, adequately powered buspirone-challenge study that (a) includes both ME/CFS and depression control arms — a comparison never yet performed with buspirone, (b) stratifies by sex and menstrual phase, (c) measures baseline cortisol alongside prolactin (cortisol modulates the buspirone-stimulated prolactin response; Dinan et al.\ 2001 @Dinan2001Buspirone), and (d) records nausea/adverse symptoms so the hormonal signal can be separated from drug tolerability.
*Consequence:* Which mechanism is correct determines the interpretation of the probe and its value: a dopaminergic-brake account would tie this peripheral test to a central dopamine deficit and to dopamine-directed research, whereas a serotonergic or estradiol account would point research toward those axes instead — resolving this is a prerequisite for using the challenge as a meaningful biomarker.
] <oq:prolactin-buspirone-mechanism>

#prediction(title: [A Modern Buspirone Challenge Will Show Exaggerated Prolactin in ME/CFS But Not Depression])[
A pre-registered replication study using a controlled oral buspirone challenge in ME/CFS, major depression, and healthy controls would be predicted to reproduce the historical pattern: a significantly larger prolactin-area-under-curve in ME/CFS than in depression, with healthy controls intermediate, at normal baseline prolactin. The prediction is falsified if a modern cohort shows no difference between ME/CFS and depression (or between ME/CFS and healthy controls) on the buspirone-stimulated prolactin response, or if the historical finding proves to be an artifact of pre-Fukuda diagnostic criteria or uncontrolled confounders (medication, menstrual phase, fasting, time of day). Given the small historical effect sizes' uncertainty, this is a cheap and quick test — feasible for an interested research physician — that would either revive or retire a notable but abandoned line of evidence.
*Consequence:* This one study would tell patients and clinicians whether the exaggerated buspirone-prolactin response is real and whether it separates ME/CFS from depression — a contrast never yet tested with this probe; even a positive result would remain a research tool until an independent group replicates it, but a negative one would retire a decades-old lead.
] <pred:prolactin-buspirone-replication>

#speculation(title: [Prolactin as a Peripheral Window on Hypothalamic Dopamine Tone])[
Because prolactin is under tonic dopamine-D2 inhibition at the lactotroph (@BenJonathan2001ProlactinDopamine @Fitzgerald2008ProlactinDopamine), a controlled challenge that transiently lifts that brake makes the peripheral prolactin response a functional read-out of the *tuberoinfundibular (hypothalamic)* dopaminergic tone that governs it — a deep-brain signal that would otherwise require PET or CSF measurement, accessed here from an ordinary blood draw. If the exaggerated buspirone→prolactin response in ME/CFS reflects reduced dopaminergic inhibitory tone (see @oq:prolactin-buspirone-mechanism), then this peripheral challenge test becomes a *candidate* non-invasive proxy — unvalidated, and specific to the hypothalamic/pituitary dopaminergic system rather than a measure of dopamine elsewhere in the brain — for one neurochemical parameter relevant to the dopamine theories of ME/CFS fatigue and reward-processing (see Chapter @ch:neurological).

*Certainty:* 0.45 — mechanism is canonical physiology (human), but the specific "prolactin = hypothalamic dopamine read-out in ME/CFS" framing is inferential and untested.

*Falsifiable prediction:* If the exaggerated prolactin response tracks a hypothalamic dopamine deficit, then (a) it should correlate with other markers of dopaminergic function (e.g., anhedonia/motivation scores, DAT/VMAT2 imaging if available) and (b) a pure D2-antagonist challenge (metoclopramide/domperidone, sparing 5-HT1A) should reproduce a similar exaggerated response; falsified if the response is abolished by 5-HT1A blockade or fails to correlate with dopamine-linked symptoms. (Origin: brainstorm idea 1.2.)

*Consequence:* If validated, a simple blood test could give researchers a non-invasive view of a deep-brain dopamine signal in ME/CFS — far easier and cheaper than PET — which would make the dopamine hypothesis far more testable.
] <spec:prolactin-dopamine-window>

#speculation(title: [Medium-Spiny-Neuron Dopaminergic Link as a Broader Dopamine-Axis Sign])[
The exaggerated prolactin response constrains an abnormality to pathways including the dopamine-D2 receptor at the lactotroph, but reduced activity in the tuberoinfundibular (hypothalamic) dopaminergic system that governs prolactin would not automatically extend to the brain's other dopaminergic systems — the nigrostriatal and mesolimbic pathways, with their dopamine-regulated medium spiny neurons of the basal ganglia, are anatomically and functionally distinct and independently regulated. This speculation asks whether, in ME/CFS, the same underlying deficit *does* span those systems: whether it could (a) contribute to the effort/motivation symptoms and psychomotor fatigue seen in ME/CFS and (b) connect the peripheral prolactin finding to the nigrostriatal dopaminergic findings documented in Long COVID (see Chapter @ch:neurological and @spec:prolactin-dopamine-window). This is a *convergence hypothesis* in the weak sense — it does not claim the pituitary finding *causes* the striatal symptoms, nor even that the hypothalamic and striatal systems co-vary; it proposes only that co-variation is plausible and testable, and would explain both a peripheral endocrine read-out and central reward/motor dysfunction if present.

*Certainty:* 0.30 — the dopamine-D2 physiology is canonical, but the specific link between a lactotroph response and medium-spiny-neuron function is indirect and unsupported by any direct ME/CFS study.

*Falsifiable prediction:* If a shared dopaminergic-tone deficit underlies both, then the exaggerated prolactin response should correlate with measures of striatal dopamine function or dopamine-linked symptoms (anhedonia, effort cost, motor fatigue) across ME/CFS patients; falsified if the prolactin response is unrelated to all striatal/dopamine-linked measures. (Origin: brainstorm idea 1.3.)

*Consequence:* If the cross-system co-variation is confirmed, a single peripheral test could serve as a candidate research proxy for one dopaminergic deficit that otherwise requires brain imaging — while remaining specific to the hypothalamic system until that co-variation is actually demonstrated.
] <spec:prolactin-msn-link>

#speculation(title: [The Challenge Test as a Dopaminergic Subtype Marker])[
If the exaggerated prolactin response reflects a dopaminergic (D2-brake) abnormality that is present in only a *subset* of ME/CFS patients, then the buspirone challenge could act as a biological **subtype marker** — identifying a dopamine-dominant subgroup within the heterogeneous ME/CFS population (see @cf:prolactin-buspirone-exaggerated). A dopaminergic subtype would be expected to show a different profile on dopamine-linked symptoms (motivation, anhedonia, motor slowing, reward-processing) and potentially a different response to dopamine-modulating interventions than serotonergic-dominant patients. This is analogous to how other challenge tests (e.g., HPA stimulation) reveal pathophysiological heterogeneity that symptom-based classification misses.

*Certainty:* 0.35 — heterogeneity in ME/CFS is well documented, but no study has tested whether the prolactin response segregates a distinct subgroup.

*Falsifiable prediction:* If the challenge marks a dopaminergic subtype, then within an ME/CFS cohort the exaggerated responders should cluster with higher dopamine-linked symptom burden and differ from non-responders on dopamine-sensitive measures; falsified if responders and non-responders are indistinguishable on all dopamine-linked measures. (Origin: brainstorm idea 1.4.)

*Consequence:* If true, a single challenge test could separate a meaningful biological subgroup of ME/CFS patients, pointing them toward dopamine-focused research and treatment rather than treating the whole population as one entity.
] <spec:prolactin-subtype-marker>

#speculation(title: [Long COVID Dopamine Bridge: Converging Independent Dopaminergic Evidence])[
The dopaminergic interpretation of the prolactin finding is mechanistically compatible with independent dopaminergic evidence from Long COVID — a closely related post-infectious illness. VMAT2-PET studies in Long COVID with new-onset apathy have shown reduced dopaminergic terminals in the striatum (see Chapter @ch:neurological and the dopaminergic VMAT2 literature), and an open-label dopamine-modulator (OSU6162) trial in ME/CFS probes the same family of systems (@Haghighi2021OSU6162). If reduced dopaminergic activity underlies both the exaggerated prolactin response in ME/CFS and the striatal dopamine loss in Long COVID, the two lines would support a shared dopamine-deficit account of post-infectious fatigue states. The critical caveat: they measure *anatomically distinct* nodes — the tuberoinfundibular/hypothalamic system versus nigrostriatal terminals — whose co-variation is an empirical assumption of this bridge, not an established fact; and ch09 documents the counter-tension that CSF dopamine metabolite indices are normal in PI-ME/CFS.

*Certainty:* 0.40 — the two lines are each plausible and mechanistically compatible, but no study has measured prolactin response and striatal dopamine in the same cohort, so the bridge is inferential.

*Falsifiable prediction:* If the bridge is real, patients with post-infectious ME/CFS/Long COVID who show exaggerated prolactin responses should also show measurable dopaminergic changes (DAT/VMAT2 imaging, dopamine-linked symptom scores); falsified if the prolactin response and striatal dopamine measures are independent across a comorbid cohort. (Origin: brainstorm idea 8.1.)

*Consequence:* If the two lines converge, it would strengthen the case that dopamine dysregulation is a shared, targetable feature of post-infectious ME/CFS and Long COVID — and justify the low-cost prolactin challenge as a screening test for that subgroup.
] <spec:long-covid-dopamine-bridge>

#limitation(title: [Limits of the Buspirone-Challenge Evidence])[
The historical evidence for the exaggerated prolactin response rests on very small studies (n = 11–20 per arm), a single diagnostic era (Fukuda and pre-Fukuda criteria, not the modern IOM/CCC criteria), and a line that was abandoned around 2001 and never re-tested with modern methods. The abandonment itself has competing explanations this section cannot adjudicate: the line may have been dropped for non-scientific reasons (fenfluramine's 1997 market withdrawal removed the serotonergic-probe family's main tool and buspirone's generic status removed commercial incentive), or because researchers judged it fragile or unreplicable — the historical record does not say. The buspirone studies lacked a depression-control arm (the depression contrast comes only from the separate d-fenfluramine study of Cleare 1995 @Cleare1995DepressionCFS, from a group sharing authors with the fenfluramine null); the controls were not severity-stratified; and several studies share the same research groups (cohort-overlap caution). Sharpe's patient group reported *more nausea* after buspirone than controls @Sharpe1996Buspirone — and nausea itself raises prolactin — so a differential emetic-response confound is embedded in the key replication and was not separable with the data collected. Buspirone is a multi-receptor drug (5-HT1A agonist, D2 blocker, 5-HT2/5-HT1D actions), so the probe does not cleanly isolate a single pathway, and the peripheral prolactin read-out is an indirect measure of only one dopaminergic subsystem. Until a modern, adequately powered replication exists, this finding should be treated as a promising but unverified research lead, not an established feature of ME/CFS.
*Consequence:* Patients and clinicians should read the exaggerated-prolactin claim as an intriguing hypothesis awaiting replication, not as a validated test — no current clinical decision should rest on it.
] <lim:prolactin-buspirone-limits>

#synthesis(title: [A Replicated Dopamine-Probe Finding Waiting for a Modern Test])[
The evidence in this section assembles into a *candidate* model, not an established one. A replicated but abandoned challenge finding — exaggerated prolactin release after buspirone in ME/CFS versus controls (@cf:prolactin-buspirone-exaggerated) — has a mechanism that is an open four-way question between dopaminergic, serotonergic, estradiol, and differential-nausea accounts (@oq:prolactin-buspirone-mechanism); the ME/CFS-versus-depression discriminator itself has never been tested with buspirone. If the dopaminergic account survives, this peripheral test becomes a candidate window on tuberoinfundibular dopamine tone (@spec:prolactin-dopamine-window), possibly co-varying with the striatal dopamine deficits documented independently in Chapter @ch:neurological and Long COVID — distinct systems whose co-variation is untested (@spec:prolactin-msn-link @spec:long-covid-dopamine-bridge) — and even a candidate marker of a dopaminergic ME/CFS subtype (@spec:prolactin-subtype-marker); an estradiol-dependent variant could additionally bear on the ~80% female predominance (@spec:fra-estradiol-prolactin-link). What the evidence establishes is the *finding itself* (small-n, pre-2010, one independent replication plus a case series); everything mechanistic remains speculative, and the single decisive next step is cheap: a pre-registered modern replication with depression controls, sex stratification, and nausea measurement (@pred:prolactin-buspirone-replication). The central open question is not whether the prolactin response differs — it likely does — but *which* regulatory failure, if any, it reveals rather than merely mirrors.

*Consequence:* One inexpensive challenge study could either hand ME/CFS research a candidate dopamine-system biomarker — or show the "signal" to be a nausea epiphenomenon or era artifact — either way resolving a question that has sat unanswered since 2001.
] <syn:prolactin-buspirone-model>
