#import "../../../../shared/environments.typ": *

=== Viral Reactivation Biomarkers
<subsec:viral-reactivation-biomarkers>

Viral reactivation testing serves two roles in ME/CFS: differential diagnosis (distinguishing active infection from post-infectious ME/CFS) and ongoing surveillance of viral persistence or reactivation as a disease driver. The Montoya group documented HHV-6 and EBV reactivation in subsets of ME/CFS patients, with antiviral treatment trials based on this rationale
Key viral reactivation biomarkers:
    - *EBV VCA IgG*: Epstein-Barr virus viral capsid antigen antibody; elevated in prior infection (near-universal). *EA-D IgG* (early antigen): Elevated titers suggest recent reactivation. *EBNA IgG* (nuclear antigen): Typically present after resolved primary infection; low or absent EBNA with high VCA suggests atypical or reactivated infection.
    - *HHV-6 IgG and IgM*: Human herpesvirus-6 serology; IgM elevation or rising IgG titers indicate reactivation. PCR (plasma or PBMC) is more specific for active replication but less sensitive for latent/chromosomally integrated HHV-6.
    - *SARS-CoV-2 Nucleocapsid IgG*: Distinguishes prior infection from vaccination-only immunity (vaccines generate spike antibodies only; nucleocapsid antibodies arise only from infection). This distinction is clinically relevant in Long COVID/ME/CFS overlap cases to confirm SARS-CoV-2 as the triggering infection.

*Interpreting very high VCA IgG with low active-reactivation markers.* A recurring pattern in ME/CFS is markedly elevated EBV VCA IgG (e.g.\ \>750 mIU/mL) together with negative or low EA-D IgG and undetectable EBV DNA by PCR. Antibody titre alone cannot distinguish active replication from immune memory, and this combination does not by itself indicate ongoing productive replication. Critically, it is equally consistent with at least three distinct states that serology cannot separate: (1) an inert post-infectious antibody set-point laid down by an intense prior immune response (often primary infection presenting as mononucleosis), persisting without active virion production; (2) ongoing abortive lytic replication (@sec:abortive-lytic), which sustains anti-viral antibody and innate immune activation while leaving conventional viral-load assays negative --- a process that is biologically *active* and potentially antiviral-responsive, not a quiescent scar; and (3) genuine but episodic or tissue-compartmentalised reactivation missed by a single blood-compartment PCR. The negative-test results that accompany this pattern are therefore largely uninformative rather than reassuring: EA-D IgG has poor negative predictive value (frequently absent during genuine reactivation), a single plasma PCR is a moment-in-time sample, and the \>750 threshold is platform- and unit-dependent. Confirmatory active-reactivation markers (EA-D, EBV/HHV-6 PCR, and --- where available --- anti-dUTPase IgG) can *support* a decision but cannot exclude an active process when negative. The practical implication is that a high VCA IgG should neither be assumed to reflect treatable active infection nor dismissed as a footprint; it warrants the clinical judgement described under antiviral patient selection (@sec:antivirals) rather than a serology-only verdict.


