#import "../../../shared/environments.typ": *

== Novel Mechanistic Hypotheses and Research Opportunities
#include "remarks/rem-intro.typ"
#include "subsec-wasf3-as-therapeutic-target/subsec-wasf3-as-therapeutic-target.typ"
#include "subsec-acetylcholine-mitochondrial-axis/subsec-acetylcholine-mitochondrial-axis.typ"
#include "subsec-atp-recovery-kinetics-and-mitophagy/subsec-atp-recovery-kinetics-and-mitophagy.typ"
#include "subsec-viral-trigger-er-stress-wasf3-pathway/subsec-viral-trigger-er-stress-wasf3-pathway.typ"
#include "subsec-b3-vagal-afferent-function-test-battery-055/subsec-b3-vagal-afferent-function-test-battery-055.typ"
#include "subsec-pyruvate-supplementation-hypothesis/subsec-pyruvate-supplementation-hypothesis.typ"
#include "subsec-methylene-blue-as-electron-transport-bypass/subsec-methylene-blue-as-electron-transport-bypass.typ"
#include "subsec-beta-blockers-for-pacing-enforcement/subsec-beta-blockers-for-pacing-enforcement.typ"
#include "subsec-immune-checkpoint-modulation/subsec-immune-checkpoint-modulation.typ"
#include "subsec-steroid-avoidant-anti-inflammatory-strategies/subsec-steroid-avoidant-anti-inflammatory-strategies.typ"
#include "subsec-central-governor-theory-link/subsec-central-governor-theory-link.typ"
#include "subsec-lactate-clearance-dysfunction/subsec-lactate-clearance-dysfunction.typ"
#include "subsec-c3-caregiver-implemented-severe-patient-protocol-050/subsec-c3-caregiver-implemented-severe-patient-protocol-050.typ"
#include "subsec-mast-cell-mitochondrial-crosstalk/subsec-mast-cell-mitochondrial-crosstalk.typ"
#include "subsec-research-priorities/subsec-research-priorities.typ"
#include "subsec-summary-of-novel-hypotheses-and-interventions/subsec-summary-of-novel-hypotheses-and-interventions.typ"
#include "../speculations/speculation-4.typ"
#include "../open-questions/open-question-1.typ"
#include "../open-questions/open-question-2.typ"
#include "../speculations/speculation-5.typ"
#include "../proposals/proposal-3.typ"
#include "../open-questions/open-question-3.typ"
#include "../speculations/speculation-7.typ"
#include "../warnings/warning-env-8.typ"
#include "../remarks/key-point-1.typ"
#include "../speculations/speculation-8.typ"
#include "../speculations/speculation-9.typ"
#include "../hypotheses/hypothesis-12.typ"
#include "../hypotheses/hypothesis-13.typ"
#include "../proposals/proposal-4.typ"
#include "../proposals/proposal-5.typ"
#include "../proposals/proposal-6.typ"
#include "../proposals/proposal-7.typ"
