#import "../../../../../shared/environments.typ": *

#speculation(title: [Precision-Weighted Effort Estimation — A Unified Model of Fatigue Perception])[
Greenhouse-Tucknott et al.\ (2022) proposed a predictive coding model that unifies pathological fatigue (chronic illness) and exertional fatigue (healthy) under a single computational framework @GreenhouseTucknott2022predictiveCodingFatigue. The model proposes that fatigue is not a direct readout of physiological state but a _percept_: the brain's posterior probability distribution over the expected cost of action, computed by integrating sensory evidence (muscle afference, metabolic signals, autonomic state) with prior beliefs about effort costs. In ME/CFS, the key computational pathology would be _increased prior precision on high-effort-cost expectations_: the brain overestimates how effortful any given action will be, because genuine peripheral dysfunction (reduced VO₂max, elevated lactate, cytokine signaling) has provided a long history of evidence that effort costs exceed reward.

The same computational framework has been applied to multiple sclerosis (MS) fatigue by Manjaly, Harrison, Critchley et al.\ (2019), who proposed that MS fatigue arises from dysregulated interoceptive prediction error signaling involving anterior cingulate and insula — the identical network implicated in ME/CFS interoceptive dysfunction @ManjalyCritchley2019MSfatigue. The MS model provides cross-disease validation: the computational pathology (increased prior precision on high-effort-cost expectations) is proposed for two neuroinflammatory conditions independently.

This model makes several testable predictions: (1) ME/CFS patients should overestimate the effort cost of an upcoming action (even sub-maximal) compared to healthy controls, quantitatively above what their measured VO₂max deficit predicts; (2) this overestimation should correlate with (a) inflammatory markers (IL-6, TNF-α), and (b) fatigue severity (FACIT-F / fVAS), but NOT with depression severity, distinguishing it from anhedonia-driven effort discounting; (3) real-time HRV biofeedback should reduce precision-weighted effort expectations more effectively in patients with high interoceptive sensibility than those with low sensibility; (4) anti-inflammatory interventions should shift prior precision downward, reducing effort perception for equivalent workloads.

The Seth (2011) interoceptive predictive coding model @Seth2011interoceptivePresence supplies the deeper theoretical layer: the generative model that produces fatigue percepts is the same model that produces the sense of _bodily presence_. When interoceptive prediction errors are chronic and unresolvable, the result is not just fatigue but a phenomenological sense of _disconnection_ from the body—the body feels alien, uncontrollable, a source of threat rather than a home base. This maps onto the anhedonia and depersonalisation components of ME/CFS emotional dysfunction.

(Certainty: 0.40. (0.35→0.40: reinforced by cross-disease convergence with Manjaly/Critchley 2019 MS fatigue predictive coding model, cert 0.75 @ManjalyCritchley2019MSfatigue). The Greenhouse-Tucknott model is a well-argued theoretical framework but entirely untested in ME/CFS. The Seth model is foundational (>900 citations) but is a theoretical proposal, not an empirical finding. The MS parallel provides cross-disease validation of the same computational framework. None of the specific predictions have been experimentally tested in any chronic fatigue population. The model's strength is its _falsifiability_: every prediction is specific and testable. *Falsification condition:* If effort perception (Borg RPE) in ME/CFS scales linearly with VO₂max deficit alone—with no additional variance explained by inflammatory markers or HRV—the precision-weighting layer is unnecessary and parsimony favors a simpler peripheral-limitation model.)
] <spec:ch15-greenhouse-tucknott-fatigue>
