#import "../../../shared/environments.typ": *

== Antiviral Trials
<sec:trials-antiviral>

The hypothesis that persistent viral infection drives ME/CFS has motivated several antiviral trials, with results that highlight the importance of patient selection.
*Valganciclovir*: Montoya et al.\ (2013, n=30) conducted a double-blind RCT of valganciclovir in ME/CFS patients selected for elevated HHV-6 and EBV antibody titers. The primary endpoint (fatigue score at 9 months) did not reach significance, but a subgroup with higher baseline antibody titers showed improvement. This suggested that antiviral therapy may benefit a virally-driven subgroup rather than the general ME/CFS population.
*Valacyclovir*: Lerner et al.\ (2007) reported improvement in a subset of ME/CFS patients with elevated EBV antibody titers treated with prolonged valacyclovir (6+ months). The study was open-label and uncontrolled, limiting conclusions.
*Paxlovid (nirmatrelvir/ritonavir)*: The NIH STOP-PASC trial tested Paxlovid for long COVID (which overlaps substantially with ME/CFS). The result was negative—no significant benefit over placebo—suggesting that if viral persistence drives symptoms, a brief antiviral course is insufficient to clear established reservoirs.
Key lessons from antiviral trials:
    - Patient selection by viral biomarkers is essential; unselected ME/CFS populations include non-virally-driven cases
    - Treatment duration may need to be prolonged (months) given evidence of viral persistence in tissue reservoirs
    - Combination antiviral strategies targeting multiple latent viruses have not been tested in ME/CFS, but the first uncontrolled data point in a closely overlapping post-infectious population appeared in 2026 (see below)
    - Novel antivirals targeting specific viral persistence mechanisms (e.g., EBV latency-to-lytic transition) may be more effective than existing agents

#speculation(title: [Combination Antiviral + Anti-Inflammatory Therapy: First Uncontrolled Data Point in Long COVID (Pridgen & Putrino 2026)])[
*Certainty: 0.21* (raw 0.25, discounted 0.85 for Long COVID population). *Evidence source:* Pridgen & Putrino (2026), single-center open-label case series, n=24 completed (12 IMC-2-only, 12 IMC-2 + Paxlovid), no placebo, no control, no randomization. (Evidence source: PBMC-free clinical observation — inference target: long-COVID symptom biology. Link is indirect to ME/CFS; population discount applied. Raw certainty from general Long-COVID population → discounted to 0.21.) @Pridgen2026HerpesAntiviralLongCOVID

*Pilot finding.* Pridgen & Putrino treated 24 Long-COVID patients with a combination regimen: IMC-2 = valacyclovir 1500 mg BID + celecoxib 200 mg BID for 120 days, with half additionally receiving a 15-day Paxlovid course (nirmatrelvir/ritonavir). Adding Paxlovid to the valacyclovir+celecoxib backbone was associated with larger self-reported improvement in fatigue (PGIC +2 points vs IMC-2 alone, ($p < 0.0001$), Cohen's d=1.8; VAS 55.3% greater reduction), brain fog, and dysautonomia. Reported gains appeared durable to ~600 days post-protocol. All endpoints were subjective (PGIC/VAS); no objective measures.

*Mechanistic rationale and relation to ME/CFS.* The regimen jointly targets the two dominant post-infectious persistence hypotheses documented in this paper: (1) herpesvirus reactivation (valacyclovir against EBV/HHV-6, a mechanism integrated at @sec:herpesviruses) and (2) residual SARS-CoV-2 persistence (Paxlovid). Adding a COX-2 inhibitor (celecoxib) as an anti-inflammatory/anti-latency adjunct is the distinctive element. This is the first direct test — albeit uncontrolled and in Long COVID, not ME/CFS — of the combination strategy that the antiviral-trial history above identifies as the untested gap (multiple latent viruses + persistence requiring prolonged, combined coverage). It does NOT contradict the negative results for brief Paxlovid courses — the NIH STOP-PASC trial (a brief monotherapy course, no benefit over placebo) and the observational finding that acute-phase nirmatrelvir did not reduce subsequent Long COVID symptoms @Durstenfeld2024paxlovid: those tested a brief monotherapy course in unselected patients, whereas this case series pairs antivirals with a 15-day Paxlovid window on a prolonged herpes-antiviral backbone.

*Critical caveats — this is NOT evidence of efficacy.* Open-label design leaves placebo effect and active-treatment-seeking selection bias unaddressed. The senior author is the inventor and a patent-holder/company founder for the IMC-2 combination (major conflict of interest), and ethics review was by a for-profit IRB. Single site, small n (12 per arm), and pronounced female bias (20 of 24). *No ME/CFS-specific data; ME/CFS severity applicability unknown — the cohort was Long COVID and not stratified by severity.* No pregnancy/lactation safety data for this regimen. The regimen must not be interpreted as a clinical recommendation; it is a hypothesis-generating pilot indicating that a randomized, double-blind, placebo-controlled trial of combination antiviral + anti-inflammatory therapy is warranted to test the viral-persistence hypothesis in ME/CFS. (Severity applicability: unknown — study population was Long COVID, not ME/CFS, and not stratified.)

*Falsifiable.* If the proposed controlled trial in an ME/CFS cohort selected for elevated herpesvirus antibody titers and/or viral-persistence biomarkers shows no difference in fatigue or functioning between the combination regimen and placebo at 6 months, then combination antiviral + anti-inflammatory therapy is not an effective anti-reservoir strategy in ME/CFS. A durable, control-verified benefit in a biomarker-selected subgroup would support the viral-persistence model.

*Consequence:* This is early, uncontrolled pilot data from a conflicted investigator — it changes nothing for treatment today, but it converts a long-standing research gap ("combination antivirals have never been tested") into a testable hypothesis, giving researchers a concrete rationale and design basis for a controlled trial in virus-selected ME/CFS patients.
] <spec:combination-antiviral-longcovid-pilot>


