#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Structural Vagal Cholinergic Denervation as an Anatomical Substrate for Post-Viral Dysautonomia and Sustained Inflammation])[
*Certainty: 0.45.* Two mechanistically distinct routes can disengage the vagal brake on systemic inflammation in post-viral illness. The first, described elsewhere in this framework, is *functional*: GPCR autoantibodies interfere with cholinergic signaling without destroying nerves (@spec:cap-autoantibody-blockade). This hypothesis proposes a second, *structural* route: physical loss of vagal cholinergic fibers. Acanfora et al.\ @acanfora2026vagaldenervation demonstrated selective depletion of VIP-positive (cholinergic) fibers in the gastric mucosa of Long COVID patients, correlating with reduced vagal HRV indices — direct in vivo evidence that autonomic dysfunction can rest on an anatomical lesion, not merely altered signaling. A proximal mechanism is available: Woo et al.\ @woo2023vagusinflammation found SARS-CoV-2 RNA and monocyte infiltration within the vagus nerve itself, and Lladós et al.\ @llados2024vagusdysfunction reported vagus-nerve thickening on ultrasound with reduced gastrointestinal peristalsis post-COVID — collectively confirming the decade-old prediction of VanElzakker @vanelzakker2013vagueinfection that pathogen-driven vagal injury underlies post-viral symptomatology. Because the vagus is the efferent arm of the cholinergic anti-inflammatory pathway (CAP; vagus → $alpha$7-nicotinic acetylcholine receptor → suppression of macrophage TNF-$alpha$), structural cholinergic denervation would disengage the CAP @tracey2002inflammatoryreflex @bonaz2018vagusmicrobiota, producing a self-sustaining proinflammatory state that plausibly maintains persistent post-viral symptoms (Acanfora studied Long COVID patients, a population with high but incomplete ME/CFS diagnostic overlap). The extrapolation to ME/CFS is currently indirect: no ME/CFS-specific vagal-mucosal histology exists, and ME/CFS shows *somatic* small fiber neuropathy (@sec:sfn) whereas Long COVID (Acanfora) showed *selectively visceral* loss (@oq:sfn-visceral-vs-somatic), so the two conditions may differ in fiber tropism.

*Testable prediction:* If structural vagal denervation drives CAP disengagement, then (a) ME/CFS patients undergoing gastric mucosal biopsy should show reduced VIP-positive fiber density relative to controls; (b) mucosal cholinergic fiber density should correlate inversely with circulating TNF-$alpha$ / CRP and positively with HF-HRV; and (c) this correlation should hold *independently* of GPCR autoantibody status, distinguishing the structural route from the functional autoantibody route. A stronger, two-hit version predicts *super-additive* CAP failure in patients positive for *both* structural fiber loss and CAP-relevant GPCR autoantibodies (@spec:cap-autoantibody-blockade): such double-positive patients should show the most refractory inflammation and the poorest taVNS response, because the pathway is disrupted at both the fiber and the signaling level. If ME/CFS gastric innervation is normal, if inflammation tracks autoantibody titres but not fiber density, or if double-positive patients are no worse than either single-positive subset, the corresponding claim is not supported for ME/CFS.

*Treatment implication:* Structural denervation, unlike functional blockade, may be only partially reversible. If confirmed in ME/CFS, this would raise the question of whether early intervention could preserve surviving fibers — a question that has no empirical basis at present. It provides a mechanistic rationale (not a clinical recommendation) for investigating vagus-nerve stimulation and cholinergic modulation — see the treatment chapters for the (limited) evidence base. This is a mechanistic hypothesis, not a basis for treatment.

*Limitations:* All direct structural evidence is Long-COVID-specific (Acanfora $n=12$, single-center, dyspeptic controls; Woo postmortem/acute; Lladós pilot $n=30$). The CAP linkage (Tracey, Bonaz) is foundational and well-replicated but not ME/CFS-specific. The structural and functional routes are not mutually exclusive and may coexist. No study has yet measured gastric cholinergic innervation in ME/CFS. Not independently replicated.

*Consequence:* This offers a concrete, biopsy-testable way to ask whether the autonomic problems in ME/CFS come from *destroyed* vagal nerves versus merely *blocked* signaling — a distinction that matters because destroyed nerves may need to be protected early rather than un-blocked later, and the answer would tell researchers whether treatments aimed at stimulating the vagus nerve are even targeting an intact structure.
] <hyp:structural-vagal-denervation-cap>
