#import "../../../../../shared/environments.typ": *

#hypothesis(title: [GPCR Autoantibodies as a Shared Transdiagnostic Neuroimmune Biomarker Across POTS, ME/CFS, and Long COVID])[
*Certainty: 0.60.* Functional GPCR autoantibodies targeting α1/β1/β2 adrenergic and M2/M4 muscarinic receptors represent a shared biomarker across the three conditions, with prevalence decreasing from POTS (89% by Gunning 2019 @Gunning2019GPCRPOTS, 8/17 by Fedorowski 2017 functional assay @Fedorowski2017Antiadrenergic) through Long COVID (Wallukat 2021 functional bioassay @Wallukat2021GPCRLongCOVID) to ME/CFS (29.5–91% prevalence depending on assay and cohort @Loebel2016 @Bynke2020). The autoantibodies demonstrate functional activity in cell-based assays @Fedorowski2017Antiadrenergic and animal passive transfer models @Li2019AdrenergicRabbit, supporting pathogenicity.

*Replication status:* Multiple independent cohorts in POTS (Oklahoma, Lund, Korean). Two independent cohorts in ME/CFS (Würzburg, Uppsala). Germain 2025 @Germain2025autoantibody null in ME/CFS (n=172 using REAP/Luminex) constitutes a substantive non-replication that may reflect assay sensitivity differences (conformational vs. linear epitopes).

*Limitations:* ELISA-based detection is not standardized across labs; functional bioassays are not scalable to routine clinical use; the Germain 2025 null requires resolution; no longitudinal data exist on titer stability.

*Assay artifact as the single biggest threat to the GPCR autoantibody evidence base.* Three detection platforms used across studies produce discordant results: CellTrend ELISA (conformation-preserving, full-length GPCRs on HEK cells) finds positive signals across ME/CFS, POTS, and Long COVID; functional cardiomyocyte bioassays (beating-rate assays) confirm activity in POTS and Long COVID but have not been systematically applied to ME/CFS; Luminex/REAP (linear epitope fragments) finds no signal in the largest ME/CFS screen to date @Germain2025autoantibody. If the CellTrend ELISA method detects non-specific binding, conformational artifacts, or irrelevant IgG subclasses rather than pathogenic autoantibodies, then the entire GPCR AAb evidence pillar — on which the transdiagnostic biomarker claim, the treatment rationale, and the neuroimmune convergence rest — is compromised. Resolving this discordance through head-to-head platform comparisons in the same patient cohort is the single highest priority for the GPCR autoantibody field.

*Falsifiable prediction:* Two-way ANOVA (condition × AAb panel) will show significant main effect of condition (POTS → ME/CFS → LC → HC, p \< 0.01) with effect size η² ≥ 0.25 for β2-AR and M3 targets. Falsified if no significant condition effect or η² \< 0.10.
] <hyp:gpcr-transdiagnostic-biomarker>
