#import "../../../../shared/environments.typ": *

#achievement(title: [Food Insecurity as an Observed Disease Correlate in ME/CFS and Long COVID])[
Cross-national evidence from multiple large-scale studies now documents a robust association between food insecurity and ME/CFS/Long COVID — adding a nutritional dimension to the well-documented socioeconomic impact of these diseases. However, the evidence base carries important structural limitations. ME/CFS-specific data comprise one NZ survey (Dey 2026, n unreported); Long COVID data are cross-sectional associations that cannot exclude reverse causation or confounding; and a systematic GRADE assessment would likely rate overall evidence as "very low" due to cross-sectional designs, single-anchor study status, and indirectness (most evidence from Long COVID, not ME/CFS — see @lim:fi-evidence-quality). (Certainty: 0.55 — downgraded from 0.75 to reflect GRADE very-low rating, single-anchor ME/CFS evidence, and LC→ME/CFS extrapolation risk)

*Evidence Base.*
- *Dey et al. 2026*—First and only ME/CFS-specific food insecurity survey, New Zealand (n unreported in abstract): ME/CFS and Long COVID patients report elevated rates of marginal, moderate, and severe food insecurity, with disease severity predicting food access difficulties and disability benefit inadequacy compounding the effect @dey2026foodinsecurity. (Certainty: 0.65; single study, not replicated)
- *Lin et al. 2025*—[Long COVID] NHIS 2022–2023 (n = 21,631): food insecurity associated with 73% higher odds of current Long COVID (aOR 1.73, 95% CI 1.39–2.15). 15% of food-insecure adults reported current Long COVID vs. 7% of food-secure adults. SNAP participation attenuated the association (p-interaction=0.04, uncorrected for multiple comparisons). Food-insecure individuals had 30% lower odds of recovery from prior Long COVID (aOR 0.70, 95% CI 0.54–0.92) — however, this is a cross-sectional association compatible with disease severity as common cause: persistent disease produces both continued FI and lower recovery rates, providing no independent evidence for FI→disease feedback @lin2025longcovidfoodinsecurity. (Certainty: 0.80)
- *Datta 2025*—[Long COVID] BRFSS 2022 (n = 271,076): Long COVID independently associated with 1–11 percentage-point increases in food insecurity across income and education strata. Employment loss and reduced work hours mediated 6–20% of the effect @datta2025longcovidfinancial. The unmediated 80–94% may reflect reverse causation, unmeasured confounding, or pathways not identified. (Certainty: 0.75)
- *Feldman 2025*—[Composite SDoH] NIH RECOVER adult cohort: social determinants of health, including food access as one undifferentiated component of a composite SDoH measure, independently associated with Long COVID risk @feldman2025sdohlongcovid. (Certainty: 0.70; composite measure — not food-insecurity-specific evidence)
- *Bowden 2026*—New Zealand nationwide cross-sectional (n = 1,902 ME/CFS on benefit): only 18.3% employed vs. 83.8% general population; 64.7% on Supported Living Payment @bowden2026mecfslabourmarket. This employment gap is the hypothesised mechanism through which food insecurity arises in ME/CFS — absent adequate income, nutritional adequacy becomes compromised. (Certainty: 0.75; does not measure FI directly)

*Interpretation.*
ME/CFS and Long COVID are associated with increased food insecurity. The employment-mediation evidence (Datta 2025: up to 20% mediated) supports the causal direction disease→FI but leaves 80–94% of the association unexplained. The FI→disease feedback direction is hypothesised but not demonstrated: the recovery association (Lin 2025: aOR 0.70) is compatible with severity-as-common-cause and provides no independent evidence beyond what the employment-mediation chain predicts. Both directions require prospective and interventional confirmation.

*Falsifiability.*
This claim would be refuted if prospective studies find that ME/CFS patients show no elevated FI after controlling for pre-illness income and wealth — testing whether the disease independently causes downward economic mobility beyond pre-existing poverty (narrower than the original falsification condition, which tested a universally acknowledged mechanism). Additional refutation: interventional trials show that resolving FI does not improve ME/CFS functional outcomes.

*Consequence:* Food insecurity is a documented socioeconomic correlate of ME/CFS and Long COVID with implications for clinical awareness and policy. The strength of causal inference is limited by cross-sectional designs and heavy reliance on Long COVID evidence extrapolated to ME/CFS. Food assistance programs may be justified on quality-of-life and financial grounds regardless of whether FI modifies disease biology.
] <ach:food-insecurity-disease-burden>
