#import "../../../../../shared/environments.typ": *

#speculation(title: [Orexin→PKA→Tau Phosphorylation: A Production-Side Mechanism Distinct from Glymphatic Clearance])[
*Certainty: 0.25.* Parhizkar et al.\ (2025) demonstrated in P301S/E4 tauopathy mice that lemborexant --- a dual orexin receptor antagonist (DORA) --- reduces tau phosphorylation via cAMP/PKA pathway inhibition, preventing neurodegeneration independently of sleep promotion @Parhizkar2025LemborexantTau. The critical dissociation: zolpidem increased sleep duration but provided *no* neuroprotection, establishing orexin signaling (not sleep duration) as the mechanistic driver. Lucey et al.\ (2023) provided human validation in an RCT (n=38): suvorexant 20 mg reduced CSF p-tau181/T181 ratio by ~10--15% in cognitively unimpaired adults @Lucey2023SuvorexantTau. Together, these studies identify a #strong[production-prevention] pathway --- orexin antagonism reduces tau phosphorylation before aggregation begins --- that is mechanistically distinct from the #strong[clearance-enhancement] pathway (glymphatic removal of already-accumulated waste) and the #strong[damage-reversal] pathway (HSP70-mediated repair, Chapter @ch:neurological).

*Relevance to ME/CFS.* Three axes of relevance, none yet tested in ME/CFS:

    - *Differential DORA safety:* The paper's existing glymphatic medication warning (Section @sec:ch15-glymphatic) lists DORAs among potentially glymphatic-impairing agents via LC-NE pathway effects @Zhu2025noradrenergicGlymphatic. However, Parhizkar et al.\ demonstrate a countervailing benefit: even if DORAs mildly suppress NE oscillations, they may simultaneously reduce tau phosphorylation via PKA. This creates an unresolved risk--benefit trade-off specific to DORAs (not Z-drugs, which carry glymphatic impairment without tau protection). The net effect in ME/CFS --- where orexin is already suppressed --- is unknown.

    - *Orexin tone paradox:* ME/CFS involves partial orexin *suppression* (Section @sec:ch15-orexin), while Parhizkar 2025's protection requires pharmacological orexin *antagonism*. If endogenous orexin is already low, the PKA pathway may already be downregulated in ME/CFS --- potentially providing endogenous protection against tau hyperphosphorylation. Conversely, the "tired but wired" phenotype suggests incomplete suppression: residual orexin tone during supposed "sleep" periods may drive both sleep fragmentation *and* pathological tau phosphorylation, in which case DORAs could provide dual benefit. This is entirely unresolved.

    - *Neurodegeneration risk context:* The paper's chronic glymphatic impairment speculation (Section @sec:ch15-neurodegeneration-risk) predicts elevated long-term tau/amyloid accumulation in ME/CFS from impaired clearance. Parhizkar 2025 adds the complementary possibility that tau may be produced *faster* (via orexin→PKA→phosphorylation) as well as cleared *slower* (via glymphatic failure) --- a double hit on tau homeostasis. This is a cross-disease extrapolation from a tauopathy model; no ME/CFS tau phosphorylation data exist.

*Falsifiable prediction:* ME/CFS patients should show higher CSF p-tau181/T181 ratios than age-matched controls, with ratio correlating with CSF orexin-A levels and unrefreshing sleep severity.

*Limitations:* Single preclinical study, male mice only, tauopathy model (not ME/CFS). Human validation (Lucey 2023) is acute single-dose, cognitively unimpaired participants. The PKA pathway has not been studied in ME/CFS. All claims are cross-disease extrapolation.
] <spec:ch15-orexin-pka-tau>
