#import "../../shared/environments.typ": *

== Brain Energy Metabolism: Cross-Disease Convergent Framework
<sec:brain-energy-cross-disease>

The energy metabolism abnormalities documented in ME/CFS peripheral tissues --- impaired oxidative phosphorylation (OXPHOS, the mitochondrial process that produces most cellular ATP), a shift toward less efficient glycolysis (sugar breakdown in the cytoplasm), and elevated blood lactate --- converge with brain imaging findings to suggest a brain energy deficit that may directly drive cognitive symptoms. This section synthesizes evidence from ME/CFS neuroimaging and cross-disease models to propose that brain energy metabolism dysfunction is not merely a downstream consequence of systemic illness but a central mechanism contributing to cognitive dysfunction, sensory processing deficits, and the selective impairment of energy-demanding CNS-coordinated processes.

#speculation(title: [Astrocyte-Mediated Brain Energy Conservation as Cognitive Dysfunction Mechanism])[
*Certainty: 0.45 (0.40→0.45: reinforced by convergence with astrocyte-gate @spec:astrocyte-gate and energy-triage @hyp:energy-triage — two independent lines from different mechanisms converge on same endpoint; originally 0.40).* Blagojevic-Stokic et al. (2026) proposed a comprehensive brain energy disorder model for autism spectrum disorder (ASD) in which astrocytic glucose metabolism dysfunction --- impaired glucose uptake, glycogen storage failure, and disrupted astrocyte-neuron lactate shuttling --- produces suboptimal ATP availability in the brain @BlagojevicStokic2026brainenergy. Their model posits an "energy-saving adaptation": the brain economizes by deprioritizing higher-order, energy-intensive processes (social communication, cognitive flexibility, sensory integration) to preserve ATP for basic survival functions. Independently, Lacourt et al. (2018) developed a structurally identical model for ME/CFS fatigue: chronic low-grade inflammation → reduced cellular energy availability → non-adaptive energy conservation as fatigue mechanism @Lacourt2018InflammationEnergy. The two models, derived from different disease contexts without cross-reference, converge on the same mechanistic logic: energy deficit drives cognitive and behavioural sacrifice.

*ME/CFS evidence.* ME/CFS independently exhibits the core biochemical features of the ASD brain energy model: (1) regional brain glucose hypometabolism — reduced sugar uptake in specific brain areas — visible on FDG-PET scans (a nuclear imaging technique that tracks radioactively labeled glucose; Siessmeier et al., 2003, n=26; Van Der Gucht et al., 2017, n=24) @siessmeier2003pet @VanDerGucht2017MMFFDG; (2) elevated ventricular lactate on magnetic resonance spectroscopy (MRS), indicating the brain is shifting toward less efficient sugar breakdown (glycolysis) rather than the oxygen-dependent mitochondrial pathway (OXPHOS) that produces 15 times more ATP per sugar molecule (Natelson et al., 2017, n=34 CFS) @Natelson2017Lactate; (3) astrocyte dysfunction implicated in central fatigue pathways (Morris & Maes, 2015) @Morris2015CentralPathways; and (4) a comprehensive 2026 brain-centered cognitive dysfunction framework that explicitly includes astrocytic glucose metabolism and lactate shuttle disruption (Xu et al., 2026) @Xu2026Neurovascular. Zhu et al. (2025) synthesized FDG-PET, MRS, and mitochondrial evidence into a convergent cerebral metabolic signature in ME/CFS @Zhu2025MetabolicNeuroimaging. (Certainty: 0.40 --- the individual components are independently supported, but the assembled framework is a mechanistic inference across studies; no direct study has simultaneously measured brain glucose, brain lactate, astrocyte function, and cognitive performance in the same ME/CFS cohort.)

*Parallel to ASD model.* In both conditions, prefrontal cortex (PFC) appears particularly vulnerable: this region has the highest metabolic rate in the human brain, the highest glycolysis/OXPHOS pathway expression, and the greatest astrocyte specialisation. ME/CFS patients show reduced activation in PFC-dependent cognitive tasks and impaired cognitive flexibility --- the same domain predicted to fail first under energy constraint. The ASD model's "energy-saving barter" --- sacrificing cognitive flexibility, novel information processing, and social engagement to preserve ATP for survival functions --- maps precisely onto ME/CFS cognitive symptoms: brain fog as reduced information processing capacity, impaired task-switching as cognitive rigidity under energy constraint, and sensory overload as inability to filter irrelevant stimuli without sufficient ATP for inhibitory networks.

*Limitations.* The ASD model is neurodevelopmental; ME/CFS is acquired. GLUT1 deficiency syndrome provides proof-of-concept that impaired brain glucose transport produces ASD-like deficits, but no GLUT1 data exist in ME/CFS. PFC-specific glucose metabolism has not been studied in ME/CFS.

*Falsifiable prediction.* (1) Hyperpolarized #super[13]C-MRS will demonstrate reduced glucose-to-lactate conversion rate in ME/CFS PFC during cognitive tasks. (2) Ketogenic diet will improve cognitive scores in ME/CFS patients with documented brain hypometabolism. (3) ME/CFS patients will show steeper cognitive decline during prolonged testing (≥ 60 min).
] <spec:astrocyte-brain-energy-conservation>

#open-question(title: [Is Brain Glucose Hypometabolism in ME/CFS Primary or Secondary?])[
ME/CFS brain glucose hypometabolism is documented but its causal status is unresolved. Four models: (1) primary metabolic (astrocytes or neurons have an intrinsic energy-production defect), (2) perfusion-limited (reduced cerebral blood flow — documented in the majority of patients — starves the brain of fuel regardless of how well cells can use it), (3) inflammation-masked (activated immune cells in the brain consume glucose for their own inflammatory signaling, hiding a true neuronal energy deficit on scans), (4) compensatory downregulation (neurons deliberately reduce their energy use as an adaptive response to whole-body energy shortage). These models are not mutually exclusive. Distinguishing them requires simultaneous #super[13]C-MRS (which tracks how fast glucose is converted to lactate in real time) with cerebral blood flow measurement, TSPO-PET (which quantifies activated immune cells in the brain and their glucose consumption), and ketone-body MRS to test whether neurons can use alternative fuels when glucose supply is limited.
] <oq:brain-hypometabolism-primary-vs-secondary>

#open-question(title: [Can Ketogenic Diet Improve ME/CFS Cognitive Symptoms via Brain Energy Restoration?])[
The ASD brain energy model identifies ketogenic diet as therapeutic proof-of-concept: ketone bodies (fat-derived molecules the brain can burn as alternative fuel) bypass glycolysis and the pyruvate dehydrogenase complex (PDC) blockade, entering the tricarboxylic acid (TCA) cycle — the mitochondrial furnace — directly as acetyl-CoA @BlagojevicStokic2026brainenergy. ME/CFS-specific clinical data are limited to case reports (n=1) @Zarnowska2018KD and ASD trials (not ME/CFS) @Lee2018modifiedKD. Key unknowns: (1) Does brain ketone uptake differ in ME/CFS? (2) Is improvement proportional to baseline hypometabolism? (3) Does effect depend on hypometabolism being metabolic vs perfusion-limited? (4) Can exogenous ketone esters test the mechanism without full dietary change --- critical for severe patients?
] <oq:ketogenic-diet-brain-energy>

=== Limitations of the ASD-ME/CFS Brain Energy Convergence

#limitation(title: [Brain Hypometabolism May Be Epiphenomenon, Not Mechanism])[
*Origin: brainstorm.* Shared FDG-PET and MRS patterns between ASD and ME/CFS could be epiphenomenal to: (1) physical deconditioning, (2) sleep disruption, or (3) systemic inflammation — each would produce indistinguishable metabolic patterns without any GLUT1/astrocytic bottleneck. No study has ruled out these alternative explanations in ME/CFS.
]

#limitation(title: [No Direct Astrocytic Evidence in ME/CFS])[
*Origin: brainstorm.* Astrocytic GLUT1 (glucose transporter protein at the blood-brain barrier) and ANLS (astrocyte-neuron lactate shuttle — the cellular supply chain that delivers fuel from support cells to neurons) failure has never been directly tested in ME/CFS. FDG-PET measures summed glucose uptake across all cell types. MRS measures bulk tissue metabolites. No ME/CFS study has quantified astrocytic GLUT1 or measured ANLS function. The evidence is entirely indirect.
]

#open-question(title: [Null Hypothesis: Brain Metabolism Does Not Differ Between ME/CFS and Other Fatigue Conditions])[
*Origin: brainstorm.* Does ME/CFS brain metabolism differ from depression-associated fatigue, MS fatigue, or post-cancer fatigue? All show frontal/basal ganglia hypometabolism — overlapping with ME/CFS. Candidate ME/CFS-specific differentiators: low CSF:plasma glucose ratio, astrocyte-specific metabolic markers, correlation between brain metabolism and PEM. A head-to-head comparison study is needed.
] <oq:brain-metabolism-specificity-fatigue>

=== Speculative Brain Energy Interventions

#speculation(title: [Ketone Esters + MCT Oil for Brain Glucose Bypass in ME/CFS])[
*Certainty: 0.35 (0.30→0.35: feed-into from @spec:astrocyte-gate cert 0.50 — if astrocytes are the bottleneck, ketone bypass directly solves the problem; contingent on astrocyte-gate cert ≥ 0.50). Probability of clinically meaningful efficacy in ME/CFS: 0.06. Origin: brainstorm.* If GLUT1-mediated brain glucose transport is impaired, ketone bodies (fat-derived fuel molecules) provide an alternative fuel that enters the brain via a different transporter (MCT1) rather than GLUT1 — directly bypassing the bottleneck. Ketone esters (lab-made ketone drinks, 15--30 grams per day) plus MCT oil (medium-chain triglyceride oil from coconut or palm, 2--4 tablespoons per day) raise blood ketone levels (beta-hydroxybutyrate, BHB) to 2--5 millimolar within 30 minutes — enough to fuel the brain without glucose. MCT oil has a dual action: its C8 component (octanoic acid) drives ketone production in the liver, while its C10 component (decanoic acid) stimulates astrocytes to produce lactate — the brain's backup fuel @Andersen2021MCTastrocytes. No ME/CFS-specific trial data exist.

*Severity applicability:* All levels. Severe: micro-dose MCT (¼ tsp, titrate). Very severe: ketone esters if tolerated; environmental energy conservation may be primary.

*Falsifiable prediction.* ME/CFS patients with documented prefrontal FDG-PET hypometabolism who achieve blood BHB ≥ 0.5 mM will show cognitive improvement proportional to baseline hypometabolism severity.
] <spec:ketone-esters-mct-bypass>

#open-question(title: [CSF:Plasma Glucose Ratio as GLUT1 Bottleneck Biomarker in ME/CFS])[
*Origin: brainstorm.* The clinical test for GLUT1 deficiency syndrome is the CSF:plasma glucose ratio — a comparison of sugar levels between spinal fluid (CSF, obtained by lumbar puncture) and blood drawn at the same time. In healthy people, spinal fluid glucose is typically 60% or more of blood glucose (ratio ≥ 0.60). In GLUT1 deficiency, the glucose transporter at the blood-brain barrier is impaired, so less sugar enters the brain, and the ratio drops below 0.50--0.60. If ME/CFS involves functional GLUT1 impairment, patients should show similarly reduced ratios. This has never been measured in ME/CFS. A single lumbar puncture study (n=30 ME/CFS, n=30 controls) with paired glucose measurement could define a treatable ME/CFS subtype. If 20--40% of patients show ratios below 0.50, this would parallel GLUT1 deficiency syndrome — where the standard treatment (ketogenic diet) directly corrects the underlying problem by providing alternative fuel that enters the brain without needing GLUT1.
] <oq:csf-plasma-glucose-ratio>

#open-question(title: [GLUT1 Deficiency Syndrome as Monogenic ME/CFS Model])[
*Origin: brainstorm.* GLUT1 deficiency syndrome (G1D, caused by mutations in the SLC2A1 gene) impairs glucose transport across the blood-brain barrier, producing epilepsy, cognitive delay, movement disorders, and ASD-like social and communication deficits — all of which improve markedly with ketogenic diet therapy (which provides alternative fuel that bypasses the broken glucose transporter). G1D is a monogenic analogue — a single-gene disease model — to the acquired brain glucose transport failure hypothesized in ME/CFS. Key questions: (1) Do adults with milder G1D variants (who have partial transporter impairment, not complete loss) report ME/CFS-like symptoms at elevated rates? (2) Could common SLC2A1 gene variants that modestly reduce GLUT1 expression — not enough to cause G1D, but enough to lower the brain's energy reserve — constitute a genetic predisposition to ME/CFS? This is testable in DecodeME (n > 17,000, existing genotyping — no new data collection needed). (3) Do G1D patient registries capture fatigue, PEM, and orthostatic intolerance, or only classical neurological symptoms like seizures and movement problems? G1D provides a causal-anchor model: if the GLUT1 bottleneck hypothesis is correct, G1D patients should show elevated ME/CFS rates. If they report only epilepsy and movement disorders without fatigue or PEM, the GLUT1-to-ME/CFS link is weakened.
] <oq:glut1-deficiency-mecfs-model>

#speculation(title: [Severity-Adapted Brain Energy Restoration Protocol])[
*Certainty: 0.25 (0.20→0.25: feed-into from @hyp:selective-dysfunction cert 0.55 — if selective dysfunction is correct, severity-adapted energy protocols follow logically; contingent on selective-dysfunction cert ≥ 0.50). Probability of clinically meaningful efficacy in ME/CFS: 0.04. Origin: brainstorm.* Brain energy interventions require severity-adapted protocols. Mild: ketone esters 15 g/day + MCT 1 tbsp + cognitive pacing. Moderate: reduced doses + pre-dose before exertion. Severe: micro-dose MCT (¼ tsp), neuroprotection only. Very severe: environmental energy conservation (dark, quiet, minimal sensory input), ketones if tolerated.

*Falsifiable prediction.* Severity-stratified 8-week protocol: (1) moderate patients --- at least 80% complete full-dose regime (15 g ketone esters + 1 tbsp MCT) with at most 1 GI adverse event requiring dose reduction, and show at least 1 SD improvement on 2/4 cognitive domains (processing speed, task-switching, working memory, sustained attention). (2) Severe patients --- at least 70% complete micro-dose regime (1/4 tsp MCT) for 8 weeks without stopping, with at least 20% within-subject stability in cognitive scores (no decline >0.5 SD). (3) Very severe --- at least 50% cannot tolerate any oral intervention (stopped within 2 weeks). Falsified if between-group tolerance proportions differ by less than 20 percentage points or if cognitive improvement in moderate group does not exceed within-subject variability.
] <spec:severity-adapted-brain-energy>

#synthesis[
*Convergent pathophysiology across ASD and ME/CFS.* The body of evidence establishes that ME/CFS independently exhibits all core biochemical features of the ASD brain energy disorder model: regional brain glucose hypometabolism on FDG-PET scans (@spec:astrocyte-brain-energy-conservation, cert 0.45), elevated ventricular lactate on MRS, astrocyte-to-neuron fuel supply dysfunction (@Xu2026Neurovascular), and an energy conservation fatigue model structurally identical to the ASD model despite independent development (@Lacourt2018InflammationEnergy). The pre-existing selective dysfunction hypothesis (@spec:astrocyte-gate, cert 0.50) and CNS energy triage framework (@spec:cns-energy-triage, cert 0.35) provide complementary models that are mutually reinforced by this cross-disease convergence. The strongest constraints: no direct measurement of the glucose transporter protein or fuel shuttle in ME/CFS brain tissue; ASD is a developmental condition while ME/CFS is acquired; reduced brain blood flow (documented in most patients) could produce the same imaging pattern without any transporter defect (@oq:brain-hypometabolism-primary-vs-secondary). The most testable hypothesis is the spinal fluid-to-blood glucose ratio (@oq:csf-plasma-glucose-ratio) — a standard clinical test that directly measures whether the glucose gate at the blood-brain barrier is working, costing approximately $50,000 to $100,000 for a definitive study. The most actionable direction is the ketone fuel bypass (@spec:ketone-esters-mct-bypass, cert 0.35; @oq:ketogenic-diet-brain-energy), with strong mechanistic logic but zero controlled data in ME/CFS. The framework's primary value is in providing testable predictions, identifying tractable research priorities, and anchoring convergent mechanistic logic across two independent disease research communities that arrived at the same conclusion without knowing about each other.
] <syn:brain-energy-asd-mecfs-model>
