#import "../../shared/environments.typ": *

== Brain Energy Metabolism: Cross-Disease Convergent Framework
<sec:brain-energy-cross-disease>

The energy metabolism abnormalities documented in ME/CFS peripheral tissues --- impaired oxidative phosphorylation (OXPHOS, the mitochondrial process that produces most cellular ATP), a shift toward less efficient glycolysis (sugar breakdown in the cytoplasm), and elevated blood lactate --- converge with brain imaging findings to suggest a brain energy deficit that may directly drive cognitive symptoms. This section synthesizes evidence from ME/CFS neuroimaging and cross-disease models to propose that brain energy metabolism dysfunction is not merely a downstream consequence of systemic illness but a central mechanism contributing to cognitive dysfunction, sensory processing deficits, and the selective impairment of energy-demanding CNS-coordinated processes.

#speculation(title: [Astrocyte-Mediated Brain Energy Conservation as Cognitive Dysfunction Mechanism])[
*Certainty: 0.45 (0.40→0.45: reinforced by convergence with astrocyte-gate @spec:astrocyte-gate and energy-triage @hyp:energy-triage — two independent lines from different mechanisms converge on same endpoint; originally 0.40).* Blagojevic-Stokic et al. (2026) proposed a comprehensive brain energy disorder model for autism spectrum disorder (ASD) in which astrocytic glucose metabolism dysfunction --- impaired glucose uptake, glycogen storage failure, and disrupted astrocyte-neuron lactate shuttling --- produces suboptimal ATP availability in the brain @BlagojevicStokic2026brainenergy. Their model posits an "energy-saving adaptation": the brain economizes by deprioritizing higher-order, energy-intensive processes (social communication, cognitive flexibility, sensory integration) to preserve ATP for basic survival functions. Independently, Lacourt et al. (2018) developed a structurally identical model for ME/CFS fatigue: chronic low-grade inflammation → reduced cellular energy availability → non-adaptive energy conservation as fatigue mechanism @Lacourt2018InflammationEnergy. The two models, derived from different disease contexts without cross-reference, converge on the same mechanistic logic: energy deficit drives cognitive and behavioural sacrifice.

*ME/CFS evidence.* ME/CFS independently exhibits the core biochemical features of the ASD brain energy model: (1) regional brain glucose hypometabolism — reduced sugar uptake in specific brain areas — visible on FDG-PET scans (a nuclear imaging technique that tracks radioactively labeled glucose; Siessmeier et al., 2003, n=26; Van Der Gucht et al., 2017, n=24) @siessmeier2003pet @VanDerGucht2017MMFFDG; (2) elevated ventricular lactate on magnetic resonance spectroscopy (MRS), indicating the brain is shifting toward less efficient sugar breakdown (glycolysis) rather than the oxygen-dependent mitochondrial pathway (OXPHOS) that produces 15 times more ATP per sugar molecule (Natelson et al., 2017, n=34 CFS) @Natelson2017Lactate; (3) astrocyte dysfunction implicated in central fatigue pathways (Morris & Maes, 2015) @Morris2015CentralPathways; and (4) a comprehensive 2026 brain-centered cognitive dysfunction framework that explicitly includes astrocytic glucose metabolism and lactate shuttle disruption (Xu et al., 2026) @Xu2026Neurovascular. Zhu et al. (2025) synthesized FDG-PET, MRS, and mitochondrial evidence into a convergent cerebral metabolic signature in ME/CFS @Zhu2025MetabolicNeuroimaging. (Certainty: 0.40 --- the individual components are independently supported, but the assembled framework is a mechanistic inference across studies; no direct study has simultaneously measured brain glucose, brain lactate, astrocyte function, and cognitive performance in the same ME/CFS cohort.)

*Parallel to ASD model.* In both conditions, the prefrontal cortex (PFC, the brain region behind the forehead responsible for planning, decision-making, and impulse control) appears particularly vulnerable: it has the highest metabolic rate in the human brain, so it is the first region to suffer when energy runs short. ME/CFS patients show reduced PFC activation during cognitive tasks and impaired cognitive flexibility — the same domain predicted to fail first under energy constraint. The ASD model's "energy-saving barter" maps directly onto the daily experience of ME/CFS: brain fog is not a vague complaint but a predictable consequence of insufficient fuel reaching the PFC; the inability to switch between tasks or adapt to unexpected changes reflects cognitive rigidity imposed by energy shortage, not a personality trait; sensory overload — being overwhelmed by noise, light, or multiple conversations — occurs because filtering out irrelevant stimuli requires inhibitory brain networks that consume large amounts of ATP, and when ATP is scarce, the brain cannot afford to run those filters. This reframes symptoms that are often dismissed as psychological or behavioural as direct biological consequences of a brain running on an inadequate energy budget.

*Limitations.* The ASD model describes a brain whose energy systems were disrupted during early development — before birth or in infancy — so its circuits were built around that deficit. ME/CFS typically begins in adolescence or adulthood, meaning the brain developed normally and then lost energy capacity later. This is a critical difference: an adult brain trying to run on a reduced energy budget may behave differently from a brain that never had full capacity to begin with. GLUT1 deficiency syndrome provides proof-of-concept that impaired brain glucose transport produces cognitive and behavioural deficits, but no measurements of the GLUT1 transporter protein exist in ME/CFS brain tissue. PFC-specific glucose metabolism has not been studied in ME/CFS.

*Falsifiable prediction.* (1) Hyperpolarized #super[13]C-MRS will demonstrate reduced glucose-to-lactate conversion rate in ME/CFS PFC during cognitive tasks. (2) Ketogenic diet will improve cognitive scores in ME/CFS patients with documented brain hypometabolism. (3) ME/CFS patients will show steeper cognitive decline during prolonged testing (≥ 60 min).
] <spec:astrocyte-brain-energy-conservation>

#open-question(title: [Is Brain Glucose Hypometabolism in ME/CFS Primary or Secondary?])[
ME/CFS brain glucose hypometabolism — reduced sugar uptake in specific brain regions — is documented but its causal status is unresolved. This matters because each possible cause implies a completely different treatment strategy. Four models: (1) *Intrinsic energy-production defect*: astrocytes or neurons cannot make enough ATP even when fuel supply is normal. If correct, treatment should target the cellular machinery directly — mitochondrial support, metabolic cofactors — and the ketogenic diet should help because ketones bypass the broken steps. (2) *Fuel delivery failure*: reduced cerebral blood flow (documented in the majority of patients during upright posture) starves the brain of glucose regardless of how well cells can use it. If correct, treatment should target blood flow — volume expansion, vasodilators, horizontal positioning — and a ketogenic diet would help less because the problem is delivery, not utilisation. (3) *Hidden deficit masked by inflammation*: activated immune cells in the brain consume large amounts of glucose for inflammatory signaling, making overall brain glucose uptake look normal on scans while neurons are actually starving. If correct, anti-inflammatory treatments could unmask an energy crisis that currently looks like normal metabolism, and combining anti-inflammatories with metabolic support might be necessary. (4) *Adaptive hibernation*: neurons deliberately reduce their energy consumption as a protective response to whole-body energy shortage, like a laptop dimming its screen to save battery. If correct, the brain is not broken — it is protecting itself — and treatments that force increased brain activity (such as graded exercise or cognitive training) would worsen outcomes by overriding a protective mechanism. These models are not mutually exclusive; a patient could have poor fuel delivery *and* mitochondrial impairment *and* inflammatory glucose consumption. Distinguishing them requires simultaneous measurements of glucose-to-lactate conversion rate, cerebral blood flow, immune cell glucose consumption, and ketone utilisation — all in the same patient, during a cognitive challenge, which has never been done in ME/CFS.
] <oq:brain-hypometabolism-primary-vs-secondary>

#open-question(title: [Can Ketogenic Diet Improve ME/CFS Cognitive Symptoms via Brain Energy Restoration?])[
The ASD brain energy model identifies ketogenic diet as therapeutic proof-of-concept: ketone bodies (fat-derived molecules the brain can burn as alternative fuel) bypass the damaged steps in glucose metabolism and enter the mitochondrial furnace directly @BlagojevicStokic2026brainenergy. ME/CFS-specific clinical data are limited to a single case report (n=1) @Zarnowska2018KD and ASD trials in children (not ME/CFS) @Lee2018modifiedKD. The practical questions for patients and clinicians are: (1) If a patient tries a ketogenic diet, will their brain actually take up and use ketones, or is their brain ketone uptake itself defective? (2) Will cognitive improvement — if any — be proportional to how severely glucose-deprived their brain was before the diet, meaning a brain scan could predict who benefits? (3) If the hypometabolism is caused by poor blood flow rather than a transporter defect, will ketones help at all or is the real problem delivery of any fuel, not just glucose? (4) Can exogenous ketone esters — lab-made ketone drinks that raise blood ketones within 30 minutes without requiring a full dietary overhaul — test the mechanism? This matters because a full ketogenic diet requires meal preparation, dietary discipline, and GI tolerance that may be impossible for severe patients; a drinkable test dose could rapidly determine whether the approach is worth pursuing.
] <oq:ketogenic-diet-brain-energy>

=== Limitations of the ASD-ME/CFS Brain Energy Convergence

#limitation(title: [Brain Hypometabolism May Be Epiphenomenon, Not Mechanism])[
*Origin: brainstorm.* Shared FDG-PET and MRS patterns between ASD and ME/CFS could be epiphenomenal to: (1) physical deconditioning (being bedbound or housebound reduces cardiac output, which reduces brain blood flow, which reduces brain glucose delivery — the brain looks starved because the patient is immobile, not because the brain has a transporter defect), (2) sleep disruption (poor sleep impairs the brain's nightly waste-clearance system, causing metabolic debris to accumulate and brain cells to slow down), or (3) systemic inflammation (inflammatory signals travelling in the blood cause neurons to reduce their activity as a protective response — the brain is not broken, it is hibernating). Each would produce brain scans indistinguishable from the ASD model's prediction, but none requires a GLUT1 transporter defect or astrocyte dysfunction. If any of these alternative explanations is correct, interventions targeting the glucose transporter (ketone esters, GLUT1 upregulators) would fail — the real treatment would be mobilisation, sleep restoration, or anti-inflammatory therapy respectively. No study has ruled out these alternatives in ME/CFS by measuring brain metabolism while controlling for activity level, sleep quality, and inflammatory markers simultaneously.
]

#limitation(title: [No Direct Astrocytic Evidence in ME/CFS])[
*Origin: brainstorm.* Astrocytic GLUT1 (the protein that transports glucose from blood into brain support cells) and the ANLS (the cellular supply chain that converts glucose to lactate in astrocytes and delivers it to neurons) have never been directly measured in ME/CFS. FDG-PET scans show total glucose uptake summed across all brain cell types — they cannot distinguish whether neurons, astrocytes, or inflammatory immune cells are consuming the glucose. MRS measures the total amount of lactate and other metabolites in a brain region — it cannot tell you whether that lactate came from astrocytes trying to feed neurons, from neurons undergoing glycolytic stress, or from activated immune cells. This is not a minor gap — it means the entire framework rests on indirect inference. The practical consequence: before clinical trials of GLUT1-targeting interventions begin, at least one of two minimal evidence steps must return positive: (1) astrocyte-derived extracellular vesicles isolated from patient blood showing reduced GLUT1 protein, or (2) a spinal fluid-to-blood glucose ratio below 0.50 in a subset of patients. Without at least one of these, clinical trials risk testing an intervention against a mechanism that may not actually be present in the patients enrolled.
]

#open-question(title: [Null Hypothesis: Brain Metabolism Does Not Differ Between ME/CFS and Other Fatigue Conditions])[
*Origin: brainstorm.* If ME/CFS brain metabolism is indistinguishable from the brain metabolism of other fatiguing illnesses, the entire ASD convergence argument loses disease specificity — it would describe a general property of severe fatigue regardless of cause, not something unique to ME/CFS. Does ME/CFS brain metabolism differ from depression-associated fatigue, MS fatigue, or post-cancer fatigue? All three conditions show reduced frontal and basal ganglia glucose uptake on FDG-PET — overlapping with ME/CFS findings. No study has directly compared ME/CFS brain metabolism to fatigue-matched controls from other conditions. The practical stakes: if the brain metabolic signature is generic, then brain-energy-targeted treatments would work equally well (or poorly) across all fatiguing illnesses, and the biomarker value is zero — you cannot use a brain scan to distinguish ME/CFS from depression if both show the same pattern. Candidate ME/CFS-specific differentiators that could give the model disease specificity: (1) low spinal fluid-to-blood glucose ratio would indicate a GLUT1 transporter bottleneck — not expected in depression, MS, or cancer fatigue where the transporter is presumably intact; (2) astrocyte-specific metabolic markers (GLUT1 on astrocyte-derived vesicles, MCT4 export transporter, lactate dehydrogenase B isoform) would be abnormal in ME/CFS but not in conditions where fatigue originates from neuronal or systemic sources; (3) correlation between brain metabolism and post-exertional malaise — a symptom unique to ME/CFS — would anchor the metabolic finding to the defining clinical feature. A head-to-head comparison study across fatiguing conditions with all three measurements would resolve this.
] <oq:brain-metabolism-specificity-fatigue>

=== Speculative Brain Energy Interventions

#speculation(title: [Ketone Esters + MCT Oil for Brain Glucose Bypass in ME/CFS])[
*Certainty: 0.35 (0.30→0.35: feed-into from @spec:astrocyte-gate cert 0.50 — if astrocytes are the bottleneck, ketone bypass directly solves the problem; contingent on astrocyte-gate cert ≥ 0.50). Probability of clinically meaningful efficacy in ME/CFS: 0.06. Origin: brainstorm.* If GLUT1-mediated brain glucose transport is impaired, ketone bodies (fat-derived fuel molecules) provide an alternative fuel that enters the brain via a different transporter (MCT1) rather than GLUT1 — directly bypassing the bottleneck. Ketone esters (lab-made ketone drinks, 15--30 grams per day) plus MCT oil (medium-chain triglyceride oil from coconut or palm, 2--4 tablespoons per day) raise blood ketone levels (beta-hydroxybutyrate, BHB) to 2--5 millimolar within 30 minutes — enough to fuel the brain without glucose. MCT oil has a dual action: its C8 component (octanoic acid) drives ketone production in the liver, while its C10 component (decanoic acid) stimulates astrocytes to produce lactate — the brain's backup fuel @Andersen2021MCTastrocytes. No ME/CFS-specific trial data exist.

*What this means for patients now.* A patient who wants to test this hypothesis themselves can try MCT oil alone (available over the counter, approximately USD 0.50--1.00 per day) before considering the more expensive ketone esters (approximately USD 3--5 per day, mail-order). Start with ¼ teaspoon of MCT oil with food and titrate slowly over several weeks to assess GI tolerance — diarrhea and nausea are common at higher doses and are dose-dependent, not dangerous. Track cognitive function at the same time each day using a simple self-rating (0--10 scale for brain fog, processing speed, and task-switching ability). If no subjective improvement after 4 weeks of consistent use at a tolerated dose, the mechanism is either wrong for that individual or the dose was insufficient. Do not interpret a negative self-trial as ruling out the hypothesis — it only rules it out for that person at that dose. MCT oil is not a treatment recommendation; it is a low-risk, low-cost self-experiment that generates personal data. Ketone esters are more potent but more expensive and have a strong, unpleasant taste that some people cannot tolerate. No patient should feel pressured to try either — this is entirely optional, and the evidence base is too thin to justify any expectation of benefit. Stopping is always the right decision if anything worsens.

*Severity applicability:* All levels. Severe: micro-dose MCT (¼ tsp, titrate). Very severe: ketone esters if tolerated; environmental energy conservation may be primary.

*Falsifiable prediction.* ME/CFS patients with documented prefrontal FDG-PET hypometabolism who achieve blood BHB ≥ 0.5 mM will show cognitive improvement proportional to baseline hypometabolism severity.
] <spec:ketone-esters-mct-bypass>

#open-question(title: [CSF:Plasma Glucose Ratio as GLUT1 Bottleneck Biomarker in ME/CFS])[
*Origin: brainstorm.* The clinical test for GLUT1 deficiency syndrome is the CSF:plasma glucose ratio — a comparison of sugar levels between spinal fluid (obtained by lumbar puncture) and blood drawn at the same time. In healthy people, spinal fluid glucose is typically 60% or more of blood glucose. In GLUT1 deficiency, the glucose transporter at the blood-brain barrier is impaired, so less sugar enters the brain, and the ratio drops. If ME/CFS involves functional GLUT1 impairment, patients should show similarly reduced ratios. This has never been measured in ME/CFS. A single lumbar puncture study (n=30 ME/CFS, n=30 controls) with paired glucose measurement — a test that costs approximately USD 200 to add to an existing spinal tap and uses standard clinical lab equipment available in any hospital — could define a treatable ME/CFS subtype for approximately USD 50,000 to 100,000 total study cost. If 20--40% of patients show ratios below 0.50, the practical consequence is immediate: those patients would have a biologically defined subtype with a clear treatment rationale (ketogenic diet, which is the standard of care for GLUT1 deficiency), a diagnostic test that distinguishes them from other ME/CFS patients, and a rationale for insurance coverage of medical ketogenic therapy. If zero patients show abnormal ratios, the GLUT1 bottleneck hypothesis is either wrong or the transporter defect is too subtle to detect with a bulk glucose measurement — in either case, ketogenic diet trials in unselected ME/CFS would be targeting a mechanism that may not exist in any patient. This is a high-priority, low-cost, high-impact study that should be done before any clinical trial of brain-energy-targeted interventions.
] <oq:csf-plasma-glucose-ratio>

#open-question(title: [GLUT1 Deficiency Syndrome as Monogenic ME/CFS Model])[
*Origin: brainstorm.* GLUT1 deficiency syndrome (G1D, caused by mutations in the SLC2A1 gene) impairs glucose transport across the blood-brain barrier, producing epilepsy, cognitive delay, movement disorders, and ASD-like social and communication deficits — all of which improve markedly with ketogenic diet therapy (which provides alternative fuel that bypasses the broken transporter). G1D is a monogenic analogue — a single-gene disease model — to the acquired brain glucose transport failure hypothesized in ME/CFS. *Practical implications of this parallel.* (1) If adults with milder G1D variants (who have partial transporter impairment, not complete loss) report ME/CFS-like symptoms at elevated rates, G1D becomes a causal-anchor model — proof that the GLUT1 bottleneck, when present in a milder acquired form, produces exactly the ME/CFS phenotype. Finding: ask G1D patient registries whether fatigue, PEM, and orthostatic intolerance appear in their symptom surveys. (2) If common SLC2A1 gene variants that modestly reduce GLUT1 expression — not enough to cause G1D, but enough to lower the brain's energy reserve — are enriched in ME/CFS, this identifies a genetic predisposition. Testable for free in DecodeME (n > 17,000, existing genotyping — no new data collection, just analysis). A positive result here would be the first ME/CFS genetic finding with a direct, testable, and treatable biochemical mechanism — not just an association. (3) If G1D registries capture only epilepsy and movement disorders, without fatigue or PEM, the GLUT1-to-ME/CFS link is weakened — the bottleneck alone is insufficient to produce the ME/CFS phenotype, and additional factors (immune activation, autonomic dysfunction) are required.
] <oq:glut1-deficiency-mecfs-model>

#speculation(title: [Severity-Adapted Brain Energy Restoration Protocol])[
*Certainty: 0.25 (0.20→0.25: feed-into from @hyp:selective-dysfunction cert 0.55 — if selective dysfunction is correct, severity-adapted energy protocols follow logically; contingent on selective-dysfunction cert ≥ 0.50). Probability of clinically meaningful efficacy in ME/CFS: 0.04. Origin: brainstorm.* Brain energy interventions require severity-adapted protocols because a treatment that helps a moderate patient — who has some metabolic reserve — may crash a severe patient whose energy systems are already operating at their limit. *Concrete protocol stratification (hypothetical, research-stage):* Mild patients (housebound but able to perform some daily activities): ketone esters 15 g/day plus MCT oil 1 tbsp plus cognitive pacing (timed work/rest intervals, never pushing through brain fog). Goal: improve cognitive stamina. Moderate patients (mostly housebound, limited activity): reduced doses plus pre-dose MCT before any planned cognitive exertion; strict work/rest ratios; never exceed tolerated limits. Severe patients (bedbound most of the day): micro-dose MCT oil (¼ teaspoon, titrated over weeks), purely for neuroprotection — not performance enhancement. The goal is stabilisation, not improvement. Very severe patients (fully bedbound, unable to tolerate light or sound): exogenous ketones only if tolerated without side effects. The primary intervention is environmental — dark room, quiet, minimal sensory stimulation — to reduce the brain's energy demand to the absolute minimum. MCT oil may cause GI distress in this group; starting dose is 1/8 teaspoon with food. *The key principle that distinguishes this from graded exercise or graded activity therapy:* the goal is never to push beyond current tolerance. The brain energy budget is assumed to be fixed and limited; the protocol works within that budget, it does not try to expand it through repeated challenge. If the protocol causes any worsening of symptoms, it is stopped immediately — not "pushed through."

*Falsifiable prediction.* Severity-stratified 8-week protocol: (1) moderate patients --- at least 80% complete full-dose regime (15 g ketone esters + 1 tbsp MCT) with at most 1 GI adverse event requiring dose reduction, and show at least 1 SD improvement on 2/4 cognitive domains (processing speed, task-switching, working memory, sustained attention). (2) Severe patients --- at least 70% complete micro-dose regime (1/4 tsp MCT) for 8 weeks without stopping, with at least 20% within-subject stability in cognitive scores (no decline >0.5 SD). (3) Very severe --- at least 50% cannot tolerate any oral intervention (stopped within 2 weeks). Falsified if between-group tolerance proportions differ by less than 20 percentage points or if cognitive improvement in moderate group does not exceed within-subject variability.
] <spec:severity-adapted-brain-energy>

#synthesis[
*Convergent pathophysiology across ASD and ME/CFS.* The body of evidence establishes that ME/CFS independently exhibits all core biochemical features of the ASD brain energy disorder model: regional brain glucose hypometabolism on FDG-PET scans (@spec:astrocyte-brain-energy-conservation, cert 0.45), elevated ventricular lactate on MRS, astrocyte-to-neuron fuel supply dysfunction (@Xu2026Neurovascular), and an energy conservation fatigue model structurally identical to the ASD model despite independent development (@Lacourt2018InflammationEnergy). The pre-existing selective dysfunction hypothesis (@spec:astrocyte-gate, cert 0.50) and CNS energy triage framework (@spec:cns-energy-triage, cert 0.35) provide complementary models that are mutually reinforced by this cross-disease convergence. *What this means concretely.* For patients: brain fog, cognitive rigidity, and sensory overload are not psychological or behavioural — they are predictable consequences of a brain running on inadequate energy, and this framework provides biological validation of symptoms that are frequently dismissed. For clinicians: the distinction between a primary metabolic defect, a perfusion problem, and an inflammatory masking effect matters enormously for treatment selection — giving mitochondrial cofactors to a patient whose real problem is low cerebral blood flow will not work, and giving vasodilators to a patient whose real problem is an astrocyte transporter defect will not work either. The right treatment depends on which model is correct for that individual patient, and currently we cannot tell. For researchers: the spinal fluid-to-blood glucose ratio (@oq:csf-plasma-glucose-ratio) is the single most actionable experiment — a standard clinical test, never run in ME/CFS, that costs approximately USD 200 to add to an existing lumbar puncture and could define a treatable subtype within a year. The ketone fuel bypass (@spec:ketone-esters-mct-bypass, cert 0.35; @oq:ketogenic-diet-brain-energy) has strong mechanistic logic but zero controlled data in ME/CFS. The GLUT1 deficiency syndrome parallel (@oq:glut1-deficiency-mecfs-model) provides a monogenic causal-anchor model that is testable for free using existing DecodeME genotype data. The strongest constraints remain: no direct GLUT1 or astrocyte fuel shuttle measurement in ME/CFS brain tissue, and the possibility that reduced brain blood flow — documented in the majority of patients — produces the same imaging pattern without any transporter defect. The framework's primary value is in providing testable predictions that discriminate between competing models, identifying research priorities that are cheap and actionable now rather than expensive and distant, and anchoring convergent mechanistic logic across two independent disease research communities that arrived at the same conclusion without knowing about each other.
] <syn:brain-energy-asd-mecfs-model>
