#import "../../../../shared/environments.typ": *

=== Thyroid Hormone Regulation of Mitochondrial Function
<sec:thyroid-mito-regulation>

The mechanisms of mitochondrial damage described above---oxidative stress, calcium overload, impaired mitophagy---do not operate in isolation. Thyroid hormones, particularly triiodothyronine (T3), regulate mitochondrial biogenesis, respiratory chain assembly, and quality control through well-characterized pathways in general endocrinology @Singh2022bioenergetic @Liao2024thyroidMito. Whether disruption of thyroid hormone signaling contributes to mitochondrial dysfunction in ME/CFS specifically has not been directly tested. Comparable mechanistic arguments could be constructed for other hormones with broad mitochondrial regulatory roles (cortisol, insulin, IGF-1), so the existence of a mechanistic overlap is necessary but not sufficient to prioritise this axis. The case for considering thyroid hormones here rests on the documented Low T3 Syndrome in ~16% of ME/CFS patients @ruiznunez2018thyroid and the selenoprotein P autoantibody finding @Sun2023selenop (Chapter @ch:endocrine, Section @sec:thyroid), which provide ME/CFS-specific evidence---albeit from single unreplicated studies---for disrupted thyroid hormone availability.

T3 regulates mitochondrial function through two distinct pathways operating on different timescales @Singh2022bioenergetic @Liao2024thyroidMito. (Note: the relative quantitative importance of T3 versus other mitochondrial regulators---insulin signaling, AMPK, mTOR, glucocorticoids, PPAR ligands---varies by tissue and metabolic context. The description below presents the T3-specific pathways; it does not imply T3 is the dominant regulator in all settings.)

==== Nuclear/Genomic Pathway (Hours to Days)

T3 binds nuclear thyroid hormone receptors (TR$alpha$1 and TR$beta$1), which act as ligand-dependent transcription factors at thyroid response elements (TREs) in nuclear DNA. This activates a transcriptional cascade: T3 $arrow.r$ PGC-1$alpha$ induction $arrow.r$ NRF-1/GABPA (Nuclear Respiratory Factor 2, distinct from the Nrf2/NFE2L2 antioxidant pathway) coactivation $arrow.r$ TFAM (mitochondrial transcription factor A) expression $arrow.r$ mtDNA replication and transcription. The net result is increased mitochondrial mass, mtDNA copy number, and respiratory capacity over 1--several days. T3 also coordinates fission, mitophagy, and biogenesis through a pathway proposed to involve ERR$alpha$-dependent ULK1 and DRP1 expression @Singh2017thyroidERR: in this proposed model, T3-induced DRP1-mediated fission physically separates damaged mitochondrial segments, enabling their PINK1/Parkin-dependent mitophagic clearance, while PGC-1$alpha$ simultaneously drives biogenesis of replacement organelles (demonstrated in specific cell types in vitro; generalisability to skeletal muscle and neurons is assumed but not confirmed). This quality-control cycle, if operative, would ensure that the mitochondrial population remains functional---a process compromised when tissue T3 is low.

==== Direct Mitochondrial Pathway (Minutes to Hours)

The full-length TR$alpha$1 mRNA also encodes two truncated proteins that are imported directly into mitochondria @WrutniakCabello2018p43. The p43 isoform (~43 kDa) localizes to the mitochondrial matrix, binds T3, and evidence from in vitro transactivation assays suggests it functions as a T3-dependent transcription factor of the mitochondrial genome---binding putative TREs in the mitochondrial D-loop region to promote synthesis of the 13 mitochondrial-encoded OXPHOS subunits. This dual system (nuclear + mitochondrial) ensures coordinated expression of both nuclear-encoded and mtDNA-encoded respiratory chain components; loss of either pathway produces stoichiometric imbalance and assembly defects.

==== Supercomplex Assembly and Cardiolipin

T3 promotes the assembly of individual respiratory complexes (I, III, IV) into *supercomplexes* (respirasomes), which channel electrons more efficiently and limit ROS generation @Singh2022bioenergetic. Supercomplex stability depends on cardiolipin, the signature phospholipid of the inner mitochondrial membrane: T3 rapidly increases cardiolipin synthase activity, and cardiolipin acts as molecular "glue" bridging Complexes III and IV (multiple cardiolipin molecules per interface in cryo-EM structures, with variable occupancy across species). Hypothyroidism causes reduced cardiolipin content and impaired supercomplex formation---a phenotype that overlaps with the supercomplex disruption produced by WASF3 overexpression, though via distinct mechanisms (@ach:wasf3-mechanism below). T3 deficiency and WASF3 elevation could in principle disrupt supercomplexes through complementary mechanisms (reduced assembly signals vs. active disassembly). Whether these two mechanisms co-occur in individual ME/CFS patients has not been tested---no study has measured both WASF3 levels and tissue T3 in the same cohort @Liao2024thyroidMito.

==== 3,5-Diiodothyronine (T2): Rapid Mitochondrial Effects

3,5-Diiodo-L-thyronine (3,5-T2), a thyroid hormone metabolite previously considered inactive, has rapid non-genomic effects on mitochondria that are independent of protein synthesis and evident within one hour @Lombardi2015T2skeletal. In vitro evidence suggests 3,5-T2 interacts with Complex IV (cytochrome $c$ oxidase), modulating the allosteric ATP-inhibitory conformation---effectively reducing the brake on terminal electron transfer (the precise binding subunit remains to be confirmed by structural studies). 3,5-T2 also stimulates fatty acid oxidation (+80--104% increase with palmitoyl substrates) via SIRT1 activation of AMPK, which phosphorylates and inhibits ACC, reducing malonyl-CoA production and thereby relieving CPT1-mediated inhibition of mitochondrial fatty acid import. T2 reduces H#sub[2]O#sub[2] production while increasing respiration rate, suggesting it shifts mitochondria toward efficient coupled respiration. Whether T2 levels are altered in ME/CFS has not been investigated.

==== Relevance to ME/CFS: The Thyroid--Mitochondrial Convergence

#fhypothesis(title: [Low Tissue T3 as Amplifier of Mitochondrial Dysfunction in a Subset of ME/CFS Patients], falsifiability: [weakly], justification: [Falsified if (a) intramuscular T3 concentrations in ME/CFS patients with serum Low T3 are normal, or (b) T3 supplementation in Low T3 ME/CFS patients fails to improve the primary endpoint of maximal coupled respiration in muscle biopsy respirometry at 12 weeks])[
*Certainty: 0.45.* In the ~16% of ME/CFS patients with documented Low T3 Syndrome (Section @sec:thyroid in Chapter @ch:endocrine), reduced tissue T3 availability may amplify several of the mitochondrial damage mechanisms described in this section through a convergent cascade. Note that this hypothesis applies specifically to the Low T3 subgroup and does not claim to explain mitochondrial dysfunction in ME/CFS patients with normal thyroid profiles:

    + *Reduced PGC-1$alpha$ activation*: Impaired mitochondrial biogenesis---fewer new mitochondria to replace damaged ones.
    + *Reduced cardiolipin synthesis*: Destabilized respiratory supercomplexes---increased electron leak and ROS generation.
    + *Impaired mitophagy coordination (if the proposed ERR$alpha$/ULK1/DRP1 pathway operates in relevant tissues)*: Reduced fission-mitophagy-biogenesis cycle---damaged mitochondria accumulate rather than being cleared @Singh2017thyroidERR. This step depends on a pathway demonstrated in vitro but not confirmed in human skeletal muscle or neurons.
    + *Potential supercomplex disruption overlap with WASF3*: Low T3 reduces assembly signals while WASF3 actively disrupts assembled supercomplexes---whether these co-occur in individual patients has not been tested @wang2023wasf3.
    + *Reduced p43-mediated mtDNA transcription*: Insufficient production of the 13 mtDNA-encoded OXPHOS subunits, creating stoichiometric imbalance with nuclear-encoded subunits @WrutniakCabello2018p43.

A hypothesized self-reinforcing cycle could operate as follows: low tissue T3 $arrow.r$ impaired biogenesis and quality control $arrow.r$ accumulation of damaged, ROS-producing mitochondria. The proposed closing link---ROS-driven oxidative inactivation of deiodinase selenocysteine residues, further reducing T4-to-T3 conversion---is the weakest step in the cycle: while sustained oxidative stress can irreversibly oxidize selenocysteine to seleninic acid, this requires severe and sustained ROS levels beyond what has been directly demonstrated in ME/CFS tissues. *This closing link should be treated as an open question rather than an established feedback mechanism.* If it does not operate, the cycle is open (T3 deficit worsens mitochondrial function, but mitochondrial dysfunction does not necessarily worsen T3 availability through this route).

Selenoprotein P autoantibodies, documented in 9.6--15.6% of ME/CFS patients @Sun2023selenop, represent a separate mechanism that could impair deiodinase function by reducing selenium delivery (Section @sec:thyroid in Chapter @ch:endocrine). However, this is a distinct mechanistic branch (autoimmune selenium transport impairment), not a substitute for the ROS-deiodinase closing link: it does not demonstrate that mitochondrial dysfunction _causes_ worsened T3 availability, which is what a true self-reinforcing cycle requires. Without evidence for either closing link, the most conservative interpretation is a one-directional pathway: low T3 may worsen mitochondrial function, but whether mitochondrial dysfunction reciprocally worsens T3 availability remains an open question.

*Testable predictions:*

    / *(a)*: ME/CFS patients with documented Low T3 Syndrome should show lower supercomplex content (measured by blue native PAGE of muscle biopsy mitochondria) than ME/CFS patients with normal thyroid hormone profiles.
    / *(b)*: Intramuscular T3 concentrations (measured by LC-MS/MS in biopsy) should be disproportionately reduced relative to serum FT3 in patients with selenoprotein P autoantibodies.
    / *(c)*: T3 supplementation in Low T3 ME/CFS patients should increase mtDNA copy number and improve respirometric parameters (maximal coupled respiration, spare respiratory capacity) measured in PBMCs or muscle biopsy at 8--12 weeks.

*Research implication:* This hypothesis predicts that future clinical trials of mitochondrial cofactor supplementation (CoQ10, NAD#super[+] precursors, carnitine) should stratify by thyroid status, as patients in the Low T3 subgroup might respond differently. This is a testable prediction, not a clinical recommendation---no evidence currently shows that cofactor supplementation fails due to T3 deficiency, and well-tolerated supplements should not be withheld pending thyroid investigation. The alternative hypothesis---that Low T3 is a protective adaptation to energy deficiency (Section @sec:thyroid in Chapter @ch:endocrine)---would predict the opposite: that correcting T3 without addressing the underlying energy deficit could worsen outcomes by raising metabolic demand beyond supply.
] <hyp:t3-mito-amplifier>

#warning-env(title: [No Direct Measurement of Intramuscular T3 in ME/CFS])[
No study has directly measured T3 concentrations in ME/CFS skeletal muscle or other target tissues. The hypothesis that tissue-level T3 is reduced rests on indirect evidence: serum Low T3 pattern @ruiznunez2018thyroid, reduced deiodinase activity indices (SPINA-GD) @Sun2023selenop, and the general finding that serum T3 underestimates tissue deficits when deiodinase function is impaired. Direct tissue measurement using LC-MS/MS in muscle biopsy is technically feasible but has not been performed in ME/CFS.
]

