#import "../../../../../shared/environments.typ": *

#speculation(title: [The Body Stays Quiet While the Mind Screams — Emotional-Autonomic Dissociation])[
In healthy people, emotional experience and the body's physical response are normally in sync: when you feel distressed, your heart rate rises, your palms sweat, your muscles tense. In ME/CFS, this coupling can break.

Rimes et al.\ (2016, n=40 CFS, 40 controls) asked participants to suppress their emotions while watching upsetting material. Healthy controls showed the expected pattern: trying to suppress emotions produced a clear spike in skin conductance (a measure of sympathetic nervous system activity). CFS patients showed the opposite: their skin conductance stayed flat—their bodies didn't react—but they reported feeling _more_ distressed, not less @Rimes2016emotionSuppressionCFS. The subjective experience of emotion had become detached from the body's autonomic response.

A small fMRI study by Wortinger et al.\ (2017, n=10 adolescent CFS, 10 controls) found that CFS patients activate different brain circuitry during emotional tasks: the anterior cingulate and prefrontal cortex worked differently, even though behavioral performance was normal @Wortinger2017emotionConflictCFS. This suggests the brain is recruiting extra resources to compensate for degraded processing at lower levels—the mental equivalent of straining to hear someone in a noisy room.

This dissociation has a direct clinical consequence: patients report emotional distress, but clinicians see normal vital signs (blood pressure, heart rate, temperature) and may dismiss the distress as exaggerated or fabricated. The absence of visible body signs is not evidence that the distress isn't real—it is evidence that the normal body substrate of emotion has been disrupted. Van Den Houte et al.\ (2017) showed the same phenomenon from the other direction: experimentally inducing a bad mood amplified physical symptoms more in CFS and fibromyalgia patients than in controls @VanDenHoute2017negativeAffectSomatic. The amplification is real—mood genuinely affects symptoms—but it reflects a sensitised circuit, not a made-up problem.

Emotional processing abnormalities in CFS have now been found across different methods: experimental tasks (Rimes 2016), questionnaires (Brooks et al.\ 2017, n=67 CFS @Brooks2017emotionalProcessingCFS), and brain imaging (Wortinger 2017). A competing explanation focuses on stress hormones: Kang et al.\ (2026) reviewed evidence that HPA axis dysfunction in ME/CFS—cortisol dysregulation leading to hippocampal changes—could independently produce cognitive and emotional symptoms @Kang2026hpaEmotionCFS. The two pathways (body-sensing disruption and hormone disruption) are not rivals—both likely operate and probably interact.

(Certainty: 0.40. Each study is small-to-moderate, single-center, and unreplicated. The convergence across different methods provides triangulation but not independent replication. Confirmation in larger adult ME/CFS samples using combined autonomic recording, brain imaging, and emotional tasks is needed. *Falsification condition:* If the correlation between body response and self-reported emotion during emotional tasks—the coherence between what the body shows and what the person feels—is the same in CFS patients as in controls, then the dissociation is not specific to the disease and may reflect general distress rather than disrupted body-sensing.)
] <spec:ch15-emotional-autonomic-dissociation>
