#import "../../../../../shared/environments.typ": *

#achievement(title: [POTS, ME/CFS, and Long COVID Converge on Shared Neuroimmune Mechanisms])[
*Certainty: 0.70.* Blitshteyn, Doherty, and Steinman @Blitshteyn2026Neuroimmune have synthesized a convergent neuroimmune framework across POTS, ME/CFS, and Long COVID — arguing that these three conditions form a spectrum of neuroimmune disorders with shared pathophysiology. The core evidence for convergence rests on four pillars: (1) GPCR autoantibodies (adrenergic α1, β1/β2, muscarinic M2/M4) identified across all three conditions by multiple independent groups @Gunning2019GPCRPOTS @Fedorowski2017Antiadrenergic @Wallukat2021GPCRLongCOVID; (2) brainstem neuroinflammation at the dorsolateral inferior medulla as a shared CNS substrate @Blitshteyn2025Neuroinflammation @Wagoner2019MedullaInflammation; (3) vagus nerve / cholinergic anti-inflammatory pathway dysfunction as a common neuroimmune mechanism; and (4) immunomodulatory treatment overlap (IVIG, immunoadsorption, rituximab) with preliminary benefit in all three conditions.

*Certainty basis:* The GPCR autoantibody evidence is strongest in POTS (0.65–0.70 from functional validation including cell-based assays @Fedorowski2017Antiadrenergic and rabbit passive transfer @Li2019AdrenergicRabbit), moderate in Long COVID (0.60–0.70 from Wallukat 2021 bioassay evidence @Wallukat2021GPCRLongCOVID), and moderate in ME/CFS (0.50–0.60 from multiple ELISA studies @Loebel2016 @Bynke2020). The Germain 2025 null result in ME/CFS (n=172, REAP/Luminex) @Germain2025autoantibody introduces an unresolved assay-sensitivity issue. Brainstem neuroinflammation evidence remains modest (0.45–0.60). Clinical neuroimmune overlap between the three conditions is the highest-certainty pillar (0.80) based on epidemiological and clinical convergence @Moen2025NeuroimmuneLongCOVID @ElRhermoul2023AutoimmunityLCPOTS.

*Replication status:* GPCR autoantibodies in POTS replicated by three independent groups (Oklahoma, Lund, CellTrend). In ME/CFS, two independent replications (Loebel 2016, Bynke 2020) but Germain 2025 null challenges reproducibility. The three-condition convergence is a narrative synthesis, not a head-to-head comparison study.

*Limitations:* Narrative review (not systematic); limited original data; GPCR autoantibody detection not standardized across labs; whether GPCR autoantibodies are causal or epiphenomenal debated; Germain 2025 null unresolved; brainstem neuroinflammation lacks direct human histopathology.

*Convergence caveat — shared methodological vulnerability.* The convergence described above draws on multiple lines of evidence that are individually weak. However, they do not constitute strong evidence because several key pillars (GPCR autoantibody prevalence, autonomic-autoantibody correlations, treatment response signals) depend on the same detection platform (CellTrend ELISA). If the CellTrend ELISA method is wrong — if it detects non-specific binding, if GPCR epitopes are lost during plate coating, or if the conformational epitopes required for functional activity are not preserved — then the autoantibody pillar collapses, weakening the neuroimmune convergence that depends on it. Convergence of multiple weak lines of evidence that share a single methodological vulnerability does not produce strong evidence. Independent validation on orthogonal platforms (Luminex, functional bioassay, mass spectrometry) for the same cohorts is essential before the convergence claim can be considered robust.
] <ach:neuroimmune-classification>
