#import "../../../shared/environments.typ": *

== Integrated Symptom Cascade Model
<sec:ch15-integrated-cascade>

The mechanisms described in Sections 15.2–15.15 do not operate in isolation: they form a self-reinforcing symptom cascade. This section presents an integrated model showing how initial triggers (infection, immune activation, autonomic dysregulation) initiate the sickness behavior state, which then activates neurochemical symptom generators, which in turn are amplified by systems-level mechanisms, creating the chronic, treatment-resistant symptom burden of ME/CFS. The cascade model also explains phenotypic variability: different entry points and dominant pathways produce different symptom profiles.

*Layer 1: Initial Trigger.* An acute infection (viral, bacterial), immune challenge (vaccination, environmental antigen), or physiological stress (trauma, toxin exposure) activates the peripheral immune system, raising circulating cytokine levels (IL-1$beta$, IL-6, TNF-$alpha$, IFN-$gamma$).

*Layer 2: Sickness Behavior State.* Peripheral cytokines communicate with the hypothalamus via vagal and humoral routes, triggering the coordinated sickness behavior program: fatigue, anorexia, social withdrawal, hyperalgesia, sleep dysregulation (Section @sec:ch15-sickness-behavior). In healthy individuals, this state resolves within days to weeks as the infection clears and cytokines normalize. In ME/CFS, the resolution fails.

*Layer 3: Neurochemical Generators.* Persistent cytokine drive, now coupled with altered circadian rhythm (Section @sec:ch15-melatonin) and adenosine dysregulation (Section @sec:ch15-adenosine), sustains and amplifies fatigue signaling. The kynurenine pathway diverts tryptophan from serotonin synthesis (Section @sec:ch15-serotonin), exacerbating mood and cognitive symptoms. These neurochemical changes are reciprocally reinforced by circadian disruption.

*Layer 4: Microglial Activation and Neuroinflammation.* Sustained peripheral cytokine production and circulating danger signals (ATG13, metabolic byproducts) activate microglia (Section @sec:ch15-microglia). Microglial activation amplifies local cytokine production, creating a self-sustaining neuroinflammatory state independent of peripheral drivers. Mast cells (Section @sec:ch15-mast-cells) establish bidirectional amplification loops with microglia.

*Layer 5: Systems-Level Amplifiers.* Chronic neuroinflammation impairs glymphatic function (Section @sec:ch15-glymphatic), preventing waste clearance and further driving microglial activation. Elevated kynurenine metabolites (Section @sec:ch15-kynurenine) and oxidative stress (Section @sec:ch15-oxidative-stress) contribute to NMDA receptor activation, driving central sensitization (Section @sec:ch15-central-sensitization) and pain amplification. Endocannabinoid deficiency (Section @sec:ch15-endocannabinoid) removes the brake on these amplifying mechanisms.

*Layer 6: PEM Loop.* Exercise-induced metabolic stress (lactate, succinate accumulation) activates danger signal pathways (Section @sec:ch15-metabolic-danger), triggering TLR4/NF-$kappa$B and NLRP3 inflammasome activation (Section @sec:ch15-cytokine-fatigue). The resulting cytokine surge recapitulates the sickness behavior state (acute, disproportionate, sustained) — post-exertional malaise. Importantly, PEM is not deconditioning; it is the acute re-engagement of the neuroinflammatory cascade triggered by metabolic stress. This is now supported by direct muscle biopsy evidence: 60 days of strict bed rest fails to reproduce the ME/CFS muscle phenotype across multiple independent dimensions @Charlton2026MuscleBedrest (see @ach:charlton2026-bedrest-rebuttal). The neuroinflammatory cascade explains PEM's delayed onset (24–48h), its disproportionate severity relative to the exertion that triggered it, and its multi-system nature.

*Interoceptive Encoding.* Throughout this cascade, the brain's interoceptive model (Section @sec:ch15-interoception) encodes the accumulated evidence of bodily dysfunction: elevated interoceptive precision weighting, expanded pain thresholds, amplified fatigue signals. Even if peripheral pathology partially remits, the brain's model persists, perpetuating symptoms.

The cascade model predicts that treatment efficacy depends on the patient's position within the cascade and the primary dominant mechanism. A patient whose PEM is driven primarily by microglial activation may respond to LDN (anti-microglial). A patient whose primary mechanism is glymphatic failure may respond to interventions improving slow-wave sleep quality. A patient with metabolic danger dominance requires pacing to prevent exercise triggering. No single intervention targets the entire cascade; multi-mechanism approaches addressing multiple layers are theoretically more robust.

