#import "../../../../../shared/environments.typ": *

#clinical-finding(title: [Four Biologically Distinct States Collapse Under the Single Word "Fatigue"])[
The word "fatigue" spans at least four biologically distinct states with different mechanisms, different diagnostic tests, and different — sometimes opposite — treatments. Collapsing them into one symptom label drives misdiagnosis and mistreatment @Tankisi2024fatigueFatigability @Jason2010FatigueTypes. The four states:

- *Peripheral fatigue* — failure of muscles to generate force under load (ATP depletion in myocytes, accumulated lactate and hydrogen ions, impaired sarcoplasmic-reticulum calcium release). Measurable with dynamometry; the muscle literally cannot contract as hard. Resolves with rest and glycogen repletion; mechanism local, recovery predictable.
- *Fatigability (post-exertional malaise)* — distinct by *time*: exertion on day 1, collapse on day 2–3, with a characteristic delay and recovery measured in days to weeks, not hours @Jason2015definingPEM. A systemic metabolic crash, not muscle failure under load. Two-day CPET shows reduced ventilatory threshold and peak VO₂ on day 2 — objectively worse after exertion @Snell2013CPET @VanNess2010PEM.
- *Sleepiness (somnolence)* — the propensity to fall asleep, driven by adenosine accumulation and circadian pressure; resolves with sleep and responds to stimulants. Distinguishable by observation: put the patient in a dark quiet room and they fall asleep within minutes — whereas an ME/CFS patient with fatigability is often "tired but wired" and cannot.
- *Amotivation (anergia)* — absence of drive to initiate action; the body can perform but the brain does not issue the command. Primarily dopaminergic (deficit in reward-prediction circuitry that assigns value to future actions). The patient with amotivation can often perform when externally compelled — the firefighter who feels no motivation but still runs into the building — whereas the patient with peripheral fatigue or fatigability cannot @Faro2024connectivity.

The four states have different treatments, and applying the treatment for one to a patient suffering from another ranges from useless to dangerous. Exercise is therapeutic for depression-driven amotivation, but for ME/CFS-type fatigability it causes measurable physiological deterioration rather than improvement @Snell2013CPET @Wilshire2018. Sleep resolves sleepiness but not ME/CFS fatigability (unrefreshing sleep persists regardless of duration) nor amotivation. The clinical discriminator is a small set of questions about timing, delay, exercise response, and whether the patient can act when externally compelled.

(Certainty: 0.55, synthesis of established constructs in exercise physiology, sleep medicine, and neuropsychiatry; ME/CFS-relevant framework, not ME/CFS-specific cohort validation of the four-way split as a whole.)

*Limitations:* The four-way taxonomy is a clinical-organizing framework drawn from distinct literatures (peripheral-muscle physiology, PEM/case-definition work, sleep medicine, dopaminergic neuropsychiatry); no single study has validated the four-state split as a diagnostic instrument in an ME/CFS cohort. The boundaries between states can co-occur in one patient (an ME/CFS patient typically has fatigability primary, plus secondary peripheral fatigue from deconditioning, plus disrupted sleep, plus possible amotivation from chronic-illness depression) — the clinically operative question is which state is *primary*, because that determines whether exercise helps or harms.

*Severity applicability:* unknown — the framework is not severity-stratified; it applies in principle across mild–very-severe patients, but for severe/very-severe patients the distinction between fatigability and amotivation is clinically critical because misapplied exercise is most harmful there.

*Consequence:* This is why "I'm tired" in a clinic must be decomposed before any treatment is chosen: the same words can mean a deconditioned muscle (helped by graded exercise), an ME/CFS energy crash (harmed by it), sleep deprivation (helped by sleep and stimulants), or a motivational collapse (helped by activity and possibly dopaminergic agents). A clinician who does not ask about timing and delay can prescribe exercise to the very patient for whom it causes measurable deterioration.
] <clf:four-states-of-fatigue>
