#import "../../../../shared/environments.typ": *

==== Primary Cascade: B-cell production → receptor-level effects

*Cascade:*
- Triggering infection → B cell activation (molecular mimicry or bystander) → cross-reactive GPCR AAb
- (a) β2-AR desensitization → vasodilation failure, impaired lipolysis, mast cell brake removal → OI, fatigue, PEM
- (b) M2/M4 mAChR blockade → impaired vagal signaling → reduced HRV, GI dysmotility, chronotropic incompetence
- (c) α1-AR agonism → vasoconstriction + counter-regulatory fatigue → POTS, hypertension
- (d) Area postrema access → brainstem microglial activation → NTS baroreflex reset → sympathetic overactivation

*Step I1:* B-cell / plasma cell autoantibody production (source-level)
- *Intercept:* Rituximab (anti-CD20 monoclonal antibody; B-cell depletion, spares long-lived plasma cells) — depletes B cells but spares long-lived CD20− plasma cells; Daratumumab (anti-CD38 monoclonal antibody; plasma cell depletion including long-lived) — depletes plasma cells (including long-lived); Immunoadsorption (IA; extracorporeal IgG removal via protein A columns) — physically removes circulating IgG (protein A columns); BC007 (DNA aptamer; GPCR autoantibody neutralization) — aptamer neutralizes specific GPCR AAbs (β1-AR, β2-AR, M2, α1-AR, AT1R, ETA).
- *Probe logic — distinguishing AAb source:*
  - *Rituximab response:* AAb produced by dividing B cells (plasmablasts). If response is transient (weeks → relapse at B-cell repopulation) → confirmed B-cell source. If sustained remission → B-cell clone was the sole AAb source and did not differentiate into long-lived plasma cells before depletion.
  - *Rituximab null but Daratumumab positive:* AAb from long-lived CD20− plasma cells — the cells that rituximab spares. The AAb source is a non-dividing plasma cell pool established during initial infection — consistent with chronic antigen-driven autoimmunity.
  - *Rituximab null AND Daratumumab null but IA/BC007 positive:* AAbs are pathogenic but their source resists depletion — sanctuary site (bone marrow niche, lymph node germinal centre) or ongoing regeneration from memory B cells faster than depletion.
  - *IA/BC007 positive, rituximab positive:* The source AND the clearance mechanism are accessible. Remove the source (rituximab) AND clear existing AAbs (IA) → maximum therapeutic effect.
- *Probe logic — distinguishing AAb subtype:*
  - *BC007 works where IA fails:* The relevant AAbs are IgG3 subclass (not removed by protein A columns) or IgA (protein A has low IgA affinity). BC007's aptamer binding is subclass-independent.
  - *IA works where BC007 fails:* The AAb target is not among BC007's aptamer panel (β1-AR, β2-AR, M2, α1-AR, AT1R, ETA) — the pathogenic AAb targets a different GPCR (M4 mAChR, angiotensin-1 receptor, endothelin receptor, or a non-GPCR target). IA removes broadly by immunoglobulin class; BC007 is target-specific.
  - *Both IA and BC007 null:* Either (a) GPCR AAbs are absent (confirm by pre-treatment AAb panel), (b) GPCR AAbs are present but not rate-limiting — downstream tissue damage is irreversible (fibrosis, neuronal loss, epigenetic consolidation), or (c) the pathogenic AAbs are IgM and not removed by IA protein A OR not neutralized by BC007's DNA aptamers.
- *If none of the above works:* GPCR autoantibodies are either absent, non-pathogenic, or not rate-limiting. See Germain 2025 @Germain2025autoantibody for assay discordance. A null across all four probes effectively excludes IgG GPCR AAb as the dominant mechanism.

*Step I2:* β2-AR desensitization/internalization (receptor-level — vascular, metabolic, mast cell)
- *Three downstream consequences of β2-AR dysfunction:*
  - *(a) Vasodilation failure:* β2-AR mediates vasodilation in skeletal muscle during exercise — essential for perfusion during activity. β2-AR AAb-induced desensitization → impaired exercise hyperemia → tissue hypoxia during exertion → lactate accumulation → PEM. Probe: Midodrine (α1 agonist, bypasses β2-AR vasodilation) should improve exercise tolerance if β2-AR vasculature is rate-limiting. If midodrine improves standing but NOT exercise tolerance → β2-AR-dependent perfusion during exertion is the specific defect.
  - *(b) Impaired lipolysis:* β2-AR mediates fatty acid mobilization from adipose tissue — the primary energy substrate during prolonged activity and fasting. β2-AR blockade → reduced free fatty acid availability → increased dependence on glucose → hypoglycemia risk + reduced ATP yield per gram substrate. Probe: MCT oil (medium-chain triglycerides, bypass β2-AR-dependent lipolysis) should improve energy if β2-AR lipolysis impairment is rate-limiting. If MCT oil improves but beta-blockers worsen fatigue → β2-AR metabolic function confirmed.
  - *(c) Mast cell brake removal:* β2-AR on mast cells inhibits degranulation. β2-AR AAb desensitization removes this brake → mast cells are constitutively degranulation-prone → MCAS phenotype. Probe: Ketotifen (mast cell stabilizer) should work disproportionately well — mast cells are β2-AR brake-deficient. If ketotifen dramatically improves symptoms → β2-AR mast cell brake removal is dominant. If ketotifen produces only modest benefit → mast cells are active but not β2-AR-dependent.
- *Combined β2-AR diagnostic:* Positive midodrine (vascular) + MCT oil (metabolic) + ketotifen (mast cell) → all three β2-AR functions are impaired. This pattern confirms β2-AR AAb pathology across all three downstream systems and strongly supports IA/BC007.

*Step I3:* M2/M4 mAChR blockade (vagal-cholinergic dysfunction)
- *M2 mAChR on SA node:* M2 receptors mediate vagal slowing of HR. M2 AAb blockade → impaired vagal HR control → reduced HRV, chronotropic incompetence, resting tachycardia. Probe: Pyridostigmine (enhances ACh at synapse) should increase HRV if M2 receptors are partially functional. If pyridostigmine does NOT improve HRV → M2 receptors are fully blocked or absent. If pyridostigmine improves HRV in some conditions but not others → M2 blockade is state-dependent (AAb binding affinity varies with cardiac workload or autonomic tone).
- *M2/M4 mAChR on gut smooth muscle and enteric neurons:* M2/M4 mediate vagal regulation of GI motility. Blockade → gastroparesis, slow transit, SIBO risk. Probe: Domperidone (D2 antagonist, prokinetic) bypasses M2/M4 entirely. If domperidone works where pyridostigmine fails for GI symptoms → the GI dysmotility is from mAChR blockade, not from enteric denervation. If pyridostigmine works for GI → mAChR blockade is partial — AChE inhibition increases ACh concentration enough to overcome competitive AAb blockade.
- *M4 mAChR in CNS (striatum — the input nucleus of the basal ganglia, caudate + putamen — and cortex):* M4 receptors modulate dopamine and glutamate signalling. M4 AAb → impaired DA/glutamate balance → cognitive dysfunction, anhedonia (inability to feel pleasure or anticipate reward). Probe: Aripiprazole should partially compensate (D2/D3 agonism downstream of M4). If aripiprazole improves cognition but pyridostigmine does NOT → the cognitive lesion is at CNS mAChR, not peripheral cholinergic. This pattern distinguishes central from peripheral cholinergic AAbs.

*Step I4:* NTS baroreflex reset (brainstem consequence of area postrema access)
- *Mechanism:* The area postrema lacks a blood-brain barrier. GPCR AAbs in circulation access circumventricular organs → bind to β2-AR and M2/M4 on NTS neurons → alter baroreflex set-point. NTS is the primary baroreflex integration centre — resetting it shifts the entire autonomic control system.
- *Consequences:* (a) Higher HR set-point at any given BP → resting tachycardia. (b) Exaggerated sympathetic response to standing → hyperadrenergic POTS component. (c) Impaired baroreflex gain → BP and HR become uncoupled → labile BP, HR variability independent of position.
- *Probe logic:*
  - *Ivabradine (If current blocker):* Reduces HR at SA node without affecting baroreflex transduction. If ivabradine normalizes HR → the tachycardia is from baroreflex reset driving excessive sympathetic tone, NOT from intrinsic SA node dysfunction. If ivabradine produces bradycardia at subtherapeutic dose → SA node intrinsic dysfunction coexists (Pattern 4, @sec:side-effects-diagnostic).
  - *Clonidine (α2 agonist):* Suppresses central sympathetic outflow at brainstem level. If clonidine normalizes BP and HR → the sympathetic overactivation is from brainstem-level drive, not from peripheral vascular hypersensitivity. If clonidine crashes BP → the sympathetic system is maintaining BP (sympathetically dependent, Pattern 4) — midodrine must precede clonidine for safety.
  - *Pyridostigmine + midodrine combination:* If combined, they should improve orthostatic tolerance by addressing both arms: pyridostigmine enhances vagal output (braking the baroreflex-driven sympathetic surge), midodrine compensates for the vasodilatory deficit. If the combination produces synergy (@sec:drug-drug-interactions) → vagal and sympathetic arms are both impaired and both rate-limiting, consistent with NTS baroreflex reset affecting both branches.

*Step I5:* Cholinergic Anti-Inflammatory Pathway (CAP) blockade
- *Mechanism:* The vagal efferent → splenic nerve → splenic T cells release ACh → α7 nicotinic AChR on macrophages → suppression of TNF-α, IL-1β, HMGB1 production. This is the body's endogenous anti-inflammatory reflex. β2-AR AAb on splenic T cells can block the cholinergic signal transduction downstream of the vagus (@spec:cap-autoantibody-blockade).
- *Consequence of CAP blockade:* Systemic inflammation is disinhibited because the vagal brake on cytokine production is removed. LDN (TLR4 antagonist on macrophages) may partially compensate by blocking cytokine production at the receiving end, but the brake itself is missing.
- *Probe logic:*
  - *taVNS (transcutaneous auricular vagus nerve stimulation):* Activates vagal afferents → vagal efferent reflex → splenic ACh release. If taVNS works → the vagal afferent-to-efferent arc is intact; CAP is functional; the lesion is upstream of the vagus (enteric, hypothalamic, systemic). If taVNS does NOT work → CAP efferent arm is blocked.
  - *taVNS + LDN:* If taVNS alone fails, add LDN (reduce neuroinflammation at NTS, restore vagal afferent transmission). If taVNS now works → the CAP afferent arm was suppressed by neuroinflammation; CAP efferent is intact. If taVNS still fails → CAP blockade is at the efferent arm (splenic β2-AR AAb).
  - *taVNS + ketotifen:* If mast cell stabilization restores taVNS response → mast-cell-driven neuroinflammation at NTS suppressed vagal afferent transmission. Mast cells are upstream of CAP.
  - *taVNS + IA:* The definitive probe. If taVNS fails before IA but works after IA → CAP efferent blockade was GPCR-AAb-mediated. If taVNS still fails after IA → CAP efferent blockade is from non-AAb mechanism (splenic nerve structural damage, α7nAChR downregulation on macrophages from chronic inflammation).
  - *Nicotine patch (transdermal, α7nAChR agonist):* Bypasses the entire vagal-splenic arc — directly stimulates the α7 receptor on macrophages. If nicotine reduces inflammatory symptoms → the CAP efferent arm is intact at the receptor level; the blockade is upstream of α7 (splenic nerve or T-cell ACh release). If nicotine has no effect → α7nAChR on macrophages are desensitized from chronic inflammation, or the macrophages are already maximally suppressed — CAP blockade is not the rate-limiting factor.

*Consequence:* The GPCR AAb cascade has five pharmacologically distinguishable levels: source (rituximab vs. daratumumab vs. IA/BC007), receptor subtype (β2-AR vascular vs. metabolic vs. mast cell), receptor class (β2-AR vs. M2/M4 vs. α1-AR), anatomical access (peripheral vs. CNS/brainstem via area postrema), and functional pathway (CAP blockade at afferent vs. efferent arm). The pattern of responses across these five levels localizes which GPCR AAb subtype is dominant, whether the AAb is peripherally or centrally active, and whether source depletion or neutralization is the treatment strategy. No single drug test isolates GPCR AAb pathology — the diagnostic pattern across 5+ probes converging on AAb-mediated mechanisms is the diagnostic.
*Origin:* mechanistic-pathway-tracing.
