#import "../../../../shared/environments.typ": *

=== Documented ME/CFS Findings and Failure Modes


The Krebs cycle generates NADH and FADH#sub[2] for the ETC via eight sequential enzymatic steps. Naviaux et al.\ found decreased TCA intermediates (citrate, isocitrate, malate, fumarate) in the ME/CFS metabolome, indicating globally reduced TCA flux . However, the specific enzymatic bottleneck(s) have not been identified.

*Aconitase (step 2: citrate → isocitrate).* Aconitase contains a [4Fe--4S] iron-sulfur cluster that is exquisitely sensitive to superoxide: a single molecule of superoxide inactivates the cluster and halts the enzyme. With Shankar et al.\ confirming elevated ROS and decreased MnSOD in ME/CFS lymphocytes , aconitase inactivation is a mechanistically predicted consequence. Yamano et al.\ ($n = 67$ CFS, 66 controls) found citrate, isocitrate, and malate significantly reduced in CFS plasma, with the pyruvate/isocitrate ratio elevated, and explicitly proposed aconitase inactivation via chronic oxidative stress as the explanation . Ciregia et al.\ found aconitase protein (ACO2) _upregulated_ 1.9-fold ($p = 0.02$) in a CFS cohort ($n = 45 + 45$) via proteomics @Ciregia2016proteomics — paradoxically, this is consistent with compensatory overexpression of an enzyme that is being oxidatively destroyed: cells produce more aconitase to compensate for functional inactivation by ROS. Despite this convergent indirect evidence, aconitase enzymatic activity has never been directly measured in ME/CFS tissue or cells (G16).

*Alpha-ketoglutarate dehydrogenase complex (KGDHC, step 4).* KGDHC has identical cofactor requirements to PDC (thiamine, lipoic acid, riboflavin/FAD, NAD#super[+]) and shares the same E2/E3 architecture, making it vulnerable to the same failure modes. KGDHC is exquisitely sensitive to oxidative stress: Tretter & Adam-Vizi demonstrated 40--50% inhibition at 0.1--0.5 mM H#sub[2]O#sub[2], irreversible HNE modification of E2 lipoic acid residues, peroxynitrite-mediated E1/E2 tyrosine nitration, and a positive feedback loop where elevated NADH/NAD#super[+] drives E3 to generate additional ROS @TretterAdamVizi2005 — every one of these inactivating conditions is independently documented in ME/CFS. A critically under-exploited connection: Fluge et al.\ documented SIRT4 upregulation in ME/CFS PBMCs  but tested only PDC consequences. SIRT4 is a mitochondrial lipoamidase that also acts on the E2 subunit of KGDHC — its upregulation would impair KGDHC in parallel with PDC.

Indirect metabolomic evidence supports a functional KGDHC block. Che et al.\ ($n = 106$ ME/CFS, 91 controls) found both $α$-ketoglutarate and succinate elevated in ME/CFS plasma @Che2022peroxisomal — substrate accumulation upstream and product accumulation downstream of KGDHC, consistent with impaired flux through the step. More strikingly, Germain et al.\ found that $α$-ketoglutarate was the second most significant metabolite distinguishing ME/CFS from controls after exercise: controls showed an $α$-KG increase while ME/CFS patients showed a _decrease_ @Germain2022exercise — an inverse trajectory consistent with selective KGDHC inhibition under metabolic stress, when NADH/NAD#super[+] rises and oxidative burden increases. Despite this convergent indirect evidence, KGDHC activity has never been directly measured in ME/CFS tissue or cells (G17).

*Succinate dehydrogenase (Complex II, step 6).* Succinate dehydrogenase is the only enzyme that participates in both the TCA cycle and the ETC. It contains iron-sulfur clusters and is the entry point for FADH#sub[2] electrons into the ubiquinone pool. It is therefore simultaneously vulnerable to ROS (via iron-sulfur cluster damage) and to CoQ10 deficiency (via impaired electron acceptance).

*Iron-sulfur cluster assembly as a systemic bottleneck.* Aconitase, KGDHC, Complex I (which contains eight [Fe--S] clusters), Complex II, and ETF-QO all depend on iron-sulfur clusters assembled by the ISCU machinery. ISCU mutations cause exercise intolerance, myopathy, and lactic acidosis — a syndrome with significant clinical overlap with ME/CFS . ISCU function has not been studied in ME/CFS. MnSOD decrease (Shankar 2025) would accelerate superoxide-mediated destruction of all iron-sulfur proteins simultaneously, creating a multi-enzyme failure pattern that could amplify the effects of any primary Complex I dysfunction.


