#import "../../../../shared/environments.typ": *

#speculation(title: [Afferent Noise and Precision Hysteresis as Formal Model Extensions for PEM])[
The predictive coding models of interoception (Seth 2011 @Seth2011interoceptivePresence, Greenhouse-Tucknott et al.\ 2022 @GreenhouseTucknott2022predictiveCodingFatigue) can be extended with two parameters that formalise the ME/CFS interoceptive dysfunction in a mathematically testable way.

*Afferent noise parameter ($sigma_upright("noise")$):* Current ODE models lack a parameter for afferent signal corruption. Adding a time-varying $sigma_upright("noise")(t)$ that scales with cytokine levels (IL-6, TNF-$alpha$), HRV complexity, and vagal afferent firing irregularity would predict that increasing $sigma_upright("noise")$ reduces interoceptive accuracy while the brain compensates by increasing interoceptive precision-weighting. When $sigma_upright("noise")$ exceeds a critical threshold, the model predicts bistable solutions (two attractors) — a "locked-in" state corresponding to all-or-nothing PEM.

*Precision hysteresis ($tau_upright("prec")$):* The time constant over which the brain's interoceptive precision-weighting decays back to baseline after a perturbation. ME/CFS is predicted to have $tau_upright("prec")$ > 72 hours (precision takes > 3 days to downregulate after a PEM-triggering event), while healthy controls have $tau_upright("prec")$ < 1 hour. This explains why PEM recovery takes days, not hours, and why the brain remains "stuck" in a high-precision interoceptive state even as peripheral inflammation resolves — consistent with the inflammation-interoception pathway (Section @sec:ch15-inflammation-interoception) and the allostatic-interoceptive system mapping @ZhangWager2025AllostaticInteroceptive.

These two parameters define a 2D phase space: $sigma_upright("noise")$ (afferent noise, x-axis) × $pi_upright("prior")$ (prior precision, y-axis). Low noise + moderate precision → healthy graded response. High noise + low precision → anxious monitoring. High noise + high precision → ME/CFS-like (low accuracy, high sensibility, low metacognitive awareness). Very high noise + very high precision → "locked-in" PEM state. (Origin: brainstorm)

(Certainty: 0.40. (0.35→0.40: reinforced by anatomical constraint from Zhang/Wager 2025 7T allostatic-interoceptive system map, cert 0.80). Mathematical extensions are theoretically coherent with the Seth/Greenhouse-Tucknott framework but entirely untested as computational models of ME/CFS. *Falsification condition:* If the model with $sigma_upright("noise")$ > 0.5 does not produce bistable attractor solutions, or if estimated interoceptive precision time constants do not distinguish ME/CFS from healthy controls on EMA data, the parameterisation is not supported. *Escape hatch:* The framework's theoretical value is in generating testable predictions, not in current confirmatory status — the next step is parameter estimation from empirical data.)
] <spec:ch15-afferent-noise-precision-hysteresis>
