#import "../../../../shared/environments.typ": *

==== Step R2: Impaired vagal afferent signaling → reduced vagal efferent tone (afferent/efferent transmission)

*Probe:* Pyridostigmine (AChE inhibitor, 30--60 mg) — enhances vagal efferent transmission by increasing synaptic ACh at M2/M3 receptors on target organs; taVNS (transcutaneous auricular vagus nerve stimulation) — electrically stimulates vagal afferents → reflex vagal efferent activation; Nicotine patch (transdermal, α7nAChR agonist) — directly stimulates the CAP efferent receptor on splenic macrophages, bypassing the entire vagal arc.

*Three-level lesion mapping:*

- *If pyridostigmine works AND taVNS works:* The vagal pathway is intact across its full arc — afferent (taVNS activates it), efferent (pyridostigmine enhances it), and postsynaptic (M2/M3 receptors respond). The lesion is upstream of the vagus: enteric level (gut dysbiosis, EC cell dysfunction) or central level (insufficient NTS/DMV activation from higher brain centres). Butyrate/5-HTP should work (enteric-level probe).
- *If taVNS works but pyridostigmine does NOT:* The vagal afferent→efferent reflex arc is intact (taVNS activates it), but the efferent arm has reduced ACh release capacity — the synapse is releasing less ACh per action potential, and AChE inhibition cannot compensate because there is insufficient ACh to potentiate. This pattern implicates: (a) reduced vesicular ACh stores at vagal efferent terminals (impaired choline acetyltransferase activity or choline deficiency), or (b) reduced number of vagal efferent fibers (neuropathy). CDP-choline (citicoline, 500--1000 mg) — choline donor for ACh synthesis — should be trialed. If CDP-choline restores pyridostigmine response → the ACh synthesis deficit is confirmed.
- *If pyridostigmine works but taVNS does NOT:* The vagal efferent arm is functional (pyridostigmine enhances it), but the afferent arm is blocked or unresponsive to electrical stimulation. Either: (a) the vagal afferent fibers are damaged — peripheral neuropathy affecting the auricular branch of the vagus (taVNS electrode site), (b) central processing of vagal afferent signals at NTS is impaired (neuroinflammation, GPCR AAb at NTS), or (c) the electrical stimulation parameters are inadequate (frequency, intensity, electrode placement). NTS neuroinflammation is the most likely in ME/CFS — try LDN or minocycline to reduce NTS inflammation, then retry taVNS.
- *If neither pyridostigmine nor taVNS works:* The vagal efferent pathway is non-functional at or downstream of the DMV motor neurons. Three possibilities: (a) severe DMV damage — brainstem neuroinflammation has damaged the vagal motor neurons themselves (not just suppressed, but lesioned); (b) ganglionic AChR autoantibodies — nicotinic AChR at autonomic ganglia are blocked, preventing vagal preganglionic→postganglionic transmission; or (c) vagal nerve structural damage — cervical vagus nerve compression, surgical damage, or demyelination.
- *Ganglionic AChR AAb probe:* If pyridostigmine null AND taVNS null → test for ganglionic (α3-β4) nicotinic AChR autoantibodies (Mayo Clinic panel). If positive → autoimmune autonomic ganglionopathy. Treatment is immunomodulation (IVIG, rituximab, plasma exchange), not cholinergic enhancement. The pharmocodiagnostic: null response to both pyridostigmine and taVNS + positive ganglionic AChR AAb = the vagal lesion is at the ganglion, not at the nerve or brainstem.

*If nicotine patch works (reduces inflammatory symptoms) where pyridostigmine and taVNS both fail:* The CAP efferent receptor (α7nAChR on macrophages) is intact and responsive — direct stimulation bypasses the entire vagal arc. The lesion is in vagal→splenic transmission (splenic nerve, T-cell ACh release) but the end organ (macrophage) can still respond. This pattern is critical: it means CAP CAN be restored — the macrophage is waiting for the signal that never arrives. The treatment target is the vagal-splenic pathway, not the macrophage.

*Consequence:* Butyrate + 5-HTP at the enteric level, taVNS at the afferent level, and pyridostigmine + CDP-choline at the efferent level distinguish three vagal lesion levels: enteric (butyrate/5-HTP-responsive), central afferent (taVNS-responsive after NTS anti-inflammatory), and ganglionic (pyridostigmine-responsive if synapses intact; neither pyridostigmine nor taVNS responsive if AChR AAb blocks). Nicotine patch probes the CAP endpoint (macrophage α7nAChR). This four-level mapping is one of the cleanest diagnostic sequences in the chapter — each probe tests a specific anatomical segment of the vagal pathway, and the pattern of responses localizes the lesion along the gut→vagus→brainstem→spleen→macrophage axis.
*Origin:* mechanistic-pathway-tracing.


