#import "../../../shared/environments.typ": *

== Sickness Behavior as Overarching Integrative Framework
<sec:ch15-sickness-behavior>

Sickness behavior—the coordinated constellation of fatigue, social withdrawal, anhedonia, cognitive slowing, hyperalgesia, and appetite suppression induced by immune activation—provides an overarching framework for understanding ME/CFS symptomatology. This section argues that many core ME/CFS symptoms represent a _chronic, dysregulated sickness behavior state_ mediated by cytokines, prostaglandins, and vagal afferents acting on hypothalamic and limbic circuits. The adaptive logic of acute sickness behavior (conserving energy for immune defense) becomes maladaptive when chronically engaged without resolution.

=== Cytokine-to-Brain Signaling Routes

Peripheral cytokines communicate with the brain through three complementary routes @Dantzer2000neural @McCusker2013. The _humoral pathway_ operates via circumventricular organs—notably the organum vasculosum of the lamina terminalis (OVLT) and the area postrema—where an incomplete blood-brain barrier permits direct cytokine diffusion into adjacent hypothalamic tissue. A _saturable transport pathway_ operates through carrier-mediated influx systems at the BBB endothelium for IL-1$beta$, IL-6, and TNF-$alpha$ @McCusker2013. The _neural pathway_ exploits vagal afferents: cytokines at peripheral infection sites activate cytokine receptors on paraganglia of the vagus nerve, transmitting immune signals to the nucleus tractus solitarius and thence to hypothalamic circuits within minutes @Dantzer2000neural @Huerta2025vagal.

At the blood-brain barrier endothelium, circulating cytokines trigger prostaglandin E#sub[2] (PGE#sub[2]) synthesis, which diffuses into the hypothalamic parenchyma to activate EP3 and EP4 receptors, suppressing wake-active orexin neurons and promoting sleep-pressure circuits @Matsumura2004endothelial @Marty2008NTS.

=== Hypothalamic Integration and the Sickness Behavior Program

#include "subsec-02-hypothalamic-integration-and-the-sicknes/hypotheses/hyp-sickness-behavior-physiological-basis.typ"

=== Persistent Sickness Behavior in ME/CFS

#include "subsec-03-persistent-sickness-behavior-in-me-cfs/hypotheses/hyp-persistent-sickness-behavior-in-me-cfs.typ"

=== Dedicated Sickness and Torpor Neural Circuits

#include "subsec-04-dedicated-sickness-torpor-neural-circuits/hypotheses/hyp-dedicated-sickness-torpor-neural-circuits.typ"

==== The EP3R "Stuck Switch" and Circuit-Leveraged Mechanisms

#include "subsec-04-dedicated-sickness-torpor-neural-circuits/speculations/spec-ep3r-stuck-switch.typ"

#include "subsec-04-dedicated-sickness-torpor-neural-circuits/speculations/spec-area-postrema-gpcr-glp1-gate.typ"

#include "subsec-04-dedicated-sickness-torpor-neural-circuits/speculations/spec-hibernation-arousal-resource.typ"

==== Constraints on the Torpor/Sickness-Circuit Model

#include "subsec-04-dedicated-sickness-torpor-neural-circuits/limitations/lim-torpor-circuits-constraints.typ"

=== Orexin/Hypocretin Suppression as a Central Mediator of ME/CFS Fatigue and Sleep Dysfunction
<sec:ch15-orexin>

The orexin (hypocretin) system provides a mechanistic link between the cytokine-driven sickness behavior described above and several cardinal ME/CFS symptoms: fatigue, unrefreshing sleep, autonomic instability, and the "tired but wired" paradox. Orexin-A and orexin-B are hypothalamic neuropeptides produced by a small population (~70,000 in humans) of neurons in the lateral and posterior hypothalamus. These neurons project widely to cortical, brainstem, and spinal targets and regulate sleep-wake transitions, arousal, autonomic function, and energy homeostasis @Sakurai1998orexin.

*Evidence for orexin suppression in ME/CFS.* López-Amador (2025) conducted an integrative review of 27 studies examining the orexin system in ME/CFS and found consistent evidence of reduced orexin-A levels, with variable orexin-B responses that may serve as a subtyping biomarker @LopezAmador2025orexin. The review identified hypothalamic orexinergic dysfunction as a central pathophysiological feature of ME/CFS, supported by concurrent hypocortisolism and autonomic dysregulation. CSF orexin-A levels in ME/CFS appear to fall in an intermediate range ($tilde$250 $plus.minus$ 30 pg/mL) --- below healthy controls but above the $<$110 pg/mL diagnostic threshold for narcolepsy type 1 @LopezAmador2025orexin @Rauf2025narcolepsyOrexin.

*Mechanism: cytokine-induced orexin suppression.* Animal studies have established a precise circuit through which inflammation suppresses orexin neurons. Grossberg et al.\ (2011) demonstrated that LPS-induced inflammation suppresses perifornical hypothalamic orexin neuron activity, reduces CSF orexin-A, and blocks dark-phase orexin activation @Grossberg2011orexinLethargy. Central orexin-A replacement fully reversed inflammation-induced lethargy, establishing causal direction: orexin suppression _drives_ fatigue rather than merely accompanying it. Importantly, orexin neurons themselves lack direct cytokine receptors; suppression is mediated by lateral hypothalamic neurotensin interneurons rather than the PGE#sub[2]/melanocortin pathways @Grossberg2011orexinLethargy. Gaykema and Goehler (2009) confirmed this using Fos immunohistochemistry: LPS reduced Fos expression in lateral orexin neurons during exploration (47% $arrow.r$ 25%) and dark-phase activity (42% $arrow.r$ 9%), with parallel suppression of histaminergic tuberomammillary neurons --- suggesting co-shutdown of the orexin--histamine arousal axis @Gaykema2009orexinSickness. Weymann et al.\ (2014) extended these findings to chemotherapy-induced fatigue, showing the same cytokine $arrow.r$ hypothalamic inflammation $arrow.r$ orexin suppression $arrow.r$ locomotor fatigue pathway, again reversible by central orexin-A rescue @Weymann2014orexinChemoFatigue.

#include "subsec-04-orexin-hypocretin-suppression-as-a-centr/hypotheses/hyp-chronic-orexin-suppression-as-a-central-.typ"

#include "subsec-04-orexin-hypocretin-suppression-as-a-centr/speculations/spec-orexin-pka-tau-phosphorylation-a-product.typ"

#include "subsec-04-orexin-hypocretin-suppression-as-a-centr/speculations/spec-daridorexant-beta-amyloid-hypothetical.typ"

#include "subsec-04-orexin-hypocretin-suppression-as-a-centr/speculations/syn-dora-neuroprotection-two-arm-convergence.typ"

==== Pharmacological Convergences on the cAMP/PKA Tau Phosphorylation Axis

*Certainty: 0.15--0.25 across agents.* The Parhizkar et al.\ @Parhizkar2025LemborexantTau demonstration that DORAs reduce tau phosphorylation via cAMP/PKA suggests that other drug classes acting on the cAMP/PKA pathway — or on parallel tau kinases — may share this neuroprotective mechanism. None of the agents below have been tested for tau effects in ME/CFS; all claims are cross-disease pharmacological extrapolation.

*DORA class comparison.* All dual orexin receptor antagonists should share the PKA-mediated tau phosphorylation reduction, but site-specificity may differ. Lucey et al.\ (2023) showed suvorexant 20 mg reduced CSF p-tau181/T181 by ~10--15% in humans but did _not_ affect phosphorylation at S202 or T217 @Lucey2023SuvorexantTau. Parhizkar et al.\ demonstrated lemborexant reduces phosphorylation at Ser202, Ser409, and Thr205 in mice @Parhizkar2025LemborexantTau. Whether this represents DORA-specific pharmacology (lemborexant blocking OX1R and OX2R with different kinetics than suvorexant), species differences (mouse vs human), or chronic-vs-acute dosing effects is unresolved. Daridorexant — the third approved DORA, already discussed for ME/CFS sleep (Chapter @ch:action-mild-moderate) — has not been tested for tau phosphorylation effects. No published study has directly compared tau phosphorylation profiles across DORAs.

*Propranolol via β-adrenergic→cAMP→PKA.* β-adrenergic receptors signal through Gs → adenylyl cyclase → cAMP → PKA — the same intracellular cascade downstream of orexin receptors. Non-selective β-blockers such as propranolol may therefore partially dampen PKA activity through a receptor population (β-adrenergic) that is mechanistically convergent with orexin signalling at the level of cAMP production. This creates a dual-benefit rationale already partially present in the paper: low-dose bedtime propranolol is discussed for autonomic coupling restoration (Section @sec:ch15-cross-modal-decoupling); the PKA dampening provides an independent — but entirely untested — neuroprotective argument. *Key caveat:* propranolol does not block orexin receptors, and the relative contribution of β-adrenergic vs orexin signalling to neuronal cAMP/PKA tone is unknown. The Hussain et al.\ (2025, SfN presentation) experimental TBI cocktail combined an alpha-blocker with a beta-blocker to improve glymphatic clearance, not to modulate tau phosphorylation — the PKA mechanism is distinct.

*Prazosin revisited.* The paper already includes prazosin among glymphatic-impairing medications (Section @sec:ch15-glymphatic), citing Zhu et al.\ @Zhu2025noradrenergicGlymphatic for NE oscillation suppression. However, alpha-1 adrenergic receptors also signal through Gq → phospholipase C → IP3/DAG → calcium — a pathway that also activates PKA indirectly via calcium-sensitive adenylyl cyclase. Iliff's group (University of Washington) found in a retrospective study that veterans taking prazosin for trauma-related nightmares showed reduced dementia risk, and they are now prospectively testing prazosin's glymphatic effects in rodents and nonhuman primates. The two mechanisms — NE oscillation suppression (potentially impairing glymphatic clearance) vs PKA pathway dampening (potentially reducing tau phosphorylation) — are in *opposition* for glymphatic outcomes but may be *synergistic* for tau outcomes. This tension is unresolved; the retrospective dementia finding suggests the net effect may favour neuroprotection in some populations. No ME/CFS prazosin data exist.

*Lithium (GSK3β inhibitor).* GSK3β is a major tau kinase distinct from PKA — it phosphorylates tau at Ser396/404 rather than the Ser202/Ser409/Thr205 sites affected by DORAs. Lithium is an established GSK3β inhibitor at therapeutic concentrations (0.6--1.2 mmol/L). Guttuso et al.\ (2024) conducted an RCT (n=60) of low-dose lithium aspartate (20--25 mg/day, far below bipolar dosing) in Long COVID cognitive impairment and found significant improvement in fatigue and cognitive endpoints, though the mechanism (GSK3β vs neurotrophic vs anti-inflammatory) was not established @Guttuso2024lithiumLongCOVID. Relevance to the tau phosphorylation discussion is speculative: if tau phosphorylation contributes to ME/CFS neurocognitive symptoms (unestablished), lithium could provide complementary tau kinase inhibition (GSK3β) to DORAs' PKA inhibition, targeting different phospho-sites. This is a multi-kinase tau suppression concept entirely untested in any condition.

*Valproate (HDAC inhibitor with GSK3β inhibition).* Valproate inhibits both histone deacetylases (HDACs) and GSK3β — providing a dual mechanism of epigenetic modulation (potentially relevant to the epigenetic consolidation lock, Chapter @ch:causal-hierarchy) and tau kinase inhibition. Like lithium, it is an "old, dirty drug" with established human safety data but significant adverse effect burden (tremor, weight gain, hepatic effects, teratogenicity) that limits its candidacy for ME/CFS. The GSK3β inhibitory component at clinically achievable concentrations is modest. No ME/CFS valproate data exist.

*Resolving the orexin tone paradox.* The Parhizkar et al.\ temporal finding — active-phase dosing (suppressing *high* endogenous orexin) more effective than inactive-phase — initially appears to complicate ME/CFS, where orexin is already partially suppressed (~250 pg/mL CSF vs narcolepsy $<$110 pg/mL). However, the resolution is that the ME/CFS problem is not *absolute level* but *circadian misplacement*: the "tired but wired" phenotype reflects orexin that is too low during wake (insufficient arousal) and too *high* during sleep (failed withdrawal, producing alpha-delta intrusion and fragmented NREM). The nocturnal orexin signal — the signal that should be absent during deep sleep but persists in ME/CFS — is the very signal that DORAs suppress. Bedtime DORA administration targets precisely the pathologically elevated nocturnal orexin window without suppressing the already-deficient daytime tone (DORAs have a ~10-hour half-life, clearing by morning). The active-phase dosing in mice (lights-off, when orexin peaks) is mechanistically analogous to bedtime dosing in humans (sleep onset, when orexin should withdraw but fails to in ME/CFS). This reframes the paradox as a *dosing alignment* question: DORAs are expected to provide dual benefit in ME/CFS — sleep consolidation + PKA-mediated tau protection — because they target the nocturnal orexin surplus rather than the daytime deficiency. The critical caveat is that intermittent or late-night DORA use could still suppress daytime orexin if the drug persists past morning awakening; short-acting DORAs (suvorexant, ~12h half-life at 20 mg) may be preferable to longer-acting formulations for ME/CFS patients specifically to avoid encroaching on the already-deficient daytime orexin window.

==== Medications and Glymphatic Clearance: Reconciling the Evidence

*Certainty: 0.15--0.30.* The paper's existing glymphatic medication warning (Section @sec:ch15-glymphatic) groups Z-drugs and DORAs together as potentially impairing glymphatic clearance via NE oscillation suppression. Three lines of evidence now suggest this grouping may be incorrect — DORAs and Z-drugs have *opposing* effects on glymphatic function, and several agents may actually *enhance* clearance:

*DORAs: unmeasured glymphatic effects, but evidence of tau production-side benefit via PKA.* The Zhu et al.\ @Zhu2025noradrenergicGlymphatic citation in the existing warning infers DORA harm from general adrenergic pharmacology but never directly tested DORAs on glymphatic flow. The mechanistic direction is unclear: (1) orexin withdrawal during sleep is normal physiology --- DORAs facilitate this natural withdrawal, which *could* permit the LC to settle into the infraslow ($tilde$0.05 Hz) oscillatory pattern that Hauglund et al.\ @Hauglund2025neVasomotion identified as the glymphatic pump driver; (2) however, ME/CFS already involves partial orexin suppression (Section @sec:ch15-orexin), and further pharmacological suppression *could* worsen clearance if orexin tone is already below the optimal range for LC oscillatory dynamics. Neither prediction has been directly tested: no study has measured glymphatic flow before and after any DORA in any species. (3) Lucey et al.\ (2023) demonstrated suvorexant reduced CSF p-tau181 by ~10--15% in sleeping humans @Lucey2023SuvorexantTau --- but this could operate via PKA-mediated reduction of tau *phosphorylation* (a production-side mechanism, Section @spec:ch15-orexin-pka-tau) rather than glymphatic *clearance* enhancement, or via improved sleep architecture independent of glymphatic pumping. The p-tau reduction is consistent with DORA benefit but does not distinguish between mechanisms. (4) Parhizkar et al.\ showed lemborexant preserved hippocampal volume by 30--40% in tauopathy mice while zolpidem gave zero protection @Parhizkar2025LemborexantTau --- again, consistent with either production-side PKA inhibition or clearance enhancement. In summary: DORAs have downstream evidence of tau-related neuroprotection but no direct glymphatic measurement. The net glymphatic effect --- enhancing (facilitated NE withdrawal) or impairing (further orexin suppression in already-suppressed ME/CFS) --- is unknown. The current evidence supports DORAs as mechanistically distinct from Z-drugs in tau outcomes, not in glymphatic clearance per se.

*Propranolol: normalising NE oscillations, not suppressing them.* Low-dose bedtime propranolol (10--20 mg, already discussed for autonomic coupling in Section @sec:ch15-cross-modal-decoupling) may improve glymphatic clearance by damping *excessive* nocturnal sympathetic tone — the "brain asleep, heart awake" decoupling pattern that SleepFM identified as the strongest disease predictor @Thapa2026sleepfm. In ME/CFS dysautonomia, NE is not simply elevated or suppressed but *dysregulated*: sympathetic surges during supposed NREM sleep fragment sleep architecture, while LC fails to settle into coherent infraslow oscillation. Propranolol at low dose acts as a normaliser, not a suppressor — reducing pathological sympathetic surges without abolishing the low-amplitude oscillatory signal needed for vasomotion. This is distinct from high-dose beta blockade which would suppress both pathological and physiological NE signalling.

*Clonidine: stabilising LC oscillatory amplitude.* Low-dose clonidine (0.025--0.05 mg at bedtime, titrated over weeks) reduces LC firing rate but preserves oscillatory competence, unlike Z-drugs which suppress oscillation amplitude by ~50% @Hauglund2025neVasomotion. By reducing the excessive tonic NE drive that keeps the LC from settling into its oscillatory state, clonidine may paradoxically *increase* oscillation quality — restoring the infraslow rhythm that drives vasomotion and glymphatic flow. No direct glymphatic data exist for clonidine; this inference is from the LC-NE oscillation physiology established by Hauglund et al.

*Trazodone: SWS consolidation without NE suppression.* Low-dose trazodone (25--50 mg) increases slow-wave sleep duration and consolidates sleep architecture without suppressing NE oscillations @Zhu2025noradrenergicGlymphatic. This makes it mechanistically distinct from Z-drugs: it improves the *window* for glymphatic clearance (more SWS) without impairing the *pump* (preserved NE oscillations). Trazodone is already discussed in the paper's treatment chapters for ME/CFS sleep; the glymphatic argument provides an additional mechanistic rationale beyond subjective sleep improvement.

*Revised medication classification.* The existing glymphatic warning should be read with the following revision, pending direct experimental glymphatic measurements in ME/CFS:

| Agent | NE oscillation effect | Net glymphatic prediction |
|-------|----------------------|--------------------------|
| Z-drugs (zolpidem) | Suppress amplitude $tilde$50% | Impair |
| DORAs (suvorexant, lemborexant) | May normalise OR may worsen (already-suppressed ME/CFS orexin) | Unknown (production-side tau benefit via PKA established; net glymphatic effect unmeasured) |
| Low-dose propranolol | Normalise (dampen surges, preserve oscillation) | Potential enhance |
| Low-dose clonidine | Stabilise (reduce tonic drive, preserve oscillatory) | Potential enhance |
| Low-dose trazodone | Neutral (consolidates SWS window) | Potential enhance via window extension |
| Alpha-1 blockers (prazosin) | Suppress amplitude | Potential impair |
| Quetiapine (low-dose) | Suppress via alpha-1 blockade | Potential impair |

The critical clinical implication: DORAs demonstrate downstream neuroprotection (tau reduction) independently of glymphatic function, but the mechanism may be production-side (PKA inhibition) rather than clearance-side. Z-drugs lack both glymphatic enhancement and tau neuroprotection. Neither drug class has been directly tested for glymphatic effects in humans. This uncertainty should be communicated clearly to patients considering sleep medication choices: the evidence for DORA benefit is more promising than for Z-drugs, but the mechanism and magnitude of any glymphatic effect remain entirely unknown.

*Prescribing framework: when, how often, which events.* The above classification is mechanistic; the practical question is *when* each agent should be taken, whether nightly or as needed, and which clinical events trigger use.

*DORAs* — nightly, scheduled. Daridorexant 25--50 mg 30 minutes before bed. The 52-week extension study demonstrated no tolerance or withdrawal with *either* continuous or intermittent use @Kunz2022daridorexant, making DORAs the only sleep medication class with explicit intermittent safety data. However, glymphatic clearance is cumulative — each non-restorative night adds metabolic waste that the next night must clear. The rationale for scheduled nightly use is that ME/CFS sleep architecture is *persistently* impaired (not episodic), and the neuroinflammatory-glympathic vicious cycle operates on a nightly basis, not an occasional one. PRN use — taking a DORA only after a subjectively bad night — is mechanistically counterproductive: by the time the patient notices non-restorative sleep, the waste has already accumulated, and the missed clearance window has closed. *Dose timing is critical:* the drug must be taken 30 minutes before bedtime to suppress the nocturnal orexin signal that should be withdrawing but fails to in ME/CFS. Taking a DORA at 3 AM after waking unfreshed is too late — the glymphatic window in the first NREM cycle is already lost.

*Trazodone* — nightly, scheduled. 25--50 mg at bedtime. The rationale for scheduled use is identical: SWS consolidation must happen *during* sleep, not after it fails. Trazodone's mechanism (SWS window extension without NE suppression) makes it complementary to DORAs: DORAs normalise the orexin→NE oscillatory signal, trazodone extends the window in which that oscillation drives clearance.

*Low-dose propranolol/clonidine* — nightly, scheduled, at bedtime. Both agents function as NE oscillation normalisers, and the glymphatic pump operates during each NREM cycle. However, propranolol also has a PRN use case documented in Chapter @ch:integrative-treatment: 10--20 mg before high-risk activities as a pacing enforcement tool (pharmacological heart rate ceiling). This PRN use is for daytime pacing, not nocturnal glymphatic support — the mechanisms are distinct.

*After PEM.* Sleep architecture fragmentation predictably worsens during post-exertional malaise (Section @sec:sleep-architecture), with CNS energy deficits intensifying 24--72 hours post-exertion. This is the event where glymphatic-enhancing agents are *most* needed — the waste production is highest and the endogenous clearance capacity is lowest. The clinical implication: the night *before* an anticipated PEM window (e.g., if the patient has a medical appointment that will trigger PEM) is not the time to skip the scheduled DORA/trazodone dose. Conversely, adding an extra agent on the night *after* a crash has no role — the glymphatic window cannot be recovered retrospectively, and polypharmacy at bedtime increases the risk of accumulated sedation and cognitive impairment. The strategy is consistent nightly scheduled use, with dosing adjustments made pre-emptively, not reactively.

*What to avoid.* Z-drugs should not be used as "rescue sleep" after a bad night — the evidence now shows they increase sleep duration while suppressing the NE oscillations needed for glymphatic clearance, and provide zero tau neuroprotection. They solve the problem the patient feels (wakefulness) while worsening the problem the patient needs solved (waste clearance). The same applies to PRN quetiapine or prazosin at bedtime for sleep — the alpha-1 blockade component impairs vasomotion regardless of dose timing.

*Contraindications and side effects.* The glymphatic benefit of these agents must be weighed against their safety profiles, which differ substantially. Trazodone is the lowest-risk entry point; DORAs have the strongest mechanistic rationale but the highest practical barriers.

    - *Trazodone 25--50 mg.* Key contraindications: MAOI co-administration (serotonin syndrome risk). Critical side effects: next-day sedation at doses above 50 mg; priapism (~1/6000, rare but permanent damage if untreated — warn male patients); orthostatic hypotension. ME/CFS-specific concern: already-impaired daytime alertness worsens if dose too high; keep at or below 50 mg.
    - *DORA (daridorexant) 25--50 mg.* Key contraindications: narcolepsy (absolute); severe hepatic impairment (Child-Pugh C); strong CYP3A4 inhibitors. Critical side effects: sleep paralysis (less than 1 percent); complex sleep behaviours (sleep-walking, rare); next-day somnolence (dose-dependent, ~3 percent at 25 mg); headache. ME/CFS-specific concern: borderline CSF orexin levels in some patients raise narcolepsy misdiagnosis concern; \$350--\$450/month without insurance; Schedule IV controlled substance — many clinicians refuse as policy; no ME/CFS-specific data.
    - *Propranolol 10--20 mg.* Key contraindications: asthma/COPD (beta-blockade triggers bronchospasm); bradycardia (HR below 60); hypotension (SBP below 100). Critical side effects: fatigue worsening, exercise intolerance, cold extremities, vivid nightmares. ME/CFS-specific concern: already documented as harm in treatment chapters; ivabradine preferred if pure HR reduction needed; low-dose bedtime use for glymphatic normalisation is entirely speculative with no published human glymphatic data.
    - *Clonidine 0.025--0.05 mg.* Key contraindications: hypotension (SBP below 100); bradycardia; severe coronary insufficiency. Critical side effects: morning sedation, dry mouth, rebound hypertension on abrupt discontinuation. ME/CFS-specific concern: no adult ME/CFS dosing data exists; orthostatic intolerance may worsen; dangerous if patient is too fatigued to refill on time; entirely speculative for glymphatic use — no published data.

*Of these four, only trazodone is a straightforward prescription:* generic (~\$4/month), 50+ years of safety data, universally accepted off-label use for insomnia. DORAs face the highest refusal risk — Schedule IV status, high cost, no FDA indication for ME/CFS, and the legitimate absence of ME/CFS-specific outcome data. A reasonable clinician would correctly state that evidence for DORAs in ME/CFS does not exist. Propranolol and clonidine for nocturnal NE normalisation are entirely speculative — no published human glymphatic data for either agent — and refusal on evidence-based grounds is appropriate. The paper provides mechanistic rationale to motivate trials, not clinical assertions that override the absence of data.

*Falsifiable predictions.* (a) DTI-ALPS glymphatic index will improve after 4 weeks of lemborexant vs placebo in ME/CFS patients, while zolpidem will show no change or worsening. (b) CSF p-tau181/T181 ratio will decrease on DORA and remain unchanged or increase on zolpidem, matched for sleep duration improvement. (c) NE oscillation amplitude during NREM sleep will increase on DORA, remain stable on propranolol/clonidine/trazodone, and decrease on zolpidem/prazosin.

*Falsifiable prediction.* A head-to-head comparison of lemborexant vs placebo in ME/CFS, with CSF p-tau181/T181 ratio as primary endpoint at 4 weeks, would directly answer: (a) whether ME/CFS patients have elevated baseline p-tau vs controls, and (b) whether further orexin suppression meaningfully reduces it. A null result would suggest either that ME/CFS does not involve tau hyperphosphorylation, or that endogenous orexin suppression has already "taken care of it." A positive result would motivate DORA + GSK3β inhibitor combination studies for multi-kinase tau suppression.

*Post-infectious context.* The orexin suppression pathway has direct parallels across post-infectious conditions. Narcolepsy type 1 is a confirmed post-infectious orexin disease: H1N1 influenza and the Pandemrix vaccine triggered autoimmune destruction of $>$95% of orexin neurons in genetically susceptible individuals (HLA-DQB1\*06:02) @Rauf2025narcolepsyOrexin. ME/CFS may occupy a less severe position on the same spectrum: functional suppression rather than destruction, intermediate orexin levels rather than abolition, and reversibility (in principle) if the inflammatory drive resolves. In Long COVID/PASC, Ruhrländer et al.\ (2025) proposed orexin disruption as an explanation for POTS, endothelial dysfunction, and metabolic dysregulation @Ruhrländer2025orexinPASC. Heinicke et al.\ (2025) measured plasma orexin-A in 78 ICU COVID patients and found that levels correlated with survival (Cohen's $d=0.4$) and inversely with length of stay, with neuropeptide perturbations persisting at 2.5-year follow-up @Heinicke2025orexinCOVID.

#include "subsec-06-medications-and-glymphatic-clearance-rec/speculations/spec-pge-sub-2.typ"

#include "subsec-06-medications-and-glymphatic-clearance-rec/speculations/spec-the-orexin-vasomotion-glymphatic-triad-a.typ"

#include "subsec-06-medications-and-glymphatic-clearance-rec/speculations/spec-thalamocortical-vasomotion-resonance-fai.typ"

#include "subsec-06-medications-and-glymphatic-clearance-rec/speculations/spec-glymphatic-failure-as-a-mechanism-for-po.typ"

#include "subsec-06-medications-and-glymphatic-clearance-rec/speculations/spec-orexin-autonomic-vascular-convergence-du.typ"

#include "subsec-06-medications-and-glymphatic-clearance-rec/speculations/spec-chronobiological-phase-separation-intern.typ"

// =============================================================================
// PART B: NEUROCHEMICAL SYMPTOM GENERATORS
// =============================================================================

