#import "../../../../shared/environments.typ": *

==== Cascade: PIP2 → TRPM3 → five-arm end-organ dysfunction

*Cascade:*
- PIP2 depletion (GPCR AAb → PLC-β hydrolysis)
- TRPM3 calcium influx failure
- (a) NK cell cytotoxicity loss → impaired viral clearance, immune surveillance
- (b) pancreatic β-cell insulin secretion impairment → postprandial energy dysregulation
- (c) neurotransmitter release impairment at autonomic ganglia → orthostatic intolerance, GI dysmotility
- (d) vascular smooth muscle calcium dysregulation → impaired vasoconstriction and vasodilation
- (e) sensory neuron TRPM3 dysfunction → altered pain and temperature perception
- Each arm has a distinct probe.


*Step A1:* PIP2 depletion (membrane-level trigger — upstream of all TRPM3 dysfunction)
- *Mechanism:* GPCR autoantibodies (β2-AR, M2/M4) activate Gαq → PLC-β → PIP2 hydrolysis to IP3 + DAG. PIP2 is the essential cofactor for TRPM3 gating — without PIP2 in the inner membrane leaflet, TRPM3 cannot open regardless of agonist (pregnenolone sulfate, heat). PIP2 depletion is the most parsimonious single mechanism for simultaneous TRPM3, TRPV1, TRPM7, and TRPC channel dysfunction — all are PIP2-dependent.
- *Intercept:* Lithium (low-dose, 2--20 mg elemental; IMPase inhibitor, mood stabilizer at microdose) — inhibits IMPase, the enzyme that degrades IP2 → IP1, conserving the inositol pool for PIP2 resynthesis @spec:low-dose-lithium. This is the most upstream probe in the entire chapter — lithium intercepts before any channel, at the membrane phospholipid level.
- *If lithium works (reduces fatigue, improves NK function, reduces PEM):* PIP2 depletion is rate-limiting. The lesion is at membrane phospholipid regulation — upstream of all ion channels. GPCR autoantibody-driven PLC hyperactivity is the likely upstream driver. This is high-specificity evidence for the autoimmune → PIP2 → ion channel dysfunction pathway. If lithium works AND immunoadsorption works → the causal chain is confirmed at both ends (remove the AAb that drives PLC, and separately conserve the PIP2 that PLC depletes).
- *If lithium does NOT work:* PIP2 depletion is not the bottleneck. Either (a) PIP2 levels are normal (AAb are not driving sufficient PLC activity), (b) PIP2 resynthesis capacity is saturated — inhibiting IMPase cannot increase PIP2 further because the synthesis pathway is already maximally active, (c) TRPM3 has additional defects beyond PIP2-dependence (direct channel phosphorylation, altered expression, or channel-blocking autoantibodies), or (d) the lesion is downstream of PIP2 availability — calcium handling inside the cell, not calcium entry at the membrane.
- *Lithium dosing gradient:* If benefit at 2--5 mg but lost at 20 mg → inverted U (IMPase inhibition at low dose, inositol depletion at higher doses). The dose at which benefit inverts is consistent with inositol pool size — inverts earlier with a smaller pool, later or never with a larger one.

*Step A2:* TRPM3 calcium influx failure (channel-level defect)
- *Mechanism:* Even with adequate PIP2, TRPM3 may fail to gate due to: (a) direct channel-blocking autoantibodies (anti-TRPM3 IgG, not yet documented but mechanistically possible), (b) altered channel expression (TRPM3 gene silencing via promoter methylation), (c) competitive inhibition at the pregnenolone sulfate binding site by endogenous antagonists, or (d) channel desensitization from chronic low-grade activation (heat, inflammation → sustained TRPM3 opening → calcium-dependent inactivation).
- *Intercept:* Pregnenolone sulfate (positive allosteric TRPM3 modulator; neurosteroid) — shifts the channel's activation curve leftward so lower PIP2/heat can open it) @spec:pregnenolone-ldn-synergy; Naltrexone (LDN, 1--4.5 mg; low-dose opioid receptor antagonist, TLR4 antagonist) — in vitro TRPM3 restoration via TLR4 antagonism reducing channel-destabilizing inflammatory signaling @Cabanas2021.
- *If LDN or pregnenolone works:* TRPM3 dysfunction is present AND rate-limiting. The lesion is at the channel level (primary channelopathy) or just above (PIP2-dependent gating failure). Distinguishing: if lithium also works → the lesion is at PIP2; TRPM3 can gate when given PIP2. If lithium does NOT work but LDN/pregnenolone works → the channel itself is the bottleneck — PIP2 depletion is not the rate-limiting node.
- *If LDN works within 48 hours:* Consistent with TRPM3 mechanism (immediate channel gating effect). Onset latency suggests TRPM3 as the primary LDN target in this patient — however, placebo and expectation effects also onset within this window limiting specificity.
- *If LDN works but it takes 3--6 weeks:* The mechanism is endorphin upregulation or TLR4-mediated anti-neuroinflammatory effect — NOT TRPM3. The patient benefits from LDN but the ion channel hypothesis is not confirmed. This dissociation is clinically relevant: a patient with LDN benefit at 6 weeks may have neuroinflammation, not ion channel dysfunction, and different follow-up probes are indicated.
- *If LDN/pregnenolone does NOT work:* TRPM3 ion channel dysfunction is either (a) absent in this patient, (b) present but not LDN-responsive (direct channel-blocking autoantibodies that LDN cannot displace, requiring immunoadsorption), (c) not rate-limiting — other channel defects dominate (TRPV1, TRPM7, or calcium channel autoantibodies), or (d) the downstream cellular machinery (calcium-dependent exocytosis, Ca²⁺/calmodulin signaling) is so damaged that restoring Ca²⁺ influx does not restore function. A null TRPM3 response combined with a null lithium response effectively eliminates the PIP2→TRPM3 ion channel axis.

*Step A3:* NK cell cytotoxicity loss (immune consequence)
- *Mechanism:* NK cells require Ca²⁺ influx through TRPM3 for lytic granule polarization and exocytosis — the killing mechanism. TRPM3 failure → impaired NK cell degranulation → reduced perforin/granzyme release → impaired viral clearance and tumour surveillance. This is one of the most consistently replicated immune findings in ME/CFS.
- *Intercept:* Immunoadsorption (extracorporeal IgG removal; autoantibody depletion) — removes GPCR autoantibodies upstream, potentially restoring PIP2 and thus TRPM3; IVIG (pooled donor immunoglobulins; broad immunomodulation, Fc receptor modulation) — broad immunomodulation including NK cell enhancement via Fc receptor modulation; Cimetidine (H2 receptor antagonist; T-cell enhancer, CYP450 inhibitor) — enhances T-cell and NK cell function through H2 receptor blockade on suppressor T cells (disinhibits cytotoxic function); Inosine pranobex (Isoprinosine, immunostimulant; NK cell enhancer) — enhances NK cell activity through undefined mechanism.
- *If cimetidine works but LDN does NOT:* The immune dysfunction is at T-cell/H2-receptor level, not NK/TRPM3-dependent. Cimetidine disinhibits cytotoxic function by blocking H2-mediated suppression — the pathway is intact but suppressed. Consistent with histamine-driven immune suppression rather than ion-channel-driven NK failure.
- *If IVIG works:* Autoantibody-mediated pathology (upstream of TRPM3) is likely dominant. The channelopathy is secondary — restoring PIP2 through AAb removal restores TRPM3 function, and NK cell cytotoxicity follows. IVIG response + LDN response = multi-level immune restoration.
- *If both IVIG and LDN work:* Both upstream (autoantibody → PIP2 restoration via IA) and downstream (TRPM3 gating via LDN) interventions are effective. Therapeutic priority: treat the autoantibody source for root cause (rituximab, IA, BC007), LDN for symptomatic channel support while awaiting source treatment to take effect. The dual response confirms the full PIP2→TRPM3→NK axis as causal.
- *If IVIG does NOT work but LDN works:* The NK defect is at the channel level — LDN restores TRPM3 gating directly at NK cells (where TRPM3 and TLR4 are co-expressed). The channelopathy is primary, not secondary to AAb. Immunoadsorption would not help because PIP2 is not the limiting factor.
- *If neither LDN nor IVIG works:* The NK cell defect is either (a) structural — NK cell numbers are reduced (common in ME/CFS), not just functionally impaired; restoring TRPM3 gating cannot rescue cytotoxicity if there are too few NK cells, or (b) the lesion is downstream of Ca²⁺ influx — the lytic granule machinery (Rab27a, Munc13-4, syntaxin-11) is intact but not responsive to calcium signal. This pattern is consistent with exhausted/depleted NK cells, not channel-inhibited NK cells.

*Step A4:* Neurotransmitter release impairment (neurochemical consequence)
- *Mechanism:* Calcium-dependent vesicle exocytosis at autonomic ganglia and CNS synapses requires TRPM3-mediated Ca²⁺ entry (and Cav2.x channels). While many synapses rely on voltage-gated calcium channels for fast transmission, TRPM3 provides sustained Ca²⁺ elevation for vesicle pool replenishment and neuropeptide release (substance P, CGRP, NPY — pain, vasodilatory, and sympathetic co-transmitters respectively). TRPM3 failure → impaired sustained neurotransmitter release → ganglionic transmission failure → orthostatic intolerance (sympathetic ganglia), GI dysmotility (enteric and vagal), and cognitive dysfunction (CNS).
- *Intercept:* Pyridostigmine (Mestinon, 30--60 mg; acetylcholinesterase inhibitor, peripheral cholinergic) — acetylcholinesterase (AChE) inhibitor, enhances cholinergic signalling by increasing synaptic acetylcholine (ACh) dwell time, compensating for reduced release probability at autonomic ganglia; Atomoxetine (norepinephrine reuptake inhibitor; NRI) — NRI, increases norepinephrine (NE) at synapse by blocking reuptake, compensating for reduced NE release; 5-HTP (serotonin precursor) — serotonin precursor, bypasses tryptophan-dependent synthesis if serotonin depletion coexists.
- *If pyridostigmine works:* Acetylcholine-dependent synaptic transmission at autonomic ganglia is impaired — consistent with TRPM3-mediated Ca²⁺-dependent vesicle release failure at the synapse. Pyridostigmine partially compensates by increasing the probability that any single release event produces postsynaptic activation. The improvement is functional, not corrective — the underlying Ca²⁺ deficit remains.
- *If pyridostigmine does NOT work and LDN works:* TRPM3 dysfunction exists (LDN responsive) but the bottleneck is upstream of cholinergic transmission — LDN benefit is through a non-synaptic mechanism: TRPM3 on immune cells (NK cells, mast cells), pancreatic β-cells, or vascular smooth muscle. The synaptic cholinergic system is either intact (sufficient Ca²⁺ from Cav channels) or too damaged to respond to AChE inhibition. This dissociation localizes the TRPM3 lesion away from autonomic ganglia.
- *If atomoxetine works but pyridostigmine does NOT:* The neurotransmitter release deficit is specific to the noradrenergic system — NE reuptake inhibition compensates. Cholinergic synapses are intact (pyridostigmine null means ACh release is adequate). This pattern distinguishes NE-specific from global Ca²⁺-dependent release failure. Consistent with selective noradrenergic defect (@ach:catecholamine-deficit) rather than global synaptic TRPM3 dysfunction.
- *If 5-HTP works but atomoxetine does NOT:* The neurotransmitter deficit is serotonergic, not noradrenergic — consistent with TRPM3 on raphe neurons (serotonin synthesis/release) being more affected than TRPM3 on locus coeruleus neurons (NE). The TRPM3 phenotype has cell-type specificity.

*Step A5:* Vascular smooth muscle calcium dysregulation (orthostatic consequence)
- *Mechanism:* Vascular smooth muscle contraction depends on Ca²⁺ influx through L-type Ca²⁺ channels (Cav1.2) and TRPM3 (which provides sustained Ca²⁺ for myosin light chain kinase activation). TRPM3 is co-expressed with Cav1.2 in resistance arteries. TRPM3 failure → impaired sustained vasoconstriction → venous pooling, orthostatic hypotension, and compensatory tachycardia.
- *Intercept:* Midodrine (α1-adrenergic receptor agonist, 2.5--10 mg; vasoconstrictor) — directly constricts vasculature through Gαq → PLC → IP3 → Ca²⁺ release from sarcoplasmic reticulum, bypassing membrane Ca²⁺ channels entirely; Ivabradine (I_f channel blocker; SA node heart rate reduction) — slows HR through If current block at SA node, no Ca²⁺ channel dependence; Fludrocortisone (mineralocorticoid; volume expansion, sodium retention) — volume expansion, reduces the vasoconstrictive demand.
- *If midodrine works:* The vasculature is responsive to direct α1 agonism — the contractile machinery (myosin light chain kinase, actin-myosin) is functional. The deficit is at the membrane level: insufficient Ca²⁺ entry for sustained contraction. Either sympathetic output is low (CNS catecholamine deficiency → reduced α1 activation → reduced Cav/TRPM3 opening) or vascular Ca²⁺ handling is directly impaired (TRPM3 dysfunction). The positive midodrine response confirms that the postsynaptic vasculature can contract — the problem is the signal to contract, not the contractile apparatus.
- *If midodrine works AND LDN works:* Both Ca²⁺-handling (TRPM3 at vascular smooth muscle) and vascular tone are abnormal. Consistent with multi-channel dysfunction from PIP2 depletion — the same PIP2 deficit affects TRPM3 (on NK cells, neurons, and smooth muscle) and potentially other PIP2-dependent channels. Immunoadsorption should be considered — if PIP2 depletion is driving multi-channel dysfunction, removing the AAb that drives PLC should restore PIP2 and all channel functions simultaneously.
- *If midodrine does NOT work:* The vasculature is unresponsive even to direct α1 stimulation. This is a severe finding — it means either (a) α1 receptors are absent or blocked (GPCR AAb against α1-AR), (b) the contractile machinery is damaged (smooth muscle atrophy from chronic disuse, nitric oxide overproduction from endothelial dysfunction), or (c) severe hypovolemic orthostatic intolerance where vasoconstriction is inadequate because there is insufficient blood volume to distribute. If fludrocortisone works where midodrine fails → hypovolemia is dominant; the vasculature is functional but empty. If neither works → the vasculature is structurally unable to contract; endothelial dysfunction or receptor-level blockade is likely.
- *If ivabradine works for HR but midodrine does NOT work for BP:* Inappropriate sinus tachycardia is the dominant hemodynamic symptom, not vascular failure. The SA node is responding to a baroreflex signal that says "pressure is low," but the vasculature cannot increase pressure. Slowing the HR reduces myocardial oxygen demand without worsening perfusion (because perfusion was already inadequate). This pattern is consistent with baroreflex reset (GPCR AAb at NTS) combined with vascular unresponsiveness.

*Consequence:* TRPM3 is the most pharmacologically probe-able ion channel in ME/CFS. Ten drugs at five distinct steps (lithium at PIP2, LDN/pregnenolone at channel, cimetidine/IVIG at NK cells, pyridostigmine/atomoxetine/5-HTP at neurotransmitter release, midodrine/ivabradine at vasculature) map the lesion along the PIP2→TRPM3→cell-type axis. The pattern of which drugs work and which do not localizes whether the defect is upstream (PIP2, treat AAb source), at the channel (TRPM3 gating, treat with LDN/pregnenolone), or cell-type-specific (NK cells → immunomodulation; synapses → neurotransmitter support; vasculature → vasoconstrictors). The onset latency of LDN response (under 48h suggests TRPM3, 3--6 weeks suggests endorphin/TLR4 — with limited specificity; placebo and expectation effects also onset within 48h) further distinguishes channel from inflammatory mechanisms.
*Origin:* mechanistic-pathway-tracing, Gerlier 2026-07-21 prompt.

