#import "../../../../shared/environments.typ": finding, speculation, hypothesis, open-question, synthesis


=== CNS Stimulants and Wake-Promoting Agents <sec:cns-stimulants>

All stimulants probe catecholamine (dopamine/norepinephrine) deficiency. Their differences in mechanism, selectivity, and safety create a hierarchy. *All are symptom management* — none address root cause. Hierarchy from safest to most concerning: pitolisant > solriamfetol ≈ modafinil > methylphenidate > amphetamines.

==== If stimulants work


#finding(claim: [Catecholamine signaling was insufficient.], explanation: [Drug increased dopamine/norepinephrine → cognition improved → signaling was inadequate.], certainty: [Medium — CSF catecholamine reduction documented @Walitt2024NIH; stimulant surveys 77.1% brain fog improvement @Eckey2025PatientReported; methylphenidate RCT 17% response @Blockmans2006MPHCFS; solriamfetol RCT significant fatigue improvement (p=0.039) @Young2025solriamfetol. But effect sizes modest and survey data uncontrolled.], dntu: [why catecholamines are deficient; whether benefit is sustainable (masking fatigue enables overexertion — survey: 77.1% brain-fog improvement but no net PEM improvement (−1.5%)).], action: [catecholamine involvement confirmed; combine with LDN (neuroinflammation) or mitochondrial supplements (metabolic constraint) to identify upstream cause.], level: [Symptom management — stimulants compensate for deficient signaling without restoring production or removing inflammatory precursor depletion.])

#finding(claim: [Dopamine deficit type (methylphenidate/solriamfetol vs. amphetamines).], explanation: [Reuptake blocker works but amphetamines cause severe crashes → low-production deficiency (stores depleted, production insufficient to replenish).], certainty: [Low to Medium.], level: [Symptom management.])

#finding(claim: [Brain energy metabolism integrity (modafinil vs. methylphenidate).], explanation: [Modafinil has brain ATP enhancement and M1→M2 microglial shift @Minzenberg2008modafinil. Methylphenidate increases REE +7% and chronically decreases hippocampal ATP @Graveling2023stimulantmitochondria. Modafinil tolerated + methylphenidate worsens energy → brain can benefit from ATP enhancement but cannot tolerate +7% metabolic cost.], certainty: [Low (modafinil's only ME/CFS RCT was negative, n=14 @Randall2005modafinil).], level: [Symptom management — modafinil blurs toward partial root cause (brain-level, speculative).])

#finding(claim: [Histaminergic arousal system intact (pitolisant).], explanation: [Pitolisant blocks H3 autoreceptors, increasing endogenous histamine. Works without sympathetic activation → histaminergic pathway functional.], certainty: [Low — no ME/CFS data.], level: [Partial root cause (speculative) — anti-neuroinflammatory M1→M2 microglial shift.])

==== What stimulants act on: arousal and reward, not attention capacity

A positive stimulant response is often read as evidence of an *attention-network* deficit. Large-sample human evidence argues against that reading. In the ABCD Study (n=11,875; 337 stimulant-on-scan-day) plus a controlled methylphenidate challenge, therapeutic stimulants were associated with functional-connectivity differences in arousal (somato-cognitive action/motor) and reward-salience (salience/parietal-memory) networks, with no detected effect in the dorsal/ventral attention or frontoparietal control networks @Kay2025stimulantarousalreward. The stimulant connectivity pattern matched sleep-duration and norepinephrine-transporter maps and reversed sleep-deprivation signatures. Objective cognition improved only in children who were ADHD-diagnosed or sleep-deprived — not in rested participants, a moderator relevant to ME/CFS given its unrefreshing sleep. Concordant meta-analyses find limited and inconsistent objective cognitive enhancement in rested healthy adults @Ilieva2015StimulantMetaAnalysis @Roberts2020CognitiveEnhancementMeta @Marraccini2016StimulantMetaAnalysis, and amphetamines have been shown to increase willingness to invest effort for reward without improving ability @Chong2023AmphetamineMotivation. Note the evidence is cross-sectional association (n=337) plus a small within-person challenge (n=5), so the network localization is suggestive, not causally established.

#speculation(title: [Stimulant benefit in ME/CFS is consistent with low arousal/reward salience, not an attention deficit])[
Read through the Kay 2025 result @Kay2025stimulantarousalreward, a positive stimulant response in ME/CFS is more parsimoniously interpreted as raising *arousal* and *reward-effort salience* than as restoring attention capacity: the drug makes effort feel more worthwhile and reduces the subjective sense of fatigue, while the underlying energy deficit that drives objective cognitive impairment is untouched. Crucially, the drug's *site of action* constrains what changes, not what was originally broken — a stimulant can raise arousal in a patient whose deficit is metabolic, so a positive response does not identify the deficient node. This is consistent with the documented dissociation between subjective and objective effects @Ilieva2013ObjectiveSubjective and with the observation that stimulants raise effort *level* while lowering effort *quality* @Bowman2023NotSoSmart — the patient works harder, not better. The mechanism is noradrenergic arousal plus dopaminergic reward-salience, which intersects with documented adrenergic dysfunction in ME/CFS/FM @Hendrix2025AdrenergicDysfunction. *Moderator caveat:* in Kay's own data objective cognition improved in depleted (ADHD/sleep-deprived) participants — a state ME/CFS may resemble — so the attention-capacity null may not transfer to an energy-depleted brain; the claim is bounded to the subjective-arousal reading, not to "attention is uninvolved." *Competing mechanism:* task-fMRI meta-analysis reports that stimulants increase right inferior frontal/insular (cognitive-control) activation @Rubia2014StimulantBrainMeta; Kay 2025 attributes this discrepancy to small-sample ROI designs versus a large brain-wide association study, but the two designs answer different questions (resting-state connectivity vs task-evoked control) and the accounts are not fully reconciled in ME/CFS. *Translation gap:* no ME/CFS-cohort study tests the arousal/reward dissociation; the inference is cross-disease (general population + ADHD). *Falsifiability:* an ME/CFS stimulant challenge should show benefit on subjective arousal/effort-reward scales without a specific cognitive-control improvement, and responders should not show a baseline attention-network deficit; the account is disconfirmed if responders show a specific cognitive-control improvement with an appropriate baseline deficit (the Rubia prediction) or if stimulant benefit scales with objective attention improvement rather than subjective arousal. *Consequence:* a patient who feels sharper on a stimulant may feel more motivated to push, not more cognitively capable — so the drug can raise effort without restoring capacity, which is precisely why it can hide PEM. (Raw certainty 0.80, general-population/ADHD → discounted to 0.60; severity applicability unknown — study populations not stratified by ME/CFS severity; evidence: large-sample human fMRI + meta-analyses, not ME/CFS-specific; origin: literature integration.)
] <spec:stimulant-arousal-reward-not-attention>

#open-question(title: [Does the stimulant-response signal localize arousal/reward or cognitive control in ME/CFS?])[
Kay 2025 (n=11,875 cross-sectional + a small controlled challenge) finds no detected attention-network effect and localizes stimulant action to arousal/reward networks @Kay2025stimulantarousalreward, whereas task-fMRI meta-analysis finds increased right inferior frontal/insular cognitive-control activation @Rubia2014StimulantBrainMeta. The discounted certainties differ by ~0.10, within measurement uncertainty. Kay attributes the discrepancy to design (large brain-wide association vs small ROI studies), but the two designs measure different things — resting-state connectivity versus task-evoked cognitive-control engagement — so the difference is not fully adjudicated. For ME/CFS this matters because the two accounts predict different differential inferences from a positive response: low arousal/reward salience (Kay) versus a cognitive-control circuit idling below capacity (Rubia). *Falsifiability:* an ME/CFS stimulant challenge with simultaneous subjective arousal/reward scales and an objective cognitive-control task distinguishes the accounts — benefit on arousal/reward without cognitive-control improvement supports Kay; a specific cognitive-control improvement with an appropriate baseline deficit supports Rubia. *Consequence:* resolving this decides whether a positive stimulant response should be interpreted clinically as a reward/arousal probe or as evidence of an under-driven cognitive-control circuit — a distinction that changes which upstream mechanism a clinician or researcher next targets. (Certainty: n/a — research question; severity applicability unknown; origin: literature integration.)
] <oq:stimulant-arousal-vs-cognitive-control>

#speculation(title: [A positive stimulant response may fractionate into arousal-deficient and reward-effort-deficient subtypes])[
Because stimulants act on two systems — noradrenergic arousal and dopaminergic reward-effort salience @Kay2025stimulantarousalreward — a positive response in ME/CFS may have two compositions. An arousal-dominant response would gain mainly subjective wakefulness/alertness and may respond to arousal-selective agents (modafinil, armodafinil, pitolisant) @Repantis2010ModafinilMPHenhancement; a reward-effort-dominant response would gain mainly drive/motivation to initiate and may respond to dopamine-transporter blockade (methylphenidate) that raises willingness to work for reward @Chong2023AmphetamineMotivation @Bowman2023NotSoSmart. Adrenergic dysfunction is documented in ME/CFS/FM @Hendrix2025AdrenergicDysfunction, providing a plausible arousal-side substrate, though direct ME/CFS reward-motivation data are absent. Note Kay found two *correlated* networks, which does not by itself establish separable systems, and the dopamine/noradrenaline mapping is imported from other work rather than demonstrated in ME/CFS. *Competing explanation:* the two gains may be one non-specific "feeling better" factor, and the drug difference may be dose/side-effect driven rather than phenotype-driven. *Translation gap:* no ME/CFS-cohort cross-over study exists; the subtype split is a hypothesis, not an observation, and has no independent (non-drug) classifier yet. *Falsifiability:* for the split to be testable it requires a baseline classifier independent of drug response (e.g. pupil/autonomic arousal index or effort-discounting k); given such a classifier, arousal-classified patients should respond to arousal-selective agents and reward-classified patients to methylphenidate on a pre-specified within-patient outcome (e.g. blinded forced choice or lower discontinuation on the matched arm). Non-selective benefit in all patients, or no baseline classifier that predicts the matched drug, falsifies separability. (Raw certainty 0.53, general-population/ADHD → discounted 0.40; severity applicability unknown — no stratification; evidence: cross-disease pharmacology + behavioral tasks, not ME/CFS-specific; origin: brainstorm.) *Consequence:* if the split is real, drug choice could follow whether the main problem is feeling awake or feeling able to start — but until an independent classifier exists, it is a hypothesis, not a usable rule.
] <spec:stimulant-endophenotypes-arousal-reward>

==== What a positive response does NOT reveal

A positive stimulant response confirms that catecholamine signaling was insufficient but does not reveal why the catecholamines are deficient (neuroinflammatory precursor depletion, metabolic packaging failure, or genetic causes remain indistinguishable). It also does not reveal *what* the drug restored: large-sample evidence indicates arousal and reward-effort salience rather than attention-network capacity @Kay2025stimulantarousalreward, so a positive response is not evidence of an attention deficit. Critically, it does not tell us whether the benefit is sustainable: stimulants can mask fatigue and enable overexertion, and the same uncontrolled survey showed +77.1% brain-fog improvement but no net PEM improvement (−1.5%, indistinguishable from zero; the pre-existing ch17 reading is that this net hides opposing individual responses). Because effect sizes are modest and much of the supporting data is uncontrolled survey data, a genuine effect cannot be cleanly separated from placebo.

==== If stimulants do NOT work
- Catecholamine deficiency may not be present — cognitive dysfunction from glymphatic failure, direct cytokines, cerebral hypoperfusion, or neuronal mitochondrial failure.
- Receptors downregulated — chronic inflammation reduces expression.
- Side effects mask benefit — sympathetic activation, metabolic cost, sleep disruption produce net negative effect.
- *Dose is a variable, not a single setting:* these drugs act on a catecholamine inverted-U — cognitive benefit appears within a dose window and inverts (turns to overstimulation, distractibility, reduced working memory) above it. A null at one dose is a statement about that dose, not the drug; both too little and too much can fail. See the dose-range reference for the modafinil window (@sec:hormetic-dose-range-reference).

==== Key caveat

A positive response is not automatically beneficial. Stimulants mask fatigue, which enables overexertion — the uncontrolled survey showed +77.1% brain-fog improvement but no net PEM improvement (−1.5%). Masking follows from the combination of subjective improvement and unchanged energy supply, which was already expected before this evidence; the arousal/reward finding additionally explains *why* subjective improvement can occur without capacity gain: raising the willingness to invest effort without increasing energy supply raises effort *level* while leaving effort *quality* and the underlying energy deficit unchanged @Kay2025stimulantarousalreward @Bowman2023NotSoSmart. Monitor PEM closely. Stimulants are contraindicated in the absence of objective activity monitoring, because subjective improvement can conceal an increasing physiological deficit.

==== How Stimulants combine with other medications
- Stimulant works but PEM worsens → the critical warning: catecholamine deficit is downstream of energy deficit. Discontinue or strictly dose-limit with objective activity monitoring.
- Methylphenidate does not work + LDA works → common ME/CFS pattern: receptor-level support more effective than reuptake blockade.
- Stimulant works + LDA works → severe dopamine deficit requiring maximal pharmacological support. Prioritize treating upstream cause.

==== What the Response Tells Us About Mechanisms

Reading the *pattern* across the stimulant class carries more diagnostic information than any single drug response, because a positive response is not one finding but two. The two systems a stimulant raises — noradrenergic arousal and dopaminergic reward-effort salience @Kay2025stimulantarousalreward — can be probed separately:

- *Arousal-dominant response:* the main gain is subjective wakefulness/alertness, and the patient responds preferentially to arousal-selective agents (modafinil, armodafinil, pitolisant) @Repantis2010ModafinilMPHenhancement. This points to an arousal-deficient subtype, consistent with documented adrenergic dysfunction in ME/CFS/FM @Hendrix2025AdrenergicDysfunction.
- *Reward-effort-dominant response:* the main gain is drive/initiation — the patient starts tasks they previously avoided — with little change in wakefulness, and the patient responds preferentially to methylphenidate, which raises willingness to work for reward @Chong2023AmphetamineMotivation.
- *The separator is effort quality, not effort level:* a drug that makes the patient do *more* while doing it *no better* is acting on reward-effort salience, not restoring capacity @Bowman2023NotSoSmart.

This pattern is the clinical form of the endophenotype split in @spec:stimulant-endophenotypes-arousal-reward; it is a hypothesis, not an observation — no ME/CFS cross-over study exists.

#finding(claim: [A positive response is consistent with low arousal or low reward-effort salience rather than a restored attention capacity], explanation: [In large-sample human evidence, stimulants were associated with connectivity differences in arousal and reward-salience networks and no detected effect in the dorsal/ventral attention or frontoparietal control networks @Kay2025stimulantarousalreward. Objective cognition improved only in ADHD or sleep-deprived individuals, and rested adults show limited and inconsistent objective enhancement @Ilieva2015StimulantMetaAnalysis @Roberts2020CognitiveEnhancementMeta @Marraccini2016StimulantMetaAnalysis. Benefit is therefore better read as a low arousal/reward-salience signal than as proof of a broken attention system — the site of drug action constrains what changes, not what was broken. A competing account (right inferior frontal/insular cognitive-control activation, @Rubia2014StimulantBrainMeta) is not yet fully reconciled in ME/CFS — see @oq:stimulant-arousal-vs-cognitive-control.], certainty: [Medium — large cross-sectional discovery sample (n=337 on-stimulant) plus a small independent challenge (n=5) @Kay2025stimulantarousalreward, read through ME/CFS adrenergic-dysfunction evidence @Hendrix2025AdrenergicDysfunction; downgraded because the causal arm is small, the network finding is associational, the ME/CFS mapping is an inference not directly tested, and no ME/CFS-cohort study tests the dissociation.], action: [do not conclude "attention deficit"; probe which system responded (wakefulness gain vs drive gain) before choosing the next drug.], level: [Symptom management.])

#finding(claim: [Non-response does not rule out catecholamine insufficiency], explanation: [The stimulants act on a catecholamine inverted-U: benefit appears within a dose window and inverts above it @sec:hormetic-dose-range-reference. A null at one dose is a statement about that dose, not the drug — both too little and too much can fail. A null also does not distinguish a postsynaptic receptor lesion (@sec:noradrenergic-node) from a presynaptic deficit (@ach:catecholamine-deficit).], certainty: [Medium — dose-response principle well established; ME/CFS-specific dose-ranging data sparse.], action: [only conclude non-response after a dose-range trial with objective monitoring, not a single-dose null.], level: [Symptom management.])

===== Side-effect signature of the stimulant response

The side-effect profile tells you which system is intact, separately from what the therapeutic response tells you is broken (patterns after @sec:side-effects-diagnostic).

- *Tachycardia or raised BP at a low noradrenergic dose → peripheral noradrenergic system intact and at critical margin* (Pattern 1/4). This is hyperadrenergic POTS until proven otherwise @sec:pots-cascade.
- *Insomnia at a low modafinil or pitolisant dose → orexin/histamine arousal axis intact and hypersensitive* (Pattern 4). The system is turned off at baseline, not broken @sec:microglial-cascade K2a — an arousal-selective probe is well chosen.
- *Severe post-dose crash on amphetamines → VMAT2 terminal compromise* (presynaptic store depletion), not merely low synaptic tone.
- *No tachycardia, no BP rise, and no alertness change at an adequate noradrenergic dose → central noradrenergic arousal non-functional or desensitized* (Pattern 5). This is a genuine exclusion signal @ach:catecholamine-deficit.
- *No insomnia and no benefit from modafinil/pitolisant → DAT/histaminergic arousal transduction non-functional* (absent, autoantibody-blocked, or saturated) — all DAT-targeting strategies are futile (Pattern 5).
- *Wakefulness improves but drive does not → the reward-effort salience system, not the arousal system, is the non-responding node* — points toward an arousal-limited subtype.

===== Root cause candidates the response does not resolve

A positive stimulant response narrows the proximal node, not the root cause. Warranted upstream candidates: (1) neuroinflammatory precursor depletion of catecholamines with microglial priming (@sec:microglial-cascade); (2) metabolic/ATP constraint on DBH-dependent vesicular packaging — selective noradrenergic deficiency (@ach:catecholamine-deficit, @sec:nad-cascade); (3) cerebral energy failure of the prefrontal/arousal substrate (@sec:brain-energy-cross-disease, @sec:cns-energy-triage-clinical); (4) adenosinergic/histaminergic/orexin arousal suppression (@sec:microglial-cascade K2a); (5) dopaminergic terminal/effort-valuation loss on the reward-effort arm (@spec:motivation-trap, @sec:dopamine-convergence). These remain indistinguishable from a stimulant response alone.

===== Overall inference certainty

*Medium.* The downstream claim — a stimulant response indexes low arousal and/or low reward-effort salience rather than low attention capacity — rests on very large human samples with an independent controlled challenge @Kay2025stimulantarousalreward, convergent with meta-analytic nulls in rested adults @Ilieva2015StimulantMetaAnalysis @Roberts2020CognitiveEnhancementMeta. It is downgraded from High because the causal arm is small (n=5), the discovery arm is cross-sectional, a *lack of* ME/CFS-cohort study tests the arousal/reward dissociation, and the ME/CFS evidence base is dominated by small or uncontrolled studies @Blockmans2006MPHCFS @Randall2005modafinil @Eckey2025PatientReported. The two-system subtype split is *Low* certainty — hypothesis-generating only (@spec:stimulant-endophenotypes-arousal-reward).

#synthesis(title: [Stimulants as arousal/reward probes, not attention tests])[
Convergent human evidence associates the therapeutic action of stimulants with arousal and reward-salience networks rather than attention-control networks @Kay2025stimulantarousalreward, with limited objective cognitive enhancement in rested adults @Ilieva2015StimulantMetaAnalysis @Roberts2020CognitiveEnhancementMeta and effort-invigoration occurring without ability gains @Chong2023AmphetamineMotivation @Bowman2023NotSoSmart. Read through ME/CFS, this makes a positive response better read as an arousal/reward-effort signal than as proof of a broken attention system (@spec:stimulant-arousal-reward-not-attention), and it explains why subjective improvement can occur without capacity gain. Because the two systems are correlated rather than demonstrated-separable, a response may fractionate into arousal-deficient and reward-effort-deficient subtypes (@spec:stimulant-endophenotypes-arousal-reward) — but that split is hypothesis-generating, lacks an independent classifier, no ME/CFS cohort has tested it, and a right-IFG/insula cognitive-control account remains an unresolved competitor @oq:stimulant-arousal-vs-cognitive-control. The central unanswered question is which of these signals a positive stimulant response actually carries in ME/CFS patients — and whether the attention-capacity null even applies to an energy-depleted brain. *Consequence:* stimulants may be useful probes of whether a patient's problem is feeling awake or feeling motivated, but they are not evidence of an attention defect — and that same mechanism can let patients feel better while they overexert.
] <syn:kay-stimulant-arousal-reward-probe>

==== Compendium

The full pharmacodiagnostic entries — including mechanism-exclusion logic, dose-specific side-effect diagnostic patterns, combination diagnostics, and worsening risk profiles — are at @ch:mechanistic-cascade-tracing (sec-12, Methylphenidate entry, Modafinil/Armodafinil entry, and related stimulant entries).


