#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Shared Central Genetic Architecture May Underlie the ME/CFS-Fibromyalgia Comorbidity])[
*Certainty: 0.52.* The largest fibromyalgia GWAS (Kerrebijn 2026, _Nature Medicine_, 2.56 million individuals) found heritability exclusively enriched in brain/neural cell types — consistent with, but not proof of, a central-nervous-system (nociplastic) role for fibromyalgia @Kerrebijn2026FibromyalgiaGWAS. This parallels the brain-enriched genetic architecture independently established for ME/CFS by DecodeME and the Maccallini meta-GWAS @DecodeME2025 @Maccallini2026metaGWAS. The convergence of both conditions on central (brain/neural) genetic architecture is consistent with the comorbidity reflecting a partially shared central genetic vulnerability; however, the fibromyalgia-ME/CFS co-occurrence figure is inflated by overlapping diagnostic criteria (Wolfe 2016), so it cannot by itself establish shared biology — the decisive test is a direct fibromyalgia × ME/CFS genetic correlation, which is untested (see Chapter @ch:genetics-epigenetics, Section @sec:kerrebijn-fibromyalgia-gwas; Open Question @oq:fm-mecfs-genetic-correlation-untested). This is a cross-reference to the detailed ch14 analysis, not an independent claim.

*Falsifiable predictions:* (1) A direct cross-trait analysis of fibromyalgia and ME/CFS GWAS will find significant positive genetic correlation. (2) Fibromyalgia PRS will be elevated in ME/CFS patients with comorbid fibromyalgia relative to those without. Falsified if the two conditions show near-zero genetic correlation despite clinical overlap.

*Consequence:* If confirmed, a shared central genetic vulnerability would make central-sensitization mechanisms a research priority to test across both conditions — but genetic architecture does not by itself determine which treatment modality is effective, so this is a research direction, not a current change to how the comorbid patient is managed. (Severity applicability: unknown — GWAS cohorts not stratified by ME/CFS severity.)
] <hyp:shared-central-genetic-architecture-fibro-mecfs>
