#import "../../../../shared/environments.typ": *

===== Cascade: Time-dependent hormetic windows — why pulsing preserves therapeutic optima

*Trigger:* The existing LDN cascade traces dose-response curves (Steps M1–M4) but does not address the temporal dimension of those curves. The time-dependent hormesis literature (Calabrese corpus: @Sun2018SeesawHormesis @Mushak2016TemporalHormesis @Calabrese2016PreconditioningHormesis) and GPCR resensitization kinetics (@CostaNeto2025GPCRTachyphylaxis @Gupta2018GPCRResensitization @Kliewer2017GPCRDephosph) jointly establish that the therapeutic window is a 3D volume (dose × time × response) — and that continuous daily dosing may extinguish it by filling the resensitization interval that the pathway requires.

*Overall falsification condition:* A prospective pulsed-vs-continuous dosing trial for at least one Nrf2-activating drug (sulforaphane, NAC, or melatonin) in ME/CFS must show superior maintenance of benefit at 12 weeks in the pulsed arm compared to the continuous arm. Falsified if no difference AND GPCR dephosphorylation half-life data for the relevant target confirm that the off-period is shorter than the half-life — i.e., the pulsing interval was too short to allow resensitization.

*Cascade:*
- Step T1 (Nrf2 extinguishment): Continuous Nrf2 activator dosing → tonic Keap1 cysteine oxidation → Nrf2/ARE transcriptional programme maintained → Nrf2 adaptive response desensitizes → protective gene expression declines despite continued drug presence
- Step T2 (GPCR resensitization blockade): Continuous agonist/receptor occupancy → receptors internalize in desensitized state → drug-free interval absent → dephosphorylation/recycling never occurs → receptor population shifts toward desensitized pool → tachyphylaxis
- Step T3 (Differential off-rate principle): Therapeutic target and adverse target have different dephosphorylation half-lives → intermittent dosing allows adverse receptor to resensitize during pause while therapeutic receptor remains modulated → therapeutic window maintained
- Step T4 (Oxidative stress amplification): High basal oxidative tone → ROS-mediated receptor oxidation accelerates desensitization → tachyphylaxis onset faster in ME/CFS than in general population → pulsed dosing more important in sicker patients

*Step T1:* Nrf2 adaptive response desensitization under continuous activator dosing
- *Mechanism:* The Keap1-Nrf2-ARE pathway is adaptive — it evolved to detect *transient* stress signals and mount a time-limited protective response. Under continuous activation (daily sulforaphane, NAC, or melatonin), the sensor desensitizes: Nrf2 protein half-life shortens, ARE-driven transcription saturates, and the anti-inflammatory gene programme plateaus or declines despite continued drug presence. This is distinct from the dose-dependent collapse described in Step M1 — here, the dose is correct (below 3.0 mg LDN) but the *timing* is wrong. The cell adapts to the chronic signal and downregulates its response. @Son2008HormeticPhytochemicals @Calabrese2016PreconditioningHormesis
- *Intercept:* If a patient loses benefit on an Nrf2 activator after weeks of daily dosing despite maintaining the correct dose, and benefit returns after a 2–3 day drug holiday → Nrf2 adaptive desensitization, not dose mismatch. The drug holiday serves as a resensitization interval.
- *Diagnostic:* Loss of benefit at unchanged dose over time NOT accompanied by worsening → adaptive desensitization (reversible). Loss of benefit at the SAME time across multiple dose escalations → dose-dependent extinction (Step M1). Loss of benefit that is permanent after discontinuation → irreversible desensitization or disease progression (exceeds this framework).
- *If a 2–3 day drug holiday restores benefit:* The cell's Nrf2 machinery can resensitize. Intermittent dosing (e.g., 5 days on / 2 days off, or every other day) would preserve the therapeutic window. Certainty: 0.25 — Nrf2 adaptive desensitization is documented in vitro; no clinical trial has tested pulsed Nrf2 activator dosing in any condition.
- *If a drug holiday does NOT restore benefit:* Either (a) the off-period was too short for Nrf2 resensitization, (b) the mechanism of benefit was not Nrf2-dependent (and tachyphylaxis is from a different pathway), or (c) the disease has progressed beyond the window where Nrf2 activation can compensate. Certainty: 0.20.

*Step T2:* GPCR resensitization blockade — the receptor-level mechanism
- *Mechanism:* GPCRs follow a conserved cycle: agonist binding → G protein activation → GRK phosphorylation → β-arrestin recruitment → receptor internalization → endosomal dephosphorylation by protein phosphatases → recycling to membrane (Gupta 2018, Kliewer 2017). Continuous receptor occupancy by a daily agonist blocks the dephosphorylation step: internalized receptors remain arrested in endosomes, unable to recycle to the membrane in a drug-naive state. The receptor population shifts from a drug-responsive surface pool to a desensitized internal pool. The critical parameter is the dephosphorylation half-life — if the drug-free interval is shorter than this half-life, resensitization never occurs. @Gupta2018GPCRResensitization @Kliewer2017GPCRDephosph
- *Intercept:* Drugs whose therapeutic target is a GPCR (all catecholamine cluster drugs: modafinil/DAT, duloxetine/NET, beta-blockers/β1/β2, guanfacine/α2A, LDA/D2) are susceptible to GPCR resensitization blockade with continuous daily dosing. The resensitization half-life of each receptor determines whether "drug holidays" are feasible: half-life under 6 hours → overnight pause sufficient; half-life 6–24 hours → weekend holidays viable; half-life above 24 hours → prolonged holidays required, high withdrawal risk.
- *Diagnostic:* If benefit from a catecholamine-cluster drug declines over weeks at a stable dose, and a 1–2 day drug holiday restores benefit → GPCR resensitization blockade (reversible). If a drug holiday does NOT restore benefit AND the receptor has a known short dephosphorylation half-life (below 6 hours) → the mechanism is not GPCR desensitization.
- *If β-blocker benefit declines at a stable dose and a weekend drug holiday restores it:* β1 receptor dephosphorylation half-life is ~4 hours → off-period was adequate for resensitization. Pulsed dosing (5 days on / 2 days off) would maintain benefit without dose escalation. Certainty: 0.20 — GPCR resensitization kinetics are well-established in vitro but have not been translated to clinical dosing trials in ME/CFS.
- *Off-target confound:* Drug holidays may produce withdrawal or rebound in susceptible patients (Hodding 1980). Beta-blocker withdrawal can cause tachycardia and sympathetic overactivity — the drug holiday that restores receptor sensitivity is the same interval that triggers withdrawal symptoms. This is a genuine tension in the framework: the resensitization interval and the withdrawal risk interval overlap. Agents with low withdrawal risk (modafinil, guanfacine) are better candidates for pulsed dosing than agents with high withdrawal risk (beta-blockers, corticosteroids). @Hodding1980DrugWithdrawal

*Step T3:* Differential off-rate principle — rapamycin as paradigm
- *Mechanism:* Rapamycin binds FKBP12, and the FKBP12-rapamycin complex inhibits mTORC1 with high affinity and mTORC2 with lower affinity. After a single dose, mTORC1 inhibition persists for days (slow dissociation from FKBP12-mTORC1), while mTORC2 inhibition resolves faster. Intermittent dosing (every 5 days) exploits this differential: mTORC1 remains suppressed throughout the interval, but mTORC2 recovers between doses, preserving insulin sensitivity and immune function that continuous daily dosing impairs. @ArriolaApelo2016RapamycinIntermittent @Konopka2023RapamycinTherapeutic
- *Intercept:* Intermittent rapamycin dosing (1–3 mg/week) preserves the therapeutic:mTORC2 adverse effect ratio observed in preclinical studies. Continuous daily dosing (reported in organ transplant protocols) produces immunosuppression and metabolic syndrome that intermittent dosing avoids.
- *Diagnostic:* If a patient tolerates weekly rapamycin but develops metabolic side effects on daily dosing → mTORC2 recovery during the off-period was preventing adverse effects. The therapeutic window is temporal, not dose-dependent — reducing the daily dose would not reproduce the benefit of intermittent dosing.
- *Generalization principle:* The differential off-rate model applies to any drug with dual targets that have different temporal recovery kinetics. Candidates include: corticosteroids (therapeutic GR modulation recovers faster than HPA axis suppression?), H1 antihistamines (peripheral H1 recovers faster than CNS H1?), DORAs (partial orexin blockade kinetics vs complete blockade). Each is a testable hypothesis; none has been tested.

*Step T4:* Oxidative stress amplification of tachyphylaxis — ME/CFS-specific vulnerability
- *Mechanism:* ROS generated by receptor activation can oxidize receptor cysteine residues, producing distinct functional outcomes — including accelerated desensitization that is independent of the canonical β-arrestin pathway @Teyani2024Beta2Tachyphylaxis. In healthy tissue, antioxidant defences clear these ROS before they oxidize the receptor. In ME/CFS, where baseline oxidative stress is elevated (documented across glutathione, SOD, lipid peroxidation, and isoprostane studies), receptor-level ROS may accumulate faster, accelerating tachyphylaxis. This creates a self-reinforcing loop: oxidative stress → faster receptor desensitization → reduced drug efficacy → symptom worsening → increased oxidative stress.
- *Intercept:* ME/CFS patients with the highest oxidative stress biomarkers (low GSH, high 8-isoprostane, high TBARS) may be the fastest to tachyphylax and the most in need of pulsed dosing strategies. This is a mechanistic prediction — the oxidative stress → tachyphylaxis link has been demonstrated for β2-adrenergic receptors in airway disease but not tested in ME/CFS for any receptor class.
- *Diagnostic:* If a patient with objectively elevated oxidative stress loses drug benefit faster than predicted by receptor pharmacology alone → ROS-mediated receptor oxidation may be contributing. Pulsed dosing reduces cumulative ROS exposure at the receptor — testing this prediction requires a head-to-head pulsed vs continuous trial with oxidative stress biomarkers as covariates.
- *Consequence:* If oxidative stress accelerates tachyphylaxis in ME/CFS, then the same drug at the same dose benefits a patient with low oxidative burden for months but a patient with high oxidative burden for only weeks. This would make oxidative stress a predictor of pulsing need — patients above a threshold benefit from intermittent dosing; patients below can maintain on continuous dosing. Certainty: 0.15 — ROS-mediated receptor tachyphylaxis is documented for one receptor class (β2AR) in airway disease; generalization to ME/CFS drug targets is speculative.

*Cascade resolution:* The dose-response curve is a 3D volume, not a 2D function. Time is the missing axis in the existing hormesis framework. For any drug whose therapeutic mechanism is hormetic (Nrf2 cluster) or GPCR-mediated (catecholamine cluster, LDA), the question is not just "what dose?" but "at what interval?" The resensitization clock is receptor-specific, and the optimal pulsing interval is the minimum off-period that allows the therapeutic receptor to resensitize without triggering withdrawal at the adverse receptor. This framework classifies drugs by resensitization kinetics and withdrawal risk — it is a scaffold for empirical testing, not a dosing algorithm.

*Consequence:* Pulsed dosing is not a fringe strategy — it is the logical consequence of taking GPCR resensitization kinetics and time-dependent hormesis seriously as pharmacological principles. The framework predicts that some ME/CFS patients who report "the drug stopped working after a few months" have not developed true tolerance but have filled the resensitization interval through continuous daily dosing. If a 2–3 day drug holiday restores benefit, the mechanism was adaptive desensitization, not disease progression. This is a testable, actionable, zero-cost intervention: stop the drug temporarily before concluding it has failed.
