#import "../../../../shared/environments.typ": *

=== NET Degradation and DNase Activity as Candidate Post-Viral Biomarkers
<sec:net-dnase-biomarker>

NET degradation capacity—the balance between NET production and DNase-mediated NET clearance—has emerged from COVID-19 research as a potential post-viral biomarker with direct relevance to ME/CFS. Garcia et al. @GarciaLabroucheColomer2024 demonstrated that the ratio of NET markers (MPO-DNA, H3cit, H3cit-DNA) to functional DNase activity was markedly elevated in severe and critical COVID-19 patients and correlated with CRP and neutrophil/lymphocyte ratio—standard clinical severity markers. Crucially, H3cit and H3cit-DNA levels predicted hospitalisation among ambulatory patients, suggesting NET/DNase imbalance is an early rather than late feature of severe disease @GarciaLabroucheColomer2024.
*Assay components.* A clinically applicable NET degradation panel would measure: (1) NET remnants (MPO-DNA complexes, citrullinated histone H3) by ELISA; (2) functional DNase activity by residual dsDNA degradation assay; (3) NET/DNase ratio as an integrated imbalance metric; and optionally (4) DNase1 and DNase1L3 antigen levels to distinguish enzymatic deficiency from consumption. The Garcia functional DNase assay—measuring residual dsDNA after plasma incubation—provides a scalable, quantitative method suitable for large cohorts that avoids the technical demands of zymography or continuous fluorometric kinetic assays @GarciaLabroucheColomer2024. Complementary calprotectin (S100A8/S100A9) measurement offers a clinically accessible proxy for NET burden ($r >= 0.745$ with H3-NET levels) @Hetland2022.
*ME/CFS applicability.* No study has measured NET remnants, DNase activity, or NET/DNase ratios in ME/CFS patients. This is a notable gap given that: (a) ME/CFS shares thrombo-inflammatory features with long COVID; (b) herpesviruses implicated in ME/CFS triggering (EBV, CMV) are established NETosis inducers @Schonrich2016; (c) ME/CFS patients have documented neutrophil dysfunction that may include defective NET clearance; and (d) NET/DNase imbalance is genetically influenced via _DNASE1_ polymorphisms, providing a testable genetic susceptibility hypothesis (Chapter @ch:genetics-epigenetics). The NET/DNase ratio could serve as a post-viral stratification biomarker distinguishing patients with ongoing thrombo-inflammatory NET pathology from those with predominantly metabolic or neurological phenotypes.
*Technical precedent.* The Garcia et al. assay was applied to n=145 COVID-19 patients across three severity strata with robust statistical adjustment (age, sex, BMI) @GarciaLabroucheColomer2024. The key challenge for ME/CFS application is the lower expected NET burden in chronic post-viral compared to acute severe infection, requiring high assay sensitivity and potentially enrichment for patients with recent symptom exacerbation or known thrombo-inflammatory features.


