#import "../../../shared/environments.typ": *

== Connective Tissue Subsystem Extensions

#proposal(title: [Multi-Compartment ECM Turnover Model with Tissue-Specific Parameters])[
The integrated model treats connective tissue as a single uniform compartment, yet clinical observations in ME/CFS with hEDS show differential symptom patterns across tissue types (vascular fragility, cervical ligament instability, joint hypermobility, skin extensibility). A multi-compartment ECM model captures this heterogeneity by assigning tissue-specific turnover rates and coupling strengths to four key compartments: vascular ($"ECM_vas"$), cervical ligament ($"ECM_cerv"$), tendon ($"ECM_tend"$), and dermal ($"ECM_derm"$). Each compartment follows coupled dynamics:

$
frac(d ["ECM_i"], d t) = k_"ECM,synth"^i - k_"ECM,deg"^i dot.op ["MMP_i"] dot.op ["ECM_i"], quad i in {"vas", "cerv", "tend", "derm"}
$

where synthesis rates $k_"ECM,synth"^i$ and MMP-dependent degradation rates $k_"ECM,deg"^i$ vary by tissue. Vascular ECM has the fastest turnover (hours to days) and is most sensitive to inflammatory MMP induction; cervical ligaments have the slowest turnover (months to years) and are most vulnerable to cumulative strain accumulation; tendons have intermediate turnover; dermal ECM is moderately fast with distinct collagen type ratios. The MMP activity $"MMP_i"$ in each compartment responds to both systemic signals (IL-6, TNF-α from the cytokine network) and local stimuli (mechanical strain $sigma_i$, mast cell activation $"MC_d"$):

$
"MMP_i" = "MMP_0" dot.op (1 + alpha_"inf" dot.op ["IL-6"] + alpha_i_"strain" dot.op sigma_i + alpha_i_"MC" dot.op "MC_d")
$

The tissue-specific strain coefficients $alpha_i_"strain"$ reflect differing mechanotransduction sensitivity: cervical ligaments are highly strain-sensitive (high $alpha_"cerv"^"strain"$) and accumulate MMP under minor orthostatic stress, explaining POTS exacerbation in hEDS patients; tendons respond to activity-related strain; vascular ECM responds to shear stress and pulsatile pressure. Mast cell coupling $alpha_i^"MC"$ varies by tissue density: gut mucosa has high mast cell density and high coupling, driving SIBO-mediated ECM degradation. The model predicts that symptom clusters correlate with dominant compartments: patients with dominant vascular ECM instability present with orthostatic intolerance and syncope; cervical ligament dominance presents with neck pain, headaches, and dysautonomia; tendon dominance presents with joint instability and dislocations; dermal dominance presents with skin extensibility and wound healing deficits. Treatment strategies can be compartment-targeted: strengthening cervical support (physical therapy for deep neck flexors) reduces $sigma_"cerv"$ and MMP activation in that compartment; beta-blockers reduce pulsatile pressure on vascular ECM; mast cell stabilizers reduce $alpha_i^"MC"$ across compartments.

*Certainty: 0.45.* Tissue-specific ECM turnover rates are well-established in connective tissue biology, and the differential clinical presentation in hEDS is documented. The novel application to ME/CFS symptom patterning requires validation that: (1) ME/CFS patients with different symptom clusters show corresponding differences in ECM turnover markers (e.g., collagen degradation products specific to each tissue type); (2) compartment-specific MMP activity can be measured non-invasively (e.g., imaging biomarkers for vascular ECM stiffness); and (3) interventions targeting specific compartments produce the predicted symptom-selective improvements. The cross-compartment coupling via systemic inflammation and mast cell activation suggests that effective treatment requires addressing both local strain drivers and systemic amplifiers.
]

#proposal(title: [Cross-Reference: HIF-1alpha-Mitochondria-ECM Triad Integration])[
The HIF-1alpha-ECM coupled differential equations proposed in Chapter @ch:energy-metabolism-models extend the energy metabolism model with hypoxia sensing and connective tissue degradation. This triadic coupling---HIF-1alpha induction by ROS, ECM degradation via HIF-1alpha-mediated MMP induction, and impaired energy production from reduced perfusion due to ECM degradation---creates a slow positive feedback loop operating on timescales of weeks to months. The loop architecture mirrors the energy--immune vicious loop (Section @sec:energy-immune-coupling) but with distinct timescales and tissue specificity: the energy--immune loop operates over hours to days and affects systemic inflammation, while the HIF-1alpha-ECM loop operates over weeks to months and produces structural tissue changes. This dual-loop structure predicts a "two-stage" progression model: early ME/CFS is dominated by the energy--immune loop (symptom flares, PEM, relapses), while late ME/CFS incorporates the HIF-1alpha-ECM loop (connective tissue degradation, vascular compliance changes, progressive symptom consolidation). The transition between stages depends on cumulative ROS exposure and ECM quality trajectories, which can be modeled by extending the damage accumulation equation (@eq:damage-accumulation) to include an ECM damage component with slower repair kinetics. Interventions targeting HIF-1alpha stabilization (e.g., PHD activators) or ECM repair (specific collagen support) may be particularly relevant in late-stage disease where the structural loop is dominant, whereas early-stage disease may respond more to energy--immune cycle disruption (e.g., immunomodulation, mitochondrial support). This stage-specific treatment strategy emerges from the coupled multi-timescale model and is not apparent when considering either loop in isolation.

*Certainty: 0.45.* The HIF-1alpha-ECM coupling mechanism is biochemically validated in tendinopathy and other connective tissue disorders @Moschini2026HIFTendinopathy. The application to ME/CFS disease staging requires validation that: (1) ME/CFS patients show elevated HIF-1alpha and ECM degradation markers relative to healthy controls; (2) the temporal pattern of these markers (slow increase over months) differs from inflammatory markers (fast fluctuations over hours to days); and (3) clinical severity correlates more strongly with ECM markers in late-stage disease and with inflammatory markers in early-stage disease. If confirmed, the HIF-1alpha-ECM loop would explain why ME/CFS tends to worsen over time despite apparent symptom stability: slow structural degradation accumulates beneath the surface of fluctuating acute symptoms.
]

#include "subsec-01-neuroimmune-integration-gpcr-autoantibody-and-vagal-cap-exte/subsec-01-neuroimmune-integration-gpcr-autoantibody-and-vagal-cap-exte.typ"
