#import "../../../../shared/environments.typ": *

=== Research Gaps at Step 9


Six gaps at Step 9, all concerning the mitochondrial antioxidant machinery: (G33) PRDX3 expression in ME/CFS patient tissue (PRDX3-KO mice phenotypically resemble ME/CFS); (G34) NRF2 pathway activation status; (G35) thioredoxin / thioredoxin reductase (TRX/TXNRD) system; (G36) GPX4 lipid-peroxidation surveillance; (G37) direct muscle F2-isoprostanes (the gold-standard lipid peroxidation biomarker); (G38) mitochondrial glutathione (mGSH) pool.

#figure(
  kind: table,
  caption: [Step 9 (ROS scavenging) research gap prioritization. Step 9 is net-negative for ATP; failure is amplificatory, propagating damage to Steps 3, 5, 6, 7.],
  table(
    columns: (auto, auto, auto, auto, auto, auto, auto),
    align: (left, left, left, left, left, left, center),
    table.header([*Gap*], [*Essentiality*], [*Worst-case impact*], [*Tractability*], [*Therapeutic leverage*], [*Measurement*], [*Priority*]),
    [G33: PRDX3 expression], [High — secondary H#sub[2]O#sub[2] scavenger downstream of MnSOD; Prdx3-KO mice show reduced mtDNA content, reduced ATP, impaired mitochondrial fusion, and diminished exercise endurance @Lee2020prdxKO (phenotype shared with many mitochondrial conditions, not ME/CFS-specific); Sonn et al.\ showed in cardiac tissue that PRDX3 protects PINK1 from OMA1-mediated degradation — PRDX3 loss impairs mitophagy @Sonn2022prdx3cardiac (tissue context may differ in skeletal muscle)], [Indirect: amplifies aconitase, Complex I, cardiolipin damage; additionally impairs mitophagy via PINK1 destabilization], [Hard — muscle biopsy Western or IHC], [Long-term], [Muscle biopsy (Western or IHC)], [2],
    [G34: NRF2 pathway (master antioxidant regulator)], [High — upregulates MnSOD, GPX1, catalase, thioredoxin, HO-1 simultaneously; but each target also has NRF2-independent regulation], [Indirect but widespread; directionality unknown (suppressed vs compensatorily activated)], [Moderate — NRF2 target mRNA panel in PBMCs (NQO1, HO-1, GCLC); not available through standard clinical labs], [Research-stage — sulforaphane, dimethyl fumarate (requires lymphocyte monitoring), omaveloxolone (hepatic monitoring); premature pending NRF2 measurement], [Blood draw (PBMC qPCR/RNA-seq; research lab, not standard clinical)], [1],
    [G35: Thioredoxin / TXNRD system], [High — parallel to GSH as a major redox buffer; TXN transcript elevated in male Long COVID patients (Shankar 2025 ) but TXNRD1/2 protein and activity unmeasured], [Indirect; could mask or worsen G33], [Moderate — erythrocyte TXNRD activity is available], [Long-term], [Blood draw (erythrocyte TXNRD activity)], [2],
    [G36: GPX4 lipid peroxidation surveillance], [High — sole enzyme preventing ferroptotic membrane damage; GPX4 protein _elevated_ 1.9× in ME/CFS lymphocytes (Shankar 2025, compensatory response)  — but enzymatic activity, tissue-specific data (muscle/brain), and ferroptosis markers (ACSL4, 4-HNE) remain unmeasured], [Indirect; links to cardiolipin peroxidation (@spec:cardiolipin-peroxidation)], [Moderate — lymphocyte data exist; remaining work is activity assay and tissue-specific replication], [Near-term — selenium, vitamin E, CoQ10], [Blood draw (PBMC data exist); muscle biopsy for tissue-specific], [1],
    [G37: Muscle F2-isoprostanes], [Plasma F2-isoprostanes _established_ as elevated in CFS: Kennedy 2005 ($n = 47$ vs 34, correlated with PEM in low-cardiovascular-risk subgroup, $p = 0.027$, cross-sectional) @Kennedy2005isoprostanes and Robinson 2010 ($n = 33$ vs 33, elevated at rest and persisting 24h post-exercise) @Robinson2010isoprostanes — muscle-specific measurement remains genuinely open], [Objective quantification of tissue-level ROS-damage state], [Moderate — LC-MS assay available; muscle biopsy required for tissue-specific data], [Immediate — baseline and response-to-intervention marker], [Blood draw (plasma LC-MS); muscle biopsy for tissue-specific], [1],
    [G38: Mitochondrial glutathione pool (mGSH)], [High — the cytosolic GSH compartment is not equivalent; mGSH is separately regulated], [Direct on ROS scavenging capacity], [Hard — requires subcellular fractionation from biopsy], [Immediate — NAC, GSH precursors already in use], [Muscle biopsy (subcellular fractionation)], [2],
  )
) <tab:step9-gap-priorities>

G34 (NRF2 pathway) and G37 (F2-isoprostanes) are priority 1 because they are tractable PBMC/plasma assays with immediately actionable interventions (sulforaphane, dimethyl fumarate; antioxidant dose-titration). G34 is notable because downstream NRF2 targets are documented as abnormal (Shankar 2025: reduced MnSOD protein, GPX4-mediated lipid peroxidation ), a review has identified NRF2 inhibition as a candidate contributor @Davis2025nrf2lipid, yet the regulator itself has not been measured. The NRF2 target mRNA panel (NQO1, HO-1, GCLC) in PBMCs is a well-established assay requiring only a blood draw. The Long COVID bridge adds plausibility: Morris et al.\ showed that SARS-CoV-2 directly suppresses NRF2 protein and NRF2-dependent gene expression @Morris2023nrf2covid, raising the possibility that post-viral NRF2 suppression persists into ME/CFS. However, reduced downstream targets are also consistent with compensatory NRF2 _upregulation_ overwhelmed by oxidative demand (see Step 9 discussion above); the measurement would resolve directionality. G36 (GPX4) is priority 1 because it connects directly to cardiolipin peroxidation (@spec:cardiolipin-peroxidation) and is already partially characterized by Shankar 2025 — the remaining work is replication. Step 9 as a whole is _amplificatory_ rather than stoichiometric: its failure does not reduce per-cycle ATP output but accelerates damage to every other step, which is why antioxidant-targeted interventions have the potential for non-linear benefit once the primary ROS source is identified.

#speculation(title: [The Itaconate--NRF2 Paradox: NRF2 May Be Activated But Functionally Overwhelmed])[
*Certainty: 0.30 (conditional on itaconate shunt being active in ME/CFS, which itself remains unconfirmed; unconditional certainty is lower).* Itaconate is a direct, potent NRF2 activator: 4-octyl-itaconate alkylates KEAP1 at Cys151, releasing NRF2 for nuclear translocation. If the metabolic safe mode model is correct and itaconate shunt activation is present in ME/CFS, then NRF2 _should already be activated_ by itaconate-mediated KEAP1 modification. Yet downstream NRF2 targets are depleted (Shankar 2025: reduced MnSOD ). This creates a paradox: the problem may not be NRF2 _suppression_ but rather NRF2 activation that is _functionally overwhelmed_ by oxidative demand. Three sub-hypotheses: (a) NRF2 is nuclear and transcriptionally active, but antioxidant enzyme proteins are consumed faster than they can be synthesized; (b) NRF2 target gene promoters (NQO1, GCLC, HMOX1) are epigenetically silenced, preventing transcription despite nuclear NRF2; (c) chronic stress selects for NRF2 splice variants (e.g., NRF2-$Delta$Neh2) with reduced transactivation capacity. These three interpretations have opposite therapeutic implications: if (a), adding NRF2 activators (sulforaphane) would be futile and the correct intervention is reducing oxidative demand (MitoQ, elamipretide); if (b), epigenetic modifiers would be needed; if (c), the NRF2 pathway itself requires isoform-specific targeting. The G34 measurement protocol should therefore include not just NRF2 protein and nuclear localization but also NRF2 target mRNA levels, promoter methylation status, and NRF2 isoform profiling.

This paradox connects to G39 (PGC-1$alpha$) via the NRF2--PGC-1$alpha$ bidirectional circuit: PGC-1$alpha$ co-activates NRF2 transcription, and NRF2 induces PGC-1$alpha$ expression. In ME/CFS, both arms may be simultaneously impaired — PGC-1$alpha$ hyperacetylated (G39) and NRF2 overwhelmed (G34) — creating a broken hormetic loop. In healthy individuals, exercise generates a brief ROS pulse that activates NRF2, which cooperates with PGC-1$alpha$ to drive both antioxidant defense and mitochondrial biogenesis (mitohormesis). In ME/CFS, this loop is broken at every node: exercise is contraindicated (PEM), AMPK is impaired @Brown2018AMPK, PGC-1$alpha$ cannot be deacetylated (impaired SIRT1), and even if NRF2 is activated, the transcriptional programme is overwhelmed. The patient cannot exercise to activate hormesis, cannot activate PGC-1$alpha$ pharmacologically without AMPK, and the resulting antioxidant deficit makes any subsequent exercise more damaging — a self-reinforcing trap.

*Testable prediction:* NRF2 nuclear protein in ME/CFS PBMCs will be normal or _elevated_ (not reduced); NQO1/HO-1 mRNA may be elevated; but the corresponding protein levels will be disproportionately low relative to mRNA (indicating post-transcriptional failure or excessive protein turnover). Falsified if NRF2 nuclear protein is genuinely reduced, consistent with simple suppression.
] <spec:itaconate-nrf2-paradox>

