#import "../../../shared/environments.typ": *

#limitation(title: [Expert Caution on Off-Label Drugs: "Little or No Benefit, More Likely Adverse Effects"])[
The chapter's protocol content above is substantially more optimistic about off-label symptomatic drugs than a major severe-ME/CFS clinical-advocacy source. The Science for ME (2026) factsheet, authored by Prof. Jonathan Edwards and S4ME members, states that several drugs widely prescribed for ME/CFS "based on weak theoretical evidence and anecdotal clinical experience" — it explicitly lists antihistamines, naltrexone, fludrocortisone, and ivabradine — "probably produce little or no benefit and are more likely to produce adverse effects," even though several are now undergoing formal trials partly due to the emergence of Long COVID @S4ME2026ManagementSevereVerySevere. (The factsheet does not address other off-label drugs the chapter discusses, such as ketotifen and cromolyn; this caution applies specifically to its four listed agents.)

This is a genuine unresolved tension. The corpus's favourable LDN data (e.g., 73.9% reported response in an observational cohort @Polo2019) and mast-cell medication support coexist with serious-safety and null-evidence entries in the wider literature (e.g., @Bolton2019NaltrexoneSAE) and now with this explicit expert caution. The factsheet's position is that the evidence base for these drugs is weak-theoretical and anecdotal and that adverse effects are more likely than benefit. Neither side is a severe-ME/CFS-specific RCT, which does not exist for any of these drugs. (Certainty: 0.40 — expert-consensus/advocacy caution set against observational cohort data; no severe-ME/CFS RCT for any listed drug. Severity applicability: severe/very-severe, where adverse effects may be least tolerated.)

*Consequence:* Prescribers should treat the favourable observational reports and the explicit expert caution as two poles of an unresolved question: an off-label drug may help an individual (observational response data) yet on balance show little group benefit and real adverse-effect risk. This argues for conservative, individually-monitored, clearly time-limited trials with explicit stopping criteria — not either blanket dismissal or unqualified enthusiasm. Where a drug's use is diagnostic (a trial that reveals mechanism by its response or non-response), that purpose is distinct from and not refuted by the factsheet's therapeutic caution.
] <lim:off-label-drug-expert-caution>
