#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Shared Transdiagnostic CNS Genetic Factor Across Chronic Overlapping Pain Conditions])[
*Certainty: 0.55.* The Kerrebijn 2026 GWAS found fibromyalgia shows genetic correlation (rg) above 0.7 with low back pain, post-traumatic stress disorder, and irritable bowel syndrome, and pervasive positive correlation with depression, somatoform/dissociative disorders, and migraine @Kerrebijn2026FibromyalgiaGWAS. Independent genomic structural-equation modeling (Johnston 2025) establishes nociplastic pain as a shared heritable factor underlying chronic overlapping pain conditions @Johnston2025NociplasticPain, and Lin 2026 (GenomicSEM) identifies a shared latent genetic liability across fibromyalgia and psychiatric traits, with enrichment in synaptic function and a transdiagnostic CNS factor @Lin2026FibromyalgiaPsychiatric.

*Interpretation.* This pattern supports a transdiagnostic central-sensitization model: chronic overlapping pain conditions (COPCs) share a common, centrally-mediated genetic architecture rather than being wholly distinct entities. The ME/CFS relevance is that ME/CFS already shows high genetic correlation with irritable bowel syndrome (rg = 0.75) and depression (rg = 0.60) in DecodeME @DecodeME2025 — the same gut-brain and central-nervous-system genetic axes implicated in the fibromyalgia findings.

*Evidence-quality note:* Genetic correlation is an association between heritable components, not proof of shared causal biology — correlated traits may share pathways or share population structure. Causality (a shared CNS factor driving multiple conditions) rests on the GenomicSEM/MR analyses (quasi-causal, contingent on instrument validity) rather than the rg values alone @Lin2026FibromyalgiaPsychiatric @Hu2025BrainNetworkFM.

*Falsifiable predictions:* (1) A transdiagnostic genomic SEM factor across fibromyalgia, IBS, low back pain, and depression will show significant heritability and enrichment in shared neural cell types. (2) Polygenic risk for nociplastic pain will predict symptom severity across ME/CFS, fibromyalgia, and IBS cohorts. Falsified if the shared genetic factor explains negligible variance or if enrichment is condition-specific rather than shared.

*Consequence:* This argues that ME/CFS, fibromyalgia, IBS, and chronic pain are not fully separate genetic disorders but members of a shared central-sensitization family — which matters because it supports transdiagnostic treatment strategies (centrally-acting approaches) and explains the high comorbidity burden in ME/CFS patients.
] <hyp:shared-transdiagnostic-cns-genetic-factor>
