#import "../../../../../shared/environments.typ": *

#hypothesis(title: [High Fibromyalgia Genetic Correlation With Chronic Pain and Psychiatric Traits])[
*Certainty: 0.42.* The Kerrebijn 2026 GWAS found fibromyalgia shows genetic correlation (rg) above 0.7 with low back pain, post-traumatic stress disorder, and irritable bowel syndrome, and pervasive positive correlation with depression, somatoform/dissociative disorders, and migraine @Kerrebijn2026FibromyalgiaGWAS. Independent genomic structural-equation modeling (Johnston 2025) reports nociplastic pain as a shared heritable factor underlying chronic overlapping pain conditions @Johnston2025NociplasticPain, and Lin 2026 (GenomicSEM) reports a shared latent genetic liability across fibromyalgia and psychiatric traits with synaptic-function enrichment @Lin2026FibromyalgiaPsychiatric.

*Interpretation.* These rg values establish that fibromyalgia shares substantial genetic variance with chronic pain and psychiatric/somatic traits. Whether a single transdiagnostic CNS factor *drives* this (versus several overlapping pathways, or shared population structure) is not yet established — the GenomicSEM common-factor analyses are a candidate formalization of that idea, not proof of it. The ME/CFS relevance is that ME/CFS already shows high genetic correlation with irritable bowel syndrome (rg = 0.75) and depression (rg = 0.60) in DecodeME @DecodeME2025 — the same axes implicated in the fibromyalgia findings.

*Evidence-quality note:* Genetic correlation is an association between heritable components, not proof of shared causal biology — correlated traits may share pathways or share population structure. Causality (a shared CNS factor driving multiple conditions) rests on the GenomicSEM/MR analyses (quasi-causal, contingent on instrument validity) rather than the rg values alone @Lin2026FibromyalgiaPsychiatric @Hu2025BrainNetworkFM.

*Falsifiable predictions:* (1) A transdiagnostic genomic SEM factor across fibromyalgia, IBS, low back pain, and depression will show significant heritability and enrichment in shared neural cell types. (2) Polygenic risk for nociplastic pain will predict symptom severity across ME/CFS, fibromyalgia, and IBS cohorts. Falsified if the shared genetic factor explains negligible variance, if enrichment is condition-specific rather than shared, or if the correlations are attributable to population structure.

*Consequence:* Fibromyalgia, ME/CFS, IBS, and chronic pain show high pairwise genetic correlation — a real finding that argues for shared genetic underpinnings — but whether a single central-sensitization mechanism drives this is unproven; transdiagnostic treatment strategies remain a hypothesis to test, not an established implication. (Severity applicability: unknown — GWAS cohorts not stratified by severity.)
] <hyp:shared-transdiagnostic-cns-genetic-factor>
