#import "../../../../../shared/environments.typ": *

#limitation(title: [SynGO Enrichment Is Unpublished, Method-Dependent, and Vulnerable to Gene-Level Confounds])[
The postsynaptic-assembly localization of the ME/CFS genetic signal rests on a single, unpublished MAGMA gene-set enrichment run against the SynGO resource, performed by one investigator and documented on a science blog rather than in a peer-reviewed publication, with no deposited analysis code or exact parameter set — it is not independently reproducible from its own source and has not been independently replicated. Gene-set enrichment is sensitive to analytic choices (SNP-to-gene window size, background gene set, multiple-testing method), and the DecodeME+MVP "concordance" is not fully independent, since the meta-analysis incorporates DecodeME (the same cohort counted in both runs). Two further confounds could produce a spurious postsynaptic signal without any ME/CFS-specific meaning: (1) *gene-length/conservation bias* — synaptic genes are exceptionally long, conserved, and loss-of-function-intolerant @Koopmans2019SynGO, and MAGMA enrichment is biased toward exactly these properties by statistical construction, so the signal may tag generic gene features rather than synapse biology; and (2) *pleiotropy* — SynGO terms are overrepresented among genes for intelligence, educational attainment, ADHD, autism, bipolar disorder, and neurodevelopmental disorders @Koopmans2019SynGO, so the enrichment may reflect a generic brain-expressed-conserved-gene tag shared with many neuropsychiatric traits rather than an ME/CFS-specific mechanism. The SynGO resource itself is an in silico gene-ontology knowledge base built by expert curation (which may over-annotate the most-studied postsynaptic and glutamatergic structures); any enrichment finding is an inference from GWAS gene-set analysis, with a translation gap between ontology annotation and disease tissue.

(Certainty: N/A — this is a methodological limitation. Severity applicability: unknown.)

*Consequence:* Until the SynGO enrichment is published with code, independently replicated in a non-overlapping cohort, and shown to survive correction for gene length/conservation and to exceed the generic brain-trait pleiotropy baseline, the postsynaptic-assembly localization should be treated as a hypothesis for testing — not as an established feature of ME/CFS — so that readers do not mistake a single unpublished analysis for a replicated genetic finding.
] <lim:syngo-enrichment-unpublished>
