#import "../../../../shared/environments.typ": *

=== Vasomotor Dysfunction and Thermoregulatory Failure


#speculation(title: [Tonic Cutaneous Vasoconstriction Bias Explains Dual Heat+Cold Intolerance])[
*Certainty: 0.40.* ME/CFS patients paradoxically report both heat and cold intolerance — two symptoms that appear to require opposite vascular states. Heat intolerance requires vasodilation failure (cannot dissipate heat), cold intolerance requires thermogenesis failure (cannot conserve or generate heat). Cambras et al. demonstrated that skin temperature circadian rhythm disruption is associated with elevated endothelin-1 (ET-1), a potent vasoconstrictor @Cambras2023SkinTemperatureEndothelin. This suggests a vasomotor bias toward tonic vasoconstriction: ET-1 elevation may lock cutaneous vessels in a chronically constricted state, preventing both heat-induced vasodilation (→ heat intolerance) and cold-induced perfusion for thermogenesis (→ cold intolerance). Normally, cutaneous vessels flip-flop between dilated (heat dissipation) and constricted (heat conservation) states with high dynamic range. In ME/CFS, the vasomotor setpoint may be shifted toward constriction, compressing the dynamic range from both sides — vessels cannot dilate enough for cooling, and cannot recruit enough perfusion for warming. This single mechanism would explain the dual-intolerance paradox without requiring separate heat and cold pathways. Falsifiable: laser Doppler flowmetry will show baseline cutaneous perfusion 40% lower in ME/CFS than controls; both heat challenge (43°C) and cold challenge (15°C) will elicit blunted perfusion responses in ME/CFS; ET-1 receptor antagonism will restore perfusion flexibility.
] <spec:vasomotor-constriction-bias>

#open-question(title: [Could Cold Intolerance Reflect Failed Brown Adipose Tissue Activation via Sympathetic Dysfunction?])[
Cold adaptation requires brown adipose tissue (BAT) activation via sympathetic nervous system norepinephrine release at β3-adrenergic receptors, triggering UCP1-mediated thermogenesis. ME/CFS sympathetic dysregulation — documented adrenergic receptor dysfunction, POTS, and reduced HRV — may prevent BAT activation, causing cold intolerance via failed thermogenesis. This would mirror heat intolerance from failed vasodilation: both reflect sympathetic output that is tonically elevated but dynamically inflexible — high enough to maintain vasoconstriction, but unable to mount the coordinated sympathetic surge needed for BAT activation. Falsifiable: PET-CT with ^18F-FDG after controlled cold exposure (16°C, 2 h) will show absent BAT activation in ME/CFS vs age/BMI-matched controls; β3-agonist (mirabegron) will restore BAT uptake and cold tolerance. This is mechanistically grounded in established BAT physiology but entirely untested in ME/CFS.
] <oq:bat-cold-intolerance>

#speculation(title: [Peri-Exertional COX-2 Inhibition with Celecoxib for PEM Prevention])[
*Certainty: 0.40. Probability of clinically meaningful efficacy: 0.08.* Post-exertional malaise (PEM) involves an inflammatory cascade peaking 6–48 h after exertion: C4a complement elevation @Sorensen2003complement, IL-1beta and IL-6 surges, and prostaglandin E2 (PGE2) release from COX-2 upregulation in activated immune cells and endothelium. If COX-2-derived PGE2 is a necessary amplifier of the PEM inflammatory cascade, selective COX-2 inhibition (celecoxib) timed to the peri-exertional window could prevent or attenuate PEM by blocking PGE2 synthesis at its peak.

*Mechanism.* Exertion in ME/CFS triggers: (1) complement activation → C5a → neutrophil/monocyte COX-2 upregulation; (2) mechanical stress on skeletal muscle → COX-2 induction in myocytes and satellite cells; (3) endothelial shear stress → endothelial COX-2 expression. COX-2 converts arachidonic acid to PGH2, the precursor of PGE2, PGD2, PGI2, and TXA2. PGE2 amplifies the inflammatory signal through EP2/EP4 receptor-mediated cAMP signalling and NF-kappaB activation. If PGE2 is a positive feedback amplifier rather than a downstream bystander in the PEM cascade, blocking its synthesis during the critical 6–24 h post-exertion window could reduce PEM magnitude without requiring full anti-inflammatory immunosuppression.

*Timing hypothesis.* Standard NSAID dosing (TID, continuous) may not prevent PEM because: (a) continuous COX-2 inhibition allows upstream complement activation to proceed unopposed, and (b) the prostanoid mediator mix after exertion changes over time (PGE2 dominant at 6–12 h, PGI2 at 24–48 h). A peri-exertional protocol — celecoxib 200 mg at exertion onset + 200 mg at 12 h — would target the PGE2-rich window while avoiding continuous suppression. The protocol differs from standard COX-2 inhibitor use in requiring exertion-triggered, not scheduled, dosing.

*Safety considerations.* Cardiovascular safety is paramount in a population with already-impaired endothelial function: selective COX-2 inhibitors carry cardiovascular risk (increased thrombotic events) by suppressing endothelial PGI2 without platelet COX-1 inhibition. Celecoxib has the most favourable cardiovascular profile among COX-2-selective NSAIDs at 200 mg BID. However, in ME/CFS patients with POTS, hypovolemia, or endothelial dysfunction, even short-course COX-2 inhibition may: (1) raise blood pressure (sodium retention, reduced renal PGE2); (2) impair flow-mediated dilation; (3) interact with antihypertensives (ACE inhibitors, ARBs, beta-blockers common in this population). The risk-benefit ratio is unfavourable unless the PEM-prevention effect size is large (≥50% PEM severity reduction).

*Falsifiable predictions.* (1) Randomised, placebo-controlled, within-subject crossover trial (n=20, two identical standardized exercise challenges separated by ≥4 weeks): celecoxib 200 mg at exertion start + 200 mg at 12 h will reduce 24 h PEM severity (visual analogue scale) by ≥30% vs placebo. (2) Urinary PGE-M (PGE2 metabolite) at 6 h post-exertion will be suppressed by celecoxib and correlate with PEM severity. (3) C4a and IL-1beta elevations will NOT be suppressed by celecoxib (confirming COX-2 acts downstream of complement/cytokine triggering, not upstream). (4) Patients with the largest C4a spike at 6 h will show the greatest celecoxib response.

*Limitations.* No ME/CFS-specific COX-2 data exist. The cardiovascular risk in a population with known endothelial dysfunction is a serious concern — a negative safety outcome would outweigh any potential PEM benefit. Celecoxib is a moderate CYP2C9 substrate; ME/CFS patients on other CYP2C9-metabolised drugs (cannabidiol, losartan, fluoxetine) may have altered exposure. The peri-exertional dosing protocol requires patients to predict exertion — feasible for planned activities but not for spontaneous PEM triggers.
] <spec:celecoxib-pem-prevention>

