#import "environments.typ": *

= Abstract

Myalgic encephalomyelitis/chronic fatigue syndrome (ME/CFS) is a severe, chronic, multi-system neuroimmune disease affecting an estimated 0.89% to 2.5% of the global population. Characterized by profound post-exertional malaise, unrefreshing sleep, cognitive dysfunction, and autonomic dysregulation, ME/CFS represents one of the most disabling chronic conditions in modern medicine. Despite affecting millions worldwide, the disease has historically suffered from underfunding, dismissal by medical professionals, and classification as a syndrome rather than a disease with identifiable pathophysiology.

The February 2024 NIH deep phenotyping study fundamentally transformed this landscape by demonstrating specific biological abnormalities: decreased brain activity in effort-related neural circuits, exhausted T-cell populations, chronic B-cell activation deficits, and depleted catecholamine levels in cerebrospinal fluid. These findings conclusively established ME/CFS as a systemic biological disease with measurable immune, neurological, and metabolic dysfunction.

This comprehensive documentation synthesizes current research across clinical presentation, pathophysiological mechanisms, treatment approaches, research evidence, and quantitative modeling. The work integrates findings from hundreds of peer-reviewed sources spanning energy metabolism dysfunction, immune exhaustion, neuroinflammation, endocrine dysregulation, cardiovascular abnormalities, gut-brain axis disruption, and genetic-epigenetic factors.

Part I (Chapters 1–5) provides detailed clinical characterization of core and additional symptoms, the evolution of diagnostic criteria from Fukuda through the Canadian Consensus and International Consensus Criteria, and disease course variations from mild to very severe presentations including severity-specific phenotyping. Part II (Chapters 6–15) examines established and hypothetical pathophysiological mechanisms across ten chapters covering mitochondrial dysfunction, immune exhaustion, neuroinflammation, endocrine dysregulation, cardiovascular and autonomic failure, gut-microbiome disruption, genetic and epigenetic factors, integrative multi-system models, speculative mechanistic hypotheses with falsifiable predictions, and symptom-producing mechanisms. Part III (Chapters 14a–19) opens with urgent action protocols for severe and very severe cases, followed by pediatric-specific management for both housebound and ambulatory children, then documents symptom-based management, medications targeting underlying mechanisms, supplement regimens, lifestyle interventions, emerging therapies, and integrative personalized approaches. Part IV (Chapters 20–25b) synthesizes biomarker research, clinical trial outcomes, mechanistic studies, epidemiological patterns, research controversies, translational findings, research infrastructure proposals, and a set of fully specified proposed studies with explicit hypotheses and trial designs. Part V (Chapters 26–32) develops formal mathematical models of disease dynamics using ordinary differential equation systems, presenting energy metabolism models, immune system dynamics, neuroendocrine and autonomic regulation, integrated multi-system coupling, temporal evolution with tipping-point dynamics, and predictive clinical applications for pacing optimization and treatment selection.

Nine appendices provide reference material: a glossary of medical and scientific terms, abbreviations, diagnostic tools and assessment scales, patient resources, mathematical derivations supporting Part V, supplement protocols, a research synthesis, an annotated bibliography of landmark studies, and a registry of ongoing and planned ME/CFS studies.

Methodologically, this work uses a structured epistemic classification system distinguishing achievements (high-certainty findings from replicated studies), hypotheses (certainty $gt.eq 0.45$, requiring validation), speculations (certainty $< 0.45$, exploratory), predictions (testable claims for future research), warnings (critical limitations and contraindications), and recommendations (evidence-based guidance requiring physician review). Evidence quality is systematically classified as high, medium, or low certainty based on sample size, peer-review status, replication, and methodological rigor. A cross-document hypothesis registry tracks all speculative content with falsifiability assessments.

This documentation serves multiple audiences: researchers seeking comprehensive mechanistic understanding and quantitative modeling frameworks, clinicians requiring evidence-based treatment protocols with dosing guidance and contraindication awareness, patients and caregivers needing accessible explanations of symptoms and management strategies, and advocates working toward recognition, funding, and medical education reform. The work is released under the Creative Commons Attribution 4.0 International License to maximize accessibility and enable derivative works.

Written by a software architect and patient-researcher with degrees in industrial engineering and management sciences, this documentation applies systems thinking, computational analysis, and first-principles reasoning to ME/CFS pathophysiology while maintaining epistemic humility about the substantial uncertainties remaining in the field. The author explicitly disclaims medical expertise and emphasizes that all content represents literature synthesis and personal experience documentation, not clinical advice. All treatment decisions must be made in consultation with qualified healthcare providers.

ME/CFS research is at a critical inflection point. The biological validation provided by recent NIH and international studies, combined with shared research agendas driven by Long COVID parallels, offers unprecedented opportunity for mechanistic discovery and therapeutic development. This document aims to accelerate progress by organizing scattered findings into an accessible, comprehensive reference while identifying critical knowledge gaps requiring focused investigation.

