

## Version 7.2

- *Bibliography consolidation + retrospective adaptation (Eckey 2025)* (3 bib files: treatments.bib, neuroinflammation.bib, neurology-comorbidities.bib; ch07 sec-28, ch14d, ch22 lim-pacing-evidence-base, ch27 protocol-1 + LDA differential, ch32 IVIG/rituximab + LDA + stimulants, hypothesis-registry): Removed a misattributed duplicate bib entry `Vernon2025PNAS` that described the Eckey et al.\ 2025 PNAS survey (same DOI/PMCID) under the wrong first author "Vernon, Suzanne D" and wrong article number (26 vs 28); consolidated all 10 of its citations to the canonical @Eckey2025PatientReported and corrected an erroneous "alias entry" note on the unrelated McManimen & Jason entry. Retroactive evidence adaptations: reinforced the pacing evidence-base limitation (ch22) with the Eckey pacing NAS 75.2% and cross-cluster effectiveness; reinforced the IVIG/rituximab section (ch32) with the Eckey IgG/multisystemic-cluster patient-reported signal (73.3%). All new content flagged patient-reported, single-survey, unblinded. No certainty bumps (survey-correlational evidence does not meet the bump bar). _Motivated by:_ @Eckey2025PatientReported — source of the consolidated survey data and the corrected citations.

## Version 7.1

- *Patient-reported treatment outcomes gap-fill (Eckey et al.\ 2025)* (Chapter 14d cross-disease; Chapter 24, sec-02 severity-stratified pathways + sec-07 GET-avoidance; Chapter 28, CoQ10/B12/PEA dose-response; Chapter 32, sec-02 how-to-use patient-reported stratification; Chapter 33, sec-12 medication compendium LDN/ivabradine/Amphetamines/Nattokinase/Melatonin/Beta-Blockers): Gap-fill integration of the Eckey et al.\ 2025 PNAS patient-reported treatment survey ($n = 3{,}925$) beyond the pre-existing stimulant-contraindication usage. Added: GET measured the lowest Net Assessment Score of any treatment ($-$72.2%) to the GET-avoidance harm-survey evidence; four-symptom-cluster treatment-stratification framework and the finding that disease severity (capacity), not diagnosis label, is the strongest predictor of treatment response (Chapter 32); severity-stratification prevalence data (Chapter 24); symptom-level differentials (LDN improves fatigue/PEM/brain fog but not POTS; ADHD stimulants help brain fog/fatigue but not PEM/POTS and benefit only the low-POTS cognitive cluster; ivabradine reported superior to beta-blockers; melatonin the only treatment improving unrefreshing sleep; H1RA+H2RA best for MCAS); dose-response signals (PEA enhanced-bioavailability 56.8% vs 41.5%; B12 injections 47.1% vs oral 30.5%; CoQ10 higher-dose 50.7% vs 26.7%); and safety signals (5% anticoagulant/antiplatelet discontinuation for bleeding incl. one GI bleed; 17–21% worsening on beta-blockers/stimulants/Mestinon). All additions flagged as patient-reported, unblinded, single-survey evidence with severity-applicability and evidence-class caveats. _Motivated by:_ @Eckey2025PatientReported — largest patient-reported treatment-outcome survey in ME/CFS and long COVID, quantifying treatment responses, symptom-cluster stratification, severity as response predictor, and GET harm.

## Version 6.2

- *TSPO PET imaging integration* ([Chapter 6, 1 new speculation environment; Chapter 7, 1 new limitation environment; Chapter 14k, 2 new hypothesis environments; Appendix H, 2 new annotated entries; references.bib, 8 new entries; hypothesis-registry.typ, 2 new entries]): Integration of 8-paper literature review on TSPO PET imaging in ME/CFS, highlighting critical methodological gaps and mechanistic insights. Single published ME/CFS TSPO PET study (Raijmakers 2021, n=9) found NO neuroinflammation using first-generation tracer; no whole-body TSPO PET studies exist in PubMed. Key finding: Barzon 2026 demonstrated peripheral inflammation reduces TSPO tracer brain influx (BBB transport confounding), potentially masking neuroinflammation. Added neuroinflammation measurement limitation environment to Chapter 7. Added TSPO dual-role speculation environment to Chapter 6 (mitochondrial dysfunction vs inflammation marker). Added two hypotheses to Chapter 14k: BBB transport confounding hypothesis (explains negative TSPO PET findings) and peripheral-inflation central-starvation hypothesis (resolves paradox of elevated peripheral TSPO with decreased brain signal). Updated hypothesis registry with 2 new entries. _Motivated by:_ @Raijmakers2021TSPOCFS — single ME/CFS TSPO PET study showing null neuroinflammation finding; @Barzon2026TSPOBBB — BB B transport confounding mechanism; @VanElzakker2019TSPOReview — comprehensive TSPO biology review. Michelle James Stanford conference data (unpublished) suggests whole-body TSPO imaging would reveal "peripheral-up, central-down" pattern, but study not yet in PubMed.
