


## Version 7.9

- *Sustained new-onset ME/CFS risk up to four years after SARS-CoV-2 (Hadidchi et al.\ 2025)* ([Ch01 sec-04 epidemiology risk-factors + prevalence, 2 paragraphs strengthened; Ch06 onset-patterns, 1 bullet strengthened; Ch14d cross-disease, 5 new environments (`hyp:postcovid-postacute-iron-prediction`, 3 limitations, 2 open-questions) + 1 new synthesis `syn:postinfectious-trigger-convergence` + 1 bullet; hypothesis-registry.typ, 2 new entries; Appendix H, 8 new annotated entries; `bib/epidemiology.bib` + `bib/long-covid.bib`, 8 new entries]): Integrated the large-cohort epidemiological finding that SARS-CoV-2 infection raises new-onset ME/CFS risk sustained to four years post-infection (Hadidchi et al.\ 2025, J Transl Med, n=147,377 EHR, adjusted HR 1.46 hospitalized / 1.56 non-hospitalized), directionally replicated by RECOVER (n=11,785, ~2.8-fold incidence) and the CDC INSPIRE cohort. Added a dedicated cross-disease synthesis anchoring the paper's post-viral onset model at pandemic scale (cert 0.60 for the convergent onset claim), a hypothesis that the acute-biomarker null (ferritin/CRP/D-dimer/LDH do not predict converters) narrows the converter-discriminating window to the post-acute transition and feeds the existing iron-redox temporal model (cert 0.40, with an explicit "iron may be off the causal pathway" alternative), plus three critical-category limitations (diagnostic-delay vs true new-onset, vaccination-era confounding, single-system generalizability) and two open-questions (liver function as a risk-stratification marker; non-inflammatory acute trigger). No certainty bumps — the Hadidchi evidence is risk/incidence rather than a direct independent replication of an exact existing claim, and was channeled into new hypotheses rather than bumping shared registry content (MIXED-mode concurrency). _Motivated by:_ @Hadidchi2025CFSrisk — the primary large-cohort monocentric EHR study; @RECOVER2025, @Unger2024MECFSinspire, @Vu2024FatiguePostCovid — directional replication cohorts. _Clinical relevance:_ HIGH — prognosis/monitoring: sustained post-COVID ME/CFS risk justifies earlier diagnosis and (if the post-acute iron prediction replicates) a simple 3-month iron panel as a risk-stratification aid. _Quality note:_ none (PROCEED; 0/8 included papers <0.40 discounted; no new treatment claims).

## Version 7.8

- *Hibernation biology as a candidate resource for the low-energy state (cross-species)* ([Chapter 18 sickness/torpor section, 1 new consolidated speculation `spec:hibernation-arousal-resource` + 2 new `#registry-entry` speculation entries (later consolidated to 1 hibernation entry + 1 EP3R + 1 area-postrema from the parent cycle); Appendix H, 12 new annotated entries; `bib/pathophysiology-general.bib`, 12 new entries; glossary.json, 6 new entries]): Integrated hibernation/torpor-arousal molecular biology as a cross-species, research-stage *candidate* resource for the reversible energy-state switch implicated in the ME/CFS low-energy state — not a mechanism or treatment claim. Consolidated the arousal-machinery and adaptive-pausing content into one speculation that explicitly subordinates itself to the paper's existing ISR/mTORC1 framework (ch07 @spec:pem-isr, @spec:isr-chronic, @hyp:pem-biphasic-isr + WASF3), contributes a specific polysome-profiling assay, carries a torpor-vs-ME/CFS phenotype critical constraint (no defended hypothermia), a Duffy oxidative-damage safety caveat, a matched-sedentary control-arm discriminator, and cross-species translation-gap/severity caveats. No certainty bumps (PARTIAL decision; all content speculation/S-type per WEAK-EVIDENCE active caps). Ch30 cascade skipped for no discriminating value (no drug ≥0.40 ME/CFS; redundant with existing A2A/AMPK content). _Motivated by:_ @Shimaoka2018A1ARHypothermia — central A1AR agonism induces torpor/hypothermia in a non-hibernator (conserved entry signal); @Jobava2021AdaptivePausing — a "hibernation-like" adaptive-pausing program in non-hibernating mammalian cells that overlaps the ISR line of evidence; @Drew2026HibernationBiomedicine — the broad hibernation-medicine resource framing. _Clinical relevance:_ LOW — basic-science drug-discovery resource; no diagnostic, treatment, or biomarker implication for current practice. _Quality note:_ WEAK-EVIDENCE (PARTIAL — >50% of included papers discounted below 0.40; all model-system/cross-species).

## Version 7.7

- *Plasma-cell targeting (daratumumab / anti-CD38) update — LLPC source & NK-depletion limit* ([Chapter 33 sec-12 medication-reference compendium, 2 new `#finding` environments in the Daratumumab (Anti-CD38) entry; hypothesis-registry.typ, 1 new entry; Appendix H, 2 new annotated entries; `bib/autoimmunity.bib`, 2 new entries (Cox2022dUTPaseMECFS, Ray2026nkLongCOVID)]): Gap-fill update to the already-integrated daratumumab topic (Fluge 2025 pilot, ResetME trial, and the rituximab-null→plasma-cell-sanctuary framing are all pre-existing). Added mechanistic depth on WHY plasma-cell targeting is biologically targeted: Cox 2022 (JCI Insight) shows EBV/HHV-6A dUTPases drive TFH differentiation, activin A and IL-21 secretion, and extrafollicular antibody responses in ME/CFS, plausibly generating the CD38+ long-lived plasma cells that antibody depletion must reach (cert 0.65) @Cox2022dUTPaseMECFS. Added a response/safety limitation: Ray 2026 (Front Immunol) documents CD56+CD16+ NK-cell depletion and reduced NK inflammatory capacity in Long COVID; since NK cells are an on-target CD38+ population depleted by daratumumab, pre-existing NK deficiency predicts non-response and compounds infection risk in the immunosuppressed window — consistent with Fluge's low-baseline-NK→poor-response observation (cert 0.45) @Ray2026nkLongCOVID. No certainty bumps beyond a single justified 0.40→0.65 on the LLPC plasma-cell-targeting hypothesis (direct ME/CFS-cohort mechanistic evidence). No duplication of existing daratumumab content; additions are targeted mechanistic and limitation findings only. _Motivated by:_ @Cox2022dUTPaseMECFS — the viral-dUTPase→TFH/activin-A→LLPC generation chain that explains the plasma-cell-targeted rationale; @Ray2026nkLongCOVID — the NK-depletion limitation constraining daratumumab response/safety in post-viral patients. _Clinical relevance:_ MEDIUM — mechanistic context and a response-stratification caution for any autoantibody-positive trial; no dosing or prescribing change recommended.

## Version 7.6

- *Peppercorn 2025 DNA methylation landscapes in ME/CFS vs Long COVID + methylation consolidation gap-fill* ([Chapter 14d cross-disease, 1 new speculation `spec:methylene-mecfs-longcovid-distinguish`; Chapter 14 global-methylation, 1 citation + cross-reference reinforcement; Appendix H, 1 new annotated entry; `bib/genetics-epigenetics.bib` 1 entry corrected (DOI/PMID/volume/pages + accurate DMF counts); hypothesis-registry.typ, 1 new entry]): Gap-filled the partially-integrated Peppercorn et al.\ 2025 (IJMS) comparison of the peripheral-blood methylomes of ME/CFS and Long COVID, which was previously cited only for its 67.8% hypermethylation-dominance statistic. Added a cross-disease speculation (ch14d) that the PBMC methylome has a largely shared core between the two conditions (118 shared differentially methylated fragments, Pearson R = 0.88) yet contains distinguishing sites (ME/CFS 214 DMFs vs Long COVID 429; 6 opposite-direction DMFs incl. an FGD2 promoter hypermethylated only in LC), with a stage-from-onset confound explicitly flagged (LC ~1 yr vs ME/CFS ~12 yr) (cert 0.52) — consistent with the existing "shared yet distinct" ME/CFS-vs-LC narrative (cf.\ 7T MRS) and a caution against pooling the two conditions in methylation research. Retroactive adaptation (Phase 6) added the Peppercorn RRBS study and a cross-reference to the new speculation in the ch14 global-methylation section. Corrected the bib placeholder DOI (`10.3390/ijmsXXXXX`) to the verified `10.3390/ijms26146631` and updated the note to the accurate 214/429/118 DMF figures (145 hyper / 69 hypo in ME/CFS). No certainty bumps (single-lab n=5 study, raw cert 0.52, no independent replication — below the bump bar). _Motivated by:_ @Peppercorn2025methylation — the Otago head-to-head RRBS methylome comparison providing the first direct ME/CFS-vs-Long-COVID methylation landscape. _Clinical relevance:_ MEDIUM — a research-stage differential-diagnostic/stratification direction (if the 6 opposite-direction DMFs replicate, a blood-based LC-vs-ME/CFS differentiator); severity applicability unknown.

## Version 7.5

- *Symptom causes & persistence in long COVID and ME/CFS (Komaroff & Dantzer 2025)* ([Chapter 15 sickness-behavior, 1 new hypothesis `hyp:ch15-sickness-torpor-circuits`; Chapter 15 Omdal-null reconciliation, 1 citation reinforcement; hypothesis-registry.typ, 2 new entries; Appendix H, 8 new annotated entries; `bib/long-covid.bib` 3 new, `bib/neuroinflammation.bib` 3 new, `bib/autoimmunity.bib` 1 new, `bib/immune.bib` 1 new; glossary.json, 5 new entries]): Integrated the high-authority Komaroff & Dantzer 2025 *Cell Reports Medicine* review consolidating how long COVID and ME/CFS symptoms arise and persist. Added a hypothesis that core symptoms are generated by dedicated, recently-discovered sickness-behavior and torpor neural circuits (area postrema→brainstem; organum vasculosum→ventromedial preoptic area; median preoptic nucleus→torpor) activated by neuroinflammation, with a torpor-like AMPK/mTOR hypometabolic-switch framing (cert 0.45, translation-gap annotated for the rodent-derived circuits). Added a registry hypothesis on self-reinforcing vicious cycles (mitochondrial↔inflammation, redox↔energy, redox↔endothelial, spike/fibrin epitope) sustaining symptom persistence (cert 0.45), folding in the new torpor/hypometabolic-switch and two-way preoptic-switch concepts. Phase 6 retroactive reinforcement added @KomaroffDantzer2025SymptomPersistence to the existing ch18 Omdal-null reconciliation (CNS-confined neuroinflammation→circuit maintenance), corroborating the paper's pre-existing neuroinflammation-specific account. No certainty bumps (reinforcement is citation-level; existing claims already confident and no independent-line convergence crossed the bump bar). _Motivated by:_ @KomaroffDantzer2025SymptomPersistence — the review proposing neuroinflammation-activated sickness/torpor neural circuits as the symptom-generating pathway; @Hrvatin2020TorporNeurons, @Machado2025PreopticSwitch — the rodent torpor/fever-switch circuits. _Clinical relevance:_ MEDIUM — mechanistic framing and a research-stage anti-neuroinflammation treatment direction (no dosing/data; traditional anti-inflammatories predicted inadequate); severity applicability unknown.

## Version 7.4

- *7T MRS brain/muscle chemistry in ME/CFS and long COVID (Godlewska et al.\ 2025)* — gap-fill + reinforcement of a partially-integrated finding ([Chapter 14d cross-disease, 1 new hypothesis `hyp:distinct-brain-neurochemistry-mecfs-longcovid` + 1 new speculation `spec:long-covid-dacc-choline` + 1 methodological-limitation addition; Chapter 7 sec-27 brain-energy, accuracy update + 1 citation reinforcement; Chapter 7 sec-04 PDH, 1 citation reinforcement; Appendix H, 6 new annotated entries; `bib/long-covid.bib` 4 new `bib/neuroinflammation.bib` 2 new; hypothesis-registry.typ, 2 new entries]): Completed the long-COVID and muscle halves of the Godlewska 7T MRS study beyond the pre-existing brain-lactate coverage. Added a hypothesis that ME/CFS (anterior-cingulate lactate↑, replicated across three independent lab clusters) and long COVID (dorsal-cingulate choline↓) show separable brain neurochemistry, arguing against pooling the two conditions (cert 0.50). Added a speculation on the long-COVID dorsal-cingulate choline reduction as an associative coagulation/"brain fog" substrate (cert 0.35, flagged region-/age-dependent per Pajuelo/Mueller heterogeneity). Retroactive reinforcement updated the existing `oq:brain-metabolism-specificity-fatigue` open question (previously "no cross-condition comparison exists") with the Murrough MDD-discrimination and ME-vs-LC MRS evidence, and reinforced the ch07 PDH exercise-provoked-muscle prediction with Naegel 2023 load-gated muscle-deficit data. No certainty bumps (all incoming certainties <0.70 per the Evidence Quality Floor). _Motivated by:_ @Godlewska2025MRS — 7T MRS head-to-head showing ME/CFS lactate↑ and long COVID choline↓ with distinct neurochemistry; @Murrough2010VentricularLactate — ventricular lactate discriminates CFS from major depressive disorder. _Clinical relevance:_ MEDIUM — research-stage diagnostic differentiation and trial-stratification implication; no treatment change.

## Version 7.4

- *Innate immune hyperactivation cascade routing (Che et al.\ 2025)* ([Chapter 33, sec-08 integrative models, 1 new cascade subsection `sec:innate-immune-hyperactivation-cascade`; Chapter 33 sec-12, 6 `*Appears in:*` cross-reference lines (Colchicine, LDN, Minocycline, Corticosteroids, Anakinra, Canakinumab); hypothesis-registry.typ, 1 new entry]): Routed the already-integrated Che et al.\ 2025 (npj Metab Health Dis) innate-immune-evidence through the ch33 differential-diagnostic cascade framework as a scoped micro-add, without duplicating content already in ch08/ch18/ch17 (Che 2025 was already cited there; this cascade adds the drug-testable peripheral-vs-CNS driving question). The cascade distinguishes three overlapping drivers of fatigue/PEM — systemic innate-immune inflammation (broad anti-inflammatory → inflammasome/IL-1 → LDN/minocycline), metabolic energy-triage (@sec:triage-cascade), and CNS-restricted neuroinflammation (@sec:microglial-cascade) — and frames differential drug response as a research/clinical-judgment tool (not a validated diagnostic instrument). No new bib entries (reuses `@che2025innate`, `@Hornig2015`); no certainty bumps (scope control); competing peripheral-driver vs CNS-confined hypothesis flagged as an unresolved tension. Cohort-overlap caveat (Che 2025 shares the Lipkin multi-site program with Hornig 2015) is noted in the registry entry. _Motivated by:_ @che2025innate — Lipkin multi-site metabolomic/proteomic + ex-vivo microbial-stimulation study documenting an exaggerated innate immune response that worsens after exercise and correlates with fatigue/PEM. _Clinical relevance:_ MEDIUM — mechanistic context for differential drug-response interpretation; no treatment or diagnostic change recommended. _Quality note:_ none (scoped cross-referencing scaffold; severity applicability stated; no new treatment claims).

## Version 7.3

- *Dementia neuroinflammation cross-disease integration (Kuring et al.\ 2026)* ([Chapter 14d cross-disease, 2 speculations + 1 synthesis `sec:architecture-c-cross-disease-bridges`; Chapter 8 pro-inflammatory cytokines, 1 limitation; Chapter 19 causal-hierarchy, chronicity criterion cross-disease sentence; Chapter 18 neurodegeneration-risk speculation, supporting-evidence reinforcement; Appendix H, 3 new annotated entries; `bib/neuroinflammation.bib`, 3 new entries; hypothesis-registry.typ, 2 new entries; glossary.json, 4 new entries]): Integrated the systemic review/meta-analyses testing the inflammatory-mediated-neurodegeneration hypothesis (Kuring 2026 dementia + Kuring 2023 depression/anxiety/PTSD + Strawbridge 2019 CFS) as cross-disease evidence that chronic low-grade inflammation can be dissociated from psychiatric comorbidity and can run mechanistically upstream of CNS pathology. Added two speculations: (1) a bidirectional mental-illness-inflammation template (cert 0.40) — the reverse-direction counterpart to the existing neuroinflammation-cascade-generator model, framed as an unresolved bidirectional loop whose direction cross-sectional data cannot order; (2) a shared set of G-CSF/GM-CSF/IL-17 markers (cert 0.30) — noting G-CSF/GM-CSF severity-correlated in ME/CFS and elevated in Alzheimer's, as a specific testable marker set rather than nonspecific "inflammation". Added a cross-disease limitation (ch08) that excluding comorbid inflammatory conditions removes classically-reported IL-6/TNF-$alpha$ elevations in dementia — a methodological caution for comorbidity-masked ME/CFS cytokine claims. Added a synthesis condensing these into a convergent template. Phase 6 retroactive reinforcement: strengthened the ch18 neurodegeneration-risk speculation with an independent inflammation-driven route, and the ch08 TNF-$alpha$ section with the 42-study Strawbridge meta. No certainty bumps (same-group provenance of the two Kuring meta-analyses lowers independence below the bump bar). _Motivated by:_ @Kuring2026InflammatoryDementia — 41-study meta-analysis finding dementia inflammation dissociable from psychiatric/physical comorbidity; @Kuring2023InflammatoryMood — companion depression/anxiety/PTSD inflammatory meta; @Strawbridge2019CFSInflammatory — CFS inflammatory-protein meta providing the ME/CFS-side profile comparison. _Clinical relevance:_ MEDIUM — cross-disease mechanistic context for causal-hierarchy and inflammatory-marker interpretation; no treatment or diagnostic change. _Quality note:_ none (targeted cross-disease integration, no new treatment claims).

## Version 7.2

- *Bibliography consolidation + retrospective adaptation (Eckey 2025)* (3 bib files: treatments.bib, neuroinflammation.bib, neurology-comorbidities.bib; ch07 sec-28, ch14d, ch22 lim-pacing-evidence-base, ch27 protocol-1 + LDA differential, ch32 IVIG/rituximab + LDA + stimulants, hypothesis-registry): Removed a misattributed duplicate bib entry `Vernon2025PNAS` that described the Eckey et al.\ 2025 PNAS survey (same DOI/PMCID) under the wrong first author "Vernon, Suzanne D" and wrong article number (26 vs 28); consolidated all 10 of its citations to the canonical @Eckey2025PatientReported and corrected an erroneous "alias entry" note on the unrelated McManimen & Jason entry. Retroactive evidence adaptations: reinforced the pacing evidence-base limitation (ch22) with the Eckey pacing NAS 75.2% and cross-cluster effectiveness; reinforced the IVIG/rituximab section (ch32) with the Eckey IgG/multisystemic-cluster patient-reported signal (73.3%). All new content flagged patient-reported, single-survey, unblinded. No certainty bumps (survey-correlational evidence does not meet the bump bar). _Motivated by:_ @Eckey2025PatientReported — source of the consolidated survey data and the corrected citations.

## Version 7.1

- *Patient-reported treatment outcomes gap-fill (Eckey et al.\ 2025)* (Chapter 14d cross-disease; Chapter 24, sec-02 severity-stratified pathways + sec-07 GET-avoidance; Chapter 28, CoQ10/B12/PEA dose-response; Chapter 32, sec-02 how-to-use patient-reported stratification; Chapter 33, sec-12 medication compendium LDN/ivabradine/Amphetamines/Nattokinase/Melatonin/Beta-Blockers): Gap-fill integration of the Eckey et al.\ 2025 PNAS patient-reported treatment survey ($n = 3{,}925$) beyond the pre-existing stimulant-contraindication usage. Added: GET measured the lowest Net Assessment Score of any treatment ($-$72.2%) to the GET-avoidance harm-survey evidence; four-symptom-cluster treatment-stratification framework and the finding that disease severity (capacity), not diagnosis label, is the strongest predictor of treatment response (Chapter 32); severity-stratification prevalence data (Chapter 24); symptom-level differentials (LDN improves fatigue/PEM/brain fog but not POTS; ADHD stimulants help brain fog/fatigue but not PEM/POTS and benefit only the low-POTS cognitive cluster; ivabradine reported superior to beta-blockers; melatonin the only treatment improving unrefreshing sleep; H1RA+H2RA best for MCAS); dose-response signals (PEA enhanced-bioavailability 56.8% vs 41.5%; B12 injections 47.1% vs oral 30.5%; CoQ10 higher-dose 50.7% vs 26.7%); and safety signals (5% anticoagulant/antiplatelet discontinuation for bleeding incl. one GI bleed; 17–21% worsening on beta-blockers/stimulants/Mestinon). All additions flagged as patient-reported, unblinded, single-survey evidence with severity-applicability and evidence-class caveats. _Motivated by:_ @Eckey2025PatientReported — largest patient-reported treatment-outcome survey in ME/CFS and long COVID, quantifying treatment responses, symptom-cluster stratification, severity as response predictor, and GET harm.

## Version 6.2

- *TSPO PET imaging integration* ([Chapter 6, 1 new speculation environment; Chapter 7, 1 new limitation environment; Chapter 14k, 2 new hypothesis environments; Appendix H, 2 new annotated entries; references.bib, 8 new entries; hypothesis-registry.typ, 2 new entries]): Integration of 8-paper literature review on TSPO PET imaging in ME/CFS, highlighting critical methodological gaps and mechanistic insights. Single published ME/CFS TSPO PET study (Raijmakers 2021, n=9) found NO neuroinflammation using first-generation tracer; no whole-body TSPO PET studies exist in PubMed. Key finding: Barzon 2026 demonstrated peripheral inflammation reduces TSPO tracer brain influx (BBB transport confounding), potentially masking neuroinflammation. Added neuroinflammation measurement limitation environment to Chapter 7. Added TSPO dual-role speculation environment to Chapter 6 (mitochondrial dysfunction vs inflammation marker). Added two hypotheses to Chapter 14k: BBB transport confounding hypothesis (explains negative TSPO PET findings) and peripheral-inflation central-starvation hypothesis (resolves paradox of elevated peripheral TSPO with decreased brain signal). Updated hypothesis registry with 2 new entries. _Motivated by:_ @Raijmakers2021TSPOCFS — single ME/CFS TSPO PET study showing null neuroinflammation finding; @Barzon2026TSPOBBB — BB B transport confounding mechanism; @VanElzakker2019TSPOReview — comprehensive TSPO biology review. Michelle James Stanford conference data (unpublished) suggests whole-body TSPO imaging would reveal "peripheral-up, central-down" pattern, but study not yet in PubMed.
