// Generated by GenerateReaderData.java from chapter sources.
// Do not edit by hand. Depth legend (per reader group):
//   E = Essential, R = Recommended, O = Optional, S = Skip, — = no guidance.
// Reading time is words / 238 wpm. Conservative classifier:
// only explicit skip/skim/optional language downgrades a rating.
#import "tables.typ": booktabs-stroke, table-inset

#figure(
  table(
    columns: (2.2fr, 0.5fr, 0.7fr, 0.7fr, 0.9fr, 0.9fr),
    inset: table-inset,
    stroke: booktabs-stroke(7),
    [*Chapter*], [*Time*], [*Patient*], [*Caregiver*], [*Clinician*], [*Researcher*],
    [@ch:introduction], [30 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:history-of-mecfs], [14 min], [Optional], [Optional], [Recommended], [Recommended], 
    [@ch:core-symptoms], [78 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:additional-symptoms], [24 min], [Recommended], [Recommended], [—], [Recommended], 
    [@ch:diagnostic-criteria], [40 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:disease-course], [95 min], [Recommended], [Recommended], [Recommended], [Recommended], 
  ),
  caption: [Chapter-level reading routes and estimated time — Part I — Clinical Presentation],
)

#figure(
  table(
    columns: (2.2fr, 0.5fr, 0.7fr, 0.7fr, 0.9fr, 0.9fr),
    inset: table-inset,
    stroke: booktabs-stroke(16),
    [*Chapter*], [*Time*], [*Patient*], [*Caregiver*], [*Clinician*], [*Researcher*],
    [@ch:energy-metabolism], [153 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:immune-dysfunction], [123 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:neurological], [108 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:endocrine], [43 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:cardiovascular], [52 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:gut-microbiome], [30 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:brain-clearance-architecture], [7 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:genetics-epigenetics], [45 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:integrative-models], [37 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:comparative-nosology], [5 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:speculative-hypotheses], [224 min], [Recommended], [Optional], [Recommended], [Recommended], 
    [@ch:symptom-mechanisms], [89 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:causal-hierarchy], [78 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:universal-mechanisms], [33 min], [Recommended], [Recommended], [—], [Recommended], 
    [@ch:female-reproductive-axis], [13 min], [Recommended], [Recommended], [Recommended], [Recommended], 
  ),
  caption: [Chapter-level reading routes and estimated time — Part II — Pathophysiology],
)

#figure(
  table(
    columns: (2.2fr, 0.5fr, 0.7fr, 0.7fr, 0.9fr, 0.9fr),
    inset: table-inset,
    stroke: booktabs-stroke(14),
    [*Chapter*], [*Time*], [*Patient*], [*Caregiver*], [*Clinician*], [*Researcher*],
    [@ch:mechanism-treatment-map], [7 min], [Recommended], [—], [Recommended], [Recommended], 
    [@ch:symptom-management], [29 min], [Recommended], [Recommended], [Recommended], [—], 
    [@ch:urgent-action-severe], [87 min], [Recommended], [—], [—], [—], 
    [@ch:action-mild-moderate], [55 min], [Recommended], [—], [Recommended], [—], 
    [@ch:pediatric-severe], [22 min], [Recommended], [Recommended], [Recommended], [—], 
    [@ch:pediatric-ambulatory], [6 min], [Recommended], [Recommended], [Recommended], [—], 
    [@ch:medications-mechanisms], [77 min], [Recommended], [Recommended], [Recommended], [—], 
    [@ch:supplements], [52 min], [Recommended], [—], [Recommended], [Recommended], 
    [@ch:lifestyle], [77 min], [Recommended], [Recommended], [—], [Recommended], 
    [@ch:emerging-therapies], [7 min], [—], [—], [Recommended], [Recommended], 
    [@ch:integrative-treatment], [43 min], [—], [Recommended], [Recommended], [—], 
    [@ch:medication-response-reference], [110 min], [Recommended], [—], [Recommended], [Recommended], 
    [@ch:mechanistic-cascade-tracing], [457 min], [Recommended], [—], [—], [—], 
  ),
  caption: [Chapter-level reading routes and estimated time — Part III — Treatment and Management],
)

#figure(
  table(
    columns: (2.2fr, 0.5fr, 0.7fr, 0.7fr, 0.9fr, 0.9fr),
    inset: table-inset,
    stroke: booktabs-stroke(15),
    [*Chapter*], [*Time*], [*Patient*], [*Caregiver*], [*Clinician*], [*Researcher*],
    [@ch:research-methods-mecfs], [15 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:biomarker-research], [51 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:clinical-trials], [21 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:mechanistic-studies], [23 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:epidemiology-outcomes], [25 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:healthcare-systems-policy], [5 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:economic-impact], [2 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:controversies], [47 min], [Recommended], [Optional], [Recommended], [—], 
    [@ch:translational-findings], [42 min], [Recommended], [Optional], [—], [Recommended], 
    [@ch:global-perspectives], [1 min], [Recommended], [Optional], [—], [Recommended], 
    [@ch:research-infrastructure], [23 min], [Optional], [Recommended], [—], [—], 
    [@ch:patient-generated-knowledge], [2 min], [Recommended], [Optional], [Recommended], [Recommended], 
    [@ch:proposed-studies], [115 min], [Optional], [Recommended], [—], [—], 
    [@ch:research-proposals-index], [1 min], [Recommended], [Optional], [—], [Recommended], 
  ),
  caption: [Chapter-level reading routes and estimated time — Part IV — Research and Evidence],
)

#figure(
  table(
    columns: (2.2fr, 0.5fr, 0.7fr, 0.7fr, 0.9fr, 0.9fr),
    inset: table-inset,
    stroke: booktabs-stroke(9),
    [*Chapter*], [*Time*], [*Patient*], [*Caregiver*], [*Clinician*], [*Researcher*],
    [@ch:modeling-foundations], [17 min], [Recommended], [—], [Recommended], [Recommended], 
    [@ch:energy-metabolism-models], [40 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:immune-system-models], [29 min], [—], [—], [Recommended], [Recommended], 
    [@ch:neuroendocrine-models], [36 min], [—], [—], [Recommended], [Recommended], 
    [@ch:integrated-systems], [51 min], [—], [—], [Recommended], [Recommended], 
    [@ch:temporal-evolution], [47 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:predictive-applications], [22 min], [Recommended], [Recommended], [Recommended], [Recommended], 
    [@ch:causal-hierarchy-formal], [25 min], [Recommended], [Recommended], [Recommended], [Recommended], 
  ),
  caption: [Chapter-level reading routes and estimated time — Part V — Mathematical Modeling],
)

