#import "../../../../shared/environments.typ": *

=== Metabolic Trap: IDO-Kynurenine Pathway
  <sec:kynurenine-cascade>

*Certainty: 0.45.* IDO-driven kynurenine pathway dysregulation documented in ME/CFS (elevated kynurenine/tryptophan ratio, elevated quinolinic acid in CSF, reduced serotonin in CSF). The cascade has three pharmacologically distinct arms: serotonin depletion, quinolinic acid-mediated NMDA excitotoxicity, and kynurenic acid-mediated NMDA antagonism. Each arm produces different symptoms and responds to different drugs. The diagnostic task is to determine which arm(s) are dominant in a given patient.

#include "subsubsec-01-cascade-ido-kynurenine-serotonin-depletion-quinkyna-imbalance.typ"
#include "subsubsec-02-step-h1-ido-upregulation-the-shared-upstream-trigger.typ"
#include "subsubsec-03-step-h2a-serotonin-depletion-the-5-ht-arm.typ"
#include "subsubsec-04-step-h2b-quinolinic-acid-nmda-excitotoxicity-the-glutamate-arm.typ"
#include "subsubsec-05-step-h2c-kynurenic-acid-vs-quinolinic-acid-imbalance-the-astrocyte-arm.typ"

#synthesis(title: [Serotonin Supplementation for ME/CFS: No Demonstrated Benefit, with a Differentiated Mechanistic Assessment])[
No direct ME/CFS trial demonstrates that tryptophan or 5-HTP supplementation changes any outcome; that negative fact is firm. But whether a supplement *could* act is not a single question — it splits by target compartment, and the two compounds differ. Tryptophan is the weaker candidate on mechanistic grounds: in normal physiology roughly 95% of dietary tryptophan enters kynurenine catabolism rather than serotonin synthesis (@fig:tryptophan-normal), and chronic inflammation raises that fraction by inducing IDO/TDO (elevated kynurenine/tryptophan ratio, reduced serotonin; Section @sec:medication-reference) — so oral tryptophan largely feeds the diverting pathway it is meant to bypass, and can worsen brain fog via quinolinic acid in IDO-saturated patients. 5-HTP is not an IDO substrate (Section @sec:5-htp, ch29), so it escapes that specific diversion; its limitation is different and location-specific. Oral 5-HTP is predominantly decarboxylated *peripherally* to serotonin, which does not cross the blood--brain barrier — so for a *central* serotonin deficit (reduced CSF serotonin is documented at the opening of this section, certainty 0.45) oral 5-HTP is a route-of-delivery failure.

That central failure does not, however, extinguish the peripheral hypothesis. The chapter's own integrative model treats peripheral serotonin — synthesized by gut enterochromaffin cells and signalling through vagal afferents — as a separate, candidate multi-system lesion (@hyp:peripheral-serotonin-convergence, cert 0.50; @syn:peripheral-serotonin-depletion-model). Under that model, 5-HTP acting peripherally is on-target rather than a miss, and 5-HTP is established to raise serotonin levels in clinical settings (Section @sec:5-htp, ch29); what is untested is whether this improves ME/CFS outcomes. The evidence therefore supports a differentiated conclusion: no supplement is demonstrated to benefit ME/CFS; tryptophan's rationale is undermined by diversion and it carries a worsening risk; 5-HTP's *central* rationale is undermined by the blood--brain barrier, but its *peripheral* (gut--vagal) effect is a plausible and unvalidated hypothesis — a genuine open question, not a disproof. Absence of RCT evidence means benefit is not established, not that none is possible; per-patient flux control (Section @subsec:sapropterin-bh4, ch29) and the location of the serotonin deficit remain unresolved, and wholesale suppression of the kynurenine pathway could even worsen the NAD#super[+] deficit the mitochondrial model describes (Section @sec:map-nad, ch22).

The honest value of the serotonin arm is therefore diagnostic hypothesis-testing rather than treatment, and even that is a *candidate* probe: a controlled, clinician-supervised challenge that distinguishes tryptophan-worsening (consistent with IDO saturation) from tolerably-null-tryptophan-with-5-HTP-improvement (consistent with a tryptophan-hydroxylase bottleneck) may help localize which mechanism dominates in an individual, but the readout is unblinded, unvalidated, and confounded by placebo and by the differing bioavailability of the two compounds, so a positive response cannot establish that serotonin depletion is the cause of the illness.

*Safety:* 5-HTP must not be combined with serotonergic agents — SSRIs, SNRIs, MAOIs, TCAs, mirtazapine, tramadol, triptans, ondansetron, linezolid, or other drugs that raise serotonin — because of serotonin-syndrome risk; this is a real, potentially life-threatening interaction requiring medical review. Tryptophan supplementation that causes worsening must be stopped. No dosing, safety, or efficacy data exist in ME/CFS; nothing here is a treatment recommendation or a basis for self-treatment.
] <syn:serotonin-supplementation-potency> 

