#import "../../../../shared/environments.typ": *

==== The Inverted U-Curve as a Diagnostic Pattern
<sec:inverted-u-curve>

*Certainty: 0.30.* Inverted-U dose-response is documented for LDN in ME/CFS and is a well-established general pharmacology principle (hormesis as the default dose-response model, not the exception @Calabrese2002hormesisHistory @CalabreseBaldwin2003toxicologyRethinks @Calabrese2010hormesisCentral). Catecholamine inverted-U at prefrontal D1/α2A receptors is a canonical neuroscience finding @Arnsten2011catecholaminePFC @Cools2011invertedU. Extension to specific drug classes below is mechanistic inference. See @ch:integrative-models for the unifying hormesis framework.

Some drugs produce benefit at low doses that disappears or inverts at higher doses. This inverted U-curve is not a failed titration — it is a diagnostic pattern indicating bidirectional regulation of the target system:

- *LDN:* Benefit at 0.5--4.5 mg (TLR4 antagonism enhancing endorphin tone). At 50 mg, full mu-opioid blockade eliminates the endorphin compensation that was maintaining mood and pain regulation -> the benefit inverts. The transition from clinical LDN dose (0.5--4.5 mg, TLR4 antagonism) to 50 mg (full mu-opioid antagonism) represents dose-dependent target selection — a different receptor engages — rather than a second inversion on a single dose-response curve. A *within-range* inversion can occur at 0.5--4.5 mg when the TLR4 hormetic window is the dominant therapeutic mechanism: low-dose TLR4 blockade (0.5--1.5 mg) triggers Nrf2-mediated compensatory anti-inflammatory priming (M1 to M2 phenotype shift), but higher doses within the LDN range remove the basal TLR4 tone needed to sustain this compensatory response — consistent with a biphasic microglial metabolic switch documented in vitro (@Kucic2021LDNmicroglia). The dose at which this within-range inversion occurs identifies whether the patient's therapeutic mechanism is the TLR4 hormetic window (inversion below 2 mg) or opioid compensatory upregulation (monotonic benefit across the clinical LDN range, target-selection transition only at 50 mg). @Dara2023 @Calabrese2021Nrf2 @Toljan2018
- *Aripiprazole:* At low occupancy (low dose), D2 partial agonism provides net agonism in a dopamine-deficient system → improvement. At higher occupancy (higher dose), the antagonist property dominates → D2 blockade worsens the dopamine deficit → improvement inverts. The dose at which the inversion occurs measures receptor reserve: inversion at 1 mg → low receptor reserve (few receptors, each one's agonism mattered); inversion at 5 mg → high receptor reserve (many receptors, many must be blocked before net effect inverts). This is a canonical partial agonist inverted-U — the net effect inverts when occupancy crosses 50% and the antagonist component exceeds the endogenous agonist deficit. @Sun2020yinYangHormesis
- *Beta-blockers:* Low-dose β1 blockade reduces HR without impairing metabolism. At higher doses, β2 blockade removes the lipolysis fallback → fatigue worsens beyond HR improvement. The inversion occurs at the dose where β1/β2 selectivity is lost. The dose at which fatigue worsens (not just HR reduction) identifies the metabolic contribution of β2-AR signaling. This follows the Yerkes-Dodson inverted-U principle: moderate adrenergic tone optimizes function; excessive blockade impairs it @Calabrese2008yerkesDodson.
- *Corticosteroids:* Low-dose (physiological replacement, 5--10 mg prednisone) may improve immune regulation without immunosuppression. High-dose (1 mg/kg) causes HPA axis suppression and rebound crash on taper. The inverted U identifies the dose at which the drug transitions from physiological modulation to pharmacological override of the HPA axis.
- *DORAs:* At low dose, partial orexin blockade suppresses nocturnal arousals → improved sleep maintenance. At higher doses, complete orexin blockade → sleep paralysis, complex sleep behaviours, or daytime hypersomnia. The inverted U identifies the orexin tone floor — the dose at which blockade exceeds the system's residual orexin production. If inversion occurs at 25 mg daridorexant → severe orexin deficiency (consistent with orexin-suppression model). If inversion only occurs at 50 mg → mild-to-moderate orexin suppression.
- *Rapamycin (sirolimus):* At 1--3 mg/week, mTORC1 inhibition restores autophagy and mitophagy by disinhibiting ULK1 → clearance of damaged mitochondria and protein aggregates. At higher cumulative exposure, mTORC2 inhibition dominates → immunosuppression, insulin resistance, and hyperlipidaemia. The dose at which mTORC2 side effects emerge measures the chronic:mTORC1:mTORC2 selectivity ratio for that patient. If immunosuppression at 1 mg/week → mTORC2 is extremely sensitive; rapamycin's therapeutic window is narrower than the typical 1--3 mg/week range. If no mTORC2 effects at 5 mg/week → wide mTORC1:C2 selectivity; rapamycin's therapeutic window extends beyond the standard dose range. @Sarbassov2006rapamycin @Lamming2012rapamycin
- *Allopregnanolone:* At low concentrations (1--5 nM, luteal-phase equivalent), allopregnanolone as a GABA-A positive allosteric modulator paradoxically increases anxiety and negative mood. At higher concentrations (>10 nM, pregnancy-level), the same compound produces sedation and anxiolysis — a biphasic concentration-response curve documented in healthy women @Andreen2009allopregnanoloneBiphasic. The inversion at low concentrations has diagnostic relevance for ME/CFS: if a patient's symptom severity worsens during the luteal phase when allopregnanolone is rising from low to moderate levels → the patient may be in the anxiogenic arm of the biphasic curve. If severity improves as allopregnanolone rises further in pregnancy → the patient may have transited into the anxiolytic arm. This predicts that patients in the anxiogenic luteal phase would require doses that push concentration past the inversion point — but the clinical dose to achieve this in ME/CFS is not established, brexanolone/zuranolone carry REMS restrictions and risk of excessive sedation, and no dosing data exist for this population. This is a mechanistic inference framework only — not a treatment recommendation.
- *Guanfacine:* Low-dose (0.5--1 mg) selectively activates postsynaptic α2A receptors in PFC → improved cognition. Higher doses (2--4 mg) activate presynaptic α2A autoreceptors on LC neurons → reduce NE release broadly → cognitive benefit inverts as the global NE suppression overwhelms the PFC-specific benefit. The dose at which inversion occurs measures the PFC-to-global α2A sensitivity ratio.
- *Gabapentinoids:* Low-dose (100--300 mg gabapentin) provides pain relief through α2δ-CaV channel block on pathological pain circuits. Higher doses produce global neurotransmitter release suppression → cognitive impairment, sedation. The inversion identifies the dose at which α2δ block transitions from pathological-circuit-selective to global. If inversion at 300 mg → narrow therapeutic window; α2δ channels are uniformly expressed and non-selectively blocked. If inversion at 1,200+ mg → wide therapeutic window; pathological circuits have higher α2δ expression than physiological circuits, conferring natural selectivity.
- *Duloxetine:* Low-dose (20--30 mg) primarily blocks 5-HT reuptake → serotonergic benefit (mood, descending pain modulation). At 60+ mg, NE reuptake inhibition dominates → sympathetic activation → worsening of orthostatic intolerance, tachycardia. The inverted U identifies the dose at which NE reuptake inhibition exceeds the patient's orthostatic tolerance. If inversion at 30 mg → severe orthostatic vulnerability to NE; duloxetine's NE component is harmful at any dose — use an SSRI for serotonergic benefit alone. If inversion at 90 mg → good orthostatic reserve; duloxetine's SNRI mechanism is accessible. The catecholamine inverted-U at prefrontal D1/α2A receptors @Arnsten2011catecholaminePFC explains why NE reuptake inhibition optimizes cognition only within a narrow concentration window — exceeding it impairs cognitive function even without orthostatic intolerance.
- *Antihistamines (H1):* Low-dose cetirizine 5--10 mg blocks peripheral H1 → MCAS symptom relief. At 20--40 mg, CNS H1 blockade → sedation. The inverted U identifies the dose at which CNS H1 penetration occurs — this dose IS the BBB permeability measurement for cetirizine in that patient. If sedation at 10 mg → BBB is highly permeable to this H1; use fexofenadine (P-gp substrate, minimal CNS penetration) instead. If no sedation even at 40 mg → BBB impermeable or CNS H1 receptors desensitized.
- *Modafinil:* Low-dose (50--100 mg) blocks DAT → synaptic DA increase → cognitive benefit. At 200+ mg, histaminergic/orexin activation → insomnia, anxiety. The inverted U identifies the dose at which DAT occupancy saturates and the drug's secondary mechanisms (histamine, orexin) become dominant. If inversion at 100 mg → the cognitive benefit is from low-level DAT block only; the histaminergic/orexin systems contribute only side effects. If inversion at 300 mg → the histaminergic/orexin systems are tolerant to activation; the patient can benefit from higher doses. The D1 inverted-U at prefrontal cortex @Cools2011invertedU @Cools2022neuromodulationPFC explains why excessive DAT blockade impairs cognition: prefrontal DA concentration has a narrow optimum beyond which D1 overactivation impairs working memory.

*Diagnostic logic of the inverted U:* The drug has two competing effects that dominate at different occupancy levels. The dose at which the U inverts reveals the relative receptor reserve, the endogenous tone of the target system, and the width of the therapeutic window. A narrow inverted U (benefit only at the lowest dose) = fragile system with minimal reserve. A wide inverted U (benefit across a broad dose range) = robust system with high reserve. *Boundary condition:* If the offending symptom at the higher dose is identical to the disease symptom being treated (e.g., fatigue worsens at higher dose of a fatigue-targeting drug like modafinil), the inverted-U interpretation is confounded and cannot distinguish therapeutic window narrowing from simple dose-dependent adverse effect. The inverted-U diagnostic framing is valid only when the higher-dose symptom is physiologically distinct from the target symptom (e.g., orexin→insomnia rather than fatigue, β2→metabolic rather than HR) — or when the drug's mechanism at the higher dose is independently characterized.

*Consequence:* If a drug works at low dose and stops working at a higher dose, the correct response is not "drug failed" — it is "the U inverts at dose X, which tells you the target system's receptor reserve at occupancy level Y." Reduce to the effective dose; do not abandon the drug class.
*Origin:* mechanistic-pathway-tracing.
