#import "../../shared/environments.typ": *

#include "intro-preamble.typ"
#include "sec-01-developing-a-treatment-plan/sec-01-developing-a-treatment-plan.typ"
#include "sec-02-treating-comorbidities/sec-02-treating-comorbidities.typ"
#include "sec-03-personalized-medicine-approaches/sec-03-personalized-medicine-approaches.typ"
#include "sec-04-primary-mechanism-map-causal-loops-detection-and-targeted-interventions/sec-04-primary-mechanism-map-causal-loops-detection-and-targeted-interventions.typ"
#include "sec-05-combination-therapies/sec-05-combination-therapies.typ"
#include "sec-06-cross-domain-medical-parallels-learning-from-other-fields/sec-06-cross-domain-medical-parallels-learning-from-other-fields.typ"
#include "sec-07-novel-mechanistic-hypotheses-and-research-opportunities/sec-07-novel-mechanistic-hypotheses-and-research-opportunities.typ"
#include "sec-08-working-with-healthcare-providers/sec-08-working-with-healthcare-providers.typ"
#include "sec-09-severity-stratified-metabolic-reserve-building-protocol/sec-09-severity-stratified-metabolic-reserve-building-protocol.typ"
#include "sec-10-connective-tissue-preservation-strategies/sec-10-connective-tissue-preservation-strategies.typ"
#include "sec-11-thermal-combination-protocols/sec-11-thermal-combination-protocols.typ"
#include "sec-12-math-model-extensions-for-thermoregulation/sec-12-math-model-extensions-for-thermoregulation.typ"
#include "sec-13-additional-math-model-extensions-for-thermoregulation/sec-13-additional-math-model-extensions-for-thermoregulation.typ"
