#import "../../../../shared/environments.typ": *

=== Pattern 6 — Symptom-Specific Dissociation
<sec:pattern-dissociation>

*Certainty: 0.25.* The dissociation logic below is mechanistic inference. The diagnostic claim — that two symptoms diverging at a drug's node proves they have different mechanisms — is logical but untested as a formal diagnostic method.

A drug may improve one symptom while leaving another untouched, or worsen one while improving another. This dissociation is diagnostic: it proves that the two symptoms diverge at or above the drug's node — they are maintained by different mechanisms in that patient.

*Dissociated improvement (symptom X improves, symptom Y does not):*
- *Guanfacine improving brain fog but worsening fatigue:* Prefrontal α2A receptors mediate cognitive function — guanfacine activates them, improving fog. But central NE suppression removes sympathetic compensation for the energy deficit → fatigue worsens. The diagnostic inference: brain fog and fatigue are *different nodes* in this patient. The cognitive lesion is prefrontal noradrenergic; the energy lesion is downstream of central sympathetic tone. Rate-limiting mechanisms diverge at the LC-NE projection.
- *Pyridostigmine improving standing tolerance but worsening supine symptoms:* Cholinergic tone was needed for orthostasis (vagal enhancement compensates for standing sympathetic withdrawal). But supine cholinergic activity was already excessive — the autonomic set-point is pushed into parasympathetic overdrive at rest. The drug improves one state (standing) by exacerbating the other (supine). Diagnostic: the autonomic set-point is wrong — the system oscillates between sympathetic underdrive (standing) and parasympathetic overdrive (supine), and improving one side unmasks the imbalance on the other.
- *Aripiprazole improving motivation/anhedonia but worsening brain fog:* D2/D3 partial agonism corrects the mesolimbic dopamine deficit (motivation, reward), confirming DA receptor-level pathology. But cognitive fog does not improve — the cognitive bottleneck is not dopaminergic. Either glutamatergic (PFC NMDA hypofunction), cholinergic (basal forebrain), or inflammatory. The dissociation localizes two separate lesions: DA-dependent motivation and non-DA-dependent cognition.
- *Midodrine improving orthostatic HR but worsening supine hypertension:* Peripheral α1 agonism compensates for standing venous pooling (neuropathic POTS). But at rest, the same α1 agonism increases afterload in a supine position where preload is already restored — producing supine hypertension. Diagnostic: confirms neuropathic POTS (denervated legs, intact supine vasculature). The treatment unmasks the asymmetry: the problem is selective to standing, not a generalized vascular tone deficit.
- *Antihistamines (H1) improving pruritus but worsening fatigue:* H1 blockade reduces mast-cell-driven itching (MCAS confirmed). But sedation from CNS H1 blockade worsens daytime fatigue — the histaminergic wakefulness system was compensating for an orexin deficit. Removing histaminergic tone unmasks the orexin deficiency. Diagnostic: two separate histamine-dependent systems: peripheral MCAS (histamine drives symptoms) and CNS wakefulness (histamine maintains function). The drug exposes that they are served by the same receptor but with opposite clinical significance — block one, lose the other. This patient needs a mast cell stabilizer (ketotifen, which stabilizes at lower doses than its H1 sedation threshold) rather than pure H1 antagonist.
- *Gabapentinoids improving neuropathic pain but producing disabling cognitive fog:* α2δ-CaV channel blockade reduces abnormal pain signaling — confirming central sensitization with α2δ-CaV channel involvement. But cognition is also dependent on α2δ-CaV-mediated neurotransmitter release in PFC and hippocampus — fog emerges because the same channel that mediates pathological pain also mediates physiological cognition. Diagnostic: the central sensitization is α2δ-CaV dependent (a subtype of central sensitization, not NMDA/P2X7/cytokine-driven). The dissociation identifies the specific calcium channel involved but also reveals that the channel cannot be blocked without cognitive cost. Try PEA (PPAR-α, no CaV involvement) for the same pain mechanism. If PEA works → confirms pain is neuroinflammatory (glial), not α2δ-CaV voltage-gated-channel-driven.
- *Duloxetine improving mood but worsening orthostatic intolerance:* SNRI-mediated NE reuptake inhibition improves prefrontal NE → mood benefit (confirming NE deficiency for mood). But peripheral NE reuptake inhibition increases standing NE release → vasoconstriction → already-compromised capacitance vessels cannot accommodate → worsening OI. Diagnostic: the NE deficiency for mood is central (PFC); the NE excess for vasculature is peripheral. The dissociation localizes two different NE system states: central deficiency vs. peripheral overactivity — the hallmark of DBH-level catecholamine dysregulation (@ach:catecholamine-deficit). The brain has too little NE, the periphery has too much. Use atomoxetine (pure NRI, no 5-HT) if mood benefit is the goal; use guanfacine (central α2A, no peripheral NE increase) if cognition is the goal.
- *Modafinil improving wakefulness but impairing cognitive precision (wired, not functional):* DAT blockade → increased synaptic DA → wakefulness and arousal (confirmed: DAT functional, DA release intact). But cognition worsens — the prefrontal DA increase is excessive, pushing past the optimal DA concentration for PFC working memory into overactivation (inverted U for PFC DA). Diagnostic: the PFC DA system is hyper-responsive — the same DAT blockade that produces useful wakefulness at the brainstem/hypothalamic level produces cognitive impairment at the cortical level. The DA system has organ-level dissociation: subcortical DA is deficient (wakefulness benefits), cortical DA is oversensitive (cognition worsens). This patient needs a brain-region-selective DA strategy — low-dose aripiprazole (partial agonist with prefrontal 5-HT1A-mediated stabilization) rather than DAT blockade.
- *DORAs improving sleep maintenance but causing daytime hypersomnia:* OX1R/OX2R blockade suppresses nocturnal orexin surges (confirmed: orexin-mediated awakenings were the sleep maintenance problem). But the blockade persists into daytime → residual orexin antagonism worsens daytime hypersomnia. Diagnostic: orexin tone is marginal — blocking it at night improves sleep but the residual blockade exceeds the system's daytime recovery. The dose at which daytime hypersomnia appears IS the orexin reserve measurement. If daytime hypersomnia at 25 mg → severe orexin deficiency; the patient needs orexin agonism (pitolisant), not antagonism, despite the night-time benefit. If daytime hypersomnia only at 50 mg → mild orexin suppression; 25 mg is the correct dose.
- *Aripiprazole improving sleep but not PEM or energy — and sleep remains unrefreshing:* D2/D3 partial agonism facilitates sleep initiation and maintenance (D2 receptors are expressed on VLPO — the ventrolateral preoptic nucleus, the brain's primary sleep-promoting nucleus; D2 agonism in VLPO suppresses arousal-promoting regions, facilitating NREM sleep onset). But: PEM and energy do not improve → the basal ganglia and dopaminergic motor/motivation circuits are NOT the rate-limiting bottleneck for energy or PEM generation. Sleep improves but remains unrefreshing → glymphatic clearance is still impaired. The VLPO-sleep D2 receptor population is functional (the drug successfully facilitates sleep ON and maintenance), but the downstream glymphatic machinery — LC-NE vasomotion coupling, AQP4 astrocyte endfoot localization, or perivascular space patency — is independently damaged. Diagnostic: (a) D2 receptors in VLPO are present and responsive → the sleep deficit has a dopaminergic component (confirmed); (b) PEM and energy deficits are non-dopaminergic — the basal ganglia D2/D3 circuits are not the bottleneck (energy is ATP-level or non-DA neurotransmitter-level); (c) the glymphatic system is independently impaired — sleep duration is adequate but clearance is not (consistent with alpha-delta sleep, LC-NE overactivity during purported SWS, or AQP4 mislocalization independent of sleep onset). This pattern traces three separate lesions: sleep initiation (D2-sensitive, aripiprazole fixes), PEM/energy (non-D2, ATP or non-dopaminergic), and glymphatic clearance (sleep-independent dysfunction). Probe sequence: add bedtime melatonin or prazosin to test LC-NE-mediated glymphatic failure (@sec:glymphatic-cascade); add LDN to test neuroinflammatory contribution; supine sleep positioning (@sec:glymphatic-cascade M3) to test mechanical drainage. If melatonin improves morning unrefreshing → LC-NE overactivity during sleep was suppressing glymphatic clearance even though aripiprazole improved sleep ON. If none of these restores refreshing sleep → AQP4 mislocalization or perivascular obstruction, not NE-mediated vasoconstriction, is the glymphatic lesion. If LDN + aripiprazole together restore refreshing sleep → neuroinflammation at VLPO (sleep on) combined with independent glymphatic inflammation (clearance) — dual-sleep-pathology.
- *L-DOPA/carbidopa improving apathy but worsening orthostatic hypotension:* L-DOPA → dopamine synthesis → mesolimbic DA → apathy improves (confirmed: DA deficiency for motivation). But peripheral conversion to DA → D2-mediated vasodilation + central D2 sympathetic suppression → OH worsens beyond tolerable threshold. Diagnostic: AADC is active peripherally (carbidopa dose insufficient to block it fully), and D2 receptors are supersensitive in both mesolimbic (benefit) and cardiovascular (side effect) systems. The same DA deficiency that makes L-DOPA work also makes it produce OH at doses where carbidopa's peripheral block is incomplete. Increase carbidopa or switch to a direct D2/D3 agonist with better central selectivity (pramipexole).

*Symptom swap (total burden unchanged, but distribution shifts):*
- The drug changes which symptom dominates without changing total functional capacity. This occurs when the energy bottleneck is fixed and the drug only redirects allocation: aripiprazole shifts allocation from physical to cognitive; pyridostigmine shifts from cognitive to autonomic. The total energy pool is unchanged — the drug only changes which demand-response system gets priority. Diagnostic: the primary lesion is an energy production bottleneck, and all downstream symptoms are triage artifacts. Treating any downstream symptom merely redistributes the deficit.

*Consequence:* When a drug improves symptom X but not Y, the two symptoms are mechanistically distinct in that patient. This is one of the highest-information outputs of a single drug trial — it traces the causal architecture of the symptom complex without any additional testing. Track which symptom improved, which didn't, and which worsened: the pattern maps the causal topology.
*Origin:* mechanistic-pathway-tracing.
