#import "../../../../../shared/environments.typ": *

#speculation(title: [Fasting-UPR-Gut-Liver Axis: ER Stress in Intestinal Epithelial Cells])[
*Certainty: 0.30.* Intermittent fasting or prolonged fasting may induce endoplasmic reticulum (ER) stress in intestinal epithelial cells (IECs) of ME/CFS patients, triggering the unfolded protein response (UPR) in a gut-specific manner that propagates to hepatic inflammation via the gut-liver axis. Fasting deprives IECs of luminal nutrients, particularly butyrate (their preferred fuel, Section @sec:microbiome), forcing metabolic reliance on glutamine and ketone bodies. In energy-compromised ME/CFS IECs, this fuel switch may exceed the mitochondrial capacity, producing ER stress via ATP insufficiency for protein folding.

*Mechanism.* IECs are high-turnover cells with substantial protein synthesis demands (digestive enzymes, mucins, tight junction proteins). During fasting, the loss of butyrate as primary energy source shifts metabolism to glutamine oxidation. If mitochondrial reserve is insufficient (consistent with documented ME/CFS mitochondrial dysfunction, Chapter @ch:energy-metabolism), ATP production falls short of protein folding demand, causing: (1) unfolded protein accumulation in the ER → PERK/eIF2alpha activation; (2) IRE1alpha-XBP1s pathway activation driving inflammatory cytokine production (IL-6, TNF-alpha); (3) ATF6-mediated CHOP expression → IEC apoptosis if UPR fails to restore homeostasis. Apoptotic IECs release DAMPs (HMGB1, ATP) into the portal circulation, activating hepatic Kupffer cells via TLR4 and NLRP3 → liver inflammation → systemic cytokine elevation. HMGB1's redox-dependent pro-inflammatory activity (disulfide-HMGB1 signals via TLR4 while fully reduced HMGB1 is chemotactic) provides a mechanistic link between fasting-induced ER stress and the type of inflammatory output observed @Ibrahim2026HMGB1Neuroinflammation @Chen2026HMGB1pCTSLAxis. The liver responds by producing acute-phase proteins (CRP, serum amyloid A) that further impair systemic energy metabolism.

*ME/CFS context.* ME/CFS patients often report that fasting improves cognitive clarity temporarily (patient-reported — not yet studied formally), but prolonged fasting or caloric restriction triggers PEM-like deterioration. This biphasic response may reflect initial UPR adaptation (ATF4-driven metabolic flexibility improvement) followed by ER stress decompensation when mitochondrial reserve runs out. The gut-liver axis connection also links to hepatic insulin resistance (Section @sec:insulin-glucose in Chapter @ch:endocrine) — liver inflammation from IEC-derived DAMPs would impair hepatic gluconeogenesis regulation and contribute to the metabolic inflexibility documented in ME/CFS.

*Falsifiable predictions.* (1) ME/CFS IECs (organoid cultures from patient biopsies) will show elevated UPR markers (p-eIF2alpha, XBP1s, CHOP) and reduced ATP content compared to controls under fasting-mimicking conditions (low glucose, low butyrate). (2) ME/CFS plasma will show elevated IEC-derived DAMPs (I-FABP, REG3alpha) during prolonged fasting (>16 h) but not after short-term fasting (12 h), correlating with UPR markers in blood. (3) Portal vein-equivalent markers (GLP-2, FGF19) in ME/CFS will show an altered fasting-response profile consistent with IEC ER stress. (4) Ursodeoxycholic acid (UDCA, an ER stress-reducing bile acid) will prevent fasting-induced pem-like deterioration in a placebo-controlled challenge trial.

*Limitations.* IEC UPR has never been studied in ME/CFS. Organoid cultures from ME/CFS patients do not exist. The fasting-UPR-gut-liver chain relies on general cell biology (well-established in other contexts) but has no ME/CFS-specific evidence. Patient reports of fasting effects are anecdotal; no controlled study of fasting in ME/CFS exists. The ER stress model predicts that fasting is detrimental in ME/CFS, but some patient reports suggest benefit — this may reflect inter-individual differences in mitochondrial reserve.
] <spec:fasting-upr-gut-liver>
