#import "../../../../shared/environments.typ": *

=== Circulating Cell-Free Mitochondrial DNA and Mitophagy Signalling
<sec:cfmtdna-mitophagy>

Circulating cell-free mitochondrial DNA (ccf-mtDNA) is released from cells during both physiological processes (exercise, mitophagy) and pathological states (cell death, inflammation). Its levels therefore reflect the balance between mitochondrial turnover, damage, and clearance. In acute SARS-CoV-2 infection, markedly elevated ccf-mtDNA signals massive mitochondrial release during cell death and predicts adverse outcomes. By contrast, Matits et al.\  ($n = 228$; EPILOC cohort) reported nominally lower ccf-mtDNA in Long COVID patients compared to recovered controls, though the finding did not reach statistical significance after full covariate adjustment ($p = 0.089$; partial $eta^2 = 0.01$--$0.02$; $p = 0.038$ only in a sensitivity analysis excluding high-CRP outliers). A preliminary case series (Szögi et al.\ ; $n = 5$ Long COVID, $n = 5$ ciliary dyskinesia controls) also reported reduced ccf-mtDNA alongside mitochondrial ultrastructural abnormalities, though the extremely small sample and non-standard controls preclude generalization.

#hypothesis(title: [Impaired Mitophagy Traps Damaged Mitochondria in Long COVID])[
*Certainty: 0.35.* _If_ ccf-mtDNA is genuinely reduced in Long COVID (a finding that did not reach conventional significance after full covariate adjustment in the sole adequately powered study), one interpretation is that impaired mitophagy prevents clearance and extracellular release of damaged mitochondria, causing their intracellular accumulation. This would produce chronic cellular stress and energy deficits without the external damage signal seen in acute infection  . This connects to the mitophagy coordination pathway proposed in Section @sec:thyroid-mito-regulation. If the ERR$alpha$/ULK1/DRP1 fission-mitophagy-biogenesis cycle is disrupted, damaged organelles persist. However, the deconditioning alternative has not been excluded---physically active individuals have higher ccf-mtDNA, and Long COVID patients are typically less active than recovered controls.

*Testable prediction:* Muscle biopsy from Long COVID patients with low ccf-mtDNA should show increased mitochondrial PINK1/Parkin co-localization (stalled mitophagy) compared to recovered controls with normal ccf-mtDNA. Falsified if mitophagy markers are normal or reduced despite low ccf-mtDNA.
] <hyp:impaired-mitophagy-longcovid>

In ME/CFS, Tsilioni et al.\  found exosome-associated mtDNA _elevated_ after exercise\ ---a different compartment, different timing, and potentially a different mechanism (active exosomal secretion rather than passive release from cell death). Quantitative details (sample size, effect size) for the Tsilioni study are not available from the abstract, and the finding has not been independently replicated; it should be weighted accordingly. Whether resting ccf-mtDNA is also altered in ME/CFS is unknown (see @spec:cfmtdna-distinguish in Section @sec:cross-disease for the cross-disease comparison).

*Post-hoc observation: IgG immune complexes and the mitophagy block.*
The following connection was constructed after both the Liu and Matits findings were available; it was not predicted by either study and should be read as a hypothesis-generating observation, not as a deduction. The IgG immune complex finding (Section @sec:igg-mito-disruption above) could in principle relate to the impaired mitophagy hypothesis. Liu et al.\ @Liu2026IgGcomplexes showed that IgG from ME/CFS patients induces mitochondrial fragmentation _without_ depolarizing the fragments---spare respiratory capacity was maintained or increased. Since the canonical PINK1/Parkin mitophagy pathway requires depolarization, IgG-induced fragments that retain membrane potential might evade this clearance route, potentially contributing to intracellular accumulation. However, this reasoning has several unverified steps: (a) PINK1/Parkin dynamics have not been measured in IgG-treated cells; (b) PINK1-independent mitophagy pathways (BNIP3, FUNDC1) could clear polarised fragments; (c) the Liu experiment used ME/CFS sera while the Matits finding is in Long COVID patients; (d) the HUVEC model may not represent whole-body ccf-mtDNA dynamics. The connection remains speculative and requires direct experimental testing before it can be considered mechanistically supported.

*Deconditioning as a causal feedback loop, not merely a confound.*
Physical activity is a potent stimulus for mitophagy via AMPK activation. The deconditioning commonly seen in ME/CFS and Long COVID patients may therefore not simply confound the ccf-mtDNA measurement---it may _mediate_ the mitophagy impairment. Reduced activity $arrow.r$ reduced AMPK-stimulated mitophagy $arrow.r$ accumulation of damaged mitochondria $arrow.r$ further impaired energy production $arrow.r$ further reduced activity capacity. This creates a self-reinforcing loop in which deconditioning is both a consequence and a cause of mitochondrial quality control failure. Strict pacing, while essential for preventing PEM-mediated kindling (Chapter @ch:neurological), may paradoxically worsen this mitophagy deficit. Whether a "therapeutic window" exists---activity sufficient to maintain AMPK-mediated mitophagy signaling without crossing the PEM threshold---is an open question with direct clinical implications (see Chapter @ch:lifestyle for pacing recommendations).

#warning-env(title: [Deconditioning--Mitophagy Loop Does Not Justify Graded Exercise Therapy])[
The observation that reduced physical activity may impair AMPK-mediated mitophagy does _not_ justify graded exercise therapy (GET), which operates at intensities far above any plausible mitophagy-only threshold and carries well-documented risk of harm in ME/CFS patients. The "therapeutic window" concept---if one exists---would involve minimal activity levels (e.g., gentle movement well below the PEM threshold), not structured exercise programmes. This distinction is critical: the deconditioning loop is a mechanistic observation, not a clinical recommendation.
]

*Clinical translation:* None of the pathways described in this subsection (ccf-mtDNA, mitophagy, PINK1/Parkin) are currently testable or targetable in clinical practice. ccf-mtDNA measurement is a research-only assay. No approved drug specifically targets mitophagy in ME/CFS or Long COVID. The one provisional clinical implication is that strict rest-only approaches may have a theoretical cost; discuss gentle movement within the patient's individual PEM threshold with a pacing specialist (Chapter @ch:lifestyle). For severe or very severe patients who are bedbound, this consideration does not apply---rest is essential.

#warning-env(title: [Replication Status and Limitations])[
The mitochondrial fragmentation effect was predominantly observed in female patients; male-specific mechanisms remain unexplored. The HUVEC model relies heavily on glycolysis, which may mask oxidative phosphorylation effects that would manifest in more OXPHOS-dependent tissues (skeletal muscle, neurons). The IgG purification method did not effectively capture pentameric IgM, which may carry additional pathogenic activity. Not all ME/CFS patients' IgG induced fragmentation, consistent with disease heterogeneity. Independent replication is pending.
]


