#import "../../../../../shared/environments.typ": *
#import "/src/main/typst/lib/clinical-caution.typ": clinical-caution

==== Why Herpesvirus Antibodies Persist for Decades
<sec:herpesvirus-antibody-persistence>

Herpesvirus antibodies are commonly cited as evidence of viral reactivation in ME/CFS — but antibody titre interpretation is constrained by a body of basic immunology that is often overlooked in clinical reasoning. The persistence of antiviral antibodies decades after infection is largely the work of long-lived plasma cells (LLPCs), which maintain antibody output independently of ongoing antigenic stimulation. This does not mean that herpesvirus reactivation does not occur in ME/CFS — the evidence for abortive lytic replication and poly-herpesvirus co-reactivation is substantial (Sections @sec:abortive-lytic, @sec:poly-herpesvirus). It means that structural antigen IgG titre alone — the most commonly used clinical test — cannot distinguish between memory of a past infection and evidence of current viral activity. The implication is not that all herpesvirus serology is useless, but that its interpretation requires the right antigen targets and the right clinical context.

===== The Immunology of Lifelong Antibody Maintenance

After an acute infection, short-lived plasma cells in secondary lymphoid organs produce the initial antibody burst. A fraction of activated B cells differentiate into long-lived plasma cells that migrate to survival niches in the bone marrow, where they constitutively secrete antibody for the lifetime of the host — without requiring re-exposure to antigen, without dividing, and independently of memory B cell replenishment @Amanna2007Duration @Hammarlund2017PlasmaCell @Robinson2022LLPC.

The Amanna–Slifka longitudinal cohort (n=45, followed up to 26 years) established the quantitative foundation @Amanna2007Duration:
    - Antiviral antibody half-lives: VZV ~50 years; EBV, measles, mumps >200 years
    - By contrast, vaccine-induced antibodies to non-replicating antigens (tetanus: 11 years; diphtheria: 19 years) wane much faster
    - Memory B cell numbers did NOT correlate with serum antibody titres for 5/8 antigens tested — demonstrating that antibody levels and B cell memory are independently regulated

The Hammarlund primate model provided direct experimental confirmation @Hammarlund2017PlasmaCell: bone marrow LLPCs survived for more than a decade after sustained depletion of memory B cells. BrdU pulse-chase experiments detected plasma cells labelled at the time of vaccination still alive 10 years later without any evidence of cell division. The LLPC pool alone — without memory B cell input and without antigenic stimulation — was sufficient to maintain stable serum antibody titres.

A critical structural determinant of antibody longevity is the physical form of the antigen that drove the original response @Slifka2019Multivalency @Chackerian2020LLPC. Highly multivalent, repetitive antigen arrays — such as viral capsids and envelope glycoprotein lattices — cross-link B cell receptors with high avidity, lowering the activation threshold and preferentially driving LLPC differentiation. Herpesviruses present precisely this type of antigen: icosahedral capsids with repeating structural subunits, dense glycoprotein arrays on the viral envelope, and tegument proteins packaged at high copy number. They are structurally optimised to generate exceptionally durable antibody responses.

Robinson et al. demonstrated that LLPCs accumulate in bone marrow at a rate of approximately one cell per hour after immunisation, and that the final number scales with the duration of the germinal centre reaction @Robinson2022LLPC. This implies that the magnitude of the initial infection — the antigen load and the duration of the germinal centre response — determines long-term antibody levels, not the frequency of subsequent reactivation events.

===== What This Means for Herpesvirus Serology

The persistence of herpesvirus antibodies decades after infection is therefore expected and normal — but the picture is not binary. LLPCs provide a substantial antigen-independent baseline that persists for the host's lifetime. Against this high baseline, the contribution of any individual reactivation event to total structural antigen IgG may be modest and difficult to detect. However — and this is a critical caveat — structural antigen IgG CAN rise measurably during clinical herpesvirus reactivation: VZV IgG rises during shingles, CMV IgG rises during CMV disease, and EBV VCA/EBNA-1 IgG can rise during EBV-driven post-transplant lymphoproliferative disorder. The LLPC baseline dominates the total signal, but reactivation can contribute to it. The correct interpretive principle is therefore not "structural IgG is pure LLPC output and never indicates viral activity" — it is "structural IgG has a large antigen-independent LLPC component, and elevated titres alone, without corroborating evidence from viral DNA, viral mRNA, or lytic-cycle antibody data, are insufficient to diagnose active reactivation."

This does not mean herpesvirus reactivation does not occur in ME/CFS — the dUTPase, ALR, and poly-herpesvirus co-reactivation evidence is discussed below (Sections @sec:abortive-lytic, @sec:poly-herpesvirus). It means that antibody titre alone — particularly against structural viral antigens (VCA, gB) and latency proteins (EBNA-1, which is not a structural antigen but is functionally in the same interpretive category because it is constitutively expressed during latency) — cannot distinguish between:
    - Normal LLPC maintenance without viral activity
    - Low-level abortive lytic replication in the absence of productive infection
    - Overt lytic reactivation with infectious virion production

===== What IS a Signal of Active Viral Activity (and What Isn't)

| Antibody target | What it indicates |
|-----------------|-------------------|
| VCA IgG, EBNA-1 IgG, CMV gB IgG, VZV gE IgG | LLPC output (may reflect infection that occurred decades ago) |
| EA-D IgG (EBV early antigen diffuse) | Lytic cycle entry — but early antigen antibodies can persist for years after resolved reactivation |
| VCA IgM | Genuine herpesvirus reactivation OR recent primary infection OR nonspecific polyclonal B cell activation OR rheumatoid factor interference — cannot distinguish between these without clinical context and confirmatory testing |
| Anti-dUTPase IgG (BLLF3, U45, ORF8) | Evidence of abortive lytic replication — dUTPase is an early lytic gene product; antibody presence signals recent expression of lytic genes, not necessarily productive replication |
| Viral DNA in plasma (quantitative PCR) | Presence of cell-free virions — indicates productive lytic replication; however, may be negative during abortive lytic replication (ALR, Section @sec:abortive-lytic) where no infectious virions are produced. A negative qPCR does not exclude ALR. |
| Viral mRNA (EBER, BLLF1) in tissue | Active viral gene expression at the tissue site |

The critical interpretive principle: the bottom three rows of this table provide the strongest evidence of ongoing viral activity, but each has caveats — qPCR may be negative during ALR, viral mRNA requires tissue biopsy, and dUTPase antibodies come from a single research group without independent replication. The top rows are dominated by the LLPC baseline: isolated elevation of structural antigen or latency protein IgG, without corroborating evidence from viral DNA, viral mRNA, or lytic-cycle antibodies, is insufficient to diagnose active reactivation. Clinicians and researchers should not diagnose "active EBV" or "chronic herpesvirus reactivation" on the basis of structural antigen IgG alone.

When confirmatory testing (qPCR, EA-D, dUTPase serology) is negative or unavailable — a common clinical scenario — a time-limited valacyclovir trial with predefined stopping rules and symptom tracking remains a reasonable shared-decision option for the post-infectious subset with clinical suspicion of herpesvirus-driven pathology. This is expert opinion, supported by the two controlled positive antiviral trials (Lerner 2007, Montoya 2013) that enrolled on elevated antibody titres rather than confirmed viral replication, and is not a universal recommendation. The goal is to avoid reflexive chronic antiviral prescribing triggered by an isolated VCA IgG result, while preserving access to a therapeutic trial when the clinical picture warrants it.

===== Evidence in ME/CFS: Is Antibody Elevation Real?

The question of whether ME/CFS patients have elevated herpesvirus antibodies above the healthy seropositive baseline is not settled:

*Evidence of elevation:*
    - Palomo et al. (n=40 ME/CFS, 16 controls): elevated anti-dUTPase IgG to EBV, HHV-6, VZV; 72.5% co-expression of multiple herpesvirus antibodies vs 31% controls @Palomo2026dUTPase
    - Apostolou et al. (n=95 ME/CFS, 110 controls): elevated salivary EBNA-1 IgG and EBV-VCA IgG in ME/CFS — detected locally in saliva, not systemically in plasma @Apostolou2022Saliva
    - Loebel et al. (n=92 CFS, 50 controls): EBNA-6 repeat region IgG enhanced in CFS, though overall EBV IgG pattern "quite similar" between groups @Loebel2017EBVsero

*Evidence of no elevation:*
    - Cliff et al. (n=251 ME/CFS, 107 controls): UK ME/CFS Biobank — no differences in seroprevalence for six herpesviruses between ME/CFS and controls @Cliff2019Cellular
    - Blomberg et al. (Swedish cohort, Canada criteria): suspension multiplex immunoassay for HHV-1-7 — overall IgG anti-herpes-viral reactivities did NOT show significant differences between ME/CFS and blood donor controls @Blomberg2019HerpesvirusNull

#open-question(title: [Is Herpesvirus Antibody Elevation a Universal Feature of ME/CFS?])[

*Certainty: contested.* Two large seroprevalence studies (Cliff n=251, Blomberg) found no overall elevation; three smaller studies (Palomo, Apostolou, Loebel) found antigen-specific elevations. The contradiction is likely resolvable by antigen specificity — dUTPase (an early lytic protein) and EBNA-6 (a latency protein with human homology) may be selectively elevated while structural antigen antibodies (VCA, EBNA-1, gB) are not. If this is correct, ME/CFS is characterised by a qualitative shift in antibody fine specificity (toward lytic-cycle and cross-reactive epitopes) rather than a quantitative elevation in total herpesvirus IgG. This would explain why seroprevalence studies (which measure presence/absence of IgG against structural antigens) find no difference, while studies using lytic-cycle antigens find elevations.

*Falsifiable prediction 1:* A study measuring IgG against structural antigens (VCA, gB, gE) AND lytic-cycle antigens (dUTPase, EA-D) AND latency-protein repeat regions (EBNA-6) simultaneously in the same ME/CFS cohort should find elevations only in the lytic and repeat-region categories, not in structural antigen IgG. Falsified if structural antigen IgG is equally elevated.

*Falsifiable prediction 2:* ME/CFS patients with elevated anti-dUTPase antibodies should show higher viral DNA loads (qPCR) than patients with normal anti-dUTPase levels. Falsified if dUTPase antibody elevation is independent of viral DNA detection.

*Consequence:* If the antigen-specificity model is correct, herpesvirus serology in ME/CFS diagnosis and research should shift from measuring total IgG seroprevalence to targeted measurement of lytic-cycle antibodies (dUTPase, EA-D). Total IgG panels — the most commonly used clinical test — are uninformative.
] <oq:herpesvirus-antibody-universal>

#hypothesis(title: [Lytic-to-Structural IgG Ratio (LSR) as a Diagnostic Biomarker])[

*Certainty: 0.45.* In normal LLPC biology, the ratio of IgG against lytic-cycle herpesvirus antigens (EBV BZLF1, EA-D, dUTPase) to structural antigens (VCA-p18 — the immunodominant capsid protein measured by standard VCA IgG — EBNA-1, gB) should remain stable — both antibody types are produced by the same LLPC pool established during primary infection. If ME/CFS involves abortive lytic reactivation (preferentially boosting lytic-antigen responses via short-lived plasmablasts) or epitope-specific autoimmune drift (affecting specific lytic epitopes), the LSR will be elevated. This ratio uses each patient as their own internal control, eliminating confounding by infection timing, age, and initial antigen load. The concept directly explains the contradictory literature: structural-antigen IgG is normal (Cliff, Blomberg null findings), while lytic-antigen IgG is elevated (Palomo dUTPase, Loebel EBNA-6 repeat). A partial independent replication of dUTPase antibody elevation now exists outside the Ariza/Williams group — Maes et al. (2025) found EBV and HHV-6 dUTPase antibodies accounted for 63.7% of fatigue-depression-anxiety variance in RRMS patients, though this is a different disease population and requires confirmation in ME/CFS @Maes2025RRMSdUTPase. *Origin: brainstorm.*

The precedent from multiple sclerosis is instructive: EBNA-1 antibodies cross-react with GlialCAM specifically in MS patients, not in seropositive healthy controls @Lanz2022Nature. The pathogenic feature is the qualitative shift in antibody fine specificity — the same principle may apply in ME/CFS, where cross-reactive antibodies could target autonomic neurons, skeletal muscle, or mitochondrial antigens. The elevated titre is a byproduct of autoimmune drift, not the primary pathology.

*Falsifiable prediction:* The LSR (anti-BZLF1 IgG / anti-VCA-p18 IgG ratio) will discriminate ME/CFS from healthy seropositive controls (AUC ≥ 0.75) and correlate with symptom severity (r ≥ 0.3 with fatigue score), while neither anti-BZLF1 nor anti-VCA alone will show significant discrimination. IgG avidity (urea-wash ELISA) for anti-herpesvirus antibodies will be uniformly high (avidity index >0.6, consistent with remote past infection) — low-avidity IgG ($<$0.4) would refute the LLPC model and support recent abortive reactivation.

*Consequence:* A blood test comparing the ratio of two antibody types could distinguish ME/CFS patients with an ongoing immune problem from those with normal antibodies from past infections — providing a low-cost diagnostic tool using existing clinical assays.
] <hyp:lytic-structural-igg-ratio>

#limitation(title: [Methodological Weaknesses in the Herpesvirus Serology Literature])[
The evidence base for elevated anti-herpesvirus antibodies in ME/CFS suffers from methodological threats on both sides. The positive studies (Palomo, Apostolou, Loebel) are small, use different antigen preparations with no standardisation, and have not been independently replicated — the dUTPase findings derive from a single research group. The null studies have their own limitations: Cliff 2019 measured seroprevalence (binary ±) rather than quantitative titres, and in a population where >90% of adults are seropositive for EBV and VZV, seroprevalence cannot detect titre differences — Cliff's null result for structural antigen seroprevalence confirms universal prior infection, not absence of titre elevation. Blomberg 2019 used a suspension multiplex immunoassay whose sensitivity for detecting subtle titre differences compared to standard ELISA has not been established, and compared ME/CFS patients to blood donor controls who are systematically healthier than the general population. The question of whether herpesvirus antibody elevation exists in ME/CFS is not scientifically settled for any antigen class — the literature is too methodologically heterogeneous on both sides to support a definitive conclusion. Researchers designing studies should pre-register protocols, use ≥3 distinct antigen preparations spanning structural and lytic-cycle targets, match controls on age/sex/infection timing, and apply correction for multiple comparisons. Until a study meeting these criteria is published, the question remains open. *Origin: brainstorm.*

*Consequence:* The herpesvirus serology literature in ME/CFS is too methodologically heterogeneous to support a definitive conclusion in either direction. Researchers designing studies should pre-register their protocols, use ≥3 distinct antigen preparations spanning structural and lytic-cycle targets, match controls on age/sex/infection timing, and apply Bonferroni correction.
] <lim:herpesvirus-serology-methods>

#speculation(title: [B Cell Dysregulation as Driver of Antibody Elevation])[

*Certainty: 0.30.* An alternative to viral reactivation as the driver of elevated herpesvirus antibodies is intrinsic B cell dysregulation. Sun et al. (2024) performed scRNA-seq on peripheral blood from ME/CFS patients (n=4) and found that memory B cells in ME/CFS show a unique subtype early in pseudotime, with increased trajectory toward plasma cell differentiation — suggesting B cell overactivity @Sun2024Immunometabolic. If this finding replicates in larger cohorts, it would mean that elevated herpesvirus antibodies in ME/CFS could reflect dysregulated B cell → plasma cell differentiation rather than antigen-driven responses to viral reactivation. The certainty is low (0.30) because the finding comes from a single study with n=4 patients and n=4 controls, and the link between increased plasma cell differentiation and herpesvirus antibody titres has not been directly tested.

*Falsifiable prediction:* ME/CFS patients with elevated herpesvirus antibodies will show increased frequencies of antibody-secreting cells (CD19^low CD27^high CD38^high) in peripheral blood AND increased plasma cell numbers in bone marrow aspirates, independent of viral DNA load. Falsified if antibody elevation always correlates with detectable viral DNA.

*Consequence:* If this mechanism is confirmed, herpesvirus antibody elevation in ME/CFS would be a readout of B cell dysregulation rather than viral reactivation — changing the diagnostic and therapeutic implications entirely. Antiviral therapy would not be expected to reduce antibody titres, and the focus would shift to B cell-targeted interventions. However, this is early-stage; the finding may turn out to be a dead end.
] <spec:antibody-elevation-bcell-dysregulation>

#limitation(title: [Herpesvirus Antibody Titres Cannot Be Interpreted as Evidence of Active Infection])[
Total IgG against structural herpesvirus antigens (VCA, CMV gB, VZV gE) and latency proteins (EBNA-1) has a substantial antigen-independent component maintained by long-lived plasma cells established at primary infection — not a pure readout of the current state of the virus. LLPCs maintain antibody titres for decades without antigenic stimulation (@Amanna2007Duration, half-life >200 yr for EBV; @Hammarlund2017PlasmaCell, LLPC survival >10 yr without memory B cells). However, structural antigen IgG CAN be boosted by clinical reactivation (e.g., VZV IgG rises during shingles), so elevated titres against a high LLPC baseline are ambiguous. An elevated titre may indicate: (a) greater LLPC numbers from a more intense primary infection; (b) individual variation in bone marrow niche capacity; (c) ongoing antigenic stimulation from viral reactivation; or (d) intrinsic B cell dysregulation driving excess plasma cell differentiation (@Sun2024Immunometabolic, preliminary, n=4). The critical distinction is between detectable antibodies (universal in seropositive adults, expected from LLPCs) and significantly elevated titres above age/sex-matched norms (could reflect any of a–d). Without viral DNA (qPCR), viral mRNA (in situ hybridisation), or lytic-cycle antibody data, herpesvirus IgG titre alone is uninformative about viral activity — but when confirmatory testing is negative or unavailable, a time-limited antiviral trial with defined stopping rules remains a defensible clinical option for the post-infectious subset. This principle applies to all herpesviruses (EBV, HHV-6, CMV, VZV, HSV-1/2) and is not specific to ME/CFS — it is a general constraint on serological interpretation.

*Consequence:* Clinicians should not diagnose "chronic EBV" or "chronic herpesvirus reactivation" based on IgG serology alone, and should not initiate indefinite antiviral therapy on the basis of isolated structural antigen IgG titres. A time-limited antiviral trial with predefined stopping rules and symptom tracking is a reasonable shared-decision option when clinical suspicion is high and confirmatory testing is unavailable or negative (acknowledging that qPCR may be negative during abortive lytic replication). This balances patient safety — protecting against unnecessary long-term antiviral treatment — with access to a therapeutic trial in appropriate cases.
] <lim:herpesvirus-antibody-interpretation>

#synthesis(title: [Rethinking Herpesvirus Serology in ME/CFS])[

The evidence collectively argues that herpesvirus serology in ME/CFS has been systematically misinterpreted: the large antigen-independent LLPC baseline means that isolated structural-antigen or latency-protein IgG elevation is insufficient to diagnose active viral reactivation, while the contradictory literature on antibody elevation has not been resolved by any study to date — the evidence is too methodologically heterogeneous on both sides to support a definitive conclusion (@oq:herpesvirus-antibody-universal, @lim:herpesvirus-serology-methods). The strongest practical implication is that clinical decisions should not rest on structural antigen IgG alone (@lim:herpesvirus-antibody-interpretation) — but neither should the absence of accessible confirmatory testing preclude a time-limited therapeutic trial in appropriate patients. The dUTPase, ALR, and poly-herpesvirus evidence (Sections @sec:abortive-lytic, @sec:poly-herpesvirus) establishes that viral reactivation occurs in a subset of ME/CFS patients; what remains unresolved is how to identify that subset with available tests.

*Consequence:* The existing clinical practice of diagnosing "viral reactivation" from herpesvirus IgG panels alone is not supported by basic immunology. The path forward is: (1) use viral DNA (qPCR), viral mRNA, and lytic-cycle antibody testing where available — with the caveat that qPCR may be negative during abortive lytic replication; (2) where these are unavailable, a time-limited antiviral trial with predefined stopping rules remains a reasonable clinical option for the post-infectious subset; (3) research should focus on validating antigen-specific biomarkers (including dUTPase antibodies, pending independent replication) rather than continuing to measure total IgG seroprevalence.
] <syn:herpesvirus-antibody-persistence-model>

==== What Antiviral Response Reveals About the Elevated LSR

<sec:lsr-cascade-interpretation>

#clinical-caution()

===== Two Candidate Mechanisms

An elevated LSR (anti-BZLF1 IgG / anti-VCA-p18 IgG) could arise from two fundamentally different mechanisms, with different therapeutic implications:

*Mechanism 1 — Abortive lytic reactivation (ALR)*: Stress, inflammation, or immune suppression triggers EBV's immediate-early genes (BZLF1, BRLF1). The lytic cascade initiates through early gene expression (dUTPase, EA-D), preferentially boosting short-lived plasmablast (SLPB) responses to lytic antigens. Because the reactivation is abortive — the viral DNA replication step is either blocked or insufficient for productive replication — late structural genes (VCA, gB) are NOT expressed, and no infectious virions are produced. The LSR rises because lytic IgG (from both LLPC baseline AND SLPB output) increases while structural IgG (LLPC-only) stays stable.

*Mechanism 2 — LLPC autoimmune drift (no ongoing viral activity)*: ME/CFS-associated B cell dysregulation (increased plasma cell differentiation trajectory, @Sun2024Immunometabolic) drives preferential survival and clonal expansion of bone marrow LLPCs producing cross-reactive lytic-epitope antibodies. Anti-BZLF1/dUTPase IgG is selectively enriched relative to anti-VCA-p18 IgG through niche competition for APRIL/BAFF/IL-6 survival signals. The LSR rises — but there is NO active viral replication (no viral DNA, no viral mRNA, no ALR). The elevated lytic antibodies are a readout of B cell dysregulation, not viral activity.

===== Interpreting Valacyclovir Response Through the LSR

#speculation(title: [What Valacyclovir Response Tells Us About the Mechanism Driving Elevated LSR])[

*Certainty: 0.15.* Valacyclovir (acyclovir prodrug) inhibits EBV DNA polymerase (BALF5) — it blocks viral DNA replication but does NOT block BZLF1 or dUTPase expression (immediate-early and early genes are transcribed before DNA replication). It does NOT deplete existing LLPCs or SLPBs. Because valacyclovir acts selectively on DNA replication (a mid-cascade node in ALR) and has no effect on LLPC maintenance, its clinical response pattern can help distinguish between the two candidate mechanisms — but imperfectly.

If valacyclovir produces clinical improvement AND LSR declines after 3–6 months, Mechanism 1 (ALR-driven) is supported but not proven: valacyclovir is also active against VZV and HSV, and clinical improvement could reflect suppression of non-EBV herpesviruses. Inference certainty is low (0.10) due to poly-herpesvirus antiviral activity and the inability to exclude off-target mechanisms.

If valacyclovir produces zero clinical response AND LSR remains elevated, the most likely interpretation is Mechanism 2 (LLPC autoimmune drift): the elevated LSR reflects B cell dysregulation and clonal LLPC selection, not ongoing viral replication. Valacyclovir has no target in this cascade — it neither blocks LLPC antibody secretion nor depletes cross-reactive LLPC clones. However, an alternative cannot be excluded: if ALR is stuck at the immediate-early/early gene expression stage (BZLF1 and dUTPase are expressed, but the cascade never reaches DNA replication), valacyclovir would have NO target in the cascade because the DNA polymerase step is never reached. In this scenario, lytic antigens continue to be produced and the LSR stays elevated despite successful DNA polymerase blockade. The distinction between "LLPC-driven LSR" and "early-gene-only ALR with valacyclovir-irrelevant bottleneck" cannot be made from valacyclovir response alone — it requires direct measurement of viral gene expression (EA-D IgG, dUTPase IgG kinetics, or ideally viral mRNA in PBMCs).

If valacyclovir fails but valganciclovir succeeds, the dominant virus is likely HHV-6 or CMV (broader-spectrum ganciclovir covers both, while acyclovir is EBV/VZV/HSV-selective), OR the virus is in a tissue sanctuary site (CNS, DRG) that ganciclovir accesses better than acyclovir. If both valacyclovir and valganciclovir fail, and LSR is confirmed elevated, this is the strongest available negative evidence that the elevated LSR is NOT driven by ongoing viral replication — Mechanism 2 (LLPC autoimmune drift) becomes the leading explanation.

*Falsifiable prediction:* In a cohort of ME/CFS patients with elevated LSR, pre- and post-valacyclovir (6 months at therapeutic dose) LSR measurements will show: (a) decline in LSR only in patients who clinically respond; (b) no decline in LSR in non-responders. Falsified if LSR declines in non-responders (would suggest ALR continues despite absent clinical benefit — the antibody signal is more sensitive than symptom change) OR if LSR stays unchanged in responders (would suggest valacyclovir's clinical benefit is independent of ALR suppression).

*Consequence:* If confirmed, an elevated LSR that does not budge after valacyclovir would strongly indicate that the antibody abnormality is LLPC-driven — directing treatment toward B cell-targeted interventions (currently research-stage only) rather than antiviral escalation. This would spare patients from years of empirically escalated antiviral therapy (valacyclovir → valganciclovir → repeat cycles) when the underlying mechanism is not viral. *Origin: brainstorm — cascade trace.*

] <spec:lsr-valacyclovir-response>

#open-question(title: [What Does a Discordant Pattern Mean — LSR Elevated but Valacyclovir Succeeds?])[

*Certainty: N/A — research question.* The cascade-to-drug tracing above describes what valacyclovir response and non-response would mean for the LSR. But there is a third, more ambiguous pattern: valacyclovir produces clinical improvement but the LSR remains elevated. This would suggest viral reactivation is rate-limiting for symptoms but the LSR is maintained by a mechanism valacyclovir does not touch — either (a) LLPCs produce the lytic IgG baseline while SLPB-derived lytic IgG from ALR events is too small a fraction to move the ratio, or (b) the clinical benefit comes from suppressing a different herpesvirus (VZV, HSV) that is contributing to symptoms without affecting EBV LSR. This question cannot be answered without a prospective study measuring LSR, viral DNA (qPCR for each herpesvirus), and clinical symptoms simultaneously before, during, and after antiviral therapy.

*Consequence:* none — this is a methodological question about measurement synchronicity. The resolution depends on data that does not yet exist.

] <oq:lsr-valacyclovir-discordant>

#synthesis(title: [The LSR as a Convergent Tool: From Serological Interpretation to Pharmacodiagnostic Inference])[

The LSR can function as a bridge between serological immunology and diagnostic pharmacology — the same ratio that resolves the contradictory herpesvirus serology literature (@hyp:lytic-structural-igg-ratio) also yields differential predictions about antiviral drug responses (@spec:lsr-valacyclovir-response). If validated, a single pre-treatment blood test would do double duty: it would stratify patients by mechanism (ALR-driven vs LLPC-driven), AND predict whether valacyclovir is likely to provide benefit. This closes a gap in the current clinical algorithm: the LSR provides objective pre-treatment stratification, replacing the "time-limited trial with stopping rules" heuristic with a biomarker-informed decision. An elevated LSR that declines with valacyclovir confirms ALR at the individual-patient level without requiring qPCR (which may be negative during ALR). An elevated LSR that does not budge after valacyclovir provides strong negative evidence for LLPC-driven antibody abnormality, directing treatment away from antiviral escalation and toward B cell-targeted research. The LSR validation study (@sec:lsr-biomarker-validation-study) is the most direct path from this convergent hypothesis to clinical deployment — it requires no new assay development and could be executed on existing clinical ELISA platforms within 2–3 years. The central unanswered question is whether LSR elevation exists at all in ME/CFS: the ratio has never been computed in any disease population, and the normal range is entirely unknown. Until the first measurement is made, the entire convergent framework — serological interpretation, pharmacodiagnostic inference, and mechanism-based treatment stratification — is a reasoning scaffold awaiting its first data point.

*Consequence:* If the LSR is validated, a single inexpensive blood test could simultaneously diagnose a mechanism AND predict an antiviral response AND guide treatment decisions — replacing the current clinical reality of diagnosing "viral reactivation" from structural antigen IgG alone and empirically cycling through antivirals without knowing whether they will work. This is the clinical promise of the LSR framework, but it requires the foundational step no one has taken: measuring the ratio for the first time.

] <syn:lsr-convergent-framework>
