#import "../../../../shared/environments.typ": *

#speculation(title: [Retrospective Prodromal Syndrome as Subclinical Metabolic Reserve Depletion])[
*Certainty: 0.40.* The clinical vignettes above may represent a unified *retrospective prodromal syndrome* reflecting subclinical depletion of metabolic reserve---the same mechanism formalised in the Architecture C metabolic reserve hypothesis (@sec:architecture-c-metabolic-reserve). In this framework, constitutional factors (genetic mitochondrial efficiency, neurodevelopmental phenotype, connective tissue properties) set a lower ceiling for ATP production ($J_"production,max"$) from birth. The individual operates with reduced headroom ($R_"headroom"$) but compensates through intelligence, persistence, or lifestyle adaptation. Symptoms (tremor, fatigue, cold extremities, cognitive fade) represent moments when demand transiently exceeds this lower ceiling---too brief to trigger medical evaluation, too persistent to be normal. The eventual collapse into full ME/CFS occurs when an immune trigger (infection, vaccination reaction) or cumulative load permanently reduces production capacity below the minimum needed for daily function.

*Testable predictions:* (1) Pre-illness CPET data in athletes who later develop ME/CFS should show reduced VO#sub[2]max relative to training volume. (2) Siblings of ME/CFS patients (sharing genetic ceiling) should show measurable subclinical exercise intolerance on formal testing. (3) Retrospective analysis of school attendance records should show elevated minor illness absences 3--5 years before diagnosis. (4) Wearable data (HRV, sleep architecture) from the pre-illness period should show reduced autonomic reserve compared to matched controls.

*Falsification:* If prospective metabolic testing of at-risk individuals (e.g., children of ME/CFS parents) shows identical exercise capacity and autonomic function to controls until the moment of triggering infection, the subclinical prodromal model is not supported and sudden-onset remains the dominant paradigm.

*Not yet replicated.* No prospective study has tracked objective exercise capacity or metabolic markers in individuals before ME/CFS diagnosis. The retrospective ICD data @Wirth2026prodromalICD are the strongest available evidence for a measurable pre-diagnostic period but cannot distinguish prodrome from coincidental comorbidity.
] <spec:prodromal-syndrome>