#import "../../../shared/environments.typ": *

== Severity-Stratified Metabolic Reserve Building Protocol
#include "remarks/rem-intro.typ"
#include "subsec-severe-mecfs-houseboundbedbound/subsec-severe-mecfs-houseboundbedbound.typ"
#include "subsec-moderate-mecfs-ambulatory-limited/subsec-moderate-mecfs-ambulatory-limited.typ"
#include "subsec-mild-mecfs-functional-with-limitations/subsec-mild-mecfs-functional-with-limitations.typ"
#include "subsec-mild-moderate-mecfs-ambulatory-good-oral-tolerance/subsec-mild-moderate-mecfs-ambulatory-good-oral-tolerance.typ"
#include "subsec-severe-mecfs-housebound-limited-oral-intake/subsec-severe-mecfs-housebound-limited-oral-intake.typ"
#include "subsec-step-1-baseline-sibo-testing/subsec-step-1-baseline-sibo-testing.typ"
#include "subsec-step-3-sibo-treatment-if-positive/subsec-step-3-sibo-treatment-if-positive.typ"
#include "subsec-step-4-post-intervention-rs-supplementation/subsec-step-4-post-intervention-rs-supplementation.typ"
#include "subsec-speculative-combination-and-access-proposals-from-the-unified-model/subsec-speculative-combination-and-access-proposals-from-the-unified-model.typ"
#include "../warnings/warning-env-9.typ"
#include "../speculations/speculation-12.typ"
#include "../proposals/proposal-8.typ"
#include "../proposals/proposal-9.typ"
#include "../proposals/proposal-10.typ"
#include "../proposals/proposal-11.typ"
#include "../proposals/proposal-12.typ"
#include "../open-questions/open-question-4.typ"
#include "../open-questions/open-question-5.typ"
#include "../open-questions/open-question-6.typ"
