#import "../../../../shared/environments.typ": *

==== Cascade: Functional Iron Deficiency → Fe-S Cluster Failure → ETC Complex Impairment → ATP Depletion
  <sec:iron-redox-cascade>

*Cascade:*
- Chronic inflammation → IL-6/STAT3 signalling (established in ME/CFS, cert 0.50)
- Hepcidin paradox: hepcidin is LOW (~50% reduction, @Kavyani2023Hepcidin) — NOT high as classic inflammatory anemia predicts
- Despite low hepcidin, functional iron deficiency persists: high ferritin, low serum iron, low TSAT (@Swiatczak2022, @Baklund2021RoutineBlood)
- Four candidate hepcidin-independent trapping mechanisms (@spec:hepcidin-independent-ferroportin-blockade, cert 0.40):
  (a) ferroportin trafficking defect via IRP/IRE dysregulation,
  (b) ceruloplasmin/ferroxidase deficiency,
  (c) NCOA4 ferritinophagy blockade,
  (d) LCN2/NGAL futile iron scavenging cycle
- Trapped macrophage iron → serum iron restriction → five downstream arms:
- (a) Mitochondrial Fe-S cluster deficiency → Complex I (8 Fe-S clusters), Complex II (3), Complex III (1 Rieske) → impaired ETC → reduced ATP yield → fatigue/PEM
- (b) Aconitase (Fe-S enzyme) inactivation → Krebs cycle bottleneck → reduced NADH → further ATP deficit + citrate accumulation
- (c) Cytochrome c oxidase (heme a/a₃, Complex IV) impairment → terminal electron transport failure → O₂ not reduced to H₂O → reactive oxygen species leak
- (d) Tyrosine hydroxylase (iron cofactor) → reduced dopamine synthesis → low CSF dopamine (documented, @walitt2024deep)
- (e) TPO (thyroid peroxidase, heme-iron) → reduced T4 synthesis → low T3 syndrome (@spec:hepcidin-endocrine-bridge, cert 0.40)
- Net convergence: multi-system ATP depletion + dopamine deficiency + thyroid dysfunction → fatigue, PEM, cognitive impairment, orthostatic intolerance
- Temporal trajectory: acute hypoferremia (Phase 0) → stress erythropoiesis + monocyte iron loading (Phase I, @Hanson2024iron) → established functional iron deficiency + low hepcidin (Phase II–III, @spec:temporal-phase-shift-iron, cert 0.35)

*Cross-disease divergence:* In Long COVID, the iron phenotype differs — monocyte iron loading + lymphocyte iron starvation (single-cell, @Hanson2024iron), RBC O₂-binding defect (@KronsteinWiedemann2024RBC), and ferritin variability (35% hyperferritinaemic, 24% iron deficient, 9% anaemic, @Sonnweber2022CovILD). The therapeutic bifurcation is at the Fe-S cluster level: ME/CFS needs iron redistribution (intracellular iron is trapped), LC needs iron phenotyping (some patients need repletion, some need chelation — @hyp:iron-redox-polarity-diagnostic-bifurcation, cert 0.55).

*Drug interception nodes (from mechanism → drug, tracing the cascade forward):*
- Node 1 — Serum iron / TSAT (pre-ETC): Oral iron works only in genuine deficiency (ferritin \<30 µg/L or TSAT \<16%). In functional deficiency, oral iron fails (ferroportin blocked — see @spec:hepcidin-independent-ferroportin-blockade) and may worsen ferroptosis risk. IV iron (iron sucrose, ferric carboxymaltose) may bypass the enteral ferroportin block in some patients by delivering iron directly to transferrin — but this is untested in ME/CFS. *If IV iron works:* the bottleneck is at the enteral iron absorption step (ferroportin blockade at the enterocyte, not the macrophage). *If IV iron fails:* the bottleneck is downstream — macrophage iron trapping, Fe-S cluster assembly failure, or ceruloplasmin deficiency preventing iron loading onto transferrin even when iron is IV-delivered. _Certainty of inference: 0.30_ (IV iron bypass mechanism is mechanistically sound but zero ME/CFS data).
- Node 2 — Fe-S cluster assembly (ETC level): CoQ10 (ubiquinone/ubiquinol) bypasses Complex I and II Fe-S deficiencies by accepting electrons directly from Complex II and ETF dehydrogenase. L-carnitine shuttles fatty acids into mitochondria, bypassing the glycolytic-ETC uncoupling. Both are already in the ME/CFS armamentarium. *If CoQ10 works:* supports Fe-S cluster failure as rate-limiting — CoQ10's electron bypass compensates for Fe-S-electrodeficient ETC complexes. *If CoQ10 fails:* the bottleneck may be at Complex IV (heme-dependent, not Fe-S-cluster-dependent) or downstream at ATP synthase. _Certainty: 0.35_ (CoQ10 benefit is consistent with Fe-S cluster failure but is not specific — CoQ10 also helps PDH inhibition, NOS uncoupling, and generic mitochondrial support).
- Node 3 — Macrophage iron trapping (pharmacological chelation): Deferiprone (oral, membrane-permeable) chelates intracellular labile iron in macrophages, bypassing the entire hepcidin-ferroportin axis. *If deferiprone works:* confirms that trapped macrophage iron is the rate-limiting resource — the iron is present but inaccessible, and direct chelation-based removal improves iron availability by reducing the futile LCN2 cycle and freeing NCOA4-ferritinophagy capacity. *If deferiprone fails:* the bottleneck is NOT macrophage iron trapping — it may be at Fe-S cluster assembly (ISA/ISC machinery defective, iron delivered but cannot be inserted), ceruloplasmin deficiency (iron exported but not loaded onto transferrin), or a non-iron mechanism (NAD depletion, PDH inhibition). _Certainty: 0.25_ (zero deferiprone data in ME/CFS; black-box agranulocytosis warning; @spec:deferiprone-functional-iron-deficiency).
- Node 4 — Ferroptosis (oxidative stress endpoint): NAC (N-acetylcysteine, glutathione precursor), α-lipoic acid (mitochondrial antioxidant), and vitamin E (α-tocopherol, chain-breaking lipophilic antioxidant) each attenuate lipid peroxidation by different mechanisms. *If anti-ferroptosis agents work:* supports ferroptosis as a contributing mechanism — reducing the labile iron pool's catalytic capacity (via glutathione) or scavenging lipid peroxyl radicals (via vitamin E) improves outcomes. *If they fail:* ferroptosis is not a major contributor, or the ferroptosis is iron-independent (e.g., driven by glutathione depletion alone, not catalytic iron). _Certainty: 0.30_ (anti-ferroptosis agents have multiple mechanisms; benefit is not specific to the iron-ferroptosis link).

*Discriminating probe:* Deferiprone vs IV iron is the cleanest — deferiprone removes trapped iron (confirms trapping), IV iron bypasses the enteral block (confirms ferroportin blockade at enterocyte). If deferiprone works and IV iron does not → macrophage trapping, not enterocyte blockade. If IV iron works and deferiprone does not → enteral ferroportin blockade, not macrophage trapping. If neither works → bottleneck is downstream (Fe-S assembly, ceruloplasmin, or non-iron). _Quality gate: no clean discriminator exists — both drugs have uncertain specificity._ Deferiprone chelates zinc as well as iron; its benefit could be zinc-mediated. IV iron's failure could reflect ceruloplasmin deficiency preventing iron loading onto transferrin — not ferroportin blockade at all.

*Certainty: 0.35.* The cascade is mechanistically coherent at every step but each node has an alternative explanation. The hepcidin paradox is the strongest empirical anchor — Kavyani2023 is the only measurement and needs independent replication. The cascade below the serum iron level (Fe-S clusters, aconitase, cytochrome c oxidase) is physiological reasoning applied to ME/CFS — none of these nodes have been directly measured in ME/CFS tissue.
