#import "../../../shared/environments.typ": *

// =============================================================================
// SECTION 2: TRIGGER-CAPABLE MECHANISMS
// =============================================================================

== Trigger-Capable Mechanisms
<sec:trigger-capable>

Four mechanisms meet all four criteria and are therefore candidates for trigger-capable root causes. These are not mutually exclusive: different patients may enter the disease through different trigger-capable mechanisms, and in some patients, multiple root causes may engage simultaneously. What unites them is that each can, in principle, account for the full syndrome without requiring prior dysfunction elsewhere.

Before examining each candidate, what is _not_ on this list is equally important. Mitochondrial dysfunction, arguably the most studied mechanism in ME/CFS, is not classified as trigger-capable. Neither is gut dysbiosis, immune dysregulation considered generically, or hormonal disruption. This may seem counterintuitive given the evidence for each of these processes. The reason is Criterion 1: none of these mechanisms arises directly from known ME/CFS precipitants without an intermediary. Mitochondrial dysfunction does not spontaneously develop in response to viral infection; it develops because viral infection triggers neuroinflammation, metabolic suppression, or autoimmunity, which then damages mitochondria. The mitochondrial damage is real and consequential, but it is an amplifier of the upstream process, not the initiating event. The same applies to the reproductive axis: it is a modulatory/amplifier layer that changes how symptoms are expressed across the menstrual cycle, pregnancy, and the menopause transition, but it is not a trigger-capable root cause (see the reproductive-lifespan synthesis @syn:fra-reproductive-lifespan-model). This classification does not diminish its clinical importance — for many women, cycle-phase or menopausal amplification is a principal determinant of daily symptom burden.

=== CNS Energy Crisis
<sec:root-cns-energy>

The central nervous system orchestrates virtually all demand-responsive physiological functions: autonomic regulation of heart rate and blood pressure, immune surveillance and cytokine coordination, endocrine signaling, sleep-wake cycling, and the allocation of metabolic resources across tissues. The brain, comprising approximately 2% of body mass, consumes roughly 20% of resting metabolic energy. When the brain's own energy supply fails, the downstream consequences are not confined to neurological symptoms—they propagate to every system the brain coordinates.

The proposed cascade begins with CNS hypometabolism: reduced glucose and oxygen delivery to neuronal populations, whether from neuroinflammation-driven metabolic suppression, neurovascular uncoupling, or direct mitochondrial dysfunction in glial and neuronal cells. The evidence for this initial step is substantial and converges from multiple methodologies. PET imaging studies demonstrate cortical and subcortical hypometabolism in ME/CFS patients, with particular involvement of the cingulate cortex, prefrontal regions, and basal ganglia @Nakatomi2014neuroinflammation. The Nakatomi study additionally demonstrated microglial activation in these regions, using the #super[11]C-PK11195 ligand, linking the hypometabolism to an active neuroinflammatory process rather than simple atrophy or disuse. SPECT studies reveal widespread cerebral hypoperfusion that correlates with cognitive dysfunction severity, consistent with neurovascular uncoupling or upstream autonomic failure to maintain cerebral perfusion pressure @Barnden2011brainstem.

Most compellingly, the 2024 NIH intramural study by Walitt et al.\ documented reduced CSF catecholamine precursors (DOPA, DOPAC, DHPG), indicating that the brain's own neurotransmitter synthesis is compromised @Walitt2024NIH. A follow-up analysis by Aregawi et al. (2026) refined these findings using novel composite pathway indices, demonstrating that the deficiency is *selectively noradrenergic*: the NE Pathway (NE + DHPG + MHPG) was significantly reduced in PI-ME/CFS and PASC (with the largest reduction in the PEM subgroup), while the DA Pathway (DA + DOPAC + HVA) was indistinguishable from healthy controls @Aregawi2026Noradrenergic. This selectivity implicates the ATP-dependent vesicular step --- DBH is localized within synaptic vesicles and requires an ATP-driven proton pump for substrate uptake --- rather than a global cofactor depletion affecting both pathways equally. The CSF catecholamine deficit therefore represents downstream evidence of CNS energy compromise at the level of ATP-dependent biosynthetic capacity, not merely neurotransmitter utilization or cofactor depletion.

The Walitt study also identified altered effort-perception circuitry: ME/CFS patients showed abnormal functional connectivity between motor cortex, basal ganglia, and prefrontal regions during effort tasks, suggesting that the brain's assessment of effort cost is disrupted. This altered effort perception is consistent with a brain that lacks the energy resources to accurately calibrate metabolic demand signals.

Consistent with this CNS energy-compromise picture, a proof-of-concept MRI study reported elevated resting brain lactate that failed to rise under a controlled hypoxic challenge, together with an unresolved brainstem-volume direction — one cohort (Vienna) reported reduced brainstem volume, another (Griffith) reported larger volume — a pattern tentatively consistent with the brain operating under chronic metabolic limitation despite normal arterial oxygenation (@syn:experimental-hypoxia-virtual-hypoxia-brainstem-model). This is preliminary (single preprint, not yet replicated) and the brainstem-volume direction is unresolved across cohorts; it is cited here as converging spectroscopic evidence for the CNS energy deficit, not as an independent root-cause demonstration.

From CNS hypometabolism, the cascade propagates through every system the brain coordinates:

    - *Autonomic dysfunction* (Chapter @ch:cardiovascular): Failed coordination of sympathetic and parasympathetic outflow produces orthostatic intolerance, impaired cardiac output regulation, and the orthostatic tachycardia that afflicts over 30% of ME/CFS patients @Hoad2008pots @Yu2022. The brain's inability to dynamically adjust vasomotor tone to postural changes explains why symptoms are position-dependent.

    - *Immune dyscoordination* (Chapter @ch:immune-dysfunction): The hypothalamus regulates immune function through the hypothalamic-pituitary-adrenal axis and the cholinergic anti-inflammatory pathway (vagal efferent signaling that suppresses peripheral TNF-$alpha$ production). CNS energy failure disrupts both pathways, producing the paradoxical immune state described in Chapter @ch:immune-dysfunction: elevated inflammatory markers alongside impaired immune effector function.

    - *Endocrine disruption* (Chapter @ch:endocrine): The hypothalamic-pituitary axes governing thyroid function, adrenal output, growth hormone secretion, and gonadal function all depend on adequate hypothalamic energy supply. CNS hypometabolism produces the characteristic “hypothalamic pattern” of ME/CFS: low-normal cortisol with blunted diurnal rhythm, reduced growth hormone pulsatility, and altered thyroid set-points.

    - *Sleep architecture disruption* (Chapter @ch:neurological): Sleep-wake cycling depends on the coordinated activity of hypothalamic orexin neurons, ventrolateral preoptic area GABAergic neurons, and brainstem monoaminergic nuclei. In rodent models, inflammatory cytokines actively suppress orexin neuron firing @Grossberg2011orexinLethargy, and partial orexin deficiency produces the sleep fragmentation and REM-gating failures characteristic of narcolepsy Type 2 @Ito2023orexinREM — a pattern that may overlap with ME/CFS sleep dysfunction (Section @spec:mecfs-functional-narcolepsy, certainty 0.30). Energy-depleted sleep-regulating circuits cannot maintain normal slow-wave sleep architecture, producing the unrefreshing sleep universal in ME/CFS.

    - *Gut-brain axis dysfunction* (Chapter @ch:gut-microbiome): Vagal efferent tone regulates gut motility, intestinal barrier function, and mucosal immune responses. Reduced vagal output from an energy-depleted brainstem permits gut barrier compromise, bacterial translocation, and the downstream immune activation that further burdens the already-struggling CNS.

The cascade's reach is limited only by the brain's reach—which is to say, not limited at all. Every organ system that receives neural input, hormonal regulation, or immune coordination from the CNS is a potential downstream casualty of CNS energy failure. This structural property is what makes the CNS energy crisis uniquely qualified as a trigger-capable mechanism: it does not need to invoke independent pathology in multiple organ systems because a single central failure cascades to all of them.

*Assessment against the four criteria.*

    - *Precipitant compatibility:* Viral infection is a potent cause of neuroinflammation; both direct viral neurotropism (as demonstrated for EBV, HHV-6, and SARS-CoV-2) and peripheral cytokine signaling to the brain (via circumventricular organs, vagal afferents, and BBB transport) can produce CNS metabolic suppression. Severe physiological stress activates hypothalamic stress responses that, if sustained, deplete catecholamine reserves and shift the balance between excitatory and inhibitory neurotransmission toward a hypometabolic state. Surgery combines inflammatory insult, anesthetic-induced neuronal stress, and the physiological shock of tissue trauma. All three major ME/CFS precipitants converge on the CNS.

    - *Energy collapse sufficiency:* If the brain cannot coordinate the autonomic, endocrine, and metabolic responses required for exertion, any physical or cognitive demand will exceed the system's capacity to respond. The result is post-exertional malaise—not because peripheral energy production has failed (though it may also be compromised), but because the central coordinator has insufficient energy to manage the demand. The 12–72 hour delay characteristic of PEM is consistent with a CNS-mediated mechanism: the brain initially attempts to meet the demand by drawing on reserves, and the “crash” occurs when those reserves are exhausted and the neuroinflammatory response to the overshoot peaks.

    - *Chronicity:* Neuroinflammation is self-perpetuating through multiple reinforcing loops. Activated microglia release pro-inflammatory cytokines (TNF-$alpha$, IL-1$beta$, IL-6) that damage the blood-brain barrier, permitting further peripheral immune cell infiltration, which sustains microglial activation. Microglial activation also produces reactive oxygen species that damage local mitochondria, worsening the CNS energy deficit. Catecholamine depletion reduces the brain's capacity to activate the cholinergic anti-inflammatory pathway, removing a key brake on both central and peripheral inflammation. Epigenetic changes in microglia can stabilize the activated phenotype, making the inflammatory state self-sustaining even if the original trigger resolves. A cross-disease precedent for an inflammation-driven, self-perpetuating CNS lesion is provided by the inflammatory-mediated-neurodegeneration meta-analyses in dementia, which found inflammation dissociable from psychiatric comorbidity and mechanistically upstream of neurodegeneration @Kuring2026InflammatoryDementia @Kuring2023InflammatoryMood — evidence that a low-grade chronic inflammatory state can be trigger-capable and self-sustaining across disorders, not merely a downstream epiphenomenon (Section @spec:bidirectional-mood-inflammation-template). The longitudinal, exposure-defined version of this precedent comes from a large US electronic-health-record cohort: a defined episode of acute brain-parenchymal inflammation (encephalitis) predicts later dementia, with specific dementia codes (Alzheimer's, vascular, specified) robust in adults 40–60 y (risk ratio 5.16) and >60 y (2.11), strongest for non-infectious/post-infectious inflammatory (autoimmune) etiologies (risk ratio 3.93), and with a similar relationship reproduced in an independent UK primary-care cohort @Aditi2026EncephalitisDementia @Granerod2017PostEncephalitis (Section @spec:encephalitis-dementia-precedent). This supports the claim that a defined acute CNS inflammation episode can measurably precede and predict later degeneration — distinct from, though complementary to, the self-perpetuation loops above (encephalitis itself is an acute, largely self-limited episode rather than evidence of ongoing self-sustaining inflammation, and the younger-cohort excess reflects post-encephalitic sequelae rather than Alzheimer-type disease @Aditi2026EncephalitisDementia).

    - *Multi-system spread:* The brain innervates and regulates every organ system. A central coordination failure naturally produces multi-system dysfunction without requiring independent pathology in each system. This is the strongest criterion met by the CNS energy crisis hypothesis: it is the only trigger-capable mechanism whose multi-system reach is guaranteed by anatomy rather than dependent on molecular diffusion or receptor expression patterns.

The CNS energy crisis is the only trigger-capable root cause with direct genetic anchoring. The DecodeME GWAS and Maccallini 2026 meta-analysis converge on neuronal cell-type enrichment with zero immune signal (Section @syn:genetic-neuronal-convergence) — the constitutional vulnerability is in the very circuits the CNS energy crisis model identifies as the primary site of failure. The genetic evidence does not prove that CNS energy failure _is_ the root cause, but it establishes that the genetic architecture is compatible with a CNS-primary model and incompatible with a model in which the initial lesion is encoded in immune cells. The CNS energy crisis hypothesis does not merely pass Criterion 1 (precipitant compatibility) — it is the mechanism most strongly predicted by the genetic architecture itself: a brain whose circuits are genetically vulnerable to metabolic failure would be expected to fail first when confronted with a systemic inflammatory precipitant, with peripheral pathology following as a downstream consequence of failed central coordination.

#include "subsec-01-cns-energy-crisis/hypotheses/hyp-cns-energy-crisis-as-trigger-capable-roo.typ"

The formal dynamical systems analysis of the CNS energy crisis as an attractor basin is developed in Section @sec:bifurcation-analysis, where the CNS energy state is modeled as a bifurcation parameter whose reduction below a critical threshold drives the system into the ME/CFS disease attractor.

=== Metabolic Safe Mode Lock
<sec:root-safe-mode>

Where the CNS energy crisis hypothesis posits a failure of the brain's energy supply, the metabolic safe mode hypothesis proposes something more radical: the body's energy suppression is _deliberate_. The metabolic downregulation observed in ME/CFS is not a malfunction but an evolutionarily conserved protective program—the cellular equivalent of a computer entering safe mode—that has become locked in the activated state.

The conceptual distinction is important. Under the CNS energy crisis model, the brain is _unable_ to produce enough energy; under the safe mode model, the body is _choosing not to_. The distinction matters therapeutically: if the problem is inability, the solution is to restore capacity; if the problem is a deliberate program that refuses to disengage, the solution is to reset the program. These are fundamentally different treatment strategies.

The mechanistic details of the safe mode hypothesis are developed in Section @sec:safe-mode. In summary: upon detecting a severe threat (infection, trauma, extreme stress), the body activates a coordinated metabolic suppression program through multiple converging pathways. Itaconate shunt activation diverts cis-aconitate away from the TCA cycle via the enzyme aconitate decarboxylase 1 (ACOD1/IRG1), reducing mitochondrial ATP production while simultaneously generating the immunomodulatory metabolite itaconate @Naviaux2016metabolomics. IDO (indoleamine 2,3-dioxygenase) upregulation shunts tryptophan toward the kynurenine pathway, simultaneously depleting serotonin precursors and generating immunomodulatory metabolites—with the additional consequence of reducing NAD#super[+] synthesis via the de novo pathway (Section @sec:kynurenine-trap). Mitochondrial dynamics shift toward fission (via DRP1 activation), fragmenting the mitochondrial network and reducing oxidative phosphorylation efficiency. The net result is a coordinated, whole-body metabolic downregulation that conserves resources for immune defense while limiting substrate availability to intracellular pathogens.

This program has clear evolutionary logic. During acute infection, the host faces a dilemma: many intracellular pathogens (including viruses) depend on host metabolic machinery for replication. Reducing metabolic output restricts pathogen replication at the cost of host performance—a trade-off that is favorable during acute infection, where survival matters more than performance. The sickness behavior that accompanies this metabolic suppression (fatigue, anorexia, social withdrawal) enforces the energy conservation by making activity aversive.

The critical failure in ME/CFS is not the activation of this program—which is normal and adaptive—but its failure to disengage. Several lock mechanisms can prevent disengagement:

*Persistent low-grade immune activation.* Even after the triggering infection resolves, ongoing immune stimulation from autoantibodies, reactivated herpesviruses, gut bacterial translocation, or other sources maintains the cytokine signals (particularly IL-6 and type I interferons) that keep the safe mode program engaged. The program cannot distinguish between “infection persists” and “immune system is activated for other reasons”; it responds to the cytokine signal regardless of its source.

*Hypothalamic setpoint shift.* The hypothalamus integrates peripheral immune signals and sets metabolic “targets” for the organism. A severe enough initial insult—particularly one that involves direct hypothalamic inflammation—may shift these setpoints such that the metabolic targets are permanently lowered. The organism then “defends” a lower metabolic rate, interpreting attempts to increase metabolism as dangerous deviation from the setpoint.

*Epigenetic stabilization.* The gene expression changes that implement the safe mode program (ACOD1 upregulation, IDO induction, mitochondrial fission gene expression) may become epigenetically stabilized through DNA methylation or histone modifications during the acute phase. Once epigenetically fixed, these expression patterns persist even after the signaling that induced them resolves, creating a metabolic state that is self-sustaining at the chromatin level.

*Self-reinforcing exertion logic.* The most insidious lock mechanism is the program's own logic. During metabolic suppression, the body's response to exertion is abnormal: energy demands cannot be met normally, metabolic waste accumulates, and the autonomic response to exercise is dysregulated. The safe mode program interprets these abnormal responses as evidence that the threat persists—because in the evolutionary environment, abnormal exercise responses during infection _were_ evidence of ongoing threat. Physical exertion during ME/CFS therefore triggers further suppression rather than the gradual disengagement that would occur during normal recovery from infection. This is the biological basis of post-exertional malaise under the safe mode model: PEM is not a failure to cope with exertion, but the program's enforcement mechanism for continued energy conservation.

*Assessment against the four criteria.*

    - *Precipitant compatibility:* Infection and severe stress are the canonical activators of the sickness behavior and metabolic suppression programs. The safe mode response evolved precisely to be triggered by these events. This criterion is met with particular strength: the safe mode hypothesis does not merely _accommodate_ known precipitants—it _predicts_ them.

    - *Energy collapse sufficiency:* The program deliberately suppresses energy production. Post-exertional malaise is the body's enforcement mechanism: the metabolic cost of exertion is deferred (Section @sec:evolutionary-deferred-cost) and then collected aggressively, producing the characteristic delayed crash. The delay is not pathological—it reflects normal physiology of deferred metabolic cost—but the severity of the crash is amplified by the suppressed restoration capacity.

    - *Chronicity:* The self-reinforcing nature of the program—where exertion signals continued threat, and the resulting further suppression prevents the normal disengagement process—creates a stable lock. Epigenetic stabilization of the metabolic gene expression changes (Section @sec:epigenetic-dynamics) can make the lock effectively permanent. The longer the program remains engaged, the more deeply it becomes entrenched.

    - *Multi-system spread:* The safe mode program is a whole-body metabolic shift, not a tissue-specific phenomenon. Every cell that depends on mitochondrial ATP production is affected. The behavioral components (fatigue, anorexia, withdrawal) are mediated by hypothalamic signaling that coordinates the whole organism. The immune components affect all immune cell lineages. The metabolic components affect every tissue that uses oxidative phosphorylation.

#include "subsec-02-metabolic-safe-mode-lock/hypotheses/hyp-metabolic-safe-mode-as-trigger-capable-r.typ"

==== Safe Mode Threat Signal Miscalibration
<sec:threat-miscalibration>

The safe mode switch responds to the composite threat signal $cal(T)$ (formalized in Chapter @ch:causal-hierarchy-formal), whose weights $w_"cyto"$, $w_"ROS"$, $w_"LPS"$, $w_V$ determine how much each input contributes to the engagement decision. A distinct predisposition mechanism—separate from the four root causes above—arises if these weights are _miscalibrated_ by genetic polymorphisms in oxidative stress sensing pathways.

The Nrf2 (Nuclear factor erythroid 2-related factor 2) pathway is the master regulator of the cellular antioxidant response. Polymorphisms that reduce Nrf2 activity—or that impair the upstream sensors feeding into Nrf2—effectively _increase_ $w_"ROS"$ in the threat signal equation: the same level of oxidative stress produces a disproportionately large threat signal, activating safe mode at lower actual threat levels. The SOD2 Ala16Val polymorphism @Shimoda2004SOD2, which affects the mitochondrial targeting efficiency of manganese superoxide dismutase, is a candidate: the Val allele reduces mitochondrial SOD2 import, increasing mitochondrial ROS, which is sensed as elevated threat even when the actual pathogenic threat is modest.

Proteomics studies of ME/CFS PBMCs have identified disrupted mitochondrial and oxidative stress response pathways @Sweetman2020Nrf2, consistent with a model in which the cellular antioxidant defense is either overwhelmed or under-responsive. Whether this reflects a consequence of chronic disease or a pre-existing vulnerability remains unresolved.

#include "subsec-03-safe-mode-threat-signal-miscalibration/speculations/spec-oxidative-stress-sensing-polymorphisms-a.typ"

=== GPCR Autoantibody Cascade
<sec:root-gpcr>

The autoimmune hypothesis, detailed in Section @sec:gpcr-autoantibodies, proposes that autoantibodies against G-protein coupled receptors—particularly $beta_2$-adrenergic and muscarinic M3/M4 receptors—are sufficient to initiate the ME/CFS cascade. GPCRs are not niche signaling molecules: they constitute the largest family of cell surface receptors in the human genome, mediating adrenergic control of vasomotor tone, cardiac contractility, bronchial smooth muscle relaxation, immune cell trafficking, lipolysis, insulin secretion, and neurotransmitter release. Functional autoantibodies against these receptors produce endothelial dysfunction, impaired vasoregulation, dysregulated immune responses, and autonomic failure—a multi-system catastrophe arising from a single immunological mechanism.

The autoimmune hypothesis faces a structural tension with the genetic evidence that must be acknowledged directly. The DecodeME GWAS and Maccallini 2026 meta-analysis find zero immune cell-type enrichment — no signal in T cells, B cells, NK cells, or macrophages (Section @syn:genetic-neuronal-convergence). This does not refute the autoimmune hypothesis — the GPCR autoantibody cascade can be acquired (infection-triggered molecular mimicry or bystander activation) rather than genetically encoded — but it does constrain the interpretation. The autoantibodies cannot be the downstream expression of a constitutional immune predisposition toward autoimmunity, because no such predisposition is detectable. They must instead represent an acquired immunological event — a post-infectious break in tolerance — occurring in a host whose genetic vulnerability lies elsewhere (in neuronal circuits). The two-hit model resolves this tension: the neuronal genetic vulnerability (hit 1) determines _who_ is susceptible, and the acquired autoimmune event (hit 2) determines _how_ the disease initiates in a given patient. The strongest independent evidence supporting this framing is the 2026 Germain et al. REAP study (n=172), which found no autoantibody reactivity in chronic, pre-COVID ME/CFS using an unbiased proteome-wide screen — consistent with GPCR autoantibodies being an acquired, trigger-specific phenomenon rather than a genetically encoded autoimmune diathesis.

The evidence base is substantial though internally conflicting, a tension that demands honest assessment. Elevated anti-$beta_2$-adrenergic and anti-muscarinic autoantibodies are reported in 29–91% of ME/CFS patients across studies @Loebel2016 @Bynke2020, with the wide range reflecting differences in assay methodology, patient selection, and definition of “elevated.” Symptom severity correlates with autoantibody titers in some studies @Sotzny2021 @Azcue2026gpcr, though the correlation is modest and not replicated in all cohorts.

The therapeutic evidence is more compelling than the biomarker evidence. Immunoadsorption—which non-selectively removes circulating antibodies including autoantibodies—produced clinical improvement in approximately 70% of treated patients in open-label studies @Stein2024immunoadsorption. The improvement was transient, recurring within months as autoantibody titers recovered, consistent with the autoantibodies being pathogenic (removing them helps) and continuously produced (the effect wears off when they return). Most compellingly, daratumumab (targeting CD38#super[+] plasma cells, the cellular factories that produce autoantibodies) produced marked improvement in 60% of patients in a pilot study @Fluge2025daratumumab, with the response latency (8–9 months) matching the expected decay kinetics of autoantibodies after their source is eliminated (IgG half-life approximately 3 weeks, but tissue-bound and sequestered antibodies persist longer).

The cascade from GPCR autoantibodies to full ME/CFS proceeds through several parallel pathways:

*Endothelial pathway.* Anti-$beta_2$ autoantibodies impair endothelium-dependent vasodilation by interfering with $beta_2$-adrenergic receptor signaling on endothelial cells. This reduces tissue perfusion, particularly in capillary beds where flow depends on active vasodilation. The resulting tissue hypoxia forces anaerobic metabolism, generating lactate and depleting NAD#super[+]. Chronic hypoperfusion additionally damages the endothelium itself, creating a secondary loop of endothelial dysfunction $arrow.r$ reduced flow $arrow.r$ more endothelial damage.

*Immune reprogramming pathway.* GPCR autoantibodies reprogram monocyte cytokine production toward a pro-inflammatory, tissue-remodeling phenotype, as reported by Hackel et al. @Hackel2025monocyte. This reprogramming produces elevated MIP-1$delta$, PDGF-BB, and TGF-$beta$3—cytokines that drive fibrosis, angiogenesis, and chronic inflammation. The reprogrammed monocytes create a self-sustaining inflammatory environment that persists even between autoantibody binding events (Section @hyp:autoantibody-monocyte).

*Autonomic pathway.* Anti-muscarinic autoantibodies (particularly anti-M3) disrupt parasympathetic signaling, while anti-$beta_2$ autoantibodies dysregulate sympathetic signaling. The combined effect is autonomic dysfunction affecting heart rate variability, blood pressure regulation, gut motility, and thermoregulation. Azcue et al.\ (2026) provide the strongest quantitative evidence for this pathway: $beta_2$-adrenergic AAb titers correlate with sympathovagal imbalance in ME/CFS at $r=0.45$ ($p=0.001$) using HRV frequency-domain parameters @Azcue2026gpcr.

*Neuroinflammatory pathway.* Autoantibody-mediated endothelial dysfunction compromises the blood-brain barrier, permitting peripheral immune mediators and autoantibodies to access the CNS. Once in the brain, autoantibodies can directly affect neuronal and glial GPCRs, while the accompanying inflammatory infiltrate triggers microglial activation and the neuroinflammatory cascade described in Section @sec:root-cns-energy.

*Assessment against the four criteria.*

    - *Precipitant compatibility:* Molecular mimicry between viral antigens and GPCR epitopes is a well-established mechanism of post-infectious autoimmunity, documented in Chagas disease (anti-$beta_1$ autoantibodies following _Trypanosoma cruzi_ infection) and dilated cardiomyopathy. Bystander activation during acute infection can break tolerance to self-antigens that become exposed in damaged tissue. Surgical trauma releases sequestered self-antigens in the context of adjuvant-like inflammatory signaling, providing both antigen and activation signals for autoreactive B cells.

    - *Energy collapse sufficiency:* Endothelial dysfunction $arrow.r$ tissue hypoxia $arrow.r$ anaerobic metabolic shift $arrow.r$ ATP depletion. Exertion increases oxygen demand that hypoperfused tissues cannot meet, producing the delayed energy failure characteristic of PEM. The delay reflects the time required for tissue-level oxygen debt to accumulate and for the inflammatory response to the ischemia-reperfusion insult of exertion to peak.

    - *Chronicity:* Long-lived plasma cells in bone marrow and mucosal niches can secrete autoantibodies for decades without requiring ongoing B cell stimulation (Section @hyp:plasma-cell-sanctuary). These plasma cells are resistant to conventional immunosuppression and to B cell depletion (explaining the rituximab failure). Only plasma cell-targeting agents (daratumumab) or non-selective antibody removal (immunoadsorption) can address this reservoir.

    - *Multi-system spread:* GPCRs are expressed in virtually every tissue. $beta_2$-adrenergic receptors are found on cardiomyocytes, bronchial smooth muscle, vascular endothelium, hepatocytes, adipocytes, and immune cells. Muscarinic receptors are expressed in the brain, heart, smooth muscle, secretory glands, and immune cells. Functional autoantibodies against these receptors would produce dysfunction wherever these receptors mediate physiological responses—which is essentially everywhere.

#include "subsec-04-gpcr-autoantibody-cascade/hypotheses/hyp-gpcr-autoantibody-cascade-as-trigger-cap.typ"

=== TRPM3 Channelopathy
<sec:root-trpm3>

The most recently validated candidate, TRPM3 ion channel dysfunction, was confirmed in a 2026 multi-site study @Sasso2026trpm3 and is detailed in Section @sec:trpm3-hypotheses. TRPM3 (Transient Receptor Potential Melastatin 3) is a calcium-permeable non-selective cation channel expressed in a remarkably diverse set of tissues: NK cells, T cells, B cells, neurons (including dorsal root ganglion nociceptors), pancreatic beta cells, vascular smooth muscle, renal epithelium, and retinal ganglion cells. Dysfunction of this single molecular target produces a breadth of downstream effects that rivals the multi-system reach of GPCR autoantibodies.

The central insight is that TRPM3 mediates calcium influx required for multiple calcium-dependent cellular processes: immune cell degranulation (the release of cytotoxic granules by NK cells and cytotoxic T cells), neurotransmitter vesicle fusion and release, insulin granule exocytosis, and vascular smooth muscle contraction. Calcium is the universal intracellular second messenger; a channel that gates calcium entry in multiple cell types is, by definition, a multi-system regulator.

When TRPM3 function is impaired, the consequences manifest simultaneously across all expressing tissues:

*Immunological consequences.* The “stuck doors” metaphor from Section @sec:trpm3-hypotheses captures the core immunological defect: immune cells (particularly NK cells) recognize their targets normally—the pattern recognition and activation machinery is intact—but cannot complete the killing because degranulation requires calcium influx through TRPM3 (among other channels). The cytotoxic granules are loaded, the cell is activated, but the final exocytosis step is impaired. The result is the paradoxical immune state characteristic of ME/CFS: simultaneous overactivation (persistent recognition, recruitment of more immune cells, elevated cytokine signaling) and underperformance (failed effector function, persistent target survival). This frustrated immune response consumes energy—activated immune cells have metabolic rates 10–100 times their resting rate—without achieving pathogen clearance, creating a sustained metabolic drain.

*Neurological consequences.* TRPM3 in dorsal root ganglion neurons participates in nociception and thermal sensation. Channel dysfunction may contribute to the pain sensitization, temperature dysregulation, and sensory processing abnormalities reported in ME/CFS. In central neurons, disrupted calcium signaling affects neurotransmitter release kinetics, potentially contributing to the cognitive dysfunction and altered synaptic plasticity.

*Metabolic consequences.* TRPM3 in pancreatic beta cells participates in glucose-stimulated insulin secretion. Channel dysfunction may impair insulin release, contributing to the glucose utilization abnormalities and metabolic inflexibility documented in ME/CFS (Chapter @ch:energy-metabolism). Additionally, mitochondrial calcium uptake—which regulates TCA cycle enzyme activity and oxidative phosphorylation rate—depends on cytosolic calcium signals that TRPM3 contributes to. Impaired TRPM3 function may therefore directly reduce mitochondrial metabolic capacity.

*Vascular consequences.* TRPM3 in vascular smooth muscle contributes to vessel tone regulation. Channel dysfunction may alter the balance between vasoconstriction and vasodilation, contributing to the perfusion abnormalities documented in ME/CFS.

*Assessment against the four criteria.*

    - *Precipitant compatibility:* Post-viral acquisition of TRPM3 dysfunction is plausible through several routes: direct viral modification of channel protein or its regulatory subunits, autoantibody formation against channel epitopes (particularly the extracellular domains), epigenetic silencing of TRPM3 gene expression during the inflammatory response, or persistent modification of the lipid membrane environment that affects channel gating (TRPM3 activity is modulated by membrane cholesterol and PIP#sub[2] content). The inflammatory and oxidative environment of acute infection could produce any of these modifications.

    - *Energy collapse sufficiency:* Impaired mitochondrial calcium signaling reduces oxidative phosphorylation capacity by limiting calcium-dependent activation of TCA cycle dehydrogenases. The frustrated immune response described above consumes ATP without resolution, creating a sustained metabolic drain. Disrupted insulin secretion impairs glucose utilization in insulin-dependent tissues. Together, these produce a multi-pathway energy failure that worsens with exertion, because exertion increases calcium-dependent metabolic demands that dysfunctional channels cannot support.

    - *Chronicity:* If TRPM3 dysfunction reflects a structural channel modification (covalent post-translational modification, autoimmune targeting, or epigenetic silencing), it persists independently of the triggering event. The secondary immune dysregulation—chronic activation without resolution—further stabilizes the pathological state by maintaining the inflammatory environment that may have caused the channel dysfunction in the first place.

    - *Multi-system spread:* TRPM3 is expressed across immune, neural, endocrine (pancreatic), and vascular tissues. Channel dysfunction in all these tissues produces the multi-system presentation characteristic of ME/CFS. The tissue distribution of TRPM3 maps remarkably well onto the organ systems affected in ME/CFS.

TRPM3 channelopathy is compatible with the neuronal genetic architecture: like the GPCR autoantibody cascade, it is proposed as an acquired mechanism — a post-infectious ion channel dysfunction — not a genetically encoded trait. The DecodeME GWAS identified no TRPM3 locus associations, consistent with TRPM3 dysfunction being environmental in origin (viral modification, autoantibody-mediated blockade, epigenetic silencing). The TRPM3 channel's expression in central and peripheral neurons — including dorsal root ganglion nociceptors and striatal circuits implicated by the GWAS cell-type enrichment — provides a direct anatomical bridge between the genetic-architecture finding (vulnerability is neuronal) and a plausible acquired mechanism operating on that neuronal substrate. If TRPM3 dysfunction is confirmed in CNS neurons (currently unmeasured), it would link the most replicated ion channel finding in ME/CFS to the tissue that genetics identifies as the site of constitutional vulnerability.

#include "subsec-05-trpm3-channelopathy/hypotheses/hyp-trpm3-channelopathy-as-trigger-capable-r.typ"

==== TRPM3 Sensitization via Pregnenolone Sulfate

The TRPM3 channel is not merely dysfunctional in ME/CFS—it is a potential _therapeutic target_. Pregnenolone sulfate (PregS) is a known endogenous TRPM3 agonist that activates the channel through a direct binding site, as demonstrated by Vriens et al.\ in the landmark study establishing TRPM3 as a nociceptor channel @Vriens2011pregnenolone. Wagner et al.\ showed that TRPM3 functions as an ionotropic steroid receptor in pancreatic beta cells, directly activated by PregS @Wagner2008pregnenolone.

The therapeutic hypothesis is that exogenous pregnenolone or neurosteroid precursors could partially restore TRPM3 function, lowering the effective threshold for other interventions—functioning as a "sensitizer" that makes the overall treatment combination more effective. This connects to the separatrix nudging framework (Chapter @ch:causal-hierarchy-formal, Section @sec:separatrix-nudging): if TRPM3 function contributes 0.10--0.15 of the single-parameter escape threshold, and PregS supplementation restores a fraction of that, the synergistic coefficient $gamma_("TRPM3","CI") approx 0.45$ with Complex I function means a modest TRPM3 improvement disproportionately enhances energy-targeted interventions.

Cabanas et al.\ demonstrated that naltrexone restores TRPM3 ion channel function in ME/CFS NK cells _in vitro_ @Cabanas2018trpm3, establishing proof-of-concept that pharmacological TRPM3 modulation is achievable. Whether PregS achieves the same effect through a different mechanism (direct agonism vs.\ opioid receptor antagonism-mediated channel restoration) is an open question.

#include "subsec-06-trpm3-sensitization-via-pregnenolone-sul/speculations/spec-pregnenolone-sulfate-as-trpm3-sensitizer.typ"

=== Relationships Among Trigger-Capable Mechanisms
<sec:root-cause-relationships>

The four trigger-capable mechanisms are not independent. Their interconnections are extensive and create a web of potential co-activation that complicates the question of “which came first” while simultaneously explaining why ME/CFS is so resistant to single-target treatments.

GPCR autoantibodies may modulate TRPM3 gating through second messenger pathways: muscarinic receptor autoantibodies activate phospholipase C, which hydrolyzes PIP#sub[2]—a lipid required for TRPM3 channel activity (Section @sec:trpm3-hypotheses). Chronic PIP#sub[2] depletion from sustained autoantibody-driven PLC activation could reduce TRPM3 function, making the GPCR autoantibody cascade and TRPM3 channelopathy two aspects of a single pathogenic process rather than independent root causes.

CNS energy failure may activate the metabolic safe mode program: if hypothalamic energy supply drops below a threshold, the brain may interpret this as a threat signal and engage the metabolic suppression program, linking the CNS energy crisis to the safe mode lock. Conversely, the safe mode program's deliberate metabolic suppression includes reduced cerebral blood flow and neurotransmitter synthesis, contributing to the CNS energy deficit.

The safe mode program's immune activation component—maintained cytokine production, persistent inflammatory signaling—creates an environment conducive to autoimmune breakthrough through molecular mimicry or bystander activation, potentially generating GPCR autoantibodies as a secondary consequence of the safe mode state.

These interconnections mean that in practice, trigger-capable mechanisms may co-activate, and the question of which mechanism was “first” may be unanswerable in individual patients. The more productive question—and the one with therapeutic relevance—is: which root-level processes are _currently active_ and maintaining the disease? A patient whose disease began with GPCR autoantibodies may now be maintained primarily by the metabolic safe mode lock, if epigenetic consolidation has rendered the safe mode self-sustaining independent of its original autoantibody trigger. Conversely, a patient who entered through the safe mode door may now have developed secondary GPCR autoantibodies that represent a new, independent disease-maintaining mechanism.

This distinction between _initiating cause_ and _maintaining cause_ is crucial for treatment strategy and is developed further in Section @sec:treatment-vs-cause.

Figure @fig:trigger-mechanism-relationships maps the bidirectional interactions among the four trigger-capable mechanisms, illustrating how co-activation and mutual reinforcement complicate the identification of a single initiating cause.

#include "../../../figures/fig-trigger-mechanism-relationships.typ"
