#import "../../../../shared/environments.typ": *

==== Step D1: HIF-1α stabilization → WASF3 upregulation (transcriptional trigger)

*Mechanism:* HIF-1α is the master transcriptional regulator of the hypoxic response. Under normoxia, HIF-1α is constitutively produced but immediately degraded (prolyl hydroxylase hydroxylates HIF-1α → pVHL ubiquitin ligase recognition → proteasomal degradation). Under hypoxia or pseudohypoxia (ROS accumulation, succinate accumulation, fumarate accumulation — all inhibit prolyl hydroxylase), HIF-1α escapes degradation → translocates to nucleus → dimerizes with HIF-1β → binds hypoxia response elements (HREs) → transcriptionally activates target genes including WASF3, PDK1, LDH-A, GLUT1, and VEGF.

*Probes for HIF-1α→WASF3 pathway:*
- *Dimethyl fumarate (DMF, 120--240 mg BID):* Activates Nrf2 → Nrf2 binds antioxidant response elements (AREs) → upregulates antioxidant enzymes (SOD, catalase, glutathione peroxidase) → reduces ROS → reduces ROS-mediated prolyl hydroxylase inhibition → restores HIF-1α degradation → reduces WASF3 expression. Additionally, DMF directly inhibits HIF-1α nuclear translocation (Nrf2 competes with HIF-1α for CBP/p300 coactivators). If DMF improves exercise tolerance and reduces lactate → HIF-1α-driven WASF3 upregulation is present and rate-limiting. If DMF causes severe flushing → mast cell hyper-reactivity (Pattern 3, @sec:side-effects-diagnostic) — pre-treat with aspirin (blocks PGD2-mediated flushing without affecting Nrf2 activation). If flushing is aspirin-preventable → confirms PGD2-mediated MCAS subtype.
- *Vitamin C (500--2000 mg, timed with peak prolyl hydroxylase activity — circadian-optimized, @sec:safe-mode):* Prolyl hydroxylase requires vitamin C as a cofactor. If timed vitamin C improves symptoms → prolyl hydroxylase was cofactor-limited, and HIF-1α stabilization was vitamin-C-reversible. Distinguishes cofactor deficiency (simple, nutritional) from ROS-mediated PHD inhibition (requires antioxidant intervention). If vitamin C + NAC works where vitamin C alone does not → ROS is the dominant PHD inhibitor; the vitamin C provides cofactor, NAC scavenges the ROS that was inhibiting PHD.
#finding(claim: [DMF AND vitamin C/NAC produce no improvement], explanation: [HIF-1α stabilization is not the dominant mechanism of WASF3 upregulation; WASF3 may be regulated by genetic variants, epigenetic methylation, or non-HIF-1α transcriptional regulators (NF-κB, STAT3)], certainty: [Low to Medium], level: [Partial root cause])
