#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Severity-Dependent Baseline Gut Permeability])[
*Certainty: 0.50.* The individual supporting observations (CBF reduction by severity @VanCampen2020SeverityCPET, cytokine-severity correlations @Montoya2017, reduced cortisol in severe patients @Komaroff2021severe, POTS comorbidity @Komaroff2021severe) are moderately well-established, but their _integration_ into a unified severity-stratified permeability model has not been directly tested. Certainty is set at 0.50 rather than the originally proposed 0.65 to reflect this untested integration.

Severe ME/CFS patients likely exhibit _higher_ baseline permeability markers than mild/moderate patients, mediated by four convergent mechanisms:

    - *Chronic splanchnic dysregulation*: Severe patients demonstrate exaggerated vascular dysregulation during minimal stress. van Campen et al. @VanCampen2020SeverityCPET documented 27% reduction in cerebral blood flow during 20-degree head-up tilt in severe ME/CFS patients, compared to 7% in healthy controls. Given that splanchnic vessels receive lower circulatory priority than cerebral vessels during sympathetic activation, severe patients likely experience chronic low-grade splanchnic hypoperfusion during routine activities (postural changes, cognitive work, meals), leading to sustained gut barrier stress rather than episodic exercise-induced spikes.

    - *Cytokine-mediated barrier disruption*: Montoya et al. @Montoya2017 established that 17 cytokines correlate linearly with ME/CFS disease severity, 13 of which are proinflammatory. Several of these—particularly IL-1$beta$, IL-6, and IFN-$gamma$—are known to disrupt tight junction proteins through direct effects on occludin and ZO-1 expression @Montoya2017. In severe patients with sustained cytokine elevation, this creates a potential _bidirectional cycle_: cytokines disrupt tight junctions $arrow.r$ LPS translocation increases $arrow.r$ TLR4 activation amplifies cytokine production $arrow.r$ further barrier compromise. This self-sustaining loop may explain why disease severity tends to increase over time in some patients.

    - *Impaired barrier repair capacity*: A comprehensive biomarker examination of severely ill (housebound) ME/CFS patients @Komaroff2021severe revealed significantly lower morning salivary cortisol (median 0.20 mcg/dL vs.\ 0.45 mcg/dL in controls, p=0.002) and reduced serum albumin. Cortisol is essential for tight junction protein expression and barrier maintenance; albumin reflects protein nutritional status necessary for epithelial cell regeneration. Severe patients' reduced capacity for barrier repair may allow wheat-induced or hypoperfusion-induced permeability to persist longer than in ambulatory patients.

    - *POTS comorbidity and splanchnic pooling*: Approximately 45% of severely ill ME/CFS patients exhibit orthostatic intolerance @Komaroff2021severe, suggesting substantial overlap with postural orthostatic tachycardia syndrome (POTS). In POTS, the splanchnic vascular bed—which contains up to 30% of total blood volume—exhibits excessive abdominal blood pooling even in supine and resting positions. This chronic pooling can paradoxically reduce effective splanchnic perfusion during activity, as blood accumulates in distended vessels rather than perfusing capillary beds. For severe ME/CFS patients with POTS features, baseline gut hypoperfusion may be a chronic condition rather than an activity-triggered event.

] <hyp:severity-gut-permeability>
