#import "../../../../shared/environments.typ": *

*Abbreviations used in this section:*

/ *ATP*:  adenosine triphosphate
/ *BBB*:  blood-brain barrier
/ *BP*:  blood pressure
/ *CNS*:  central nervous system
/ *CoQ10*:  coenzyme Q10; ubiquinol/ubiquinone
/ *CYP*:  cytochrome P450
/ *DA*:  dopamine
/ *DNRI*:  dopamine-norepinephrine reuptake inhibitor
/ *ETC*:  electron transport chain
/ *GPCR*:  G protein-coupled receptor
/ *GSH*:  glutathione; primary intracellular antioxidant
/ *HPA*:  hypothalamic-pituitary-adrenal axis
/ *HR*:  heart rate
/ *IENFD*:  intraepidermal nerve fiber density
/ *IVIG*:  intravenous immunoglobulin
/ *LDN*:  low-dose naltrexone
/ *MCAS*:  mast cell activation syndrome
/ *NAC*:  N-acetylcysteine
/ *NE*:  norepinephrine
/ *NMDA*:  N-methyl-D-aspartate
/ *NRI*:  norepinephrine reuptake inhibitor
/ *PDH*:  pyruvate dehydrogenase
/ *PEM*:  post-exertional malaise
/ *POTS*:  postural orthostatic tachycardia syndrome
/ *PMC*:  post-masking crash (see Mechanism H)
/ *PTSD*:  post-traumatic stress disorder
/ *REE*:  resting energy expenditure
/ *ROS*:  reactive oxygen species
/ *SC*:  supercomplex
/ *TLR4*:  Toll-like receptor 4
/ *VMAT2*:  vesicular monoamine transporter 2
/ *hEDS*:  hypermobile Ehlers-Danlos syndrome


=== Protracted and Permanent Worsening After Medications
  <sec:protracted-permanent-worsening>

*Certainty: 0.20--0.35.* No systematic study has measured medication-induced protracted or permanent worsening in ME/CFS. The mechanisms below derive from known pharmacology, the energy ratchet model (@sec:ratchet-cascade), and documented adverse reaction patterns in this population. Clinical incidence is unknown. Every estimate in this section is provisional pending controlled pharmacovigilance data.

==== Definitions and Temporal Boundaries

The distinction between protracted and permanent worsening is clinical, not absolute — a patient who has not recovered by year 5 may still recover by year 10, and post-mortem histological data do not exist. The definitions below establish working boundaries for clinical decision-making, not fixed biological thresholds.

#definition(title: [Protracted Worsening])[
*Definition:* A medication-induced decline in functional baseline that persists for weeks to months after drug discontinuation — beyond the drug's pharmacokinetic clearance window (5 × half-life) — but eventually returns to or near the pre-treatment baseline.

*Temporal boundary:* Duration exceeds drug clearance + expected PEM recovery window (typically 2--6 weeks for a moderate crash) but less than 6--12 months. If function has not returned to within 80% of pre-treatment baseline by 12 months, the worsening is reclassified as permanent.

*Mechanistically:* Protracted worsening implies the drug triggered a cascade that outlasts receptor occupancy — VMAT2 depletion, microglial activation cycle, epigenetic de-repression, HPA axis suppression, or a PEM episode that the patient's reduced recovery capacity could not fully resolve before the next stressor. The system is in a stable but reversible off-baseline state.

*Clinical implication:* Do NOT rechallenge. The drug demonstrated the capacity to trigger a cascade beyond its pharmacology. The fact that the patient eventually recovered does not mean the next exposure will follow the same trajectory — each episode of protracted worsening may consume recovery capital that is finite.
] <def:protracted-worsening>

#definition(title: [Permanent Worsening])[
*Definition:* A medication-induced decline in functional baseline that persists beyond 12 months after drug discontinuation, with no meaningful recovery toward the pre-treatment baseline. This includes both step-function deterioration (a single dose/cycle causes an immediate, irreversible drop) and ratchet deterioration (each exposure causes incremental decline, with ≤80% recovery between cycles, producing cumulative net loss).

*Temporal boundary:* No return to ≥80% of pre-treatment functional baseline by 12 months after cessation. At that point, recovery is no longer the working assumption — the worsening is the patient's new baseline, and treatment strategy must adapt accordingly.

*Mechanistically:* Permanent worsening implies the drug triggered a cascade culminating in structural-level damage that the body cannot repair — neuronal loss (VMAT2 terminal dropout, IENFD reduction), mitochondrial DNA damage beyond repair capacity, epigenetic consolidation into a new transcriptional set-point, or immunologic sensitization that permanently lowers the activation threshold for the same inflammatory cascade. The energy ratchet model predicts exactly this: a sufficiently severe PEM episode, or a drug-induced metabolic stress that mimics one, consumes irrecoverable functional capacity because the underlying repair deficit (impaired mitophagy, depleted GSH, chronic neuroinflammation) means damage accumulates faster than it is cleared.

*Clinical implication:* The damage is done. The goal shifts from "recovery" to "adaptation" — managing the patient at their new, lower baseline. The medication that caused this should be documented as a severe intolerance in the patient's record (functionally listed as an allergy, though the mechanism is not IgE-mediated). Any medication sharing the same pharmacodynamic target should be approached with extreme caution — if the mechanism was VMAT2 depletion, all catecholamine-releasing agents are contraindicated; if the mechanism was microglial triggering, all neuroactive medications that activate TLR4 should be avoided.
] <def:permanent-worsening>

==== The Energy Ratchet as the Unifying Mechanism for Medication-Induced Worsening

The energy-ratchet hysteresis model (@sec:ratchet-cascade) describes progressive, irreversible loss of functional capacity across repeated PEM episodes. The same model applies to medication-induced worsening, with one critical difference: the drug is the PEM trigger, not exertion. Unlike voluntary exertion, which the patient can limit or terminate when symptoms start, medication-induced PEM can continue for the full duration of drug exposure. This produces a relentless, weeks-to-months-long metabolic collapse that often far exceeds any PEM episode the patient has experienced from physical exertion alone.

The ratchet operates through four converging pathways:

1. *Metabolic substrate depletion:* The drug imposes a chronic energy demand (increased REE, sympathetic activation, immune activation, hepatic CYP processing) that depletes ATP, NAD⁺, and glutathione below the recovery threshold. The system cannot replenish substrates while they are being consumed — a net-negative metabolic balance sustained over weeks.
2. *Mitochondrial damage accumulation:* Sustained metabolic stress → sustained ROS production → mitochondrial DNA damage → ETC dysfunction → less ATP production per unit substrate → still greater deficit. The mitochondria that were already damaged by the disease process are now further damaged by the drug — and mitophagy, already impaired in ME/CFS, cannot clear the damaged organelles. The loss is cumulative and, above a threshold, irreversible.
3. *Epigenetic consolidation:* Sustained stress signaling (NF-κB, p38 MAPK, HIF-1α) drives histone modifications and DNA methylation patterns that transcriptionally lock the cell into a low-energy state. The drug-induced stress episode — if severe enough and long enough — can consolidate a temporary metabolic shutdown into a permanent transcriptional program.
4. *Immunologic sensitization:* A drug-induced inflammatory cascade can prime the immune system such that the same cascade is triggered more easily next time — permanently lowering the activation threshold. This is the pharmacologic analog of the kindling model: each exposure lowers the threshold for the next, and a single severe exposure can reset the threshold to a new, permanently lower level.

*Diagnostic implication:* When a patient reports that they "never recovered" from a medication trial, the ratchet model provides the mechanistic explanation. The drug-induced metabolic stress exceeded the repair capacity, damage accumulated, and the system settled at a new, lower baseline. The question is not whether the patient's report is accurate — it is which of the four ratchet pathways was the dominant mechanism, because the answer determines which future medications carry the same risk.

==== Eleven Mechanisms of Medication-Induced Worsening

Every medication-induced protracted or permanent worsening falls into one or more of the following eleven categories. The categories are not mutually exclusive — a single drug can trigger multiple mechanisms simultaneously, and the most severe worsening occurs when several mechanisms converge.

===== Mechanism A — Pharmacodynamic Direct Damage

The drug's primary pharmacodynamic effect directly damages a vulnerable system. This is the simplest mechanism: the drug does what it was designed to do, but the target system is too fragile to tolerate the perturbation. Note: direct endocrine suppression (corticosteroid → HPA axis atrophy) is addressed under Mechanism J below; Mechanism A here covers non-endocrine direct damage.

*Classic example:* Amphetamines → VMAT2 depletion. The drug reverses the dopamine transporter and depletes vesicular stores — its intended mechanism. In a patient with borderline VMAT2 terminal density (as documented in long COVID @Liu2026VMAT2longcovid), a single dose can collapse the dopaminergic system. The crash lasts weeks because vesicular repopulation requires de novo synthesis of VMAT2 protein and reuptake of dopamine into newly empty vesicles — both energy-intensive processes that an energy-compromised neuron cannot perform quickly. If terminal dropout occurs (the depletion is so severe that the terminal cannot recover and dies back), the loss is permanent.

*Other examples:* Valganciclovir bone marrow suppression → hematopoietic stem cell depletion if concurrent with chronic inflammation-driven myelosuppression. Aminoglycoside antibiotics → direct cochlear/vestibular hair-cell toxicity → irreversible sensorineural hearing loss or vestibular dysfunction, and in ME/CFS patients with pre-existing autonomic instability, vestibular loss compounds orthostatic intolerance. Statins → HMG-CoA reductase inhibition in skeletal muscle → coenzyme Q10 depletion + impaired mitochondrial function in myocytes → rhabdomyolysis spectrum, from mild CK elevation to frank muscle necrosis; ME/CFS patients with pre-existing mitochondrial dysfunction have lower tolerance. MAO inhibitors → irreversible MAO binding → 2--4 weeks to resynthesize enzyme after discontinuation; in a patient dependent on monoamine oxidase for catecholamine recycling, this period of impaired turnover can trigger a protracted crash. Chemotherapy agents (vincristine, cisplatin, taxanes) → direct axonal toxicity, microtubule disruption, or mitochondrial poisoning; in ME/CFS patients whose nerves already have reduced IENFD, the reserve for tolerating further neurotoxicity is minimal.

*Diagnostic:* The drug's primary mechanism is the cause. The temporal relationship is clear: onset during exposure, resolution timeline maps the target system's repair rate (VMAT2 protein half-life: estimated at 2--4 days from rodent studies; terminal regrowth: weeks to months; nerve regeneration: months to years; cochlear hair cells: do not regenerate — loss is permanent; MAO resynthesis: 2--4 weeks). If the drug also causes cumulative toxicity, Mechanism G applies concurrently.

===== Mechanism B — Metabolic Cost-Induced PEM Cascade

The drug does not directly damage the target system but imposes a metabolic cost (increased REE, sympathetic activation, immune activation, hepatic processing) that is sufficient to trigger a PEM episode. That PEM episode then follows the standard ratchet trajectory — the same mechanism that makes a physical crash cause permanent decline. The drug is the trigger; the PEM cascade is the effector.

*Classic example:* Methylphenidate — increases resting energy expenditure by an estimated +7% and HR by 10--20 bpm. In a patient whose daily energy budget is already at zero margin, a sustained metabolic demand increase over 4--6 weeks produces a cumulative energy deficit that the system cannot close. The patient functions better during the drug (cognitive benefit from increased synaptic NE/DA) but depletes faster — the functional improvement masks the metabolic depletion until the crash is catastrophic. The crash on cessation is both withdrawal (NE/DA depletion) and PEM (metabolic debt catching up). If the PEM episode is severe enough, the ratchet advances.

*Other examples:* Modafinil → insomnia → sleep deprivation → cumulative glymphatic impairment → neuroinflammatory escalation → PEM. IVIG → immune complex formation + complement activation → transient 48--72h inflammatory flare → PEM episode in an energy-depleted patient, and if the flare severity exceeds recovery capacity, the ratchet advances. Systemic beta-agonists (albuterol, terbutaline) → sustained sympathetic activation → tachycardia + increased metabolic rate → net-negative energy balance. Thyroid hormone replacement at even slightly supraphysiologic doses → increased basal metabolic rate → accelerated substrate depletion in a system with zero energy margin. Any drug causing sustained tachycardia (anticholinergics, some antipsychotics) → chronic increased cardiac work → cumulative metabolic drain.

*Diagnostic:* The drug's therapeutic effect was positive (the drug "worked") but the metabolic cost exceeded the benefit. The worsening is from the metabolic debt, not the drug's direct pharmacology. The same drug at a lower dose, with concurrent metabolic support (CoQ10, NADH, NAC), or with a different dosing schedule (alternating days, periodic washout) may avoid the ratchet — but only if the dose-reduction maintains therapeutic benefit while staying below the metabolic-cost PEM threshold.

===== Mechanism C — Paradoxical Receptor Reaction

The drug produces a paradoxical reaction (Pattern 2, @sec:side-effects-diagnostic) — instead of the expected therapeutic or side effect, the target system responds in the opposite direction. This paradoxical response can trigger a cascade that outlasts receptor occupancy.

*Classic example:* LDN causing severe depression or suicidal ideation in the paradoxical reactor phenotype. Expected: brief opioid receptor blockade → compensatory endorphin upregulation → mood improvement. Observed: opioid blockade unmasked a severe endogenous opioid deficit, and the receptor-level dysregulation triggered a depressive episode that persists beyond LDN clearance because: (a) the opioid system cannot restore tone quickly — opioid peptide synthesis and receptor trafficking take days to weeks to re-equilibrate; (b) the depressive episode triggered a secondary stress cascade (HPA axis overactivation → cortisol → hippocampal glucocorticoid receptor downregulation → HPA axis desensitization) that sustains itself after the original trigger is gone; (c) the patient may have an OPRM1 polymorphism that alters naltrexone binding kinetics such that receptor occupancy lasts longer than predicted by plasma half-life.

*Other examples:* H2 antagonists (famotidine, cimetidine) → paradoxical depression → sustained mood deterioration from H2 receptor-mediated CNS histamine pathway disruption, with the same secondary cascade mechanism as LDN. Benzodiazepines or Z-drugs → paradoxical excitation (from altered chloride gradients, NKCC1/KCC2 imbalance) → sustained hyperarousal that persists beyond drug clearance because the excitation triggered a microglial activation cycle that is self-sustaining. Ketamine → psychotomimetic reaction at sub-anesthetic dose → traumatic psychological experience → PTSD-like hypervigilance that lowers the patient's PEM threshold permanently through chronic sympathetic overactivation. Aripiprazole at microdose (0.25--0.5 mg) in patients with supersensitive D2/D3 receptors → partial agonism at supersensitive receptors produces full-agonist-level activation → akathisia and agitation that may persist weeks beyond clearance if receptor-state consolidation occurs. Fludrocortisone → paradoxical worsening of orthostatic symptoms in patients with connective-tissue-driven venous pooling (hEDS component) — volume expansion pools in the legs rather than increasing cardiac preload, and hypokalemia worsens vascular smooth muscle function.

*Diagnostic:* The patient has the paradoxical reactor phenotype — the receptor system is inverted. This is a permanent trait: the patient's receptor system will always respond paradoxically to this drug class, and likely to others that converge on the same receptor population. The reaction identifies the receptor system (opioid, histamine, GABA/glutamate, dopamine, mineralocorticoid) as a core component of this patient's ME/CFS — it was load-bearing for homeostasis, and its disruption unmasked the dependency.

===== Mechanism D — Immune Sensitization / Neo-Autoimmunity

The drug triggers an immune response that outlasts the drug exposure — either by inducing autoantibody production, by sensitizing mast cells, or by triggering an autoimmune cascade that propagates independently.

*Classic example:* Rituximab inducing late-onset neutropenia or secondary immunodeficiency → persistent infection susceptibility that outlasts B-cell repopulation because the bone marrow niche was damaged. IVIG triggering anti-IgA antibodies in IgA-deficient patients → anaphylaxis on subsequent exposure because the first exposure sensitized the immune system.

*Other examples:* Any drug can theoretically induce drug-induced lupus or drug-induced autoimmune hepatitis — rare but documented across multiple drug classes (minocycline, TNF inhibitors, hydralazine, procainamide). The mechanism is hapten formation (drug binds to a self-protein → immune system recognizes the drug-protein complex as foreign → cross-reactive antibodies that also recognize the unmodified self-protein → ongoing autoimmunity after drug clearance). In ME/CFS patients with pre-existing immune dysregulation, this mechanism may be more likely — the immune system is already primed to break tolerance, and a drug-provided hapten may be the final trigger. Immune checkpoint inhibitors (pembrolizumab, ipilimumab) → removal of peripheral tolerance checkpoints → autoimmune attack on any organ system, with ME/CFS patients at theoretical increased risk given pre-existing autoreactive B-cell expansion. Sulfonamide antibiotics → hypersensitivity syndrome (DRESS) → multiorgan immune activation that can cause permanent end-organ damage (hepatic, renal, cardiac). IVIG in patients with MCAS → complement anaphylatoxin generation (C3a/C5a) → mast-cell degranulation → histamine/tryptase/PGD2 release → further complement activation → self-sustaining complement-mast cell amplification loop that may not self-terminate.

*Diagnostic:* The worsening mechanism is immunologic, not pharmacodynamic. New autoantibodies or immune markers may be detectable. The patient has acquired a new autoimmune condition from the drug — this is a new disease process, not just a worsening of ME/CFS. Treat the new autoimmune condition as a separate entity, with ME/CFS as a modifier of treatment tolerance and recovery trajectory.

===== Mechanism E — Withdrawal or Discontinuation Syndrome That Outlasts Recovery Capacity

The drug's discontinuation produces a withdrawal syndrome, and the patient's energy-depleted state prevents them from weathering the withdrawal. A withdrawal that is mild in healthy patients (resolved within 1--2 weeks) can trigger a PEM cascade in an ME/CFS patient, and the PEM cascade then becomes the dominant pathology — the withdrawal is the match, PEM is the fire, and the fire cannot be extinguished because the patient has no metabolic reserve.

*Classic example:* SSRI/SNRI discontinuation syndrome — serotonin and norepinephrine reuptake blockade is removed → neurotransmitter levels crash → withdrawal symptoms (brain zaps, dizziness, anxiety, dysautonomia). A healthy patient experiences this for 1--2 weeks. An ME/CFS patient experiences this AND the withdrawal triggers a PEM episode — the dizziness and anxiety are stress signals that activate the HPA axis and sympathetic nervous system, consuming energy the patient does not have. The withdrawal-induced PEM episode then follows the standard ratchet trajectory — the longer and more severe the withdrawal, the higher the probability of permanent decline. If the patient was on a high-dose SNRI for years and tapers over 2 weeks (the standard clinical recommendation for a healthy patient), the withdrawal severity + the PEM cost may exceed what the patient's system can absorb.

*Other examples:* Corticosteroid withdrawal → HPA axis suppression + glucocorticoid receptor supersensitivity → withdrawal symptoms (fatigue, body aches, orthostatic intolerance, mood collapse) that are indistinguishable from a severe ME/CFS crash. The patient undergoes a crash that is both withdrawal and PEM, and if the HPA axis cannot recover (prolonged suppression → adrenal atrophy), the crash becomes permanent. Gabapentinoid withdrawal → GABA/glutamate imbalance → anxiety, insomnia, tachycardia → sympathetic overactivation → PEM cascade. Opioid withdrawal → autonomic storm → PEM cascade. Benzodiazepine withdrawal → among the most severe withdrawal syndromes in pharmacology, with anxiety, insomnia, tachycardia, and autonomic instability persisting for months in healthy patients; in ME/CFS, the sustained sympathetic overactivation during extended withdrawal is a prolonged metabolic drain that can trigger a PEM cascade crossing the ratchet threshold. Baclofen withdrawal → GABA-B receptor supersensitivity → severe spasticity, autonomic instability, and in some cases psychosis — the withdrawal syndrome itself can be life-threatening and the PEM cascade it triggers may be catastrophic.

*Diagnostic:* The patient was on the drug long-term (months to years) and discontinued without an ME/CFS-adapted taper protocol. The worsening was from the withdrawal, not the drug's therapeutic effect. The same drug, if never started, would not have caused the problem — but once started, the exit strategy is as important as the entry strategy. This mechanism is particularly pernicious because it converts a maintenance medication (SSRI, SNRI, gabapentinoid, corticosteroid) from a therapeutic tool into a liability: the drug must be continued indefinitely because the cost of stopping is higher than the cost of continuing. The patient is pharmacologically trapped.

===== Mechanism F — Iatrogenic Unmasking of Pre-Existing Occult Pathology

The drug does not directly cause damage but reveals a pre-existing, previously subclinical vulnerability that was already present. The medication acts as a stress test — it exposes pathology that was compensating below the clinical threshold, and once unmasked, the pathology cannot be re-compensated. The drug is the revealer, not the cause, but the clinical consequence (permanent functional decline) is identical to iatrogenic damage. This mechanism is distinct from Mechanism A: the tissue was already damaged before the drug; the drug simply removed the compensation.

*Classic example:* Valacyclovir → CNS toxicity (confusion, hallucinations) at standard doses. The drug itself does not cause neuronal damage — it accumulates due to impaired renal clearance. The CNS toxicity reveals occult renal impairment (reduced GFR) that was previously asymptomatic. The drug is stopped, the acute toxicity resolves, but the renal impairment is permanent — and the patient has learned that their kidneys cannot clear renally-excreted drugs at standard doses. All future renally-cleared medications must be dose-adjusted.

*Other examples:* Corticosteroid trial in a patient with occult adrenal insufficiency → supraphysiologic glucocorticoid suppresses the already-fragile HPA axis → upon taper, the axis cannot recover because it was already near-failure before steroids — the drug unmasks the pre-existing insufficiency and converts it from compensated to decompensated. Beta-blocker trial for POTS → unmasks a patient's dependency on sympathetic drive to maintain cardiac output in the setting of a stiff, hypovolemic ventricle — the drug's beta-1 blockade removes the compensation, and the patient crashes with severe bradycardia and hypotension. A cholinesterase inhibitor (donepezil) in a patient with occult myasthenia → cholinergic crisis because the patient's neuromuscular junction was already compensating for receptor deficiency via increased ACh release; the drug pushes the system into depolarization block. Fluoroquinolones in a patient with occult collagen disorder → tendon rupture reveals previously undiagnosed connective tissue pathology (e.g., undiagnosed EDS). Any vasodilator (nitrates, calcium-channel blockers) in a patient with occult autonomic failure → severe orthostatic hypotension unmasks that the patient was dependent on high sympathetic tone to maintain upright BP.

*Diagnostic:* The patient was stable before the drug and permanently worse after — but the drug's known pharmacology does not explain structural damage. The worsening reveals a pre-existing vulnerability that was compensated. Key distinguishing features: (a) the decline occurs rapidly (hours to days of exposure), faster than cumulative toxicity mechanisms; (b) the culprit organ system was not the drug's primary target — renal toxicity from a non-nephrotoxic drug, autonomic collapse from a non-autonomic drug; (c) the decline does not reverse after drug clearance because the underlying pathology (renal impairment, HPA insufficiency, connective tissue defect) is permanent. This is the pharmacologic equivalent of a cardiac stress test — the treadmill didn't cause the coronary artery disease, it revealed it. The diagnostic information is high-yield and applies to all future medication decisions: the patient now has a documented vulnerability map.

===== Mechanism G — Cumulative Dose-Dependent Toxicity

The drug causes damage that is proportional to total lifetime exposure — each dose contributes additively, and below a threshold cumulative dose, toxicity does not occur. Once the threshold is crossed, damage is often irreversible because the cumulative insult exceeds the tissue's regenerative capacity. ME/CFS patients may have lower toxicity thresholds than the general population due to impaired repair mechanisms, reduced antioxidant capacity (depleted GSH), and pre-existing subclinical organ damage that reduces functional reserve.

*Classic example:* DCA (dichloroacetate) → peripheral neuropathy. DCA-induced axonal damage is dose-cumulative — above a total lifetime dose threshold of approximately 25--30 g, the risk of irreversible neuropathy increases substantially. In ME/CFS patients with pre-existing small-fiber neuropathy (reduced IENFD), the DCA neuropathy threshold is likely lower, and the nerve regeneration machinery is already stressed — even a moderate cumulative dose may produce permanent loss.

*Other examples:* Valganciclovir → cumulative bone marrow suppression → each course depletes the hematopoietic stem cell pool; in a patient with chronic inflammation-driven myelosuppression, the cumulative HSC loss may reach a threshold beyond which marrow recovery is no longer possible. Aminoglycosides → cumulative cochlear hair-cell loss → each exposure kills a fraction of the non-regenerating hair-cell population; hearing loss becomes clinically detectable only when a critical fraction is lost — the toxicity is cumulative and permanent. Cisplatin/carboplatin → cumulative ototoxicity and nephrotoxicity. Amiodarone → cumulative pulmonary fibrosis and thyroid destruction. Long-term metformin → cumulative risk of vitamin B12 deficiency through impaired ileal absorption → subacute combined degeneration of the spinal cord if unrecognized; in ME/CFS patients whose neurologic function is already compromised, B12 deficiency compounds existing neurocognitive deficits. Any drug causing chronic oxidative stress (doxorubicin, chronic acetaminophen at high therapeutic doses) → cumulative GSH depletion + cumulative mitochondrial DNA damage → organ dysfunction that crosses the clinical threshold only after years of silent accumulation.

*Diagnostic:* The worsening is delayed — toxicity emerges after weeks to months (or years) of exposure, not acutely. The temporal relationship is obscured by the delay: the drug was well tolerated initially, and the patient may not connect a slow, insidious decline to a medication started months ago. Key features: (a) toxicity onset correlates with cumulative dose, not plasma concentration or duration of current treatment course; (b) there is no recovery after drug discontinuation — the damage was cumulative and reached an irreversible threshold during treatment; (c) the same drug at the same daily dose was tolerated until it wasn't — the patient's report of "it was fine for months and then suddenly it wasn't" is mechanistically expected. Overlaps with Mechanism A (direct damage) — the distinction is the dose-cumulative nature: Mechanism A produces damage proportional to current receptor occupancy or drug concentration; Mechanism G produces damage proportional to total lifetime exposure. DCA and valganciclovir exhibit both mechanisms simultaneously.

===== Mechanism H — Suppressive Masking → Delayed Catastrophic Crash (PMC)

The drug suppresses the patient's somatic warning signals — PEM early-warning cues, fatigue perception, pain signaling, or autonomic dysregulation symptoms — producing a period of apparent functional improvement during which the patient overexerts. When the drug is stopped, or when the cumulative overexertion debt exceeds even the drug's masking capacity, the patient crashes catastrophically. The drug did not directly cause structural damage (Mechanism A) nor impose a net metabolic cost (Mechanism B) — rather, it disabled the protective feedback loop that normally prevents the patient from exceeding their energy envelope. The crash that follows drug cessation is the accumulated PEM debt — weeks or months of overexertion — arriving all at once. This is the Post-Masking Crash (PMC).

*Classic example:* Amphetamines suppressing fatigue perception → the patient feels cognitively normal and functionally capable, so they increase activity to pre-illness levels. The VMAT2 depletion and metabolic debt (Mechanisms A and B) are accumulating silently beneath the masking effect. When the drug is stopped or tolerance develops, the masking is removed and the full extent of accumulated damage — mitochondrial depletion, VMAT2 terminal loss, weeks of metabolic debt — becomes apparent as a single catastrophic crash. The patient's report of "I felt better than I had in years, and then I crashed harder than I ever have in my life" is the PMC signature.

*Other examples:* Methylphenidate → the dopaminergic cognitive enhancement masks the underlying metabolic depletion (Mechanism B) — the patient functions at a higher level but depletes energy reserves below what their sensory feedback would normally permit, and the crash magnitude is proportional to the duration of masking × the degree of overexertion enabled. Gabapentinoids → suppression of neuropathic pain and anxiety removes the somatic PEM warning signals, allowing the patient to exceed their energy envelope. Benzodiazepines → anxiolysis and muscle relaxation suppress the somatic anxiety and muscle tension that normally signal "stop"; the patient continues activity until exhaustion. NSAIDs or corticosteroids taken for pain → pain suppression enables overexertion during an active inflammatory episode; when the drug wears off, not only does the original pain return, but the accumulated overexertion debt triggers a PEM crash on top of the inflammatory flare. Modafinil → wakefulness promotion masks the sleep-deprivation signal that would normally enforce rest; cumulative sleep debt + glymphatic impairment → neuroinflammatory crash that is more severe than any single night of poor sleep would produce.

*Diagnostic:* The patient reports significant functional improvement during treatment followed by a crash that is disproportionately severe relative to the drug's known withdrawal or toxicity profile. Key features distinguishing PMC from Mechanism B (metabolic PEM): (a) the functional improvement during treatment is reported as "better than baseline," not just "the drug had some benefit"; (b) the crash onset coincides with drug cessation, tolerance development, or the patient's realization that they "overdid it" while on the drug; (c) the crash magnitude correlates with the duration and intensity of the functional improvement — the better the patient felt, the more they overexerted, and the harder they crashed. The PMC mechanism is particularly dangerous because it makes the drug's therapeutic benefit the vector of harm — the drug worked so well at symptom suppression that it bypassed the body's only defense against PEM, which is the sensation of fatigue itself.

===== Mechanism I — Blood-Brain Barrier / Neurovascular Disruption

The drug directly or indirectly disrupts blood-brain barrier (BBB) integrity, allowing peripheral inflammatory mediators, autoantibodies, or the drug itself to enter the CNS compartment at abnormally high concentrations. The resulting neuroinflammatory cascade causes cognitive decline, neuropsychiatric symptoms, or worsening of central sensitization. In ME/CFS, where BBB integrity may already be compromised by chronic neuroinflammation and where circulating autoantibodies against CNS targets may already exist, BBB disruption is particularly dangerous — it removes the one remaining barrier between a dysregulated peripheral immune system and a vulnerable CNS.

*Classic example:* Fluoroquinolone antibiotics (ciprofloxacin, levofloxacin) → BBB disruption via MMP-9 upregulation + direct endothelial toxicity → peripheral inflammatory cytokines and the drug itself enter the CNS → acute neuropsychiatric symptoms (anxiety, insomnia, confusion, psychosis) that can persist for weeks to months because: (a) the BBB repair requires endothelial cell turnover (days to weeks); (b) the inflammatory mediators that entered the CNS during the period of permeability triggered a microglial activation cycle that sustains neuroinflammation after BBB resealing; (c) fluoroquinolones also deplete mitochondrial DNA and impair oxidative phosphorylation in CNS endothelial cells, compounding the injury. ME/CFS patients with pre-existing neuroinflammation have reduced BBB repair capacity.

*Other examples:* Systemic inflammatory response to any drug (DRESS syndrome, serum sickness, severe infusion reaction) → massive cytokine release → transient global BBB permeability → peripheral autoantibodies enter CNS → new-onset neuropsychiatric symptoms. Contrast agents (gadolinium-based) → endothelial toxicity + deposition in brain tissue → chronic neuroinflammatory focus with unknown long-term consequences, particularly relevant in patients with impaired renal gadolinium clearance. Chronic high-dose corticosteroids → glucocorticoid-mediated tight junction protein downregulation (claudin-5, occludin) → gradual BBB leakiness that may not be acutely symptomatic but that over months allows progressive CNS exposure to peripheral inflammatory mediators. IVIG with high IgG concentrations in a patient with already-leaky BBB → IgG entry into CNS parenchyma → local immune-complex formation with CNS autoantigens → neuroinflammatory flare. Certain antihistamines at high doses (diphenhydramine) → anticholinergic-mediated cerebral hypoperfusion + endothelial muscarinic receptor blockade → impaired neurovascular coupling → functional BBB disruption through altered cerebral blood flow regulation.

*Diagnostic:* The worsening is predominantly neuropsychiatric — cognitive decline, mood changes, and new-onset CNS symptoms (headache, photophobia, sound sensitivity, brain fog) disproportionate to systemic symptoms. Key features: (a) temporal relationship to BBB-disrupting drug classes; (b) cognitive symptoms are the dominant manifestation, not fatigue or myalgia; (c) symptoms may partially improve but rarely return fully to baseline because the microglial activation triggered during BBB permeability can become self-sustaining; (d) new sensitivities to light, sound, and cognitive effort emerge or worsen — consistent with central sensitization from CNS neuroinflammation. This mechanism overlaps with Mechanism D when the BBB disruption permits CNS autoantibody entry, and with Mechanism F when the drug unmasks pre-existing BBB fragility or pre-existing CNS autoantibodies.

===== Mechanism J — Endocrine / HPA Axis Disruption

The drug suppresses, disrupts, or permanently alters an endocrine feedback axis. The endocrine system's characteristic time constant — weeks to months for axis recovery, potentially permanent if structural atrophy occurs — means that even brief pharmacologic suppression can produce protracted consequences. ME/CFS patients start with compromised HPA axis function (the hypocortisolism model, @sec:hpa-axis), reduced thyroid hormone conversion, and frequently disrupted gonadal steroid axes — the reserve for tolerating further endocrine perturbation is minimal. This mechanism was previously subsumed under Mechanism A; it is separated here because endocrine axes exhibit distinct recovery dynamics (weeks-to-months feedback-loop re-equilibration vs. structural repair), and because the therapeutic implication differs: endocrine axis suppression may be partially correctable with hormone replacement, while direct structural damage (Mechanism A) cannot be replaced pharmacologically.

*Classic example:* Corticosteroids (prednisone, methylprednisolone, hydrocortisone) → HPA axis suppression. Exogenous glucocorticoids suppress CRH and ACTH via negative feedback at the hypothalamus and pituitary → adrenal zona fasciculata atrophy from lack of trophic stimulation. After drug discontinuation, the axis must recover sequentially: CRH neurons must re-establish tonic firing (days to weeks), pituitary corticotrophs must re-express ACTH (days to weeks), and the atrophied adrenal cortex must regenerate cortisol-producing cells (weeks to months, potentially incomplete if atrophy is severe). During the recovery period, the patient is functionally adrenal-insufficient — unable to mount a cortisol response to any stressor, including the metabolic stress of a PEM episode. If the recovery period coincides with a PEM episode, the patient has no cortisol reserve to contain the inflammatory response, and the PEM cascade is unopposed.

*Other examples:* Megestrol acetate (appetite stimulant) → potent glucocorticoid activity → HPA axis suppression identical to corticosteroids, but often unrecognized because megestrol is prescribed as an appetite stimulant, not as a corticosteroid. Opioid analgesics (chronic use) → suppression of GnRH pulsatility → central hypogonadism → loss of testosterone's neuroprotective and mitochondrial-supportive effects; in ME/CFS patients whose energy metabolism may be testosterone-dependent, this loss compounds mitochondrial dysfunction. Thyroid hormone over-replacement → suppression of TSH → endogenous T4/T3 production suppressed → if exogenous thyroid is then stopped abruptly, the patient undergoes a period of iatrogenic hypothyroidism while the thyroid axis recovers, and hypothyroidism symptoms (fatigue, cognitive slowing, cold intolerance) are indistinguishable from worsening ME/CFS. Aromatase inhibitors or SERMs → estrogen depletion → loss of estrogen's mitochondrial biogenesis signaling (estrogen receptor-β activates PGC-1α) → compounding effect on existing mitochondrial dysfunction. GnRH agonists (leuprolide) → profound suppression of gonadal axis → in female ME/CFS patients, loss of neurosteroid modulation of GABAergic tone → worsening of central sensitization and anxiety. Ketoconazole (antifungal) at high doses → inhibition of multiple cytochrome P450 steroidogenic enzymes → adrenal insufficiency from blocked cortisol synthesis, distinct from HPA axis suppression — the adrenals are capable of producing cortisol but the enzymatic machinery is blocked.

*Diagnostic:* The worsening is systemic — fatigue, orthostatic intolerance, mood changes, and cognitive dysfunction that are indistinguishable from worsening ME/CFS. Key distinguishing features from other mechanisms: (a) the drug is known to suppress or disrupt an endocrine axis; (b) laboratory confirmation is possible — morning cortisol, ACTH stimulation test, testosterone (free and total), thyroid panel (TSH, free T4, free T3), and in women, estradiol and FSH; (c) the temporal recovery pattern maps the axis recovery time constant (HPA axis: months to years; gonadal axis: weeks to months; thyroid axis: weeks); (d) the symptoms may partially respond to physiologic hormone replacement — if hydrocortisone 15--25 mg/day produces partial functional improvement, the HPA axis is the dominant mechanism and the diagnosis is confirmed. This mechanism is distinguished from Mechanism E (withdrawal): in Mechanism J, the damage is the axis suppression itself; in Mechanism E, the withdrawal symptoms trigger PEM which becomes the dominant pathology. The two mechanisms converge when HPA axis suppression during corticosteroid withdrawal (J) produces a withdrawal syndrome (E) that triggers a PEM episode (B) — the full corticosteroid convergence cascade involves J + E + B simultaneously.

===== Mechanism K — Pharmacokinetic Catastrophe from Impaired Clearance

The drug accumulates to toxic concentrations because the patient's clearance mechanisms — hepatic metabolism (CYP450, UGT, sulfation), renal excretion, or biliary elimination — are impaired. ME/CFS-specific factors that reduce clearance include: (a) impaired hepatic CYP450 activity from chronic inflammation (inflammatory cytokines downregulate CYP expression); (b) occult renal impairment from chronic hypoperfusion or comorbid dysautonomia; (c) genetic polymorphisms in CYP enzymes that are silent in the general population but clinically significant when compounded by disease-related metabolic impairment; (d) reduced hepatic blood flow from autonomic dysfunction → reduced first-pass metabolism and higher bioavailability; (e) biliary stasis from reduced oral intake and autonomic gastroparesis → impaired enterohepatic clearance of drugs excreted via bile. The drug is prescribed at a standard dose appropriate for a patient with normal clearance, but the patient's actual clearance is a fraction of normal — drug levels rise to toxic range over days to weeks, and the toxicity is misattributed to the drug's pharmacodynamic mechanism when it is actually a pharmacokinetic problem.

*Classic example:* A tricyclic antidepressant (amitriptyline, nortriptyline) prescribed at a low dose (10--25 mg) for sleep or neuropathic pain in a patient with impaired CYP2D6 function (either genetic poor-metabolizer status or inflammation-mediated CYP2D6 downregulation). The drug accumulates to levels 3--10× higher than expected for the dose → anticholinergic toxicity (tachycardia, confusion, urinary retention, ileus) → the anticholinergic delirium is mistaken for worsening ME/CFS brain fog, and the tachycardia is mistaken for POTS worsening. The drug is continued or even dose-escalated because the toxicity mimics the disease being treated. When the drug is finally stopped, the patient improves — but the anticholinergic burden during the accumulation period may have caused permanent cognitive impairment through sustained muscarinic receptor blockade in the CNS.

*Other examples:* Opioids (codeine, tramadol, oxycodone) in CYP2D6 ultra-rapid metabolizers → prodrugs (codeine → morphine, tramadol → O-desmethyltramadol) convert to active metabolites at rates far exceeding expected → opioid toxicity at standard doses. Conversely, CYP2D6 poor metabolizers get no analgesic effect from codeine or tramadol (cannot convert to active metabolite) but are labeled as "opioid non-responders." Warfarin in patients with impaired CYP2C9 → standard doses produce supratherapeutic INR → bleeding risk. Phenytoin in patients with impaired CYP2C9/2C19 → nystagmus, ataxia, and cognitive impairment at standard doses, misdiagnosed as worsening neurologic ME/CFS symptoms. Valacyclovir → accumulation of acyclovir in patients with occult renal impairment → CNS toxicity (confusion, hallucinations, myoclonus) — this is Mechanism K (pharmacokinetic) revealing Mechanism F (occult renal impairment). Metformin in patients with occult renal impairment → lactic acidosis risk from metformin accumulation. Any polypharmacy combination saturating a shared CYP pathway → competitive inhibition of metabolism → both drugs accumulate → toxicity that is attributed to each drug individually rather than to their interaction.

*Diagnostic:* The drug produces toxicity symptoms at doses that are well tolerated by the general population. Key features: (a) symptoms are dose-dependent — lower doses are tolerated, higher doses are not; (b) symptoms match the drug's known overdose/toxicity profile, not its therapeutic effect; (c) symptoms gradually worsen over days to weeks of continued use as drug accumulates, not on first dose; (d) the same drug class may be tolerated in a different member that uses a different metabolic pathway — e.g., a patient who cannot clear fluoxetine (CYP2D6) may tolerate citalopram (primarily CYP2C19); (e) therapeutic drug monitoring (serum drug levels) confirms supratherapeutic concentrations at standard doses. This mechanism overlaps with Mechanism F when the impaired clearance reveals pre-existing occult pathology (renal impairment, hepatic dysfunction), and with Mechanism G when the accumulation results in cumulative toxicity over time rather than acute overdose. Distinguishing from Mechanism A: Mechanism A produces damage at therapeutic concentrations in a vulnerable system; Mechanism K produces toxicity because concentrations are not therapeutic — they are toxic due to impaired clearance. The clinical distinction matters because Mechanism K can sometimes be managed by simple dose reduction guided by therapeutic drug monitoring, while Mechanism A requires avoiding the drug class entirely.

===== Convergence: When Multiple Mechanisms Act Simultaneously

The most severe and most common cause of permanent worsening is convergence — a single drug triggers multiple mechanisms simultaneously. A typical example: amphetamines in an ME/CFS patient with underlying VMAT2 deficiency.

*Amphetamine convergence cascade:*
- Mechanism A (direct damage): VMAT2 depletion → dopaminergic terminal collapse.
- Mechanism B (metabolic PEM): increased REE + HR + suppressed appetite → net-negative energy balance sustained over weeks → mitochondrial damage accumulation.
- Mechanism C (paradoxical): if the patient has a supersensitive dopaminergic system (from chronic DA deficiency), the amphetamine dose that is therapeutic for a healthy patient produces psychotic excitation — a paradoxical reaction that consumes additional energy.
- Mechanism E (withdrawal): cessation triggers a dopamine crash that itself produces PEM, on top of the existing PEM from metabolic debt and mitochondrial damage.
- Mechanism H (PMC — post-masking crash): amphetamine's suppression of fatigue perception masks the accumulating metabolic debt and VMAT2 depletion; the patient functions at pre-illness levels for weeks while silent damage accrues beneath — when the drug is stopped, the sum of weeks of overexertion arrives as a single catastrophic crash far more severe than any individual day's PEM episode.

The result is a patient who: (a) experienced weeks of functional improvement on the drug (cognitive benefit from increased DA + masking of fatigue), (b) experienced a severe crash on cessation (withdrawal + PEM convergence + PMC of accumulated overexertion debt), (c) never recovered to pre-treatment baseline (VMAT2 terminal loss + mitochondrial damage + epigenetic consolidation), and (d) has lost the option of using any catecholamine-modulating medication because their system has demonstrated catastrophic vulnerability.

This convergence pattern is the mechanism behind the clinical observation that amphetamines cause the most severe and most commonly irreversible worsening in ME/CFS patients — because they hit five of the eleven mechanisms simultaneously in a patient population with a pre-existing catecholamine deficit.

===== Framework Limitations: Overlap, Taxonomy, and Causal Attribution

#limitation(title: [Framework Limitations])[
*Mechanism overlap.* Several mechanism pairs share effector pathways or risk factors and may represent related processes viewed from different angles rather than genuinely distinct mechanisms. Mechanisms B (metabolic PEM) and E (withdrawal-PEM) share the same effector pathway — both converge on PEM → energy-ratchet advancement — and differ only in the trigger (metabolic demand vs. withdrawal). Mechanisms F (iatrogenic unmasking) and K (pharmacokinetic catastrophe) partly overlap — both involve pre-existing vulnerability (occult pathology on one hand, impaired clearance on the other), and the clinical presentation can be identical when impaired clearance reveals occult organ dysfunction (e.g., valacyclovir accumulation from renal impairment). Mechanisms A (direct damage) and G (cumulative toxicity) overlap for drugs like DCA that cause both acute pharmacodynamic damage and cumulative dose-dependent toxicity — a drug that causes direct neuronal injury at any dose will cause even more damage as cumulative exposure increases, blurring the A/G boundary.

*No independent validation.* The eleven-mechanism taxonomy is a clinical heuristic derived from pharmacological first principles. It has not been empirically validated as a classification system. Patients may experience worsening that does not fit cleanly into any single mechanism, or that fits multiple simultaneously. Some apparent medication-induced worsening may instead reflect non-specific drug intolerance — compounded pharmacokinetic impairment from multiple mechanisms (K + CYP polymorphism + renal impairment), or polypharmacy interactions producing a unified global intolerance rather than specific receptor-system pathology.

*Causality is presumed, not established.* ME/CFS severity fluctuates spontaneously, and the disease can progress independently of medication trials. A temporal association between a medication trial and worsening does not establish causation, particularly in a disease with an unpredictable trajectory. If a patient tries 5--10 medications over years of fluctuating illness, some trials will coincide with worsening by chance alone. The attribution of worsening to a specific medication is a working hypothesis, not a confirmed causal relationship. Controlled prospective pharmacovigilance registries are needed to distinguish drug-induced decline from natural disease history.

*Falsifiability of the energy-ratchet model.* The ratchet model (@sec:ratchet-cascade) explains all outcomes (recovery = below threshold; permanent worsening = threshold crossed). For it to function as more than an interpretive framework, it must specify conditions under which it would be abandoned. The single clearest falsification condition: a patient with documented sustained medication-induced metabolic stress (sustained tachycardia + elevated REE for >4 weeks, confirmed by objective measurement) who recovers fully to pre-treatment baseline without lasting functional loss. Such a case would demonstrate that even severe, sustained metabolic stress can be fully reversed — the ratchet is escapable. To date, no such case has been documented in the literature, but the absence of negative evidence is not positive evidence.

*VMAT2 evidence chain.* The amphetamine risk architecture depends on the inference that ME/CFS patients have reduced VMAT2 terminal density. Direct VMAT2 PET measurement exists in long COVID (@Liu2026VMAT2longcovid) but has not been replicated in ME/CFS. The cross-disease inference from long COVID to ME/CFS assumes shared pathophysiology that has not been established. Furthermore, VMAT2 PET is a research-only imaging modality not clinically available — the recommendation to exclude VMAT2 deficiency before considering amphetamines (below) refers to a test that no clinician can currently order. The clinical impression that amphetamines cause permanent worsening in ME/CFS is itself based on patient and clinician reports without systematic pharmacovigilance data, and may be confounded by exposure duration — amphetamines' functional benefit during treatment encourages longer use, producing greater cumulative metabolic stress than medications that are discontinued sooner due to intolerance.

*Consequence:* The eleven-mechanism framework is a clinical reasoning tool, not a validated taxonomy. Clinicians should treat mechanism assignments as working hypotheses and inform patients that the attribution of worsening to a specific medication is probabilistic, not definitive. Future pharmacovigilance registries could validate or refute individual mechanism categories.
]


=== Drug-Indexed Pharmacodiagnostic Reference

For per-medication analysis covering every drug discussed in this chapter — including cascade-node locations, positive/null/side-effect diagnostic inferences, protracted/permanent worsening mechanism assignment, risk classification, and rechallenge guidance — see the Medication Reference at @sec:medication-reference. That section provides the second entry door into this chapter: drug-indexed rather than mechanism-indexed, with each drug's complete ch30 pharmacology aggregated in one place.

Below, the summary risk table ranks medications by worsening risk (for quick cross-drug comparison) and the clinical protocol provides a structured approach when a patient reports never recovering from a medication trial.

==== Summary Risk Table

*Note: All risk classifications are ordinal categories derived from pharmacological first principles and the energy-ratchet model. They are NOT empirical incidence rates — no controlled pharmacovigilance data exist in ME/CFS. Use as a comparative risk framework, not as quantitative probability estimates.*

| Medication | Protracted Risk | Permanent Risk | Dominant Mechanism | Rechallenge? |
|---|---|---|---|---|
| Amphetamines | Very High | High | A + B + E convergence | Never |
| Methylphenidate | High | Moderate | B + E | Only after full recovery, at lower dose, with metabolic support |
| IVIG | Moderate | Low--Moderate | B + D | Only with MCAS pre-treatment |
| Corticosteroids | Moderate--High | Low--Moderate | A + E | Short courses only; taper over weeks, not days |
| Immunoadsorption | Low--Moderate | Low | B | Acceptable with hemodynamic support |
| SSRIs/SNRIs | Low--Moderate | Low | E | Yes, with very slow taper planned in advance |
| Benzodiazepines | Low--Moderate | Low | E | Yes, with very slow taper planned in advance |
| Gabapentinoids | Low--Moderate | Low | E | Yes, with very slow taper |
| DCA | Moderate | Moderate | A | Only if no neuropathy and PDH is the last remaining hypothesis |
| Aripiprazole | Low--Moderate | Low | A + C + D | At lower dose; never if persistent post-clearance akathisia |
| Valganciclovir | Moderate | Low | A | Only with ANC monitoring; G-CSF support if needed |
| H2 Antagonists | Low | Very Low | C | Never if psychiatric reaction |
| LDN | Low | Very Low | C | Never if psychiatric reaction |
| Fludrocortisone | Low | Very Low | C | Yes, at lower dose with compression |
| Valacyclovir | Low | Very Low | A (unmasking) | Yes, with dose adjustment for renal function |
| DMF | Very Low | Very Low | N/A | Yes, with aspirin pre-treatment for flush |
| DORAs | Very Low | Very Low | N/A | Never if sleep paralysis; diagnostic done |
| H1 Antihistamines | Very Low | Very Low | N/A | Yes, at lower dose |
| Pyridostigmine | Very Low | Very Low | N/A | Always, at lower dose |
| Pitolisant | Very Low | Very Low | N/A | Yes, at lower dose |
| Mitochondrial Supplements | Very Low | Very Low | N/A | Always — worsening is diagnostic, not harmful |

==== Clinical Protocol: When a Patient Reports Never Recovering From a Medication

#warning-env(title: [Protocol for Medication-Associated Permanent Decline])[
When a patient reports they "never recovered" after a medication trial, the following protocol should be applied before any new medication is prescribed:

1. *Confirm the temporal relationship.* Did the decline begin during treatment, on dose increase, on discontinuation, or weeks after cessation? The timing maps the mechanism: during treatment → direct pharmacodynamic damage (Mechanism A) or metabolic PEM (Mechanism B); on discontinuation → withdrawal-PEM convergence (Mechanism E); weeks after → paradoxical receptor cascade (Mechanism C) or immune sensitization (Mechanism D).

2. *Quantify the decline.* What was the patient's functional baseline (upright hours, step count, cognitive task capacity, PEM threshold) before the medication trial? What was it 3 months after? What is it now? If the decline is ≥20% of pre-treatment baseline and has not recovered within 12 months → permanent worsening as defined in this section.

3. *Identify the dominant mechanism.* Using the eleven-mechanism framework (A--K) above, identify which mechanism(s) the drug's pharmacology could have triggered. The mechanism determines which future medications carry the same risk: if Mechanism A (pharmacodynamic damage) → avoid all drugs with the same target; if Mechanism B (metabolic PEM) → all drugs that increase metabolic demand are relatively contraindicated; if Mechanism C (paradoxical) → all drugs converging on the same receptor population should be avoided; if Mechanism D (immune sensitization) → all drugs that activate the same immune pathway should be avoided; if Mechanism E (withdrawal-PEM) → any drug that must be discontinued someday carries a risk; if Mechanism F (iatrogenic unmasking) → the unmasked pathology must be formally diagnosed and managed as a new comorbidity; if Mechanism G (cumulative toxicity) → all drugs with dose-cumulative toxicity profiles are relatively contraindicated; if Mechanism H (PMC) → any drug that suppresses fatigue, pain, or PEM warning signals should be avoided or used only with strict activity pacing protocols; if Mechanism I (BBB disruption) → all drugs with known BBB-disrupting potential should be avoided, and the CNS autoantibody status should be assessed; if Mechanism J (endocrine disruption) → the specific endocrine axis must be tested and physiologic replacement considered; if Mechanism K (pharmacokinetic catastrophe) → all drugs metabolized or cleared by the affected pathway require dose reduction guided by therapeutic drug monitoring.

4. *Identify the system that failed.* The worsening pattern identifies which organ system had the least reserve: dopaminergic (amphetamine crash), HPA axis (steroid withdrawal), hematopoietic (valganciclovir marrow suppression), opioid (LDN paradoxical depression), histaminergic (H2 antagonist depression). This is a permanent vulnerability map for the patient — any future medication that taxes the same system carries elevated risk.

5. *Document as a severe intolerance.* The medication that caused permanent worsening should be documented as a severe intolerance in the patient's record, with the specific mechanism noted (e.g., "amphetamine — VMAT2 depletion with permanent functional decline"). While the mechanism is not IgE-mediated, flagging it as functionally equivalent to an allergy helps prevent accidental re-exposure.

6. *Adjust treatment expectations.* The patient is now at a permanently lower baseline. Future treatment trials should target stabilization at this new baseline, not recovery to the pre-medication baseline. The goal is to prevent further ratchet advancement, not to reverse the damage that has already been done.

7. *Screen for iatrogenic comorbidities.* The medication may have caused a new disease entity on top of ME/CFS: iatrogenic adrenal insufficiency (corticosteroids), iatrogenic peripheral neuropathy (DCA), iatrogenic bone marrow failure (valganciclovir), iatrogenic cognitive impairment (benzodiazepines, gabapentinoids), and PTSD from a traumatic adverse reaction (ketamine, LDN psychiatric). Treat these as separate conditions, with ME/CFS as a modifier of treatment tolerance.
] <warn:medication-permanent-decline-protocol>

*Consequence:* Every medication that works therapeutically can also cause protracted or permanent worsening — the question is the magnitude of risk, the mechanism, and whether the diagnostic information justifies the risk. The PEM budget constraint already ranks drugs by diagnostic-yield-to-PEM-cost ratio. The worsening risk adds a second dimension: diagnostic-yield-to-permanent-decline-risk ratio. A drug that provides high-specificity diagnostic information (amphetamine crash confirms VMAT2 pathology) at a 30--50% risk of permanent decline is not a diagnostic probe — it is an unacceptable gamble. The algorithm should sequence probes by (diagnostic yield) / (PEM cost × permanent worsening risk), not just diagnostic yield / PEM cost.
*Origin:* mechanistic-pathway-tracing, 2026-07-23.
