#import "../../../../shared/environments.typ": *

==== Step T2: Pattern diagnosis of ATP triage — which systems are deprioritized?

The core probe: pharmacological bypass of each demand-response signaling pathway. Each drug provides the neurotransmitter or receptor activation that ATP shortage should have funded. The pattern of which bypass works identifies which signaling system is being ATP-triage-deprioritized:

- *Midodrine works → adrenergic signaling (α1) ATP-triage-deprioritized.* The sympathetic nervous system requires ATP for NE synthesis (tyrosine hydroxylase requires BH4, which requires GTP), NE vesicular loading (VMAT2 requires ATP), and NE release (Ca²⁺-dependent exocytosis requires ATP for Ca²⁺-ATPase). If the sympathetic system's ATP budget is cut, NE signaling fails. Midodrine bypasses the entire NE pathway — it directly activates α1 receptors, requiring no ATP for synthesis, storage, or release. The positive midodrine response means α1 receptors are present and responsive, but endogenous NE is insufficiently produced or released — consistent with ATP-triage-deprioritized adrenergic signaling.
- *Pyridostigmine works → cholinergic signaling ATP-triage-deprioritized.* ACh synthesis (choline acetyltransferase requires acetyl-CoA, which requires ATP for pyruvate dehydrogenase and citrate synthase), vesicular loading (VAChT requires proton gradient, indirectly ATP-dependent), and release. Pyridostigmine increases synaptic ACh by blocking its degradation — it makes whatever ACh IS released last longer. Pyridostigmine response means ACh is being released at some level (the synapse is functional), but the amount is inadequate (consistent with reduced synthesis from ATP shortage). AChE inhibition amplifies the signal without requiring more ATP.
- *Aripiprazole works → dopaminergic signaling ATP-triage-deprioritized.* DA synthesis (tyrosine hydroxylase is BH4- and ATP-dependent), VMAT2 loading (ATP-dependent proton gradient), and DA release are all ATP-expensive. Aripiprazole bypasses all of it — a partial agonist directly activates D2/D3 receptors regardless of endogenous DA levels. Aripiprazole response means the postsynaptic DA system is intact but presynaptic DA production cannot keep up with ATP demand.
- *Guanfacine works → prefrontal noradrenergic signaling ATP-triage-deprioritized.* PFC pyramidal neurons require NE for working memory maintenance through α2A receptor activation → cAMP suppression → HCN channel closure → strengthened synaptic connectivity. Guanfacine directly activates α2A receptors — bypassing the entire LC-NE synthesis and release pathway. Guanfacine response means the PFC circuits are intact and waiting for a signal that ATP shortage prevents the LC from sending.
- *Pitolisant or modafinil works → histaminergic/orexin signaling ATP-triage-deprioritized.* Orexin neurons are among the most metabolically active in the brain — their firing rate is directly proportional to ATP availability. Under energy shortage, orexin neurons reduce firing → reduced wakefulness drive. Pitolisant releases histamine (bypassing orexin), modafinil increases DA (bypassing orexin and histamine). Both provide wakefulness signals that the energy-depleted orexin system cannot generate.

*Diagnostic pattern — the triage fingerprint:*
- *Midodrine + aripiprazole + pyridostigmine all work:* Broad multi-system triage. Adrenergic, dopaminergic, AND cholinergic signaling are all ATP-deprioritized. This is the CNS energy crisis pattern — the brain has cut neurotransmitter production across multiple systems to conserve ATP for vital functions. The drug combination restores all three signaling pathways — but note the metabolic cost (@sec:metabolic-cost): each drug has its own ATP cost, and the combination may exceed the energy budget even though each individual drug produces benefit.
- *Midodrine works alone (aripiprazole and pyridostigmine do not):* Selective adrenergic triage. The ATP shortage is specifically affecting sympathetic NE synthesis — consistent with DBH being ATP-sensitive (DBH converts DA → NE, requiring ascorbate and copper, indirectly ATP-dependent for vesicular pH). DA and ACh systems have sufficient ATP budget; NE system does not. This is the neuropathic POTS pattern — selective sympathetic denervation, not global energy failure.
- *Aripiprazole works alone (midodrine and pyridostigmine do not):* Selective dopaminergic triage. The ATP shortage is specifically affecting DA synthesis — consistent with tyrosine hydroxylase being BH4-dependent and BH4 synthesis being GTP-dependent (GTP is ATP-derived). DA neurons are particularly vulnerable to ATP shortage because they have high baseline firing rates and require continuous BH4 regeneration.
- *None of the above works:* The dysfunction is NOT energetic — it is pharmacological (receptor blockade by autoantibodies, receptor desensitization, or structural receptor loss). The signaling systems have adequate ATP but the receptors cannot respond. This eliminates the energy triage model and directs diagnostic attention to GPCR AAb, channelopathy, or receptor-level pathology.
- *Pacing reduces the number of bypass drugs needed:* If pacing increases the ATP pool (by reducing demand → mitochondrial recovery → more ATP available for the next day) → fewer signaling systems are ATP-deprioritized. The patient who needs midodrine + aripiprazole + pyridostigmine while working full-time may only need midodrine when pacing reduces ATP demand. The reduction in required bypass drugs with pacing quantifies the ATP deficit — if pacing eliminates the need for two of three drugs → the energy deficit was demand-driven and partially reversible. If pacing changes nothing → the energy deficit is production-driven (structural mitochondrial damage) — ATP production is fixed regardless of demand.

*Consequence:* The energy triage model is the only cascade in this chapter that is NOT hypothesis-specific — it applies across all energy-deficit hypotheses (mitochondrial, delivery, substrate). The triage fingerprint (which bypass drugs work) identifies which signaling systems are ATP-depleted in that patient, and pacing's effect on the fingerprint quantifies the degree to which the deficit is demand-driven vs. production-fixed. The most clinically actionable inference: if the patient requires 3 bypass drugs to function, their energy deficit is severe and their PEM budget for additional drug trials is minimal — prioritize low-energy-cost interventions. If pacing eliminates the need for bypass drugs, the treatment is pacing — not pharmacology.
*Origin:* mechanistic-pathway-tracing.
