#import "../../../../../shared/environments.typ": *

#limitation(title: [Ratchet Recovery vs.\ Attractor Escape: What $tau_upright("rec")$ Actually Measures])[
The recovery time constant $tau_upright("rec")(B)$ (Equation @eq:recovery-scaling) describes how rapidly $B(t)$ relaxes toward the current ceiling $B_max(t)$ within inter-event dynamics (Equation @eq:ratchet-interevent). It does _not_ describe escape from the disease attractor itself. The bistability analysis (Chapter @ch:integrated-systems, Section @sec:hysteresis-analysis) treats the entire disease state---including all $B$ values up to $B_max$---as a stable basin sustained by positive feedback among energy depletion, immune dysregulation, ROS, and inflammation. Even after a patient has fully relaxed to $B = B_max$ via slow endogenous repair (potentially years in the floor regime), the system remains within the disease basin. True recovery requires _crossing the separatrix_ into the healthy attractor, which is biophysically distinct from intra-basin relaxation.

Two implications follow.

(1) *Pharmacological recovery is parameter modification, not amplification of endogenous repair.* Effective treatments work by shifting parameter values (raising $alpha_upright("CI")$, lowering $k_upright("exh")$, modifying $K_upright("MC")$, and others) until either the disease attractor shrinks enough that noise-driven escape becomes feasible (Section @sec:stochastic-resonance) or the saddle-node bifurcation reverses and the disease attractor disappears entirely. The ratchet's $tau_upright("rec")$ characterizes intra-basin relaxation under fixed parameters, not this parameter-modification trajectory.

(2) *The 5% spontaneous-recovery rate refers to near-separatrix patients only.* The Kramers escape rate (Equation @eq:kramers-rate) depends exponentially on attractor depth. Patients deep in the disease attractor---particularly those in the floor regime ($B lt.eq B_upright("collapse")$)---have negligible spontaneous escape probability regardless of elapsed time. The reported aggregate recovery statistics @Brurberg2014 are dominated by patients near the separatrix where modest perturbations or supportive care can tip the trajectory across.

Clinical implication: long observation of an extremely severe patient with no functional change does not indicate that endogenous repair is exhausted or that a permanent floor has been reached. It is the expected behavior of a system trapped in a deep attractor under unchanged parameters; meaningful change requires parameter modification (pharmacological intervention) or a perturbation large enough to cross the structural hysteresis gap (Equation @eq:hysteresis-width).
]
