#import "../../../../shared/environments.typ": *

#limitation(title: [The Psychologization-Harm Evidence Base Is Cross-Sectional])[
The psychologization harm framework and much of the supporting evidence rest on cross-sectional designs (Büchner 2025, Pantelic 2022, Clutterbuck 2024) and qualitative studies (Ireson 2022, Hammer 2025). These establish association but not causation. The temporal direction could be partially reversed: patients with more severe ME/CFS see more clinicians, have more "medically unexplained" symptoms, and thereby accumulate more psychologization encounters — making psychologization exposure partially a marker of disease severity rather than a cause of deterioration. No prospective cohort study has measured psychologization exposure at baseline and tracked functional decline over time while controlling for objectively measured severity (CPET, actigraphy, biomarker panels).

Note on evidence standards: the patient survey evidence cited for harm (Eckey 2025, Hammer 2025, Büchner 2025) shares methodological limitations with patient-reported improvement evidence that this paper critiques when used to support CBT/GET — both are unblinded, subjective, retrospective self-reports. The same evidence-quality standards must apply to all therapeutic claims regardless of direction. The signal strength differs (harm reports are consistent across four countries, multiple survey instruments, and produce concordant rates of 50–75% worsening, whereas improvement reports in CBT/GET trials are contradicted by objective measures), but the evidence type is the same. This does not invalidate the harm claims — it qualifies their precision.

The Schomerus essay itself is a position paper with 37 citations, not a systematic review — it synthesizes existing evidence without PRISMA methodology, risk-of-bias assessment, or explicit inclusion criteria. Its primary value is framing and normative argument, not new empirical data.
] <lim:psychologization-cross-sectional>

The most important test would be a prospective cohort study measuring psychologization exposure at diagnosis and tracking functional decline over 3–5 years with comprehensive confounder control. This would distinguish the Schomerus hypothesis (psychologization causes worsening via pacing disruption, HPA acceleration, and healthcare avoidance) from the null hypothesis (psychologization is epiphenomenal to severity). Until such a study exists, the evidence base supports the conclusion that psychologization is harmful — but not with the causal certainty it might seem to provide.
