#import "../../../../../shared/environments.typ": *

#open-question(title: [Synaptic-Density PET as a Presynaptic Proxy for Synaptic Structure])[
If ME/CFS genetic risk localizes to synaptic assembly and scaffolding, synaptic density itself may be measurably altered in the disease — a testable prediction for in-vivo synaptic-density imaging. Positron-emission tomography using radiotracers for the synaptic vesicle glycoprotein 2A (SV2A) — [11C]-UCB-J and [18F]-SynVesT-1 — is established as a research tool in neuropsychiatric disorders, where SV2A signal is reduced in schizophrenia cortex @Onwordi2020SV2Aschizophrenia and couples to glutamatergic markers in healthy volunteers @Onwordi2021SV2Aglutamate; the method and its specificity limitations are reviewed in @Asch2024SV2Adepression and @Serrano2022synapticdensity. A critical design caveat is compartment specificity: SV2A is a *presynaptic* vesicle glycoprotein, whereas the SynGO genetic signal localizes to *postsynaptic* assembly and scaffolding (@spec:syngo-postsynaptic-assembly). Because pre- and postsynaptic structures co-assemble, SV2A signal may still covary with total synapse number and remain informative as a presynaptic proxy, but a *null* SV2A result would not falsify a postsynaptic-assembly deficit. An SV2A-PET study in ME/CFS — e.g., comparing across striatum, hypothalamus, and cortex against healthy controls — should therefore be designed compartment-aware (paired with a glutamatergic-neurochemistry readout such as MRS glutamate, which measures pooled synaptic glutamate, @Thapaliya2024glutamateMRS) rather than treated as a stand-alone test of the postsynaptic hypothesis.

(Certainty: N/A — this is an open research question / proposed tool, not an established finding. Translation gap: SV2A-PET evidence is from schizophrenia/healthy-volunteer and methodological cohorts, not ME/CFS. Severity applicability: unknown.)

*Falsifiable prediction:* An in-vivo [11C]-UCB-J or [18F]-SynVesT-1 PET study, ideally paired with a postsynaptic-sensitive readout, will show a measurable difference in SV2A binding (synaptic density) in one or more brain regions in ME/CFS versus matched controls. Falsified if synaptic density is indistinguishable from controls across all regions examined; a null SV2A result alone, however, does not rule out a postsynaptic-assembly deficit.

*Consequence:* A positive SV2A-PET result would give ME/CFS a direct, quantitative measure of synaptic density in the living brain — strengthening the claim that ME/CFS involves altered synaptic structure — and could serve as an objective severity or treatment-response biomarker. But because the tracer is presynaptic while the genetic signal is postsynaptic, a negative scan must not be read as ruling out the synaptic hypothesis. It is early-stage: SV2A-PET is an established method in other disorders but untested in ME/CFS.
] <oq:syngo-synaptic-density-pet>
