#import "../../../../../shared/environments.typ": *

#open-question(title: [Are Innate-Like T Cells Activated or Depleted in Post-Infectious ME/CFS?])[
BioMapAI finds heightened inflammatory activity in MAIT and gamma-delta T cells secreting IFN-gamma and granzyme A in ME/CFS @Xiong2025BioMapAI. In contrast, single-cell RNA-sequencing of Long COVID with ME/CFS finds galectin-9-associated depletion of gamma-delta and MAIT cells, alongside monocyte and NK remodeling and T-cell exhaustion @Shahbaz2026single-cell-immune. Cell-type frequency correlates with symptom severity in related cytotoxic-T-cell data @Lee2025TcellActivation. These observations need not be contradictory at all — they may measure different dimensions. BioMapAI's signal is a *per-cell functional* readout (IFN-gamma and granzyme A secretion); Shahbaz's is a *frequency/count* readout (number of MAIT and gamma-delta cells). A frequency-based count is blind to per-cell hyperactivation: a T-cell population that is small in number but individually hyperactivated would read as "depleted" on a count yet "activated" on function, so both findings could be simultaneously true.

If they are in genuine tension, the simplest reading is that the two studies are not tracking one within-disease timecourse but comparing different things: different populations (ME/CFS broadly vs Long COVID with ME/CFS), different measurement platforms (immune-profiling inside a multi-omics model vs single-cell RNA frequency/state), and likely different disease durations. A more complex, unproven reconciliation is the "dynamic trajectory" — an innately-reactive T-cell population hyperactivated early or during flares, then driven toward exhaustion and depletion over the chronic course by sustained antigen exposure. This ordered sequence is one candidate, not an established account; neither study has serial within-subject data to confirm it.

The unresolved question is whether the correct reading — and with it any therapeutic implication — is activation, depletion, an ordered sequence, or simply two different cell-kinds being counted and measured differently. An intervention modulating T-cell activation/exhaustion balance would depend on which state dominates, but any such decision is premature and requires prospective interventional testing.

Certainty: n/a — this is an open research question posed by two bodies of evidence. Severity applicability: unknown — neither study stratifies by severity; both sample ambulatory post-infectious cohorts.

*Consequence:* Only serial, within-cohort measurement that tracks MAIT and gamma-delta T cells over disease duration *and* captures both cell frequency and per-cell functional output can resolve this. Until then, "hyperactive innate-like T cells" and "exhausted/depleted innate-like T cells" remain possibly-orthogonal descriptions — pointing to opposite therapeutic strategies if they are alternatives, and to a combined intervention problem if they are sequential.
] <oq:mait-gamadelta-activation-vs-depletion>
