#import "../../../../../shared/environments.typ": *

#speculation(title: [SleepFM as ME/CFS Decoupling Quantification Tool])[
SleepFM or an equivalent multimodal sleep foundation model, applied to existing ME/CFS polysomnography datasets, could quantify the degree of cross-modal decoupling in patients versus matched controls. Because the model was trained on 65,000 individuals without ME/CFS-specific labels, its learned representation of "normal" physiological coupling provides a normative reference against which ME/CFS decoupling can be measured. Key predictions: (a) ME/CFS patients will show significantly higher multimodal reconstruction error (indicating greater cross-modal decoupling) than healthy controls. (b) Decoupling magnitude will correlate with symptom severity (fatigue, unrefreshing sleep, cognitive dysfunction). (c) Specific decoupling patterns may distinguish ME/CFS subtypes (sleep-predominant, brain fog-predominant, PEM-predominant --- Section @sec:ch15-phenotypes). (d) Post-exertional worsening on Day 2 post-CPET will be reflected in increased decoupling magnitude in the intervening night's sleep data. (e) Decoupling indices may respond to treatment more sensitively than sleep staging metrics, providing a treatment-response biomarker.

*Certainty: 0.25.* The model architecture is validated (Nature Medicine, $n=65,000$), but SleepFM has not been applied to ME/CFS data; the predictions above are mechanistically grounded but entirely untested. The existence of large-scale PSG datasets at established ME/CFS research centres (Stanford Sleep Medicine Center cohort, Bateman Horne Center) makes this a feasible near-term study. Cross-reference to @sec:ch25b-sleepfm-proposed for a detailed study protocol.

*Limitations:* SleepFM was trained on clinical PSG populations (patients referred for sleep assessment), not general-population screening, which may introduce referral bias. PSG hardware, electrode montages, and scoring conventions vary between centres, potentially limiting transferability. The model's original training data and weights are not publicly available as of 2026, and the interpretability of its learned features is limited by the black-box nature of foundation models. No ME/CFS-specific data exist.
] <spec:ch15-sleepfm-decoupling>
