#import "../../../../shared/environments.typ": *

==== Step E2: PDH phosphorylation — enzymatic block (the enzyme level)

*Probes for restoring PDH activity:*
- *Dichloroacetate (DCA, 12.5--25 mg/kg/day, investigational in ME/CFS):* PDK inhibitor — directly blocks the kinase that phosphorylates and inactivates PDH. DCA restores PDH activity regardless of upstream cytokine drive. If DCA dramatically reduces lactate and improves exercise tolerance → PDH phosphorylation IS the rate-limiting metabolic step. DCA is the highest-specificity probe for PDH in this chapter. CAUTION: DCA causes reversible peripheral neuropathy at cumulative doses >30 g — limit trial duration; monitor nerve conduction. DCA is not approved for ME/CFS — requires off-label prescription or clinical trial access.
- *Thiamine (B1, 100--900 mg/day, IV or oral):* Essential cofactor for PDH (thiamine pyrophosphate is the prosthetic group of PDH E1). If thiamine works → PDH cofactor deficiency. Simple, reversible, nutritional — the most accessible PDH probe. Distinguish: thiamine deficiency vs. PDK-driven phosphorylation. If LDN does NOT reduce lactate but thiamine DOES → PDH inhibition is from cofactor deficiency, not PDK-mediated phosphorylation. If thiamine works and LDN works → dual mechanism: inflammatory PDK activation + thiamine deficiency (common in SIBO, gut dysbiosis).
- *Alpha-lipoic acid (300--600 mg BID):* Antioxidant that also serves as a PDH cofactor and reduces PDK expression. If ALA works → oxidative stress drives PDK expression, and antioxidant + cofactor support restores PDH.
- *Magnesium (400--800 mg, IV or oral):* Mg²⁺ is a PDH phosphatase cofactor — PDH phosphatase requires Mg²⁺ to dephosphorylate and activate PDH. If IV magnesium improves exercise tolerance → Mg²⁺ deficiency prevented PDH dephosphorylation. The PDH enzyme is phosphorylated (PDK active) AND cannot be dephosphorylated (PDH phosphatase Mg²⁺-deficient).
- *Niacin/NR (NAD⁺ precursors):* NAD⁺ is a substrate for PDH (converts NAD⁺ → NADH). If PDH activity is restored (by thiamine, DCA, or Mg²⁺) but symptoms do NOT improve → NAD⁺ may be rate-limiting for PDH throughput. Add nicotinamide riboside (NR) to provide NAD⁺ substrate. If NR + thiamine works where thiamine alone does not → dual cofactor deficiency (thiamine + NAD⁺).

*Distinguishing DCA vs. thiamine response:* DCA = PDK inhibition (restores PDH regardless of cofactor status). Thiamine = cofactor repletion (restores PDH only if cofactor was deficient). DCA+ but thiamine null → PDK is the dominant inhibitor, cofactor status is adequate. Thiamine+ but DCA null (impossible — DCA should always work if PDH phosphorylation is the block; a null DCA response suggests the PDH complex is structurally damaged or absent, not just phosphorylated). Both null → PDH is not the metabolic bottleneck — the ETC downstream of acetyl-CoA, the TCA cycle itself, or substrate delivery is rate-limiting.
