#import "../../../../../shared/environments.typ": *

#speculation(title: [FADS1/2 Polymorphisms and SPM Precursor Conversion in ME/CFS])[
*Certainty: 0.35.* Fatty acid desaturase genes FADS1 and FADS2 encode Delta-5 and Delta-6 desaturases, the rate-limiting enzymes for long-chain polyunsaturated fatty acid (LC-PUFA) synthesis from dietary precursors. Common FADS cluster polymorphisms (rs174537, rs174546, rs174583) determine inter-individual variation in LC-PUFA levels, including arachidonic acid (AA), eicosapentaenoic acid (EPA), and docosahexaenoic acid (DHA) @Schaeffer2006FADS @Ameur2012FADS. Since AA, EPA and DHA are the substrates for SPM biosynthesis (resolvins, maresins, protectins) @Serhan2022SPMResolvinLongCOVID, FADS variants that reduce LC-PUFA levels may impair the resolution phase of inflammation in ME/CFS by limiting SPM precursor availability. This is consistent with the emerging picture of resolution failure in post-viral syndromes: Engert et al. (2026) demonstrated that sleep disturbance dysregulates SPM biosynthesis in Long COVID @Engert2026SPMSleepLongCOVID, and Rauf et al. (2026) characterized PASC as a disorder of impaired innate immune resolution @Rauf2026PASCResolutionFailure. This connects to the gut-microbiome lipid mediator axis (Speculation @spec:gut-microbiome-spm-deficiency, Chapter @ch:gut-microbiome): patients with both low-genetic SPM-precursor capacity (unfavourable FADS variants) AND low bacterial SPM-precursor supply (dysbiosis) would face a compounded deficit.

*Mechanism.* The minor (low-activity) allele at rs174537 (G allele, frequency ~30% in Europeans) is associated with: (1) 15–25% lower AA and EPA in plasma and red blood cell membranes; (2) reduced conversion of linoleic acid (LA) to AA and alpha-linolenic acid (ALA) to EPA/DHA; (3) altered AA/EPA ratio affecting the balance of pro-inflammatory vs pro-resolving mediator production. In ME/CFS, low EPA and DHA availability would reduce resolvin E1, D1 and protectin D1 synthesis, impairing neutrophil clearance, macrophage efferocytosis, and inflammatory resolution. The resulting failure-to-resolve could shift the inflammatory trajectory from self-limited to chronic.

*ME/CFS context.* If FADS polymorphisms contribute to SPM insufficiency in ME/CFS, they would predict: (a) differential response to omega-3 supplementation (high-activity allele carriers will benefit more because they have the enzymatic capacity to convert EPA/DHA to SPMs); (b) interaction with gut microbiome composition (dysbiosis-reduced bacterial SPM-precursor supply compounds low host conversion capacity); (c) enrichment of low-activity FADS haplotypes in the ME/CFS population, particularly in patients with prominent non-resolving inflammatory features.

*Falsifiable predictions.* (1) ME/CFS patients carrying the low-activity FADS haplotype (rs174537 GG) will show lower plasma AA, EPA, and DHA, and correspondingly lower SPM levels (resolvin D1, resolvin E1) compared to high-activity (TT) carriers. (2) Omega-3 supplementation (EPA 2 g + DHA 1 g/day, 12 weeks) will increase plasma SPM levels and reduce inflammatory markers (hs-CRP, IL-6) preferentially in FADS high-activity carriers. (3) ME/CFS patients with both unfavourable FADS genotype AND low gut Faecalibacterium abundance will show the lowest SPM levels and highest PEM severity — a gene-microbiome interaction. (4) FADS genotype will not affect NK cytotoxicity or complement activation (SPM-independent pathways), providing a specificity control.

*Limitations.* FADS polymorphisms have not been studied in any ME/CFS genetic cohort. The SPM resolution model assumes that SPM availability is rate-limiting for inflammatory resolution in ME/CFS — this has not been demonstrated. Omega-3 supplementation has been tested in ME/CFS with mixed results (Chapter @ch:supplements), but never stratified by FADS genotype or with SPM endpoints. The predicted gene-microbiome interaction requires large sample sizes (n > 500) for adequate statistical power.
] <spec:fads-polymorphisms-spm>
