#import "../../../../shared/environments.typ": finding

=== Low-Dose Naltrexone (LDN) <sec:low-dose-naltrexone-ldn>

LDN blocks TLR4 receptors on microglia (reducing neuroinflammation), restores TRPM3 calcium channel function in vitro, and triggers compensatory endorphin upregulation. Does not increase metabolic rate — can be tried even in severe patients.

#block[==== Why Higher Dose Is Not Necessarily Better — The Hormetic Dose-Response Window] <ldn-hormetic-window>

*Origin: Kevin Lee (personal communication, July 2026) — the clinical observation that even if LDN works via TLR4/TRPM3, this does not explain why higher dose is not always better and why some patients do better at lower doses.*

If LDN were a simple receptor-level drug (more TLR4 blockade = more benefit), the therapeutic logic would push toward 4.5 mg for everyone — maximal target engagement within the LDN window. This is not what is observed clinically. Some patients do better at 0.5--1.5 mg than at 3.0--4.5 mg, and dose escalation can extinguish a response that was present at a lower dose. (Severity applicability: all — optimal dose is mechanism-dependent, not severity-dependent; start lower in severe/very severe patients for safety, but the dose-response curve shape is predicted to be independent of severity.) @Dara2023 @BruunPlesner2020LDN @Calabrese2021Nrf2 @Toljan2018

LDN's dose-response is better understood through three superimposed mechanisms with different concentration optima:

- *TLR4 hormetic window (low-dose priming):* Partial TLR4 blockade at 0.5--1.5 mg may trigger compensatory anti-inflammatory priming via Nrf2-mediated transcriptional upregulation — a hormetic response in which the mild stress of receptor blockade activates the cell's own anti-inflammatory programmes (M1→M2 phenotype shift, metabolic switch from glycolysis to OXPHOS in microglia). At higher doses (3.0--4.5 mg), TLR4 blockade removes the basal TLR4 tone needed to sustain this compensatory response — the hormetic benefit collapses, not because too little receptor is blocked, but because too much is. @Kucic2021LDNmicroglia @Calabrese2021Nrf2 @Kwilasz2021NTXmicroglia

- *Opioid receptor compensatory upregulation (mid-dose plateau):* Brief overnight opioid blockade triggers compensatory endorphin production — this mechanism has an individual ceiling set by endogenous opioid precursor expression. Beyond that ceiling, increasing LDN dose adds nothing to endorphin tone. @Boyadjieva2004 @Kreek1992

- *Why the overnight blockade window matters — GPCR resensitization kinetics:* LDN's 4–6 hour blockade window (bedtime dosing, daytime washout) functions as a de facto pulsed regimen. This is not a convenience convention — it tracks the conserved GPCR resensitization cycle: activation → desensitization → internalization → endosomal dephosphorylation → recycling to the membrane surface in a drug-naive state @CostaNeto2025GPCRTachyphylaxis @Gupta2018GPCRResensitization @Kliewer2017GPCRDephosph. If LDN were taken continuously (multiple daily doses), the opioid and TLR4 receptors would remain in the internalized, desensitized pool — the resensitization interval that the 16–20 hour daytime washout provides would be filled, and the compensatory endorphin upregulation that requires a drug-free resensitized receptor surface would not occur. LDN's therapeutic effect depends on the *recovery* from blockade as much as on the blockade itself — a time-dependent dimension that single-mechanism "LDN blocks TLR4" models do not capture. This principle generalizes: any drug whose therapeutic mechanism depends on a compensatory response triggered by transient receptor perturbation will lose effectiveness with continuous dosing. The 4–6 hour blockade window is empirical (it is what clinicians use), but the GPCR resensitization rationale for *why* the window matters is inferential — no study has compared pulsed vs continuous LDN dosing in any condition. @Hodding1980DrugWithdrawal (withdrawal risk counterpart: the same drug-free interval that enables resensitization could trigger withdrawal if opioid dependence has developed)

- *Dose-window overlap and individual variation:* Each of LDN's four targets (TLR4, TRPM3, opioid receptors, orexin disinhibition) has a distinct concentration-response curve. Some patients' optimal dose is determined by the TRPM3 window (closer to 3.0--4.5 mg), others by the TLR4 hormetic window (closer to 0.5--1.5 mg), and still others by endorphin upregulation kinetics. The clinical observation that "the right dose varies" is not noise — it is the predictable consequence of a multi-target drug with non-overlapping dose optima. @Toljan2018 @Dara2023

*Falsifiable prediction:* A prospective within-range dose-response trial (0.5, 1.5, 3.0, 4.5 mg, n≥30 per arm, crossover, 8 weeks per dose) in ME/CFS should reveal non-monotonic individual response curves — most patients will not show monotonic improvement across the full dose range. Falsified if the group-average dose-response is strictly monotonic AND individual curves do not show inversions. Currently contradicted by zero data: no within-range dose-response trial has been conducted. @BruunPlesner2020LDN (ED50=3.88 mg in fibromyalgia with wide interindividual variation)

*Certainty: 0.30 — no within-range dose-response trial exists in any condition; the hormetic model is mechanistically grounded (@Calabrese2021Nrf2 cert 0.72, @Calabrese2021UltraLow cert 0.65) but untested for LDN specifically. Evidence is from: single-dose fibromyalgia trial (@BruunPlesner2020LDN, ED50 estimation), microglial M1→M2 dose-dependence in vitro (@Kucic2021LDNmicroglia), opioid receptor feedback models (@Boyadjieva2004, @Kreek1992), and review-level biphasic characterization (@Dara2023, @Toljan2018). The absence of direct evidence is itself informative — no one has asked the question in a design that could answer it. The LIFT trial (@LIFT2025protocol) uses a single LDN dose; it cannot address this.*

*Consequence:* For clinicians and patients, the hormetic model provides a mechanistic rationale for dose-finding patience: start at 0.5 mg, titrate slowly, and recognise that "more" is not always "better." If a lower dose works better than a higher dose, this is not a failed titration — it identifies that the patient's therapeutic mechanism is the TLR4 hormetic window or endorphin ceiling, not TRPM3 restoration. For researchers, the absence of a within-range dose-response study is the single largest evidence gap in the LDN literature — a four-arm crossover dose-response trial in ME/CFS would cost an estimated $200,000--$400,000 and answer a question affecting every LDN prescription written in any chronic illness.

==== If LDN works


#finding(claim: [Neuroinflammation was present.], explanation: [LDN blocked TLR4 → microglia calmed → inflammatory cytokines (IL-1β, TNF-α) decreased → symptoms improved.], certainty: [Low to Medium — LDN's TLR4 antagonism is established in vitro @Younger2013; neuroinflammation is documented in ME/CFS (@sec:neuroinflammation). But no direct evidence that clinical benefit is TLR4-mediated.], dntu: [what is causing the neuroinflammation — autoantibodies (@sec:root-gpcr), viral components, mitochondrial debris, or vagal stress signals.], action: [anti-neuroinflammatory strategies become relevant.], level: [Partial root cause — LDN calms microglia without removing the trigger.])

#finding(claim: [TRPM3 ion channel dysfunction was present.], explanation: [LDN restores TRPM3-mediated calcium flux in NK cells in vitro @Cabanas2018trpm3. TRPM3 is essential for immune killing, neurotransmitter release, and vascular tone. TRPM3 dysfunction is the most replicated ion channel finding in ME/CFS @Cabanas2021.], certainty: [Low to Medium — the central link (LDN restores TRPM3 in living humans, producing clinical benefit) has never been demonstrated.], dntu: [whether TRPM3 dysfunction is primary or secondary to GPCR autoantibody-driven PIP2 depletion (@hyp:ch14h-pip2-convergence).], action: [TRPM3-targeting strategies (pregnenolone sulfate, PIP2 maintenance) become relevant.], level: [Potential root cause — TRPM3 is a trigger-capable root cause (@sec:root-trpm3); LDN partially restores its function.])

#finding(claim: [Orexin suppression may have been relieved.], explanation: [LDN reduces hypothalamic microglial activation → less PGE2/TNF-α suppressing orexin neurons → increased orexin → improved wakefulness and cognition. Orexin falls into an intermediate "gray zone" in ME/CFS CSF (@hyp:ch15-orexin-suppression).], certainty: [Low — no study has measured orexin before/after LDN in ME/CFS.], level: [Symptom management.])

#finding(claim: [Endorphin-mediated pain relief and mood improvement.], explanation: [Brief overnight opioid blockade triggers compensatory endorphin upregulation.], certainty: [Medium for pain, Low for other symptoms.], level: [Symptom management.])

==== Dose-Dependent Differential Inference — The Dose-Response Curve Shape Is Diagnostic

LDN's four mechanisms have non-overlapping dose optima (@sec:hormetic-dose-response): TLR4/Nrf2 hormetic priming peaks at 0.5--1.5 mg, opioid compensatory upregulation plateaus at 1.5--3.0 mg, TRPM3 restoration may require 3.0--4.5 mg, and orexin disinhibition tracks the TLR4 dose-response. Response *at which dose* therefore discriminates which mechanism is rate-limiting — information a single fixed-dose trial cannot provide.

#finding(claim: [Benefit at 0.5--1.5 mg that is lost at 3.0--4.5 mg → TLR4/Nrf2 hormetic mechanism dominant.], explanation: [Partial TLR4 blockade primes Nrf2-mediated M1→M2 microglial shift; higher doses remove the basal TLR4 tone sustaining the priming signal and the benefit collapses @Calabrese2021Nrf2 @Kucic2021LDNmicroglia. Window width estimates Nrf2 transcriptional reserve — benefit lost by 1.5 mg = narrow reserve; benefit persisting to 3.0 mg = broad reserve.], certainty: [Low — hormetic model mechanistically grounded but no within-range dose-response trial exists.], dntu: [what is activating TLR4 (autoantibodies, viral components, mitochondrial debris); whether Nrf2 reserve is itself impaired.], action: [maintain the low dose — escalation is counterproductive; response to other Nrf2 activators (sulforaphane, lithium, melatonin) is predicted by window width.], level: [Partial root cause — identifies neuroinflammation as TLR4-driven and microglia as Nrf2-responsive.])

#finding(claim: [Benefit rising to 1.5--3.0 mg, plateauing, and preserved at 4.5 mg → opioid compensatory mechanism dominant.], explanation: [Compensatory endorphin upregulation has a ceiling set by POMC/proenkephalin expression @Boyadjieva2004 @Kreek1992. Plateau without high-dose worsening excludes TLR4 hormetic dominance, which would worsen at 4.5 mg.], certainty: [Low to Medium — endorphin rebound documented; ceiling inference untested.], dntu: [whether pain/mood benefit masks ongoing disease progression.], action: [titrate to the plateau point and no higher; treat the underlying pain driver directly.], level: [Symptom management.])

#finding(claim: [Benefit only at 3.0--4.5 mg with no low-dose effect → TRPM3 or orexin mechanism dominant (tentative).], explanation: [TRPM3 restoration may require higher concentrations; orexin disinhibition tracks hypothalamic TLR4 dose-response, which may differ from cortical populations. No TRPM3 dose-response data exist — all in vitro work used a single concentration @Cabanas2018trpm3.], certainty: [Low — the TRPM3 dose-response is the single largest evidence gap in the LDN literature.], dntu: [which of TRPM3 vs. orexin is responsible — wakefulness/cognition-dominant benefit suggests orexin; multi-system benefit (immune, vascular, neurotransmitter) suggests TRPM3.], action: [TRPM3 function measurement when clinically available; pregnenolone sulfate as adjunct.], level: [Potential root cause if TRPM3 (@sec:root-trpm3); symptom management if orexin.])

#finding(claim: [Biphasic (M-shaped) response — benefit at 0.5 mg, lost at 1.5 mg, returning at 3.0--4.5 mg → two non-overlapping optima engaged.], explanation: [TLR4/Nrf2 hormetic window at low dose plus a second mechanism (likely TRPM3) at higher dose. The patient has two rate-limiting mechanisms addressable by the same drug at different doses.], certainty: [Low — predicted by the multi-target model; never tested.], dntu: [whether combining low-dose LDN with a second TRPM3-targeting agent captures both optima simultaneously.], action: [choose the dose targeting the dominant symptom domain; consider mechanism-specific adjuncts rather than a compromise dose.], level: [Mixed — one mechanism may be root-cause-level (TRPM3), the other partial (TLR4).])

#finding(claim: [LDN full-range tested (0.5--4.5 mg), ceiling signal only, no therapeutic window at any dose → none of LDN's four mechanisms is rate-limiting, and the microglial activation pathway is NOT TLR4-driven.], explanation: [The patient has probed the entire dose range and each band returned a specific null: (1) the top of the TLR4 hormetic band (3.0--4.5 mg) produced systemic sickness — confirming the TLR4 hormetic ceiling was crossed and Nrf2 reserve is narrow; (2) the upper range below the ceiling (3.0--4.0 mg) produced no benefit — excluding TRPM3/orexin as therapeutic mechanisms; (3) lower doses (0.5--1.5 mg, 1.5--3.0 mg) were either not trialled or produced no therapeutic signal despite adequate duration — excluding TLR4/Nrf2 hormetic priming and endorphin compensation. The combination of ceiling signal (sickness at 4.5 mg) + therapeutic null across all bands means: the microglial population IS present and TLR4-responsive (the ceiling proves receptor engagement), but TLR4 blockade does not produce a therapeutic window — the anti-inflammatory benefit never appears before the hormetic collapse. This is distinguishable from pure non-response (no signal at any dose), which could reflect insufficient trial duration or drug access failure rather than true mechanism absence. A ceiling signal without a therapeutic window is a stronger exclusion than simple null response.], certainty: [Low — no prospective dose-response trial validates the ceiling-only pattern as a mechanism exclusion. The inference that hormetic crossing without prior benefit excludes TLR4 as a therapeutic target is mechanistically coherent but unvalidated.], dntu: [whether lower doses (0.5--3.0 mg) were actually trialled for adequate duration (>=4 weeks each) — if not, the exclusion of TLR4/Nrf2 and endorphin mechanisms is premature. The ceiling signal at 4.5 mg only proves receptor engagement; it does not prove the lower bands were adequately tested.], action: [If lower bands were not adequately tested: trial 0.5 mg × 4 weeks, then 1.5 mg × 4 weeks before concluding TLR4/Nrf2 non-involvement. If all bands were adequately tested: the therapeutic target is NOT TLR4. Probe D2-mediated microglial activation (LDA), mast-cell→microglial pathway (ketotifen, cromolyn), or non-microglial mechanisms entirely. The ceiling signal + null therapeutic window strongly predicts LDA response — the same microglial population that LDN's TLR4 blockade engaged but could not produce benefit from is likely D2-responsive.], level: [Diagnostic — the ceiling-only pattern is a specific null that narrows the differential to non-TLR4 microglial pathways.])

==== What a positive response does NOT reveal

Which of the four mechanisms is responsible *at a single fixed dose* (LDN targets all simultaneously) — however, the dose-response curve shape discriminates: benefit lost on escalation implicates the TLR4/Nrf2 hormetic window; plateau without loss implicates opioid compensation; high-dose-only benefit implicates TRPM3 or orexin (see dose-dependent differential inference above). Whether response is pharmacological or placebo (no ME/CFS-specific RCT vs. placebo); the upstream cause of the dysfunction.

==== If LDN does NOT work
- Neuroinflammation may not be dominant — or LDN may fail to reach brain microglia (BBB permeability, pharmacokinetics).
- TRPM3 dysfunction may be absent or not LDN-responsive — or LDN may restore NK cell TRPM3 without affecting neuronal/vascular TRPM3.
- Dose or duration insufficient — no ME/CFS-specific dose-response studies exist. *The failure may be a dose too high, not too low:* if the therapeutic mechanism is the TLR4/Nrf2 hormetic window (0.5--1.5 mg), a trial conducted only at 3.0--4.5 mg sits above the therapeutic window and guarantees apparent non-response even in a true responder (@sec:hormetic-dose-response). Non-response cannot be concluded unless the low-dose window has also been tested.
- LDN may simply not work better than placebo in ME/CFS. No large RCT exists. If LDN = placebo, every inference above collapses.
- Paradoxical reactors worsen on LDN (@sec:paradoxical-reactor) — their adverse response is itself diagnostic.
- *Critical caveat for LDN non-response with subsequent LDA response:* TLR4 antagonism and D2 partial agonism are complementary targets on the same microglial population. LDN non-response does not mean neuroinflammation is absent — it may mean TLR4 is not the rate-limiting input; D2 agonism can still suppress microglial cytokine output through a different signalling pathway. If LDA works dramatically after LDN non-response, this is evidence FOR microglial involvement, not against it.

==== Side Effects per Dose Zone — What Side Effects at Each Dose Reveal

Side effects are not uniform across doses — they track the mechanism engaged at that concentration. A side effect at one dose and not another is dose-dependent diagnostic information, not random intolerance.

*Systemic sickness (malaise, flu-like, nausea) appearing at a specific dose and absent below it:*

This is a within-range hormetic crossing. LDN's TLR4 blockade at low doses (0.5--1.5 mg) triggers Nrf2-mediated M1→M2 microglial shift — the hormetic anti-inflammatory programme. At higher doses, TLR4 blockade removes the basal TLR4 tone that sustains this priming. When the threshold is crossed, the M2 programme collapses → microglia revert to M1 → cytokine surge (IL-1β, TNF-α) → systemic sickness. The dose at which sickness appears identifies the patient's hormetic ceiling, which is also the threshold of their Nrf2 transcriptional reserve.

#finding(claim: [Sickness at 3.0--4.5 mg, absent at ≤2.5 mg → TLR4/Nrf2 hormetic window dominant, narrow reserve.], explanation: [The patient crosses the TLR4 blockade threshold between their tolerated dose and the sickness dose — basal TLR4 tone falls below what is needed to sustain Nrf2-mediated M2 priming. The microglial anti-inflammatory programme collapses and systemic cytokine release produces flu-like symptoms. This is exactly the pattern the hormetic model predicts: benefit is lost when blockade crosses the threshold, and loss presents as active sickness, not just neutral return-to-baseline.], certainty: [Low to Medium — mechanistically grounded in the hormetic TLR4/Nrf2 model @Calabrese2021Nrf2 @Kucic2021LDNmicroglia but no clinical study has measured microglial cytokines during LDN dose escalation. Patient self-report of dose-specific sickness is the only available signal.], dntu: [what is driving TLR4 activation — the trigger that loads the TLR4 signalling pathway and makes microglial M1 the default state; whether Nrf2 reserve is intrinsically impaired or merely narrow against a strong TLR4 signal.], action: [stay at or below the highest tolerated dose — escalation past the ceiling is counterproductive and actively harmful. The inversion point is the diagnostic signal: the dose just below sickness identifies the patient's therapeutic ceiling. Narrow window → Nrf2 reserve limited; predict narrow windows for other Nrf2 activators (sulforaphane, lithium, melatonin). Broad window (sickness only at 4.5 mg) → Nrf2 reserve adequate but TLR4 signal strong — anti-inflammatory adjuncts (PEA, luteolin) may widen the window.], level: [Partial root cause — identifies Nrf2 reserve as the limiting factor for anti-inflammatory benefit.])

*Dose-specific nausea without systemic sickness — gut TLR4 blockade:*

#finding(claim: [GI-predominant nausea at a specific dose → gut enteric TLR4 blockade is the dominant local effect, not CNS microglial blockade.], explanation: [Enteric glial cells and enteric neurons express TLR4. At a dose that suppresses gut TLR4 without crossing the CNS hormetic threshold → local GI effects (nausea, altered motility, gut discomfort) without systemic cytokine surge. This is distinct from CNS-mediated systemic sickness — the gut is the primary site of TLR4 antagonism at this dose in this patient, either because of first-pass metabolism concentrating naltrexone in the gut wall, or because gut TLR4 tone is higher than CNS.], certainty: [Low — enteric TLR4 blockade by LDN has not been studied in humans. Inference from gut-brain axis pharmacology.], dntu: [whether gut permeability (elevated LPS) is driving gut TLR4 activation; whether CNS benefit occurs at a different dose.], action: [split the dose — bedtime CNS-targeted dose + morning gut-targeted dose at the tolerated level; or use compounded transdermal LDN to bypass gut first-pass. If nausea persists on transdermal → CNS TLR4 threshold crossed, not gut-localized.], level: [Symptom management.])

*Sedation at low dose (0.5--1.5 mg):*

#finding(claim: [Sedation at initiation → orexin system critically low.], explanation: [Opioid receptor blockade suppresses orexin neurons that are already deficient — consistent with the orexin gray-zone hypothesis (@hyp:ch15-orexin-suppression). Sedation typically resolves as compensatory endorphin upregulation occurs over 2--4 weeks. Persistent sedation → orexin deficit is structural, not opioid-suppressed.], certainty: [Medium for orexin mechanism — orexin's role in LDN sedation is inferred; no study has measured orexin during LDN initiation.], dntu: [whether sedation will resolve with continued dosing; whether other orexin-suppressing drugs (antihistamines, benzodiazepines) are being taken concurrently.], action: [start at 0.25 mg if sedation at 0.5 mg; if sedation persists at 0.25 mg → LDN may not be tolerated. If sedation resolves after 4 weeks → endorphin upregulation has compensated; this confirms functional orexin reserve.], level: [Symptom management — identifies orexin status but does not treat it.])

*Vivid dreams / nightmares at any dose:*

#finding(claim: [REM disinhibition — opioid tone was suppressing REM.], explanation: [Opioid agonists suppress REM sleep; opioid antagonism disinhibits it → REM rebound with vivid dreams. Confirms that endogenous opioid tone was present and active — the opioid system is functional.], certainty: [Medium — REM disinhibition by opioid antagonism is well-established in sleep pharmacology.], dntu: [whether the vivid dreams will subside with continued dosing (endorphin compensation restabilizing REM).], action: [switch to morning dosing if sleep disruption is unacceptable — concedes endorphin upregulation benefit but preserves TLR4/TRPM3 mechanisms. If vivid dreams persist despite morning dosing → unrelated to opioid rebound; consider concurrent sleep pathology.], level: [Symptom management — identifies opioid tone as load-bearing for sleep architecture.])

*Dysphoria or depression at any dose — the paradoxical reactor phenotype:*

#finding(claim: [Opioid system is load-bearing for mood homeostasis.], explanation: [Opioid receptor blockade unmasks an endogenous opioid deficit — the system that was maintaining mood stability through opioid tone collapses when even partial blockade is applied. This is a permanent trait: the patient's mood regulation depends on opioid signalling that LDN interrupts.], certainty: [High for the trait — paradoxical dysphoria on opioid antagonists is a well-documented clinical phenomenon.], dntu: [which opioid receptor subtype is responsible (mu vs. delta vs. kappa); whether the deficit is pre-existing or induced.], action: [stop LDN immediately. The patient should permanently avoid all opioid-modulating drugs: naltrexone, naloxone, buprenorphine, tramadol, tapentadol. This is not a slow-titration issue — the reaction is pharmacodynamic, not dose-rate-dependent.], level: [Safety — paradoxical reactor identification protects against iatrogenic harm from future opioid-modulating medications.])

*No side effects at any dose up to 4.5 mg:*

#finding(claim: [TLR4 and opioid systems are not rate-limiting, or the patient has broad receptor reserve.], explanation: [Neither TLR4 blockade (no GI/CNS sickness) nor opioid blockade (no sedation, no dysphoria, no vivid dreams) produces perceptible effects. This is not the same as therapeutic non-response — the patient may still benefit via TRPM3 restoration or endorphin upregulation. But the absence of side effects is itself diagnostic: it means the TLR4 hormetic ceiling has not been reached (broad Nrf2 reserve), the orexin system has adequate reserve, and opioid tone is not load-bearing for mood or sleep.], certainty: [Low — absence of side effects cannot confirm receptor function; it only confirms no receptor-level crisis was triggered.], dntu: [whether higher doses (>4.5 mg) would produce effects that the current range did not.], action: [titrate to max tolerated or max clinical dose (4.5 mg). If no benefit at 4.5 mg + no side effects → none of LDN's four mechanisms are rate-limiting.], level: [Diagnostic — silence across all four receptor systems is a strong null signal.])

*Warning — dose-too-high non-response masquerading as non-response:*

A patient trialled only at 3.0--4.5 mg who experiences no benefit AND no side effects may be a true non-responder. But a patient who experiences systemic sickness at 4.5 mg and was never trialled at lower doses is a *missed responder* — their therapeutic mechanism is the TLR4/Nrf2 hormetic window (0.5--1.5 mg), and the 4.5 mg dose sits above their therapeutic range. Non-response cannot be concluded unless the low-dose window (0.5--1.5 mg) has also been tested. This error (starting too high, concluding drug doesn't work, and stopping) is common enough to merit explicit documentation in the differential diagnostic algorithm.

==== Key caveat

non-response is weaker evidence than response. LDN non-response does not exclude immune involvement — autoantibody, B-cell, mast-cell, and T-cell mechanisms are not directly targeted. LDN non-response especially does not exclude microglial involvement if LDA (D2) works — the two drugs target different receptors on the same cell.

==== How LDN combines with other medications
- LDN + pyridostigmine both work → neuroinflammation → autonomic dysfunction (inflammatory-to-autonomic pathway).
- LDN works + valacyclovir does not → neuroinflammation without active viral replication (post-infectious mechanism).
- LDN works + antihistamines do not → neuroinflammation from non-mast-cell sources (autoantibodies, microglial priming).
- LDN does not work + cimetidine works → VIM phenotype (@sec:vim-phenotype): T-cell dysfunction, not TLR4/TRPM3.
- LDN does not work + LDA works → microglial involvement confirmed through D2 pathway despite TLR4 non-response. Complementary targets (TLR4 + D2) on the same cell population; combination may be synergistic even when LDN appears ineffective alone — LDN may reduce one input while LDA raises the threshold on all inputs simultaneously.
- LDN does not work + mast-cell stabilisers work → mast-cell → microglial pathway confirmed, but TLR4 is not the dominant microglial receptor for mast-cell-derived signals in this patient.

==== Compendium

The full pharmacodiagnostic entry — including mechanism-exclusion logic (TLR4/TRPM3/endorphin/orexin), dose-specific side-effect diagnostic patterns (SE0–SE5), combination diagnostics with aripiprazole and midodrine, and worsening risk profiles — is at @ch:mechanistic-cascade-tracing (Chapter 33, sec-12, LDN entry). The M1–M4 cascade tracing LDN's multi-target dose-response through each mechanism is at Chapter 33, sec-08. Side effects classified by the five diagnostic patterns (Patterns 1–5) are detailed at Chapter 33, sec-10.
