#import "../../../../../shared/environments.typ": *

#synthesis(title: [A Brain-First, Glutamatergic Genetic Architecture for ME/CFS])[
Taken together, the DecodeME single-gene results and the Maccallini 2026 meta-GWAS/WGS converge on a coherent genetic model that reframes where ME/CFS liability originates. The anchoring observation is *tissue specificity*: genetic risk is enriched exclusively in brain and pituitary tissue across thirty tissue types, with no peripheral immune or metabolic tissue reaching significance (@hyp:brain-first-genetic, @ach:maccallini-metagwas) — a brain-first architecture formalized as the efferent-coupling causal model in Chapter @ch:causal-hierarchy (@prop:efferent-coupling-dag) and offered as convergent support for the CNS energy crisis as a trigger-capable root cause (@sec:cns-energy-crisis). The most specific *replicated pathway* is glutamatergic: single genes in DecodeME (SHISA6, UNC13C) and a Bonferroni-corrected gene-set in the meta-analysis both implicate glutamatergic synaptic machinery (@hyp:glutamatergic-synaptic-dysfunction), motivating a two-hit model in which a constitutional excitatory/inhibitory-imbalance substrate is tipped past a homeostatic threshold by an infection-driven glutamatergic insult (@hyp:two-hit-glutamatergic-infectious). This single genetic signature does explanatory work across the paper: it grounds the cerebellar cognitive-affective (CCAS) phenotype in replicated cerebellar neuronal enrichment (@hyp:ch14h-ccas-cerebellar); it resolves the depression paradox — high genetic correlation but no shared causal variants — as shared glutamatergic genes expressed in different circuits (@spec:depression-paradox, @spec:depression-shared-genes-different-circuits); it offers a genetic reading of the strong IBS correlation via enteric glutamatergic signaling (@spec:enteric-glutamatergic-ibs); and it provides disciplined cross-disease comparisons to schizophrenia, epilepsy, and autism where the *same pathway, different circuit* logic prevents naive drug-repurposing inferences (@spec:schizophrenia-glutamatergic-parallel, @spec:epilepsy-glutamatergic, @spec:autism-cerebellar-glutamate). A secondary dopaminergic-midbrain signal additionally reframes "fatigue" as a possible effort-valuation computation rather than muscle exhaustion (@spec:vta-sn-dopaminergic).

What the genetics does *not* yet establish is equally important. The meta-analysis is a preprint (certainty 0.50); heritability is modest ($h^2_("SNP") approx 0.095$), so genetic liability is one contributor among many rather than a deterministic cause; brain-tissue enrichment localizes risk to neuronal circuits but does not identify *which* circuits are causal versus downstream; and every subtyping proposal built on this architecture — glutamatergic, dopaminergic, cerebellar, and composite polygenic risk scores (@spec:composite-neuronal-prs, @spec:da-prs-subtyping, @spec:combinatorial-snp-risk, @oq:cell-type-prs-subtyping) — remains untested against clinical outcomes. The peripheral glutamate proxy (@spec:ka-qa-glutamate-biomarker) is unvalidated. The central open question is therefore not whether ME/CFS has a brain-first, glutamatergic genetic component — two independent datasets now support this — but whether that component defines actionable patient subtypes and points to circuit-specific glutamatergic therapies, or whether it is a broad constitutional risk factor whose expression is dominated by non-genetic triggers.

*Consequence:* The strongest genetic evidence to date points to ME/CFS risk being wired into brain glutamate-signaling circuits rather than into the immune system or muscles — which, if it holds up in peer review and larger cohorts, would shift where researchers look for causes and drugs (toward brain excitation/inhibition balance) and could eventually let a blood-based DNA score flag people whose illness is primarily neuronal; but heritability is modest and none of the proposed genetic subtypes has yet been shown to predict who responds to which treatment, so this is a reorientation of the research map, not yet a clinical tool.
] <syn:brain-first-glutamatergic-genetic-architecture>
