#import "../../../../../shared/environments.typ": *

#synthesis(title: [Three-Line Genetic Convergence on Neuronal Biology])[
Three independent evidence lines — using different data types and analytic approaches — converge on neuronal biology as the genetic substrate of ME/CFS: (1) common variant GWAS enriches in brain tissues and neuronal gene-sets (DecodeME @DecodeME2025, Maccallini 2026 meta-GWAS @Maccallini2026metaGWAS); (2) rare variant burden from whole-exome sequencing concentrates in neuronal and synaptic genes @Snyder2025rareBrain; (3) cell-type enrichment analyses find medium spiny neuron (MSN) enrichment across three independent atlases and two methods while finding zero immune cell-type enrichment @Finucane2018stratifiedLDSC.

This three-pronged genetic architecture (brain-enriched common variants + rare neuronal variants + immune cell-type null) has two separable implications. First, it provides converging support for the brain-first genetic model: genetic liability operates primarily through neuronal circuits, and peripheral pathology may arise as a downstream consequence rather than a primary genetic risk. Second, the immune null — the finding that ME/CFS-associated genetic variants show no enrichment in any immune cell type (T cells, B cells, NK cells, macrophages) when tested against the ImmGen reference dataset via the Finucane 2018 stratified LDSC pipeline — does not contradict the extensive evidence for immune dysfunction in ME/CFS documented in Chapter @ch:immune-dysfunction. It suggests instead that immune pathology in ME/CFS may be acquired (infection-triggered) or environmentally driven, with effect sizes below GWAS detection threshold, rather than genetically encoded in common variants.

GWAS cell-type enrichment tells us *where constitutional liability is encoded* (neurons), not which mechanisms are operative in the established disease. All trigger mechanisms — viral infection, GPCR autoantibody production, mast cell activation, TRPM3 channelopathy, skeletal asymmetry — and all amplifier mechanisms — the PEM metabolic danger cascade, kindling-driven threshold lowering, glymphatic failure, complement-mast cell amplification loops, endothelial senescence, NET/DNase imbalance — remain valid acquired pathophysiological processes. The brain-first genetic architecture does not displace them; it constrains the upstream origin of vulnerability while the triggers and amplifiers describe the downstream acquired pathology that propagates from or triggers upon that vulnerable CNS substrate. This is formalised in the two-hit model: genetic vulnerability in neuronal circuits (hit 1) + environmental trigger (hit 2) → disease, with amplifiers sustaining chronicity. Neither invalidates the other.

However, cell-type enrichment at the MSN/eMSN level is method-dependent (certainty ~0.40–0.50 versus 0.80 for the broad neuronal signal), and MSN enrichment is shared across multiple brain-relevant traits (schizophrenia, depression, alcohol consumption, sleep duration — @Duncan2025cellTypeBrain). The genetic data identify *where* ME/CFS risk is encoded (neurons), and suggest *which cell type* may be most involved (MSNs), but does not yet identify *which mechanism* within those neurons mediates risk. The most important open question is whether the genetic signal points to a specific MSN-intrinsic pathology or to a broader neuronal process that MSN transcriptomes happen to tag by their high transcriptional diversity.

*Consequence:* Multiple independent methods using different data types agree that ME/CFS risk is genetically encoded in neurons, not immune cells — a finding that, if sustained by peer review and independent replication, would redirect ME/CFS research toward neuronal circuit mechanisms and away from the assumption that immune dysfunction is genetically primary. For patients: strengthens the evidence that ME/CFS has a biological, brain-based genetic architecture — the variation is in the genes that build and operate brain circuits, not in genes that influence psychology or behaviour.
] <syn:genetic-neuronal-convergence>
