#import "../../../../../shared/environments.typ": *

#synthesis(title: [Three-Line Genetic Convergence on Neuronal Biology])[
Three independent evidence lines — using different data types and analytic approaches — converge on neuronal biology as the genetic substrate of ME/CFS: (1) common variant GWAS enriches in brain tissues and neuronal gene-sets (DecodeME @DecodeME2025, Maccallini 2026 meta-GWAS @Maccallini2026metaGWAS); (2) rare variant burden from whole-exome sequencing concentrates in neuronal and synaptic genes @Snyder2025rareBrain; (3) cell-type enrichment analyses find medium spiny neuron (MSN) enrichment across three independent atlases and two methods while finding zero immune cell-type enrichment @Finucane2018stratifiedLDSC.

This three-pronged genetic architecture (brain-enriched common variants + rare neuronal variants + immune cell-type null) has two separable implications. First, it provides converging support for the brain-first genetic model: genetic liability operates primarily through neuronal circuits, and peripheral pathology may arise as a downstream consequence rather than a primary genetic risk. Second, the immune null does not contradict the extensive evidence for immune dysfunction in ME/CFS documented in Chapter @ch:immune-dysfunction — it suggests instead that immune pathology in ME/CFS may be acquired (infection-triggered) or environmentally driven, with effect sizes below GWAS detection threshold, rather than genetically encoded in common variants.

However, cell-type enrichment at the MSN/eMSN level is method-dependent (certainty ~0.40–0.50 versus 0.80 for the broad neuronal signal), and MSN enrichment is shared across multiple brain-relevant traits (schizophrenia, depression, alcohol consumption, sleep duration — @Duncan2025cellTypeBrain). The genetic data identify *where* ME/CFS risk is encoded (neurons), and suggest *which cell type* may be most involved (MSNs), but does not yet identify *which mechanism* within those neurons mediates risk. The most important open question is whether the genetic signal points to a specific MSN-intrinsic pathology or to a broader neuronal process that MSN transcriptomes happen to tag by their high transcriptional diversity.

*Consequence:* Multiple independent methods using different data types agree that ME/CFS risk is genetically encoded in neurons, not immune cells — a finding that, if sustained by peer review and independent replication, would redirect ME/CFS research toward neuronal circuit mechanisms and away from the assumption that immune dysfunction is genetically primary. For patients: strengthens the evidence that ME/CFS has a biological, brain-based genetic architecture — the variation is in the genes that build and operate brain circuits, not in genes that influence psychology or behaviour.
] <syn:genetic-neuronal-convergence>
