#import "../../../../../shared/environments.typ": *

==== Published Critique in Nature Communications

Davenport et al.\ published a formal Matters Arising in _Nature Communications_ @Davenport2025EffortDeconditioning directly challenging the effort-preference and deconditioning interpretation. Their critique argued that the framing “risks reinforcing skepticism about the serious biological nature of [ME/CFS] and its hallmark of post-exertional malaise (PEM), as well as its potential misclassification as a mental health condition.” The critique rests on four methodological and physiological grounds.

*Single CPET cannot characterize PEM.* Walitt et al.\ used a single maximal exercise test, but a single CPET cannot measure the response to an initial exertion — which is precisely what PEM is @Davenport2025EffortDeconditioning. The two-day CPET paradigm, in which a second maximal test is performed 24 hours after the first, is the standard for characterizing post-exertional metabolism in ME/CFS @Lim2020CPETMeta. The Institute of Medicine cautioned that “a single CPET may be insufficient to document the abnormal response of ME/CFS patients to exercise.” Because deconditioning and PEM are not mutually exclusive, observing deconditioned-like features cannot explain PEM. Using a single CPET therefore prevented Walitt et al.\ from testing whether PEM is linked to effort preference at all, since they never measured performance under objective, standardized maximal-exertion criteria.

*The heart-rate data argue against deconditioning.* In deconditioning, exercise heart rate is typically elevated for a given workload. In the Walitt study, exercise HR was instead *lower* in post-infectious ME/CFS participants than in healthy volunteers @Davenport2025EffortDeconditioning. Davenport et al.\ interpret this as inconsistent with the deconditioning hypothesis and more consistent with chronotropic incompetence and impaired oxidative metabolism — both documented features of ME/CFS — which limit energy production and are key drivers of PEM. This is the physiological crux of the rebuttal: the same data that Walitt et al.\ read as deconditioning are read by Davenport et al.\ as evidence of intrinsic metabolic and autonomic limitation. (See @sec:cpet-hypotheses for the related chronotropic-intolerance and autonomic-mitochondrial hypotheses.)

*PEM is not mere discomfort.* Walitt et al.\ characterized PEM as “discomfort” associated with exertion, which Davenport et al.\ argue downplays its severity. PEM is a profound exacerbation of multiple signs and symptoms, reduced functioning, and inability to recover after even minor physical or cognitive exertion @Davenport2025EffortDeconditioning. The 2015 IOM report proposed renaming the illness “systemic exertion intolerance disease” precisely to underscore the central, severe nature of PEM.

*The study was underpowered and under-controlled.* Only 8 post-infectious ME/CFS participants and 9 healthy volunteers completed CPET @Davenport2025EffortDeconditioning. Controls were not matched as deconditioned comparators. The order in which outcome measures were administered was omitted from the abstract, and some participants may have represented the mildest disease subgroup, limiting ecological validity. Davenport et al.\ urged that the findings be interpreted and disseminated with caution.

*Consequence:* If the effort-preference and deconditioning framing is accepted uncritically, clinicians and policymakers may discount the biological basis of ME/CFS and its hallmark PEM, reinforcing the psychogenic stigma that has long harmed patients and justified graded exercise despite documented harms. Severity applicability: the deconditioning-rebuttal claim applies across mild-to-severe disease, though Walitt's sample itself under-represented severe patients.
