#import "../../../../shared/environments.typ": *

=== Changes in Medical Understanding
<subsec:medical-understanding>

The medical understanding of ME/CFS has undergone dramatic shifts, moving from psychogenic theories toward recognition as a biological disease.

*The Psychogenic Era.*
In 1970, psychiatrists McEvedy and Beard published analyses of 15 ME outbreaks (including Royal Free 1955) in the _British Medical Journal_, concluding they represented "mass hysteria" based partly on the preponderance of female patients and institutional settings @McEvedy1970. This analysis was conducted without examining patients or consulting treating physicians. McEvedy's argument rested on three assumptions: that female predominance indicated psychogenic vulnerability (rather than immunological susceptibility, consistent with women's higher rates of most autoimmune diseases), that absence of mortality implied non-organic etiology, and that negative laboratory tests ruled out biological disease (a logical error — absence of evidence for a known pathogen is not evidence of absence of disease). Ramsay, who had personally examined Royal Free patients during the 1955 outbreak, published a book-length rebuttal in 1986 documenting long-term follow-up with objective findings — abnormal muscle biopsy, persistent neurological signs, exercise intolerance — that could not be explained psychosomatically @Ramsay1986. The Ramsay-McEvedy debate crystallized a deeper epistemological tension: when standard tests are normal, does the abnormality lie in the patient's psychology or in the sensitivity of the tests? Subsequent mathematical modeling of outbreak data has demonstrated that the epidemiological patterns fit infectious disease models, mathematically refuting the hysteria hypothesis @Underhill2021.

*The PACE Trial and Institutional Reversals.*
The largest ME/CFS treatment trial ever conducted (PACE, n=641), published in _The Lancet_ in 2011, reported that cognitive behavioral therapy and graded exercise therapy produced recovery rates of 22% @White2011pace. Independent re-analysis revealed that mid-trial changes to recovery thresholds had inflated results — under the original protocol definitions, recovery rates were approximately 6% in all groups with no meaningful advantage for any treatment @Wilshire2018. Patient surveys found that 54–74% reported worsening from graded exercise therapy @Geraghty2019GET. This prompted a series of institutional reversals: the CDC removed graded exercise therapy from its clinical guidance (2017), Cochrane withdrew and revised its systematic review (2019), and NICE guideline NG206 explicitly recommended against graded exercise therapy (2021) @NICE2021mecfs. The PACE trial has become the most-cited cautionary tale in ME/CFS research methodology, demonstrating that patient-led FOIA requests and independent statisticians — not institutional quality control — were required to force data release and re-analysis.

*Return to Biological Investigation.*
The Lake Tahoe outbreak reinvigorated biological research, leading to investigations of viral triggers, immune dysfunction, and neurological abnormalities through the 1990s and 2000s. The Canadian Consensus Criteria (2003) and International Consensus Criteria (2011) explicitly framed ME/CFS as a neuroimmune disease with objective physiological abnormalities.

*The 2015 IOM Report.*
The Institute of Medicine's comprehensive review concluded that "ME/CFS is a serious, chronic, complex systemic disease that often can profoundly affect the lives of patients" @IOM2015. The committee emphasized that ME/CFS is a "medical—not psychiatric or psychological—illness" and called for increased research funding and physician education.

*The 2024 NIH Deep Phenotyping Study.*
The landmark NIH intramural study by Walitt et al.\ (2024) using deep phenotyping provided evidence for biological abnormalities across multiple systems in ME/CFS @walitt2024deep. This study demonstrated brain dysfunction (decreased temporoparietal junction activity), immune exhaustion (exhausted T-cells and chronic B-cell activation), and neurochemical abnormalities (low catecholamines in cerebrospinal fluid). Standard clinical laboratory panels remained normal — validating what every outbreak from 1934 to 1985 had reported. The NIH officially stated that "ME/CFS is a serious, chronic, systemic disease... researchers have found differences in the brains and immune systems of people with post-infectious ME/CFS" @nih2024mecfs. However, the study was controversial in its interpretive framing: the lead authors emphasized an "effort preference" model — suggesting that patients' reduced motor output reflected altered decision-making about effort rather than physiological impairment — despite documenting physiological abnormalities that equally supported a metabolic or neuroinflammatory interpretation. This framing triggered widespread criticism from patient organizations, researchers, and clinicians, and highlighted a recurring pattern: objective biological findings can be co-opted by preexisting psychosomatic interpretive frameworks, even by investigators themselves.

*The COVID-19 Catalyst.*
The COVID-19 pandemic paradoxically accelerated ME/CFS research by creating millions of long COVID patients with overlapping symptom profiles. The recognition that 10–30% of COVID-19 survivors develop persistent symptoms, with up to 51% of long COVID patients meeting ME/CFS diagnostic criteria @RECOVER2025, brought unprecedented attention and funding to post-infectious illness research. This convergence has produced several advances:

    - *Shared research infrastructure*: Long COVID research programs (RECOVER, PHOSP-COVID) have included ME/CFS comparison groups, generating high-quality data on both conditions.
    - *Treatment crossover*: Interventions studied for long COVID, including low-dose naltrexone (LDN), have shown promise in ME/CFS populations. LDN, which modulates microglial activation and neuroinflammation, emerged from long COVID clinical experience and is now being systematically studied in ME/CFS @Bolton2020LDN.
    - *Biomarker discovery*: The urgency of the long COVID crisis has accelerated biomarker research applicable to both conditions, including markers of immune exhaustion, microclotting, and mitochondrial dysfunction.
    - *Public recognition*: The visibility of long COVID has reduced stigma around ME/CFS and increased acceptance that post-infectious chronic illness is a legitimate medical phenomenon.

The connection between long COVID and ME/CFS has validated decades of patient advocacy and shifted the research paradigm toward viewing ME/CFS as the prototypical post-acute infection syndrome.
