#import "../../../../../shared/environments.typ": *

#achievement(title: [Unified Mechanistic Model of ME/CFS])[
ME/CFS is best understood as a disorder of impaired physiological adaptability and resilience. The contemporary literature converges on a biologically coherent model in which immune disturbance, metabolic reprogramming, endothelial dysfunction, and impaired physiological adaptability interact across systems, positioning ME/CFS within a broader class of post-infectious, immune-mediated chronic diseases characterised by dynamic, stress-revealed pathology rather than fixed structural lesions. @Watton2026unified (Certainty: 0.45 — model is a review synthesis subject to revision; individual component certainties vary)

*Key insight — state-dependent pathology.* A central conceptual advance is the recognition that some key abnormalities are exaggerated or revealed under physiological stress rather than fully manifest at rest. Cellular and vascular systems show varying degrees of resting dysfunction (e.g., flow-mediated dilation impairment at rest, ~5.1% vs 8.2% in controls, Section @sec:endothelial) but often exhibit disproportionate failure under metabolic, oxidative, or immune challenge — unable to up-regulate energy production, maintain redox balance, or preserve barrier integrity. @Watton2026unified This pattern implies that resting biomarkers will systematically underestimate, but not misrepresent, disease burden. The principle of stress-revealed pathology does not mean "normal at rest" — resting abnormalities exist and are measurable — but rather that the full magnitude of dysfunction becomes visible only under challenge.

*Limitations of the "state-dependent" framing.* Several documented ME/CFS abnormalities appear to be structural or constitutive rather than state-dependent: capillary basement membrane thickening (collagen IV deposition, Chapter @ch:cardiovascular), RBC morphological abnormalities and deformability deficits persisting beyond the 120-day RBC lifespan, and ion channel dysfunction (TRPM3) observable in resting NK cells. The state-dependent model must coexist with evidence for constitutive pathology; the two are not mutually exclusive. Some abnormalities may be structural and cumulative (basement membrane thickening, epigenetic marks), while others are dynamically stress-revealed (endothelial adaptive capacity, mitochondrial metabolic reserve, CSF proteomic shifts). A complete model requires both categories.

*Operationalising "physiological resilience."* The concept of impaired physiological resilience requires measurable parameters to avoid tautology. Candidate operational definitions include: (a) spare respiratory capacity (the difference between maximal and basal mitochondrial oxygen consumption — a direct measure of metabolic reserve, recently demonstrated to be acutely modifiable by whole-body hyperthermia in ME/CFS PBMCs @Hochecker2025HyperthermiaMECFS, and proposed as the bottleneck for thermoregulatory work ch06:@spec:mitochondrial-reserve-thermoreg); (b) endothelial barrier recovery time after standardised challenge (TNF-$alpha$ or H#sub[2]O#sub[2] exposure, measuring time to restoration of transendothelial electrical resistance); (c) heart rate recovery after standardised orthostatic or exercise challenge; (d) the hysteresis magnitude between stress removal and symptom/sign resolution (the temporal lag characterising PEM); and (e) the ratio of resting to stress-provoked biomarker levels (e.g., ATG13, haptoglobin proteoforms, EV cargo profiles). These are individually measurable and collectively define a multidimensional resilience phenotype. The Watton--Prusty model gains testability to the extent that these or analogous parameters are specified. (Overall model certainty: 0.45)

*Mechanistic convergence across domains.* The unified model identifies convergent abnormalities spanning:

- *Immune dysregulation:* Persistent innate and adaptive immune activation, selective monocyte/T-cell reprogramming, abortive viral reactivation (herpesvirus dUTPases driving chronic innate immune activation without productive infection), fibronectin--IgG circulating immune complex alterations with homeostatic antibody depletion, and autoantibodies against $beta$-adrenergic and muscarinic receptors (with the strongest quantitative autonomic--autoantibody correlation to date being $r=0.45$, $p=0.001$, documented by Azcue et al. 2026 @Azcue2026gpcr)
- *Metabolic reprogramming:* Hypometabolic signatures, mitochondrial fragmentation induced by circulating factors (IgG fractions), impaired oxidative phosphorylation, and dysregulated autophagy/mitophagy (elevated ATG13)
- *Endothelial and microvascular dysfunction:* Stress-revealed impairment of endothelial metabolic responsiveness, coagulation abnormalities, fibrinolysis-resistant fibrin(ogen) aggregates, haptoglobin proteoform insufficiency exacerbating haem-mediated oxidative stress
- *Lipid and membrane biology:* SMPDL3B-mediated sphingolipid imbalance altering lipid raft fluidity and immune receptor organisation, linking omics-level lipid abnormalities to cellular immunophenotypes
- *Extracellular vesicle communication:* EVs carrying altered proteomic signatures, severity-associated immune markers, and mitochondrial DNA capable of activating innate immune pathways, providing a mechanism for local cellular dysfunction to propagate systemic effects

*Replicability at pathway vs. gene level.* A systematic reanalysis by Keele et al. found that only 2 genes were consistently replicated across ME/CFS transcriptomic studies, with proteomic convergence largely absent. However, convergence emerged at the pathway level, with mitochondrial dysregulation as a recurrent feature across multiple data modalities. This pattern — limited reproducibility at individual molecular signals but consistency at the systems level — supports the unified model's emphasis on coordinated multi-system dysfunction rather than single-gene defects.

*Long-COVID as convergent evidence — with important caveats.* The emergence of Long-COVID did not provide conceptual novelty, but it did provide statistical power, temporal anchoring (known infection date), and institutional legitimacy — enabling larger-scale investigation of biological processes relevant to ME/CFS. Large-scale Long-COVID cohorts have identified abnormalities in immune dysregulation, endothelial function, coagulation, metabolism, and viral persistence that map onto pre-existing ME/CFS research strands. This convergence suggests that some post-infectious biological mechanisms may be shared. @Watton2026unified

*However, three important qualifications apply.* First, several objective measures show substantive divergence between Long-COVID and ME/CFS rather than simple convergence. Long-COVID patients with self-reported PEM show no 2-day CPET deterioration — the single most robust objective biomarker in ME/CFS (see Section @sec:cross-disease on CPET divergence). Circulating cell-free mitochondrial DNA dynamics are directionally opposite: reduced ccf-mtDNA in Long-COVID (impaired mitophagy) versus elevated exosome-associated mtDNA post-exercise in ME/CFS (stress-triggered release). Shahbaz et al. found both overlap and divergence in immune cell phenotypes between Long-COVID-associated and idiopathic ME/CFS — shared immune activation but more pronounced T-cell exhaustion, NK-cell alteration, and MAIT/$gamma delta$ T-cell depletion in the Long-COVID-associated group. Second, Long-COVID cohorts are heterogeneous and include many patients whose symptoms resolve within 12 months, whereas ME/CFS by definition requires 6 months and typically persists for years to decades — the comparison conveys partial rather than complete equivalence. Third, the claim that prior ME/CFS uncertainty "reflected insufficient investigative capacity, not the absence of biology" is a plausible inference, not a demonstrated fact. Alternative interpretations are not eliminated: genuine biological heterogeneity, diagnostic criteria so broad they produce irreproducible cohorts, or fundamentally different disease processes in subsets of patients could all contribute to prior null findings independent of funding level. The Keele et al. finding of pathway-level but not gene-level convergence is equally consistent with heterogeneous biology being studied with better tools as it is with a single biology finally illuminated by adequate methods. The question warrants an open mind, not premature closure. @Watton2026unified

*Key uncertainties.* The Watton--Prusty model identifies critical unresolved questions: what upstream events stabilise persistent immune-metabolic dysregulation? Why do only a subset of individuals exposed to the same trigger develop chronic illness? What mechanism governs the transition from acute trigger to sustained dysregulation? Are the identified abnormalities primary drivers or secondary adaptations? Resolving these questions requires large deeply-phenotyped cohorts incorporating physiological challenge paradigms together with integrated multi-omic and functional approaches, including time-resolved single-cell transcriptomics (scSLAM-seq), exercise-challenged CSF proteomics, and plasma-mediated pathophysiology studies. @Watton2026unified (Certainty: 0.55)
]
