#import "../../../../shared/environments.typ": *

#achievement(title: [The Five Psychologization Harms — A Framework from Within Psychiatry])[
Schomerus et al.\ (2026) articulate five specific, interconnected harms that follow from psychologizing LC and ME/CFS, whether primary or secondary:

*Harm 1: Iatrogenic deterioration from activation therapy.* A psychological attribution implies that deconditioning, avoidance, and illness beliefs must be treated with graded activity. Patient surveys document that 72% of LC respondents reported "damaging or incorrect treatments, predominantly activating therapies during rehabilitation or medical recommendations to exercise" @Hammer2025LCBarriers. The US patient survey by Eckey et al.\ (2025, n=3,867) found that 50% of those who experienced graded exercise therapy reported substantial worsening, with a further 30% reporting moderate or mild deterioration; only 10% experienced any improvement @Eckey2025PRO. These harm reports are biologically anchored: PEM is driven by impaired energy metabolism (Chapter @ch:energy-metabolism) and exertion above the lowered threshold produces measurable tissue damage @Appelman2024muscle.

*Harm 2: Invalidation of illness experience.* When symptoms are framed as products of dysfunctional illness beliefs rather than biological disease, the patient's body perception—their only available instrument for managing PEM through pacing—is pathologized. Psychologization undermines the patient's capacity for self-management by reclassifying pacing as "avoidance" and genuine PEM as "catastrophizing" (Section @sec:ch15-emotional-interoceptive). Büchner et al.\ (2025, n=1,156) found that 46.8% of LC patients were told their symptoms were psychological; this experience was strongly associated with perceived stigma ($p < 0.001$) and mediated worse mental health outcomes @Buchner2025Psychologization.

*Harm 3: Neglect of biomedical diagnosis and treatment.* A psychological framework reduces the perceived need for biomedical investigation. Individual symptoms and comorbidities—POTS, MCAS, orthostatic hypotension—are somatically treatable in many cases, yet patients report that psychosomatic attribution prevents appropriate workup. The D-A-CH consensus explicitly recommends systematic exclusion of treatable somatic conditions before considering psychiatric differentials @Hoffmann2024DACHconsensus. A psychological "F-diagnosis" can produce negative cascading effects across treatment, employment law, and insurance as physical complaints receive less attention in the presence of psychiatric labels—a well-documented diagnostic overshadowing effect.

*Harm 4: Medico-legal disadvantage.* In disability assessment, insurance evaluation, and workers' compensation, the assumption of psychological causation is practically unfalsifiable: rejection of the psychosomatic disease model is itself interpreted as evidence of its relevance (lack of insight, somatization). Unlike in therapeutic contexts where the patient can decline an unhelpful model, in medico-legal settings the attribution carries binding consequences.

*Harm 5: Family and social harm.* The same logic that pathologizes patients also pathologizes their caregivers. Parents of children with ME/CFS who protect their child from activity that triggers PEM can be accused of facilitating avoidance, reinforcing illness behavior, or even perpetrating Münchhausen-by-proxy syndrome—with documented cases of child protection proceedings and loss of custody @Schomerus2026PsycheRole. Similar dynamics affect adult children caring for parents with ME/CFS and parents with ME/CFS who are assessed for childcare capacity.

_(Certainty: 0.70. Each harm category is supported by independent evidence: quantitative surveys for harms 1–3 @Hammer2025LCBarriers @Eckey2025PRO @Buchner2025Psychologization, clinical consensus for harm 3 @Hoffmann2024DACHconsensus, qualitative evidence for harms 4–5. The framework's explanatory power is high—it subsumes the existing bullet-list harms into a coherent causal taxonomy. Not yet formally evaluated as a psychometric instrument or intervention target. Replication status: partially—the harm categories are articulated as a conceptual framework; each sub-component has independent supporting evidence but the framework as a whole has not been empirically validated. *Falsifiability:* The framework predicts that psychologization exposure → functional decline is mediated by pacing disruption (Harm 2) — testable via the prospective cohort design proposed in @oq:psychologization-prospective-cohort. The framework would be weakened if psychologization exposure does not independently predict functional decline after controlling for objective baseline severity, or if the pacing-disruption mediation pathway is not significant.)_
] <ach:psychologization-five-harms>
