#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Dysbiotic Microbiome-Immune-Metabolome Crosstalk with a Benzoate-to-Hippurate Axis])[
BioMapAI's connectivity map links three physiological compartments in ME/CFS @Xiong2025BioMapAI. Compared to healthy controls, patients show decreased butyrate and branched-chain amino acid microbial pathways and increased tryptophan and benzoate pathways, changes the model ties to gastrointestinal symptoms. In parallel, the immune system loses health-associated interactions with Th17, Th22, and regulatory T cells and shifts toward heightened inflammatory activity in mucosal-associated invariant T (MAIT) and gamma-delta T cells. A network-level change is an increase in the benzoate-to-hippurate transformation, which the model attributes to emotional disturbance, sleep problems, and fatigue. *Important caveat:* these symptom attributions and the direction of the links are model output — the model's SHAP connectivity map is correlational, its symptom attributions were not held-out validated (see @lim:biomapai-symptom-circularity), and the model does not establish which compartment drives which, or whether any of it is cause versus consequence.

These observations knit together hypotheses already present in this paper. Decreased butyrate and branched-chain amino acid capacity is established in the gut-microbiome literature (@ach:butyrate-deficiency, @Xiong2023multiomics). Increased tryptophan flux is consistent with the kynurenine/serotonin-diversion hypothesis (@Kavyani2022kynurenine, @taenzer2023urine). The innate-like T-cell signature echoes single-cell and flow-cytometry evidence of T-cell remodeling in post-infectious ME/CFS, including galectin-9-associated depletion of gamma-delta and MAIT cells in Long COVID with ME/CFS @Shahbaz2026single-cell-immune and cytotoxic-T-cell alterations tracking symptom severity @Lee2025TcellActivation. The benzoate-to-hippurate axis itself has only indirect support: elevated hippuric acid is reported in post-infectious syndromes @Brigo2025UremicMetabolites and in fibromyalgia @Malatji2017FibromyalgiaMetabolomics, but these are small (n=41; n=18) neighbouring-population studies that show hippurate elevation in *other* conditions — they do not independently establish a benzoate-to-hippurate axis tied to ME/CFS symptoms.

The hypothesis — and it is a hypothesis, not an established mechanism — is that these changes may not be parallel coincidences but part of a coordinated host-microbiome dysregulation: gut dysbiosis *might* produce a microbial-metabolite signal (decreased butyrate/BCAA, increased tryptophan/benzoate) that is read by the immune system and reflected in plasma lipids and bile acids, with a resulting inflammatory tone (MAIT/gamma-delta IFN-gamma and granzyme A) contributing to symptom burden, and the benzoate-to-hippurate transformation (hepatic glycine conjugation of microbially-produced benzoate) *possibly* serving as a readout. Direction of causation is unresolved and may run part or all of both ways: symptoms and inactivity could alter the gut and diet; benzoate is a common food additive and gut-processed species, so dietary intake is an uncontrolled confound. A simpler alternative is a single shared upstream perturbing agent producing correlation across compartments without directed crosstalk.

Certainty: 0.30 — the component pillars (butyrate, tryptophan, T-cell inflammation) are each supported by separate literature, but the specific integrated "crosstalk" and benzoate-to-hippurate axis rest on a single model's correlational connectivity map plus two tiny neighbouring-population pilots (Brigo 0.26, Malatji 0.20, which are not replication) with unaddressed reverse-causation and diet confounds. Severity applicability: unknown — cohort not stratified by severity; severity-specific claims cannot be made.

*Falsifiable prediction:* In an independent ME/CFS cohort with paired metagenomics and plasma/urine metabolomics, patients vs controls should show (a) reduced abundance of butyrate- and BCAA-producing taxa with reduced corresponding metabolites, (b) increased benzoate and hippurate, and (c) a significant positive correlation between plasma/urinary hippurate (or a benzoate-pathway score) and severity of fatigue, sleep disturbance, or emotional disturbance, *after adjusting for dietary benzoate intake and overall dysbiosis burden*. If the benzoate-to-hippurate axis is only a marker of global dysbiosis (or of diet), it should not independently predict symptom severity after those adjustments.

*Consequence:* Until the hypothesis survives independent, diet-adjusted replication, it is a research readout to test, not a measure to track illness burden in the clinic. If it does replicate, it could become a urinary/blood readout of the microbial-immune interface — but that is a future step, not a present capability.
] <hyp:biomapai-dysbiotic-crosstalk-benzoate-hippurate>
