#import "../../../../shared/environments.typ": *

=== Speculative Immune-Targeted Interventions
<sec:speculative-immune-interventions>

#speculation(title: [ATG13 Neutralization via Monoclonal Antibodies])[
*Certainty: 0.35. Probability of clinically meaningful efficacy in ME/CFS: 0.05.* If ATG13 is a circulating DAMP amplifying CDR downstream of abortive viral reactivation, neutralising monoclonal antibodies could reduce inflammatory signaling. This is analogous to anti-cytokine biologics but targets a novel DAMP pathway. ATG13 mAbs would require development from scratch (no existing therapeutic pipeline). The therapeutic concept is mechanistically coherent but requires ATG13 to be a causal driver rather than an epiphenomenon. Falsifiable: anti-ATG13 mAb treatment in ex vivo ME/CFS PBMC cultures will reduce IL-1$beta$, TNF-$alpha$, IL-6 and shift mitochondrial morphology toward interconnected networks.
] <spec:atg13-mab>

#speculation(title: [TRPM3 Agonists for Calcium Homeostasis Restoration])[
*Certainty: 0.45. Probability of clinically meaningful efficacy in ME/CFS: 0.10.* TRPM3 calcium channel dysfunction in NK cells is a reproducible ME/CFS finding. TRPM3 agonists (pregnanolone sulfate, CIM0216) could restore calcium flux, normalising mitochondrial function, redox regulation, and endothelial responsiveness — all calcium-dependent processes. Pregnanolone sulfate is an endogenous neurosteroid with established safety profile; CIM0216 is a research tool. No ME/CFS TRPM3 agonist trial exists. Falsifiable: TRPM3 agonist treatment will restore calcium influx kinetics, improve mitochondrial membrane potential, increase NK cytotoxicity, and reduce ROS in ME/CFS cells.
] <spec:trpm3-agonists>

#speculation(title: [Sphingolipid Modulators to Restore Lipid Raft Function])[
*Certainty: 0.42. Probability of clinically meaningful efficacy in ME/CFS: 0.06.* SMPDL3B-mediated lipid raft disorganization may underlie receptor mis-localization (TRPM3, $beta$-adrenergic). Sphingolipid modulators (myriocin, FTY720/fingolimod, sphingosine kinase inhibitors) could normalise raft fluidity and restore signal transduction. FTY720 is FDA-approved for multiple sclerosis — a cross-disease precedent for sphingolipid modulation. However, FTY720 induces lymphopenia (lymphocyte sequestration), which could be counterproductive in an already immune-compromised condition. Falsifiable: sphingolipid modulator treatment will normalise lipid raft fluidity (Laurdan staining), restore TRPM3/$beta$-adrenergic receptor surface localization, and improve cAMP/calcium signaling.
] <spec:sphingolipid-modulators>

#speculation(title: [ASM Modulators for SMPDL3B Pathway Correction])[
*Certainty: 0.38. Probability of clinically meaningful efficacy in ME/CFS: 0.04.* SMPDL3B is an acid sphingomyelinase (ASM)-like protein. ASM inhibitors (amitriptyline, desipramine — functional inhibitors of ASM) are already prescribed to ME/CFS patients for pain/sleep, providing a serendipitous existing-use cohort. If amitriptyline's benefit in ME/CFS is partly mediated through ASM inhibition and lipid raft normalization rather than NMDA antagonism alone, this would explain the efficacy at low doses where antidepressant effects are absent. Falsifiable: ASM modulators will normalise SMPDL3B activity in ME/CFS immune cells, restore lipid raft fluidity, and improve TRPM3 function.
] <spec:asm-modulators-smpdl3b>

#speculation(title: [Fibronectin-IgG Complexes as Immunological Memory Impairment])[
*Certainty: 0.35. Probability of clinical diagnostic utility: 0.05.* Directionally discordant Fn1 biology may reflect broader immunological memory dysfunction. IgG-mediated pathogen clearance and cellular debris scavenging are compromised, creating feedback where new triggers exacerbate unresolved debris accumulation. Reduced natural IgM anti-fibronectin antibodies (documented after COVID) represent loss of homeostatic protection. Falsifiable: ME/CFS patients will show impaired clearance of labeled immune complexes in vitro, reduced IgM repertoire diversity (NGS), and exaggerated inflammatory responses to immune complex rechallenge.
] <spec:fibronectin-immunological-memory>

#speculation(title: [SMPDL3B as Sex-Stratified Mechanistic Substrate])[
*Certainty: 0.30. Probability of clinical relevance: 0.02.* ME/CFS shows ~3:1 female predominance. SMPDL3B regulation may be estrogen-responsive, providing a mechanistic substrate for sex differences in lipid raft organization and clinical presentation. This is entirely speculative — SMPDL3B sex-specificity has not been studied in any condition. Falsifiable: SMPDL3B expression will correlate with estrogen levels across menstrual cycle phases and differ between males and females with matched ME/CFS severity.
] <spec:smpdl3b-sex-stratification>

#speculation(title: [Compensatory $beta_2$-AR Upregulation in AAb-Positive ME/CFS])[
*Certainty: 0.35.* Chronic $beta_2$-AAb exposure may trigger receptor desensitization followed by compensatory $beta_2$-AR upregulation on immune cells (monocytes, NK cells) and endothelial cells, paradoxically increasing catecholamine sensitivity. This "rebound hypersensitivity" could contribute to PEM after minor sympathetic surges. @Azcue2026gpcr @Hackel2025monocyte. Prediction: $beta_2$-AR density (radioligand binding or PET) inversely correlated with $beta_2$-AAb titers at rest but positively correlated with post-exertional symptom severity. Ex vivo monocytes from $beta_2$-AAb-positive patients show amplified cytokine response to isoproterenol vs $beta_2$-AAb-negative. Immunoadsorption normalizes $beta_2$-AR density within 2 weeks. Limitation: receptor density never measured in ME/CFS. Falsifiable by radioligand binding in $beta_2$-AAb-positive vs negative PBMCs.
] <spec:beta2-ar-compensatory-upregulation>

#speculation(title: [Vagal Afferent M3 Desensitization as PEM Driver])[
*Certainty: 0.32.* M3 mAChRs on vagal afferents in nucleus tractus solitarius may be desensitized by chronic low-level M3-AAb agonism, creating a "vagal blind spot" where peripheral inflammatory/metabolic signals fail to trigger parasympathetic compensation. After exertion, unopposed sympathetic activation persists → PEM. PCC borderline/pathological M3 results @Azcue2026gpcr may indicate acute-phase vagal damage with M3-AAb overlay. Prediction: M3-AAb-positive patients show reduced compensatory parasympathetic response after isometric handgrip vs M3-AAb-negative. Baroreflex sensitivity improves after M3-AAb immunoadsorption within 3 weeks. Limitation: vagal afferent receptor expression not measured in ME/CFS; M3-AAb functional status undetermined. Falsifiable by baroreflex sensitivity comparison stratified by M3-AAb titers pre/post immunoadsorption.
] <spec:vagal-m3-desensitization-pem>

#speculation(title: [Sex-Specific GPCR AAb Epitope Repertoire and Female Bias])[
*Certainty: 0.25.* Estrogen upregulates $beta_2$-AR on B cells (ER$alpha$ binding to $beta_2$-AR promoter), increasing antigenic target density. BAFF-mediated B cell survival further preserves $beta_2$-AAb-producing clones in females. This may partially explain 4:1 female predominance in ME/CFS. PCC sex ratio closer to 1:1 because acute COVID-19 B cell depletion resets epitope repertoire. Prediction: $beta_2$-AAb titers correlate with serum estrogen across menstrual cycle phases; male ME/CFS patients show lower $beta_2$-AAb titers vs females matched for severity; $beta_2$-AR expression on B cells (flow cytometry) higher in female ME/CFS vs male vs HC. Limitation: no direct evidence linking estrogen to GPCR AAb titers in ME/CFS; single cross-disease inference chain. @Azcue2026gpcr.
] <spec:sex-gpcr-aab-female-bias>

#limitation(title: [Scope and Foundation Caveat for GPCR Autoantibody Framework])[
The GPCR autoantibody content in this paper identifies beta2-adrenergic and muscarinic receptor autoantibodies as a promising mechanistic axis supported by multiple independent groups (Loebel, Bynke, Sotzny, Azcue, Wallukat, Stein), early therapeutic signals (immunoadsorption, daratumumab), and convergent cross-disease evidence (CRPS, FM passive transfer). However, the framework rests on a contested measurement platform (CellTrend ELISA) whose specificity has been challenged: Vernino 2022 found 98.3% POTS positivity and 100% control positivity using the same methodology; Germain 2025 (n=172, REAP+Luminex, 7,542 interactions) found complete null results for GPCR autoantibodies in ME/CFS. The strongest quantitative correlation (Azcue2026: beta2-AAb vs sympathovagal imbalance, r=0.45, r^2=0.20) explains only 20% of HRV variance. No clinical GPCR autoantibody test is available in routine care. The treatment protocols, biomarker proposals, and mathematical models downstream of this section represent provisional scaffolding for hypothesis testing — not validated clinical pathways. The simplest explanation for the CellTrend vs REAP discrepancy (non-specific ELISA binding) would nullify most of the GPCR-AAb-specific proposals. Readers should regard these as a research agenda, not as established mechanism.
] <lim:gpcr-aab-framework-caveat>
