#import "../../../../shared/environments.typ": *

=== Normal Mechanisms Turned Pathological


The following are not failures of the energy machinery in the conventional sense. Each is a normal biological program—one that evolved for protective purposes—that has become self-sustaining and now suppresses energy production as a consequence of its persistence. The distinction matters therapeutically: these programs cannot be treated by supplying more substrate or replacing a broken enzyme. They require a different kind of intervention—a signal that tells the system the danger has passed—and until that signal arrives, they will continue to consume or suppress the very energy they originally evolved to protect.

    / *Cell danger response (certainty 0.40)*: The cell danger response (CDR) is a normal coordinated defensive program: when a cell is threatened, it reduces mitochondrial function, shifts metabolism toward protective inflammatory readiness, and alters purinergic signaling to alert neighboring cells . In ME/CFS, this program appears to fail to terminate after the initial trigger resolves—or, under the strongest alternative interpretation, the trigger itself (persistent virus, autoantibodies, microclots) has not resolved, and the CDR continues responding appropriately to an ongoing stimulus. Either interpretation implies chronically suppressed oxidative phosphorylation; they differ in what treatment is required (Section @sec:metabolic-trap).

    / *Hypometabolic dauer state (certainty 0.30)*: The dauer state is a well-characterized survival program in _C. elegans_: when environmental conditions become hostile, the organism suppresses approximately 80% of metabolic activity to conserve resources until conditions improve. The hypothesis is that ME/CFS represents an analogous human hypometabolic survival state, with a ~2-year threshold beyond which the state becomes entrenched and potentially irreversible. As with the CDR, this is not a broken mechanism—it is a working one applied in the wrong context (Section @sec:metabolic-trap).

    / *IDO metabolic trap (certainty 0.35)*: Indoleamine 2,3-dioxygenase (IDO) is a normal immune enzyme: when activated by IFN-$gamma$ during infection, it diverts tryptophan away from serotonin synthesis toward the kynurenine pathway, depleting an amino acid that pathogens need. In ME/CFS, chronic immune activation maintains IDO activity, producing neurotoxic kynurenine metabolites that perpetuate the immune activation that drives IDO—a self-sustaining loop. The IDO pathway is functioning correctly; it is the immune context that maintains it that has become pathological (Section @sec:metabolic-trap).

    / *Succinate as metabolic danger signal (certainty 0.35)*: Succinate is a normal TCA cycle intermediate. When it accumulates—as occurs when oxidative phosphorylation is impaired and the TCA cycle backs up—it acts as a danger signal: it activates the NLRP3 inflammasome and stabilizes HIF-1$alpha$, both of which promote glycolytic-inflammatory metabolism. This is a designed signaling role, but in ME/CFS the impaired ETC creates chronic succinate accumulation, locking cells into a self-reinforcing glycolytic-inflammatory state that further suppresses oxidative metabolism (Chapter @ch:symptom-mechanisms).

