#import "../../../../shared/environments.typ": *

=== What This Part Contributes---and What It Does Not
<sec:contribution-scope>

The models developed in Chapters @ch:energy-metabolism-models through @ch:predictive-applications attempt something not, to our knowledge, previously published in the ME/CFS literature: a multi-system ODE framework that couples energy metabolism, immune dynamics, neuroendocrine regulation, autonomic control, coagulation, mast cell activation, connective tissue biomechanics, GI motility/SIBO dynamics, and epigenetic state dynamics into an integrated dynamical system of 64 state variables. Specifically, the contributions are:

+ *Mechanistic PEM model*: To our knowledge, no prior work formulates post-exertional malaise as a dynamical system with explicit rate equations for ATP depletion, ROS generation, secondary immune activation, and delayed symptom amplification. The model extends to metabolic flexibility (Randle cycle, GPR81 feedback), carnitine shuttle dynamics, and mitochondrial quality control (fission/fusion/mitophagy/biogenesis) (Chapter @ch:energy-metabolism-models).
+ *Extended immune and vascular models*: Mast cell degranulation dynamics with self-amplification thresholds, coagulation cascade with microclot-mediated oxygen delivery reduction (predicting multiplicative VO#sub[2] impairment), endothelial dysfunction via eNOS uncoupling, and daratumumab response kinetics (Chapter @ch:immune-system-models).
+ *Neuroendocrine integration*: BH4 three-way cofactor competition (TPH/TH/NOS) reveals coordinated serotonin/dopamine/NO deficits from a single bottleneck; cerebrovascular autoregulation models multiplicative CBF impairment; central sensitization is modeled as bidirectional feedback rather than passive readout; small fiber neuropathy couples to autonomic dysfunction (Chapter @ch:neuroendocrine-models).
+ *Multi-system coupling*: The integrated 64-variable model (Chapter @ch:integrated-systems) formalizes bidirectional interactions---energy$<->$immune, neuro$<->$immune, HPA$<->$immune, cardiovascular$<->$metabolic, gut$<->$brain$<->$immune, autonomic$->$motility$->$SIBO$->$immune$+$energy, mast cell$<->$energy$<->$autonomic, coagulation$<->$oxygenation$<->$mitochondria---as explicit coupling terms. The model includes GI motility/SIBO dynamics with autonomic and mast cell drivers, connective tissue/EDS biomechanical coupling to POTS, and epigenetic state dynamics (methylation + acetylation as slow variables creating hysteresis). Phair modeled one pathway; Broderick characterized one network; the present work attempts to link these subsystems dynamically.
+ *Bifurcation and attractor analysis*: Beyond Phair's single-pathway bistability, the coupled system exhibits three distinct disease attractors (metabolic-dominant, immune-dominant, severe/locked), identified through bifurcation analysis. Separatrix topology determines which recovery paths are accessible from each attractor (Chapter @ch:integrated-systems).
+ *Temporal evolution and early warning signals*: Critical slowing down analysis yields wearable-detectable early warning signals for PEM crashes 24--48 h in advance. Hysteresis from epigenetic consolidation defines a 3--12 month intervention window after disease onset. Hopf bifurcation predicts 2--6 week symptom oscillation periods usable as proximity-to-recovery biomarkers. Kramers escape rate theory quantifies spontaneous recovery probability as a function of disease duration (Chapter~@ch:temporal-evolution).
+ *Clinical translation via control and network theory*: Pacing is formulated as optimal control (Pontryagin maximum principle, Hamilton--Jacobi--Bellman for stochastic extension), yielding state-dependent rules and quantitative safety margins. Global sensitivity analysis (Sobol indices) ranks drug targets across the population and reveals subtype-specific target inversion. Network controllability analysis predicts that 4--6 simultaneous interventions are structurally required for full system control---providing a mathematical explanation for monotherapy failure. A synergy matrix identifies specific treatment combinations and antagonisms. Virtual population simulation enables in silico trial design with enrichment optimization (Chapter~@ch:predictive-applications).

These contributions must be understood in the context of severe limitations.

#include "limitations/critical-limitations-of-the-present-models.typ"

In summary, the present work is the most comprehensive attempt at dynamical systems modeling of ME/CFS to date---extending from single-subsystem ODEs through a 64-variable integrated model to bifurcation analysis, optimal control theory, and network controllability---but it remains a theoretical framework awaiting computational implementation and empirical validation. It should be read as a formalization of hypotheses---translating the verbal models of Morris and Maes @morris2013neuroimmune and others into the language of differential equations, and then extracting predictions that are only accessible through the mathematical formalism---rather than as established quantitative science.

