#import "../../../../shared/environments.typ": *

// Subsec-14: The Ligand-Receptor Duality
// Added 2026-07-26 — meta-framework for signal classification

=== The Ligand-Receptor Duality: Which Signal Carries the Diagnostic Information?
  <sec:ligand-receptor-duality>

The five diagnostic patterns above (Patterns 1--5: exaggerated, paradoxical, off-target, tolerability ceiling, absent) classify *what kind* of side-effect signal the body is producing. But there is a prior and more fundamental question: for any given medication, *which signal* — the therapeutic effect or the side effect — carries the diagnostic information in the first place?

This is the Ligand-Receptor Duality: every drug a patient takes binds to a receptor and produces two classes of signal. In standard pharmacology, the *therapeutic signal* is the drug's purpose and the *side-effect signal* is noise to be tolerated or avoided. But in ME/CFS — where receptor populations may be desensitized, absent, autoantibody-blocked, or supersensitive from chronic deficiency — this polarity can invert. The side effect may be the primary diagnostic signal, revealing which systems are intact enough to react. The therapeutic effect may be irrelevant, not because the drug failed, but because the target system is too damaged to produce a response in either direction.

==== The Principle

Every medication produces two signals:

#strong[Signal 1 — Therapeutic:] Does the drug produce its intended clinical effect? This tells you whether the target mechanism is *broken enough to be rate-limiting* — if the drug fixes it and the patient improves, the target was a bottleneck. If the drug does nothing, the target is either not rate-limiting or too damaged to respond even when corrected.

#strong[Signal 2 — Side-Effect:] What does the body do in response to the presence of the drug? This tells you whether the responding systems are *intact enough to react* — if a system produces a side effect, it is functional. If it produces an exaggerated side effect, it is supersensitive. If it produces the opposite effect, regulatory polarity is inverted. If it produces no side effect when one is expected, the system is absent, desensitized, or blocked.

In a healthy patient, Signal 1 >> Signal 2 — the therapeutic effect dominates, and side effects are nuisance to be minimized.

In ME/CFS, Signal 2 >= Signal 1 for many drug classes — and for some, Signal 2 is the ONLY informative signal.

==== Classification Rubric: Which Signal Dominates Diagnostics?

For each drug, classify into one of four categories:

| Category | Label | Definition | Diagnostic rule |
|----------|-------|------------|-----------------|
| I | Therapeutic = Primary, Side-Effect = Null | Target mechanism is the diagnostic signal. Responding systems are intact. | If therapeutic effect is present → mechanism confirmed. If absent → mechanism not rate-limiting. Side effects are nuisance, not diagnostic. |
| II | Side-Effect = Primary, Therapeutic = Null | The side-effect signal is the diagnostic signal. The target may be too damaged to produce a therapeutic response. | If side effect is present → the responding system is intact. If expected side effect is absent → the system is damaged (Pattern 5: absent expected side effect). The therapeutic effect may be irrelevant — a null therapeutic response does not rule out the mechanism. |
| III | Both Therapeutic AND Side-Effect Are Diagnostic Each provides orthogonal information. | Full bidirectional probe — the therapeutic response localizes the lesion, the side-effect profile maps the surrounding systems. | Both signals are tracked. Response without expected side effect = important dissociation. Side effect without therapeutic response = the responding system is intact but the target is either not the bottleneck or is too damaged for the drug to fix. |
| IV | Neither Signal Is Diagnostic | The drug's binding does not interact with a system that is damaged or rate-limiting in ME/CFS. | Null results across both signals are non-informative. |

==== Mechanism-Family Matrix: Which Signal Dominates for Each Drug Class

The classification depends on which mechanism family the drug targets — and what ME/CFS does to that family's receptors and downstream effectors. The matrix below is organized by mechanism family, with drugs grouped under the family whose receptor state determines the dominant signal.

*Mechanism Family 1 — Dopaminergic:* Chronic dopamine deficiency in ME/CFS produces D2/D3 receptor supersensitivity (upregulation from low tonic dopamine). The receptors are hypersensitive — any D2/D3 agonist or partial agonist will produce an exaggerated side effect at a dose that should be subclinical. This receptor state makes the side-effect signal dominant.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| Aripiprazole/LDA (0.25--2 mg) | II | Cognitive improvement → D2/D3 system is rate-limiting for cognition (certainty: Medium). Null is ambiguous — the receptor could be functional but D2/D3 is not the cognitive bottleneck, or receptors are desensitized. | Akathisia at microdose → D2/D3 supersensitivity confirmed (certainty: High — the side effect at 0.25--0.5 mg is diagnostic irrespective of whether the drug works for cognition). No akathisia at any dose → D2/D3 receptors are desensitized, absent, or blocked (Pattern 5). No akathisia BUT drug works for cognition → dissociation — D2/D3 signalling in ventral striatum is distinct from prefrontal D2/D3; striatal D2 is desensitized, prefrontal D1/D3 is intact. | The side-effect signal is the diagnostic signal. The therapeutic response tells you whether dopamine is a cognitive bottleneck; the side effect tells you whether D2/D3 receptors exist at all. The side-effect signal carries higher certainty. |
| Pramipexole (0.125--0.25 mg) | II | RLS relief → D2/D3 postsynaptic intact (certainty: Medium). Null → D2/D3 not rate-limiting for RLS, or receptors desensitized. | Nausea at RLS dose → area postrema D2/D3 supersensitivity confirmed (certainty: High). Dizziness at RLS dose → cardiovascular D2/D3 supersensitivity confirmed. Neither → D2/D3 too damaged to respond (Pattern 5). Nausea without dizziness → dissociation (area postrema D2 intact, cardiovascular D2 desensitized). | Same logic as aripiprazole. The side-effect profile at subclinical doses IS the receptor-function assay. |
| Methylphenidate, Amphetamines | III | Cognitive/energy benefit → DA/NE deficiency confirmed (certainty: Medium--High if response is robust). Null → DA/NE not rate-limiting, or terminals depleted beyond what reuptake inhibition can salvage. | Tachycardia ceiling → NE-responsive cardiovascular system intact (Pattern 4). Crash → DA depletion confirmed (VMAT2 terminal compromise). Insomnia → orexin-histamine axis is DA-sensitive. All three are diagnostic. | Both signals carry orthogonal information. The therapeutic response tells you whether DA/NE is the bottleneck; the side-effect ceiling tells you which supporting system has the least reserve. |
| Amantadine, L-DOPA, Selegiline/Rasagiline | III | Therapeutic response → presynaptic DA system is the bottleneck (certainty: Medium). Null → lesion not at DA release/synthesis/degradation. | Side effects reveal whether: (a) D2/D3 receptors exist (nausea from L-DOPA), (b) peripheral sympathetic system has reserve (livedo from amantadine), (c) NMDA system has reserve (confusion from amantadine), (d) serotonergic system is fragile (serotonin syndrome from MAO-B inhibitor). | Both signals are diagnostic. |

*Mechanism Family 2 — Noradrenergic/Adrenergic:* The noradrenergic system has two subtypes — hyperadrenergic (chronic NE overstimulation → α1/α2 desensitization) vs. neuropathic (sympathetic denervation → α1 supersensitivity). Which subtype a patient has determines which drug produces which side-effect signal.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| Midodrine (2.5--10 mg) | II, with subtype-dependent dominance | BP/orthostatic improvement → α1 receptors are present and functional (certainty: Medium). Null → α1 absent, blocked (GPCR AAb), or orthostatic intolerance is not hypovolemic/neuropathic. | Severe hypertension at 2.5 mg → α1 denervation hypersensitivity confirmed (neuropathic POTS — certainty: High). No piloerection → length-dependent sympathetic neuropathy (certainty: Medium--High). No BP response → α1 absent or autoantibody-blocked (Pattern 5). | The side-effect signal is the primary diagnostic signal. The therapeutic response is downstream of what the side effect already revealed. |
| Clonidine (0.05--0.1 mg) | II | Central sympathetic suppression → sympathetic drive confirmed as load-bearing (certainty: Medium). Controlled HR/BP reduction → some sympathetic reserve. | Hypotensive crash at 0.05 mg → minimal sympathetic reserve (certainty: High — the dose at which BP drops is an ordinal readout of sympathetic reserve). No BP change at 0.1 mg → α2 autoreceptors desensitized (hyperadrenergic POTS — certainty: High). | The side-effect signal is the diagnostic signal. The therapeutic effect is secondary — the drug is primarily a probe, not a treatment. |
| Prazosin (0.5--1 mg) | II | Glymphatic improvement (morning symptom reduction) → NE-mediated vasoconstriction was suppressing glymphatic flow (certainty: Low--Medium). Null → glymphatic impairment is not NE-driven, or prazosin dose insufficient. | Severe OH at 0.5 mg → standing BP depends on α1-mediated vasoconstriction (neuropathic POTS — certainty: High). No OH at 1 mg → BP is not α1-dependent (hyperadrenergic POTS or adequate reserve). | The side-effect signal is the primary diagnostic signal. The glymphatic therapeutic effect is what the patient wants, but the OH at microdose is what tells the doctor which POTS subtype the patient has. |
| Beta-blockers | III | HR reduction without fatigue worsening → sympathetic overactivation isolated to HR (certainty: Medium). Null → HR is not sympathetically driven (SA node dysfunction). | Fatigue worsening beyond HR-matched ivabradine → β2-AR-mediated lipolysis was metabolic fallback (certainty: Medium--High). Implies PDH/ETC glucose-to-ATP impairment. | Both signals are diagnostic and orthogonal. |
| Droxidopa | III | Orthostatic improvement → NE synthesis capacity intact and rate-limiting (certainty: Medium). Null + midodrine works → presynaptic NE synthesis/storage deficit. | Supine hypertension without orthostatic benefit → postsynaptic vasculature desensitized (hyperadrenergic POTS — certainty: Medium). | Both signals differentiate presynaptic vs. postsynaptic lesions. |
| Atomoxetine, Solriamfetol | III | Cognitive benefit → NE deficiency confirmed, prefrontal α2A intact (certainty: Medium). Null cognitive benefit with BP/HR increase → prefrontal α2A desensitized. | BP/HR increase without cognitive benefit → NE is available at the synapse but prefrontal cortex cannot use it (α2A desensitization — certainty: Medium). | The dissociation between therapeutic and side-effect signals IS the diagnostic finding. |

*Mechanism Family 3 — Cholinergic:* Acetylcholine receptors (muscarinic, nicotinic) can be supersensitive from denervation or desensitized from autoantibody blockade. The gut cholinergic system is the most accessible readout.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| Pyridostigmine (30--60 mg) | II | POTS symptom improvement → cholinergic signaling intact at autonomic ganglia (certainty: Medium). Null → vagal efferent pathway non-functional, or AChE not rate-limiting. | Severe GI cramping/diarrhea at 30 mg → gut muscarinic hypersensitivity from enteric denervation (certainty: High). No GI effects at 60 mg → gut muscarinic receptors desensitized or absent (Pattern 5). No HRV improvement + GI effect → cholinergic system intact at gut but not at heart — denervation pattern is tissue-specific. | The side-effect signal is the diagnostic signal. The therapeutic response for POTS tells you whether cardiac vagal tone is improvable; the GI side effect tells you whether muscarinic receptors exist at all. |

*Mechanism Family 4 — Opioid and TLR4:* LDN is the probe. Two competing mechanisms — opioid receptor blockade → endorphin upregulation (therapeutic) vs. TLR4 antagonism → microglial suppression (therapeutic). The side-effect signal tells you which mechanism dominates and whether opioid receptors are functional.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| LDN (0.5--4.5 mg) | II | Symptom improvement → neuroinflammation/TRPM3 present (certainty: Medium). Null → TLR4/opioid systems not rate-limiting. Note: therapeutic response cannot distinguish opioid vs TRPM3 mechanism. | Sedation at low dose → orexin system critically low (certainty: High). Dysphoria/depression → opioid-dependent homeostasis confirmed (certainty: High — the "paradoxical reactor" phenotype for opioid systems). No response to either → TLR4 and opioid systems both non-functional or non-contributory (Pattern 5). | The side-effect signal is the diagnostic signal for LDN. A patient who gets dysphoria at 0.5 mg has told you more about their opioid system than any therapeutic response could. |

*Mechanism Family 5 — Histaminergic:* H1 and H2 receptors can be desensitized (chronic mast cell histamine exposure), supersensitive (histaminergic insufficiency), or paradoxically inverted (CNS histamine dysregulation). The side-effect signal IS the receptor-function assay.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| H1 antihistamines (cetirizine, fexofenadine, etc.) | II | MCAS symptom reduction → peripheral mast cell histamine is rate-limiting for flushing/pruritus/GI (certainty: Medium). Null → mast cells not rate-limiting, or histamine is not the dominant MCAS mediator (leukotrienes, prostaglandins). | No sedation at 4× dose → CNS H1 receptors desensitized from chronic mast cell histamine exposure (MCAS with CNS involvement — certainty: High). Dose-dependent somnolence → H1 receptors intact, MCAS is peripheral-only. | The side-effect signal (sedation or its absence) is the primary diagnostic signal — it tells you whether CNS H1 receptors exist and are functional, which determines whether MCAS is CNS-involved. |
| Ketotifen | II | MCAS improvement → mast cell degranulation rate-limiting (certainty: Medium). Null → mast cells not rate-limiting. | Severe sedation at 0.5 mg → histaminergic wakefulness depends on mast-cell-derived histamine; the patient is "held awake" by their MCAS (certainty: High). MCAS improvement without sedation → H1 receptors intact but ketotifen benefits via mast cell stabilization, not H1 block. | The side-effect signal dominates — sedation at 0.5 mg diagnoses CNS MCAS involvement more precisely than any MCAS lab test. |
| Doxepin (3--6 mg, pure H1 antagonist) | II | Improved sleep maintenance → histaminergic arousal is the dominant cause of awakenings (certainty: Medium). Null → awakenings are non-histaminergic (orexin, adrenergic, pain). | Next-day sedation at 3 mg → H1 supersensitivity from histaminergic insufficiency (certainty: High). No next-day sedation → H1 desensitized from chronic histamine exposure. | The side-effect signal (next-day sedation at microdose) is the primary diagnostic signal. |
| Pitolisant (H3 inverse agonist) | III | Cognitive/mast-cell improvement → histaminergic anti-inflammatory mechanism (M1→M2 switch) confirmed (certainty: Medium). Null → histaminergic system not the bottleneck. | Insomnia ceiling → histaminergic system is on a hair trigger (orexin-suppression model) — certainty: High. Headache ceiling → histamine-mediated vasodilation (MCAS vascular hyper-reactivity). | Both signals are diagnostic and orthogonal. |
| Famotidine/Cimetidine | II | MCAS/GI improvement → H2-mediated gastric histamine or T-cell modulation (cimetidine) rate-limiting (certainty: Low—Medium). Null → H2 not rate-limiting for GI or systemic MCAS. | Depression/suicidal ideation → paradoxical reactor phenotype extended to histaminergic system (certainty: High — the side effect is a permanent trait marker). The dissociation (famotidine depression but not cimetidine, or vice versa) distinguishes off-target from class effect. | The side-effect signal is the primary diagnostic signal — and the most clinically important one, since it identifies a permanent contraindication. |

*Mechanism Family 6 — GABAergic:* The GABA-A system in ME/CFS may have chloride gradient inversion (NKCC1/KCC2 imbalance) from neuroinflammation, making GABA excitatory rather than inhibitory. The side effect IS the polarity assay.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| Z-drugs (zolpidem, eszopiclone) | II | Sleep initiation → GABA-A α1 functional and PAM-responsive (certainty: Medium). Null → sleep-onset insomnia is not GABA-A α1-mediated. | Paradoxical excitation/complex sleep behaviours → GABAergic inversion confirmed (NKCC1/KCC2 imbalance — certainty: High). Absent expected amnesia → hippocampal GABA-A α1 desensitized. Normal sedation + amnesia → GABA-A α1 intact. | The side-effect signal IS the diagnostic signal. A patient who gets paradoxical excitation from zolpidem has just had their chloride gradient tested without an invasive procedure. No GABA-A PAM should ever be prescribed to this patient. |
| Benzodiazepines | II | Anxiety reduction → GABA-A functional (certainty: Medium). Null → GABA-A not rate-limiting for anxiety, or GABAergic inversion limits response. | Paradoxical excitation → same GABAergic inversion mechanism as Z-drugs (certainty: High). Severe sedation at minimal dose → GABA-A hypersensitivity (consistent with low GABAergic tone from interneuron dysfunction). | Same polarity assay as Z-drugs. |

*Mechanism Family 7 — NMDA/Glutamatergic:* NMDA receptor tone in ME/CFS may be globally low (kynurenic acid dominance) or regionally excessive (quinolinic acid excitotoxicity). The side effect distinguishes which.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| Memantine | II | Cognitive improvement → NMDA excitotoxicity rate-limiting (certainty: Low—Medium). Null → NMDA not the cognitive bottleneck. | Sedation/brain fog at low dose → basal glutamate tone globally low (kynurenic acid dominance, not quinolinic acid excess — certainty: High). No sedation at therapeutic dose → adequate glutamatergic reserve. | The side-effect signal distinguishes KYNA dominance from QUIN excess — a distinction no lab test can make. |
| Ketamine (0.1--0.5 mg/kg) | II | Rapid pain relief → QUIN-driven NMDA excitotoxicity rate-limiting for pain (certainty: Medium). Rapid mood improvement → mTORC1/BDNF synaptogenesis, not NMDA block. | Psychotomimetic at 0.1 mg/kg → severe NMDA hypofunction (KYNA dominance confirmed — certainty: High). The dissociation at sub-anesthetic dose IS the NMDA-tone assay. | The psychotomimetic side effect is the primary diagnostic signal. Pain relief without psychotomimesis tells you the opposite (QUIN excess). Null for all → NMDA not rate-limiting. |
| Amantadine (100 mg) | II | Cognitive/energy benefit → presynaptic DA release bottleneck (certainty: Medium). | Confusion at 100 mg → NMDA hypofunction confirmed (same pattern as ketamine sensitivity — two structurally different NMDA antagonists produce the same cognitive ceiling at subtherapeutic doses — certainty: High). | NMDA side-effect signal dominance for the NMDA component, Category III for the DA component. |

*Mechanism Family 8 — Mast Cell (MCAS):* Mast cells release histamine, prostaglandins, leukotrienes, and tryptase. Different drugs probe different mediators. The side-effect signal identifies which mediator dominates.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| Niacin (50--500 mg) | II (pure probe) | No therapeutic indication for niacin at these doses for MCAS. | Severe flush at 25--50 mg → dermal mast cell PGD2 hyper-reactivity (severe cutaneous MCAS — certainty: High). No flush at 500 mg → HCA2 desensitization or PGD2 synthase deficiency. Flush prevented by aspirin → confirms PGD2 pathway. Flush prevented by antihistamines → histamine-mediated MCAS, not PGD2. | Niacin is a pure side-effect probe. It has no therapeutic indication as an MCAS probe — the side effect IS the entire diagnostic signal. |
| Aspirin (low-dose) | II | Anti-inflammatory/pain benefit → COX-1/COX-2-driven inflammation rate-limiting (certainty: Medium). | Worsening MCAS symptoms → prostaglandin-mediated mast cell stabilization was active; removing it unmasks MCAS (certainty: High). No MCAS worsening → prostaglandin-independent MCAS. | The side-effect signal IS the diagnostic signal. A patient whose MCAS worsens on aspirin has just confirmed their mast cells are prostaglandin-buffered. |
| DMF (dimethyl fumarate) | II | Nrf2 activation → antioxidant benefit (certainty: Medium). Null → Nrf2 not rate-limiting. | Severe flushing at 120 mg → mast cell hyper-reactivity confirmed (certainty: High). Flushing prevented by aspirin → confirms PGD2-mediated MCAS. | The flushing side effect is the MCAS probe; the Nrf2 therapeutic effect is a separate diagnostic axis. |

*Mechanism Family 9 — Glutathione/Nrf2/Oxidative Stress:* The side-effect signal reveals which downstream system is the bottleneck in the redox cascade.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| NAC (600--1,200 mg) | II | Reduced oxidative stress → glutathione synthesis rate-limiting (certainty: Low—Medium). Null → GSH system not rate-limiting, or cysteine is diverted to other pathways. | Worsening fatigue at 600 mg → thiol-radical burst exhausts GSH before synthesis, OR cysteine diverted from transsulfuration (H₂S vasodilation lost), OR copper chelation impairs DBH (certainty: Medium—High for each). Worse at 600 mg, better at 1,200 mg → initial radical burst cleared by higher GSH synthesis — confirms high oxidative stress AND functional GSH machinery. Worse at all doses → chronic thiol stress or H₂S pathway dependence. | The side-effect signal is the primary diagnostic signal. A patient who gets worse at 600 mg and better at 1,200 mg has confirmed their oxidative stress level and GSH synthesis capacity simultaneously. |

*Mechanism Family 10 — Mitochondrial:* Energy substrate supplementation can produce worsening if the ETC bottleneck is downstream of the supplemented node. The side-effect signal maps the block site.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| CoQ10, NADH, L-carnitine, D-ribose | II | Improved energy → supplemented node was rate-limiting (certainty: Low—Medium for any single supplement). Null → node not rate-limiting (most common outcome; non-informative). | Worsening, not improvement → downstream ETC block confirmed (certainty: Medium--High). CoQ10 worsen → Complex III block. NADH worsen → Complex I functional, Complex III+ blocked. Carnitine worsen → lipid peroxide overload. The pattern of which supplement worsens and which doesn't maps the ETC block site. | The side-effect signal dominates diagnostic yield. Therapeutic null is common and non-informative because the bottleneck is rarely at the node being supplemented. Worsening is rare but highly informative. |

*Mechanism Family 11 — Orexin/Arousal:* The orexin system in ME/CFS may be suppressed (microglial inflammation → orexin neuron inhibition) or desensitized from chronic compensatory activation. The side-effect signal reveals which.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| DORA (daridorexant, suvorexant) | II | Improved sleep maintenance → pathological nocturnal orexin surges suppressed (certainty: Medium). Null → orexin-driven awakenings not the mechanism, or orexin tone already at floor. | Sleep paralysis at low dose → orexin tone critically low (certainty: High — borderline narcolepsy-level deficiency). No effect on sleep → orexin tone already at floor. No sleep paralysis + improved maintenance → orexin tone normal. | The side-effect signal (sleep paralysis at microdose) IS the orexin-tone assay. The therapeutic effect is secondary. |
| Modafinil/Armodafinil | III | Cognitive benefit → DA deficiency confirmed (certainty: Medium). Null → DAT dysfunctional. | Insomnia ceiling → orexin/histamine axis intact + DA-sensitive. Next-day fatigue → energy reserve is bottleneck, not arousal. No insomnia at 200 mg → orexin/histamine axis desensitized (consistent with orexin suppression model). | Both signals are diagnostic and orthogonal. |

*Mechanism Family 12 — Autoimmune (GPCR AAb, B-cell, Plasma-cell):* Immune-modulating drugs produce a response pattern that distinguishes AAb subtype, B-cell vs. plasma-cell source, and complement involvement.

| Drug | Category | Signal-1 (Therapeutic) | Signal-2 (Side-Effect — dominant) | Reasoning |
|------|----------|------------------------|----------------------------------|-----------|
| IVIG | II | Sustained improvement → circulating IgG AAb present + rate-limiting (certainty: Medium). Null → AAb absent or not rate-limiting, or profound immune exhaustion. | Transient flare (48--72h) → confirms AAb neutralization + complement activation (certainty: High — the flare IS the diagnostic signal). Flare >7 days → complement-MCAS amplification loop. No flare + no response → no AAb, or immune exhaustion. | The side-effect signal is the primary diagnostic signal. The flare confirms AAb presence more directly than the therapeutic response — the body is mounting a reaction to the neutralized immune complexes. |
| Rituximab | III | Response → AAb from dividing plasmablasts (certainty: Medium). Null → AAb from long-lived plasma cells (rituximab-spared), or AAb not rate-limiting. | Infusion reactions → intact immune recognition. Transient response (weeks → relapse) → B-cell repopulation re-drives AAb. | Both signals contribute. The null/non-null distinction for rituximab vs. IVIG vs. daratumumab distinguishes plasmablast vs. plasma-cell AAb source. |
| BC007, Immunoadsorption | III | Response → GPCR AAb present and rate-limiting (certainty: Medium--High if response is robust). Null → AAb absent or not rate-limiting. | BC007 working where IA fails → AAb subtype not removed by protein A columns (IgG3, IgA). IA working where BC007 fails → AAb target not among BC007's known aptamers. | Both signals are diagnostic. |

==== The Fifth Diagnostic Pattern as a Category II Sentinel

Note that Pattern 5 — *absence of an expected side effect* — is the most information-dense signal in the entire framework, and it is almost exclusively a Category II phenomenon (Side-Effect = Primary). When a drug that *should* produce a side effect produces none, the responding system is too damaged to react. This is the body's silence as diagnostic data:

- Midodrine producing no piloerection → cutaneous α1 receptors denervated (length-dependent sympathetic neuropathy). The body cannot produce goosebumps — and that inability is the diagnosis.
- Antihistamines producing no sedation → CNS H1 receptors desensitized from chronic mast cell histamine exposure. The body is so accustomed to high histamine that blocking it produces no perceptible change.
- Caffeine producing no tachycardia → central sympathetic activation failure. The CNS cannot mount a catecholamine response to adenosine blockade.
- Droxidopa producing no orthostatic improvement → AADC deficiency or VMAT2 terminal loss. The precursor arrives but cannot be converted or stored.
- Pramipexole producing no nausea or dizziness → D2/D3 receptors in area postrema and cardiovascular centres are too damaged to respond. The drug that reliably causes nausea in healthy and Parkinson's patients is inert in this patient — and that inertness is the most specific diagnostic finding the drug can provide.

In each case, the *lack* of the drug's most reliable and universal side effect is a higher-certainty diagnostic finding than any therapeutic response could produce. A null therapeutic response has many possible explanations (wrong dose, wrong duration, mechanism not rate-limiting, individual metabolism). An absent universal side effect has far fewer: the responding system is absent, desensitized, or blocked.

==== Practical Clinical Integration

For every new medication trial, patients and clinicians should record two questions with equal weight:

#strong[Before each trial:] For this drug, which signal is Category I (therapeutic = primary), II (side-effect = primary), or III (both)?

#strong[After each trial:] Record both: (1) Did the therapeutic effect occur? At what dose? (2) Did the expected side effects occur? At what dose? Which expected side effects were ABSENT?

The side-effect profile — including the silences — is as much a part of the diagnostic record as the therapeutic response. A patient who has tried 10 medications has generated 20 signals (10 therapeutic, 10 side-effect profiles), not 10. A patient whose records show "LDN: did not help" has discarded diagnostic information. The same patient whose records show "LDN: no therapeutic response. ALSO no sedation, no dysphoria, no GI effects, no sleep changes at any dose up to 4.5 mg" has generated a high-certainty finding: their TLR4 and opioid systems are either non-functional or non-contributory — both receptors must be non-responsive for neither agonism nor antagonism to produce any perceptible effect.

This is the Ligand-Receptor Duality in practice: the drug is two probes, not one. The patient's body is the assay. And in ME/CFS — where the readout systems may be damaged in ways that conventional medicine has no other way to measure — the side effect may be the most valuable diagnostic test the patient ever undergoes.

*Consequence:* Every medication section in this paper's treatment chapters should, where applicable, include a Ligand-Receptor Duality classification (Category I--IV) for that drug in ME/CFS, specifying which signal carries the diagnostic information and why. The classification should cite the relevant mechanism family from the matrix above.

*Certainty: 0.25.* The Ligand-Receptor Duality is a conceptual meta-framework for organizing the existing five diagnostic patterns (Patterns 1--5). It introduces no new empirical claims — it is a reclassification of existing pharmacodiagnostic logic under a unified principle. The Category assignments for each drug are derived from the mechanistic reasoning embedded in Patterns 1--5, which themselves carry certainty = 0.30. The meta-framework inherits this certainty and applies an additional 0.05 discount for the abstraction layer between principle and specific drug assignments. No formal validation of the classification rubric against clinical data has been performed; the rubric is offered as a tool for structuring diagnostic reasoning, not as a validated diagnostic instrument.

*Origin:* mechanisms-of-action framework, user-specified conceptual framing, 2026-07-26.
