#import "../../../shared/environments.typ": *

#open-question(title: [Epigenetic Consolidation: A Major Therapeutic Gap])[
Of all documented ME/CFS mechanisms, epigenetic consolidation has the fewest targeted treatment options. No approved therapy has been tested for its epigenetic effects in ME/CFS. Rapamycin and spermidine have relevant mechanisms but have not been studied in this context. The causal role of epigenetic changes in ME/CFS remains unproven — observed methylation differences @Trivedi2018methylation are cross-sectional and could be consequences rather than causes of disease.

The gain-vs-loss tension that previously divided the paper's model has been resolved by the unified per-locus vector model in Chapter @ch:causal-hierarchy-formal (@oq:consolidation-directionality). ME/CFS shows bidirectional methylation alterations: some loci hypermethylated, others hypomethylated. The vector model captures both via $bold(cal(M)) in [0, 1]^n$, with consolidation depth $||bold(cal(M)) - bold(cal(M))^"baseline"||$. In cancer, global DNMT3B redistribution (ProB → ProA/gene-region) produces both patterns simultaneously, making gain and loss complementary manifestations. For ME/CFS, the proposed mechanism is more targeted: HSAT2-specific loss-meCpG with loss of DNMT3B activity as a consequence of HSAT2 activation rather than global enzymatic redistribution (Geneviève Fourel, pers. comm. May 2026). The therapeutic implication is locus-dependent:

- *Loss-dominant patients* ($||bold(cal(M))_"ProB" - bold(cal(M))_"ProB"^"baseline"||$ dominant): Remethylation strategies (DNMT3B activators, methyl donor support with SAMe, methyl-folate, methyl-B12, betaine). Demethylating agents (5-azacitidine, HDAC inhibitors, TET activators) are contraindicated — they would worsen existing hypomethylation at ProB repeats.
- *Gain-dominant patients* ($||bold(cal(M))_"ProA" - bold(cal(M))_"ProA"^"baseline"||$ dominant): Energy restoration → passive demethylation after inflammation resolves.
- *Mixed* (most typical): Methyl-donor support (low-risk default) plus energy restoration. Locus-specific targeting (remethylation at ProB repeats + demethylation at hypermethylated promoters) is the principled ideal but requires pharmacological tools that do not yet exist.

Methyl-donor support (SAMe, methyl-folate, methyl-B12, betaine) represents the safest default strategy for all patients pending per-locus methylation profiling, since methyl donors support both methylation maintenance (preventing further ProB erosion, no harm at hypermethylated loci) and de novo remethylation at hypomethylated loci (potential benefit). Efficacy for ME/CFS symptoms remains unproven. For the full formal treatment including the DNMT3B zero-sum constraint ($sum_i Delta m_i = 0$), the irreversibility threshold $m_i^"crit"$, the $B_"strength"$ derived variable, and tissue/cell-type considerations, see Chapter @ch:causal-hierarchy-formal @oq:consolidation-directionality.

*Provisionality.* The ProA/ProB repeat framework @BonnetFourel2026ProAB is a preprint, developed in cancer, not peer-reviewed. Its extension to ME/CFS is our extrapolation, not endorsed by those authors.
] <oq:epigenetic-gap>
