#import "../../shared/environments.typ": *

= Economic Impact of ME/CFS
<ch:economic-impact>

#chapter-abstract[
Direct costs (medical visits, tests, medications, alternative treatments), indirect costs (lost earnings, reduced work hours, early exit from workforce), caregiver economic burden, lifetime cost estimates per patient, cost-effectiveness of proper diagnosis vs. misdiagnosis cycling, economic case for increased research funding (ROI analysis), and occupational consequences (>75% unemployment rate, workplace accommodations, disability systems). The evidence is descriptive and cross-sectional — cost-of-illness surveys, administrative data, systematic reviews, and government reports — with zero cost-effectiveness studies of any ME/CFS care model.

*Consequence:* This chapter provides the quantitative foundation for the argument that ME/CFS is a severe economic disease, not just a severe clinical one. The numbers that follow are not abstractions — they represent years of lost earnings, families forced into poverty, and caregivers who cannot work. They establish the economic dimension of neglect.
]

== The Scale of the Problem

ME/CFS imposes economic costs that are systematically underestimated, because the disease itself is systematically underdiagnosed. An estimated 84--91% of U.S. patients remain undiagnosed @IOM2015 — every cost estimate in this chapter is therefore a lower bound, capturing only the visible fraction of the disease's economic footprint.

#achievement(title: [The IOM 2015 Economic Benchmark])[
The 2015 Institute of Medicine report established the baseline: 836,000 to 2.5 million Americans affected, with annual economic costs of USD 17--24 billion, including USD 9.1 billion in lost household and labor-force productivity @IOM2015. This represented USD 18,000--29,000 per patient per year, with indirect costs (lost earnings, reduced work hours, informal care) accounting for approximately two-thirds of the total. The IOM estimate remains the most widely cited single number for U.S. ME/CFS economic burden, though it is a modeled extrapolation from prevalence surveys and cost data, not a direct measurement from claims or administrative databases. (Certainty: 0.77 — government report by National Academies; modeled estimate, not direct cost measurement; extrapolated from survey data. IOM + Clayton 2015 summary share the same evidence base — treated as one source.)

*Consequence:* The USD 17--24 billion figure — even treated as a lower bound — places ME/CFS in the same economic tier as well-recognized chronic diseases. For a policymaker deciding where to allocate research funding, this number should trigger the same institutional response as the economic burden of multiple sclerosis or rheumatoid arthritis. It has not. Severity applicability: the cost estimate does not stratify by severity; indirect costs are likely underestimated for severe/very severe patients whose caregivers face the highest economic burden.
] <ach:iom-benchmark>

#achievement(title: [Australian Cost-of-Illness Confirmation])[
Australian cost-of-illness studies independently confirm the IOM magnitude and extend it with direct patient-level measurement. Zhao et al. (2023) estimated AU\$14.5 billion in total annual costs (AU\$28,800 per patient), with indirect costs dominating — lost productivity, informal care, and reduced workforce participation @Zhao2023AustralianBurden. Close et al. (2020), using a separate Australian cohort (n=485), found mean annual costs of AU\$14,523 per patient, with 73% attributable to indirect costs and only 16.6% of patients employed @Close2020AustralianEconomic. The convergence of two independent Australian studies — different samples, different years, different methodologies — with the IOM U.S. estimate suggests the economic burden is not a methodological artefact of any single study. (Certainty: 0.70 — two independent cost-of-illness studies with convergent estimates; both cross-sectional; n=128 + n=485; Australian data, not U.S. claims-based.)

*Consequence:* Cross-national replication of the cost magnitude strengthens the case that ME/CFS is inherently expensive — not expensive because of any country's specific healthcare or disability system. The disease's cost structure (indirect costs >> direct costs) is consistent across countries, consistent with a disease that removes people from the workforce at high rates and provides them with few effective medical treatments. Severity applicability: neither Australian study stratified costs by severity; the 16.6% employment rate may not generalize to mild patients who continue working part-time.
] <ach:australian-costs>

#achievement(title: [KCE Belgium Population-Level Confirmation])[
The KCE Belgian ME/CFS needs assessment (Cornelis et al. 2026, n=749 survey + 19 qualitative interviews) provides the most recent population-level economic data from a government HTA agency. Mean duration of work invalidity: 8.6 years. 73.2% of patients had at least one comorbidity. Diagnostic delay exceeded 2 years for 50% of patients @Cornelis2026KCE420 @Cornelis2026KCE420S. The KCE report is significant not for any single number but because a government health technology assessment body — whose output typically informs reimbursement and care-pathway decisions — conducted a formal needs assessment for ME/CFS, implicitly recognizing it as a condition warranting systematic health-economic evaluation. (Certainty: 0.68 — government HTA report; survey + qualitative; Belgium-specific; cross-sectional.)

*Consequence:* When a government HTA agency formally evaluates ME/CFS, it signals institutional recognition that the disease is a legitimate object of health-economic analysis. The 8.6-year mean work invalidity duration translates directly to lost tax revenue, increased disability payments, and reduced household economic security — consequences that accrue to the state, not just the patient. Severity applicability: KCE weighted toward moderate/severe patients (survey methodology); mild patients underrepresented; very severe patients — who cannot complete surveys — entirely absent.
] <ach:kce-belgium>

== Employment and Occupational Consequences

The single most economically destructive feature of ME/CFS is its impact on employment. Across every study and every country, ME/CFS patients are employed at rates far below the general population, and the gap represents decades of lost earnings, lost tax revenue, and lost productive contribution.

#achievement(title: [The Employment Gap])[
Employment rates for ME/CFS patients range from 16.6% (Close et al. 2020, Australia, n=485) to 27% (Jason et al. 2020, U.S. estimate) @Close2020AustralianEconomic @Jason2020economic. Bowden et al. (2026), using New Zealand's Integrated Data Infrastructure (n=1,902 ME/CFS patients on health/disability benefits), found 18.3% employment among benefit recipients versus 83.8% in the general population — a 65.5 percentage point gap @bowden2026mecfslabourmarket. Castro-Marrero et al. (2019) found 52.3% unemployment and 45.3% on sick leave in a Spanish cohort @CastroMarrero2019employment. The disability determination systems that adjudicate claims for this population are structurally mismatched to ME/CFS pathophysiology (see @ch:healthcare-systems-policy for the systemic analysis). The most commonly cited summary figure — >75% of ME/CFS patients unable to work — comes from Podell et al. (2020) @Podell2020, a practice guide co-authored by clinicians and an attorney specializing in disability claims. (Certainty: 0.75 — multiple independent studies across four countries, consistent direction. All cross-sectional; employment defined differently across studies; selection bias toward more severely affected patients in clinical cohorts; Bowden 2026 limited to benefit recipients and may overstate employment gap for the full ME/CFS population.)

*Consequence:* If 75% of ME/CFS patients cannot work, and employment among the non-ME/CFS population is approximately 60–84%, then ME/CFS strips approximately 50 percentage points from the employment rate of those it affects. Across 1–2.5 million U.S. patients, this represents 500,000–1.25 million people removed from the workforce — a macroeconomic effect, not a personal misfortune. The employment data is the mechanism behind the indirect-cost dominance in every cost-of-illness study: the disease is expensive because it stops people from earning, not primarily because it generates medical bills. Severity applicability: employment rates vary by severity — mild patients may continue working part-time or with accommodations; moderate patients are substantially affected; severe patients are almost uniformly unable to work; very severe patients are not captured in any employment survey because they cannot participate in research.
] <ach:employment-gap>

#open-question(title: [Employment Retention Interventions])[
No study has tested whether workplace accommodations, flexible scheduling, remote work, or phased return-to-work programs reduce the rate at which ME/CFS patients exit the workforce. The literature documents the exit — it does not test interventions to prevent it. The research gap is not methodological; it is institutional. No funding body has prioritized employment retention in ME/CFS as a research question. (Certainty: 0.55 — absence of evidence, not evidence of absence. The intervention question is well-defined and testable with existing employment-support frameworks adapted for PEM.)

*Consequence:* Employers, disability insurers, and policymakers currently operate in an evidence vacuum. A human resources department deciding whether to offer a ME/CFS-affected employee remote work has no data on whether this accommodation reduces the probability of permanent workforce exit — even though the economic stakes are high (one prevented exit = decades of preserved earnings). The absence of this research is itself an economic cost. Severity applicability: mild-to-moderate patients are the primary target for employment retention interventions; severe patients are usually already out of the workforce; very severe patients are not the intervention target.
] <oq:employment-retention>

== Caregiver Economic Burden

The economic cost of ME/CFS extends beyond the patient to family members who reduce their own work hours, leave the workforce, or become informal caregivers — often without compensation, training, or support.

#achievement(title: [Family Economic Impact])[
Brittain et al. (2021), using the FROM-16 family impact tool, found that 87% of family members of ME/CFS patients reported moderate-to-severe impact on their own quality of life, and 50.2% reported reduced family income following the patient's diagnosis @Brittain2021FamilyImpact. The Australian cost-of-illness studies include informal care in their indirect cost estimates — the cost of care provided by family members who could otherwise be working @Zhao2023AustralianBurden @Close2020AustralianEconomic. However, no study has produced a standalone monetary valuation of ME/CFS caregiver burden using established health-economic methods (willingness-to-pay, replacement-cost, or opportunity-cost valuation). (Certainty: 0.55 — single family-impact study; n=68 patients + 118 family members; FROM-16 validated but not ME/CFS-specific; no monetary caregiver valuation exists.)

*Consequence:* The caregiver burden is simultaneously the most visible (every patient and family knows it) and the least quantified dimension of ME/CFS economics. The 50.2% income-reduction figure means that ME/CFS often impoverishes two people per patient — the patient and the primary caregiver. This has implications for disability benefit design: a system that assesses only the patient's functional capacity ignores the caregiver's lost income and the household-level economic destruction. Severity applicability: caregiver burden scales with patient severity — a caregiver for a very severe patient provides near-constant care; a caregiver for a mild patient may face only reduced household productivity.
] <ach:caregiver-burden>

== Research Funding Disparity

The economic argument for increased ME/CFS research funding is not that the disease is underfunded in absolute terms — it is that it is underfunded relative to its burden, in a pattern that distinguishes it from every other chronic disease of comparable severity.

#achievement(title: [The Burden-to-Funding Ratio])[
Mirin et al. (2020) compared ME/CFS disease burden (IOM 2015 USD 17--24B estimate, plus DALY-based burden metrics) against NIH research funding (~USD 15M/year) and found a burden-to-funding ratio of approximately 1,000:1 — meaning the disease generates roughly USD 1,000 in economic cost for every USD 1 of NIH research funding @Mirin2020ResearchFunding. By comparison, multiple sclerosis (annual cost USD 39,000--68,000/patient, comparable per-patient to ME/CFS) received ~USD 115M/year in NIH funding — a burden:funding ratio of ~30:1 @Simoens2022MSBurden. Rheumatoid arthritis (annual cost USD 12,000--21,000/patient) received ~USD 86M/year — ratio ~32:1 @Hsieh2020RAburden. The three-order-of-magnitude gap between ME/CFS and comparably burdensome diseases is the strongest single piece of quantitative evidence for research neglect. (Certainty: 0.65 — Mirin 2020 burden side relies on IOM 2015 modeled estimate; funding figures are public NIH data and verifiable; cross-disease comparators are systematic reviews. The ratio's magnitude depends on the burden estimate — if IOM overestimated burden by 2x, the ratio is still ~500:1. The qualitative conclusion — ME/CFS is severely underfunded relative to burden — is robust to plausible variation in the burden estimate.)

*Consequence:* The burden:funding ratio is the chapter's most politically actionable finding. For an NIH program officer, a congressional staffer, or a research charity allocating funds, the phrase \u{201c}1,000:1 cost:funding ratio\u{201d} is a single number that captures the structural neglect. The cross-disease comparators (MS, RA) are critical — they establish that the disparity is not explained by inherent difficulties in studying ME/CFS (MS and RA are also complex, chronic, immune-mediated diseases with no cure) but by a systematic underinvestment that predates and is independent of any scientific challenge. Severity applicability: research funding affects all severity levels, but severe/very severe patients — who have the least capacity to participate in advocacy — are the most affected by funding scarcity, because they have the greatest need for treatment discovery and the least ability to travel to the few existing research centers.
] <ach:burden-funding-ratio>

#limitation(title: [No Formal Return-on-Investment Analysis])[
The burden:funding ratio is a descriptive comparison, not a causal model. It shows disparity but does not answer the policy question: if ME/CFS research funding increased to parity with MS (~USD 115M), what return would that generate? A formal ROI analysis would require: (1) modeling the probability that increased funding yields a disease-modifying treatment within N years, (2) estimating what fraction of the USD 17--24B annual burden such a treatment would eliminate, and (3) discounting future benefits to present value. No such analysis exists for ME/CFS. The Cochrane 2021 systematic review confirmed that zero cost-effectiveness studies exist for any ME/CFS intervention — including research funding itself as an intervention @Cochrane2021CostEffectiveness.

*Consequence:* The burden:funding ratio is persuasive but not probative for a specific funding target. It tells you the present state is unjustified; it does not tell you what funding level would be optimal. In policy contexts, this distinction matters — a cost-effectiveness analyst will ask "what is the marginal return on the next 10 million dollars?" and the current literature cannot answer. This limitation is not a weakness of the case for increased funding; it is a consequence of the same underfunding that the case critiques. (Certainty: 0.75 — confirmed by Cochrane 2021 systematic review @Cochrane2021CostEffectiveness; absence of evidence for ROI of ME/CFS research funding is a documented finding from systematic search, not an assumption.) Severity applicability: the ROI gap affects evidence-based funding advocacy across all severity levels.
] <lim:no-roi>

== Cost-Effectiveness: An Evidence Vacuum

#limitation(title: [Zero Cost-Effectiveness Studies])[
Cochrane et al. (2021) conducted the first and only systematic review of economic evaluations in ME/CFS and found six studies — all based on pre-2021 CBT/GET intervention models, most published before the NICE 2021 guideline reversal that withdrew the GET recommendation @Cochrane2021CostEffectiveness. None evaluated the cost-effectiveness of modern energy-management-based care, specialist ME/CFS clinic models, diagnostic pathways, or pharmacological interventions. After the 2021 NICE reversal, the pre-2021 cost-effectiveness evidence is not just thin — its clinical basis (GET as recommended care) is obsolete. A 2024 bibliometric analysis confirmed the field remains tiny and fragmented, with only 13.8% of health-economics publications on ME/CFS involving international collaboration @Wan2024HealthEconomicsTrends.

*Consequence:* Every claim in this chapter about the economic case for diagnosis, treatment, or research funding rests on burden documentation, not on cost-effectiveness evidence. The distinction is important. A burden study tells you the disease is expensive. A cost-effectiveness study tells you whether spending money on a specific intervention reduces that expense. The first exists for ME/CFS. The second does not — for any intervention. This is the most consequential evidence gap in the chapter, and it flows directly from the research underfunding documented in @ach:burden-funding-ratio. You cannot measure cost-effectiveness without first developing interventions to evaluate. (Certainty: 0.75 — confirmed by Cochrane 2021 systematic review @Cochrane2021CostEffectiveness and Wan 2024 bibliometric analysis @Wan2024HealthEconomicsTrends; absence of post-NICE-2021 cost-effectiveness evidence is a documented finding, not an assumption.) Severity applicability: the cost-effectiveness gap affects evidence-based policy for all severity levels.
] <lim:no-cea>

== Cross-Disease Economic Context

ME/CFS economic burden is best understood not in isolation but in comparison with diseases whose severity, chronicity, and cost structures are comparable — and whose funding levels are not.

Table <!-- cross-disease economic comparison -->:
- *Multiple sclerosis:* Annual per-patient total cost USD 39,000--68,000 (U.S./Europe, varying by disability level); indirect costs 50--75% of total; NIH funding ~USD 115M/year; DMTs exist that modify disease course @Simoens2022MSBurden.
- *Rheumatoid arthritis:* Annual per-patient total cost USD 12,000--21,000 (biologic era, U.S./Europe); indirect costs ~40--60% of total; NIH funding ~USD 86M/year; multiple FDA-approved disease-modifying therapies @Hsieh2020RAburden.
- *ME/CFS:* Annual per-patient total cost USD 18,000--29,000 (U.S. IOM estimate); indirect costs ~66--73% of total; NIH funding ~USD 15M/year; zero disease-modifying therapies.

#speculation(title: [Comparative Neglect as a Structural Phenomenon])[
The cross-disease comparison reveals a pattern that cannot be explained by disease severity, prevalence, or economic burden — because ME/CFS is comparable to MS and RA on all three dimensions and receives 7--13% of their research funding per DALY. The three-order-of-magnitude burden:funding ratio gap is larger than can be explained by any single factor (diagnostic ambiguity, patient advocacy strength, PI pipeline, historical stigma). It likely reflects the interaction of all these factors — a structural neglect that is self-reinforcing: low funding then few researchers then slow progress then perceived as intractable then continued low funding. Breaking this cycle would require a funding intervention at the scale of the NIH's response to HIV/AIDS in the 1980s or to Long COVID in 2020 — a recognition that the funding deficit is not marginal but structural. (Certainty: 0.35 — speculative interpretation of cross-sectional funding data; the self-reinforcing model is plausible but untested; alternative explanations include differences in advocacy infrastructure, disease recognition, and biomarker availability. Origin: synthesis from Phase 2 evidence landscape.)

*Consequence:* If the structural-neglect hypothesis is correct, the policy implication is that incremental funding increases will not close the gap — the neglect is self-stabilizing and requires a step-change intervention to disrupt. If the hypothesis is wrong and the gap reflects legitimate scientific difficulty, then incremental funding increases should produce proportional returns and the hypothesis is falsified by showing that additional ME/CFS funding generates discovery at a rate comparable to MS/RA funding. This is testable with a dedicated ME/CFS research program that includes an explicit evaluation component. Severity applicability: the structural-neglect hypothesis applies to the research enterprise as a whole; its downstream effects are felt most acutely by severe and very severe patients, who have the greatest need for treatment advances.
] <spec:structural-neglect>

== Evidence Gaps and Research Directions

#open-question(title: [The Missing Economic Evidence])[
The ME/CFS economic evidence base has several structural gaps that no single study has addressed:

1. *No U.S. claims-data cost-of-illness study:* The IOM estimate is modeled, not measured. An analysis of Medicare/Medicaid/private-insurer claims for patients with ICD-coded ME/CFS (G93.3) would produce the first direct measurement of U.S. ME/CFS healthcare utilization and costs. This is feasible with existing data.

2. *No longitudinal lifetime-cost study:* All existing cost data are cross-sectional. A cohort study tracking patients from diagnosis through the disease course would capture the temporal pattern of costs — whether they front-load (diagnostic odyssey), plateau (stable disability), or escalate (progressive worsening) — and would inform the timing of interventions.

3. *No cost-effectiveness of the diagnostic pathway:* The economic case for reducing diagnostic delay — that earlier diagnosis prevents inappropriate treatments, reduces healthcare utilization, and preserves employment — is plausible but unquantified. A Markov model comparing diagnosis at 6 months vs diagnosis at 5 years (the current median) would need data on what happens during the 4.5-year gap. Those data do not exist.

4. *No caregiver monetary valuation:* The 50.2% family-income reduction (Brittain 2021) is the closest proxy, but a formal willingness-to-pay or replacement-cost valuation would quantify the caregiver burden in terms that health-economic decision models can use.

5. *No developing-country data:* Every existing study comes from a high-income country. Post-infectious fatigue follows infectious-disease burden globally (@ch:global-perspectives); the countries with the most triggering infections are the countries with zero economic data.

(Certainty: 0.60 — the gaps are confirmed by systematic reviews @Cochrane2021CostEffectiveness and bibliometric analysis @Wan2024HealthEconomicsTrends; the list is descriptive, not speculative.)

*Consequence:* This gap inventory is the research agenda for ME/CFS health economics. Each item is feasibly addressed with existing methods and, in several cases, existing data (U.S. claims, NZ administrative data, UK CPRD). The barriers are not methodological; they are institutional — no funding body has commissioned these studies. This is itself a consequence of the research underfunding documented in this chapter. Severity applicability: the research gaps affect evidence-based policy for all severity levels.
] <oq:missing-evidence>

== Summary: The Economic Dimension of Neglect

ME/CFS is an economically severe disease by any measure: USD 17--24 billion annually in the U.S., AU\$14.5 billion in Australia, per-patient costs comparable to MS and RA, employment rates below 27% across studies, indirect costs accounting for two-thirds or more of the total burden, and caregiver economic impact that impoverishes families. Its research funding receives approximately USD 1 for every USD 1,000 in economic cost it generates — a ratio 30--40 times worse than MS or RA.

The economic data are descriptive, not causal — they document the present state, not the return on hypothetical interventions. The most important economic study in ME/CFS has not been done: the cost-effectiveness of reducing diagnostic delay, of funding a sustained research program, or of any care model. The evidence gap is not an accident — it is a predictable consequence of the same structural underinvestment it would quantify if filled.

#synthesis(title: [The Economic Case for ME/CFS])[
ME/CFS imposes costs of USD 18,000--29,000 per patient per year across three countries with independent cost-of-illness studies. Employment rates cluster around 20% (versus ~80% in the general population). Caregivers experience 50% household-income reductions. Yet the disease receives approximately USD 15M per year in U.S. federal research funding — a 1,000:1 burden-to-funding ratio that is 30--40 times worse than multiple sclerosis or rheumatoid arthritis, diseases with comparable per-patient costs and disability severity.

The economic argument for increased funding has never been stronger — because the data keep accumulating — and never been harder to dismiss — because the cross-disease comparators show the disparity is structural, not attributable to any unique feature of ME/CFS as a research target. The argument's single vulnerability — that it is descriptive, not causal, and cannot predict the return on a specific funding increase — is itself a product of the underfunding it documents @lim:no-roi. The research needed to estimate the ROI of ME/CFS research funding has itself not been funded.

The strongest conclusion the evidence supports is not that a specific funding increase is cost-effective, but that the current funding level is impossible to justify on any cost-effectiveness principle — because the burden is documented, the funding disparity is measured, and no disease of comparable economic severity is funded at ME/CFS levels. A funding level that is unjustifiable on the available evidence is a funding level that should change, regardless of whether the optimal level can be calculated — just as a treatment known to be harmful is withdrawn before its replacement is proven effective.

*Consequence:* This synthesis translates the chapter's descriptive economics into a single actionable claim: the current level of ME/CFS research funding is inconsistent with its documented burden. Policy change does not require proving that a specific funding level is optimal — it requires demonstrating that the current level is indefensible. The chapter provides that demonstration. (Certainty: 0.65 — cost-of-illness data from multiple independent studies with convergent estimates across three countries; funding disparity verified against public NIH data; the synthesis translates descriptive evidence into a policy claim, not a causal inference.) Severity applicability: the synthesis applies to the research enterprise as a whole; its policy implications affect patients across all severity levels, with the largest impact on severe and very severe patients who have the greatest need for treatment advances and the least capacity to participate in the research advocacy that would produce them.
] <syn:economic-impact-model>
