#import "../../shared/environments.typ": *


= Symptom-Based Management
<ch:symptom-management>

While the preceding chapters establish _why_ ME/CFS produces its characteristic disability, this chapter addresses a more immediate question for patients and clinicians: what can be done about each symptom now, before—and alongside—any attempt to reverse the underlying disease process. Symptom-based management is not a substitute for mechanism-directed treatment, but for most patients it is the intervention that most rapidly improves daily quality of life, and for the severely affected it can be the difference between an unbearable and a bearable existence.

The approach taken here is deliberately organised by symptom domain rather than by drug class or mechanism, because that is how patients experience the illness and how clinical decisions are actually made. After an opening section on comorbidity management, which sets a foundational principle rather than treating a single symptom, each domain section pairs non-pharmacological and pharmacological options and states the strength of evidence behind each recommendation. Throughout, two principles recur. First, in a multi-system illness with a fixed and reduced energy envelope, treating one symptom in isolation can worsen another; interventions must therefore be weighed against their systemic cost. Second, much of the guidance rests on clinical experience and extrapolation from related conditions rather than on ME/CFS-specific randomised trials—a limitation stated explicitly wherever it applies, rather than obscured.

The chapter opens with comorbidity management (Section @sec:comorbidity-management), because unaddressed comorbid conditions—mast cell activation, orthostatic intolerance, sleep disorders, and others—frequently drive symptom burden that would otherwise be attributed to ME/CFS itself, and their aggressive treatment often yields the largest gains. It then turns to the management of post-exertional malaise (Section @sec:managing-pem), the cardinal feature of the illness and the foundation on which all other treatment depends, centred on pacing and energy-envelope theory. Subsequent sections address the domains that most consistently impair function: sleep (Section @sec:sleep-management), pain (Section @sec:pain-management), cognitive dysfunction (Section @sec:cognitive-management), orthostatic intolerance (Section @sec:orthostatic-management), and the broader autonomic symptoms—thermoregulatory, gastrointestinal, and urinary—that accompany dysautonomia (Section @sec:autonomic-management). Patients with severe disease should read this chapter alongside the urgent-action protocols of Chapter @ch:urgent-action-severe, and those with mild to moderate disease alongside Chapter @ch:action-mild-moderate, which sequence these same interventions into staged treatment plans.

