#import "../../../../shared/environments.typ": *

*Abbreviations used in this section:*

/ *5-HTP*:  5-hydroxytryptophan; serotonin precursor
/ *AAb*:  autoantibody
/ *AADC*:  aromatic L-amino acid decarboxylase; converts L-DOPA to dopamine
/ *ACh*:  acetylcholine
/ *AChE*:  acetylcholinesterase
/ *AMPK*:  AMP-activated protein kinase; cellular energy sensor
/ *ANC*:  absolute neutrophil count
/ *ANT*:  adenine nucleotide translocator; mitochondrial inner membrane ATP/ADP exchanger
/ *AQP2*:  aquaporin-2; renal collecting duct water channel
/ *ATP*:  adenosine triphosphate
/ *BBB*:  blood-brain barrier
/ *BP*:  blood pressure
/ *cAMP*:  cyclic adenosine monophosphate
/ *Ca²⁺*:  calcium ion
/ *CNS*:  central nervous system
/ *CoQ10*:  coenzyme Q10; ubiquinol/ubiquinone
/ *COX-2*:  cyclooxygenase-2
/ *CRP*:  C-reactive protein
/ *CSF*:  cerebrospinal fluid
/ *CYP*:  cytochrome P450
/ *DA*:  dopamine
/ *DAT*:  dopamine transporter
/ *DBH*:  dopamine-beta-hydroxylase
/ *DCA*:  dichloroacetate; pyruvate dehydrogenase kinase inhibitor
/ *DMF*:  dimethyl fumarate
/ *DNRI*:  dopamine-norepinephrine reuptake inhibitor
/ *DORA*:  dual orexin receptor antagonist
/ *EBV*:  Epstein-Barr virus
/ *ESR*:  erythrocyte sedimentation rate
/ *ETC*:  electron transport chain
/ *FDG*:  fluorodeoxyglucose; glucose analogue for PET imaging
/ *G-CSF*:  granulocyte colony-stimulating factor
/ *GABA*:  gamma-aminobutyric acid
/ *GAD*:  glutamate decarboxylase; gamma-aminobutyric acid synthesis enzyme
/ *GI*:  gastrointestinal
/ *GLP-1*:  glucagon-like peptide-1; incretin hormone
/ *GLP-1R*:  glucagon-like peptide-1 receptor
/ *GPCR*:  G protein-coupled receptor
/ *GSH*:  glutathione; primary intracellular antioxidant
/ *HCA2/GPR109A*:  hydroxycarboxylic acid receptor 2; niacin receptor on mast cells
/ *HCN*:  hyperpolarization-activated cyclic nucleotide-gated channel
/ *HHV-6*:  human herpesvirus 6
/ *HPA*:  hypothalamic-pituitary-adrenal axis
/ *HR*:  heart rate
/ *HSC*:  haematopoietic stem cell
/ *H₂S*:  hydrogen sulfide; gaseous vasodilator and mitochondrial electron donor
/ *IA*:  immunoadsorption
/ *IDO*:  indoleamine 2,3-dioxygenase
/ *IENFD*:  intraepidermal nerve fibre density
/ *IgE*:  immunoglobulin E
/ *IgG*:  immunoglobulin G
/ *IL*:  interleukin
/ *IMPase*:  inositol monophosphatase; lithium target in phosphatidylinositol 4,5-bisphosphate resynthesis
/ *IVIG*:  intravenous immunoglobulin
/ *KYNA*:  kynurenic acid; N-methyl-D-aspartate receptor antagonist
/ *LDN*:  low-dose naltrexone
/ *MAO-B*:  monoamine oxidase B; degrades dopamine
/ *MCAS*:  mast cell activation syndrome
/ *MRGPRX2*:  Mas-related G protein-coupled receptor X2; mast cell receptor
/ *mTORC1*:  mechanistic target of rapamycin complex 1
/ *mTORC2*:  mechanistic target of rapamycin complex 2; regulates cell survival and cytoskeleton
/ *NAC*:  N-acetylcysteine
/ *NCX1*:  Na⁺/Ca²⁺ exchanger 1
/ *NE*:  norepinephrine
/ *NET*:  norepinephrine transporter
/ *NF-κB*:  nuclear factor kappa-B
/ *NK cell*:  natural killer cell
/ *NMDA*:  N-methyl-D-aspartate
/ *Nrf2*:  nuclear factor erythroid 2-related factor 2; antioxidant master regulator
/ *NRI*:  norepinephrine reuptake inhibitor
/ *NSAID*:  non-steroidal anti-inflammatory drug
/ *NTS*:  nucleus tractus solitarius
/ *OH*:  orthostatic hypotension
/ *OI*:  orthostatic intolerance
/ *PDH*:  pyruvate dehydrogenase
/ *PDK*:  pyruvate dehydrogenase kinase
/ *PEA*:  palmitoylethanolamide; PPAR-alpha agonist
/ *PEM*:  post-exertional malaise
/ *PFC*:  prefrontal cortex
/ *PGD2*:  prostaglandin D2; mast-cell-derived prostaglandin
/ *PGDS*:  prostaglandin D2 synthase
/ *PGE2*:  prostaglandin E2
/ *PGH2*:  prostaglandin H2; COX product and PGDS/PGES substrate
/ *PIP2*:  phosphatidylinositol 4,5-bisphosphate
/ *PKA*:  protein kinase A; cAMP-dependent kinase
/ *PKC*:  protein kinase C
/ *POTS*:  postural orthostatic tachycardia syndrome
/ *QUIN*:  quinolinic acid; N-methyl-D-aspartate receptor agonist from kynurenine pathway
/ *REE*:  resting energy expenditure
/ *RLS*:  restless legs syndrome
/ *ROS*:  reactive oxygen species
/ *RVLM*:  rostral ventrolateral medulla; primary sympathetic output nucleus
/ *SA node*:  sinoatrial node
/ *SC*:  supercomplex
/ *SERT*:  serotonin transporter
/ *sigma1R*:  sigma-1 receptor; endoplasmic reticulum chaperone regulating autophagy and ER stress
/ *SkQ1*:  plastoquinonyl-decyl-triphenylphosphonium; mitochondrial-targeted antioxidant
/ *SNRI*:  serotonin-norepinephrine reuptake inhibitor
/ *SSRI*:  selective serotonin reuptake inhibitor
/ *SV2A*:  synaptic vesicle glycoprotein 2A; levetiracetam binding site
/ *TCA*:  tricarboxylic acid cycle
/ *TLR4*:  Toll-like receptor 4
/ *Treg*:  regulatory T cell; CD4+CD25+FoxP3+
/ *TRPM3*:  transient receptor potential melastatin 3; non-selective cation channel
/ *TRPV1*:  transient receptor potential vanilloid 1; capsaicin receptor; mediates heat/pain and arteriolar vasoconstriction
/ *TXA2*:  thromboxane A2; platelet-derived vasoconstrictor
/ *VLM*:  ventrolateral medulla
/ *VMAT2*:  vesicular monoamine transporter 2
/ *WASF3*:  Wiskott-Aldrich syndrome protein family member 3; respiratory supercomplex assembly inhibitor


=== Five Diagnostic Patterns in Adverse Drug Reactions

*Pattern 1 — Exaggerated therapeutic effect.* The target system was already operating at critical margin, and the drug pushes it over the edge.

- *LDN causing severe sedation in a subset:* The orexin/arousal system was already barely functional. Microglial TLR4 blockade removes the last excitatory drive to orexin neurons → unopposed sleep pressure. Implies hypothalamic neuroinflammation was actively suppressing orexin — consistent with the orexin-suppression model (@sec:microglial-cascade Step K2a). This patient needs orexin support (pitolisant, OX2R agonist), not orexin suppression (DORA).
- *Beta-blockers worsening fatigue beyond HR reduction:* β2-AR blockade impairs lipolysis — the primary fatty acid mobilization pathway. If fatigue worsens on propranolol beyond what ivabradine produces at matched HR, the patient was relying on β2-AR-mediated lipid metabolism to compensate for impaired glucose oxidation. Implies mitochondrial glucose-to-ATP conversion is compromised (PDH, ETC) and fatty acid oxidation is the metabolic fallback. β2-AR blockade removes the fallback → energy collapse. Consistent with PDH inhibition (@sec:pdh-cascade) or WASF3 supercomplex disruption (@sec:wasf3-cascade).
- *Midodrine producing severe hypertension at minimal dose (2.5 mg):* α1 receptors are hypersensitive — textbook denervation hypersensitivity. Confirms neuropathic POTS (sympathetic denervation → upregulated postsynaptic α1 receptors) rather than hyperadrenergic POTS (which would show α1 desensitization from chronic NE overstimulation). Diagnostic: supine NE should be low, and the patient should have poor endogenous vasoconstriction (cold extremities, venous pooling) despite the hypertensive reaction to exogenous agonist.
- *Pramipexole (sifrol) causing nausea and dizziness at RLS starting dose (0.125–0.25 mg):* Nausea is D2/D3 agonism in the area postrema (chemoreceptor trigger zone, outside the blood-brain barrier). Dizziness is orthostatic hypotension from combined peripheral D2-mediated vasodilation and central D2-mediated sympathetic suppression. At the minimal dose used for RLS, these side effects indicate: (a) D2/D3 receptors are supersensitive in both the area postrema (nausea) and cardiovascular regulatory centres (dizziness) — the same supersensitivity that makes low-dose D2 agonism effective also makes it produce side effects at doses that are subclinical in Parkinson's patients; (b) the orthostatic intolerance system is already operating at critical margin — even weak peripheral vasodilation + mild central sympathetic suppression is enough to decompensate it. Diagnostic: this patient's dopaminergic system is hypersensitive (consistent with chronic dopamine deficiency → postsynaptic D2/D3 upregulation in multiple brain regions). The orthostatic intolerance is dopaminergically vulnerable — if pramipexole causes dizziness at 0.125 mg, the patient's haemodynamic stability depends on intact central sympathetic outflow, and any D2-mediated suppression tips the balance. Implies the patient has neuropathic POTS (already-compensated sympathetic tone) or dopamine-dependent cardiovascular regulation. If nausea is present but dizziness is absent → D2 receptors are supersensitive in the area postrema but cardiovascular D2/D3 signalling is either desensitized or non-functional — an unexpected dissociation. If neither nausea nor dizziness occurs at therapeutic doses → D2/D3 receptors in area postrema and cardiovascular centres are too damaged or desensitized to respond (Pattern 5 — absent expected side effect), which would make D2 agonism ineffective for any indication in this patient.
- *Ketotifen causing severe sedation or hypersomnia at 0.5--1 mg:* Ketotifen is a mast cell stabilizer with H1 antagonist activity. At standard MCAS doses (1--2 mg BID), sedation is expected as the H1 component suppresses histaminergic wakefulness. Sedation at 0.5 mg (pediatric dose) implies: (a) the histaminergic arousal system is already barely functional — minimal H1 blockade collapses remaining wakefulness, consistent with the orexin suppression model (@sec:microglial-cascade Step K2a); or (b) ketotifen's mast-cell stabilizing effect is additionally suppressing a compensatory mast-cell-driven arousal mechanism (histamine released from CNS mast cells was the only thing keeping the patient awake). Diagnostic: this patient's wakefulness depends on histaminergic tone from mast cell degranulation — they are being "held awake" by their own MCAS. If ketotifen reduces MCAS symptoms (flushing, GI, pruritus) without sedation → the mast-cell stabilizing benefit is achieved at a dose below the H1 sedation threshold; H1 receptors are intact but not hypersensitive. If ketotifen produces NO effect (no MCAS improvement, no sedation) → either mast cells are not rate-limiting for symptoms, or ketotifen cannot access CNS mast cells at this dose. The dissociation of MCAS benefit vs sedation identifies whether mast cells are driving symptoms or just co-occurring.
- *Pregnenolone sulfate causing agitation, insomnia, or anxiety at 25--50 mg:* Pregnenolone is a TRPM3 positive allosteric modulator and a negative allosteric modulator of GABA-A receptors, with additional NMDA receptor modulatory activity. At the low doses used for TRPM3 gating support, these side effects imply: (a) TRPM3 channels are functional and hypersensitive — the positive allosteric modulation of TRPM3 produces excessive calcium influx in sensory and autonomic neurons, driving CNS excitation; (b) GABA-A negative modulation at a system already in a low-GABAergic tone state (consistent with neuroinflammation-driven interneuron dysfunction, @sec:kynurenine-cascade H2b) tips the excitation-inhibition balance toward excitation; and (c) the dual mechanism — TRPM3 activation + GABA-A disinhibition — means the patient has both an intact, hypersensitive ion channel AND a fragile inhibitory system. Diagnostic: if agitation occurs at 25 mg but not 10 mg → the TRPM3 system has a narrow tolerable modulation window; the patient's CNS excitation-inhibition balance is on a knife edge. If no agitation even at 100 mg → TRPM3 is either desensitized, absent, or already maximally activated (Pattern 5 — absence of expected CNS excitation implies the channel cannot be further activated). If pregnenolone produces sedation (unexpected, since it is a GABA-A NAM) → the NMDA negative modulatory effect dominates, and the patient's glutamatergic system is hyperactive (quinolinic-acid-driven NMDA excitotoxicity, consistent with the kynurenine pathway); the GABA-A NAM effect is outweighed by NMDA suppression. This dissociation — sedation vs. agitation from the same drug — distinguishes glutamatergic excitotoxicity from GABAergic insufficiency as the dominant CNS pathology.
- *Clonidine (0.05--0.1 mg at bedtime, central α2 agonist) causing hypotensive crash at minimal dose:* Clonidine suppresses central sympathetic outflow via α2 autoreceptors on LC neurons and brainstem presympathetic nuclei (RVLM). At this dose — 1/4 to 1/2 of the antihypertensive starting dose (0.1 mg BID) — a BP crash implies the total systemic BP is sympathetically maintained: removing even a fraction of central sympathetic outflow unmasks an absolute dependence on α2-gated sympathetic tone for every mmHg of perfusion pressure. Diagnostic: (a) the baroreflex arc is impaired — the NTS cannot mount a compensatory sympathetic response when clonidine suppresses the RVLM because the NTS itself is dysfunctional (consistent with brainstem neuroinflammation, @sec:brainstem-cascade); (b) the remaining sympathetic output is load-bearing — there is minimal adrenergic reserve; (c) midodrine MUST precede any clonidine or guanfacine trial — the patient needs exogenous α1 agonism before central α2 agonism can be explored safely. If clonidine at 0.05 mg produces controlled HR/BP reduction without crash → the sympathetic system has some reserve; central α2 agonism may be accessible. If clonidine at 0.1 mg produces NO change in BP/HR → α2 autoreceptors are desensitized (chronic NE overstimulation from hyperadrenergic POTS) — the central sympathetic system cannot be suppressed pharmacologically because the receptors are already non-responsive. The dose at which BP drops is an ordinal readout of sympathetic reserve: the lower the dose, the thinner the reserve.
- *Prazosin (0.5--1 mg at bedtime, peripheral α1 antagonist, glymphatic probe) causing severe orthostatic hypotension at minimal dose:* Prazosin blocks α1 receptors on vascular smooth muscle, preventing NE-mediated vasoconstriction — the intended effect for glymphatic support (vasodilation during sleep → improved CSF-ISF exchange, @sec:glymphatic-cascade). But at 0.5 mg — 1/2 of the PTSD nightmare starting dose (1 mg) — severe OH implies the patient's standing BP depends on α1-mediated vasoconstriction for every mmHg of orthostatic tolerance. Diagnostic: (a) this is textbook neuropathic POTS — the sympathetic nerves to the legs are denervated, and the remaining vasoconstriction is from circulating NE acting on supersensitive α1 receptors; blocking even a fraction causes OH because there is zero redundancy; (b) the glymphatic benefit is inaccessible behind the OH ceiling — the same α1 blockade that would improve glymphatic flow during sleep makes the patient unable to stand safely. If prazosin worsens OH at 0.5 mg but improves morning symptoms at 0.25 mg taken strictly supine (patient remains supine for 8+ hours after dose) → the glymphatic window exists but requires strict supine dosing — the patient cannot stand for at least 8 hours post-dose. This is a practical constraint: prazosin becomes a bedtime-only, supine-only glymphatic probe. If prazosin produces no OH at 1 mg → the standing BP does NOT depend on α1-mediated vasoconstriction; either (a) the patient has hyperadrenergic POTS (standing BP is maintained by β1 cardiac output, not α1 vasoconstriction — consistent with OH from clonidine, not prazosin), or (b) the patient has adequate sympathetic reserve. The prazosin OH threshold at microdose distinguishes neuropathic POTS (OH from α1 block) from hyperadrenergic POTS (OH from central α2 suppression with clonidine) — two subtypes that require opposite pharmacological strategies.

*Pattern 2 — Paradoxical reaction.* The target system has a regulatory inversion — the expected response is reversed.

- *LDN causing depression, suicidal ideation, or agitation (the "paradoxical reactor" phenotype):* Opioid system dysregulation at the receptor or downstream signaling level. Brief opioid blockade at low-dose naltrexone should trigger compensatory endorphin upregulation and improved mood. Instead, blockade triggers dysphoria — implying: (a) the endogenous opioid system is tonically active to compensate for chronic pain or inflammation, and removing that compensation unmasks a severe deficit; (b) the patient may have a genetic variant in OPRM1 (μ-opioid receptor) altering naltrexone binding kinetics; or (c) the TLR4 antagonism is not the dominant LDN effect in this patient — the opioid receptor interaction dominates and goes the wrong direction. Diagnostic: this patient should NOT receive any opioid-modulating medication. Their pain and mood regulation depend on intact opioid tone. The adverse reaction itself identifies them as opioid-dependent for homeostasis.
- *Fludrocortisone worsening orthostatic symptoms:* Expected: volume expansion → improved preload → reduced orthostatic tachycardia. Paradoxical worsening implies: (a) the volume expansion is causing excessive venous pooling rather than increased cardiac preload (venous compliance from connective tissue laxity is the dominant vascular defect — volume goes to the legs, not the heart); (b) fludrocortisone-induced hypokalemia is worsening vascular smooth muscle function; or (c) aldosterone-sensitive sodium channels in the brain (circumventricular organs) are triggering a central sympathetic overactivation that exceeds the peripheral volume benefit. Diagnostic: this patient has connective-tissue-driven venous pooling, not hypovolemic POTS. Compression garments should work; fludrocortisone should not.
- *IVIG causing transient worsening (immune activation flare) before improvement:* IVIG neutralizes circulating autoantibodies and modulates Fc receptors on immune cells. An initial worsening — increased fatigue, flu-like symptoms, brain fog — is expected as immune complexes form and complement is activated during autoantibody neutralization (Herxheimer-like). If the flare resolves within 48--72 hours and is followed by sustained improvement → GPCR autoantibody-mediated pathology is present and IVIG is effective. Diagnostic: the flare itself confirms autoantibody presence — the body is mounting an immune response to the neutralized complexes. If the flare does NOT resolve (>7 days of worsening) → either: (a) the patient cannot tolerate complement activation (complement regulatory protein deficiency, @spec:complement-pem-biphasic), (b) mast cell activation is being triggered by immune complex formation (C3a/C5a anaphylatoxin release → mast cell degranulation), consistent with the complement-mast cell amplification loop (@spec:complement-mast-cell-loop). If IVIG produces NO response AND no flare → either no GPCR AAb present, or the AAb are not rate-limiting, or the IgG preparation does not contain the relevant idiotypes. The absence of any immune reaction to a foreign IgG preparation suggests profound immune exhaustion or tolerance.
- *IVIG or rituximab producing no change in symptom trajectory over 6+ months:* Expected: if autoantibodies drive symptoms, removing or neutralizing them should improve symptoms within weeks to months. Complete non-response implies: (a) autoantibodies are not present or not rate-limiting, (b) autoantibodies are present but downstream tissue damage is irreversible (neural loss, fibrosis, epigenetic consolidation), (c) the relevant autoantibodies are IgM (rituximab spares plasma cells, and pre-existing IgM-producing plasma cells are not depleted), or (d) autoantibody production is ongoing from a sanctuary site not accessible to IVIG/rituximab (CSF compartment, lymph node, bone marrow niche). Diagnostic: non-response to both IVIG AND rituximab effectively excludes circulating IgG autoantibody-mediated pathology as the dominant mechanism. The lesion is either upstream of autoantibody production (T-cell, persistent antigen) or downstream of antibody-mediated damage (irreversible tissue-level changes). If rituximab produces no response but IVIG does → rituximab spares long-lived plasma cells that produce the relevant AAb; the AAb source is a non-dividing plasma cell pool. Daratumumab (anti-CD38, depletes plasma cells) should be considered.
- *Famotidine or cimetidine causing depression or suicidal ideation:* H2 receptor antagonists normally suppress gastric acid without CNS effects at standard doses. The emergence of psychiatric adverse effects implies: (a) H2 receptors in the CNS are playing a compensatory role for mood regulation — blocking them removes a histaminergic mood-stabilizing effect that was compensating for a serotonergic or dopaminergic deficit; (b) the patient has a paradoxical CNS histamine response (H2 agonism normally pro-cognitive, so blockade should not be depressogenic unless brain histamine tone is inverted); or (c) the H2 blocker is altering gut-brain axis signalling in a patient whose mood is gut-dependent (microbiome-mediated serotonin synthesis depends on gastric pH for precursor absorption). Diagnostic: this patient has the "paradoxical reactor" phenotype extended to the histaminergic system — consistent with opioid/histamine cross-sensitization (@sec:paradoxical-reactor). This patient should avoid all H2 antagonists. Furthermore, if famotidine causes depression but cimetidine does not → the effect is drug-specific (not class-wide), ruling out H2 receptor mechanism and implicating an off-target effect of the specific molecule — cimetidine's T-cell enhancement may be protective via immune-mediated mood regulation. If cimetidine causes depression but famotidine does not → the effect is through CYP450-mediated drug interactions (cimetidine inhibits CYP1A2, 2D6, 3A4, altering antidepressant or endogenous steroid metabolism), not H2 blockade.
- *Low-dose IL-2 causing symptom flare resembling autoimmune activation:* IL-2 at low doses (1--3 million IU/day subcutaneously) expands regulatory T cells (Tregs) — CD4+CD25+FoxP3+ T cells that suppress autoimmune effector T-cell responses. If IL-2 causes a transient inflammatory flare (increased fatigue, flu-like symptoms, lymphadenopathy, worsened brain fog) instead of the expected gradual improvement → the patient's autoimmune pathology involves activated effector T cells that IL-2 also stimulates before Tregs can suppress them. IL-2 binds the high-affinity trimeric IL-2R (CD25/CD122/CD132) on Tregs at low concentrations but also stimulates effector T cells and NK cells expressing the intermediate-affinity dimeric receptor (CD122/CD132) at higher local concentrations. A flare indicates: (a) effector T-cell or NK-cell populations are pre-activated and respond to IL-2 before Treg expansion takes effect (onset within 24--48 hours, too fast for Treg expansion which requires 2--4 weeks); (b) the autoimmune component is T-cell-driven, not purely B-cell/autoantibody-driven — IL-2 temporally reveals the T-cell vs. B-cell balance in the autoimmune pathology. If the flare resolves within 1--2 weeks and is followed by sustained improvement → Tregs expanded and are functional — the autoimmune process is Treg-suppressible, and the initial flare was transient effector activation. If the flare persists beyond 2 weeks without improvement → Tregs cannot suppress the effector response; the autoimmune process is Treg-resistant (consistent with effector T cells that have escaped peripheral tolerance), or Treg expansion failed (IL-2 dose insufficient, IL-2R signaling pathway defective in this patient's Tregs). If IL-2 produces NO flare AND no improvement → either Tregs are not the autoimmune bottleneck (B-cell/plasma-cell-driven autoimmunity, complement-driven, or non-immune pathology), or the Treg pool is already maximally expanded and cannot be further augmented — a ceiling effect consistent with chronic antigen-driven Treg exhaustion. If IL-2 produces improvement without any flare → Tregs expanded without effector activation — the patient has a pure Treg deficiency with quiescent effector T cells. Diagnostic: IL-2 is the highest-specificity probe for Treg function in ME/CFS — the flare-vs-improvement temporal pattern separates T-cell-driven autoimmunity from Treg-deficiency-driven immune dysregulation. A patient who flares on IL-2 should not receive other T-cell-stimulating immunotherapies without prior Treg expansion.
- *Z-drugs (zolpidem, eszopiclone) causing paradoxical excitation, complex sleep behaviours, or absence of expected amnesia:* Z-drugs are GABA-A α1-preferring positive allosteric modulators. Paradoxical excitation (agitation, hallucinations, complex sleep behaviours — sleep-eating, sleep-driving) implies: (a) the GABA-A system is dysregulated — instead of the expected hyperpolarization and sedation, GABA-A activation triggers paradoxical depolarization, consistent with altered chloride gradients in CNS neurons (NKCC1/KCC2 imbalance from neuroinflammation → intracellular chloride elevated → GABA-A activation produces chloride efflux and depolarization rather than influx and hyperpolarization); or (b) the α1-containing GABA-A receptors are hypersensitive at some sites and desensitized at others — spatial heterogeneity from region-specific neuroinflammation. Diagnostic: this patient has a GABAergic inversion — GABA is excitatory, not inhibitory, in key circuits. This is a severe finding consistent with the NKCC1-upregulation/KCC2-downregulation pattern documented in neuroinflammatory and chronic pain states. Z-drugs, benzodiazepines, and all GABA-A PAMs should be avoided — they will worsen symptoms through paradoxical excitation. The absence of expected anterograde amnesia at standard zolpidem doses (5--10 mg) → GABA-A α1 receptors mediating memory consolidation (hippocampal CA1, dentate gyrus) are desensitized — the receptor population that normally produces amnesia as a side effect is non-functional. This is a specific pharmacodiagnostic for hippocampal GABA-A α1 desensitization. If amnesia IS present at standard doses → hippocampal GABA-A α1 is intact; the receptor population is normally sensitive. If complex sleep behaviours occur → the motor cortex and basal ganglia GABA-A circuits are disinhibiting motor programs during sleep — a specific probe for motor-system GABA-A dysregulation. The three dissociable Z-drug side effects (excitation, amnesia, complex behaviours) map onto three GABA-A α1-containing circuits: cortical (excitation), hippocampal (amnesia), and striatal/motor (complex behaviours). The pattern identifies which circuit is most dysregulated.
- *Low-dose aspirin worsening MCAS symptoms:* Aspirin at antiplatelet doses (75--100 mg) inhibits COX-1, reducing thromboxane A2 (TXA2) and prostaglandin production. Worsening of MCAS symptoms (flushing, pruritus, GI distress, bronchospasm) implies prostaglandin-mediated mast cell stabilization was active — COX-1-derived PGD2 was tonically inhibiting mast cell degranulation through DP1 receptor signaling. Removing this brake unmasked the underlying MCAS. Diagnostic: this patient's mast cells are prostaglandin-buffered — PGD2 is compensatory, not pathogenic. NSAIDs are contraindicated in this MCAS subtype. If aspirin worsens symptoms but celecoxib (COX-2 selective) does not → the protective prostaglandin is COX-1-derived (likely PGD2 from mast cells themselves, which express COX-1 constitutively), not COX-2-derived. If both aspirin and celecoxib worsen → both COX-1 and COX-2 contribute to the prostaglandin brake; mast cells are maximally unstable without continuous prostaglandin tone. If aspirin produces NO worsening → the prostaglandin brake is absent or already saturated; mast cell degranulation is driven by non-prostaglandin pathways (IgE, MRGPRX2, complement C3a/C5a, or TLR4). This patient can safely use NSAIDs without MCAS exacerbation. If aspirin PREVENTS niacin flushing → the flushing pathway is COX-1/COX-2-dependent (PGD2 release from dermal mast cells in response to niacin's hydroxycarboxylic acid receptor 2 activation) — confirms mast cell PGD2 hyper-reactivity in skin, not systemic MCAS. The aspirin probe distinguishes systemic prostaglandin-buffered MCAS (worsening) from cutaneous PGD2 hyper-reactivity (niacin flush prevention) from prostaglandin-independent MCAS (no effect).

*Pattern 3 — Unexpected off-target effect.* A system the drug wasn't supposed to affect reveals latent vulnerability.

- *Pyridostigmine causing severe GI cramping/diarrhea at 30 mg:* Acetylcholine accumulation at muscarinic receptors in the gut. Expected at higher doses, but severe at minimal dose implies: (a) acetylcholinesterase activity is already reduced (from inflammation, oxidative stress, or genetic AChE variants) → less enzyme available to degrade ACh, so AChE inhibition has outsized effect; or (b) the gut has upregulated muscarinic receptor density or sensitivity in compensation for reduced vagal tone → the tissue is primed to overreact to ACh. Diagnostic: start at 10--15 mg. If GI sensitivity persists, the gut cholinergic system is hypersensitive — consistent with enteric denervation and compensatory receptor upregulation.
- *Aripiprazole causing akathisia at 0.5 mg:* D2/D3 partial agonism at minimal dose producing motor restlessness. Expected at antipsychotic doses (5--30 mg) but not at microdoses. Implies: (a) D2 receptors are supersensitive (upregulated from chronic dopamine deficiency) — the same receptor state that makes aripiprazole effective at microdoses also makes it produce akathisia at microdoses; (b) the patient's dopaminergic deficit is severe enough that the partial agonist's intrinsic activity at 0.5 mg exceeds what the system can buffer. Diagnostic: this patient has severe dopamine deficiency — the akathisia confirms the receptor pathology. Consider even lower starting dose (0.1 mg liquid titration) or switching to a different dopamine strategy (amantadine, which increases release rather than agonizing receptors directly).

  *If akathisia persists for weeks AFTER discontinuation:* Aripiprazole's half-life is ~75 h — drug should be cleared in 6--7 days. Akathisia lasting weeks beyond clearance cannot be explained by residual drug occupying the receptor. Three mechanisms can produce this:

  (a) *Receptor-state consolidation.* Prolonged D2/D3 partial agonism at supersensitive receptors triggers a persistent change in receptor trafficking or signaling — the receptor population does not revert to baseline sensitivity on drug removal. The system has "learned" a new set-point. This is pharmacologically plausible: GPCRs undergo agonist-induced conformational changes that persist after ligand dissociation through β-arrestin scaffolding and receptor oligomerization — the activated receptor complex remains in a signaling-competent state even after the drug is gone. If this is the mechanism, the akathisia will eventually resolve as receptor turnover (t½ ~3--7 days for D2) replaces the conformationally locked population — expected resolution within 3--6 weeks. Time to resolution maps the receptor half-life in vivo.

  (b) *Microglial triggering — the dopamine/microglia bidirectional loop.* D2/D3 receptors are expressed on microglia (@sec:lda-differential). Aripiprazole's D2 partial agonism on microglia may have triggered a microglial activation burst — cytokine release → neuroinflammation → striatal circuit dysfunction → akathisia. The drug is the trigger, but the akathisia is maintained by the inflammatory cascade it initiated, not by continued receptor occupancy. This is the same mechanism posited for neuroleptic malignant syndrome (NMS), where a single dose of a D2-blocking antipsychotic can trigger a weeks-long hyperthermic/dysautonomic crisis that continues after drug clearance — the drug is the match, the inflammatory cytokine storm is the fire. In ME/CFS patients with pre-existing microglial priming, this match-to-fire transition may occur at much lower doses. Diagnostic: if LDN or minocycline shortens the akathisia duration → microglial mechanism confirmed; the anti-inflammatory intervention extinguishes the fire the D2 signal started.

  (c) *Unmasked pre-existing akathisia from another source.* The patient attributed the akathisia to aripiprazole but it was actually a withdrawal syndrome from a recently discontinued medication — SSRIs, SNRIs, and antipsychotics all produce withdrawal akathisia that can last weeks to months. Aripiprazole's D2/D3 agonism may have temporarily suppressed the withdrawal akathisia (D2 stimulation in the ventral striatum inhibits motor restlessness), and akathisia "emerged" only when aripiprazole was stopped — not because aripiprazole *caused* it, but because aripiprazole was masking it. The temporal correlation (akathisia persisted after stopping aripiprazole) is equally consistent with this interpretation: the akathisia was always present, was transiently suppressed by aripiprazole treatment, and emerged fully when aripiprazole was withdrawn. This is a diagnostic confound: akathisia that continues after the drug is gone can mean the drug caused a persistent state OR the drug was suppressing a pre-existing state. Distinguish: if akathisia appeared within hours of the *first* aripiprazole dose → aripiprazole caused it (rxns (a) or (b)). If akathisia only appeared after aripiprazole was stopped, or worsened on stopping → consider withdrawal/re-emergent akathisia from another agent.

  *Contrast — akathisia that resolves as drug clears (2--7 days after discontinuation):* This is the diagnostically cleaner pattern. The akathisia tracks plasma concentration — present when drug occupies receptors, absent when drug is gone. This means: (a) D2/D3 receptors are supersensitive (the microdose produced the effect of a therapeutic dose); (b) receptor signalling is intact — the receptors can be activated AND deactivated normally; (c) receptor trafficking is intact — the receptor population returns to baseline sensitivity when the agonist is removed; (d) therefore the chronic dopamine deficiency is *presynaptic* — production, release, or storage is impaired — while postsynaptic machinery is functional. This specifically rules out postsynaptic D2/D3 pathology (receptor desensitization, G-protein uncoupling, arrestin defects). The lesion is upstream: TH expression, AADC activity, VMAT2 packaging, or dopaminergic terminal integrity. Probe sequence: methylphenidate (blocks reuptake — tests if DA is being released but cleared too fast); L-DOPA (provides substrate — tests if synthesis is the bottleneck); rasagiline (blocks degradation — tests if accelerated turnover is the bottleneck). If all three fail despite confirmed functional postsynaptic receptors → VMAT2 terminal loss (DA cannot be stored, so it cannot be released, reuptake-inhibited, or synthesis-bypassed).

  If akathisia persists weeks after discontinuation — see above. Distinguishing criterion: does akathisia track plasma concentration? Yes → presynaptic lesion, intact postsynaptic. No → receptor-state consolidation, microglial triggering, or unmasking confound.

  *Consequence:* The patient with akathisia persisting weeks after aripiprazole discontinuation has generated diagnostic data: (i) supersensitive D2 receptors (confirmed by akathisia at microdose); (ii) either receptor-state consolidation OR microglial triggering OR unmasking confound — distinguished by timeline: onset on first dose = aripiprazole-caused; onset only after stopping = consider withdrawal from another agent; (iii) if anti-inflammatory treatment resolves persistent akathisia → microglial loop confirmed; (iv) if akathisia resolves spontaneously in 3--6 weeks → receptor-turnover mechanism (D2 receptors replaced); (v) this patient should never be re-challenged with any D2/D3 agonist — the receptor population has demonstrated it can be driven into a persistent activated state.
- *Amantadine (100--200 mg/day, dopamine release enhancer + weak NMDA antagonist) causing livedo reticularis or confusion at subtherapeutic dose:* Amantadine increases dopamine release from surviving presynaptic terminals by blocking dopamine reuptake and enhancing vesicular release — a presynaptic strategy that bypasses D2/D3 receptor issues. Livedo reticularis (net-like violaceous skin mottling) is a well-known amantadine side effect from catecholamine-mediated peripheral vasoconstriction in dermal arterioles with compensatory venular dilation. At the low dose of 100 mg (half the Parkinson's starting dose), livedo implies: (a) catecholamine-mediated vasomotor instability in skin microvasculature is already at threshold — consistent with peripheral sympathetic dysregulation (neuropathic POTS with regional denervation → patchy vasomotor control); (b) the skin microvasculature mirrors the systemic autonomic state — livedo at 100 mg suggests the peripheral sympathetic system has zero reserve for additional catecholamine tone. Confusion at 100 mg implies NMDA antagonism sensitivity — amantadine's weak NMDA block (Ki ~10 µM) is normally imperceptible, but in a system with NMDA hypofunction (KYNA dominance, kynurenine pathway), even weak block tips cognition over the edge. Diagnostic: (a) livedo reticularis at 100 mg → peripheral sympathetic vasomotor fragility confirmed — consistent with neuropathic POTS with dermal microvascular involvement (pattern may predict response to midodrine: the same sympathetic deficit that causes patchy vasoconstriction in skin may cause venous pooling in legs); (b) confusion at 100 mg → NMDA hypofunction confirmed (same pattern as ketamine psychotomimetic sensitivity — two structurally different NMDA antagonists produce the same cognitive ceiling at subtherapeutic doses, confirming global NMDA deficiency); (c) improvement + no livedo/confusion → dopamine release is the bottleneck AND peripheral sympathetic/NMDA systems have adequate reserve — amantadine is usable long-term. If amantadine produces no cognitive benefit at 200 mg despite no side effects → dopamine release is not the bottleneck (consistent with VMAT2 terminal loss — vesicles are empty, amantadine has nothing to release). Try L-DOPA (substrate load) or pramipexole (direct postsynaptic).
- *Duloxetine or amitriptyline causing severe anticholinergic toxicity (confusion, dry mouth, constipation, urinary retention) at low antidepressant doses:* Duloxetine (SNRI) has minimal direct anticholinergic effect; amitriptyline (TCA) blocks M1 muscarinic receptors. If anticholinergic symptoms appear with duloxetine (which should not produce them), an unexpected off-target system is vulnerable — either: (a) the patient has subclinical acetylcholinesterase deficiency (AChE genetic variant) → baseline synaptic ACh is already high, so even the weak indirect anticholinergic effect of NE-mediated inhibition of cholinergic neurons is sufficient to push the system over threshold; or (b) duloxetine is unmasking undiagnosed Sjögren's syndrome (sicca + anticholinergic effect = severe dry mouth, blurred vision, dysphagia). If amitriptyline produces severe sedation at 5--10 mg (not 25--50 mg) → H1 receptor supersensitivity; this patient's histaminergic wakefulness drive is easily suppressed, consistent with orexin/histamine dysfunction. Diagnostic: both agents probe NE/5-HT reuptake function but amitriptyline additionally probes H1 and M1 receptor tone. The specific side-effect ceiling identifies which receptor system has the least functional reserve.
- *Gabapentin or pregabalin causing severe sedation, cognitive impairment, or ataxia at minimal doses (100--300 mg gabapentin, 25--50 mg pregabalin):* Gabapentinoids bind the α2δ subunit of voltage-gated calcium channels (CaV), reducing neurotransmitter release. At these doses, therapeutic effect on neuropathic pain should not yet be achieved — the side effects appear before any analgesic ceiling is reached, implying the α2δ-containing CaV channels are hypersensitive or already upregulated. In ME/CFS, this pattern could mean: (a) the patient has central sensitization so severe that even minimal CaV channel blockade produces disproportionate CNS depression — consistent with TRPM3-dependent calcium dysregulation driving compensatory CaV upregulation; or (b) gabapentinoids are hitting a system that is already calcium-starved — reducing Ca²⁺ influx further tips neurons below their minimum activation threshold. If the patient experiences paradoxical agitation on gabapentin → GABA synthesis is altered (gabapentin increases GABA via GAD activation; if GAD is dysfunctional, glutamate accumulation → paradoxical excitation). Diagnostic: this patient has severe central sensitization. Gabapentinoids cannot be titrated to effective doses — consider PEA (PPAR-α, no calcium channel effect), LDN, or ketamine (NMDA block) for neuropathic pain instead.
- *Fluvoxamine producing GI distress at low-dose (25--50 mg) before sigma-1 receptor (sigma1R) benefit:* Fluvoxamine is unique among SSRIs — at 25--50 mg, it is a potent sigma1R agonist (Kd ~36 nM) with minimal SERT occupancy; sigma1R activation restores ER stress responses and promotes autophagy. At 100+ mg, SERT occupancy dominates and sigma1R selectivity is lost. GI distress (nausea, diarrhoea, cramping) at 25--50 mg is a 5-HT3-mediated off-target effect — serotonin release in the gut before SERT blockade at the synapse. If GI distress appears at sigma1R doses (25--50 mg) and prevents titration → the sigma1R therapeutic window is inaccessible behind the GI serotonergic ceiling; the gut 5-HT3 system is hypersensitive (consistent with serotonergic gut hypersensitivity from 5-HT depletion peripherally + 5-HT3 receptor upregulation). If sigma1R benefit (reduced fatigue, improved cognition) appears at 25--50 mg without GI distress → sigma1R agonism is the mechanism AND the gut serotonergic system has adequate reserve. If benefit appears at 25--50 mg but is lost at 100+ mg → sigma1R is the therapeutic mechanism and SERT-mediated 5-HT reuptake inhibition is counterproductive (consistent with the kynurenine pathway's serotonin depletion — increasing synaptic 5-HT reuptake inhibition when serotonin pool is already depleted produces no additional benefit, and the sigma1R component is diluted). If NO benefit at any dose → neither sigma1R nor SERT is rate-limiting. Diagnostic: fluvoxamine is the only SSRI that distinguishes sigma1R from 5-HT mechanisms by dose — low-dose (25--50 mg) response = sigma1R (ER stress, autophagy); high-dose (100+ mg) response = serotonergic; response at low dose lost at high dose = sigma1R is therapeutic, 5-HT is counterproductive. This is the highest-specificity probe for the sigma1R hypothesis in the entire chapter.
- *Lithium (2--20 mg elemental/day, as PIP2 probe) causing polydipsia, polyuria, or fine tremor at microdose:* Lithium inhibits IMPase and GSK-3β. At the elemental microdoses used for PIP2 probing (2--20 mg elemental — equivalent to 10--70 mg lithium orotate or 75--750 mg lithium carbonate; well below bipolar doses of 150--300 mg elemental), these side effects should be imperceptible. Polydipsia and polyuria at elemental microdose imply aquaporin-2 hypersensitivity in renal collecting ducts — lithium inhibits adenylyl cyclase and GSK-3β in collecting-duct principal cells, reducing vasopressin V2-receptor-driven cAMP/PKA-mediated AQP2 translocation, and in a system where AQP2 is already suppressed (consistent with chronic low-grade kidney stress from dehydration, POTS hypovolemia, or NSAID nephrotoxicity), the additional IMPase inhibition unmasks a pre-existing renal concentrating defect. Fine tremor at microdose implies cerebellar/neuromuscular sensitivity — consistent with hyperadrenergic POTS (β2-mediated physiological tremor is unmasked by lithium's augmentation of NE release at the presynaptic terminal, since lithium acutely increases neurotransmitter release through PIP2 → DAG → PKC pathways before its chronic mood-stabilizing effects occur). Nausea at microdose → lithium is a direct gastric irritant; nausea appearing at elemental microdose (where irritation should be minimal) suggests either gastric hypersensitivity or slow gastric emptying (consistent with POTS/vagal dysfunction). However, lithium-induced nausea even at low doses is common and non-specific — the diagnostic value is lower than tremor or polydipsia, which are more specific to lithium's PIP2/CNS/kidney pharmacology. Diagnostic: polydipsia at 2 mg elemental → severe occult nephrogenic DI vulnerability; tremor at 2 mg elemental → cerebellar NE hypersensitivity; nausea at 2 mg elemental → severe gastric dysmotility. If NO polydipsia, tremor, or nausea at 20 mg elemental → renal concentrating mechanism, cerebellar sensitivity, and GI transit are all functional — lithium's PIP2 inhibition is selective for the therapeutic target. Lithium is the most upstream pharmacological probe in the chapter — a response implies the lesion is at or above PIP2; a side effect maps vulnerability in the kidney, cerebellum, and GI systems that PIP2 also gate. Note: dose equivalence varies by salt — lithium orotate (2--10 mg elemental per capsule) provides microdose ranges; lithium carbonate (28 mg elemental per 150 mg pill) requires quarter-tablet splitting for elemental microdosing.
- *5-HTP (50--100 mg, as serotonin precursor probe) causing GI distress or serotonin syndrome at low dose:* 5-HTP bypasses tryptophan hydroxylase — the rate-limiting IDO-kynurenine drain on tryptophan — and directly supplies serotonin synthesis via AADC. GI distress at 50 mg (nausea, cramping, diarrhoea) implies gut serotonin hypersensitivity: 5-HT3 and 5-HT4 receptors in the enteric nervous system are upregulated from chronic serotonin depletion peripherally (tryptophan diverted to kynurenine via IDO → peripheral serotonin deficiency → compensatory receptor upregulation). The gut's reaction to even a modest serotonin precursor reveals the depth of the peripheral serotonin drain. If serotonin syndrome (confusion, hyperthermia, autonomic instability) appears at 50--100 mg → either AADC activity is very high (rapid conversion) or MAO-A is impaired (serotonin degradation failure) — consistent with oxidative-stress-mediated MAO dysfunction. If NO GI distress at 100 mg → the peripheral serotonin system has adequate reserve (IDO drain is not severe, gut serotonin receptors are normally sensitive). Diagnostic: 5-HTP is the only probe that directly tests the kynurenine pathway's serotonin depletion arm — tryptophan → serotonin, not tryptophan → kynurenine. A positive cognitive or mood response confirms serotonin synthesis is rate-limiting; GI distress at low dose reveals the gut's compensatory receptor state, tracing the severity and tissue distribution of the serotonin deficit.
- *Niacin (50--100 mg, as MCAS probe) producing severe flush at sub-physiologic dose:* Niacin activates hydroxycarboxylic acid receptor 2 (HCA2/GPR109A) on dermal Langerhans cells and mast cells, triggering PGD2 release → vasodilation and flushing. At vitamin doses (15--20 mg/day), flushing is not expected; at the pharmacologic threshold of 50 mg, mild flushing is normal. Severe flush (intense erythema, pruritus, warmth extending from face to torso and lasting >30 minutes) at 50--100 mg implies mast cell PGD2 hyper-reactivity — the dermal mast cell pool releases disproportionate PGD2 per unit HCA2 activation. Diagnostic: the niacin flush threshold maps cutaneous MCAS severity. If flush appears at 25 mg → severe dermal mast cell hyper-reactivity; if flush only at 250+ mg → mild or absent MCAS in skin; if no flush even at 500 mg → HCA2 receptor desensitization or PGD2 synthase deficiency (rare: PGD2 pathway non-functional, would also explain absence of aspirin sensitivity). If aspirin prevents niacin flush → confirms PGD2 is the flush mediator (COX-1 → PGH2 → PGDS → PGD2); mast cell COX-1 is functional and the PGD2 pathway is the dominant skin MCAS mediator. If antihistamines prevent niacin flush → histamine, not PGD2, is driving the flush — a different MCAS subtype. The niacin probe is the lowest-cost MCAS diagnostic: a 50 mg OTC niacin tablet and 20 minutes of observation provide a functional readout of dermal mast cell PGD2 release capacity.
- *NAC (N-acetylcysteine, 600--1,200 mg/day, glutathione precursor) causing paradoxical fatigue worsening or anhedonia at standard dose:* NAC supplies cysteine for glutathione (GSH) synthesis — the rate-limiting substrate for the body's primary antioxidant. Paradoxical worsening implies: (a) cysteine is being diverted from the transsulfuration pathway (cysteine → cystathionine → H₂S) toward GSH synthesis, reducing hydrogen sulfide (H₂S) production — H₂S is a gaseous vasodilator and mitochondrial complex IV electron donor; losing H₂S-mediated vasodilation in an already vasoconstricted system worsens tissue perfusion → fatigue; (b) NAC's thiol group reacts with existing ROS to form intermediate thiol radicals before GSH is fully synthesized — in a system with high baseline oxidative stress, the intermediate thiol-radical burst exceeds the GSH synthetic capacity and produces net oxidative damage; (c) NAC is a weak metal chelator, and at sustained high doses may reduce copper availability for dopamine-β-hydroxylase (DBH; copper-dependent NE synthesis enzyme) — anhedonia and cognitive worsening in a patient already NE-deficient could reflect borderline DBH function tipped below threshold (consistent with @ach:catecholamine-deficit, though this mechanism is speculative at standard oral doses). Diagnostic: (a) worsening at 600 mg that resolves at 1,200 mg → the initial thiol-radical burst exhausted GSH capacity at low dose; higher dose saturates the radical-scavenging pathway and shunts toward net GSH synthesis — confirms high baseline oxidative stress AND functional GSH synthesis machinery; (b) worsening at all doses with no improvement → either chronic thiol stress (GSH system cannot handle any additional cysteine load, consistent with severe oxidative damage overwhelming the system) or H₂S pathway dependence (the patient's tissue perfusion depends on H₂S vasodilation and NAC's diversion of cysteine away from transsulfuration removes this vasodilatory support); (c) cognitive/anhedonia worsening specifically → DBH copper chelation is the dominant mechanism — consistent with catecholamine synthesis deficit (the patient was borderline NE-deficient and NAC pushed DBH below functional threshold). If NAC + selenium (GSH peroxidase cofactor) prevents worsening → selenium deficiency was the bottleneck in GSH recycling — confirms oxidative stress is glutathione-cycle-limited. If NAC improves symptoms → oxidative stress and glutathione depletion are present and rate-limiting — NAC is therapeutic. If NAC produces no effect → either oxidative stress is not rate-limiting, or glutathione is not the bottleneck (consider mitochondrial antioxidants: CoQ10, MitoQ, SkQ1).

*Pattern 4 — Tolerability ceiling imposed by a specific system.* The drug works but cannot be titrated because side effect Y from system Z appears first. The ceiling identifies which system has the least reserve.

- *Ivabradine limited by bradycardia before POTS HR symptom control is achieved:* The SA node's intrinsic firing rate reserve is exhausted. The sinus node is operating near its lower functional limit even at rest — consistent with intrinsic SA node dysfunction (possibly from cardiac NCX1 reversal, @spec:ch10-cardiac-ncx-reversal) or ganglionic cholinergic overactivity. Diagnostic: the chronotropic incompetence is not purely autonomic — there is also a structural/ionic SA node limitation.
- *Guanfacine limited by hypotension before cognitive benefit:* α2A-mediated central sympathetic suppression reduces BP below tolerable threshold. The sympathetic nervous system is maintaining blood pressure — remove even a fraction of central sympathetic outflow and BP crashes. Diagnostic: the patient is sympathetically dependent for hemodynamics. Midodrine (peripheral α1 agonism) should be co-administered to maintain BP while guanfacine provides prefrontal cognitive benefit. Without midodrine, guanfacine's cognitive benefit is inaccessible because hemodynamics collapse first.
- *Memantine limited by brain fog/sedation before glutamatergic benefit:* NMDA antagonism reduces excitatory neurotransmission broadly — not just at pathological quinolinic-acid-driven synapses but at normal glutamatergic circuits. If sedation appears at doses below therapeutic range for cognitive improvement, the patient's glutamatergic system has insufficient reserve — basal glutamate tone is already low (consistent with regional brain hypometabolism on FDG-PET, @sec:cns) and further NMDA blockade tips cognition over a cliff. Diagnostic: this patient needs glutamatergic tone enhancement, not reduction. The cognitive dysfunction is from insufficient excitation, not excessive quinolinic-acid-driven excitation. Kynurenine pathway may be producing kynurenic acid (NMDA antagonist) dominance rather than quinolinic acid (NMDA agonist) excess.
- *Ketamine (sub-anesthetic, 0.1--0.5 mg/kg IV or 10--30 mg intranasal) producing psychotomimetic effects (hallucinations, dissociation, anxiety) at doses below analgesic threshold:* Ketamine is a non-competitive NMDA antagonist with additional opioid and HCN1 channel activity. At sub-anesthetic doses, psychotomimetic effects indicate NMDA receptor functional reserve is critically low — the same NMDA hypofunction that ketamine should probe (quinolinic-acid-driven excitotoxicity → ketamine blocks the excessive NMDA activation) instead produces subjective psychosis because basal NMDA tone is already below the threshold for normal cognitive integration. Diagnostic: (a) psychotomimetic sensitivity at 0.1 mg/kg → severe NMDA hypofunction; the patient's NMDA system cannot buffer even minimal antagonism — consistent with kynurenic acid dominance (NMDA antagonist) rather than quinolinic acid excess (NMDA agonist); (b) the dissociation distinguishes NMDA hypofunction from NMDA excitotoxicity — if ketamine were blocking pathological quinolinic-acid-driven NMDA overactivation, cognitive clarity should improve (as it does in some chronic pain patients). Instead, worsening hallucination/dissociation confirms that NMDA tone is globally deficient, not regionally excessive. If ketamine produces rapid-pain-relief-without-psychotomimesis → the pain is quinolinic-acid-driven NMDA excitotoxicity (consistent with the kynurenine pathway's QUIN arm), and ketamine is blocking a pathological excess, not a physiological function. If ketamine produces rapid mood improvement (antidepressant effect) without pain relief and without psychotomimesis → mTORC1-mediated synaptogenesis is the mechanism (ketamine → AMPA activation → BDNF → mTORC1), not NMDA antagonism. Diagnostic sequence: if ketamine null for all → NMDA system not rate-limiting for pain, cognition, or mood — consider cholinergic or inflammatory mechanisms instead.
- *Celecoxib/etoricoxib (COX-2 selective) causing fatigue worsening or cognitive impairment before anti-inflammatory benefit:* COX-2 is constitutively expressed in brain (hippocampus, cortex, hypothalamus) where COX-2-derived PGE2 regulates synaptic plasticity, cerebral blood flow via EP2/EP4 receptors on vascular smooth muscle, and hypothalamic-pituitary function. In a system already energy-compromised, COX-2 inhibition reduces PGE2 → (a) loss of PGE2-mediated cerebral vasodilation → reduced cerebral perfusion → cognitive fog worsens before inflammation resolves; (b) loss of PGE2-mediated mitochondrial biogenesis (PGE2 → EP4 → cAMP → PGC-1α) → mitochondrial ATP production drops in cells that were relying on PGE2 signaling to maintain energy metabolism; (c) PGE2 suppression removes a critical input to the hypothalamic-pituitary axis → cortisol output drops → fatigue from relative hypocortisolism in a patient with already-borderline HPA axis function. Diagnostic: fatigue worsening on COX-2 inhibitor traces the magnitude of the system's dependence on COX-2-derived PGE2 for three separate functions — cerebral perfusion, mitochondrial maintenance, and HPA axis drive. If celecoxib improves symptoms without fatigue → COX-2-mediated inflammation is the dominant PGE2 effect; PGE2 signalling in mitochondria and HPA axis is intact (COX-2-derived PGE2 was driving neuroinflammation, not tissue maintenance). If celecoxib worsens fatigue at 100 mg BID → try to increase CoQ10/creatine (mitochondrial bypass) + maintain adequate hydration (cerebral perfusion) + monitor morning cortisol to determine which of the three PGE2 functions is the ceiling. If celecoxib produces no effect at all → COX-2 is not rate-limiting for the patient's current inflammatory state; the inflammation is COX-1-driven, complement-driven, mast-cell-driven, or non-inflammatory (metabolic, autoimmune).
- *Methylphenidate limited by tachycardia, insomnia, or post-dose crash before cognitive benefit:* Methylphenidate blocks NET and DAT, raising synaptic NE and DA. In a patient reliant on NE reuptake for maintaining baseline catecholamine tone, reuptake blockade causes sympathetic overactivation (tachycardia exceeding POTS tolerance, anxiety, vasoconstriction) at doses where DAT occupancy is still suboptimal for cognitive benefit. The +7% REE increase from methylphenidate in an already energy-compromised patient produces a net negative energy balance — the brain works but the body depletes faster. Post-dose crash from dopamine depletion after reuptake block wears off creates a binge-crash pattern that maps onto PEM. Diagnostic: this patient's cognitive dysfunction is from NE deficiency (the drug worked on cognition but the sympathetic side effects prevent titration), confirming the noradrenergic hypothesis (@ach:catecholamine-deficit). The specific ceiling (tachycardia vs crash vs insomnia) identifies the weakest link in NE/DA homeostatic capacity. If tachycardia is first ceiling → hyperadrenergic POTS component; atomoxetine (pure NRI) should be tried, since it produces less HR increase while still correcting prefrontal NE deficiency. If crash is first ceiling → DA depletion is primary; add CoQ10/NADH for mitochondrial ATP regeneration capacity. If insomnia is first ceiling → DAT occupancy is too high for the patient's orexin drive; split dosing or switch to modafinil (DAT block without the hypothalamic arousal overdrive of full NDRI).
- *Amphetamines (dextroamphetamine, lisdexamfetamine) causing severe post-dose crash indistinguishable from PEM:* Amphetamines deplete vesicular dopamine via VMAT2 inhibition and reverse DAT/NET direction, releasing catecholamines from terminals. In a patient with borderline intact dopaminergic terminals (subclinical VMAT2 deficiency), a single dose of amphetamine depletes the remaining vesicular stores — the crash is genuine monoamine depletion, not just receptor downregulation. This crash is pharmacologically indistinguishable from a PEM episode: extreme fatigue, mental depression, sleep EEG changes lasting 3--4 weeks. Diagnostic: amphetamine-induced crash confirms VMAT2 terminal compromise. The patient's dopaminergic system cannot sustain the catecholamine demand of a releasing agent — implying fewer surviving terminals (consistent with Liu 2026 VMAT2 PET in long COVID) and fragile vesicular storage. This patient should NEVER receive amphetamines again. The strong response-to-total-crash trajectory is a high-specificity pharmacodiagnostic for VMAT2 pathology. If amphetamines produce NO response (no cognitive benefit AND no crash) → two possibilities: (a) DAT is already saturated or absent (severe terminal loss beyond what VMAT2 PET would show), or (b) the dopamine system is not the bottleneck — the cognitive dysfunction is from a non-dopaminergic mechanism (glutamatergic, cholinergic, or inflammatory).
- *Modafinil/armodafinil dose-limited by insomnia or next-day fatigue, not by lack of efficacy:* Modafinil blocks DAT (raising synaptic DA) and activates histaminergic and orexin systems. Insomnia at doses above 100 mg implies the orexin/histamine arousal axis is hypersensitive — small increases in extracellular DA via DAT block are sufficient to fully activate a system that was already at threshold (consistent with the orexin-suppression model: the system is turned off at baseline, not broken, and DAT block releases the brake). Next-day fatigue (not insomnia) implies delayed metabolic cost catching up — the +7% REE from elevated wakefulness depletes already-limited energy reserves overnight. Diagnostic: distinct from methylphenidate crash; modafinil's DAT-only action means NE is not involved. If insomnia is the ceiling → orexin/histamine tone is intact and DA-sensitive → try pitolisant (H3 inverse agonist, releases endogenous histamine without DAT-mediated DA increase). If next-day fatigue (not insomnia) is the ceiling → energy reserve is the bottleneck, not arousal; add mitochondrial support before retrying. If modafinil produces NO response (no benefit, no insomnia, no crash) → DAT dysfunction — the transporter is absent, blocked by autoantibodies, or genetically non-functional — making all DAT-targeting strategies futile.
- *Solriamfetol dose-limited by BP/HR elevation without cognitive benefit:* Solriamfetol is a pure DNRI (selective DA/NE reuptake inhibitor) with no releasing activity. If systolic BP or HR increase appears at sub-therapeutic doses for cognition, the patient's noradrenergic system is intact and responsive — NE reuptake inhibition produces the expected sympathetic effect but at the wrong dose window. The dissociation (cardiovascular response but no cognitive response) localizes the cognitive deficit: the prefrontal NE system is either desensitized (α2A receptors downregulated from chronic stress/inflammation) or anatomically disconnected (white-matter loss in PFC-cingulate tracts). Diagnostic: NE is available at the synapse but the prefrontal cortex cannot use it — consistent with the prefrontal hypometabolism model (@ach:catecholamine-deficit). Guanfacine (direct α2A agonism, bypassing endogenous NE release) should be tried: it directly stimulates postsynaptic α2A receptors on prefrontal pyramidal neurons irrespective of NE release. If guanfacine works where solriamfetol did not → confirms the lesion is postsynaptic receptor function, not presynaptic NE availability. If solriamfetol produces cognitive benefit with no BP/HR effect → the NE system is intact and tone is normal — the cognitive dysfunction is DA-mediated (the DNRI's DA component is providing the benefit), not NE-deficiency. Switch to a pure DRI or L-DOPA.
- *Pitolisant dose-limited by insomnia or headache before cognitive/mast cell benefit:* Pitolisant is an H3 inverse agonist that releases endogenous histamine and promotes M1→M2 microglial polarization. Insomnia at low doses (4.5--9 mg) implies the histaminergic arousal system is already near its activation threshold — the H3 brake is barely on and removing even a fraction releases histamine enough to disrupt sleep. The histaminergic system is intact but suprachiasmatically or orexin-driven suppressed. Diagnostic: this patient's sleep-wake cycle is on a hair trigger — consistent with orexin suppression model (orexin neurons are actively inhibited by microglial inflammation; removing the H3 brake releases histamine and counteracts the orexin deficit during wake but cannot be sustained during sleep). If headache is the ceiling → histamine-mediated vasodilation is the limiting factor; consistent with vascular hyper-reactivity (MCAS component). If pitolisant improves cognitive AND mast-cell symptoms → histaminergic anti-inflammatory mechanism (M1→M2 switch) confirmed. If pitolisant produces NO response at all → the histaminergic system is not the bottleneck — either H3 receptors are downregulated or histamine synthesis is depleted (rare: histidine deficiency or HNMT overactivity).
- *Valganciclovir dose-limited by bone marrow suppression before antiviral effect:* Valganciclovir inhibits viral DNA polymerase in EBV, HHV-6, CMV. Bone marrow suppression (neutropenia, anemia, thrombocytopenia) is dose-dependent. If neutropenia (ANC dropping below 1,500) occurs at subtherapeutic doses for antiviral effect (below 900 mg/day), the bone marrow has no haematopoietic reserve — implying chronic inflammation-driven myelosuppression, haematopoietic stem cell exhaustion, or cytokine-mediated suppression of granulopoiesis. Diagnostic: this patient cannot support an intensive antiviral trial without G-CSF support or marrow-protective strategies. If bone marrow suppression is absent even at full therapeutic doses (1,800 mg/day) → marrow reserve is intact, HSC pool is healthy — excludes HSC-level pathology and chronic myelosuppression as components of their ME/CFS. If valganciclovir causes renal toxicity (creatinine rise) at low doses → renal function is already compromised; acyclovir (renally cleared) cannot be safely dosed either. The pattern of which organ system hits its ceiling first (bone marrow vs kidney vs GI) identifies the weakest organ system in that patient — which may itself be a clue to their dominant pathology.
- *Valacyclovir dose-limited by CNS effects (confusion, hallucination) or renal toxicity:* Valacyclovir is renally cleared; CNS effects appear when renal clearance is impaired and acyclovir accumulates. If confusion or hallucinations occur at standard doses (1,000 mg TID) → renal clearance is subnormal even if serum creatinine is within normal range (creatinine can remain normal until ~50% GFR loss). Cystatin C should be measured to detect occult renal impairment. Diagnostic: this patient has subclinical renal insufficiency undetected by standard labs. The CNS toxicity is a pharmacodiagnostic for renal reserve, not CNS vulnerability. If CNS effects occur despite normal cystatin C and CrCl → blood-brain barrier integrity is compromised (neuroinflammation increases BBB permeability to acyclovir), or the patient is a CYP poor metabolizer with abnormally high valacyclovir-to-acyclovir conversion. If valacyclovir causes no renal or CNS effects at full dose after 6+ months → renal clearance and BBB integrity are intact — excludes both renal compromise and significant BBB disruption as components of their ME/CFS.
- *DORA (daridorexant, suvorexant, lemborexant) producing sleep paralysis or complex sleep behaviours before sleep maintenance improvement:* DORAs block OX1R/OX2R orexin receptors, suppressing wakefulness drive. Sleep paralysis (consciousness during REM atonia) or complex behaviours (sleep-walking) occur because orexin is not just a wake promoter — it also gates REM-NREM transitions and suppresses motor activity during REM. If sleep paralysis occurs at low doses (25 mg daridorexant) → the patient's orexin tone is critically low at baseline (consistent with the orexin-suppression model, @sec:microglial-cascade Step K2a); orexin receptor blockade pushes a system that was already near REM-entry threshold over the edge. Diagnostic: this patient has borderline narcolepsy-level orexin deficiency. A CSF orexin-A measurement is warranted. DORAs are contraindicated — this patient needs orexin agonism (pitolisant, OX2R agonist), not antagonism. If DORAs improve sleep maintenance without sleep paralysis → orexin tone is normal; the benefit comes from suppressing pathological nocturnal orexin surges, not from blocking absent orexin. If DORAs produce NO effect on sleep maintenance → orexin tone is so low that receptor blockade produces no further suppression (floor effect); consistent with severe orexin deficiency — the DORA is blocking receptors that are no longer being activated endogenously.
- *Trazodone dose-limited by next-day sedation or orthostatic hypotension before sleep initiation benefit:* Trazodone at 25--50 mg blocks 5-HT2A, H1, and α1 receptors. Next-day sedation at 50 mg → H1 receptor supersensitivity or slow CYP2D6 metabolism (the active metabolite mCPP accumulates). If the patient has severe morning fatigue on trazodone but sleep quality improves → the glymphatic benefit (slow-wave sleep enhancement via 5-HT2A blockade) is achieved but H1-mediated next-day sedation erases daytime function. The sedation ceiling identifies that H1 tone is the limiting system. Orthostatic hypotension at 25 mg → α1 receptor blockade is clinically significant; the patient's BP depends on α1 adrenergic tone (consistent with neuropathic POTS). If the patient tolerates trazodone 25 mg without next-day sedation → H1 receptors are desensitized (chronic histamine exposure from MCAS), and CYP2D6 metabolism is normal. This patient should try higher doses for slow-wave sleep enhancement. If trazodone produces priapism → a rare pharmacodiagnostic for intact α1-mediated vascular smooth muscle function in penile arteries (does not generalize as a systemic probe).
- *Low-dose doxepin (3--6 mg) producing no sedation improvement for sleep maintenance:* Doxepin at 3--6 mg is a pure H1 antagonist (no serotonergic/noradrenergic activity at this dose). If it fails to improve sleep maintenance → H1-mediated histaminergic arousal is not the cause of nocturnal awakenings. The awakenings are from a non-histaminergic mechanism: (a) orexin surges (consistent with orexin-suppression model — the system oscillates between suppression and rebound activation), (b) adrenergic surges (hyperadrenergic POTS, nocturnal sympathetic activation), or (c) pain-driven awakenings. If doxepin provides excellent sleep maintenance at 3 mg → histaminergic arousal is the dominant cause of awakenings; consistent with MCAS with CNS involvement (nocturnal mast cell degranulation → histamine release → arousal). If doxepin causes next-day sedation at 3 mg → H1 receptors are supersensitive, consistent with histaminergic insufficiency (not excess) — histamine is needed for daytime wakefulness and minimal blockade tips the patient into hypersomnia.
- *Melatonin (0.5--3 mg) producing paradoxical alertness or fragmented sleep:* Melatonin normally advances circadian phase and reduces sleep latency. Paradoxical alertness implies: (a) the patient's circadian phase is so severely delayed that melatonin given at the "normal" bedtime is hitting a phase where melatonin receptors are desensitized (the patient's endogenous melatonin peak is at 4 AM, not 11 PM); (b) melatonin is being metabolized abnormally (CYP1A2 ultra-rapid metabolizer → short duration of action triggers rebound arousal); or (c) the patient has a melatonin receptor polymorphism (MTNR1B variant) altering signalling direction. If melatonin causes vivid nightmares → melatonin disinhibits REM sleep in a patient with pre-existing REM sleep dysregulation (consistent with alpha-delta sleep, @sec:cns sleep section). If melatonin produces NO effect on sleep latency at 3 mg → either: (a) the patient's sleep-onset insomnia is not circadian (it is hyperarousal-driven — orexin/noradrenergic), (b) the pineal gland is producing maximal endogenous melatonin already (supplementation cannot add), or (c) MT1/MT2 receptors are downregulated from chronic exogenous supplementation or inflammation.
- *Rapamycin (sirolimus) dose-limited by immunosuppression or hyperlipidaemia before metabolic/mitophagy benefit:* Rapamycin inhibits mTORC1 at low doses (1--3 mg/week) to restore autophagy and mitophagy. At higher doses, mTORC2 inhibition adds immunosuppression (impaired T-cell proliferation, infection risk) and hyperlipidaemia (altered hepatic lipid metabolism). If immunosuppression markers (reduced lymphocyte count) appear at doses below the metabolic benefit threshold → the mTORC1/mTORC2 selectivity ratio is narrow — rapamycin is not viable for chronic metabolic use in this patient. If metabolic benefit (improved exercise tolerance) at 3 mg/week without immunosuppression → clear mTORC1 selectivity; long-term use possible. The immunosuppression ceiling IS the mTORC1 selectivity measurement. If hyperlipidaemia at low dose → hepatic mTORC1 is particularly sensitive; lipid monitoring essential. If impaired wound healing → mTORC2-mediated epithelial repair is the ceiling; the patient's tissue turnover relies on mTORC2 more than expected.
- *Nattokinase/lumbrokinase dose-limited by bleeding risk before microclot clearance benefit:* These fibrinolytic enzymes degrade fibrin directly (serine protease activity). Bleeding risk (epistaxis, gingival bleeding, easy bruising) appears because the same activity that degrades pathological microclots also degrades physiological fibrin at wound sites. If bleeding appears at doses (2,000--4,000 FU/day) below the microclot clearance threshold → the haemostatic reserve is narrow; microclots are degradation-resistant (cross-linked, amyloid), or baseline coagulation is already fragile (low fibrinogen, impaired platelet function, or fragile microvasculature from connective tissue laxity). Diagnostic: the bleeding ceiling-to-benefit ratio quantifies the distance between pathological and physiological fibrin dependence. If no bleeding even at high doses (8,000+ FU/day) → wide fibrinolytic reserve; robust coagulation. If neither bleeding NOR clinical improvement → microclots are not rate-limiting for PEM — the mechanism is metabolic, mitochondrial, or neuroinflammatory, not microvascular obstruction.
- *Levetiracetam dose-limited by psychiatric adverse effects or sedation before anti-kindling benefit:* Levetiracetam binds SV2A, reducing neurotransmitter release probability in circuits undergoing kindling (repeated subthreshold stimulation → progressively increasing response). In ME/CFS, if PEM represents a kindling-like process, SV2A binding should reduce PEM frequency and severity. Psychiatric adverse effects (agitation, depression, suicidal ideation) at 250--500 mg/day (below anti-kindling threshold of 1,000--3,000 mg/day) imply the limbic neurotransmitter system has minimal reserve — consistent with DA deficiency and serotonergic depletion from the kynurenine pathway. Sedation at low dose implies global cortical/thalamic suppression in a system near its activation threshold (consistent with FDG-PET regional hypometabolism). Diagnostic: levetiracetam is the highest-specificity probe for the neuronal kindling hypothesis of PEM. Positive response confirms PEM is neuroplastic; null response shifts differential to metabolic or microvascular mechanisms.
- *GLP-1 agonists (semaglutide, tirzepatide) dose-limited by unacceptable lean mass loss or severe GI intolerance before anti-inflammatory benefit:* GLP-1 agonists suppress appetite, slow gastric emptying, and reduce systemic inflammation (CRP reduction of 20--40% independent of weight loss). If anti-inflammatory benefit (reduced CRP, improved symptoms) is achieved but accompanied by unacceptable lean mass loss (sarcopenia, weakness, functional decline) → the patient's basal metabolic rate depends on GLP-1-sensitive energy allocation — reducing caloric intake further depletes an already energy-compromised system, and the lean mass loss confirms that muscle protein synthesis cannot keep pace with the catabolic state imposed by caloric restriction. Diagnostic: this patient's energy deficit is so severe that any reduction in caloric intake — even with the anti-inflammatory benefit of GLP-1 agonism — costs more in functional lean mass than it returns in inflammatory suppression. GLP-1 agonists are contraindicated in sarcopenic ME/CFS. If GI intolerance (severe nausea, vomiting, gastroparesis) appears before anti-inflammatory benefit → the patient's gastric motility is already compromised (consistent with vagal dysfunction, enteric neuropathy, or gastroparesis from GPCR AAb). GLP-1 agonists worsen gastroparesis by slowing gastric emptying further. If anti-inflammatory benefit without significant lean mass loss → the patient has adequate metabolic reserve; GLP-1 agonism is usable. If NO anti-inflammatory benefit despite adequate dosing and tolerance → GLP-1R signaling pathway is not rate-limiting for inflammation in this patient; the inflammation is GLP-1R-independent (complement-driven, mast-cell-driven, TLR4-driven, or inflammasome-driven).
- *DCA (dichloroacetate) dose-limited by peripheral neuropathy before PDH activation benefit:* DCA inhibits PDK, restoring PDH activity and reducing lactate accumulation. Peripheral neuropathy (stocking-glove distribution, axonal sensorimotor) is the dose-limiting toxicity — cumulative doses above ~30 g produce reversible neuropathy in most patients, with some developing irreversible damage. If neuropathy appears at low cumulative doses (under 10 g) → the patient's peripheral nerves are already vulnerable (consistent with pre-existing small-fiber neuropathy, IENFD reduction, or neuropathic POTS). Diagnostic: DCA neuropathy onset at low cumulative dose confirms pre-existing peripheral nerve fragility — the neuropathy is unmasked, not caused de novo. If PDH benefit (reduced lactate, improved exercise tolerance) appears at doses below the neuropathy threshold → PDH phosphorylation is confirmed as rate-limiting AND the therapeutic window is accessible in this patient. If DCA produces no lactate reduction despite adequate dosing → PDH is not rate-limiting; the metabolic block is downstream of PDH (TCA cycle, ETC, or ATP synthase). DCA is the highest-specificity probe for PDH in the entire chapter — a null response eliminates PDH as the bottleneck. If DCA is unavailable → the thiamine response pattern (@sec:pdh-cascade E2) provides a lower-specificity but accessible alternative.
- *Metformin/berberine dose-limited by GI intolerance before AMPK-mediated metabolic benefit:* Both agents activate AMPK (metformin through complex I inhibition → AMP/ATP ratio increase, berberine through direct AMPK phosphorylation and mitochondrial complex I inhibition). GI intolerance (cramping, diarrhoea, nausea) at 500 mg metformin or 500 mg berberine — well below the standard Type 2 diabetes starting doses — implies: (a) enterocyte mitochondrial vulnerability — the gut epithelium has the highest turnover rate of any tissue and is exquisitely ATP-dependent; even mild complex I inhibition tips ATP below the threshold for tight junction maintenance → osmotic diarrhoea; (b) the gut microbiome is AMPK-sensitive — berberine's additional bile-acid-modulating and antimicrobial effects compound the GI disruption; (c) metformin's serotonin release from enterochromaffin cells (5-HT3-mediated) triggers nausea at doses where AMPK activation is minimal. Diagnostic: GI ceiling at micro-dose identifies which metabolic probe (metformin vs. berberine) is better tolerated — if berberine causes GI but metformin does not, bile-acid/gut-microbiome disruption is the mechanism (berberine-specific); if metformin causes GI but berberine does not, 5-HT3 serotonergic gut hypersensitivity is the mechanism (metformin-specific). If both cause GI at microdoses → gut epithelial ATP deficit is severe — any mitochondrial complex I inhibition collapses enterocyte function. If berberine causes hypoglycemia at 500 mg → gluconeogenesis is already impaired (AMPK activation suppresses hepatic gluconeogenesis, and in a patient with borderline glucose production, even mild suppression tips glucose below threshold). If NO GI at 1,000+ mg of either → enterocyte mitochondria and gut microbiome are resilient; AMPK pathway is accessible. If neither produces metabolic benefit despite adequate dosing → AMPK pathway is not the rate-limiting bottleneck for systemic metabolism; the lesion is downstream of AMPK (mitochondrial, not signaling).
- *NADH (5--20 mg/day, Complex I electron donor) causing paradoxical fatigue worsening:* NADH feeds electrons directly into Complex I of the ETC. Worsening fatigue at 5 mg implies Complex I is functional and accepting electrons, but the downstream ETC is blocked — electrons leak at the block site (usually Complex III or IV) → superoxide production → oxidative stress worsens. Diagnostic: the divergence between NADH and CoQ10 worsening maps the ETC block site. NADH worsen + CoQ10 neutral → the block is between Complex I and the CoQ10 pool — Complex I dysfunction with intact Complex III/IV. CoQ10 worsen + NADH neutral → the block is at Complex III (CoQ10 feeds electrons into a blocked Complex III). Both worsen → global ETC dysfunction (severe damage). Neither worsens but no benefit → bottleneck is upstream (TCA cycle substrate supply) or downstream (ATP synthase, ANT, or ATP utilization), not electron transfer. If NADH improves fatigue at 5 mg → Complex I electron deficiency confirmed; the downstream ETC is functionally intact — this is a highly specific probe for Complex I as the rate-limiting node.

*Pattern 5 — Absence of an expected side effect.* The system that should produce the side effect is too damaged to respond.

- *Midodrine producing no piloerection (goosebumps) or scalp tingling at therapeutic doses:* α1 receptors on piloerector muscles and scalp vasculature are not responding. These are the most accessible clinical readouts of peripheral α1 receptor function. If midodrine raises BP but produces no piloerection, the vascular α1 receptors are functional but the cutaneous α1 receptors are denervated or desensitized — suggests a length-dependent sympathetic neuropathy (longest fibers to skin affected first). Diagnostic: confirms neuropathic POTS with small-fiber-predominant sympathetic denervation pattern. Skin biopsy for intraepidermal nerve fiber density (IENFD) should show reduction in lower extremities.
- *Caffeine producing no tachycardia or alertness:* Adenosine A2A receptors are desensitized from chronic overstimulation (patient has been self-medicating with caffeine for years), or the sympathetic nervous system cannot mount a catecholamine response to adenosine blockade. If caffeine produces no HR increase AND midodrine works → the sympathetic effector pathway is functional (α1 receptors respond to direct agonist) but the central sympathetic activation from adenosine blockade fails — consistent with central catecholamine deficiency (@ach:catecholamine-deficit).
- *Antihistamines producing no sedation:* Histamine H1 receptors in the CNS are already saturated or desensitized from chronic mast cell degranulation. The absence of the expected sedative side effect of first-generation antihistamines (diphenhydramine, hydroxyzine) implies: (a) the histaminergic arousal system is tonically suppressed — consistent with chronic mast cell activation maintaining high CNS histamine exposure, leading to H1 receptor downregulation; or (b) the orexin/histamine arousal axis is non-functional (consistent with orexin suppression model). Diagnostic: this patient has MCAS with CNS involvement. The absence of antihistamine sedation is a biomarker of chronic CNS histamine exposure.
- *Droxidopa producing no improvement in orthostatic symptoms:* Droxidopa is a synthetic NE precursor that crosses the BBB and is converted to NE by aromatic L-amino acid decarboxylase (AADC) in both central and peripheral neurons. Expected effect: increased NE → peripheral vasoconstriction → reduced orthostatic tachycardia. If droxidopa produces no orthostatic improvement → AADC activity is deficient or NE stores cannot be loaded (VMAT2 dysfunction) — the precursor arrives but cannot be converted or stored. If midodrine works but droxidopa does not → the lesion is presynaptic (NE synthesis/storage), not postsynaptic (α1 receptor). Confirms the catecholamine synthesis deficit model (@ach:catecholamine-deficit) and is consistent with VMAT2 terminal loss. If droxidopa causes supine hypertension without orthostatic benefit → AADC is active and NE is being synthesized, but the postsynaptic vasculature is desensitized — consistent with hyperadrenergic POTS (α1 receptors downregulated from chronic NE overstimulation). Diagnostic: droxidopa probes NE synthesis capacity; midodrine probes α1 receptor function. Together they distinguish presynaptic vs postsynaptic noradrenergic lesions.
- *Corticosteroids (prednisone, methylprednisolone, hydrocortisone) producing rapid improvement followed by severe crash on taper:* Expected: corticosteroids suppress inflammation broadly → symptom improvement within hours to days. Rapid improvement confirms that inflammation is driving symptoms — but the improvement does not distinguish viral, autoimmune, or mast-cell-mediated inflammation. The crash on taper is the diagnostic signal: if the patient crashes within 24--48 hours of dose reduction → the HPA axis is suppressed and cannot produce endogenous cortisol to compensate (iatrogenic adrenal insufficiency from even short-course steroids, consistent with underlying HPA axis dysfunction, @sec:hpa-axis). If the patient shows no improvement at all → inflammation is not rate-limiting for their current symptom state, or the inflammation is steroid-resistant (NF-κB-independent pathways, inflammasome-driven). Diagnostic: corticosteroid response localizes inflammation as present and rate-limiting but does not identify the source. The crash-on-taper identifies HPA axis fragility — this patient cannot produce endogenous glucocorticoids under stress.
- *CoQ10, NADH, creatine, or L-carnitine producing paradoxical fatigue worsening (not improvement):* These supplements support mitochondrial ATP production (ETC shuttle, electron donor, ATP buffer, fatty acid shuttle). Paradoxical worsening implies: (a) the mitochondrial defect is downstream of the supplementation point — the ETC is so damaged that increasing substrate flux generates ROS without ATP → oxidative stress worsens; (b) carnitine worsening → fatty acid oxidation is already maximal and pushing more substrate through β-oxidation generates lipid peroxides (consistent with impaired antioxidant capacity, low glutathione); or (c) CoQ10 worsening → Complex III is the bottleneck — pushing electrons into Complex I/II without functioning Complex III → electron leak → superoxide production. Diagnostic: absence of improvement is non-informative (common: mitochondrial supplements fail in patients whose bottleneck is not at the supplemented node). Worsening is informative: the supplementation node is intact but the downstream pathway is blocked — adding substrate increases ROS, not ATP. Discontinue and test the next node in the ETC. If CoQ10 worsens → try creatine (bypasses ETC entirely for ATP buffering). If carnitine worsens → try MCT oil (medium-chain triglycerides bypass carnitine-dependent transport).
- *L-DOPA/carbidopa producing severe nausea or orthostatic hypotension at 1/4 tablet (6.25/25 mg):* L-DOPA is converted to dopamine by AADC. Nausea is D2 agonism in area postrema; OH is peripheral D2-mediated vasodilation + central D2 sympathetic suppression. At 1/4 of the Parkinson's starting dose, these effects imply: (a) AADC activity is high (rapid peripheral conversion to dopamine before carbidopa blocks it) — or the patient is taking L-DOPA without adequate carbidopa co-administration; (b) D2 receptors are supersensitive (same receptor upregulation pattern seen with pramipexole and aripiprazole) — confirming chronic dopamine deficiency across multiple dopaminergic drugs; (c) the patient's orthostatic system is dopaminergically vulnerable — confirms neuropathic POTS with dopamine-dependent sympathetic tone. If L-DOPA produces cognitive benefit without nausea/OH → the DA deficiency is severe enough that the AADC step is rate-limiting (not enough endogenous L-DOPA substrate), but D2 receptors are not supersensitive — an intermediate dopamine deficiency phenotype. If L-DOPA produces NO cognitive benefit at all → the lesion is not at the DA synthesis level; either D2/D3 receptors are absent/desensitized, or the cognitive dysfunction is not dopaminergic.
- *Selegiline or rasagiline (MAO-B inhibitor) causing serotonin syndrome at subtherapeutic dose or interacting with previously cleared SSRI:* MAO-B inhibitors prevent dopamine degradation. Rasagiline is selective for MAO-B at all clinical doses (1 mg/day), unlike selegiline which loses selectivity above 10 mg/day. Serotonin syndrome with a previously-tolerated SSRI after starting either agent implies: (a) for selegiline — the dose has exceeded MAO-B selectivity (above 10 mg/day) and MAO-A is now inhibited, or the patient is a CYP2D6 poor metabolizer → selegiline accumulates → MAO-A inhibition at lower doses; (b) for rasagiline — serotonin syndrome despite MAO-B selectivity at 1 mg/day suggests an idiosyncratic MAO-A interaction unique to that patient's serotonergic fragility, or the SSRI had not been adequately washed out. If serotonin syndrome occurs on rasagiline but not selegiline → the mechanism is not MAO-A inhibition (which rasagiline spares) — it may be a rasagiline-specific off-target effect on 5-HT release or metabolism. If serotonin syndrome occurs on selegiline but not rasagiline → confirms the mechanism is MAO-A crossover at supraselective selegiline doses — switch to rasagiline 1 mg for pure MAO-B inhibition. If the patient had stopped the SSRI 14 days ago but still develops serotonin syndrome → the SSRI or its active metabolite had an unusually long half-life (fluoxetine/norfluoxetine: 4--16 days), and 14 days was insufficient washout. Diagnostic: the comparison between rasagiline and selegiline distinguishes MAO-B-selective vs. MAO-A crossover toxicity — rasagiline positive (serotonin syndrome) at 1 mg excludes MAO-A inhibition as the mechanism and implicates an idiosyncratic serotonergic vulnerability. If MAO-B inhibition produces no cognitive or fatigue benefit despite near-complete MAO-B suppression (rasagiline 1 mg/day or selegiline under 10 mg/day achieves over 90 percent MAO-B inhibition in striatum) → DA degradation is not the rate-limiting step — DA synthesis, release, or postsynaptic receptor function is the bottleneck. If MAO-B inhibition works synergistically with L-DOPA (greater than additive) → DA synthesis (L-DOPA) and DA degradation (MAO-B) are both rate-limiting; combined intervention is required. Never prescribe MAOIs in ME/CFS without genotyping CYP2D6 and verifying complete SSRI washout with a negative serum drug level.
- *Ambroxol producing no TRPV1-mediated pain reduction or PEM benefit:* Ambroxol is a TRPV1 antagonist (in addition to its mucolytic and Nav1.8 blocking properties). If ambroxol 30--120 mg/day produces no reduction in localized muscle pain or PEM severity → TRPV1-mediated pain or arteriolar vasoconstriction is not rate-limiting. Distinguish: (a) TRPV1 channels are not involved in the pain/PEM mechanism — sensory TRPV1 and vascular TRPV1 are both non-contributory, consistent with the null capsaicin response pattern (@sec:trpv1-cascade B1); (b) ambroxol does not reach arteriolar smooth muscle TRPV1 at clinical doses — the mucolytic effect is achieved (bronchial secretion clearance) but systemic TRPV1 blockade at vascular concentrations is insufficient; or (c) TRPV1 is present and rate-limiting but ambroxol's TRPV1 affinity is too low at therapeutic concentrations — a selective TRPV1 antagonist (NEO6860) would be needed to test the hypothesis. If ambroxol produces PEM reduction where capsaicin does not → TRPV1 antagonism (ambroxol blocks) is more effective than desensitization (capsaicin depletes), implying the TRPV1 channels are constitutively active (tonic opening from sustained metabolite exposure) rather than sensitized (lowered activation threshold from PGE2). Constitutive TRPV1 activity is consistent with chronic ischemia — the channels are open at rest because the tissue is always producing metabolites at baseline. If ambroxol improves airway symptoms (reduced cough, improved sputum clearance) but not PEM → the mucolytic mechanism is the only clinical effect; TRPV1 is not rate-limiting for PEM even though mucolytic benefit confirms the drug reached systemic circulation. If ambroxol produces GI upset (nausea, abdominal pain) consistent with TRPV1 antagonism in gut → enteric TRPV1-expressing afferents are hypersensitive, consistent with visceral hypersensitivity and IBS overlap in ME/CFS. The GI side effect confirms systemic TRPV1 engagement even if skeletal muscle TRPV1 blockade is insufficient for PEM benefit — the drug is reaching TRPV1 channels, but the affected tissue compartment (gut, not muscle) determines the clinical effect.
- *Corticosteroid non-response despite high inflammatory markers:* If CRP/ESR are elevated and corticosteroids produce no symptom improvement → the inflammation is steroid-resistant. Distinguish: (a) inflammasome-driven inflammation (NLRP3 → IL-1β, IL-18 — corticosteroids do not suppress the inflammasome; colchicine or anakinra would work); (b) complement-driven inflammation (C3a/C5a anaphylatoxins — corticosteroids do not suppress complement activation; C1 inhibitor or eculizumab would work); (c) mast-cell-driven inflammation (histamine, tryptase, prostaglandins — corticosteroids partially suppress but mast cell stabilizers are more specific); or (d) the inflammation is a downstream consequence, not the driver — treating it doesn't change the disease trajectory. Diagnostic: steroid non-response despite systemic inflammation shifts focus to inflammasome/complement/mast-cell pathways.
- *Dimethyl fumarate (DMF) producing severe flushing or GI intolerance before Nrf2 benefit:* DMF activates Nrf2 (antioxidant master regulator). Flushing is prostaglandin D2-mediated from mast cell degranulation (DMF non-specifically activates hydroxycarboxylic acid receptor 2 on mast cells). If flushing is severe at 120 mg → mast cells are hyper-reactive. Pre-treat with aspirin (COX inhibitor, blocks PGD2 production) — if aspirin prevents DMF flushing, the mechanism is mast-cell PGD2 release, confirming MCAS. GI intolerance → gut Nrf2 activation causes initial oxidative shift in enterocytes; if GI symptoms persist beyond 2 weeks, gut mucosa cannot adapt. Diagnostic: DMF flushing is a mast cell probe. Mild flushing is expected and non-informative. Severe flushing → active MCAS. Flushing prevented by aspirin → confirms prostaglandin-mediated MCAS (PGD2 subtype), distinct from histamine-mediated MCAS.
- *BC007 or immunoadsorption producing complete non-response:* Both remove GPCR autoantibodies (BC007 via aptamer neutralization, IA via physical removal). Complete non-response after adequate cycles implies: (a) GPCR AAbs are not present in this patient (should be confirmed by pre-treatment AAb panel), (b) GPCR AAbs are present but not rate-limiting — downstream damage is irreversible, or (c) the relevant AAbs are IgM (not removed by IA protein A columns) or rapidly regenerated from a protected plasma cell pool. If BC007 works where IA did not → the relevant AAbs are not removed by protein A columns (IgG3 subclass or IgA), or IA removed them but synthesis outpaced clearance — BC007 neutralizes faster than the body can produce new AAbs. If IA works where BC007 did not → the AAb target is not one of BC007's known aptamers (BC007 targets specific GPCR AAbs). Diagnostic: BC007 response vs IA response narrows the AAb subtype and identifies whether the dominant mechanism is circulating antibody or tissue-bound antibody.
