#import "../../../../shared/environments.typ": *

=== Mechanisms of Impaired T4 to T3 Conversion


The conversion of thyroxine (T4, the major thyroid hormone secreted by the thyroid gland) to triiodothyronine (T3, the metabolically active form) occurs primarily in peripheral tissues through the action of deiodinase enzymes. Three deiodinase isoforms exist, all selenoproteins requiring selenocysteine at their catalytic site. Type 1 deiodinase (DIO1) in liver and kidney contributes a substantial fraction of circulating T3 via outer-ring deiodination. Type 2 deiodinase (DIO2) in brain, pituitary, thyroid, skeletal muscle, heart, and adipose tissue produces local T3 for tissue-specific needs and contributes comparably to circulating T3 in humans. Type 3 deiodinase (DIO3) in multiple tissues inactivates T4 and T3 by inner-ring deiodination, converting T4 to reverse T3 (rT3) and T3 to the inactive isomer 3,3$prime$-T2 (distinct from the biologically active 3,5-T2, which is produced from T3 by DIO1/DIO2 outer-ring deiodination; see Section @sec:t2-diiodothyronine).

#fhypothesis(title: [Cytokine-Mediated Deiodinase Suppression], falsifiability: [weakly], justification: [Falsified if deiodinase enzyme activity is normal despite elevated IL-6/TNF-$alpha$, or if patients with documented deiodinase suppression show normal free T3 and reverse T3 levels])[
The chronic low-grade inflammation documented in ME/CFS (Chapter @ch:immune-dysfunction) likely suppresses deiodinase enzyme activity through multiple mechanisms. Pro-inflammatory cytokines, particularly IL-6 and TNF-$alpha$, directly inhibit DIO1 and DIO2 expression and activity while upregulating DIO3, shifting the balance toward production of inactive reverse T3 rather than active T3. Sustained oxidative stress, documented in ME/CFS (Chapter @ch:energy-metabolism), may irreversibly oxidise the catalytic selenocysteine residues of deiodinases to seleninic acid, though this requires severe and sustained ROS levels beyond what has been directly measured in ME/CFS tissues. Additionally, the mitochondrial dysfunction documented in ME/CFS may impair ATP-dependent cellular uptake of T4, reducing substrate availability for conversion to T3 @ruiznunez2018thyroid.
] <hyp:deiodinase-suppression>

If this hypothesis is correct, it would offer one possible explanation for why increasing thyroid hormone replacement dose (giving more T4) often fails to improve symptoms in ME/CFS patients: the limiting factor would be not T4 availability but rather the capacity to convert T4 to active T3 at the cellular level. However, T4 treatment failure in ME/CFS has multiple competing explanations, including symptom overlap with non-thyroidal causes, the possibility that Low T3 is a protective adaptation, and the fundamental question of whether thyroid dysfunction is relevant to a given patient's presentation.

