#import "../../../shared/environments.typ": *

== Inflammatory Cytokine-Induced Somnolence and Fatigue
<sec:ch15-cytokine-fatigue>

Pro-inflammatory cytokines (IL-1$beta$, IL-6, TNF-$alpha$, IFN-$alpha/gamma$) directly induce fatigue and somnolence through central mechanisms independent of peripheral tissue damage. This section reviews the cytokine-fatigue literature, the specific profile documented in ME/CFS (elevated IL-1$beta$, IL-6, IFN-$alpha$ in subsets), and the downstream signaling pathways by which circulating cytokines access the brain to suppress arousal circuits and activate fatigue-signaling pathways.

=== Cytokine-to-Brain Signaling Routes

Peripheral cytokines communicate with the brain through three complementary routes @Dantzer2000neural @McCusker2013. The _humoral pathway_ operates via circumventricular organs—notably the organum vasculosum of the lamina terminalis (OVLT) and the area postrema—where an incomplete blood-brain barrier permits direct cytokine diffusion into adjacent hypothalamic tissue. A _saturable transport pathway_ operates through carrier-mediated influx systems at the BBB endothelium for IL-1$beta$, IL-6, and TNF-$alpha$ @McCusker2013. The _neural pathway_ exploits vagal afferents: cytokines at peripheral infection sites activate cytokine receptors on paraganglia of the vagus nerve, transmitting immune signals to the nucleus tractus solitarius and thence to hypothalamic circuits within minutes @Dantzer2000neural @Huerta2025vagal.

At the BBB endothelium and within perivascular spaces, circulating cytokines trigger prostaglandin E#sub[2] (PGE#sub[2]) synthesis, which diffuses into the hypothalamic parenchyma to activate EP3 receptors, suppressing wake-active orexin neurons and promoting sleep-pressure circuits. Microglia—the brain's resident immune cells—amplify this signal via TLR4/NF-$kappa$B activation, producing local IL-1$beta$, IL-6, and TNF-$alpha$ that sustain the fatigue state long after peripheral cytokine levels normalize @McCusker2013.

=== Quantitative Human Cytokine-Fatigue Relationships

<obs:cytokine-fatigue-correlation>
Vollmer-Conna et al. @VollmerConna2004 demonstrated in prospective cohorts with documented EBV, Q fever, and Ross River virus infection that IL-1$beta$ and IL-6 levels correlate directly and quantitatively with fatigue severity, malaise, pain, mood disturbance, and cognitive slowing. Higher peripheral cytokine burdens predict worse sickness symptom scores, establishing a dose-dependent relationship in humans analogous to animal model data (study: multiple infection cohorts, natural infection setting, certainty: Medium-High). However, Omdal et al.\ (2026, n=96) found that severely fatigued long-COVID patients (fVAS 63 vs 5) show completely normal peripheral cytokines @Omdal2026LCFatigueStress, indicating that the cytokine-fatigue correlation is state-dependent: cytokines drive fatigue during the acute phase of infection but may normalize while fatigue persists through CNS-confined maintenance mechanisms. Both findings are compatible under a biphasic model where acute cytokine surge initiates hypothalamic microglial priming, which then sustains fatigue independently of ongoing peripheral cytokine elevation.
<obs:ifn-alpha-fatigue-rct>
Capuron et al. @Capuron2002 demonstrated in a double-blind randomized trial (n=40 melanoma patients receiving IFN-$alpha$ therapy) that fatigue and anorexia emerge within two weeks of cytokine exposure through mechanisms distinct from serotonergic pathways: the neurovegetative syndrome (fatigue, somnolence, anorexia) was substantially less responsive to paroxetine than the concurrent mood syndrome. This dissociation indicates that IFN-$alpha$-induced fatigue operates via non-monoaminergic circuits, consistent with direct hypothalamic cytokine signaling (RCT, n=40, certainty: High).
=== TLR4/NF-$kappa$B as PEM Amplifier

#include "subsec-03-tlr4-nf-kappa-b-as-pem-amplifier/hypotheses/hyp-tlr4-nf-kappa-b-activation-as-pem-cytoki.typ"

=== ME/CFS-Specific Cytokine Profile: Evidence and Limitations

Several large studies document cytokine abnormalities in ME/CFS subsets. Hornig et al. @Hornig2015 identified distinct plasma immune signatures early in illness (elevated pro-inflammatory cytokines) that shift toward an exhaustion pattern in longer-duration disease. Montoya et al. @Montoya2017 correlated 17 cytokines with disease severity in 192 CFS patients, with IL-17F and TGF-$beta$ showing the strongest severity correlations. Giloteaux et al. @Giloteaux2023 conducted comprehensive proteomics analysis, identifying dysregulated cytokine networks in ME/CFS.

However, a systematic review of 15 case-control studies (Corbitt et al. @Corbitt2019, screening 16,702 publications) concluded that cytokine findings are _heterogeneous and inconclusive_ as diagnostic markers. No universal cytokine signature has been validated. Elevations in IL-1$beta$, IL-6, and IFN-$alpha/gamma$ are documented in _subsets_ of ME/CFS patients and should not be overstated as universal features.

This heterogeneity is consistent with ME/CFS being a syndrome of multiple convergent pathomechanisms: cytokine-driven fatigue may predominate in some patient subsets while other mechanisms (adenosine dysregulation, mitochondrial dysfunction, central sensitization) predominate in others.

*Fatigue Without Detectable Peripheral Inflammation.* Omdal et al.\ (2026, n=96) directly tested whether fatigue severity in long COVID correlates with peripheral inflammatory biomarkers — and found a complete dissociation: fVAS 63 vs 5 (p = 0.001) despite zero differences in CRP, TNF-α, IL-6, HSP90α, Serpin F1, hemopexine, or APOA4 @Omdal2026LCFatigueStress. Multivariable regression confirmed no biomarker-fatigue association. This null is important because it constrains the cytokine-fatigue model: if peripheral cytokines are not elevated in severely fatigued patients, then either (a) fatigue is driven by CNS-confined inflammation not reflected in blood, (b) fatigue is maintained by non-inflammatory mechanisms (epigenetic, metabolic, predictive processing), or (c) cytokines were elevated earlier and triggered persistent downstream effects after normalising. The sickness behavior model (Section @sec:ch15-sickness-behavior) and the locked-sickness-behavior framework predict option (c): hypothalamic microglial priming, once established by an acute cytokine storm, maintains fatigue signalling via CNS circuits independently of ongoing peripheral immune activation. This CNS-confined, circuit-mediated account is independently reinforced by Komaroff and Dantzer (2025), who propose that symptom persistence in long COVID and ME/CFS is generated by dedicated sickness-behavior and torpor neural circuits downstream of (localized) neuroinflammation rather than by ongoing systemic cytokines @KomaroffDantzer2025SymptomPersistence.

