#import "../../shared/environments.typ": *

#include "sec-01-why-this-chapter-exists.typ"
#include "sec-02-how-to-use.typ"
#include "sec-03-immune-neuroimmune.typ"
#include "sec-04-antiviral.typ"
#include "sec-05-stimulants.typ"
#include "sec-06-mitochondrial.typ"
#include "sec-07-mast-cell-histamine.typ"
#include "sec-08-oxidative-inflammatory.typ"
#include "sec-09-autonomic-cardiovascular.typ"
#include "sec-10-electrolytes.typ"
#include "sec-11-sleep-pain.typ"
#include "sec-12-emerging-investigational.typ"
#include "sec-13-reference-table.typ"
