#import "../../../../shared/environments.typ": *

==== Step H2c: Kynurenic acid vs. quinolinic acid imbalance (the astrocyte arm)

*Mechanism:* KYNA is produced in astrocytes (KAT is predominantly astrocytic) and acts as an endogenous NMDA antagonist at the glycine site — competing with QUIN at the same binding site. KYNA is broadly neuroprotective (reduces excitotoxicity) but also suppresses glutamatergic transmission → cognitive slowing. The QUIN/KYNA ratio determines the net glutamatergic effect: high QUIN/low KYNA → excitotoxicity; low QUIN/high KYNA → cognitive suppression; both high → competing effects (excitotoxicity from QUIN at NMDA receptors that are partially blocked by KYNA → unpredictable net effect). In ME/CFS, the QUIN/KYNA ratio may be shifted in either direction in different patients.

*Probes for KYNA/QUIN imbalance:*
- *No direct KYNA modulator exists clinically.* KYNA is a tryptophan metabolite — reducing kynurenine production (IDO inhibition, LDN) reduces both QUIN and KYNA proportionally. KMO inhibitors (which block QUIN synthesis and shunt kynurenine to KYNA) exist in preclinical development but are not available.
- *Memantine vs. LDN head-to-head:* If memantine works better than LDN → QUIN excitotoxicity dominates over microglial neuroinflammation. NMDA blockade is more specific than anti-inflammatory suppression. If LDN works better than memantine → microglial neuroinflammation dominates (LDN reduces both IDO induction AND cytokine-mediated symptoms). Memantine may still provide benefit but it is downstream of the primary pathology.
- *Memantine + LDN combination:* If the combination is synergistic → QUIN excitotoxicity AND neuroinflammation are independent co-drivers (LDN reduces QUIN production by reducing IDO, memantine blocks existing QUIN at the receptor). If the combination is additive only → LDN reduces QUIN production, which reduces NMDA activation → memantine has less to block → the drugs are operating in series on the same pathway.
- *Pregnenolone (50--200 mg, neurosteroid):* Pregnenolone is a negative allosteric modulator of NMDA receptors (different site from QUIN/KYNA) and a negative allosteric modulator of GABA-A receptors. If pregnenolone improves cognition and reduces anxiety → the NMDA system is hyperactive (consistent with QUIN dominance). If pregnenolone causes sedation → the NMDA negative modulatory effect dominates, consistent with QUIN-driven excitotoxicity being suppressed. If pregnenolone causes agitation → GABA-A negative modulation is tipping excitation-inhibition balance in a system with low GABAergic reserve.
- *If memantine causes sedation (Pattern 4) AND LDN improves symptoms:* The patient has KYNA-dominant kynurenine pathway — basal glutamate tone is already low (from KYNA antagonism), and further NMDA blockade (memantine) reduces glutamate below the threshold for normal cognition. LDN's benefit is from reducing neuroinflammation, not from restoring glutamatergic balance. This patient should avoid all NMDA antagonists.

*Consequence:* The kynurenine cascade is uniquely diagnostic because it has three arms producing diametrically opposite effects: serotonin depletion (treat with 5-HTP), NMDA excitotoxicity (treat with memantine), and NMDA suppression (avoid NMDA antagonists, treat upstream with LDN). The differential diagnosis: 5-HTP response localizes the lesion to the serotonin arm. Memantine response at standard doses without sedation localizes the lesion to the QUIN arm. Memantine sedation at low dose localizes the lesion to the KYNA arm (basal glutamate tone low). The combination of 5-HTP + memantine responses maps whether both arms are active simultaneously. LDN response tells you IDO is driving the pathway. The tryptophan challenge test (improvement vs. worsening after tryptophan supplementation) tells you whether IDO is saturated — a rapid, low-cost probe that no one performs but that directly informs the entire kynurenine diagnostic logic. This is the most biochemically accessible cascade in the chapter: serum kynurenine/tryptophan ratio and QUIN/KYNA ratio are measurable in clinical labs, unlike ion channel function or autoantibody bioassays. The cascade tracing should be correlated with serum metabolite measurements whenever possible — the pharmocodiagnostic logic and the biochemical measurements validate each other.
*Origin:* mechanistic-pathway-tracing.


