#import "../../../../shared/environments.typ": *

==== Step H2b: Quinolinic acid → NMDA excitotoxicity (the glutamate arm)

*Mechanism:* QUIN is produced in microglia (KMO is predominantly microglial) and acts as an NMDA receptor agonist at the glycine co-agonist site. Unlike glutamate (which is rapidly cleared by astrocytes), QUIN has a long half-life in the extracellular space. Chronic QUIN elevation → sustained low-grade NMDA receptor activation → (a) excitotoxicity — excessive Ca²⁺ influx through NMDA receptors → mitochondrial Ca²⁺ overload, oxidative stress, and synaptic dysfunction; (b) reduced long-term potentiation (LTP) — the NMDA receptor is desensitized from chronic low-level activation, and the dynamic range for LTP (learning, memory) is reduced → cognitive dysfunction; (c) selective vulnerability of GABAergic interneurons (which express high levels of GluN2B-containing NMDA receptors that QUIN preferentially activates) → reduced inhibitory tone → network hyperexcitability → anxiety, hyperarousal, sensory sensitivity, tinnitus.

*Probes for NMDA excitotoxicity:*
- *Memantine (5--20 mg):* Uncompetitive NMDA receptor antagonist — blocks the channel only when it is open (use-dependent). Preferentially blocks pathological tonic NMDA activation while sparing physiological phasic activation. If memantine improves cognition, reduces anxiety, and reduces sensory hypersensitivity → NMDA excitotoxicity is present and rate-limiting. Onset latency: improvement within days → functional NMDA overactivation (QUIN is present and active). Improvement at 2--4 weeks → the NMDA system is adapting to reduced activation (receptor trafficking, CREB signaling). Dose titration: if sedation/brain fog appears at low dose (5 mg) → basal glutamate tone is already low (Pattern 4, @sec:side-effects-diagnostic) — reducing NMDA further tips cognition over a cliff. This patient has kynurenic acid dominance, not quinolinic acid excess. If memantine can be titrated to 20 mg without sedation → QUIN-driven excitotoxicity is dominant and NMDA blockade is well-tolerated.
- *Low-dose amitriptyline (5--10 mg at bedtime):* NMDA antagonist (weak, at low doses) + NE/5-HT reuptake inhibition + H1 antagonism (sleep). If amitriptyline improves sleep AND cognition → dual mechanism: NMDA antagonism reduces nocturnal excitotoxicity + H1 blockade consolidates sleep. The cognitive improvement may be secondary to improved glymphatic clearance during sleep.
- *Ketamine (0.1--0.5 mg/kg IV, investigational):* NMDA antagonist (channel blocker, different site from memantine) + rapid antidepressant effect (mTORC1-dependent synaptogenesis). If ketamine produces rapid improvement (within hours) → NMDA antagonism is the mechanism (fast), and the synapse is capable of rapid plasticity. If improvement lasts days to weeks after a single infusion → ketamine has triggered synaptogenesis (new spine formation in PFC), not just blocked NMDA. If ketamine produces transient worsening (dissociation, anxiety) but no subsequent improvement → the NMDA system is too fragile for direct blockade. CAUTION: ketamine increases HR and BP — may worsen hyperadrenergic POTS.
- *Riluzole (50 mg BID, glutamate release inhibitor):* Reduces presynaptic glutamate release by blocking voltage-gated Na⁺ channels. If riluzole works → the glutamatergic excess is from excessive release, not just from QUIN agonism. If riluzole does NOT work but memantine works → the glutamatergic problem is specifically NMDA receptor-level (QUIN agonism), not excessive glutamate release.
- *NAC (600--1200 mg BID):* Cysteine donor for glutathione synthesis → reduces oxidative stress from NMDA-mediated Ca²⁺ influx. If NAC + memantine is synergistic (greater than additive, @sec:drug-drug-interactions) → NMDA excitotoxicity drives ROS production, and blocking NMDA (memantine) + scavenging ROS (NAC) closes the excitotoxicity→ROS→mitochondrial damage→ATP deficit→impaired Ca²⁺ clearance→more NMDA activation loop.

