#import "../../../../../shared/environments.typ": *

==== Nature Communications Commentary

The most substantive published rebuttal is the Matters Arising by Davenport et al.\ in _Nature Communications_ @Davenport2025EffortDeconditioning. It argues that the effort-preference and deconditioning interpretation “risks reinforcing skepticism about the serious biological nature of [ME/CFS] and its hallmark of post-exertional malaise (PEM), as well as its potential misclassification as a mental health condition.”

The rebuttal rests on a core methodological point: the study used a single CPET, which cannot characterize PEM because it cannot measure the response to an initial exertion. The two-day CPET, with a second maximal test 24 hours later, is the standard method for documenting post-exertional metabolism in ME/CFS @Lim2020CPETMeta, and the Institute of Medicine cautioned that a single test may be insufficient. Because deconditioning and PEM are not mutually exclusive, evidence of deconditioning cannot by itself explain PEM @Davenport2025EffortDeconditioning.

The critique also turns the physiological data against the deconditioning hypothesis. Deconditioning typically produces elevated exercise heart rate at a given workload, yet exercise HR was *lower* in post-infectious ME/CFS participants than in healthy volunteers @Davenport2025EffortDeconditioning. Davenport et al.\ read this as inconsistent with deconditioning and more consistent with chronotropic incompetence and impaired oxidative metabolism — both established ME/CFS features. They further argued the study was underpowered (only 8 post-infectious ME/CFS and 9 healthy volunteers completed CPET), lacked deconditioned control matching, and did not document outcome-measurement order in the abstract. The full argument is developed in the mechanistic-studies chapter at @sec:effort-preference-controversy.

This response, together with the authors' reply below and the Frontiers reanalysis @kirvinquamme2025effort, illustrates the wider academic contest over whether the same objective data should be interpreted as deconditioning or as intrinsic metabolic and autonomic limitation. The stakes are clinical: the interpretation directly affects whether patients are treated with activity-based therapies or energy-envelope pacing. Severity applicability: broad, from mild to severe, since the deconditioning rebuttal applies to the full severity spectrum.
