#import "../../../../../shared/environments.typ": *

#speculation(title: [Emotional-Autonomic Dissociation in ME/CFS])[
The gap between subjective emotional experience and objective autonomic response—emotional-autonomic dissociation—may be a hallmark of the interoceptive dysfunction in ME/CFS. Rimes et al.\ (2016, n=40 CFS, 40 controls) found that during an experimental emotion suppression task, CFS patients showed blunted electrodermal activity (reduced sympathetic reactivity) with simultaneously elevated self-reported distress @Rimes2016emotionSuppressionCFS. This dissociation—the subjective experience decoupled from the peripheral autonomic signal that normally grounds it—parallels the interoceptive accuracy-sensibility dissociation described above.

The Wortinger et al.\ (2017) pilot fMRI study (n=10 adolescent CFS, 10 controls) demonstrated that CFS patients activate different neural circuitry during emotional conflict processing: altered anterior cingulate and prefrontal activation despite preserved behavioural performance @Wortinger2017emotionConflictCFS. This pattern—compensatory neural recruitment to maintain behavioural performance in the face of degraded underlying processing—is consistent with the predictive coding model's prediction that higher-level cortical networks must overcompensate when lower-level interoceptive signals are noisy.

This dissociation has clinical significance: it explains why patients report emotional distress that clinicians may dismiss because it lacks accompanying physiological signs (normal BP, HR, temperature). The absence of visible autonomic reactivity is not evidence that the emotional distress is fabricated or exaggerated; it is evidence that the normal autonomic substrate of emotion has been disrupted. Van Den Houte et al.\ (2017) demonstrated this in the opposite direction: experimentally inducing negative affect genuinely amplifies somatic symptom reporting in CFS and fibromyalgia more than in controls @VanDenHoute2017negativeAffectSomatic—the amplification pathway is real and bidirectional, but it reflects a _sensitised psychophysiological circuit_, not psychogenesis.

The convergence of emotional processing abnormalities across independent studies using different methodologies—experimental emotion suppression (Rimes 2016), behavioural questionnaires (Brooks et al.\ 2017, n=67 CFS @Brooks2017emotionalProcessingCFS), and fMRI (Wortinger 2017)—provides triangulation, though all studies are single-center and unreplicated in independent labs. A competing HPA axis pathway has been proposed: Kang et al.\ (2026) reviewed HPA axis dysregulation in ME/CFS as an alternative mechanism for cognitive and emotional changes, arguing that cortisol dysregulation → hippocampal atrophy → cognitive deficits + emotional dysregulation @Kang2026hpaEmotionCFS. The HPA and interoceptive pathways are not mutually exclusive—both may operate simultaneously and interact.

(Certainty: 0.40. The Rimes 2016 dissociation finding is from a single experimental study with moderate sample size, not independently replicated. The Wortinger 2017 fMRI pilot is very small (n=10 per group) and adolescent-only. The Van Den Houte 2017 affect amplification finding is well-controlled but from a single study. All three converge on the same mechanistic model despite methodological differences, providing triangulation, but confirmation in larger, adult ME/CFS samples using combined autonomic + fMRI + emotional processing paradigms is needed. *Falsification condition:* If emotional-autonomic coherence (within-subject correlation between EDA change and self-reported distress during emotion tasks) does NOT distinguish CFS from controls—i.e., the dissociation is not disease-specific but reflects general distress—the interoceptive pathway is not supported.)
] <spec:ch15-emotional-autonomic-dissociation>
