#import "../../../../../shared/environments.typ": *

==== Why Herpesvirus Antibodies Persist for Decades
<sec:herpesvirus-antibody-persistence>

Herpesvirus antibodies are commonly cited as evidence of viral reactivation in ME/CFS — but antibody titre interpretation is constrained by a body of basic immunology that is often overlooked in clinical reasoning. The persistence of antiviral antibodies decades after infection is largely the work of long-lived plasma cells (LLPCs), which maintain antibody output independently of ongoing antigenic stimulation. This does not mean that herpesvirus reactivation does not occur in ME/CFS — the evidence for abortive lytic replication and poly-herpesvirus co-reactivation is substantial (Sections @sec:abortive-lytic, @sec:poly-herpesvirus). It means that structural antigen IgG titre alone — the most commonly used clinical test — cannot distinguish between memory of a past infection and evidence of current viral activity. The implication is not that all herpesvirus serology is useless, but that its interpretation requires the right antigen targets and the right clinical context.

===== The Immunology of Lifelong Antibody Maintenance

After an acute infection, short-lived plasma cells in secondary lymphoid organs produce the initial antibody burst. A fraction of activated B cells differentiate into long-lived plasma cells that migrate to survival niches in the bone marrow, where they constitutively secrete antibody for the lifetime of the host — without requiring re-exposure to antigen, without dividing, and independently of memory B cell replenishment @Amanna2007Duration @Hammarlund2017PlasmaCell @Robinson2022LLPC.

The Amanna–Slifka longitudinal cohort (n=45, followed up to 26 years) established the quantitative foundation @Amanna2007Duration:
    - Antiviral antibody half-lives: VZV ~50 years; EBV, measles, mumps >200 years
    - By contrast, vaccine-induced antibodies to non-replicating antigens (tetanus: 11 years; diphtheria: 19 years) wane much faster
    - Memory B cell numbers did NOT correlate with serum antibody titres for 5/8 antigens tested — demonstrating that antibody levels and B cell memory are independently regulated

The Hammarlund primate model provided direct experimental confirmation @Hammarlund2017PlasmaCell: bone marrow LLPCs survived for more than a decade after sustained depletion of memory B cells. BrdU pulse-chase experiments detected plasma cells labelled at the time of vaccination still alive 10 years later without any evidence of cell division. The LLPC pool alone — without memory B cell input and without antigenic stimulation — was sufficient to maintain stable serum antibody titres.

A critical structural determinant of antibody longevity is the physical form of the antigen that drove the original response @Slifka2019Multivalency @Chackerian2020LLPC. Highly multivalent, repetitive antigen arrays — such as viral capsids and envelope glycoprotein lattices — cross-link B cell receptors with high avidity, lowering the activation threshold and preferentially driving LLPC differentiation. Herpesviruses present precisely this type of antigen: icosahedral capsids with repeating structural subunits, dense glycoprotein arrays on the viral envelope, and tegument proteins packaged at high copy number. They are structurally optimised to generate exceptionally durable antibody responses.

Robinson et al. demonstrated that LLPCs accumulate in bone marrow at a rate of approximately one cell per hour after immunisation, and that the final number scales with the duration of the germinal centre reaction @Robinson2022LLPC. This implies that the magnitude of the initial infection — the antigen load and the duration of the germinal centre response — determines long-term antibody levels, not the frequency of subsequent reactivation events.

===== What This Means for Herpesvirus Serology

The persistence of herpesvirus antibodies decades after infection is therefore expected and normal — but the picture is not binary. LLPCs provide a substantial antigen-independent baseline that persists for the host's lifetime. Against this high baseline, the contribution of any individual reactivation event to total structural antigen IgG may be modest and difficult to detect. However — and this is a critical caveat — structural antigen IgG CAN rise measurably during clinical herpesvirus reactivation: VZV IgG rises during shingles, CMV IgG rises during CMV disease, and EBV VCA/EBNA-1 IgG can rise during EBV-driven post-transplant lymphoproliferative disorder. The LLPC baseline dominates the total signal, but reactivation can contribute to it. The correct interpretive principle is therefore not "structural IgG is pure LLPC output and never indicates viral activity" — it is "structural IgG has a large antigen-independent LLPC component, and elevated titres alone, without corroborating evidence from viral DNA, viral mRNA, or lytic-cycle antibody data, are insufficient to diagnose active reactivation."

This does not mean herpesvirus reactivation does not occur in ME/CFS — the dUTPase, ALR, and poly-herpesvirus co-reactivation evidence is discussed below (Sections @sec:abortive-lytic, @sec:poly-herpesvirus). It means that antibody titre alone — particularly against structural viral antigens (VCA, gB) and latency proteins (EBNA-1, which is not a structural antigen but is functionally in the same interpretive category because it is constitutively expressed during latency) — cannot distinguish between:
    - Normal LLPC maintenance without viral activity
    - Low-level abortive lytic replication in the absence of productive infection
    - Overt lytic reactivation with infectious virion production

===== What IS a Signal of Active Viral Activity (and What Isn't)

| Antibody target | What it indicates |
|-----------------|-------------------|
| VCA IgG, EBNA-1 IgG, CMV gB IgG, VZV gE IgG | LLPC output (may reflect infection that occurred decades ago) |
| EA-D IgG (EBV early antigen diffuse) | Lytic cycle entry — but early antigen antibodies can persist for years after resolved reactivation |
| VCA IgM | Genuine herpesvirus reactivation OR recent primary infection OR nonspecific polyclonal B cell activation OR rheumatoid factor interference — cannot distinguish between these without clinical context and confirmatory testing |
| Anti-dUTPase IgG (BLLF3, U45, ORF8) | Evidence of abortive lytic replication — dUTPase is an early lytic gene product; antibody presence signals recent expression of lytic genes, not necessarily productive replication |
| Viral DNA in plasma (quantitative PCR) | Presence of cell-free virions — indicates productive lytic replication; however, may be negative during abortive lytic replication (ALR, Section @sec:abortive-lytic) where no infectious virions are produced. A negative qPCR does not exclude ALR. |
| Viral mRNA (EBER, BLLF1) in tissue | Active viral gene expression at the tissue site |

The critical interpretive principle: the bottom three rows of this table provide the strongest evidence of ongoing viral activity, but each has caveats — qPCR may be negative during ALR, viral mRNA requires tissue biopsy, and dUTPase antibodies come from a single research group without independent replication. The top rows are dominated by the LLPC baseline: isolated elevation of structural antigen or latency protein IgG, without corroborating evidence from viral DNA, viral mRNA, or lytic-cycle antibodies, is insufficient to diagnose active reactivation. Clinicians and researchers should not diagnose "active EBV" or "chronic herpesvirus reactivation" on the basis of structural antigen IgG alone.

When confirmatory testing (qPCR, EA-D, dUTPase serology) is negative or unavailable — a common clinical scenario — a time-limited valacyclovir trial with predefined stopping rules and symptom tracking remains a reasonable shared-decision option for the post-infectious subset with clinical suspicion of herpesvirus-driven pathology. This is expert opinion, supported by the two controlled positive antiviral trials (Lerner 2007, Montoya 2013) that enrolled on elevated antibody titres rather than confirmed viral replication, and is not a universal recommendation. The goal is to avoid reflexive chronic antiviral prescribing triggered by an isolated VCA IgG result, while preserving access to a therapeutic trial when the clinical picture warrants it.

===== Evidence in ME/CFS: Is Antibody Elevation Real?

The question of whether ME/CFS patients have elevated herpesvirus antibodies above the healthy seropositive baseline is not settled:

*Evidence of elevation:*
    - Palomo et al. (n=40 ME/CFS, 16 controls): elevated anti-dUTPase IgG to EBV, HHV-6, VZV; 72.5% co-expression of multiple herpesvirus antibodies vs 31% controls @Palomo2026dUTPase
    - Apostolou et al. (n=95 ME/CFS, 110 controls): elevated salivary EBNA-1 IgG and EBV-VCA IgG in ME/CFS — detected locally in saliva, not systemically in plasma @Apostolou2022Saliva
    - Loebel et al. (n=92 CFS, 50 controls): EBNA-6 repeat region IgG enhanced in CFS, though overall EBV IgG pattern "quite similar" between groups @Loebel2017EBVsero

*Evidence of no elevation:*
    - Cliff et al. (n=251 ME/CFS, 107 controls): UK ME/CFS Biobank — no differences in seroprevalence for six herpesviruses between ME/CFS and controls @Cliff2019Cellular
    - Blomberg et al. (Swedish cohort, Canada criteria): suspension multiplex immunoassay for HHV-1-7 — overall IgG anti-herpes-viral reactivities did NOT show significant differences between ME/CFS and blood donor controls @Blomberg2019HerpesvirusNull

#open-question(title: [Is Herpesvirus Antibody Elevation a Universal Feature of ME/CFS?])[

*Certainty: contested.* Two large seroprevalence studies (Cliff n=251, Blomberg) found no overall elevation; three smaller studies (Palomo, Apostolou, Loebel) found antigen-specific elevations. The contradiction is likely resolvable by antigen specificity — dUTPase (an early lytic protein) and EBNA-6 (a latency protein with human homology) may be selectively elevated while structural antigen antibodies (VCA, EBNA-1, gB) are not. If this is correct, ME/CFS is characterised by a qualitative shift in antibody fine specificity (toward lytic-cycle and cross-reactive epitopes) rather than a quantitative elevation in total herpesvirus IgG. This would explain why seroprevalence studies (which measure presence/absence of IgG against structural antigens) find no difference, while studies using lytic-cycle antigens find elevations.

*Falsifiable prediction 1:* A study measuring IgG against structural antigens (VCA, gB, gE) AND lytic-cycle antigens (dUTPase, EA-D) AND latency-protein repeat regions (EBNA-6) simultaneously in the same ME/CFS cohort should find elevations only in the lytic and repeat-region categories, not in structural antigen IgG. Falsified if structural antigen IgG is equally elevated.

*Falsifiable prediction 2:* ME/CFS patients with elevated anti-dUTPase antibodies should show higher viral DNA loads (qPCR) than patients with normal anti-dUTPase levels. Falsified if dUTPase antibody elevation is independent of viral DNA detection.

*Consequence:* If the antigen-specificity model is correct, herpesvirus serology in ME/CFS diagnosis and research should shift from measuring total IgG seroprevalence to targeted measurement of lytic-cycle antibodies (dUTPase, EA-D). Total IgG panels — the most commonly used clinical test — are uninformative.
] <oq:herpesvirus-antibody-universal>

#hypothesis(title: [Lytic-to-Structural IgG Ratio (LSR) as a Diagnostic Biomarker])[

*Certainty: 0.45.* In normal LLPC biology, the ratio of IgG against lytic-cycle herpesvirus antigens (EBV BZLF1, EA-D, dUTPase) to structural antigens (VCA-p18 — the immunodominant capsid protein measured by standard VCA IgG — EBNA-1, gB) should remain stable — both antibody types are produced by the same LLPC pool established during primary infection. If ME/CFS involves abortive lytic reactivation (preferentially boosting lytic-antigen responses via short-lived plasmablasts) or epitope-specific autoimmune drift (affecting specific lytic epitopes), the LSR will be elevated. This ratio uses each patient as their own internal control, eliminating confounding by infection timing, age, and initial antigen load. The concept directly explains the contradictory literature: structural-antigen IgG is normal (Cliff, Blomberg null findings), while lytic-antigen IgG is elevated (Palomo dUTPase, Loebel EBNA-6 repeat). *Origin: brainstorm.*

The precedent from multiple sclerosis is instructive: EBNA-1 antibodies cross-react with GlialCAM specifically in MS patients, not in seropositive healthy controls @Lanz2022Nature. The pathogenic feature is the qualitative shift in antibody fine specificity — the same principle may apply in ME/CFS, where cross-reactive antibodies could target autonomic neurons, skeletal muscle, or mitochondrial antigens. The elevated titre is a byproduct of autoimmune drift, not the primary pathology.

*Falsifiable prediction:* The LSR (anti-BZLF1 IgG / anti-VCA-p18 IgG ratio) will discriminate ME/CFS from healthy seropositive controls (AUC ≥ 0.75) and correlate with symptom severity (r ≥ 0.3 with fatigue score), while neither anti-BZLF1 nor anti-VCA alone will show significant discrimination. IgG avidity (urea-wash ELISA) for anti-herpesvirus antibodies will be uniformly high (avidity index >0.6, consistent with remote past infection) — low-avidity IgG ($<$0.4) would refute the LLPC model and support recent abortive reactivation.

*Consequence:* A blood test comparing the ratio of two antibody types could distinguish ME/CFS patients with an ongoing immune problem from those with normal antibodies from past infections — providing a low-cost diagnostic tool using existing clinical assays.
] <hyp:lytic-structural-igg-ratio>

#limitation(title: [Methodological Weaknesses in the Herpesvirus Serology Literature])[
The evidence base for elevated anti-herpesvirus antibodies in ME/CFS suffers from methodological threats on both sides. The positive studies (Palomo, Apostolou, Loebel) are small, use different antigen preparations with no standardisation, and have not been independently replicated — the dUTPase findings derive from a single research group. The null studies have their own limitations: Cliff 2019 measured seroprevalence (binary ±) rather than quantitative titres, and in a population where >90% of adults are seropositive for EBV and VZV, seroprevalence cannot detect titre differences — Cliff's null result for structural antigen seroprevalence confirms universal prior infection, not absence of titre elevation. Blomberg 2019 used a suspension multiplex immunoassay whose sensitivity for detecting subtle titre differences compared to standard ELISA has not been established, and compared ME/CFS patients to blood donor controls who are systematically healthier than the general population. The question of whether herpesvirus antibody elevation exists in ME/CFS is not scientifically settled for any antigen class — the literature is too methodologically heterogeneous on both sides to support a definitive conclusion. Researchers designing studies should pre-register protocols, use ≥3 distinct antigen preparations spanning structural and lytic-cycle targets, match controls on age/sex/infection timing, and apply correction for multiple comparisons. Until a study meeting these criteria is published, the question remains open. *Origin: brainstorm.*

*Consequence:* The herpesvirus serology literature in ME/CFS is too methodologically heterogeneous to support a definitive conclusion in either direction. Researchers designing studies should pre-register their protocols, use ≥3 distinct antigen preparations spanning structural and lytic-cycle targets, match controls on age/sex/infection timing, and apply Bonferroni correction.
] <lim:herpesvirus-serology-methods>

#speculation(title: [B Cell Dysregulation as Driver of Antibody Elevation])[

*Certainty: 0.30.* An alternative to viral reactivation as the driver of elevated herpesvirus antibodies is intrinsic B cell dysregulation. Sun et al. (2024) performed scRNA-seq on peripheral blood from ME/CFS patients (n=4) and found that memory B cells in ME/CFS show a unique subtype early in pseudotime, with increased trajectory toward plasma cell differentiation — suggesting B cell overactivity @Sun2024Immunometabolic. If this finding replicates in larger cohorts, it would mean that elevated herpesvirus antibodies in ME/CFS could reflect dysregulated B cell → plasma cell differentiation rather than antigen-driven responses to viral reactivation. The certainty is low (0.30) because the finding comes from a single study with n=4 patients and n=4 controls, and the link between increased plasma cell differentiation and herpesvirus antibody titres has not been directly tested.

*Falsifiable prediction:* ME/CFS patients with elevated herpesvirus antibodies will show increased frequencies of antibody-secreting cells (CD19^low CD27^high CD38^high) in peripheral blood AND increased plasma cell numbers in bone marrow aspirates, independent of viral DNA load. Falsified if antibody elevation always correlates with detectable viral DNA.

*Consequence:* If this mechanism is confirmed, herpesvirus antibody elevation in ME/CFS would be a readout of B cell dysregulation rather than viral reactivation — changing the diagnostic and therapeutic implications entirely. Antiviral therapy would not be expected to reduce antibody titres, and the focus would shift to B cell-targeted interventions. However, this is early-stage; the finding may turn out to be a dead end.
] <spec:antibody-elevation-bcell-dysregulation>

#limitation(title: [Herpesvirus Antibody Titres Cannot Be Interpreted as Evidence of Active Infection])[
Total IgG against structural herpesvirus antigens (VCA, CMV gB, VZV gE) and latency proteins (EBNA-1) has a substantial antigen-independent component maintained by long-lived plasma cells established at primary infection — not a pure readout of the current state of the virus. LLPCs maintain antibody titres for decades without antigenic stimulation (@Amanna2007Duration, half-life >200 yr for EBV; @Hammarlund2017PlasmaCell, LLPC survival >10 yr without memory B cells). However, structural antigen IgG CAN be boosted by clinical reactivation (e.g., VZV IgG rises during shingles), so elevated titres against a high LLPC baseline are ambiguous. An elevated titre may indicate: (a) greater LLPC numbers from a more intense primary infection; (b) individual variation in bone marrow niche capacity; (c) ongoing antigenic stimulation from viral reactivation; or (d) intrinsic B cell dysregulation driving excess plasma cell differentiation (@Sun2024Immunometabolic, preliminary, n=4). The critical distinction is between detectable antibodies (universal in seropositive adults, expected from LLPCs) and significantly elevated titres above age/sex-matched norms (could reflect any of a–d). Without viral DNA (qPCR), viral mRNA (in situ hybridisation), or lytic-cycle antibody data, herpesvirus IgG titre alone is uninformative about viral activity — but when confirmatory testing is negative or unavailable, a time-limited antiviral trial with defined stopping rules remains a defensible clinical option for the post-infectious subset. This principle applies to all herpesviruses (EBV, HHV-6, CMV, VZV, HSV-1/2) and is not specific to ME/CFS — it is a general constraint on serological interpretation.

*Consequence:* Clinicians should not diagnose "chronic EBV" or "chronic herpesvirus reactivation" based on IgG serology alone, and should not initiate indefinite antiviral therapy on the basis of isolated structural antigen IgG titres. A time-limited antiviral trial with predefined stopping rules and symptom tracking is a reasonable shared-decision option when clinical suspicion is high and confirmatory testing is unavailable or negative (acknowledging that qPCR may be negative during abortive lytic replication). This balances patient safety — protecting against unnecessary long-term antiviral treatment — with access to a therapeutic trial in appropriate cases.
] <lim:herpesvirus-antibody-interpretation>

#synthesis(title: [Rethinking Herpesvirus Serology in ME/CFS])[

The evidence collectively argues that herpesvirus serology in ME/CFS has been systematically misinterpreted: the large antigen-independent LLPC baseline means that isolated structural-antigen or latency-protein IgG elevation is insufficient to diagnose active viral reactivation, while the contradictory literature on antibody elevation has not been resolved by any study to date — the evidence is too methodologically heterogeneous on both sides to support a definitive conclusion (@oq:herpesvirus-antibody-universal, @lim:herpesvirus-serology-methods). The strongest practical implication is that clinical decisions should not rest on structural antigen IgG alone (@lim:herpesvirus-antibody-interpretation) — but neither should the absence of accessible confirmatory testing preclude a time-limited therapeutic trial in appropriate patients. The dUTPase, ALR, and poly-herpesvirus evidence (Sections @sec:abortive-lytic, @sec:poly-herpesvirus) establishes that viral reactivation occurs in a subset of ME/CFS patients; what remains unresolved is how to identify that subset with available tests.

*Consequence:* The existing clinical practice of diagnosing "viral reactivation" from herpesvirus IgG panels alone is not supported by basic immunology. The path forward is: (1) use viral DNA (qPCR), viral mRNA, and lytic-cycle antibody testing where available — with the caveat that qPCR may be negative during abortive lytic replication; (2) where these are unavailable, a time-limited antiviral trial with predefined stopping rules remains a reasonable clinical option for the post-infectious subset; (3) research should focus on validating antigen-specific biomarkers (including dUTPase antibodies, pending independent replication) rather than continuing to measure total IgG seroprevalence.
] <syn:herpesvirus-antibody-persistence-model>
