#import "../../../../shared/environments.typ": *

=== The NAD#super[+]--Sirtuin--Acetylation Hub
<sec:nad-sirtuin-acetylation-hub>

The preceding sections treat NAD#super[+] depletion (G22, Step 6), NRF2 pathway dysfunction (G34, Step 9), and PGC-1$alpha$ hyperacetylation (G39, Step 10) as separate research gaps. A post-hoc observation: these three gaps _could_ be mechanistically linked through a single upstream regulator — NAD#super[+]-dependent sirtuin activity — if tissue NAD#super[+] depletion proves real. This convergence rests on well-established enzymology (the sirtuin-substrate relationships are documented in non-ME/CFS biology), though the specific claim that these connections are operative in ME/CFS tissue remains a hypothesis.

SIRT1 deacetylates PGC-1$alpha$ at multiple lysine residues, converting it from an inactive hyperacetylated form to the active transcription factor that drives mitochondrial biogenesis . SIRT1 has also been reported to deacetylate NRF2, promoting its nuclear retention and transcriptional activity on antioxidant response elements, though the directness and significance of this interaction remain debated (SIRT1 may also modulate NRF2 indirectly via KEAP1 or other regulators). SIRT3, a mitochondrial matrix sirtuin, deacetylates and activates isocitrate dehydrogenase 2 (IDH2), MnSOD, and components of Complex I — the last of which directly affects electron transport chain flux. All three sirtuins require NAD#super[+] as a co-substrate (not merely a cofactor — NAD#super[+] is consumed stoichiometrically, one molecule per deacetylation event, producing nicotinamide and O-acetyl-ADP-ribose).

In ME/CFS, three independent NAD#super[+]-consuming mechanisms are plausible, though their tissue-specific operation remains largely inferred rather than directly measured:

+ *PARP hyperactivation (inferred):* The Shankar 2025 MnSOD deficit in lymphocytes  predicts increased mitochondrial superoxide $arrow.r$ oxidative DNA damage $arrow.r$ PARP1 activation $arrow.r$ NAD#super[+] consumption. A single DNA double-strand break can consume hundreds of NAD#super[+] molecules through PARP poly-ADP-ribosylation. PARP activity has not been directly measured in ME/CFS tissue.
+ *CD38 upregulation (inferred from immunology):* CD38 is the dominant NAD#super[+]-consuming enzyme in most tissues and is strongly upregulated by inflammatory cytokines (TNF-$alpha$, IFN-$gamma$) — both chronically elevated in ME/CFS. CD38 also degrades the NAD#super[+] precursor NMN, creating a double block on the salvage pathway. Note that CD38 upregulation in PBMCs would _also_ consume NAD#super[+] there — yet Heng et al.\ found PBMC NAD#super[+] _elevated_ @heng2025mecfs, suggesting that if CD38 is active in PBMCs, its consumption is outpaced by ETC-driven NAD#super[+] backup in that compartment.
+ *Kynurenine pathway diversion (documented in plasma):* Tryptophan is the sole substrate for de novo NAD#super[+] synthesis via the kynurenine pathway. IDO1 upregulation by IFN-$gamma$ diverts tryptophan toward quinolinic acid (neurotoxic) rather than completing the synthesis to NAD#super[+] — documented in ME/CFS plasma metabolomics @Germain2022exercise @Groven2021kynurenine, though the tissue-specific impact on muscle or neuronal NAD#super[+] pools is unmeasured.

#hypothesis(title: [NAD#super[+]--Sirtuin--Acetylation Hub: Unified Upstream Regulator of G22, G34, and G39])[
*Certainty: 0.40. (0.35→0.40: the SNS→AMPK→mTORC1→autophagy axis provides independent convergence—from a different lab [Brown 2018] using different methods [electrical pulse stimulation AMPK phosphorylation]—on the same endpoint of PGC-1α functional suppression. The autonomic route converges with the metabolic co-substrate route, strengthening the hub model through parallel independent evidence.)* NAD#super[+] depletion in energy-intensive tissues (skeletal muscle, neurons — not PBMCs, where Heng et al.\ found NAD#super[+] _elevated_ @heng2025mecfs, consistent with substrate backup rather than depletion) simultaneously inactivates SIRT1, SIRT3, and shifts the SIRT1/SIRT4 balance toward the inhibitory SIRT4 arm . The downstream consequences propagate through four documented pathways:

+ *PGC-1$alpha$ hyperacetylation* (G39): SIRT1 cannot deacetylate PGC-1$alpha$ $arrow.r$ biogenesis is blocked despite compensatory mRNA upregulation @wang2023wasf3 $arrow.r$ mitochondrial mass declines over weeks (Step 10).
+ *NRF2 functional suppression* (G34): SIRT1 cannot deacetylate NRF2 $arrow.r$ reduced nuclear retention and ARE binding $arrow.r$ antioxidant target genes (MnSOD, GPX4, NQO1) are under-expressed even if NRF2 protein is present  @Davis2025nrf2lipid (Step 9).
+ *Complex I and TCA cycle impairment:* SIRT3 cannot deacetylate Complex I subunits (NDUFA9) and IDH2 $arrow.r$ reduced electron transport and TCA flux $arrow.r$ lower ATP and more ROS (Steps 4--5).
+ *PDC regulation via SIRT4:* When SIRT1 activity falls but SIRT4 remains active (as documented in ME/CFS PBMCs ), SIRT4 opposes energy metabolism through at least two mechanisms: ADP-ribosylation of glutamate dehydrogenase (reducing glutamine-derived TCA anaplerosis) and lipoamidase activity that removes lipoyl groups from the E2 subunit of PDC $arrow.r$ reduced pyruvate entry into the TCA cycle (Step 3).

This model predicts that G22, G34, and G39 are not independent gaps but three readouts of a single upstream failure. Resolving G22 (measuring tissue NAD#super[+] and PARP/CD38 activity) would therefore provide mechanistic context for all three.

*Testable predictions:*
+ NAD#super[+] in ME/CFS skeletal muscle will be _reduced_ (opposite to the PBMC elevation found by Heng et al.\ @heng2025mecfs), predicting a tissue-compartment dissociation.
+ The muscle NAD#super[+]/NADH ratio will correlate inversely with PGC-1$alpha$ acetylation ratio in the same biopsies — the tighter the correlation, the stronger the evidence that NAD#super[+] depletion is the rate-limiting step for SIRT1-mediated PGC-1$alpha$ activation.
+ NR or NMN supplementation (which raises tissue NAD#super[+]) should simultaneously reduce PGC-1$alpha$ acetylation, increase NRF2 target gene expression, and improve Complex I-linked respiration in ME/CFS patient-derived cells — all three effects from a single intervention targeting the hub.
+ A factorial RCT (NAD#super[+] precursor $times$ AMPK activator) should show synergistic rather than additive effects on biogenesis markers, because AMPK and SIRT1 mutually activate each other (AMPK increases SIRT1 activity by upregulating NAMPT, raising the NAD#super[+] pool; SIRT1 deacetylates LKB1, which activates AMPK).

*Falsifiability:* This hub model would be falsified if (a) muscle NAD#super[+] is normal in ME/CFS despite PGC-1$alpha$ hyperacetylation, indicating a SIRT1-independent mechanism for the acetylation; or (b) NR/NMN supplementation raises tissue NAD#super[+] but does not change PGC-1$alpha$ acetylation or NRF2 target expression, indicating that NAD#super[+] is not rate-limiting for sirtuin activity in this context; or (c) PGC-1$alpha$ acetylation is normal in ME/CFS muscle, eliminating the need for a sirtuin-based explanation.

*Competing explanation:* A simpler model does not require NAD#super[+] depletion as a unifying hub. Chronic inflammation — well-documented in ME/CFS — can independently suppress PGC-1$alpha$ transcription (via NF-$kappa$B), impair NRF2 signaling (via inflammatory pathway crosstalk), and damage Complex I (via ROS) through their own well-characterized regulatory mechanisms. Under this three-cause model, G22, G34, and G39 are genuinely independent and do not require a shared upstream regulator. The hub model would be preferred over this simpler alternative only if co-measurement shows that NAD#super[+] depletion _correlates more tightly_ with all three downstream readouts than inflammatory markers do — i.e., if a multivariate model with NAD#super[+] as predictor outperforms one using TNF-$alpha$/IL-6 as predictors for the combined PGC-1$alpha$ acetylation + NRF2 target + Complex I activity outcome.

*Limitation:* The PBMC NAD#super[+] elevation @heng2025mecfs and the predicted muscle NAD#super[+] depletion have never been measured in the same cohort. The tissue-compartment dissociation is a prediction — specifically for skeletal muscle — not an observation; if muscle NAD#super[+] proves normal, the model does not retreat to "the relevant tissue is neurons" but is falsified (criterion a above). SIRT1 has numerous substrates beyond PGC-1$alpha$ and NRF2 (p53, FOXO3, NF-$kappa$B), and the acetylation changes may reflect a broader regulatory shift rather than a specific biogenesis/antioxidant mechanism. The hub model risks unfalsifiable circularity if every downstream effect is attributed to NAD#super[+] without specifying which effects would disprove the connection. This model was assembled post-hoc from pre-existing gap analyses; it should be evaluated as a hypothesis-generating framework, not as a confirmed mechanistic finding.
] <hyp:nad-sirtuin-hub>

