#import "../../../../../shared/environments.typ": *

#synthesis(title: [Shared Central Genetic Architecture Across Fibromyalgia and ME/CFS])[
The fibromyalgia GWAS of Kerrebijn et al.\ (2026) and the ME/CFS genetic findings of DecodeME and the Maccallini meta-GWAS jointly argue that both conditions carry a central-nervous-system genetic architecture: fibromyalgia's heritability is exclusively enriched in brain tissues and neural cell types (Achievement @ach:kerrebijn-fibromyalgia-gwas), mirroring the brain-first genetic architecture established for ME/CFS. Because fibromyalgia co-occurs with ME/CFS in 20--70% of cases and shares risk regions (_OLFM4_, _RABGAP1L_, _GPR52_), this convergent brain-enriched architecture supports a partially shared central genetic vulnerability (Hypothesis @hyp:fibromyalgia-cns-shared-genetic-vulnerability) rather than independent peripheral drivers.

A second convergent line points transdiagnostically: fibromyalgia's genetic correlation (rg > 0.7) with IBS, low back pain, and PTSD, and pervasive correlation with depression and migraine, alongside ME/CFS's rg = 0.75 with IBS, indicate a shared chronic-overlapping-pain and gut-brain genetic axis (Hypothesis @hyp:shared-transdiagnostic-cns-genetic-factor). The most important open question is whether a direct fibromyalgia × ME/CFS genetic correlation is significantly positive (Open Question @oq:fm-mecfs-genetic-correlation-untested) — currently untested — and whether the comorbidity reflects shared biology or partly diagnostic/referral artifact (Open Question @oq:fm-mecfs-comorbidity-referral-artifact).

What the evidence supports: a common central/nociplastic genetic architecture underlying both conditions and the chronic-overlapping-pain family. What remains speculative: whether specific loci (_HTT_/_GPR52_/_DRD2_) transfer mechanistically to ME/CFS, and whether the shared architecture is causal (genetic correlation is association, not proof of shared causal biology). The two-layer autoimmune reconciliation — non-HLA-linked central-sensitization genetics plus acquired antibody subsets — accommodates both the no-MHC GWAS finding and the passive-IgG autoantibody evidence (Hypothesis @hyp:fibromyalgia-autoimmune-reconciliation).

*Consequence:* Multiple independent genetic lines point to a shared brain-based (central-sensitization) architecture linking ME/CFS, fibromyalgia, and chronic-overlapping-pain conditions — which strengthens the case that the fibromyalgia-ME/CFS overlap is biologically grounded in a common nervous-system vulnerability, and argues for centrally-targeted comorbidity research, even though direct fibromyalgia × ME/CFS genetic correlation remains to be measured.
] <syn:fibromyalgia-genetics-shared-central-architecture>
