#import "../../../../shared/environments.typ": *

=== HPA Axis Abnormalities


==== Cortisol Dysregulation Patterns

<obs:cortisol-pattern>
Multiple studies document a consistent pattern of cortisol abnormalities in ME/CFS patients that differs qualitatively from both healthy individuals and patients with primary adrenal disorders. Baseline cortisol levels tend to be lower, though typically remaining within the broad “normal” laboratory reference range. The diurnal cortisol rhythm shows flattening, with reduced amplitude between morning and evening values. The cortisol awakening response (CAR)—the normal sharp rise in cortisol during the first 30–60 minutes after waking—appears attenuated. Additionally, cortisol responses to physiological and psychological stressors are blunted, despite appropriate ACTH response to exogenous CRH stimulation in some studies @pipper2024steroid.
The NIH deep phenotyping study by Walitt et al.\ identified neuroendocrine abnormalities consistent with HPA axis dysfunction, including altered catecholamine metabolism that affects upstream regulation of the HPA axis @walitt2024deep. The reduced central catecholamines documented in cerebrospinal fluid may contribute to impaired hypothalamic CRH release, providing a mechanistic link between neurological and endocrine dysfunction.

#observation(title: [Reported CRH-Neuron Reduction in Severe ME/CFS Hypothalamus])[
*Certainty: 0.30.* A single unpublished conference presentation (not yet peer-reviewed) from the University of Amsterdam (Netherlands Brain Bank ME/CFS programme), presented at the 2025 IACFS/ME conference, reports a pronounced reduction in CRH-immunoreactive neurons in the hypothalamic paraventricular nucleus of severe ME/CFS patients ($n = 7$) @dasilva2025iacfscrh. If confirmed, this would provide an anatomical substrate for the blunted central CRH drive and HPA hypoactivation documented in ME/CFS, relocating the origin of hypocortisolism from the adrenal gland to the hypothalamus. This finding, its cell-type specificity, its candidate drivers, and the substantial caveats attached to a single unpublished conference source (including whether it reflects neuron loss or peptide depletion) are developed in detail under the mechanisms of HPA dysfunction (@spec:central-crh-loss).
] <cf:crh-neuron-depletion>

Recent sex-stratified analysis by Pipper et al.\ (2024) revealed that cortisol dysregulation patterns differ significantly between male and female ME/CFS patients and vary by disease severity @pipper2024steroid. Female patients with severe ME/CFS demonstrated elevated 11-deoxycortisol (a cortisol precursor) and 17$alpha$-hydroxyprogesterone, suggesting impaired final enzymatic steps in cortisol synthesis. Male patients with mild to moderate disease showed frankly reduced cortisol and corticosterone levels but paradoxically elevated progesterone. These findings indicate that HPA dysfunction may involve enzyme deficiencies in steroidogenesis rather than simple hypothalamic-pituitary signaling deficits.

==== ACTH and CRH Abnormalities

The central components of the HPA axis—CRH from the hypothalamus and ACTH from the pituitary—show complex abnormalities that do not fit simple models of endocrine failure. Studies employing CRH stimulation tests have yielded inconsistent results. Some report normal ACTH and cortisol responses to exogenous CRH administration, while others document blunted ACTH responses despite adequate CRH stimulation. Still others find normal ACTH responses but reduced cortisol output, suggesting adrenal hyposensitivity. These inconsistencies likely reflect the heterogeneity of ME/CFS patient populations, differences in disease duration and severity, and the limitations of single-timepoint testing to capture dynamic regulatory dysfunction.

The most consistent finding across studies is evidence of enhanced negative feedback sensitivity @Papadopoulos2012HPA @Tomas2017. Dexamethasone suppression tests demonstrate that low doses of synthetic glucocorticoid produce greater and more prolonged suppression of cortisol secretion in ME/CFS patients compared to controls. This suggests that the hypothalamus and pituitary remain exquisitely sensitive to glucocorticoid feedback signals, inappropriately dampening HPA axis output even when cortisol levels are already low-normal. This pattern resembles the neuroendocrine adaptation seen in chronic stress conditions but persists inappropriately in ME/CFS despite the clinical need for robust stress responses.

==== Diurnal Rhythm Disruption

<obs:cortisol-rhythm>
The diurnal cortisol rhythm represents one of the most robust and well-characterized circadian processes in human physiology, yet ME/CFS patients consistently demonstrate flattening of this rhythm. Healthy individuals show a sharp cortisol peak within 30–60 minutes of waking (cortisol awakening response), followed by progressive decline throughout the day, reaching a nadir around midnight, and beginning to rise again in the early morning hours (3–4 AM) in anticipation of waking. In contrast, ME/CFS patients show reduced morning cortisol peak (blunted CAR), less pronounced decline during the day (flatter slope), and reduced overall amplitude (difference between peak and nadir), resulting in a “flattened” 24-hour pattern @cambras2018circadian.
The mechanistic basis for circadian rhythm disruption extends beyond the HPA axis itself to involve the central circadian clock in the suprachiasmatic nucleus (SCN) of the hypothalamus. The NIH study documented abnormalities in temporal-parietal junction function and altered brain metabolism that may affect SCN regulation @walitt2024deep. Additionally, inflammatory cytokines known to be elevated in ME/CFS (discussed in Chapter @ch:immune-dysfunction) directly disrupt circadian clock gene expression, creating bidirectional interactions between immune activation and circadian dysregulation.

The clinical consequences of flattened cortisol rhythm are profound. The morning cortisol peak serves essential physiological functions: promoting waking and alertness, mobilizing glucose for energy availability, preparing the cardiovascular system for upright posture and activity, and modulating immune function to prevent excessive inflammation. Loss of this peak explains the characteristic morning symptom severity reported by many ME/CFS patients. These include difficulty waking, prolonged morning fatigue requiring hours to achieve minimal function, orthostatic intolerance upon standing (discussed in Chapter @ch:cardiovascular), and cognitive dysfunction particularly severe in early morning hours.

