#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Acquired Alexithymia as an Interoceptive Deficit in ME/CFS])[
Elevated alexithymia—specifically difficulty identifying feelings (TAS-20 Difficulty Identifying Feelings subscale)—in ME/CFS reflects _acquired_ interoceptive dysfunction rather than trait-level psychological vulnerability. Maroti et al.\ (2017, n=43 CFS, 34 exhaustion syndrome, 43 controls) found significantly elevated alexithymia in CFS versus controls, with the Difficulty Identifying Feelings factor most affected and externally oriented thinking not differing @Maroti2017alexithymiaCFS. CFS patients showed lower emotional awareness than exhaustion syndrome patients, distinguishing chronic fatigue from stress-related exhaustion.

The interoceptive interpretation is that "difficulty identifying feelings" is not primarily an emotional processing deficit but a _bottom-up signal corruption_ problem: if interoceptive afferent signals (heart rate, gut motility, muscle tension, inflammatory signals) are degraded or noisy at the brainstem and thalamocortical level, the brain cannot construct the differentiated interoceptive experiences that emotion categories require. Barrett's Theory of Constructed Emotion @Barrett2025ConstructedEmotion predicts this specific consequence: emotion concepts require interoceptive sensory data to be categorised; degrading the sensory input degrades the categorisation, producing the phenomenology of alexithymia.

Bileviciute-Ljungar and Friberg (2020, n=30 ME/CFS) found that lower emotional awareness correlated with more frequent nocturnal awakenings on polysomnography @BileviciuteLjungar2020emotionAwarenessSleep, providing a link to sleep fragmentation—itself a downstream consequence of cytokine-driven arousal system dysregulation and orexin suppression. The relationship may be bidirectional: sleep disruption impairs interoceptive processing, and disrupted interoceptive processing worsens sleep quality.

(Certainty: 0.45. Alexithymia elevation in CFS is replicated across two independent samples (Maroti 2017, Bileviciute-Ljungar 2020) but both are small-to-moderate and from overlapping research groups. The interoceptive interpretation is plausible and theoretically coherent but has NOT been directly tested with concurrent heartbeat detection and TAS-20 measures in ME/CFS. *Falsification condition:* If TAS-20 Difficulty Identifying Feelings scores do NOT correlate with interoceptive accuracy (heartbeat detection performance) in ME/CFS—i.e., alexithymia is present but interoceptive performance is preserved—then alexithymia is not an interoceptive deficit and alternative mechanisms (HPA axis dysregulation, premorbid psychological factors) must explain it. A stratified prediction can distinguish trait from acquired alexithymia: TAS-20 DIF scores will correlate with HBDT accuracy in patients reporting post-illness-onset alexithymia (retrospective self-report of emotional change since ME/CFS onset) but NOT in patients reporting premorbid alexithymia.)
] <hyp:ch15-alexithymia-acquired>
