#import "../../../../../shared/environments.typ": *

#speculation(title: [Histamine-Orexin Arousal Bridge and the H1-Blocker Sedation Threshold])[
Histaminergic and orexinergic wake systems interact directly: orexin neurons act on monoaminergic targets — including histaminergic tuberomammillary neurons — to maintain arousal @Sakurai2021OrexinMonoamine, and both systems are canonical wake-promoting neuromodulators @Jones2020ArousalCircuits. Wake-promoting neuromodulators (histamine, orexin, norepinephrine) are further tied to sleep quality and glymphatic clearance @Pedersen2026WakeNeuromodulators.

Applied to MCAS: this bridge is not direct — peripheral mast-cell histamine does not freely cross the blood-brain barrier, so any contribution to central histaminergic tone would require an indirect route (for example vagal or immune signalling to the tuberomammillary nucleus) that is not yet evidenced. If such a route exists, episodic mast-cell histamine surges could transiently add to the central arousal load that contributes to the "wired but tired" mismatch — high arousal alongside the fatigue and non-restorative sleep that impaired clearance is proposed to produce @Pedersen2026WakeNeuromodulators. By symmetry, the sedation threshold of an H1 blocker — the dose at which central H1 blockade first emerges — could index a patient's central histamine arousal load: a lower threshold would mark a smaller central histaminergic reserve, a higher one a larger compensatory drive. The orexin-histamine interaction is established in animals and in reviews of human circuitry; no study has measured a histamine arousal load or an H1-blocker sedation threshold in ME/CFS (translation gap). (Certainty: 0.35)

_Falsifiable prediction:_ A pharmacodynamic measure of the H1-blocker sedation threshold (dose at which objective vigilance first falls) correlates with a marker of central histaminergic or orexinergic tone (for example cerebrospinal-fluid orexin-A or histamine), and ME/CFS patients with a "wired but tired" profile show a distinct, higher threshold than those without it.

*Consequence:* The sedation threshold would become a bedside readout of central histamine arousal load, giving "wired but tired" a specific neuromodulator correlate. This is a research measure, not a basis for dosing antihistamines.
] <spec:histamine-orexin-arousal-bridge>
