#import "../../../../../shared/environments.typ": *

#speculation(title: [Mast-Cell Mediator Escape Beyond H1/H2/CysLT1 Blockade])[
Receptor blockade does not stop mast-cell degranulation; it only blocks the downstream effect of released histamine and cysteinyl leukotrienes. Tryptase, a major mast-cell granule protease, signals through PAR-2 independently of histamine receptors; in rodent injury models this pathway has been shown to promote neuroinflammation and microglial activation @Ocak2020TryptasePAR2Neuroinflammation @Qin2021TryptaseMicrogliaPAR2, a route reinforced by the documented bidirectional mast-cell–microglia axis @Lakatos2025MicrogliaMast. Prostaglandin D2 (PGD2), co-released on degranulation, acts through DP1, CRTH2, and TP receptors — none of which is blocked by H1/H2 antihistamines or a CysLT1 antagonist such as montelukast @Kupczyk2017PGD2CRTH2. Residual MCAS symptoms can therefore persist even under maximal H1/H2/CysLT1 blockade, not because blockade is incomplete but because the escape mediators are pharmacologically untouched. The tryptase–PAR2 evidence is preclinical (rodent cardiac arrest and subarachnoid haemorrhage models); there are no ME/CFS data. (Certainty: 0.35)

_Falsifiable prediction:_ In MCAS patients maintained on maximal H1/H2/CysLT1 blockade, residual symptom severity correlates with tryptase and/or urinary PGD2 metabolites rather than with circulating histamine load.

*Consequence:* Persistent symptoms under full receptor blockade are consistent with two possibilities — non-histaminergic mediator escape, or simply that the drugs do not address the disease driver — and should not be assumed to prove either. This is a mechanistic framing, not a treatment recommendation — tryptase/PAR-2 and PGD2/CRTH2 blockers are not clinically available for MCAS.
] <spec:mast-cell-mediator-escape>
