#import "../../../../../shared/environments.typ": *

#speculation(title: [Pulsed Dosing and a Drug-Holiday Restore-Test for Antihistamine Tachyphylaxis])[
Chronic H1-receptor blockade can increase H1 receptor expression, a homeostatic response documented in receptor pharmacology @Miyoshi2006H1Receptor and proposed as a target of antiallergic therapy @Fukui2007H1GeneExpression. An analogous upregulation is described for H2 receptors, where the inverse-agonist property of H2 antagonists accounts for upregulation of spontaneously active H2 receptors @Smit1996H2InverseAgonism. Clinically, a related phenomenon is reported as rebound pruritus and urticaria after stopping chronic antihistamines, in a scoping review and a cetirizine case report @Seng2026ReboundReview @Seng2025CetirizineRebound. The picture is not uniform: tolerance to the sedative effects of H1 antihistamines develops within days @Richardson2002H1Tolerance, while tolerance to the anti-allergic effect is debated, and the two are pharmacologically distinct. Together these lines raise the possibility that some apparent "the antihistamine stopped working" reports reflect receptor upregulation and withdrawal rebound rather than true loss of efficacy. A research protocol that deliberately interrupts dosing and measures the response on reintroduction could separate the two: if the response is restored after an interruption, the mechanism is reversible desensitisation and upregulation; if it stays blunted on reintroduction, it is true tolerance or an underlying worsening of disease. The caution is real: withdrawal rebound after chronic antihistamines is itself documented, so any drug holiday carries a possible worsening of pruritus and urticaria, and this specific risk has not been quantified in ME/CFS or MCAS patients. The receptor-upregulation evidence is molecular (cell and receptor-expression studies) and the rebound evidence is case-level and review-level; no controlled trial has tested interrupted antihistamine dosing in any population, and none in ME/CFS. Interrupting chronic antihistamines is not a recommended strategy: in mast-cell-driven disease the withdrawal rebound can be severe, and any structured interruption should occur only under clinical supervision. (Certainty: 0.35)

_Falsifiable prediction:_ In patients reporting antihistamine tachyphylaxis, a supervised drug holiday followed by reintroduction of the same agent restores the anti-pruritic and anti-allergic response when the cause is receptor upregulation (reversible), and fails to restore it when the cause is true tolerance or disease escalation.

*Consequence:* If the distinction holds, some apparent antihistamine tolerance may be reversible desensitisation rather than true loss of efficacy. Interrupting antihistamines is not clinical guidance and carries a documented, though unquantified-in-ME/CFS, rebound risk that can be severe in mast-cell-driven disease. This is a research question, not a recommended strategy.
] <spec:antihistamine-tachyphylaxis-pulsed-dosing>
