#import "../../../../../shared/environments.typ": *

#speculation(title: [Circadian Timing of Mast-Cell-Targeted Drugs])[
Allergic and asthmatic disease has a well-described circadian rhythm: symptoms and bronchial reactivity worsen in the overnight and early-morning hours, tracking a nocturnal peak in inflammatory mediators rather than random fluctuation @Smolensky2007Chronotherapy. Urinary leukotriene E4, the stable end-product of cysteinyl-leukotriene synthesis, peaks at night in both healthy subjects and nocturnal asthmatics @Kurokawa2001LeukotrieneE4, and an inhaled corticosteroid that suppresses that early-morning leukotriene surge also improves nocturnal asthma control @Tanaka2003NocturnalLTE4. Mast-cell reactivity itself shows a time-of-day signal, with skin-prick-test wheal size varying by clock time @Ochfeld2021DiurnalSPT. The chronopharmacology principle is that drug delivery timed to the rhythm of the target system can improve the effect-to-dose ratio @Lemmer2005Chronopharmacology. Montelukast, a cysteinyl-leukotriene receptor (CysLT1) antagonist, is already labelled for evening dosing, a rare instance where the nocturnal-mediator logic has reached routine practice. A caution against overgeneralising: brain histamine is a wake-promoting signal whose circadian peak runs opposite to the peripheral allergic mediators @Mochizuki2022HistamineAlert, so "histamine peaks at night" holds for the peripheral mast-cell compartment, not for histamine everywhere in the body. If the same nocturnal-mediator rhythm governs the mast-cell-driven symptoms of ME/CFS, then shifting H1/H2 antihistamines and CysLT1 antagonists toward the evening could improve overnight and early-morning symptom control at an unchanged total daily dose. This is untested in ME/CFS: no trial has compared morning against evening dosing of these drugs in ME/CFS or MCAS, and the circadian evidence comes from asthma, rhinitis, and skin-testing cohorts, not from ME/CFS patients. (Certainty: 0.35)

_Falsifiable prediction:_ In ME/CFS patients with mast-cell-type symptoms on a stable total daily dose of H1/H2 antihistamines or a CysLT1 antagonist, an evening-weighted schedule reduces overnight and early-morning symptom scores (and, where measured, nocturnal urinary leukotriene E4) relative to a morning-weighted schedule of the same total dose.

*Consequence:* If confirmed, time-of-day dosing would be a low-cost lever on symptom control. Until an AM-vs-PM trial is run in ME/CFS, this remains a scheduling hypothesis borrowed from asthma chronobiology, not a recommendation; moving sedating agents to the evening also carries an unmeasured next-day sedation trade-off.
] <spec:circadian-mast-cell-drug-timing>
