#import "../../../../../shared/environments.typ": *

#speculation(title: [Cholinergic Modulation of Mast Cells Is Bidirectional])[
Acetylcholine acts on mast cells in both directions: it activates resting mast cells through the M3 muscarinic receptor but suppresses degranulation in stimulated mast cells through the α7 nicotinic receptor, a receptor-pattern-dependent dual effect @Kutukova2025DualAChMastCell. Enhancing cholinergic tone can increase mast-cell degranulation (neostigmine augmented degranulation and CGRP in a migraine model) @Kilinc2024MeningealMastCholinergic, and mast-cell activation depends on intact vagal signalling in vivo @Woestemeier2026VagalMastCell. The α7 arm is itself bidirectional: α7 agonism suppresses cysteinyl leukotriene release without affecting degranulation @Mishra2010NicotineAlpha7LT, yet α7 activation on mast cells accelerates atherosclerosis — a pro-inflammatory effect that cautions against cholinergic approaches in mast-cell-active patients @Wang2017NicotineAlpha7Athero. The net effect of pyridostigmine (an acetylcholinesterase inhibitor) in a mast-cell-active patient is therefore unpredictable from mechanism alone. No direct pyridostigmine-plus-mast-cell study exists; all evidence is in vitro or animal. (Certainty: 0.25)

_Falsifiable prediction:_ In mast-cell-active ME/CFS patients, pyridostigmine produces no consistent directional effect on MCAS symptom severity, and the observed direction tracks the patient's prevailing cholinergic receptor profile (M3 vs. α7 dominance).

*Consequence:* Pyridostigmine cannot be predicted to help or harm a mast-cell-active patient from mechanism alone; α7 agonism carries a documented pro-inflammatory risk signal. This is a mechanistic caution, not a treatment recommendation for or against pyridostigmine.
] <spec:cholinergic-mast-cell-bidirectional>
