#import "../../../../../shared/environments.typ": *

#speculation(title: [Cholinergic Reserve Index as a Tolerability Predictor for Pyridostigmine])[
Pyridostigmine, a reversible acetylcholinesterase inhibitor, raises acetylcholine at both nicotinic and muscarinic sites, which is why its benefit (ganglionic and neuromuscular) and its dose-limiting side effects (gastrointestinal cramps, diarrhoea, salivation, sweating, bradycardia, all muscarinic) arise from the same pharmacological action. This structure implies a per-patient window between the dose that produces benefit and the dose at which muscarinic side effects become intolerable. That window, the gap between the benefit dose and the side-effect dose, could be formalised as a "cholinergic reserve index": a patient with a wide window has ample parasympathetic capacity and is likely to tolerate the drug, while a patient whose side effects appear at or below the benefit dose has little reserve and is likely to discontinue. The concept is assembled from adjacent populations. The direct ME/CFS datapoint is a trial reporting that pyridostigmine improved hand-grip strength in ME/CFS @Schlomer2025PyridostigmineMECFS, but it did not report a formal side-effect threshold. Dose-response and tolerability data are richer in autonomic failure and POTS: pyridostigmine is a listed option for POTS in recent review and systematic-review literature @Chung2026POTSReview @Schiweck2026POTSSystematic @Raj2005PyridostigminePOTS, its orthostatic-hypotension efficacy has measurable clinical correlates @Okamoto2025PyridostigmineOH, and its pressor effect is enhanced when combined with atomoxetine @Okamoto2019AtomoxetinePyrido or contrasted with yohimbine @Shibao2010YohimbinePyrido. None of these studies computed a benefit-to-side-effect dose ratio, so the index is a proposed construct, not an existing measurement. The translation gap matters: the side-effect profile is similar across conditions, but the benefit target in ME/CFS (grip strength, possibly autonomic tone) differs from the pressor endpoint in orthostatic hypotension, so the index must be re-derived in ME/CFS rather than borrowed. (Certainty: 0.40)

_Falsifiable prediction:_ In ME/CFS (and POTS) patients initiating pyridostigmine, the ratio of the lowest benefit dose to the lowest dose producing intolerable muscarinic side effects predicts continuation at 12 weeks: patients whose side-effect dose sits at or below the benefit dose (index $lt.eq$ 1) discontinue, while those with a wider window (index $gt.eq$ 2) continue.

*Consequence:* If validated, a simple titration observation available in routine practice would let a clinician predict pyridostigmine tolerability before committing a patient to a long trial, sparing those with little cholinergic reserve a failed course. Until it is measured prospectively, the index is a descriptive hypothesis, not a validated predictor.
] <spec:cholinergic-reserve-index>
