#import "../../../../../shared/environments.typ": *

#speculation(title: [Histamine Clearance Defect vs. Receptor Over-Stimulation])[
A histamine *degradation* defect is mechanistically distinct from receptor over-stimulation. Histamine intolerance arises when accumulation exceeds degradation capacity: DAO degrades extracellular and ingested histamine (mainly gut), while HNMT is cytosolic and degrades intracellular histamine (mainly CNS) @Maintz2007HistamineIntolerance. Receptor blockade lowers the symptomatic response to a given histamine load but does not remove that load, so H1/H2/CysLT1 blockade can mask an underlying clearance deficit without correcting it. Serum DAO measurement has not proven reliable as a diagnostic biomarker @Rentzos2024DAOMeasurement, and the AOC1/HNMT variant literature is reviewed in the context of dietary histamine management @Zybul2026DAOGastro @Kadiyska2025AOC1HNMT. A fibromyalgia narrative review proposes DAO-deficiency histamine intolerance as a potentially treatable subtype @ProtasioNetto2026HITFibromyalgia, but this is narrative and the fibromyalgia population, not ME/CFS. The DAO enzyme and its measurement are treated in detail at @sec:dao; the specific HNMT clearance-failure argument sits at @spec:hnmt-clearance and is not duplicated here. (Certainty: 0.40)

_Falsifiable prediction:_ Among histamine-symptomatic patients whose symptoms do not respond to receptor blockade, functional DAO/HNMT deficiency (genotype or measured activity) is more prevalent than among those who respond to blockade alone.

*Consequence:* Clearance defects and receptor over-stimulation imply different interventions (substrate reduction vs. blockade); treating a clearance defect with receptor blockers alone would mask, not resolve, the underlying load. This is a mechanistic distinction, not a treatment recommendation — dietary histamine restriction and DAO supplementation lack robust controlled evidence in ME/CFS.
] <spec:histamine-clearance-vs-receptor>
