#import "../../../../../shared/environments.typ": *

#speculation(title: [Compensatory Mediator Release After Histamine-Receptor Blockade])[
HARM-HYPOTHESIS (unsubstantiated): blocking histamine receptors could remove an autocrine H2 negative-feedback loop and thereby increase mast-cell mediator release. The original observation is that histamine inhibits its own release through the H2 receptor, a negative-feedback control @Lichtenstein1973H2Feedback, and that H1 and H2 antihistamines act on this histamine-mediated inhibition of release @Lichtenstein1975H1H2Release. If H2 blockade removes that brake, mediator release should rise. The in-vitro evidence is old and points in both directions. In human basophils, H2 antihistamines augmented antigen-induced histamine release, consistent with removal of negative feedback @Tung1982H2AugmentRelease. In isolated rat mast cells, the finding had the opposite emphasis: evidence for H2-receptor-mediated inhibition of histamine release @Masini1982H2InhibitRelease. These studies differ in cell type (basophils versus mast cells), species (human versus rat), and conclusion, so the direction of the net effect in vivo is genuinely unresolved. There is no clinical evidence for this hypothesis: it has not been shown in any human cohort, and certainly not in ME/CFS, and the very large real-world exposure to H2 antagonists without an obvious signal of increased mediator-driven disease argues against a large effect, while not excluding a subtle one. (Certainty: 0.25)

_Falsifiable prediction:_ If H2 blockade removes autocrine negative feedback, ex-vivo histamine release from a patient's own cells (basophil or mast-cell assay) increases after H2-antagonist exposure relative to before, and some H2-blocker users show a measurable rise in mediator markers; the hypothesis fails if a controlled ex-vivo test shows no augmentation, or if the augmentation is confined to a single in-vitro model.

*Consequence:* This is a possible harm, not a demonstrated one. The contradictory in-vitro data cannot guide famotidine or other H2-antagonist prescribing, and they argue for a study, not for any change in practice.
] <spec:compensatory-mediator-synthesis-receptor-blockade>
