#import "../../../../shared/environments.typ": *

=== Existing Models
<sec:existing-models>

Four bodies of work constitute the substantive prior art in ME/CFS modeling.

*Phair's IDO metabolic trap.* The most developed mechanistic model in the ME/CFS literature is Phair, Davis, and Kashi's mathematical analysis of tryptophan metabolism @phair2019ido. This model demonstrates that substrate inhibition of indoleamine 2,3-dioxygenase 1 (IDO1), combined with non-functional IDO2 variants, produces a bistable system: one stable equilibrium at physiological tryptophan concentrations and a second pathological equilibrium at elevated concentrations. The model is genuinely novel in showing that a single-pathway bistability mechanism can explain both the triggering (transition to the pathological state during immune activation) and the persistence (stability of that state after the trigger resolves) of ME/CFS. It generates specific, testable predictions---including that recovery from the pathological state requires weeks even if tryptophan input is halted entirely. However, the model is narrowly scoped: it addresses one enzyme pathway and does not model energy metabolism, immune cell dynamics, neuroendocrine function, or the multi-system interactions that characterize the disease.

*Broderick's cytokine network analysis.* Broderick and colleagues applied network graph analysis to cytokine co-expression patterns in CFS patients versus controls @broderick2010cytokine. By measuring 16 plasma cytokines in 40 female CFS patients and 59 matched controls, they constructed mutual-information networks and identified topological differences: CFS networks were more hub-like, with attenuated Th1 and Th17 responses and altered NK cell signaling patterns. This work is computational but not dynamical---it characterizes network _structure_ (which cytokines co-vary) rather than network _dynamics_ (how cytokine concentrations evolve over time). It does not use ODEs, does not model temporal trajectories, and does not generate predictions about disease progression or treatment response. It remains the most rigorous network-level characterization of ME/CFS immune dysfunction.

*Morris and Maes's neuro-immune framework.* Morris and Maes proposed a conceptual neuro-immune model describing how peripheral immune activation, oxidative and nitrosative stress, and mitochondrial damage interact to produce ME/CFS symptoms @morris2013neuroimmune. The model identifies the pathway from infection through immune activation, oxidative and nitrosative stress, and mitochondrial damage to post-exertional malaise. While comprehensive in scope and biologically well-grounded, it is a verbal/diagrammatic model, not a mathematical one. It does not specify rate equations, parameter values, or quantitative predictions. It identifies the _structure_ of the problem that a mathematical model should formalize.

*Li et al.'s genome-scale metabolic modeling.* The most recent computational contribution is Li and colleagues' application of genome-wide precision metabolic modeling (GPMM) to ME/CFS and Long COVID muscle tissue @li2025systems. Using transcriptomic data and constraint-based flux balance analysis, they identified downregulation of the alanine/aspartate and arginine/proline metabolism pathways and proposed L-ornithine and L-aspartate (LOLA) supplementation as a candidate intervention. This work uses a genuine computational framework (constraint-based metabolic modeling), but it is _static_: flux balance analysis computes steady-state metabolic fluxes under optimality assumptions, without modeling temporal dynamics, feedback loops, or multi-system interactions. It does not address immune function, neuroendocrine regulation, or the dynamic phenomena (PEM, disease onset, relapse--remission) that define ME/CFS clinically.

