#import "../../../../shared/environments.typ": *

=== Electron Transport Chain (@eq:complex-i and @eq:atp-synthase)

*Measurements required.* (1) Peak VO₂ from CPET: directly constrains $V_(max, upright("CI"))$ and overall ETC capacity (why: VO₂ is the terminal electron acceptor flux). (2) CoQ10 levels: serum ubiquinone/ubiquinol measurement (why: determines $[upright("UQ")]$ in the model). (3) Two-day CPET decrement: the day-2 vs. day-1 VO₂ difference constrains the ROS-mediated damage rate (why: the decrement reflects acute ETC damage from exertion). (4) $"^{31}P"-"MRS"$: provides in vivo measurement of phosphocreatine recovery time, directly related to mitochondrial oxidative capacity.

*Worked example.* A patient has $alpha_(upright("CI")) = 0.65$ (35% Complex I impairment). Using the ETC model with healthy $Delta Psi_(max) = 180$ mV and $Delta Psi_(upright("threshold")) = 110$ mV: healthy steady-state $Delta Psi approx 160$ mV, giving ATP synthase a driving force of $(160 - 110)/160 = 31%$ of maximum. With $alpha_(upright("CI")) = 0.65$, reduced proton pumping lowers $Delta Psi$ to $approx 135$ mV, giving a driving force of $(135 - 110)/135 = 19%$---a 39% reduction in ATP synthase flux from a 35% Complex I impairment. This disproportionate effect is the "cliff" nonlinearity: near the threshold, small $Delta Psi$ drops cause large ATP synthesis drops.

*Inter-model dependencies.* _Inputs_: NADH from glycolysis and Krebs cycle, $[upright("UQ")]$ (modifiable by CoQ10 supplementation). _Outputs_: ATP production rate (to ATP balance equation), ROS production (to oxidative stress model), $Delta Psi$ (determines mitophagy signaling via PINK1). The oxygen consumption rate $J_(upright("CIV"))$ is constrained by $"DO"_2$ from the cardiovascular model (@ch:integrated-systems).

*Scope and rationale.* The ETC is modeled as four complexes plus ATP synthase, omitting complex subunit detail and supramolecular organization. This level captures the bioenergetically relevant behavior: proton pumping, membrane potential dynamics, and the threshold nonlinearity. Subunit-level modeling would require structural biology data not available for ME/CFS tissues.

*Falsification criteria.* The model predicts a nonlinear (convex) relationship between Complex I impairment and ATP production loss, with a cliff near $Delta Psi_(upright("threshold"))$. *Falsified if*: $"^{31}P"-"MRS"$ studies in ME/CFS patients reveal a _linear_ relationship between mitochondrial impairment indices and functional ATP production, or if the predicted cliff effect at $alpha_(upright("CI")) approx 0.6$ is not observed (patients with moderate impairment show proportional, not disproportionate, ATP loss).

*Clinical implications.* The cliff effect implies that patients near the threshold ($alpha_(upright("CI")) approx 0.6$--$0.7$) have the most to gain from even modest mitochondrial support: a small improvement in Complex I activity produces a disproportionate ATP increase. Patients well above threshold ($alpha_(upright("CI")) > 0.8$) will show minimal response to mitochondrial supplements (their $Delta Psi$ is already well above threshold), while those well below ($alpha_(upright("CI")) < 0.5$) may not respond because the deficit is too large for supplements to bridge. *Treatment implication*: CoQ10/$"NAD"^"+"$ supplementation should be most effective in moderate, not mild or severe, metabolic impairment.

