#import "../../../../shared/environments.typ": *

=== Immune-Metabolic Crosstalk Maintaining the Energy Crisis
<sec:immune-metabolic-crosstalk>

Immune activation is not independent of metabolic dysfunction—instead, immune-mediated pathways actively maintain and amplify the energy crisis. This creates a feedback loop where immune activation perpetuates energy failure.

==== Tryptophan-Kynurenine Metabolism and NAD#super[+] Depletion

The tryptophan-kynurenine pathway is one of the primary immune-activated routes of tryptophan catabolism. Elevated kynurenine production is associated with chronic immune activation (elevated IFN-$gamma$, TNF-$alpha$). However, the balance of kynurenine metabolites matters: normal kynurenine metabolism feeds into NAD#super[+] synthesis, supporting mitochondrial energy production; imbalanced metabolism produces neurotoxic metabolites while depleting NAD#super[+].

A recent metabolomics study @Abujrais2024tryptophan (published in ACS Chemical Neuroscience) profiled tryptophan metabolism in ME/CFS plasma and found higher 3-hydroxykynurenine (a neurotoxic branch product), lower kynurenic acid (neuroprotective, NAD#super[+]-producing), and lower quinolinic acid (a neurotoxic NMDA agonist that also feeds NAD#super[+] synthesis via QPRT). The net effect: immune-mediated tryptophan catabolism is diverted away from NAD#super[+] synthesis and toward neurotoxic branches. This directly links immune activation to NAD#super[+] depletion and impaired mitochondrial function.

==== T-Cell Exhaustion with Metabolic Reprogramming

Iu et al. @iu2024tcell_exhaustion (published in PNAS) profiled CD8#super[+] T cell epigenetics and metabolism in ME/CFS, finding that T cells are epigenetically primed toward an exhausted phenotype (high PD-1, TIM-3, LAG-3) while simultaneously showing altered metabolic reprogramming. Post-exercise, this metabolic dysregulation worsened. This suggests T cells cannot sustain normal metabolic flexibility in response to immune demands, contributing to both the dysfunctional immune response and persistent metabolic strain.

==== Exaggerated Innate Immune Response with Metabolic Consequences

Che, Hornig, and Lipkin  (published in npj Metabolic Health and Disease) documented an exaggerated innate immune response to standard challenges in ME/CFS. Their metabolomic data showed that immune activation is associated with impaired citric acid cycle (TCA cycle) flux and reduced beta-oxidation capacity. Mechanistically, IFN-gamma (elevated in their cohort) accelerates tryptophan degradation via indoleamine 2,3-dioxygenase (IDO), directly linking innate immune state to NAD#super[+] depletion and energy failure.

==== Oxidative Stress in Immune Cells

Shankar et al.\ @Shankar2025oxidativestress (published in PNAS) measured reactive oxygen species (ROS) in circulating lymphocytes from ME/CFS and Long COVID patients. They found elevated ROS in memory T cells, with striking sex differences: females showed higher ROS production and T-cell hyperproliferation; males showed evidence of mitochondrial lipid oxidative damage. Critically, metformin treatment attenuated T-cell hyperproliferation in vitro, suggesting ROS-driven immune dysregulation may be pharmacologically reversible.

==== Mitochondrial Fragmentation in Immune Cells: The DRP1 Connection

Schreiner et al.\ (2020) provided mechanistic evidence that HHV-6 reactivation triggers DRP1-mediated mitochondrial fragmentation in ME/CFS PBMCs @SchreinerEtAl2020, establishing that the same fission machinery implicated in neuronal mitochondrial dysfunction operates in immune cells. Missailidis et al.\ (2020) demonstrated that EBV-immortalized ME/CFS lymphocytes carry an isolated Complex V (ATP synthase) defect with compensatory respiratory upregulation and proton leak @Missailidis2020ComplexV. Despite normal resting ATP, these cells exhaust their reserve capacity under activation — the same demand-response failure pattern observed in skeletal muscle. Critically, T-cell subset counts are within normal range (Cliff 2019, n=251 @Cliff2019Cellular), confirming that ME/CFS immune dysfunction is metabolic and functional, not numerical. The integrated model: post-infectious triggers (viral reactivation, ER stress) $arrow.r$ DRP1 activation $arrow.r$ mitochondrial fragmentation $arrow.r$ failed metabolic reprogramming in CD8+ effector memory T cells $arrow.r$ epigenetic exhaustion (Iu 2024 @iu2024tcell_exhaustion) $arrow.r$ impaired immune surveillance and viral clearance. This pathway is developed in full in Chapter @ch:immune-dysfunction, Hypothesis @hyp:cd8-mito-fragmentation-exhaustion.

==== Immune Exhaustion: Suppression in ME/CFS, Activation in Long COVID

The largest direct immunophenotyping comparison of the two conditions (Petrov 2026, n=207 total) identified divergent immune states: Long COVID shows monocyte polarization, dendritic cell expansion, and persistent immune activation with features of exhaustion; ME/CFS shows reduced costimulatory molecule expression, impaired CCR7 trafficking, and less coordinated activation — a pattern of immune *suppression*, not activation-driven exhaustion @Petrov2026Immunophenotyping. This distinction is mechanistically critical: the same systemic energy failure that cripples mitochondrial function in neurons and muscle also suppresses immune cell activation capacity. The metabolic cost of immune activation cannot be met. Eaton-Fitch et al.\ (2024) confirmed this divergence at the gene expression level: ME/CFS PBMCs showed downregulated interferon signaling and immunoglobulin genes (suppression), while Long COVID showed dysregulated antigen presentation and cytokine signaling (activation) @EatonFitch2024ImmuneExhaustion.

Lee et al.\ (2025), using the UK ME/CFS Biobank (n=96), found that severe ME/CFS is distinguished from mild/moderate by increased cytotoxic effector molecule expression and enhanced early immunosenescence (CD28−) markers @Lee2025TcellActivation. This suggests that the immune suppression in ME/CFS is not static — it progresses with disease severity toward a senescent exhaustion state, consistent with the accelerated immune aging documented in Section @sec:immunosenescence-aging.

==== Multi-Omics Integration: The Full Picture

The Heng 2025 multi-omics study @heng2025mecfs integrated cellular ATP profiling with plasma proteomics from 61 matched pairs, revealing coordinated abnormalities: elevated AMP and ADP with a reduced ATP/ADP ratio (indicating cellular energy stress), altered immune cell subsets skewed toward less mature effector populations, and elevated vascular dysfunction markers (VWF, fibronectin, thrombospondin-1). A 7-biomarker panel spanning these three domains achieved 91% diagnostic accuracy (Section @sec:systems-biology in Chapter @ch:integrative-models).

These findings were substantially extended by Hoel et al.\ (2026) @Hoel2026proteome, who applied aptamer-based proteomics (SomaScan, 7,326 aptamers targeting 6,493 proteins) to serum from 50 ME/CFS patients and 29 healthy controls. Their analysis revealed a striking metabolic enzyme signature: key glycolytic enzymes—glyceraldehyde-3-phosphate dehydrogenase (GAPDH), fructose-bisphosphate aldolase A (ALDOA), and L-lactate dehydrogenase B chain (LDHB)—were among the most significantly reduced intracellular proteins in ME/CFS serum. Since these enzymes are normally abundant in skeletal muscle, their reduced circulating levels suggest decreased muscle protein turnover or altered cellular release patterns rather than simple enzyme deficiency. Notably, ATP synthase inhibitory factor 1 (ATP5IF1), which regulates mitochondrial ATP hydrolysis under hypoxic conditions, was also reduced, consistent with the mitochondrial stress protection deficit described in Section @sec:mito-evidence.

Complementing the intracellular enzyme reductions, Hoel et al.\ found chronically elevated metabolic stress hormones: FGF-21 was significantly higher in ME/CFS patients, validated by ELISA in an extended cohort (n = 212 ME/CFS, n = 66 HC), with women showing a particularly significant elevation. GDF-15, leptin, resistin, and fatty acid-binding proteins FABP3 and FABP4 were also elevated. FGF-21 and GDF-15 are “exerkines” that normally rise transiently during intense exercise to coordinate systemic energy adaptation @Hoel2026proteome. Their chronic elevation in ME/CFS—in the absence of intense exercise—suggests a state of persistent metabolic emergency signaling, as though the body is continuously experiencing the energy crisis of maximal exertion at rest. This pattern connects to the clinical observation that ME/CFS patients describe exhaustion disproportionate to activity level: their metabolic stress signaling reflects a genuine cellular energy crisis, not a perceptual distortion.

Together, these studies demonstrate that energy metabolism dysfunction in ME/CFS is not limited to mitochondrial abnormalities but extends to a coordinated shift in the circulating metabolic landscape: reduced intracellular metabolic enzymes, elevated stress hormones, and altered secretory patterns spanning multiple tissues. Breaking this cycle may require simultaneous intervention at multiple levels—addressing both the mitochondrial energy deficit and the chronic stress signaling that perpetuates it.

