#import "../../../../shared/environments.typ": *

#speculation(title: [Structural Vagal Damage as a Distinct Upstream Node in the Causal DAG])[
*Certainty: 0.30.* (Origin: brainstorm.) The extended causal DAG (@sec:inflammation-source-dag) and the paper's formal models currently represent vagal function as a *rate* (efferent tone modulating inflammation), implicitly assuming the substrate is intact and the deficit is functional. The structural denervation evidence (@hyp:structural-vagal-denervation-cap) motivates adding a separate node, $V_(upright("str"))$ — a *vagal structural capacity* variable that sets the ceiling on achievable vagal signaling regardless of stimulation. In this formulation, functional vagal tone is bounded above by $V_(upright("str"))$: if efferent cholinergic fibers are physically depleted, no amount of afferent activation (endogenous or via taVNS) can restore CAP output beyond the surviving-fiber ceiling. $V_(upright("str"))$ is a single upstream cause with three measurable downstream consequences — CAP disengagement (inflammation), impaired gastric motility (GI symptoms), and reduced HF-HRV (dysautonomia) — matching the correlation structure Acanfora observed @acanfora2026vagaldenervation. A distinct, slowly-varying structural variable is also mechanistically natural because fiber loss and functional signaling have very different time constants (a bistable-damage variant is plausible but not required).

*Testable prediction:* If $V_(upright("str"))$ is a genuine separate node rather than a redundant relabeling of functional tone, then taVNS-induced TNF-$alpha$ suppression (a functional CAP assay, idea 9.3) should show a *response ceiling* that correlates with structural fiber density (gastric VIP+ IHC or a validated proxy) and is *independent* of baseline functional HRV. Concretely: in an adequately powered ME/CFS cohort ($n gt.eq 60$), the partial $R^2$ of fiber density for the taVNS TNF-$alpha$-suppression ceiling, after adjusting for baseline HRV, should exceed 0.05. Falsified if that partial $R^2$ is below 0.05 (the ceiling is fully accounted for by functional tone), or if GI, HRV, and inflammatory readouts do not share a common latent factor.

*Limitations:* $V_(upright("str"))$ is not yet parameterized — no ME/CFS structural vagal measurement exists to estimate it, and the taVNS-ceiling prediction has not been tested. It is included here as a *placeholder* pending ME/CFS gastric-biopsy data and should be removed from the ME/CFS causal model if ME/CFS gastric innervation proves normal. The node may also collapse into existing functional-tone variables if structural and functional deficits prove empirically inseparable (see @lim:vagal-enteric-deconditioning). This is a proposed model refinement motivated by Long COVID data, not an estimated model.

*Consequence:* Treating "how many vagal nerve fibers survive" as a separate quantity from "how well the surviving fibers are firing" would tell researchers and trial designers whether vagus-stimulation therapies have a hard ceiling in a given patient — useful for predicting who can and cannot benefit, though it remains an untested modeling proposal.
] <spec:vstr-dag-node>
