#import "../../../shared/environments.typ": *

== Family 17: Structural and Tissue Integrity
<sec:um-structural>

*Family overview.* Beyond molecular dysregulation, chronic disease produces measurable structural changes in tissue architecture — capillary rarefaction, nerve fiber degeneration, muscle fibre remodelling, connective tissue abnormalities — that create self-sustaining biomechanical constraints on function.

*Concrete mechanisms and ME/CFS evidence:*

- *Skeletal muscle mitochondrial structural damage.* Electron microscopy confirms structural mitochondrial damage in ME/CFS skeletal muscle, preferentially subsarcolemmal; simultaneous necrotic and regenerating fibers suggest repeated damage-repair cycling consistent with exercise-triggered reinjury @scheibenbogen2025muscle.

- *Intracellular sodium accumulation in muscle.* Sodium MRI shows elevated intracellular Na⁺ in ME/CFS skeletal muscle, correlating inversely with grip strength; likely reflects Na⁺/K⁺-ATPase dysfunction and ion pump energy failure.

- *Glycolytic fiber shift.* A published 2026 comparison of ME/CFS and Long COVID muscle biopsies against strict 60-day bed rest controls found both patient groups had significantly more glycolytic (Type IIa/IIx + IIx) fibers and fewer Type I fibers than healthy controls; the same bed rest protocol produced no fiber type change, directly excluding deconditioning as the cause @Charlton2026MuscleBedrest. ME/CFS patients had an even lower Type I proportion than Long COVID patients. This represents adaptive remodelling toward anaerobic metabolism consistent with chronic OXPHOS insufficiency. If satellite cell depletion is confirmed, this shift would also be consistent with metabolic reprogramming in a regeneration-impaired niche (@spec:sc-depletion-glycolytic-shift below).

- *Satellite cell depletion.* A 2026 conference abstract reports significantly reduced Pax7⁺ satellite cells in vastus lateralis biopsies of 26 ME/CFS and 25 Long COVID patients vs 30 controls (P$<$0.001); trending reduced PDGFRα⁺ fibroadipogenic progenitor (FAP) cells (P=0.061); and a positive correlation between satellite cell count and OXPHOS capacity (r=0.43, P=0.0035) @Charlton2026SCdepletion. Satellite cell count was reduced both at baseline and 24 hours post-exhaustive exercise. If replicated, reduced regeneration capacity provides a mechanism for the repeated damage-repair cycling noted above: muscle cannot adequately repair micro-damage from each exertion episode, causing cumulative structural deterioration. *Evidence status: Preliminary — single cohort, single biobank (Wüst lab, VU Amsterdam); not independently replicated; conference abstract only.*

- *Capillary rarefaction and basement membrane thickening.* Fewer capillaries and thicker capillary basement membranes in ME/CFS/Long COVID skeletal muscle (independently replicated across 3 countries); CD169⁺ macrophage infiltration after exercise; endothelial microvacuolization, hypertrophy, and degeneration on EM; lower capillary-to-fiber ratios and capillary density in ME/CFS specifically. The 60-day bed rest comparator in Charlton et al. (2026) @Charlton2026MuscleBedrest showed the opposite pattern — bed rest *increased* capillary density (because atrophy outpaced capillary loss) — confirming the patient phenotype is structurally distinct from simple deconditioning; reduced oxygen delivery capacity at the tissue level @Charlton2025muscleMicrovasc @Aschman2023postcovidCapillary @Agergaard2023LongCOVIDmyopathy.

- *Small fiber neuropathy — structural fiber loss.* IENFD reduction on skin punch biopsy confirms structural nerve fiber degeneration beyond functional dysfunction; approximately one-third of ME/CFS patients affected @giannoccaro2021sfn.

- *hEDS/connective tissue hypermobility overlap.* Substantial clinical overlap between ME/CFS, hEDS, POTS, and MCAS; mast cell-derived histamine and tryptase degrade extracellular matrix and collagen, creating a bidirectional relationship between mast cell activation and structural connective tissue weakening. The capillary BM thickening documented above (Family 7) adds a further mechanism: reduced O₂ diffusion through thickened capillary walls impairs fibroblast ATP availability, slowing collagen synthesis and wound healing — an acquired tissue-level impairment layered on top of any genetic connective tissue predisposition @Charlton2025muscleMicrovasc @Wirth2026LaxityConsequences.

- *Type I fibre-selective atrophy in ME/CFS.* Charlton et al. (2026) @Charlton2026MuscleBedrest found that ME/CFS patients showed significant atrophy of Type I (oxidative) fibres compared to healthy controls, while all other fibre types were preserved. This is a disease-specific atrophy pattern: the 60-day bed rest protocol produced generalised atrophy affecting all fibre types uniformly, and Long COVID patients showed no significant fibre-type-specific atrophy. Selective loss of oxidative fibres is mechanistically significant — Type I fibres are the primary locomotors of sustained low-intensity activity and house the highest mitochondrial density. Their selective loss implies a disease process that targets oxidative capacity rather than just muscle mass, consistent with the mitochondrial dysfunction and glycolytic shift documented above.

- *OXPHOS–V̇O₂ₘₐₓ uncoupling in patients.* In healthy controls and after 60-day bed rest, both SDH activity and OXPHOS capacity correlate with whole-body maximal oxygen uptake — more mitochondrial capacity predicts higher aerobic performance. Charlton et al. (2026) @Charlton2026MuscleBedrest found this correlation is absent in both Long COVID and ME/CFS patients (p$>$0.05 in both groups, vs.\ p$<$0.05 in controls and bed rest; a formal interaction test between group and OXPHOS–V̇O₂ₘₐₓ slope has not been reported). Intrinsic mitochondrial function diverged from bed rest: OXPHOS capacity normalised to SDH activity was lower in Long COVID (significant) and numerically lower in ME/CFS (p=0.063), and electron-leak coupling efficiency (E/L ratio) was reduced in both patient groups — neither finding present after bed rest. Whether the absent correlation reflects genuine uncoupling or the limited statistical power of n≈26 per patient group (wide confidence intervals that may include the control-group correlation) cannot be determined from the published data alone; the dissociation is the strongest finding but not definitively established as an interaction.

*Evidence status:* Emerging with strong comparator evidence (muscle and capillary findings replicated in Long COVID/ME/CFS shared cohorts with 60-day bed rest controls; structural SFN documented; hEDS overlap clinically well-established; satellite cell depletion — preliminary, single cohort; glycolytic shift and OXPHOS–V̇O₂ₘₐₓ uncoupling — published, single cohort with direct comparator).

#speculation(title: [Satellite Cell Depletion as a Mechanism of Progressive Muscle Damage in ME/CFS])[
A 2026 conference abstract from the Wüst lab reports significantly reduced Pax7⁺ satellite cells in vastus lateralis biopsies of 26 ME/CFS and 25 Long COVID patients vs 30 healthy controls (P$<$0.001) — the first direct measurement of satellite cells in ME/CFS muscle @Charlton2026SCdepletion. (The same patient cohort is now published in Nature Communications @Charlton2026MuscleBedrest confirming the glycolytic shift, Type I atrophy, and OXPHOS–V̇O₂ₘₐₓ uncoupling; satellite cell quantification specifically remains from the abstract.) Fibroadipogenic progenitor (FAP) cells, which provide essential niche support for satellite cells, showed a trending reduction (PDGFRα⁺, P=0.061). Both reductions were present at baseline and 24 hours post-exhaustive exercise.

If replicated, satellite cell depletion would mean that muscle micro-damage from each exertion episode cannot be adequately repaired. The consequence is a structural ratchet: each PEM episode causes muscle damage that is repaired incompletely or replaced with fibrotic tissue rather than functional myofibres. This is consistent with the simultaneous necrotic and regenerating fibres observed on electron microscopy @scheibenbogen2025muscle — a cycle of damage and incomplete repair for which satellite cell exhaustion is a candidate mechanism. Caution: the Charlton 2026 abstract reports SC depletion at baseline as well as post-exercise; the finding is equally consistent with an exertion-independent depletion mechanism.

The finding is biologically coherent: satellite cell activation and differentiation requires a metabolic switch from glycolysis to OXPHOS @Bhattacharya2024SCmetabolic, and the observed SC-OXPHOS correlation (r=0.43, P=0.0035) is consistent with this pathway — impaired mitochondrial function directly limits the regenerative capacity of muscle stem cells. Chronic inflammation (TNFα, IL-6), oxidative stress, and metabolic dysfunction — all documented in ME/CFS — are established drivers of satellite cell depletion and impaired self-renewal in chronic disease @Dumont2015SCbiology.

The trending FAP cell reduction adds a niche-level dimension: even if some satellite cells survive, the FAP-depleted microenvironment may fail to provide the necessary support signals for myogenic differentiation @Yin2013SCniche.

*Certainty: 0.37* — conference abstract only (no full paper); single biobank, unreplicated; no adjustment for age, sex, menopause, or physical activity (all of which affect satellite cell count); no functional satellite cell assays (ex vivo differentiation); all Wüst-lab publications on this cohort are re-analyses of the same patient biobank, not independent replications.

*Evidence source:* Vastus lateralis biopsy, 26 ME/CFS + 25 Long COVID + 30 healthy controls (mixed cohort, ~50% non-ME/CFS). Inference target: ME/CFS specific. Link is direct — measurement made in target tissue.

*Severity applicability:* Mild to moderate (daily step counts 733–8609 from the full cohort @Charlton2026MuscleBedrest, confirming ambulant population). Severe/bedbound patients who exert minimally may have different satellite cell profiles (disuse atrophy vs disease-specific depletion). Physical activity was not reported stratified by satellite cell count in the abstract — satellite cells are mechanosensitive and decline with prolonged disuse in healthy individuals (losses are reported after several weeks of bed rest or immobilisation, particularly in older adults @Dumont2015SCbiology). The bed-rest comparator in the full paper confirms disease-specific structural changes @Charlton2026MuscleBedrest, but satellite cell-specific bed-rest data from this biobank has not been published.

*Falsifiable prediction:* An independent lab replicating Pax7⁺ satellite cell quantification on vastus lateralis biopsies in a new ME/CFS cohort (n≥20, ICC or IOM criteria, matched for age, physical activity measured by 7-day accelerometry) should find satellite cell counts significantly below controls with effect size comparable to Charlton 2026 after adjusting for activity level.

*Consequence:* If replicated, impaired muscle regeneration provides a direct mechanism for why ME/CFS patients do not recover from exertion normally — their muscle lacks the stem cells needed to repair exercise-induced micro-damage. This would open a new therapeutic axis: interventions that protect or expand the satellite cell pool (e.g., mitochondrial support, anti-inflammatory strategies) could reduce PEM severity and slow progressive decline. The caveat is that satellite cells are in skeletal muscle only — this mechanism cannot explain cognitive dysfunction, orthostatic intolerance, or unrefreshing sleep, which are CNS/autonomic symptoms unrelated to muscle stem cell biology.
] <spec:sc-depletion-structural-ratchet>

#speculation(title: [Glycolytic Fibre Shift as Both Consequence and Cause of Regeneration Failure])[
The shift toward glycolytic (Type II) fibres in ME/CFS muscle biopsies is typically interpreted as adaptive remodelling toward anaerobic metabolism — a downstream consequence of mitochondrial dysfunction. The satellite cell depletion finding suggests a bidirectional relationship: satellite cells require OXPHOS for differentiation @Bhattacharya2024SCmetabolic, so the glycolytic shift may degrade the satellite cell niche, impairing regeneration capacity. Impaired regeneration then drives further loss of oxidative fibres (which are preferentially damaged by exertion and require satellite cell-mediated repair), accelerating the shift. The outcome is a self-reinforcing loop: OXPHOS failure → glycolytic remodelling → impaired satellite cell function → failed repair of oxidative fibres → further glycolytic dominance.

The Charlton 2026 abstract supports the metabolic link directly: reduced antioxidative metabolites and a shift away from oxidative metabolism were documented in the same biopsies that showed satellite cell depletion @Charlton2026SCdepletion.

*Certainty: 0.30* — inferential extension of a single conference-abstract finding. The SC-OXPHOS dependency is well-established in general biology @Bhattacharya2024SCmetabolic, but the bidirectional loop hypothesis is untested.

*Falsifiable prediction:* In cross-sectional biopsy comparisons, the proportion of glycolytic fibres should inversely correlate with satellite cell count after adjusting for physical activity, and this relationship should strengthen with disease duration. Discriminating feature from simple deconditioning: deconditioning preferentially atrophies Type I (oxidative) fibres and drives a slow→fast transition, but does not prevent satellite cell-mediated fibre maintenance. The discriminating test is therefore satellite cell count trajectory, not fibre type proportion alone — SC count decline exceeding what activity-matched controls exhibit would distinguish disease-specific depletion from disuse atrophy.

*Consequence:* If true, interventions that support mitochondrial function (e.g., CoQ10, NAD⁺ precursors) could have a double benefit — improving energy production AND preserving the muscle's ability to repair itself. Conversely, the loop implies that by the time the glycolytic shift is established, mitochondrial support alone may be insufficient without also addressing the satellite cell deficit.
] <spec:sc-depletion-glycolytic-shift>

#open-question(title: [Is Satellite Cell Depletion in ME/CFS Primary or Secondary?])[
The single-cohort finding does not distinguish cause from consequence. Satellite cell depletion could be:
1. *Primary disease mechanism* — a viral or autoimmune attack on the satellite cell niche (consistent with post-infectious onset in both ME/CFS and Long COVID)
2. *Secondary to mitochondrial dysfunction* — SCs require OXPHOS for self-renewal; mitochondrial failure → SC exhaustion (supported by the r=0.43 SC-OXPHOS correlation)
3. *Secondary to chronic inflammation* — TNFα-driven satellite cell senescence is established in chronic disease
4. *Secondary to disuse/deconditioning* — muscle unloading reduces satellite cell content (countered by the published bed-rest comparator showing distinct structural and metabolic changes in the same patient cohort @Charlton2026MuscleBedrest; however, satellite cell-specific bed-rest data has not been reported from this biobank)

These mechanisms are not mutually exclusive. The shared finding across ME/CFS and Long COVID — two conditions with different triggers but shared symptoms and PEM — argues against a single disease-specific mechanism and toward a convergent downstream failure mode. Resolution requires: (a) independent replication in a non-Wüst cohort, (b) functional satellite cell assays (ex vivo differentiation capacity), (c) longitudinal data showing progression with disease duration, and (d) confounder adjustment for age, sex, physical activity, and menopause.

*Consequence:* The practical implication diverges sharply by mechanism — if primary (autoimmune/viral niche attack), immunosuppression or antiviral therapy could restore regeneration; if secondary to mitochondrial failure, metabolic support is the logical target; if secondary to inflammation, anti-inflammatory strategies take priority. The wrong bet wastes precious patient energy on futile trials.
] <oq:sc-depletion-primary-vs-secondary>

#fhypothesis(title: [OXPHOS–V̇O₂ₘₐₓ Uncoupling Reflects Disease-Intrinsic Mitochondrial Dysfunction, Not Deconditioning], falsifiability: "Whole-body oxidative capacity can be raised in ME/CFS patients by an intervention that increases mitochondrial content or respiratory capacity (e.g., pyruvate dehydrogenase activation, NAD⁺ precursor supplementation). If raised V̇O₂ₘₐₓ follows — restoring the OXPHOS–V̇O₂ₘₐₓ correlation — the uncoupling is a modifiable mitochondrial failure. If V̇O₂ₘₐₓ remains dissociated from mitochondrial content despite intervention, the limiting factor lies outside the mitochondrion (central motor output, oxygen delivery, or microvascular obstruction).", justification: "Charlton et al. (2026) Nature Communications: n=105 (4-group design including healthy controls, post-bed-rest, long COVID, and ME/CFS), directly measured OXPHOS capacity via high-resolution respirometry and V̇O₂ₘₐₓ via maximal CPET. Correlation absent in both patient groups (p>0.05) despite preservation in bed rest and healthy controls (p<0.05).")[
In healthy individuals — and even in healthy people after 60 days of strict bed rest — the relationship between mitochondrial oxidative phosphorylation capacity and whole-body maximal oxygen uptake is predictable: more mitochondrial machinery means higher aerobic performance. Charlton et al.\ (2026) showed that this relationship breaks down entirely in both Long COVID and ME/CFS @Charlton2026MuscleBedrest. Patients' V̇O₂ₘₐₓ is uniformly low regardless of how much mitochondrial capacity they retain, and intrinsic mitochondrial function (OXPHOS normalised to SDH activity, electron-leak coupling efficiency) is impaired in patients but not after bed rest. The bed rest comparator is the critical control here: bed rest does reduce OXPHOS capacity and V̇O₂ₘₐₓ, but the two remain coupled — if you lose mitochondrial mass from disuse, your aerobic capacity drops proportionally. Patients lose the coupling itself, which means they have both less capacity and less ability to use what capacity they have.

*Certainty:* 0.65 — published in Nature Communications with carefully matched comparator groups; single cohort from one lab (Wüst/VU Amsterdam); no independent replication yet of the OXPHOS–V̇O₂ₘₐₓ dissociation specifically; the finding is internally coherent across three independent measures (SDH activity, OXPHOS capacity, and intrinsic function all showing patient-specific impairment).

*Evidence source:* Vastus lateralis biopsies analysed by high-resolution respirometry (Oroboros O2k) with substrate–uncoupler–inhibitor titration; maximal CPET on cycle ergometer; 26 ME/CFS + 25 Long COVID + 30 healthy controls + 24 pre-/post-bed-rest; inference is direct.

*Severity applicability:* Mild to moderate only — patients had to complete maximal CPET and undergo biopsy; daily step counts 733–8609. Severe/bedbound patients were excluded. The OXPHOS–V̇O₂ₘₐₓ relationship in severe patients is unknown.

*Falsifiable prediction:* If the dissociation is caused by impaired oxygen delivery rather than mitochondrial failure, interventions that improve microvascular perfusion (e.g., pyridostigmine, volume expansion) should restore the correlation between mitochondrial capacity and V̇O₂ₘₐₓ in patients. If the uncoupling persists after perfusion improvement, the limiting factor is central (brain-mediated motor output restriction) or intrinsic to mitochondrial complex assembly (supercomplex disruption). Absence of correlation restoration after either oxygen-delivery or mitochondrial-directed intervention would point to a central governor mechanism.

*Consequence:* This is the strongest published evidence to date that the exercise limitation in ME/CFS is not explained by physically being less active. A patient who developed ME/CFS two years ago and a healthy person who spent 60 days in bed share similarly low aerobic capacity — but for fundamentally different reasons. For clinicians, this means "reconditioning" cannot be the therapeutic goal because the machinery needed to recondition is itself impaired. Research priority: identify what uncouples mitochondrial machinery from whole-body performance — is it microvascular obstruction preventing O₂ delivery, CNS-mediated motor output restriction, or respiratory supercomplex disruption?
] <fhyp-oxphos-vo2max-uncoupling>

#achievement(title: [Sixty-Day Bed Rest Fails to Reproduce the ME/CFS Muscle Phenotype — Deconditioning Is Not the Explanation])[
Charlton, Slaghekke, Appelman, and colleagues at VU Amsterdam and Amsterdam UMC (2026, Nature Communications) @Charlton2026MuscleBedrest compared skeletal muscle biopsies and maximal exercise responses of Long COVID and ME/CFS patients against one of the most extreme deconditioning models available — 60 days of strict head-down tilt bed rest in healthy volunteers. The design posed a straightforward question: if patient muscle looks abnormal, is that just from being inactive?

The answer is no, at multiple physiological levels that diverge between the bed rest phenotype and patient phenotype: (1) Bed rest causes generalised atrophy of all fibre types; patients show Type I-selective atrophy (ME/CFS) or no significant atrophy at all (Long COVID). (2) Bed rest preserves fibre type proportions after 60 days; both patient groups have a significant shift toward glycolytic Type II fibres, consistent with years of chronic disuse rather than acute unloading being a contributor, or a disease-intrinsic shift; longer-duration disuse models (e.g., chronic spinal cord injury) do produce fibre-type transitions, and 60 days may be insufficient to capture this. (3) Bed rest preserves the normal correlation between mitochondrial OXPHOS capacity and whole-body V̇O₂ₘₐₓ; both patient groups show no significant correlation, though with n≈26 per group, confidence intervals are wide and the possibility of a preserved-but-weaker correlation cannot be excluded (a formal interaction test between group and slope was not reported). (4) Bed rest increases capillary density (because atrophy outpaces capillary loss over 60 days); ME/CFS patients have lower capillary-to-fibre ratios and capillary density — a directionally opposite pattern. (5) Bed rest alters ventilatory patterns (increased V̇E/V̇CO₂ slope, reduced V̇Eₘₐₓ); patients' ventilatory patterns are largely normal, suggesting a different physiological limitation than simple disuse.

*Consequence:* This comparison — using strict bed rest as a control for the most extreme deconditioning dose — provides the strongest evidence to date that the skeletal muscle abnormalities in ambulant ME/CFS (mild–moderate severity) are not solely attributable to being less active. The patient phenotype diverges qualitatively from acute disuse at multiple points, though the distinction between "disease-intrinsic" and "chronic years-long partial disuse in an inflamed system" remains unresolved — 60-day bed rest in healthy volunteers does not model the interaction between disease and prolonged low activity. The finding reinforces existing guidelines (NICE 2021, @NICE2021mecfs; CDC 2017) that recommend pacing and energy management over graded exercise, and provides a mechanistic rationale: even extreme deconditioning in healthy muscle does not produce what the disease produces. For patients, this provides an evidence-based response to the clinical narrative that their symptoms represent "just deconditioning" — even 60 days in bed does not reproduce their muscle phenotype. For the field, the open question is not whether deconditioning explains but what proportion of the pathology is disease-intrinsic, what is secondary to years of reduced activity, and how these interact. *Severity applicability: ambulant mild–moderate only; severe/bedbound patients were excluded and their muscle phenotype, where disuse and disease are fully confounded, remains uncharacterised.*
] <ach:charlton2026-bedrest-rebuttal>

#synthesis(title: [The Deconditioning Null — Convergent Evidence That Disuse Is Not the Driver of ME/CFS Skeletal Muscle Pathology])[
Charlton et al. (2026) @Charlton2026MuscleBedrest demonstrated that 60 days of strict bed rest fails to reproduce the ME/CFS muscle phenotype at five independent dimensions: fibre type shift, atrophy pattern, OXPHOS–V̇O₂ₘₐₓ coupling, capillary density direction, and ventilatory response. This converges with earlier work: invasive CPET shows impaired peripheral O₂ extraction despite normal cardiac output (@Joseph2021iCPETmeCFS), plasma proteomics confirms disrupted proteomic–VO₂max associations in PEM (@Germain2025PlasmaProteomePEM), and the bed rest metabolome is now well-characterised at the multi-omics level, establishing the deconditioning phenotype with which patients can be compared (@Eggelbusch2024BedrestMetab). The convergence of three independent methodologies (muscle biopsy respirometry, invasive CPET, plasma proteomics) and two different comparator designs (bed rest control, healthy controls) establishes that the exercise limitation in ME/CFS has a disease-intrinsic component not explained by physical inactivity.

What remains open: whether the limiting factor is mitochondrial (supercomplex disruption, @spec:sc-depletion-glycolytic-shift), microvascular (capillary oxygen diffusion barrier), or central (CNS-mediated motor output restriction, see @fhyp-oxphos-vo2max-uncoupling). These are not mutually exclusive — all could operate simultaneously — but determining which is rate-limiting changes the therapeutic strategy. A mitochondrial defect calls for metabolic support; a microvascular obstruction calls for endothelial-targeted therapies; a central governor calls for neuromodulation. *Severity applicability: ambulant mild–moderate only; all patients in the Charlton cohort walked 733–8609 steps/day; severe/bedbound patients excluded.*

*Consequence:* The collective evidence from muscle biopsy, invasive CPET, and proteomics — all triangulated against direct bed rest comparators — means that a clinician who tells a mild–moderate ME/CFS patient to "just get moving" is making a claim contradicted by the strongest empirical data available. The patient's muscle is not responding to the same stimulus as a deconditioned healthy person's muscle because the muscle itself is different at the molecular level. For clinicians, the practical takeaway is consistent with existing guidance (@NICE2021mecfs): pacing and energy management that keeps exertion below the individual's ventilatory threshold replaces progressive exercise prescription. The immediate research priority is identifying what breaks the link between mitochondrial machinery and whole-body performance.
] <syn:charlton2026-deconditioning-null>

#hypothesis(title: [A Circulating Serum Factor Reproduces the ME/CFS Muscle Metabolic Phenotype in Healthy Tissue])[
Healthy 3D biofabricated skeletal muscle exposed in vitro to serum from ME/CFS and Long COVID patients undergoes a biphasic metabolic response @Mughal20253dMuscleSera: after 48 hours the tissue shows up-regulated glycolysis, myotube hypertrophy, mitochondrial hyperfusion, and paradoxically elevated oxygen consumption — a hypermetabolic adaptation — but by 96–144 hours this compensatory state collapses into contractile weakness and toroidal mitochondrial fragmentation, leaving the tissue fragile. This is not a purely correlational finding: a serum-borne factor is sufficient to shift otherwise-healthy muscle toward the glycolytic, mitochondria-unstable phenotype documented in patient biopsies (@Appelman2024MusclePEM; @spec:sc-depletion-glycolytic-shift).

The serum-transfer paradigm has prior support. Fluge et al. showed that myoblasts cultured in severe ME/CFS serum increase mitochondrial respiration and secrete excess lactate @Fluge2016PDH. Schreiner et al. found that ME/CFS serum adoptively transfers mitochondrial fragmentation and an antiviral state to naive cells @Schreiner2020HHV6MitoME. Nilsson et al. ruled out anti-mitochondrial antibodies as the mediator @Nilsson2020NoMitoAb, pointing instead to cytokines, microRNA (e.g. HHV-6 aU14), exosomes, or viral fragments. The 3D model is the most disease-representative recapitulation of these effects to date because it reproduces them in structurally intact, contracting muscle rather than a monolayer.

The monolayer-myoblast layer of this paradigm has not survived replication: a pre-registered study exposing healthy myoblasts to ME/CFS versus control serum across more than 1,700 mitochondrial stress tests found no difference in maximal respiratory capacity (see Limitation @lim:ryback-serum-transfer-null) @Ryback2026myoblastNull. This null undercuts the specific Fluge monolayer-myoblast observation cited above, but does not extend to the structurally intact 3D biofabricated muscle or to in-tissue/activity-dependent models, which differ in architecture and are not refuted by the monolayer assay.

*Certainty: 0.26* (discounted). The in-vitro design (biofabricated tissue, population weight 0.40) caps confidence; the underlying serum-transfer phenomenon rests on the 3D biofabricated model and Schreiner's cell-transfer findings (Schreiner 0.41, Appelman 0.68). The Fluge monolayer-myoblast result (previously cited at 0.52) is no longer counted as independent support after its large-scale null replication @Ryback2026myoblastNull.

*Falsifiable prediction:* Depleting or neutralizing the putative serum factor (immunoadsorption, specific cytokine or exosome blockade) should prevent or reverse the metabolic derangement — attenuated glycolysis and preserved mitochondrial integrity — in the 3D muscle model, and measurably reduce post-exertional muscle fatigue if translatable to patients.

*Severity applicability:* Unknown — the study used pooled patient sera and did not stratify by severity.

*Consequence:* Muscle dysfunction in ME/CFS need not be caused by deconditioning, neural outflow, or vascular insufficiency alone — it can be induced in isolated healthy muscle by patient serum. That makes the circulating mediator both a drug target and a candidate diagnostic signal, and reframes "muscle weakness" as a systemic serum-driven process rather than purely a tissue or central problem.
] <hyp:serum-factor-biphasic-muscle>

#speculation(title: [Biofabricated 3D Skeletal Muscle as a Functional Assay for Serum-Borne Muscle Pathogens])[
If the biphasic serum response is reproducible, a biofabricated 3D skeletal-muscle tissue (@Mughal20253dMuscleSera; platform validated in Duchenne muscular dystrophy and drug screening, @FernandezGaribay2022XenoMuscle) becomes a practical functional assay: a measurable, physiologically intact readout of whether an individual's serum impairs muscle metabolism. This would give researchers a medium-throughput ex-vivo endophenotype and could eventually serve as a diagnostic discriminator or a screening platform for candidate circulating mediators and modulators (e.g. immunoadsorption, cytokine blockers) before animal or human trials.

*Certainty: 0.28* (discounted). The platform is mature and validated, but its diagnostic utility and reproducibility across labs and serum biobanks is unproven.

*Falsifiable prediction:* A blinded cohort of ME/CFS, Long COVID, and healthy sera should yield a biphasic muscle response that (a) is significantly more frequent/severe in patient versus control sera, and (b) correlates with a patient-reported PEM or fatigue severity score.

*Severity applicability:* Unknown — candidate assay; validation would need to stratify by severity.

*Consequence:* A serum-responsive muscle tissue could turn an otherwise subjective complaint into an objective, measurable signal, accelerating the search for the circulating cause and giving clinicians a biomarker-like readout that does not depend on a patient's self-report.
] <spec:3d-biofab-muscle-platform>

#speculation(title: [The Circulating Serum Factor Is Likely a Multi-Component Cocktail, Not a Single Molecule])[
The biphasic response involves at least four distinct biological processes — pyruvate-dehydrogenase inhibition, calcium dysregulation, mitochondrial fission, and contractile impairment @Mughal20253dMuscleSera. It is implausible that one molecular species drives all four. A more parsimonious model posits several concurrent mediators: a PDH-inhibitory cytokine (e.g. TNFα/IL-6), a mitochondrial-fission or cell-danger signal (e.g. HHV-6 microRNA, consistent with serum transferring an antiviral metabolic state @Schreiner2020HHV6MitoME), a calcium or ion-channel disruptor, and a sustained inflammatory/exosomal danger signal. Anti-mitochondrial antibodies were excluded as the sole mediator @Nilsson2020NoMitoAb, but immunoglobulin-bound complexes or exosomes remain candidates.

*Certainty: 0.22* — a structurally motivated inference from the number of independent processes the serum provokes; not directly demonstrated.

*Falsifiable prediction:* Fractionation of patient serum into size, heat-labile, nuclease-sensitive, and immunodepleted components should show that no single fraction recapitulates the full biphasic phenotype — whereas the hypothesis is falsified if one isolated fraction (e.g. the exosome pool alone) reproduces the complete picture. (Origin: brainstorm.)

*Severity applicability:* Unknown — in-vitro, not severity-stratified.

*Consequence:* If the cause is a mixture rather than a single culprit, then interventions that remove one ingredient (a single cytokine blocker) may fail while the others keep damaging muscle — which would explain inconsistent single-target trials and argues for removing or blocking the serum-borne insult more broadly.
] <spec:serum-factor-multicomponent>

#speculation(title: [Toroidal Mitochondrial Fragmentation as a Candidate Disease-Specific Ultrastructural Signature])[
The ring-shaped (toroidal) mitochondrial morphology seen at the decompensation phase of the 3D model @Mughal20253dMuscleSera is a specific stress morphology distinct from the spherical/rod shapes of normal fission, commonly linked to Drp1 over-activation and Opa1 loss. If this morphology is reproduced in patient-muscle biopsies — and absent from the deconditioning bed-rest phenotype (which diverges on oxidative fibres and OXPHOS coupling @Charlton2026MuscleBedrest) or from inflammatory myopathy — it could serve as an objective electromicroscopic marker of the ME/CFS muscle pathology that does not depend on self-report. Whether toroidal morphology reflects an in-vitro artifact of the culture system, and whether it is reversible or a marker of irreversible damage, is undetermined.

*Certainty: 0.20* — morphology seen in one in-vitro study; biopsy confirmation and specificity are untested.

*Falsifiable prediction:* Electron microscopy of ME/CFS patient muscle biopsies should show toroidal mitochondria at a higher rate than bed-rest-treated healthy muscle and than age-matched controls; the marker is falsified if toroidal forms are equally common in bed-rest or healthy tissue. (Origin: brainstorm.)

*Severity applicability:* Unknown — biopsy and in-vitro evidence not severity-stratified.

*Consequence:* A microscope-based signature could let a pathologist recognize the disease in a muscle sample — an objective diagnostic-independent-of-self-report — and, if toroidal morphology proves irreversible, would strengthen the case that severe PEM episodes can leave cumulative, non-recoverable mitochondrial damage, reinforcing energy pacing as tissue preservation rather than mere symptom control.
] <spec:toroidal-mitochondrial-signature>

#limitation(title: [The In Vitro Model Does Not Fully Escape the Deconditioning Confound — a Bed-Rest Serum Control Is Needed])[
The 3D muscle model demonstrates that patient serum alone can induce metabolic fragility in otherwise-healthy tissue, which argues against deconditioning as the sole cause @Mughal20253dMuscleSera. However, blood from chronically inactive ME/CFS patients may itself carry deconditioning-associated factors — myokines released by atrophic muscle, altered metabolite profiles, or inflammation arising from inactivity — that damage healthy muscle without being disease-specific. The clean control for disease-specificity would be serum from healthy volunteers after extreme deconditioning (e.g. the 60-day bed-rest protocol that fails to reproduce the ME/CFS muscle phenotype @Charlton2026MuscleBedrest): if bed-rest serum does not reproduce the biphasic fragility, the serum effect is disease-specific and not a deconditioning artifact.

*Certainty:* n/a (epistemic caveat).

*Consequence:* Even this elegant model does not fully separate "disease causes muscle damage" from "inactivity produces circulating factors that damage muscle," so a bed-rest serum control arm is essential before claiming the serum response is disease-specific rather than inactivity-driven. (Origin: brainstorm.)
] <lim:in-vitro-deconditioning-serum-conf>

#open-question(title: [Serum Fractionation Is the Highest-Priority Next Experiment for Identifying the Circulating Mediator])[
The single most decisive next step is to fractionate ME/CFS serum by molecular size, heat-lability, nuclease-sensitivity, and immunoglobulin depletion, then test each fraction on the 3D muscle model with quantitative readouts (lactate efflux, PDK mRNA, mitochondrial morphology, contractile force) @Mughal20253dMuscleSera @Fluge2016PDH @Schreiner2020HHV6MitoME @Nilsson2020NoMitoAb. This would narrow the unknown circulating mediator from "an unidentified something" to a specific molecular class (cytokine, microRNA, exosome, metabolite, or viral fragment), which is the prerequisite for both a blood-based diagnostic and a targeted therapeutic. A parallel blinded comparison of ME/CFS vs Long COVID vs healthy sera on the platform could also test whether the assay discriminates the two conditions, which share symptoms but may differ in mediator composition.

*Certainty:* n/a (research-direction formulation).

*Consequence:* Identifying the molecular class of the serum factor would convert a promising but vague finding into a concrete testable target — the difference between "something in the blood hurts muscle" and "this specific molecule is the culprit," which is what enables a blood test and a targeted treatment. (Origin: brainstorm.)
] <oq:serum-fractionation-mediator>

#synthesis(title: [A Circulating Serum Factor Converges the Skeletal-Muscle Metabolic Findings])[
A convergent body of in-vitro and in-vivo evidence argues that a circulating factor in ME/CFS and Long COVID sera can reproduce the skeletal-muscle metabolic phenotype in otherwise-healthy contracting tissue (@hyp:serum-factor-biphasic-muscle), without deconditioning, neural, or vascular inputs. The most coherent reading is a temporal one: serum-driven pyruvate-dehydrogenase impairment forces compensatory glycolysis (a hypermetabolic phase), then cofactor/antioxidant exhaustion tips into toroidal mitochondrial fragmentation and contractile fragility — the three-phase model (@spec:pdh-three-phase-cascade, @oq:muscle-trap-hyper-vs-hypometabolic). This reconciles earlier apparently contradictory "hypermetabolic" and "hypometabolic" findings as phases of one cycle and maps onto the clinical PEM time-course. The mediator is likely multi-component rather than a single molecule (@spec:serum-factor-multicomponent), and identifying it — via serum fractionation (@oq:serum-fractionation-mediator) and torch-shaped ultrastructure biopsy work (@spec:toroidal-mitochondrial-signature) — is the decisive next step. What the evidence strongly supports is that muscle weakness has a serum-driven, disease-intrinsic component; what remains open is the identity of the mediator and whether the striking in-vitro morphology generalizes to patient tissue.

*Consequence:* Multiple converging lines now point to something in patients' blood itself damaging healthy muscle — so if that mediator is identified, it becomes both a blood-based diagnostic target and a therapy target, and it strengthens the mechanistic case for the "disease-intrinsic, not deconditioning" view of ME/CFS muscle pathology.
] <syn:biofabrication-serum-factor-model>

