#import "../../../shared/environments.typ": *

== The Population Pharmacodiagnostic Corpus — Pooling Drug Responses Across Patients <sec:population-pharmacodiagnostic-corpus>

The frameworks above (@sec:differential-diagnostic-algorithm, @sec:pharmacodiagnostic-matrix-clinical) read the drug responses of *one* patient. This section asks the population question: if many patients each run uncoordinated drug trials, and the reports are captured in a comparable form, does the pooled set become a population-level instrument for ranking which mechanisms are rate-limiting in ME/CFS?

The claim is narrow. A single patient's cocktail is one probe of several nodes. Pooled across hundreds of patients, the *pattern of what works, at what dose, for how long, and in whom* is structured as a distributed constraint-satisfaction problem over the hypothesis space. Whether that structure carries mechanistic signal — or only the community's shared beliefs and prescribing habits — is this section's open question. The corpus, if built, could *rank* candidate rate-limiting pathways and design the confirmatory trial. It cannot *confirm* mechanism. That boundary is the section's spine.

#hypothesis(title: [Pooled Drug Responses as a Population-Level Constraint-Satisfaction Instrument])[
If a set of uncoordinated single-patient drug trials is pooled, the aggregate can estimate population and subgroup treatment effects. Aggregated n-of-1 designs are formalized for pooling and subgroup estimation, the prerequisites for the biomarker and responder-subgroup use proposed here, and multi-level Bayesian models can combine many single-patient trials while handling trend, carryover, and autocorrelation @Punja2016Nof1Aggregation @Schmid2022BayesianNof1 @Hendrickson2020AggregatedNof1 @Zucker2010. Applied to ME/CFS, each drug is a row and each mechanistic hypothesis a column, exactly as in the single-patient matrix (@sec:pharmacodiagnostic-matrix-clinical), but the cells are populated by the response distribution across patients rather than by one person.

(Certainty: 0.45 — the *statistical feasibility of pooling* single-patient trials is well established in general populations; the *ME/CFS application* is untested and no such corpus exists, which is why the application-specific proposals below carry lower certainty, each stated with its own basis. Origin: /integrate-topic pharmacodiagnostic-corpus.)

*Falsifiable prediction:* A corpus pooled from single-patient ME/CFS drug trials recovers at least one drug–response association that is independently confirmed by a blinded randomized trial at a rate above chance, and for the minority of drugs that do have independent trial estimates its population estimates agree with them (rank correlation ρ > 0.5 across those drugs). Falsified if no pooled drug–response association replicates in any blinded trial, or if the corpus ranking's correlation with the trial-based ranking is ρ ≤ 0.5 across the drugs where both exist.

*Consequence:* If the pooled signal is real, a disease with no validated biomarker could get a pathway-ranking instrument built from the drug trials patients are already running.
] <hyp:population-pharmacodiagnostic-corpus>

#speculation(title: [Dose Band and Duration Are the Load-Bearing Fields])[
A corpus of "drug X helped / did not help" pools to nothing, because the paper's central dose-response result is that a null at the top of a dose range is uninformative about a window below it (@sec:dose-response-categories). The corpus therefore only carries mechanism information if each report captures the *dose band* and the *duration* of the trial. A report of "LDN, 0.5 mg, 8 weeks, cognitive fog improved, benefit lost at 3.0 mg" constrains the TLR4/Nrf2 window; "LDN did not help" does not. This is the single design requirement on which the corpus's value depends, and it is also why current forum and clinic reports — mostly yes/no — cannot be pooled retrospectively without loss @Bourke2020PatientGeneratedData @Schmid2022BayesianNof1.

(Certainty: 0.40 — the dose-band principle is established in the paper's own framework; the claim that duration and dose band are *necessary* for pooling is a design inference, not an empirical finding. Origin: brainstorm.)

*Falsifiable prediction:* A corpus that records dose band and duration predicts an independent outcome (blinded response, or an objective marker) better than a yes/no corpus of the same trials; and a drug's band-specific response rate exceeds its off-band rate by ≥2× for at least one drug whose trials span both bands. Falsified if the full-field and yes/no corpora have equal predictive validity, or responder rates are flat across dose bands for all drugs examined.

*Consequence:* A drug-response registry is only worth building if it records dose and duration, not just whether a drug worked.
] <spec:dose-band-duration-load-bearing>

#speculation(title: [Convergent Aggregation Cancels Independent Confounders — It Does Not Eliminate Them])[
Single unblinded reports are confounded by placebo, natural fluctuation, and self-selection. Open-label placebo can move subjective outcomes across conditions without deception, though effect sizes are modest and certainty of evidence is low @FlavioReis2025OpenLabelPlacebo @KleineBorgmann2025OpenLabelPlacebos, and unblinded single-case aggregation inflates favourable response sharply — one systematic review found 95% of participants responding favourably under high risk of bias @Nikles2022Nof1Physiotherapy. The aggregation argument is that these confounders are *independent across patients*: a placebo response in one patient does not predict a placebo response in another. But independence reduces noise; it does not remove systematic bias. Notoriety effects, reporting bias, and self-selection are *shared* across a community and do not cancel @Cutroneo2023Disproportionality @Richiardi2007NINFEAInternet. Crucially, a responder pattern that is *consistent across hundreds of patients* is not self-validating: a socially amplified false signal is also consistent across patients, and this chapter's own analysis of patient communities documents that they can converge on a plausible-but-wrong treatment through social reinforcement and lack the formal error-correction of scientific communities @Loth2026mecfs. Consistency of a responder-subgroup pattern is therefore not sufficient on its own; nor is population-level consistency necessary, since a genuine signal confined to a subgroup need not move the overall population. Separating a real subgroup signal from a socially amplified one requires the expectation floor below and dose/target tracking, not consistency alone.

(Certainty: 0.30 — the cancellation argument is a statistical principle; its sufficiency for ME/CFS drug reports is untested. Origin: brainstorm.)

*Critique: structurally unfalsifiable.* The core statement — that independence reduces noise but does not remove shared bias — accommodates any outcome (a consistent pooled signal is read as cancellation, an inconsistent one as residual shared bias) and cannot by itself be refuted. The claim becomes testable only when operationalized as a variance decomposition (see @spec:variance-decomposition).

*Falsifiable prediction:* The per-drug response variance partitions into an estimable shared component (expectation, recruitment channel, era) and a mechanism-relevant between-patient component, and the mechanism-relevant fraction exceeds zero for at least some drugs; apparent between-drug differences shrink toward zero after adjusting for shared channel and popularity variables. Falsified if the mechanism-relevant fraction is indistinguishable from zero for all drugs — that is, if the corpus's apparent signal is fully explained by shared expectation and channel effects.

*Consequence:* Pooling many patients can turn a scattered signal into a clear one, but it cannot turn an unblinded report into a blinded one — the corpus narrows hypotheses, it does not prove them.
] <spec:convergent-aggregation-cancels-confounders>

#speculation(title: [Drug-Response Heterogeneity Discloses Subtypes])[
Heterogeneous response to a drug is itself informative. In the HARP-2 trial, two ARDS subphenotypes responded *differentially* to simvastatin, so an overall-null trial contained a real, mechanism-revealing differential response @Calfee2018ARDSsubphenotypes. ME/CFS shows substantial, partially reproducible within-diagnosis heterogeneity @Vaes2023SymptomClusters. Read together, these imply that a corpus should not seek a single average response per drug; it should seek responder subgroups — the patients whose response pattern matches a predicted mechanism. The corpus is therefore a subtype-discovery instrument as much as a pathway-ranking one.

(Certainty: 0.42 — differential-response subtyping is demonstrated in ARDS and the ME/CFS heterogeneity is measured; the combination applied to drug-response subtyping in ME/CFS is inference. Origin: brainstorm.)

*Falsifiable prediction:* Responder subgroups derived from the corpus separate on at least one independently measured objective marker (e.g., TRPM3 function, GPCR autoantibodies, autonomic testing, or a cytokine panel) with a between-subgroup effect size larger than within-subgroup variability, in a pre-registered validation cohort. Falsified if corpus-derived subgroups show no objective separation — which would show the corpus recovers response styles, not biology.

*Consequence:* The corpus may reveal that ME/CFS is several drug-response subgroups rather than one disease — which would explain why group-level treatment trials keep returning null.
] <spec:response-heterogeneity-subtypes>

#open-question(title: [The Minimum Data Schema for a Poolable Corpus])[
What must a report contain to be poolable? The evidence supports seven fields, each with a basis: *drug* @Eckey2025PatientReported @Frost2009PatientsLikeMe; *dose* @Bourke2020PatientGeneratedData; *dose band* (the corpus's own thesis); *duration* @KleineBorgmann2025OpenLabelPlacebos @Schmid2022BayesianNof1; *response domain* @Calfee2018ARDSsubphenotypes @Vaes2023SymptomClusters; *side-effect type* @vanPuijenbroek2002Disproportionality @Cutroneo2023Disproportionality; and *stop reason* @Micale2024SocialMediaMeds. Whether this set is sufficient — and what denominator or comparator the corpus needs to interpret a signal — is unresolved. Disproportionality methods rank drug–event associations without denominators @vanPuijenbroek2002Disproportionality, but they cannot establish causation @Cutroneo2023Disproportionality @Noguchi2021SignalDetection. One further variable is mandatory if the corpus is to test its own null: a per-drug measure of community discussion volume or prescribing popularity (e.g., forum mention counts or prescription counts at the recruitment sites), without which the abandonment condition below cannot be evaluated.

*Consequence:* Without a shared schema, the drug experiences patients already accumulate stay unpoolable; with one, they become a research asset.
] <oq:corpus-minimum-data-schema>

#limitation(title: [What the Corpus Cannot Conclude])[
Four limits are structural, not fixable by scale. (1) *It cannot confirm mechanism* — disproportionality and observational inference generate hypotheses, not causal conclusions @Cutroneo2023Disproportionality @Zong2022EHRrepurposing. (2) *It cannot resolve spectrally identical hypotheses* — two mechanisms that predict the same response to every safe, accessible drug are pharmacodiagnostically indistinguishable, as in the single-patient matrix (@sec:pharmacodiagnostic-matrix-clinical). (3) *It cannot overcome unblinded self-report* — open-label placebo and single-case inflation are large @FlavioReis2025OpenLabelPlacebo @Nikles2022Nof1Physiotherapy. (4) *It cannot generalize from respondents to the population* — web cohorts are systematically self-selected @Richiardi2007NINFEAInternet. A fifth limit is ME/CFS-specific: the most severe patients, whose response data would be most informative, are least able to contribute @Loth2026mecfs.

(Certainty: 0.60 — each limit is supported by established methodological literature; the combination is a synthesis.)

*Consequence:* The corpus is a hypothesis-generation and trial-design instrument, not a diagnostic test — treating a pooled association as a confirmed mechanism would repeat the error the paper criticizes elsewhere.
] <lim:corpus-cannot-conclude>

#proposal(title: [From Scattered Prescriptions to a Ranked Differential — A Corpus Specification])[
The corpus is buildable in principle from data patients and clinicians already generate. The proposal is a minimum viable specification, not a claim that a corpus exists:

- *Unit of record:* one drug trial — drug, dose, dose band, duration, response domain, side-effect type, stop reason.
- *Response coding:* domain-specific change (not a global "better/worse"), so that a drug protecting one domain while leaving another untouched registers as the targeted signal it is (@sec:dose-response-categories).
- *Aggregation:* multi-level Bayesian pooling of single-patient trials @Schmid2022BayesianNof1 @Zucker2010, with responder-subgroup analysis rather than a single average @Hendrickson2020AggregatedNof1 @Calfee2018ARDSsubphenotypes.
- *Output:* a ranked list of candidate rate-limiting pathways, with the discriminating probes that would separate them (@sec:pharmacodiagnostic-matrix-clinical).
- *Governance:* the limits above stated as standing caveats, and the schema, aggregation rule, and reading rules published so the corpus can be audited and reproduced.

(Certainty: 0.35 — a design proposal assembled from established methods; feasibility of implementation in ME/CFS is untested. Origin: brainstorm.)

*Falsifiable prediction:* An implementation following this specification yields a per-drug responder ranking whose agreement across independent cohort halves (or independent recruitment channels) exceeds a pre-specified threshold (rank correlation ρ > 0.5), and the top-ranked pathway survives adjustment for indication and treatment popularity (rank correlation > 0.7); both thresholds are provisional and to be pre-registered with the schema. Falsified if split-half ranking agreement is ≈ 0 or if adjustment materially reshuffles the ranking, which would show the output tracks prescribing/recruitment patterns rather than mechanism.

*Consequence:* If implemented, the specification would let the community's existing drug experience feed the same differential-diagnosis logic the paper already applies to one patient — and would tell researchers which pathway to test next.
] <prop:pharmacodiagnostic-corpus-specification>

#speculation(title: [Pooled Nulls May Be More Informative Than Pooled Positives])[
The corpus literature and this paper both assume the valuable signal is responders. But the two response classes carry opposite biases. Positive reports are inflated by open-label placebo @FlavioReis2025OpenLabelPlacebo, community enthusiasm, and publication bias toward positive case series. Null reports are less inflated by expectation than positive reports, and nulls are mostly absent from the published record, so a corpus that actively solicits them captures signal the literature discards. They are not protected from fluctuation or regression to the mean — a patient whose trial coincided with a spontaneous improvement may record a null — so whether their *net* bias is smaller is the asymmetry the test below estimates, not an assumption. If this asymmetry holds, the corpus's marginal value concentrates in the null space: a hypothetical report of "LDN 3.0 mg for 12 weeks, 140 patients, no cognitive change" would constrain the TLR4/Nrf2 window more sharply than "LDN helped" constrains any mechanism. This is a statistical claim about information asymmetry, not an empirical ME/CFS finding.

(Certainty: 0.40 — mechanistically plausible from the known reporting asymmetries; untested in a corpus. Origin: brainstorm.)

*Falsifiable prediction:* In a corpus that solicits positive and null reports with equal effort, cross-cohort agreement (intraclass correlation) is higher for null-response distributions than for positive-response distributions for the same drug set, after adjusting for baseline response-rate differences: ICC(null) > ICC(positive). The comparison must be against the corpus's own inert-intervention floor, not a bare base rate, because agreement-on-noise can mimic the predicted asymmetry. Falsified if ICC(positive) ≥ ICC(null) after that adjustment, or if the two classes replicate equally well. (The un-operationalized form of this claim — that nulls are "more informative" — is unfalsifiable without this or an equivalent metric.)

*Consequence:* If true, patients' failed treatments are the most scientifically valuable data they own — the opposite of the intuition that only success stories matter.
] <spec:pooled-nulls-more-informative>

#speculation(title: [Shared-vs-Idiosyncratic Variance Decomposition Makes "Cancellation" Quantitative])[
@spec:convergent-aggregation-cancels-confounders asserts verbally that independent confounders cancel while shared bias does not. A hierarchical model can make this quantitative: partition each drug's response variance into a shared component (expectation, recruitment channel, era) and an idiosyncratic component (patient-specific). Within the idiosyncratic component, the mechanism-relevant part is the between-patient subgroup structure that tracks dose, target, or a co-variable; the mechanism signal is that structure, not the shared mean and not the unstructured patient-to-patient noise. The ratio of mechanism-relevant variance to shared variance is an estimable per-drug quantity that governs how much each report counts. Drugs with a low mechanism-relevant fraction are uninformative regardless of how many patients report them.

(Certainty: 0.40 — a direct application of multi-level variance-component methods @Schmid2022BayesianNof1; untested on ME/CFS corpus data. Origin: brainstorm.)

*Falsifiable prediction:* Per-drug mechanism-relevant variance fractions (the between-patient subgroup structure, separated from shared expectation and from unstructured noise) estimated from the corpus predict cross-cohort replication of that drug's responder pattern (higher fraction → higher replication, rank correlation ρ > 0.4). Falsified if the mechanism-relevant fraction is unrelated to replication, or if it is near zero for all drugs (no mechanism-relevant patient-to-patient variation to recover, only shared bias and noise).

*Consequence:* The corpus could report, per drug, how much of the apparent effect is real patient-to-patient variation rather than shared expectation — a number that tells readers which reports to trust.
] <spec:variance-decomposition>

#speculation(title: [Mechanistically-Inert Interventions Provide the Corpus's Internal Placebo Floor])[
The corpus will contain many trials of interventions with no plausible target in any candidate ME/CFS biology, including pathways not yet proposed. These are not noise to discard — pooled, they form an internal control arm estimating the community's baseline expectation effect, recall bias, and natural-fluctuation distribution under the corpus's own data-collection conditions. Subtracting this floor converts the corpus from a raw response catalog into an expectation-adjusted one. No external placebo data can substitute, because the magnitude depends on the specific community, instrument, and recruitment channel. The inert list must be fixed and pre-registered before data collection: because the floor's validity depends on the hypothesis space being complete — precisely the unknown the corpus exists to resolve — an active intervention misclassified as inert would inflate the floor and suppress real signal. A second, unflagged assumption is non-exchangeability: expectation is driven by drug identity and community enthusiasm, so a floor measured on inert supplements need not equal the expectation attached to a specific popular drug. The floor therefore corrects only the community-average expectation, not drug-specific inflation; the assumption is falsifiable by comparing floor magnitude across intervention classes. Supplements are a plausible high-volume stratum for this estimate @Eckey2025PatientReported.

(Certainty: 0.40 — open-label placebo magnitude is established @FlavioReis2025OpenLabelPlacebo @KleineBorgmann2025OpenLabelPlacebos; using inert interventions as an internal floor is a design inference. Origin: brainstorm.)

*Falsifiable prediction:* Mechanistically-inert interventions pool to a stable, non-zero response floor whose magnitude is smaller than the pooled response to mechanistically-targeted drugs, and subtracting that floor changes the ranking of candidate pathways (at least one top-5 pathway changes rank). Falsified if inert interventions pool to zero effect (no expectation floor), if they pool to the same magnitude as targeted drugs (the corpus measures expectation, not mechanism), if subtraction leaves the ranking unchanged, or if the inert stratum's response is unstable under pre-registration (reclassification of an "inert" intervention after data collection would show the floor is hypothesis-space-dependent, not a fixed baseline).

*Consequence:* The corpus could measure its own expectation bias instead of borrowing placebo numbers from unrelated trials — a self-calibration that makes its rankings more honest.
] <spec:inert-intervention-floor>

#proposal(title: [Hybrid Design — A Randomized n-of-1 Sub-Study Inside the Observational Corpus])[
The corpus's core weakness is unblinding (@lim:corpus-cannot-conclude). A hybrid design fixes the weakest link without abandoning scale: the observational corpus supplies the wide, cheap, hypothesis-generating signal, while a nested randomized, double-blind, placebo-controlled n-of-1 sub-study on the top three to five drugs nominated by the corpus supplies causal confirmation. The corpus becomes its own prioritization engine — it answers the "what would you randomize?" question that otherwise stalls the proposal @prop:pharmacodiagnostic-corpus-specification, using the pooled n-of-1 designs already established @Punja2016Nof1Aggregation @Zucker2010 @Schmid2022BayesianNof1.

(Certainty: 0.40 — the components are established methods; the hybrid is a design proposal. Origin: brainstorm.)

*Falsifiable prediction:* The top-ranked drug from the observational corpus beats placebo in the nested blinded n-of-1 sub-study at a higher rate than a comparator drug drawn uniformly at random from the same corpus drug set (with the enrichment statistic and null defined by permutation before data collection). Falsified if corpus nomination does not enrich for blinded-confirmed response above the permutation null. (Critique: with only three to five drugs and a small nested blinded sample, this prediction is underpowered as stated; a minimum sub-study size or a sequential design with a pre-registered stopping rule is required for the test to be informative.)

*Consequence:* If built, the corpus would not merely rank pathways — it would decide which treatments deserve rigorous blinded trials, shortening the gap between anecdote and evidence.
] <prop:hybrid-corpus-nested-nof1>

#proposal(title: [A Shared ME/CFS and Long-COVID Corpus Tests Mechanism Overlap Directly])[
The Eckey 2025 survey already spans ME/CFS and long COVID @Eckey2025PatientReported, so a shared corpus is a natural extension that turns a definitional debate — is long COVID a form of ME/CFS? — into a measurable prediction. If the two conditions share mechanisms, their drug-response fingerprints (responder prevalence by drug class and dose band) should correlate more strongly within each condition than between them at equal severity; if they are distinct, the fingerprints should diverge. The large, recently recruited long-COVID cohort raises statistical power.

(Certainty: 0.40 — the joint survey exists; the fingerprint-comparison is a proposal. Origin: brainstorm.)

*Falsifiable prediction:* Drug-response fingerprints (responder prevalence by drug class and dose band) correlate more strongly within ME/CFS vs long-COVID pairs matched on severity than between ME/CFS and long COVID at equal severity (ρ_within > ρ_between). Falsified if the fingerprints are indistinguishable across conditions.

*Consequence:* If the fingerprints overlap, a treatment that works for one condition is a rational candidate for the other, and the two communities could share one evidence base.
] <prop:shared-lc-corpus>

#proposal(title: [The Corpus Can Discover Which Existing Drug Is the Best Diagnostic Probe])[
The spectral-resolution problem is stated above as a limitation: most drugs are predicted positive under several hypotheses. The corpus could partly invert it into a search. Rank existing drugs by the *empirical* narrowness of their responder subgroup — a drug that helps a small, tightly defined subgroup constrains mechanism more than one that helps many. Response concentration (e.g., the entropy of the responder distribution across patients) is computable from the corpus and is data-driven rather than heuristic, so it avoids the labeling-bias concern that limits the clinician-assigned expected-response matrix. This is an escape only if the concentration survives adjustment for the confounders named below: under genuine spectral degeneracy — or if a narrow responder cluster is only a demographic, severity, or co-medication artifact — the method yields zero mechanistic probes, and no amount of data recovers a ranking.

(Certainty: 0.35 — responder-subgroup identification is established @Hendrickson2020AggregatedNof1 @Calfee2018ARDSsubphenotypes; the probe-selection use is a proposal, and its escape from degeneracy is unproven. Origin: brainstorm.)

*Falsifiable prediction:* Drugs with the most concentrated corpus responder distributions discriminate mechanisms in an independent validation cohort better than clinician-selected probes, *after* adjustment for indication, severity, and co-medication. Falsified if the concentration is unrelated to discriminating power, or if it disappears after confounder adjustment (which would show the narrow responder clusters were artifacts, not mechanisms). Agreement with the clinician-assigned matrix is at most a secondary consistency check: because that matrix is itself the labeling-biased object this proposal claims to avoid, matrix agreement cannot validate the method.

*Consequence:* The corpus could tell researchers which already-available drug is the best diagnostic test, without inventing anything new.
] <prop:corpus-discovers-probes>

#limitation(title: [Alternative Explanations That Could Explain the Corpus Entirely])[
The corpus has a testable null: a model using only symptom severity, drug-class popularity and availability, and community discussion volume fits the response matrix as well as a model that additionally uses dose and molecular target — measured by out-of-sample predictive fit, with abandonment if the volume-only model is not worse. Under this null the corpus is a treatment-preference catalog — essentially what the Eckey 2025 survey already is @Eckey2025PatientReported — with no mechanism-ranking content. Three specific alternatives could produce the corpus's apparent signal without any mechanism: (1) *confounding by indication* — patients do not try drugs at random, so a response difference between drug A and drug B may reflect who received them rather than the drugs' targets @Zong2022EHRrepurposing @Shahn2022AntihypertensiveRepurposing; (2) *community amplification* — a corpus recruited from a community inherits its shared beliefs, so apparent efficacy may track online discussion volume rather than pharmacology (@lim:community-error-amplification), and a consistent responder pattern is exactly what a socially amplified false signal also produces; (3) *spectral degeneracy of the drug set* — if every accessible drug helps every subgroup somewhat, many mechanism assignments fit the data equally well and the ranking is arbitrary, a degeneracy that adding patients cannot fix. The corpus is falsifiable against these alternatives only if it (a) records the indication and full co-medication background, (b) shows response tracks dose and target rather than discussion volume, and (c) demonstrates that a small set of mechanism assignments fits the observed matrix. If, after adjusting for severity, availability, and an internal inert-intervention floor, the residual between-drug ranking is explained at least as well by discussion volume as by dose or target — tested by a pre-registered model comparison (ΔAIC or out-of-sample fit) rather than raw partial-correlation magnitudes, since volume and dose are collinear (popular drugs are both discussed more and trialled across more bands) — or if the minimal set of drugs needed to discriminate the hypotheses, estimated from the corpus's own response matrix *after* the same volume adjustment applied to the ranking, is larger than patients will ever trial — then the corpus proposal is falsified outright and should not be built. The clinician-assigned expected-response matrix (@sec:pharmacodiagnostic-matrix-clinical) may only flag a candidate degeneracy for the corpus to test; because it is the labeling-biased object this proposal avoids, it cannot itself trigger abandonment. That is the abandonment condition, not a call for a better-designed corpus.

(Certainty: 0.50 — each alternative is an established threat in observational drug research; the combination as the corpus's null is a synthesis. Origin: brainstorm.)

*Consequence:* A corpus ranking is only informative if it survives these alternatives; presenting a pooled community signal as a mechanism map without ruling them out would be the most misleading possible outcome.
] <lim:corpus-alternative-explanations>

#limitation(title: [Measurement, Denominator, Polypharmacy, and Recall Limits])[
Beyond the structural limits above, four measurement problems bound the corpus's precision. (1) *Measurement validity:* the outcome is an unblinded, non-standardized judgment — the class of measurement open-label placebo moves most @FlavioReis2025OpenLabelPlacebo @KleineBorgmann2025OpenLabelPlacebos — so a common validated instrument is required, or the corpus pools incommensurable judgments. (2) *The denominator problem:* submitted reports have no denominator, so a drug with 50 enthusiastic reports and 5,000 silent failures looks identical to one with 50 reports and 50 trials; response rates are unestimable and only within-corpus relative signals are possible @vanPuijenbroek2002Disproportionality. (3) *Polypharmacy:* responses are measured against an unknown, changing co-medication background (CYP interactions, additive autonomic effects, withdrawal), so the schema must record the full regimen @Schmid2022BayesianNof1. (4) *Recall and survivor bias:* retrospective reports are shaped by outcome knowledge and by who recovered enough to participate, both pushing toward inflated positive signals @Bourke2020PatientGeneratedData @Richiardi2007NINFEAInternet. Prospective capture removes the last two biases but costs more and loses retrospective depth.

(Certainty: 0.55 — each problem is documented; the combination is a synthesis. Origin: brainstorm.)

*Consequence:* These are validity problems, not biases that average out — they must be designed against, not corrected after the fact, or the corpus's numbers will not mean what they appear to.
] <lim:corpus-measurement-limits>

#limitation(title: [Selection Bias Samples the Wrong End of the Severity Gradient])[
Corpus contributors are self-selected: online, English-speaking, mild-to-moderate, and resourced enough to afford many drug trials @Richiardi2007NINFEAInternet. The patients who have tried the most drugs and whose responses would be most informative — severe, long-duration, multi-treatment patients — are least likely to contribute (@oq:severity-epistemic-gradient). This is not random missingness: it correlates with the biology the corpus wants to rank, so the mechanism ranking may describe the mild-to-moderate respondent population and not generalize. It cannot be fixed by adding more of the same respondents; it requires caregiver-mediated and low-tech reporting channels by design.

(Certainty: 0.55 — web-cohort self-selection is documented; the ME/CFS-specific direction is inference. Origin: brainstorm.)

*Consequence:* A corpus finding might not apply to the patients who most need it — the severe and the poor — unless its design deliberately reaches them.
] <lim:corpus-selection-bias>

#synthesis(title: [The Population Corpus as a Hypothesis-Generation Instrument])[
The evidence assembled here converges on one model: a pool of uncoordinated patient drug trials is *structured as* a large, naturally occurring constraint-satisfaction problem over the ME/CFS hypothesis space (@hyp:population-pharmacodiagnostic-corpus, @prop:pharmacodiagnostic-corpus-specification). The statistical feasibility of pooling single-patient trials is established in general populations @Punja2016Nof1Aggregation @Zucker2010 @Schmid2022BayesianNof1; its single-patient form is the framework of (@sec:differential-diagnostic-algorithm, @sec:pharmacodiagnostic-matrix-clinical). Its data substrate already exists in patient registries and surveys (@prop:patient-drug-response-corpus), and its most informative signal may sit in the null reports that the published literature discards (@spec:pooled-nulls-more-informative, @spec:inert-intervention-floor). What the evidence does not support is equally clear: the corpus cannot confirm mechanism, resolve spectrally identical hypotheses, overcome unblinding, or generalize from self-selected respondents (@lim:corpus-cannot-conclude, @lim:corpus-alternative-explanations, @lim:corpus-measurement-limits, @lim:corpus-selection-bias). The central unanswered question is whether pooled response patterns recover biology at all, or only severity and drug popularity — a question that requires an internal expectation floor, severity matching, and validation against an independent, non-response measurement before any ranking can be trusted. The test is not calibration alone: if, after those adjustments, a pre-registered model comparison shows discussion volume explains the residual ranking at least as well as dose or target, the proposal is abandoned, not refined (@lim:corpus-alternative-explanations).

*Consequence:* The corpus argument gives a disease with no validated biomarker a concrete, falsifiable route to ranking which pathways matter — but only as a hypothesis generator whose findings must be confirmed by blinded trials and objective markers, never as a substitute for them.
] <syn:pharmacodiagnostic-corpus-model>

#practical-warning(title: [The Corpus Is a Research Proposal, Not a Treatment-Selector])[
No pharmacodiagnostic corpus exists for ME/CFS. Nothing in this section is a clinical recommendation, and no patient should start, stop, or change a treatment on the basis of a pooled community ranking. The null-space thesis (that failed trials are the more valuable reports) is an untested hypothesis about data collection, not an instruction to report outcomes in any particular way. The corpus's intended use is to nominate hypotheses for blinded trials and to prioritize candidate stratification variables — a research function, not a bedside one.

*Consequence:* A patient-community instrument that is mistaken for clinical guidance would cause harm of the same kind the paper documents for other over-interpreted evidence; the warning is part of the proposal, not an addendum to it.
] <warn:corpus-not-treatment-selector>

*Consequence:* Pooling drug responses across patients extends the paper's single-patient pharmacodiagnostic method to the population scale, offering a route to pathway ranking in a disease with no validated biomarker — provided the corpus is built to rank hypotheses, not to certify them (@warn:corpus-not-treatment-selector), and its selection, measurement, and confounding limits are designed against rather than corrected after the fact.

=== An Existing Dataset That Already Tests the Projection — The Eckey 2025 Survey <sec:eckey-mechanism-reanalysis>

The corpus argument above is a proposal: no poolable ME/CFS drug-response corpus exists. But one dataset already ranks treatments at population scale, and it can test the projection without new recruitment. The Eckey 2025 ME/CFS and long-COVID survey collected treatment-benefit ratings from n=3,925 patients across more than 150 interventions, scored on a seven-point effect scale and summarized as a Net Assessment Score (NAS) against an oral non-liposomal vitamin C reference @Eckey2025PatientReported. It ranks *treatments*, not *mechanisms*. The proposal here is to convert the first into the second: map each surveyed treatment to its known molecular targets, project the benefit ranking onto the hypothesis space, and ask whether the resulting mechanism ranking is internally stable and concordant with independent evidence. The survey's raw stratum-level data are public as Datasets S1–S3. Whether they contain the fields the projection actually needs — per-drug dose band, duration, and a target assignment — is not yet established, and this is a precondition rather than a given: a projection built on an incomplete target map is uninformative regardless of sample size (@spec:dose-band-duration-load-bearing).

The projection method is established outside patient-reported data, and the transfer is an assumption the re-analysis would have to defend. Drug-set enrichment analysis groups drugs by shared molecular target and tests whether a *query signature* — in its validated form a transcriptomic expression profile — is enriched across that drug set, giving mechanism-level aggregation rather than single-drug inference, as demonstrated on the Connectivity Map @Napolitano2016DrugSetEnrichment, with a pathway-resolution variant @Napolitano2019gep2pep. A patient-reported benefit rating is not a query signature; the step from a Likert-scale NAS to a target-level input is itself an untested mapping, and the method's established status does not transfer to it unchanged. The second component — splitting a cohort and asking whether a subgroup-specific ranking reproduces in the held-out half — is the standard machinery of data-driven subgroup identification, together with its central warning that unconstrained subgroup search overfits unless multiplicity is controlled and the result is validated out-of-sample @Lipkovich2017SubgroupIdentification.

#speculation(title: [The Eckey 2025 Benefit Ranking Can Be Projected Onto a Mechanism Ranking That Replicates])[
The environments that follow are not five independent studies; they are five statistics read off one projection, each with its own failure mode. The projection itself is the claim here; the cluster-discordance, cross-condition-gap, null-projection, and vitamin-C-floor environments below specify a different output or correction of that same operation.

If each treatment in the Eckey survey is mapped to its known target and the NAS ranking projected onto the hypothesis space, the resulting mechanism ranking can be tested for internal stability: split the cohort into random halves, derive the ranking in each, and compare them. The Eckey cohort is large enough (n=3,925, four response clusters) to support a held-out replication test in principle, and treatment responses already differ by cluster in the published analysis (for example, IgG benefit concentrates in the multisystemic cluster, ADHD stimulants in the cognitive cluster) @Eckey2025PatientReported. This is the cheapest available execution of the corpus thesis (@hyp:population-pharmacodiagnostic-corpus) — it reuses data that already exist — but "cheapest" refers to data acquisition, not to the work: the target map and the split-half design still have to be built and defended, and a cohort split across two conditions and four clusters leaves small per-cell counts whose power is not yet argued. It treats the treatment-to-target map as the bridge between the treatment ranking and the mechanism ranking @Napolitano2016DrugSetEnrichment, and that bridge is the weakest link.

(Certainty: 0.45 — the dataset and the projection method both exist, and the cohort is adequately sized; the *projection itself* has never been performed, the treatment-to-target map is many-to-many, and no split-half reliability standard exists for this ranking class, so this is a testable proposal, not a result. Origin: /integrate-topic eckey2025-mechanism-reanalysis. Severity applicability: unknown — the published analysis found patient capacity (severity) the strongest response predictor but did not derive a severity-stratified mechanism ranking.)

*Falsifiable prediction:* Projecting the Eckey 2025 treatment ranking onto target mechanisms yields a subgroup-specific mechanism ranking whose agreement between random cohort halves exceeds a pre-registered threshold (rank correlation ρ > 0.5), and whose top pathway remains after adjustment for treatment popularity; falsified if the ranking is unstable across random splits (ρ ≈ 0), if no subgroup-specific ranking survives, or if the ranking is explained entirely by treatment popularity.

*Consequence:* If it replicates, the first population-level mechanism ranking in ME/CFS could be produced from data that already exist, telling researchers which pathway to test next without recruiting a single new patient.
] <spec:eckey-mechanism-ranking-projection>

#open-question(title: [No Reliability Standard Yet Justifies the ρ > 0.5 Replication Threshold])[
The proposal's falsification test turns on a split-half rank correlation threshold (ρ > 0.5), but no published standard establishes what magnitude counts as replication for a patient-reported *treatment-benefit* ranking projected onto mechanisms. The closest machinery is the general subgroup-validation literature, which warns that an unconstrained subgroup ranking will fit noise unless it is validated out-of-sample, but does not supply a ranking-reliability convention for this setting @Lipkovich2017SubgroupIdentification. Two independent measurement questions bear on the threshold. First, the outcome is an unblinded, non-standardized judgment, and in ME/CFS self-reported benefit and objectively measured function are related but not interchangeable @Rekeland2022PROMmecfs, while the choice of instrument itself changes the measured response @Haywood2014PROMsystematic. Second, the baseline against which any replication is judged is the expectation/placebo floor, and expectation alone can move this class of outcome @FlavioReis2025OpenLabelPlacebo @KleineBorgmann2025OpenLabelPlacebos. A partial external check is available: an independent ME/CFS survey ranked intervention strategies by perceived helpfulness with a different instrument and population @Dorczok2026InterventionHelpfulness, so concordance between the two rankings is a further test — but a second ranking is not a reliability standard either. The deeper obstacle is that the NAS is a single global judgment whose invariance across respondents, clusters, and conditions is untested, so no threshold could yet be shown to measure replication rather than noise. The routes that would make the threshold a derived rather than a chosen quantity — permutation-derived cutoffs, an instrument-internal popularity covariate, and an invariance pre-check against the second survey — are specified as components of the validation design at @oq:eckey-validation-design, which treats the absence of a threshold standard as one of the conditions the design must satisfy.

(Certainty: 0.30 — measurement validity is documented and the methodological machinery is established, but the specific threshold has no precedent; this is an unresolved methodological question. Origin: /integrate-topic eckey2025-mechanism-reanalysis. Severity applicability: unknown.)

*Consequence:* Until a reliability benchmark exists, any claim that a projected mechanism ranking has "replicated" rests on a threshold that was chosen, not derived — so the re-analysis should report the full stability distribution rather than a single pass/fail cutoff.
] <oq:eckey-ranking-reliability-threshold>

#limitation(title: [Severity, Popularity, and Many-to-Many Mapping Can Manufacture a Mechanism Ranking])[
Four alternative explanations can produce the apparent result without mechanism. The first and strongest is severity: the survey's own published finding is that patient capacity is the single strongest predictor of treatment response — stronger than diagnosis, sex, duration, or age @Eckey2025PatientReported (see @clin:severity-dominates-response) — so if the projection recovers a ranking that tracks severity rather than target, the apparent mechanism ordering is a severity proxy. The second is popularity: the survey collects self-selected reports, and apparent efficacy may track community discussion volume or prescribing habit rather than pharmacology. Web search volume tracks pharmaceutical utilization @Simmering2014WebSearchUtilization, and social-media discussion can amplify a drug class beyond prescribing data @Stallion2026GLP1SocialMedia — though the same data can carry genuine pharmacological signal @YomTov2013WebSearchSurveillance, so popularity must be modelled as a covariate rather than dismissed. The strongest form of this threat is that the placebo response itself maps to a *structured* molecular network distinct from the drug's target @WangRS2017PlaceboNetwork: expectation can therefore generate a biologically non-random ranking with no target involvement. The third is many-to-many assignment: a single drug maps to several mechanisms (LDN, for example, has been attributed to TRPM3 modulation alongside TLR4/glial effects @Lohn2024TRPM3LDN), so its benefit must be distributed across targets or a primary assignment justified. The same problem appears in the autonomic class, where beta-blockers, ivabradine, midodrine, and volume expansion act on distinct targets for one symptom @Mar2020POTSMechanisms @Hasan2020POTSMedication — a discrimination the ranking is meant to support, and a demonstration that the independent evidence base for the mapping is itself weak. A fourth alternative is target-ontology dependence: the ranking may be an artifact of the chosen target annotation scheme, since a different ontology that groups targets at a different granularity yields a different projection @Napolitano2016DrugSetEnrichment, so an unstably annotated map can manufacture a ranking with no mechanism change. The Eckey authors name self-selection, recall bias, placebo/expectation, and polypharmacy explicitly @Eckey2025PatientReported. The re-analysis is therefore falsifiable only if it subtracts an expectation floor, adjusts for severity, and shows the residual ranking tracks dose and target rather than discussion volume.

(Certainty: 0.50 — popularity and confounding by indication are established threats in observational drug research; the many-to-many mapping is documented in ME/CFS itself. Origin: /integrate-topic eckey2025-mechanism-reanalysis. Severity applicability: unknown.)

*Falsifiable prediction:* A model using only severity plus treatment popularity/availability and community discussion volume fits the Eckey response matrix at least as well as a model that additionally uses dose and molecular target (pre-registered out-of-sample comparison); falsified — that is, the mechanism ranking is supported — if the target-and-dose model wins by a pre-specified margin after the expectation floor is subtracted and popularity is included as a covariate.

*Consequence:* If popularity and ambiguous targets are not ruled out, the "mechanism ranking" is just the community's enthusiasm rank wearing a biochemical label — the most misleading possible output of this analysis.
] <lim:eckey-projection-manufactures-ranking>

#speculation(title: [The Survey's Vitamin C Reference Arm Makes the Projection Self-Calibrating])[
Eckey used oral non-liposomal vitamin C as a low-expectation comparator with FDR-adjusted p-values @Eckey2025PatientReported, so every Net Assessment Score can be expressed as a margin over the survey's own expectation floor before any treatment is mapped to a target. This would make the projection self-calibrating if the reference is a genuine floor: the margin is measured inside the same instrument, population, and recruitment channel as the signal it corrects, rather than borrowed from an external placebo arm @FlavioReis2025OpenLabelPlacebo @KleineBorgmann2025OpenLabelPlacebos. The argument is double-edged, and the floor is conditional, not established. Vitamin C is not obviously inert — it has antioxidant, collagen-synthesis, and immune roles, and is used as an active comparator elsewhere in the supplement literature (cf. @CastroMarrero2021CoQ10) — so the reference only works under a testable condition: if vitamin C behaves statistically like the class of supplements independently judged mechanistically inert, it validates itself as a floor, and if instead it tracks dose or a specific response domain, that use is refuted. The condition is also weaker than it looks. The inert class must be fixed before the comparison, not chosen after seeing which supplements resemble vitamin C; and even a valid floor corrects only community-*average* expectation, not the drug-specific expectation attached to a popular treatment, so it cannot substitute for the popularity covariate demanded below.

(Certainty: 0.42 — the reference arm and FDR-adjusted comparisons exist in the survey, and an internal floor is a sound design inference; but vitamin C's inertness is assumed, not demonstrated, and the projection has not been run. Origin: brainstorm. Severity applicability: unknown.)

*Falsifiable prediction:* The vitamin C NAS distribution is statistically indistinguishable from the pooled distribution of independently judged mechanistically-inert supplements (no significant NAS difference after FDR), and subtracting it changes at least one top-5 projected mechanism; falsified if vitamin C separates from the inert stratum or if its margin is domain-specific.

*Consequence:* If the floor holds, the projection measures one of its central confounders inside its own data rather than assuming it — but the correction is a community-average expectation margin, conditional on vitamin C's inertness, and not a per-drug fix for the popularity threat.
] <spec:eckey-vitamin-c-self-calibration>

#speculation(title: [The Discriminating Signal Is Cluster Discordance, Not Average Benefit])[
Averaging each treatment's NAS across the whole cohort hides a mechanism that is rate-limiting in one response cluster but irrelevant in another. The higher-information statistic is the between-cluster variance of a treatment's NAS conditional on that treatment's overall NAS — how unevenly a benefit is distributed, not how large it is on average. Eckey documents cluster-specific response: IgG benefit concentrates at 73.3% in the multisystemic cluster, while ADHD stimulants reach 62.1% in the cognitive cluster but are non-significant in the multisystemic cluster @Eckey2025PatientReported. The principle is demonstrated in ARDS, where HARP-2 reported an overall-null result that contained a real, mechanism-revealing differential response between subphenotypes @Calfee2018ARDSsubphenotypes, and ME/CFS is known to carry substantial within-diagnosis heterogeneity @Vaes2023SymptomClusters. A related route avoids trusting target labels at all: drug-set enrichment assumes drugs sharing a target form a coherent set @Napolitano2016DrugSetEnrichment, but ME/CFS drug-to-target assignment is many-to-many @Lohn2024TRPM3LDN, so the dose-response *geometry* — the shape of NAS across dose bands — may be an alternative identifier that does not depend on the mapping.

(Certainty: 0.38 — differential response is demonstrated in ARDS and cluster specificity is reported in the survey; weighting the ranking by discordance and the dose-geometry alternative are both untested inference. Origin: brainstorm. Severity applicability: unknown.)

*Falsifiable prediction:* A discordance-weighted mechanism ranking replicates across random cohort halves (ρ > 0.5) while the mean-weighted ranking does not, and it out-replicates the mean-weighted ranking by a pre-specified margin (Δρ > 0); falsified if the discordance-weighted ranking fails to replicate better than the mean-weighted one, or if the two weightings rank mechanisms identically — which would show the between-cluster structure adds no discriminative information beyond the mean.

*Consequence:* If discordance carries the signal, the ranking should be built from how unevenly treatments work, not how much they work — and the report should publish the cluster-variance structure alongside the mean.
] <spec:eckey-cluster-discordance>

#speculation(title: [Null-Projection Ranks Target Engagement Without Benefit])[
The projection as proposed moves only positive NAS values onto targets. But the corpus's strongest speculative result is that null reports may be the more informative stratum @spec:pooled-nulls-more-informative. Inverting the projection gives a negative-constraint list: map the treatments whose target is documented and whose engagement is independently supported by dose or pharmacodynamics, but whose NAS sits at or near the vitamin C floor (@spec:eckey-vitamin-c-self-calibration), and ask which mechanisms are repeatedly *engaged without moving symptoms*. Such a mechanism is a non-rate-limiting pathway — a node the disease does not depend on — which sharpens the ranking as much as a positive result does. The design is circular unless "target engaged" is defined from dose and target, never from benefit: many-to-many assignment @Lohn2024TRPM3LDN and the autonomic class, where beta-blockers, ivabradine, midodrine, and volume expansion are target-distinct drugs for one symptom @Mar2020POTSMechanisms @Hasan2020POTSMedication, both threaten to smuggle benefit back into the engagement definition.

(Certainty: 0.33 — the null-stratum asymmetry is itself speculative and the projection has never been run; the circularity is a real and acknowledged design threat. Origin: brainstorm. Severity applicability: unknown.)

*Falsifiable prediction:* For at least one documented target, treatments mapping to it cluster at or near the vitamin C floor across response clusters while target-engagement markers (dose, side-effect signature) are present; falsified if target engagement and NAS are confounded by construction — that is, if no drug has both an established target and a null NAS — which would make the null-projection uncomputable.

*Consequence:* A negative-constraint list would let the projection rule mechanisms out, not only rank them in — the missing half of a differential instrument.
] <spec:eckey-null-projection>

#speculation(title: [The ME/CFS–Long-COVID Rank Gap Localizes Condition-Specific Mechanisms])[
Eckey's two populations are not identically ranked: the treatment-level NAS values in ME/CFS and long COVID share R²=0.68 of their variance @Eckey2025PatientReported. Read the projection per condition, and the concordance itself becomes the instrument: mechanisms ranked similarly in both are candidate shared mechanisms, while mechanisms whose ranking diverges are candidate condition-specific mechanisms. The R²=0.68 is a descriptive treatment-level quantity, not a null distribution, and using it as a baseline for mechanism-level rank gaps is an assumption, not a derived result: no sampling model converts a treatment-level variance-explained figure into a mechanism-level rank-gap threshold, the quantity is unadjusted for the two conditions' differing severity distributions or recruitment era, and high concordance is equally consistent with shared popularity as with shared mechanism. The proposal is therefore conditional on constructing that baseline properly: it becomes a real test only if the cross-condition comparison is severity-matched and the rank-gap null is derived (for example by permutation) rather than read off the raw R²=0.68. What the R² supplies now is a descriptive anchor, not a significance threshold: it says the two conditions are broadly similar without saying what "excess divergence" is. This connects the heterogeneous-within-diagnosis picture @Vaes2023SymptomClusters to the differential-response logic established in ARDS @Calfee2018ARDSsubphenotypes: the same statistic that reveals subphenotypes inside one disease could, once made into a proper test, separate two diseases that overlap symptomatically.

(Certainty: 0.40 — the R²=0.68 baseline is an observed survey quantity and the shared-vs-specific logic is direct; the per-condition projection and the rank-gap test are untested. Origin: brainstorm. Severity applicability: unknown.)

*Falsifiable prediction:* After severity-matched per-condition projection, at least one mechanism's cross-condition rank gap exceeds a permutation-derived null for rank gaps (not the raw R²=0.68), and its discordance replicates across random cohort halves; falsified if all projected rankings are no more divergent than the derived null predicts, or if the diverging mechanisms fail to replicate.

*Consequence:* If it holds, a single survey could speak to both remaining questions — which mechanisms ME/CFS and long COVID share, and which belong to only one — without a new cohort, but only after the baseline is rebuilt as a real null rather than read off a descriptive correlation.
] <spec:eckey-cross-condition-gap>

#open-question(title: [What Validation Design Would Reject the Null?])[
The projection has never been applied to patient-reported benefit, so its null — that the ranking carries no mechanism beyond treatment popularity and symptom severity — can be rejected only by a pre-specified validation design, not by a single post-hoc correlation. Five components would together make the null rejectable. (a) *Synthetic ground truth:* simulate a known mechanism ranking, run the full projection pipeline on the simulated corpus, and recover the known ranking; a pipeline that fails this carries no evidential weight no matter what it returns on real data. (b) *Negative-control arm:* the Wang 2017 structured placebo network shows that expectation maps to a molecular network distinct from the drug's target @WangRS2017PlaceboNetwork, so the same projection run on placebo-arm data must not recover the drug's target mechanism. (c) *A derived threshold:* replace the ρ > 0.5 convention with a null distribution of split-half correlations generated by permutation of the treatment labels, so the replication cutoff is derived from the data rather than chosen. (d) *A popularity covariate from the instrument itself:* build the discussion/popularity variable from the survey's own item set rather than an external proxy @Simmering2014WebSearchUtilization, so the covariate is measured on the same scale as the outcome. (e) *An instrument-invariance pre-check:* before any concordance claim, test whether the NAS scale is invariant across respondents against an independent ME/CFS intervention ranking @Dorczok2026InterventionHelpfulness, and define the subgroup search and its multiplicity control in advance @Lipkovich2017SubgroupIdentification. Whether all five are jointly feasible on Datasets S1–S3 is itself unresolved.

*Consequence:* Until such a design is pre-registered, the projection can only generate a ranking nobody is entitled to believe or reject — the five components are what turn it from an exercise into a test.
] <oq:eckey-validation-design>

#synthesis(title: [The Eckey Survey as a Feasibility Test of the Corpus Thesis])[
The evidence assembled in this subsection converges on a single methodological model: the Eckey 2025 survey is the corpus thesis's first executable test on data that already exist (@spec:eckey-mechanism-ranking-projection, @hyp:population-pharmacodiagnostic-corpus). Three properties make it worth running before any new corpus is built. It carries its own expectation floor in the vitamin C reference arm, so the projection can be self-calibrating rather than borrowing placebo magnitudes from unrelated trials (@spec:eckey-vitamin-c-self-calibration; cf. @spec:inert-intervention-floor). Its cluster structure and its ME/CFS-versus-long-COVID split supply two internal tests — whether the discriminating signal is between-cluster discordance rather than average benefit (@spec:eckey-cluster-discordance) and whether mechanisms localize to one condition or both (@spec:eckey-cross-condition-gap). And its null and positive reports jointly carry signal, so inverting the projection yields negative constraints on pathways that can be engaged without helping (@spec:eckey-null-projection, @spec:pooled-nulls-more-informative). What the evidence does not supply is a basis for believing the ranking before it is validated: no split-half reliability standard exists for this ranking class (@oq:eckey-ranking-reliability-threshold), and treatment popularity, many-to-many target mapping, and target-ontology dependence can each manufacture an apparent ranking (@lim:eckey-projection-manufactures-ranking, @lim:corpus-alternative-explanations). The central unanswered question is therefore not whether the projection can be run — it can, on public data — but whether a pre-registered validation design can make its output rejectable (@oq:eckey-validation-design).

*Consequence:* The Eckey re-analysis is the cheapest way to learn whether patient-reported drug experience can rank mechanisms at all — a positive result would give the field a pathway-prioritization instrument built from existing data, and a negative one would settle that the clustering in patient reports reflects preference, not biology.
] <syn:eckey-mechanism-reanalysis-model>
