#import "../../../shared/environments.typ": *

// =============================================================================
// SECTION 8: RESEARCH IMPLICATIONS
// =============================================================================

== Research Implications
<sec:causal-hierarchy-research>

The causal hierarchy proposed in this chapter generates specific, testable research priorities. If the hierarchy is correct, certain experimental designs should produce characteristic results; if it is wrong, those experiments will demonstrate that. The hierarchy's value is not in being right—it is almost certainly wrong in some particulars—but in being specific enough to be _wrong in identifiable ways_ that advance understanding.

*Single-parameter restoration experiments.* The most direct test of the hierarchy is to normalize a single mechanism and observe whether ME/CFS resolves. The prediction is clean: normalizing a trigger-capable mechanism should produce complete or near-complete recovery in the subgroup where that mechanism is active, while normalizing an amplifier should produce partial improvement that plateaus short of recovery.

The daratumumab trial provides preliminary evidence for this prediction. Depleting CD38#super[+] plasma cells—which are the source of GPCR autoantibodies—produced marked improvement in 60% of patients. If autoantibodies are trigger-capable in that subgroup, 60% is a plausible response rate (accounting for patients with concurrent load-bearing locks that prevent full recovery). The 40% non-responders may represent patients whose disease entered through a different door (safe mode, CNS energy crisis) or patients in whom epigenetic consolidation has made the disease self-sustaining independent of autoantibodies.

By contrast, NAD#super[+] supplementation trials have consistently shown modest benefit—improvement in some symptoms without approaching recovery. This “helps but doesn't cure” pattern is precisely what the hierarchy predicts for normalizing an amplifier rather than a root cause.

Future experiments should apply this logic systematically. If an intervention normalizing a predicted root cause produces only amplifier-level improvement, the hierarchy is wrong about that mechanism's tier. If an intervention normalizing a predicted amplifier produces root-cause-level recovery, the hierarchy is wrong in the other direction. Both outcomes are informative.

*Multi-omics trajectory mapping.* If the multiple-entry-point, single-final-common-pathway hypothesis (Section @sec:entry-points) is correct, then multi-omics profiling of ME/CFS patients should reveal convergent trajectories: patients with different onset types showing distinct early profiles that converge over time onto shared attractor states. Current cross-sectional omics studies cannot test this—they capture one time point and cannot distinguish convergence from initial heterogeneity. Longitudinal cohorts following patients from early disease are required.

The technical approach would involve repeated metabolomic, proteomic, and transcriptomic sampling at defined intervals (3, 6, 12, 24 months post-onset), with dimensionality reduction (UMAP, t-SNE, or diffusion maps) applied to the combined multi-omics dataset to identify trajectory convergence. The prediction is that trajectories initiated by viral infection, stress, and surgery should occupy different regions of omics space at 3 months but converge by 24 months. The convergence should be more rapid in patients with more severe disease (stronger attractor pull) and slower in patients with milder disease.

*Intervention window studies.* The epigenetic consolidation amplifier (Section @sec:amp-epigenetic) predicts that early intervention should produce dramatically better outcomes than delayed treatment, because early treatment acts before epigenetic locks stabilize the disease attractor. This prediction is testable through prospective trials that compare outcomes in patients treated at different disease durations, ideally with the same intervention protocol applied at different time points post-onset.

Ethical constraints prevent pure delay randomization (deliberately withholding treatment to study the effect of delay). However, natural variation in diagnostic and treatment delay provides a quasi-experimental opportunity: patients diagnosed and treated within 6 months of onset can be compared with patients diagnosed and treated at 1, 2, 3, and 5 years post-onset, controlling for disease severity and other confounders. The prediction is a non-linear relationship: treatment response should be relatively preserved up to the epigenetic consolidation threshold (predicted at 1–2 years), then decline sharply.

The tipping-point analysis in Section @sec:tipping-point provides a formal mathematical framework for predicting the intervention window—the period during which treatment can prevent transition from the reversible to the irreversible disease state.

*Lock hierarchy validation.* The load-bearing versus secondary lock distinction (Section @sec:load-bearing-locks) predicts different response patterns for treatments targeting each type. A systematic comparison of treatment effects—measuring both immediate symptom improvement and long-term disease trajectory—would test whether predicted load-bearing lock treatments (epigenetic modifiers, plasma cell depletion) produce different trajectory changes than predicted secondary lock treatments (antioxidants, antivirals, sleep medications).

*Genetic architecture as hierarchy validator.* The DecodeME GWAS findings provide an independent test of the causal hierarchy. The three genetic themes---neuronal/synaptic, autophagy/mitophagy, and immune-ambiguous (Section @sec:decodeme-genes, Chapter @ch:genetics-epigenetics)---should map onto the three causal tiers proposed here. If neuronal genes predict autonomic dysfunction severity (consistent with CNS energy crisis as root cause), if autophagy genes predict treatment response to mitophagy enhancers (consistent with amplifier status), and if immune genes predict immunotherapy response (consistent with GPCR autoantibody root cause), then the genetic architecture is consistent with the hierarchy, providing convergent evidence from an entirely independent data source. The proposed DecodeME-Stratified Pharmacogenomic Trial Platform (Section @sec:decodeme-pharmacogenomics, Chapter @ch:proposed-studies) would test this directly. The absence of genetic correlation with classical autoimmune diseases is already consistent with the hierarchy's placement of the GPCR autoantibody cascade as a novel immune mechanism distinct from established autoimmunity.

The formal prediction is specific: load-bearing lock removal should alter the _slope_ of the disease trajectory (enabling progressive improvement over time as the system migrates toward the healthy attractor), while secondary lock removal should alter the _level_ (producing a one-time improvement that is maintained but does not continue to accrue). This slope-versus-level distinction is testable with longitudinal outcome data and would provide strong evidence for or against the lock classification.

*Subgroup identification.* The hierarchy predicts that ME/CFS is not one disease but several diseases sharing a final common pathway, with subgroups defined by their entry mechanism and their active lock configuration. Research that treats ME/CFS as a single homogeneous condition will consistently produce disappointing results because it averages across subgroups with different active mechanisms. The hierarchy motivates a research strategy of aggressive subgroup identification—using autoantibody status, TRPM3 function, metabolomic profiling, and epigenetic markers to stratify patients before treatment assignment.

#include "open-questions/oq-experimental-validation-of-causal-hierar.typ"
