#import "../../../../shared/environments.typ": *

#proposal(title: [Sigmoid CCI-Orthostatic Severity Model])[
The correlation between connective tissue disorder severity (CCI scores) and orthostatic intolerance in ME/CFS patients with hypermobility is modest ($r = 0.42$) @Bragee2020, which may conceal a nonlinear threshold relationship. The integrated model predicts that orthostatic symptom severity $S_"ortho"$ follows a sigmoid function of CCI severity:

$
S_"ortho"("CCI") = S_"max" dot.op frac(1, 1 + exp(-k ("CCI" - theta_"50")))
$

where $S_"max"$ is maximum possible orthostatic severity, $k$ is the steepness parameter, and $theta_"50"$ is the CCI value at which orthostatic symptoms are 50% of maximum. Below threshold ($"CCI" < theta_"crit"$), compensatory mechanisms (baroreflex, vasoconstriction) maintain orthostatic tolerance despite connective tissue laxity. Above threshold, these compensations are overwhelmed, producing rapid decompensation. The sigmoid shape explains why the linear correlation is modest: most patients cluster near the inflection point where the relationship is approximately linear, but the underlying biological relationship is fundamentally threshold-based. The model predicts a critical CCI level requiring intervention: patients above this threshold show disproportionate worsening with minimal additional connective tissue deterioration, while patients below maintain reasonable orthostatic function even with similar CCI values. For clinical application, the threshold $theta_"crit"$ can be estimated from the inflection point of observed CCI-orthostatic data, with the confidence interval indicating the range of uncertainty. Treatment implications differ below and above threshold: below threshold, supportive measures (compression, salt/fluid loading) may suffice; above threshold, more aggressive interventions (procedural support, invasive monitoring) are indicated because compensatory reserves are exhausted.

*Certainty: 0.40.* The sigmoid threshold model is biologically plausible given the baroreflex physiology and vascular mechanics in hypermobility. Validation requires fitting the sigmoid model to a larger ME/CFS-hEDS dataset with detailed CCI scoring and standardized orthostatic symptom measurement. If the sigmoid fit significantly improves upon a linear model (higher $R^2$, lower AIC), the threshold hypothesis is supported. The model makes testable predictions: (1) patients near but on opposite sides of $theta_"crit"$ will show similar CCI scores but dramatically different orthostatic symptoms; (2) interventions that improve baroreflex gain (e.g., pyridostigmine) will shift the curve upward but not change $theta_"crit"$; (3) interventions that improve vascular tone (e.g., midodrine) will shift the inflection point rightward (higher $theta_"crit"$), expanding the compensated range. Distinguishing between mechanism-based treatment effects (curve shifts) requires careful dose-response modeling and longitudinal tracking.
]
