#import "../../../../../shared/environments.typ": *

#speculation(title: [ME/CFS-Long COVID Clearance Architecture Parallel: Post-Infectious Disruption of Compartmentalized Brain Clearance])[
*Certainty: 0.30.* Both ME/CFS and Long COVID involve post-infectious onset, sleep architecture disruption, cognitive dysfunction, and (in Long COVID) documented DTI-ALPS abnormalities (Tang 2025: reduced DTI-ALPS in post-COVID sleep disorder, $n=59$; Chaganti 2025: asymmetrical glymphatic dysfunction with BBB disruption correlation) @Tang2025covidSleepDTIALPS @Chaganti2025longCovidGlymphatic. The Chayama et al.\ (2026) compartmentalized clearance framework suggests testable predictions about how the two conditions might differ @Chayama2026BrainClearance.

Long COVID's documented endothelial dysfunction and BBB disruption (McAlpine 2026) would be expected to produce the inflammatory rerouting pattern --- brain antigens shunted into blood through leaky vasculature. ME/CFS, particularly with longer disease duration and the documented structural degradation of the glymphatic apparatus (Section @sec:ch15-glymphatic, ~70× recovery timescale), would be expected to shift toward the obstructive trapping pattern --- proteins retained in parenchyma with reduced border clearance. This predicts that Long COVID should show higher blood:CSF neuronal protein ratios (inflammatory rerouting), while chronic ME/CFS should show higher CSF:blood ratios (obstructive trapping). The Chaganti 2025 finding of asymmetrical glymphatic dysfunction in Long COVID is consistent with the nearest-exit principle: unilateral BBB disruption should produce unilateral clearance impairment, because each hemisphere drains to its ipsilateral border compartments.

If these predictions are confirmed, the therapeutic implications diverge: Long COVID may benefit more from endothelial-stabilising interventions (tight junction stabilisers, anti-inflammatory agents), while chronic ME/CFS may require clearance-enhancing interventions (SWS restoration, position optimisation, glymphatic pressure gradient support) to overcome the obstructive bottleneck. A null cross-condition comparison --- both conditions showing identical blood:CSF ratios --- would suggest that post-infectious clearance disruption is a unitary rather than compartment-specific phenomenon.

*Falsifiable prediction:* Long COVID patients should show higher blood NfL relative to CSF (blood:CSF ratio greater than 1, inflammatory rerouting), while ME/CFS patients with more than 5 years duration should show higher CSF NfL relative to blood (CSF:blood ratio greater than 1, obstructive trapping). Unilateral BBB disruption on DCE-MRI in Long COVID should correlate with ipsilateral DTI-ALPS asymmetry.

*Limitations:* No direct comparison study exists. CSF measurements require lumbar puncture, limiting sample sizes. Comorbid Long COVID + ME/CFS patients confound the prediction. The degree of compartmentalization in humans may differ from the mouse nearest-exit model. Tang and Chaganti are single studies with moderate sample sizes and partially overlapping populations; replication in independent cohorts is pending.
] <spec:ch15-longcovid-clearance-parallel>
