#import "../../../../shared/environments.typ": *

=== Dopaminergic Augmentation (L-DOPA, MAO-B Inhibitors, Dopamine Agonists) <sec:dopaminergic-augmentation>

#speculation(title: [Dopaminergic Augmentation for Apathy-Predominant and Motor-Slowing Phenotypes in Post-Infectious ME/CFS])[
*Certainty: 0.25 (extrapolation from long COVID VMAT2 PET data to ME/CFS; see Observation @cf:vmat2-longcovid).* The agent descriptions that follow are a proposed clinical trial framework, not a treatment recommendation. All agents are experimental in ME/CFS with no clinical trial data; the dosing examples are drawn from Parkinson's disease and depression literature, and starting doses in ME/CFS would need to be substantially lower (1/4 to 1/10 of standard). Liu et al.\ (2026) demonstrated a 16–20% reduction in striatal VMAT2 binding — a validated marker of dopaminergic terminal integrity — in 24 long COVID patients using (+)["11C"]DTBZ PET, with reductions concentrated in ventral striatum (apathy, r=−0.54), dorsal putamen (motor slowing, r=0.51), and dorsal caudate (memory decline, r=0.58) @Liu2026VMAT2longcovid. The magnitude of VMAT2 reduction is comparable to mild-to-moderate Parkinson's disease. Convergent evidence from the same Toronto cohort demonstrates elevated TSPO PET (microglial activation) @Braga2023neuroCOVID and MAO-B PET (astrogliosis) @Braga2025astrogliosis in identical striatal regions, establishing gliosis as a plausible upstream driver of dopaminergic terminal damage. Postmortem evidence confirms that SARS-CoV-2 can directly infect dopaminergic neurons via ACE2 receptors and induce cellular senescence @Yang2024dopaminesenescence.

This evidence base supports a testable hypothesis: dopaminergic augmentation may improve apathy, motor slowing, and cognitive symptoms in a subset of post-infectious ME/CFS patients whose phenotype mirrors the apathy-predominant long COVID subgroup studied by Liu et al. However, this hypothesis carries major caveats. *Zero* VMAT2 PET data exist in ME/CFS — the entire argument rests on cross-condition inference from long COVID. Aregawi et al.\ (2026) found *normal* CSF dopamine pathway indices (DA + DOPAC + HVA) in PI-ME/CFS, with selective deficiency in the noradrenergic pathway @Aregawi2026Noradrenergic. This suggests that nigrostriatal dopamine synthesis capacity may be preserved in PI-ME/CFS even if terminal density is reduced — and that noradrenergic dysfunction is the more robust finding. The VMAT2 reduction in long COVID was not accompanied by changes in peripheral DOPAC or HVA, consistent with preserved synthesis but potentially reduced vesicular storage capacity.

*Possible therapeutic agents (all hypothetical in ME/CFS):*

- *L-DOPA / Carbidopa (Sinemet):* Dopamine precursor. Standard starting dose 25/100 mg TID. Augments tonic and phasic dopamine release from surviving terminals. If terminal loss is the primary pathology, L-DOPA provides substrate for remaining terminals to increase output. *Risk:* nausea, orthostatic hypotension (worsens existing POTS/OI in many ME/CFS patients), dyskinesia with chronic use. Contraindicated in patients with severe orthostatic intolerance unless supine dosing is feasible.
- *MAO-B Inhibitors:* Selegiline (5–10 mg/day oral, or transdermal patch to bypass first-pass metabolism) and rasagiline (1 mg/day) prevent dopamine degradation. May be particularly relevant if astrogliosis-driven MAO-B hyperactivity (Braga 2025) contributes to accelerated dopamine turnover. Meyer (2026, senior author of Liu et al.) has filed a patent for rasagiline + tyramine for long COVID, underscoring translational interest. *Risk:* serotonin syndrome if combined with SSRIs/SNRIs (selegiline loses MAO-B selectivity at higher doses). Hypertensive crisis with tyramine-rich foods. Transdermal selegiline reduces but does not eliminate dietary interactions.
- *Dopamine Agonists:* Pramipexole (D2/D3 agonist), ropinirole. Direct receptor agonism bypasses terminal integrity entirely. Pramipexole at low dose (0.125–0.25 mg at bedtime) has been explored for restless legs and depression with some evidence of benefit in treatment-resistant depression. *Risk:* impulse control disorders (compulsive gambling, shopping, hypersexuality — screen before prescribing), nausea, somnolence, OH. Higher rates of impulse control disorders in Parkinson's populations argue for extreme caution in ME/CFS where risk/reward calculus is less favorable.
- *Low-Dose Aripiprazole (LDA):* Already in use in ME/CFS (Section on Low-Dose Aripiprazole, this chapter). Unlike the above, LDA is a partial D2/D3 agonist with 5-HT1A partial agonism — it *modulates* rather than augments dopamine signaling and has independent anti-inflammatory (microglial) effects. LDA's dual role (dopaminergic stabilization + microglial modulation) is conceptually attractive for the gliosis → DA damage model. However, LDA trials in ME/CFS have not stratified patients by apathy or motor-slowing phenotype, so dopaminergic mechanism-specific efficacy is unknown.

*Consequence:* This hypothesis, if validated by ME/CFS VMAT2 PET and then by targeted trials, would give clinicians a mechanistic rationale for prescribing dopaminergic agents to a specific phenotype (apathy-predominant post-infectious ME/CFS with motor slowing) — moving from empiricism to mechanism-matched treatment. In the absence of ME/CFS data, all agents listed above are experimental for ME/CFS and should not be prescribed outside clinical trials. The appeal of this direction lies in the existing safety record of L-DOPA and MAO-B inhibitors in Parkinson's populations, making off-label clinical exploration feasible once the ME/CFS evidence gap is closed.

*Limitations.* No VMAT2 PET, DAT PET, L-DOPA trial, or MAOI trial in ME/CFS. The Liu 2026 sample (young, apathy-predominant, all had depressive symptoms by inclusion criteria) may not represent the broader ME/CFS population. The normal DOPAC/HVA finding (Aregawi 2026) suggests dopaminergic synthesis remains intact, making terminal loss a partial rather than complete explanation. Dopaminergic agents carry significant side effects (nausea, OH, impulse control disorders, drug interactions) that are disproportionately consequential in ME/CFS patients with medication sensitivity, POTS, and polypharmacy. MAO-B inhibitors and L-DOPA have not been studied in the context of the severe medication hypersensitivity common in ME/CFS; starting doses would need to be substantially below standard.

*Severity applicability:* Unknown. No DA augmentation data in any ME/CFS severity level. Orthostatic hypotension risk from L-DOPA and dopamine agonists is particularly concerning in severe/very severe patients who may be supine and unable to report symptoms promptly.

*Origin: literature inference (Liu 2026).*

*Falsifiable predictions.* (a) VMAT2 PET in apathy-predominant post-infectious ME/CFS (n≥20 per trigger: SARS-CoV-2, EBV, other) should show reduced binding in the SARS-CoV-2 subgroup matching Liu et al.\ (2026) levels, with normal or near-normal binding in non-SARS-CoV-2-triggered ME/CFS. (b) L-DOPA 25/100 mg TID should improve Apathy Evaluation Scale by ≥3 points over placebo in VMAT2-confirmed patients in a crossover RCT (n≥30). (c) Baseline VMAT2 binding should predict DA augmentation response (r > 0.4). Falsified if VMAT2 PET is normal in ME/CFS regardless of trigger; if L-DOPA fails to improve apathy in VMAT2-low patients; or if VMAT2 binding does not predict treatment response.
] <spec:dopaminergic-augmentation-mecfs>

#warning-env(title: [Important Safety Considerations for Dopaminergic Agents in ME/CFS])[
- *Orthostatic intolerance:* L-DOPA, dopamine agonists, and (to a lesser extent) MAO-B inhibitors can worsen orthostatic hypotension — a core symptom in many ME/CFS patients. Screen for POTS/OI before prescribing. In patients with severe OI, dopaminergic augmentation may be contraindicated.
- *Medication hypersensitivity:* ME/CFS patients frequently exhibit exaggerated sensitivity to CNS-active medications. Starting doses should be 1/4 to 1/10 of standard Parkinson's dosing (e.g., L-DOPA 25/100 at 1/4 tablet, selegiline 1.25–2.5 mg) with slow titration over weeks.
- *Serotonin syndrome risk:* MAO-B inhibitors (selegiline > 10 mg, rasagiline) + SSRIs/SNRIs/5-HTP → serotonin syndrome. Selegiline at ≤10 mg is MAO-B selective, but selectivity is lost with dose escalation or drug interactions. Washout period (2 weeks for fluoxetine, 5 half-lives for other SSRIs) before initiating MAOI.
- *Hypertensive crisis:* MAOIs + tyramine-rich foods (aged cheese, cured meats, fermented foods, tap beer) → hypertensive crisis. Dietary counseling is mandatory.
- *Impulse control disorders:* Dopamine agonists (pramipexole, ropinirole) carry black-box risk of impulse control disorders. Parkinson's populations show 14–17% incidence. Risk in ME/CFS is unknown but may be lower due to reduced activity levels limiting opportunity for pathological gambling/shopping.
- *Motor complications:* Chronic L-DOPA use in Parkinson's produces dyskinesia and motor fluctuations. ME/CFS patients would likely be on lower doses and for shorter durations, but long-term risk is unknown.
- *Pregnancy/lactation:* No pregnancy or lactation safety data for any dopaminergic augmentation strategy in ME/CFS. All agents cross the placenta (L-DOPA, dopamine agonists, MAOIs). Do not prescribe in pregnancy.
] <warn:dopaminergic-augmentation-safety>
