#import "../../../shared/environments.typ": *
#include "sec-10-special-considerations-intro.typ"
#include "subsec-01-bedbound-patients/subsec-01-bedbound-patients.typ"
#include "subsec-02-nutritional-failure/subsec-02-nutritional-failure.typ"
#include "subsec-03-patients-considering-medical-assistance-in-dying/subsec-03-patients-considering-medical-assistance-in-dying.typ"
#include "subsec-04-financial-barriers/subsec-04-financial-barriers.typ"
#include "subsec-05-perioperative-management/subsec-05-perioperative-management.typ"
#include "subsec-06-cci-eds-severe/subsec-06-cci-eds-severe.typ"
#include "subsec-07-practical-care-protocols/subsec-07-practical-care-protocols.typ"
#include "subsec-08-hospital-and-environmental-accommodations/subsec-08-hospital-and-environmental-accommodations.typ"
