#import "../../../shared/environments.typ": *

== Connection to Patient Phenotypes
<sec:ch15-phenotypes>

ME/CFS is clinically heterogeneous, and the symptom mechanism framework provides a basis for understanding this variability. This section maps dominant symptom clusters — sleep-predominant, brain fog-predominant, pain-predominant, and PEM-predominant phenotypes — onto the mechanistic pathways described above, generating testable predictions about which mechanisms will be most prominent in each phenotype and which therapeutic targets are most likely to be relevant.

*Sleep-Predominant Phenotype.* Characterized by severe unrefreshing sleep, excessive daytime somnolence, and sleep-dependent symptom fluctuation. Dominant mechanisms: adenosine dysregulation (Section @sec:ch15-adenosine), melatonin/circadian disruption (Section @sec:ch15-melatonin), and glymphatic failure (Section @sec:ch15-glymphatic). The decoupling framework (Section @sec:ch15-cross-modal-decoupling) provides a quantitative approach to measuring the adenosine/glymphatic/circadian integration failure that characterises this phenotype. Sleep quality (not duration) improves with circadian-targeted interventions (low-dose melatonin + evening dim light) and strategies improving slow-wave sleep continuity. Cross-reference to Chapter @ch:core-symptoms sleep phenotype data.

*Brain Fog-Predominant Phenotype.* Characterized by severe cognitive impairment disproportionate to fatigue, attention/executive dysfunction, and mental effort-intolerance. Dominant mechanisms: kynurenine pathway activation driving quinolinic acid excitotoxicity (Section @sec:ch15-kynurenine), mast cell-derived histamine via H3 receptor suppression of acetylcholine (Section @sec:ch15-mast-cells), and impaired glymphatic waste clearance (Section @sec:ch15-glymphatic). Therapeutic targets: interventions supporting glymphatic clearance, mast cell stabilization, and potentially IDO inhibitors (investigational).

*Pain-Predominant Phenotype.* Characterized by widespread, disproportionate pain, allodynia, and hyperalgesia. Dominant mechanisms: central sensitization with NMDA receptor overactivation (Section @sec:ch15-central-sensitization, amplified by kynurenine pathway Section @sec:ch15-kynurenine), oxidative/nitrosative stress driving TRP channel sensitization (Section @sec:ch15-oxidative-stress), and mast cell-mediated neurogenic inflammation (Section @sec:ch15-mast-cells). Therapeutic targets: NMDA antagonists (ketamine, memantine, LDN), alpha-2-delta ligands, and antioxidant support. Pain neuroscience education (PNE) may help patients understand _why_ their pain fluctuates and why certain triggers worsen it, enabling better self-management of activity-pain interactions. However, PNE in ME/CFS must _not_ be positioned as a primary treatment or as evidence that pain is psychogenic; the underlying nociceptive and neuropathic pathology is real. PNE addresses the central amplification layer only and must be paired with biomedical treatment of the peripheral and immune drivers.

*PEM-Predominant Phenotype.* Characterized by severe post-exertional malaise that dominates the clinical picture, with minor baseline symptoms. Dominant mechanisms: metabolic danger signal activation (Section @sec:ch15-metabolic-danger), TLR4/NF-$kappa$B amplification (Section @sec:ch15-cytokine-fatigue), and the inability to suppress exercise-induced lactate inflammation via GPR81 desensitization (speculation in Section @spec:ch15-gpr81-desensitization). Therapeutic targets: strict pacing (below ventilatory threshold), potentially TLR4 antagonists (investigational), and management of post-exertional metabolic stress. Cross-reference to Chapter @ch:disease-course regarding disease severity and PEM progression.

Most patients exhibit a _mixed phenotype_ with elements of multiple dominant mechanisms. Phenotyping can guide stratified treatment: sleep-predominant patients prioritize circadian and sleep-quality interventions; brain fog-predominant patients prioritize glymphatic support and mast cell management; pain-predominant patients require central sensitization-targeted approaches; PEM-predominant patients require pacing-first strategies. This framework is testable: biomarker studies can correlate adenosine, kynurenine, histamine, and metabolic markers with phenotype, and RCTs can test mechanism-matched versus non-matched treatments.

