#import "../../../../shared/environments.typ": *

==== Step M2: Interstitial waste accumulation — mechanical vs. pharmacological clearance

*Mechanism:* If glymphatic flow is reduced, waste products accumulate in the brain interstitium. The rate of accumulation depends on: (a) production rate (how much waste is being generated — higher in neuroinflammation, metabolic dysfunction, and oxidative stress), (b) clearance rate (glymphatic flow), and (c) drainage pathway patency (CSF drainage through cribriform plate to nasal lymphatics and through meningeal lymphatics to deep cervical lymph nodes).

*Probes for waste clearance:*
- *Supine sleep position (head slightly elevated, 10--15°, no neck flexion):* The glymphatic system is gravity-assisted — supine position with neutral neck alignment maximizes CSF-ISF exchange. Neck flexion (chin to chest) compresses the internal jugular veins → impaired venous drainage → increased intracranial pressure → reduced glymphatic flow. If supine position with proper neck alignment improves morning symptoms → mechanical drainage impairment (venous outflow obstruction from poor sleep posture). This is a zero-cost, zero-risk probe — should be trialed before any pharmacological intervention. If a cervical pillow or neck brace during sleep resolves morning headaches → mechanical outflow obstruction was the glymphatic bottleneck.
- *DORAs — CAUTION:* DORAs (daridorexant, suvorexant) block orexin receptors → suppress wakefulness → may increase sleep duration. BUT: orexin is also involved in LC-NE regulation — blocking orexin may reduce LC activity (beneficial for glymphatic flow) OR it may disrupt the normal NE fluctuations that drive vasomotion (harmful). Zhu 2025 @Zhu2025noradrenergicGlymphatic showed that DORAs can impair glymphatic clearance by suppressing NE-mediated vasomotion. The effect on glymphatic flow is unpredictable — DORAs may improve sleep duration while reducing sleep quality (glymphatic clearance per hour of sleep is lower). If a patient on a DORA reports longer sleep but worse morning symptoms → the DORA is impairing glymphatic clearance despite increasing sleep time. Discontinue DORA; try melatonin + supine positioning instead.
- *LDN (continuous vs. episodic improvement):* If LDN produces continuous improvement (morning symptoms improve and stay better throughout the day) → the mechanism is sustained anti-neuroinflammatory, not glymphatic (which would only improve morning symptoms — the waste is cleared during sleep; daytime symptoms are from neuroinflammation from accumulated waste). If LDN produces ONLY morning improvement (patient wakes feeling better but symptoms worsen as the day progresses) → LDN improved glymphatic clearance during sleep, but the underlying waste production rate is unchanged → waste reaccumulates during the day. Continuous improvement = anti-inflammatory; morning-only improvement = glymphatic. The temporal pattern IS the diagnostic probe.
