#import "../../../../../shared/environments.typ": *

#speculation(title: [ICF Syndrome as Proof That Pericentromeric Methylation Loss Causes Immune Pathology])[
ICF syndrome (Immunodeficiency, Centromeric instability, Facial anomalies; OMIM #242860) is caused by autosomal recessive mutations in DNMT3B, the de novo DNA methyltransferase responsible for establishing methylation patterns during embryonic development and maintaining pericentromeric methylation in somatic cells. DNMT3B loss produces constitutive hypomethylation of satellite II and III repeats at pericentromeric regions (chromosomes 1, 9, 16), leading to satellite RNA transcription, centromeric decondensation, and multiradial chromosome formations in lymphocytes. The immunological phenotype includes hypogammaglobulinemia, recurrent infections, and combined B-cell and T-cell deficiency---an immune phenotype produced entirely by methylation loss, without autoimmunity or a primary lymphoid defect @Pappalardo2021repeats.

This is Mendelian proof-of-concept for the general principle that *loss of methylation at pericentromeric loci is sufficient to cause immune pathology.* ME/CFS may represent the acquired, attenuated version of this pathway: partial DNMT3B dysfunction (inhibition by inflammatory signals, oxidative stress, methyl-donor depletion---not mutation) → partial pericentromeric hypomethylation → partial satellite repeat derepression → partial immune dysfunction (MDSC expansion, NK suppression, CD8+ T-cell exhaustion) rather than overt immunodeficiency. The difference between ICF and ME/CFS would be quantitative (degree of DNMT3B impairment, depth of hypomethylation, severity of immune phenotype) rather than qualitative (same pathway, same loci, same downstream effects).

*Certainty:* 0.65 for the ICF mechanism (Mendelian genetics; satellite hypomethylation confirmed by multiple independent labs @Pappalardo2021repeats). 0.35 for the ME/CFS analogy (pericentromeric methylation status untested in ME/CFS; DNMT3B function not directly measured; ME/CFS immune phenotype is exhaustion, not deficiency).

*Testable predictions:* (1) ME/CFS patients should show partial hypomethylation at pericentromeric satellite II/III loci (chromosomes 1, 9, 16) by bisulfite sequencing---less severe than ICF but significantly below healthy controls. (2) DNMT3B enzymatic activity in ME/CFS PBMCs should be partially reduced (≥20% vs controls) without DNMT3B coding mutations. (3) Patients with the most severe immune exhaustion (lowest NK cytotoxicity, highest MDSC frequency) should show the deepest pericentromeric hypomethylation.

*Limitations:* ICF is a severe Mendelian disease; ME/CFS methylation changes are subtler and multifactorial. DNMT3B mutations in ICF cause catastrophic methylation failure during embryogenesis; ME/CFS involves environmentally-induced partial dysfunction in adults. Pericentromeric methylation is technically challenging to measure (repetitive DNA; standard bisulfite arrays have limited coverage of repeat elements). The ICF-ME/CFS parallel is illustrative, not diagnostic, and should not be used to assert that ME/CFS is "ICF of adulthood."
] <spec:icf-methylation-parallel>
