#import "../../../../../shared/environments.typ": *

#speculation(title: [Unpublished SynGO Enrichment Raises a Provisional Postsynaptic-Assembly Hypothesis])[
An unpublished, single-investigator gene-set enrichment analysis of SynGO synapse-ontology terms against ME/CFS GWAS data (DecodeME, and the DecodeME+MVP meta-analysis) — documented on the ME/CFS Science Blog with no deposited code or parameter set — raises the *provisional* hypothesis that the glutamatergic genetic signal, already established at the gene-set level (@hyp:glutamatergic-synaptic-dysfunction), may lean toward synaptic *assembly and scaffolding* rather than neurotransmitter release. The most significant SynGO terms were "synapse adhesion between pre- and post-synapse" (GO:0099560), "regulation of postsynaptic density assembly" (GO:0099151), and "postsynaptic density membrane" (GO:0098839), reported as Bonferroni-significant in the DecodeME run; the DecodeME+MVP run was directionally concordant, though it is not an independent replication because the meta-analysis incorporates DecodeME. The enriched genes include postsynaptic density and trans-synaptic adhesion machinery (_LRRC7_, _NLGN1_, _SHISA6_, _DCC_) alongside genes that do not sort cleanly into that category (_CACNA1E_ is a presynaptic calcium channel; _NRXN1_ is presynaptically anchored; _ARFGEF2_ is vesicle/trafficking-associated) — so the postsynaptic-vs-presynaptic distinction is a hypothesis to be tested, not an established exclusion. The SynGO resource itself documents that synaptic genes are exceptionally conserved and intolerant to loss-of-function mutation, and that SynGO terms are overrepresented among gene sets for neurodevelopmental and psychiatric disorders @Koopmans2019SynGO. This genetic (constitutional) account is complementary to — and not exclusive of — an *acquired* reduction in synaptic contacts via complement-mediated synaptic pruning, proposed separately as a mechanism for cognitive symptoms in ME/CFS (@spec:synaptic-pruning-mecfs): the two could coexist as a genetic substrate plus an acquired insult on the same synaptic-density axis.

(Certainty: 0.30 — this is a third-order inference (preprint meta-GWAS → unpublished sub-term enrichment → a postsynaptic-vs-presynaptic differential, the finest and most bias-prone claim); the direct enrichment result is unpublished, uncited, and vulnerable to gene-length/conservation bias and pleiotropy, so it is rated below the Maccallini preprint anchor (@Maccallini2026metaGWAS) it refines. Translation gap: SynGO is an in silico gene-ontology resource; the ME/CFS enrichment is inferred from GWAS gene-set analysis, not from ME/CFS tissue. Severity applicability: unknown — genetic findings not stratified by severity. Confound caveats: see @lim:syngo-enrichment-unpublished.)

*Falsifiable prediction:* A published, pre-registered MAGMA or comparable gene-set replication on an independent ME/CFS GWAS cohort (non-overlapping with DecodeME/MVP) will reproduce enrichment of the postsynaptic assembly/scaffolding SynGO terms (GO:0099560, GO:0099151, GO:0098839) at family-wise-significant levels, and this postsynaptic-vs-presynaptic specificity must survive correction for gene length/conservation (e.g., length-matched null gene sets or conditional analysis) and exceed a matched brain-trait pleiotropy baseline. The hypothesis is falsified if an independent replication shows no postsynaptic-assembly enrichment, if the signal concentrates in presynaptic vesicle-release terms, or if it attenuates to null once gene-length/conservation bias is removed.

*Consequence:* If this postsynaptic-assembly localization is confirmed by published, reproducible replication, it would narrow where in the brain's wiring ME/CFS genetic risk operates — from "glutamatergic synapses" toward the machinery that builds and scaffolds postsynaptic connections — but it currently rests on an unpublished, unreproducible analysis with indirect support, so no mechanistic or drug-target conclusions should be drawn from it yet.
] <spec:syngo-postsynaptic-assembly>
