#import "../../../../../shared/environments.typ": *

#synthesis(title: [The MCAS Stack as Four Receptor Arms: A Dissection Framework])[
The environments in this subsection assemble into a single organising idea: the four MCAS-stack drugs are not interchangeable symptomatic agents but *probes of four distinct arms* — H1/PAF (rupatadine, which also directly stabilises mast cells), H2/immune (famotidine), CysLT1/CNS (montelukast), and cholinergic (pyridostigmine) — and the *pattern of response and non-response across the four* is more informative than any single drug's effect. Read together, the speculations and open questions describe where current blockade is incomplete and where it may act.

The gaps define the shape of the framework. Four arm-level entities are not targeted by the stack at all: the H3 cognitive receptor (developed by the H3 hypothesis in ch18 sec-09), the H4 immune-cell receptor (@spec:h4-receptor-untargeted-arm), the tryptase/PGD2 mediators that escape H1/H2/CysLT1 blockade (@spec:mast-cell-mediator-escape), and the histamine *clearance* machinery (DAO/HNMT) that is mechanistically distinct from receptor stimulation (@spec:histamine-clearance-vs-receptor) — and the proposed copper–DAO link (@spec:copper-dao-histamine-bridge) is the weakest of these, since the direct human evidence was not found. The cross-arm interactions are the most mechanistically interesting: free histamine displaced from H1 may act on immunosuppressive H2 (@oq:histamine-h1-h2-redistribution), and mast cells may carry an H2/H4 autocrine brake whose blockade could paradoxically increase degranulation (@oq:h2-autocrine-mast-cell-brake) — a possibility the old, contradictory in vitro literature cannot settle. Cholinergic signalling cuts both ways on mast cells (@spec:cholinergic-mast-cell-bidirectional).

This reframes the drugs as diagnostic instruments. A symptom that resolves on pyridostigmine is consistent with cholinergic reversibility (@spec:pyridostigmine-m3-bioassay); the four-arm response profile could define MCAS subtypes (@oq:four-arm-mast-cell-mediator-map); and the *pattern of nulls* is a negative control that constrains mechanism (@oq:non-response-pharmacodiagnostic-fingerprint). The framework also reaches the pain and arousal systems: H1 sensitises TRPV1 (@spec:h1-trpv1-nociceptor-sensitisation, adjacent to @sec:trpv1-cascade), histamine intersects the orexin arousal system (@spec:histamine-orexin-arousal-bridge) and may supply compensatory arousal that H1 blockade unmasks (@spec:histamine-compensatory-arousal), and rupatadine's PAF arm could touch platelet/microclot biology (@spec:paf-platelet-microclot-modulation). Montelukast is the member most likely to engage a central target (a computational model predicts blood-brain barrier penetration) and is therefore the closest available probe of a central leukotriene arm — but its neuropsychiatric effects are a two-edged harm (@spec:montelukast-cns-leukotriene-probe). Timing is a free variable: circadian mediator peaks (@spec:circadian-mast-cell-drug-timing), the pyridostigmine therapeutic window (@spec:cholinergic-reserve-index), H1 tachyphylaxis (@spec:antihistamine-tachyphylaxis-pulsed-dosing), and cycle-linked mast cell sensitivity (@spec:cycle-timed-mast-cell-dosing). Finally, two unsubstantiated harms warn against assuming receptor blockade is costless (@spec:famotidine-gastric-ph-microbiome-histamine, @spec:compensatory-mediator-synthesis-receptor-blockade), and one hypothesis — that mast cell degranulation is a measurable energy drain — has no supporting literature at all (@lim:mast-cell-energy-envelope-drain-untested).

The honest status is that the framework's *arms* are well-described biology (H4, tryptase/PGD2, histamine H1/H2 immunology, TRPV1 sensitisation, cholinergic control of mast cells) while *every ME/CFS application is speculative*. Most supporting evidence is preclinical, general-population, or from adjacent conditions (POTS, Sjögren's, asthma), discounted at or below 0.40; a few points (pyridostigmine in ME/CFS, POTS treatment reviews) reach 0.40 but are not ME/CFS mechanism studies. No ME/CFS cohort has measured H4, DAO activity, anti-M3R, PAF/microclots, or a four-arm response profile. The framework therefore does not support any treatment recommendation or ME/CFS dosing; its value is as a *testable map* — a set of response-pattern predictions that a single well-instrumented trial could begin to discriminate.

*Consequence:* If the four-arm dissection holds, the clinical question shifts from "which antihistamine" to "which arm is dominant in this patient," and research probes (a pyridostigmine response, an H1-vs-H2 differential, a mediator panel) might stratify MCAS-positive ME/CFS. Because none of the arm-specific predictions has been tested in ME/CFS patients, this is a research agenda for stratified pharmacological probing, not a basis for altering current MCAS practice.
] <syn:mcas-stack-arm-dissociation-model>
