,
    [Neuroinflammation as Common Mechanism],
    [H], [0.70],
    [(a) Positron emission tomography (PET) imaging using translocator protein ligand ^11C-PBR28 shows activated microglia in thalamus and anterior cingulate cortex in fibromyalgia patients. (b) This "primed" microglial state is also observed in ME/CFS and Long COVID, where it correlates with fatigue severity and cognitive dysfunction. (c) The microglial priming model provides a mechanistic explanation for why minor stressors can trigger major symptom exacerbations across all three conditions.],
    [Albrecht 2019 PET study of neuroinflammation in fibromyalgia; Albornoz 2024 Long COVID microglial activation; Honore 2026 synthesis of shared mechanisms.],
    [Microglial activation across fibromyalgia, ME/CFS, and Long COVID. TSPO PET imaging evidence. Mechanistic explanation for symptom exacerbations.],
    [Ch.3:neuroinflammation-shared],

    [Central Sensitization as Shared Pain Amplification],
    [H], [0.70],
    [(a) Quantitative sensory testing (QST) demonstrates central sensitization in fibromyalgia. (b) This phenomenon is also present in ME/CFS, independent of fibromyalgia comorbidity, with objectively demonstrable lowered pain thresholds and temporal summation of pain. (c) In Long COVID, studies identify the same dysregulation, correlated with persistent pain and sensory intolerance. (d) The failure of diffuse noxious inhibitory controls (DNIC)—the descending pain modulation system—is a shared feature across all three conditions.],
    [Meeus 2007 QST study of central sensitization in CFS; Siracusa 2021 fibromyalgia review; Fernandez 2023 Long COVID pain review.],
    [Central sensitization across fibromyalgia, ME/CFS, and Long COVID. QST evidence of lowered pain thresholds. DNIC failure.],
    [Ch.3:central-sensitization-shared],

    [Terrain + Trigger Model for Post-Infectious ME/CFS],
    [H], [0.60],
    [(a) ME/CFS follows a "terrain + trigger" model where pre-existing vulnerability factors (genetic predisposition including HLA associations, hypermobility/EDS, pre-existing dysbiosis, chronic stress/trauma, latent MCAS) create a susceptible biological substrate. (b) An acute trigger (viral infection, surgery, physical trauma, or psychological trauma) then precipitates transition from vulnerability to chronic illness. (c) The specific clinical expression—fibromyalgia, ME/CFS, or Long COVID—depends on the combination of pre-existing vulnerabilities and the nature of the trigger.],
    [Honore 2026 synthesis of terrain + trigger model; Wong 2021 systematic review of post-infectious ME/CFS triggers.],
    [Pre-existing vulnerability (genetic, hypermobility, dysbiosis, stress, MCAS) combines with acute trigger to produce chronic illness. Clinical expression depends on vulnerability + trigger combination.],
    [@sec:terrain-trigger-model],
