,
    [Neuroinflammation as Common Mechanism],
    [H], [0.70],
    [(a) Positron emission tomography (PET) imaging using translocator protein ligand ^11C-PBR28 shows activated microglia in thalamus and anterior cingulate cortex in fibromyalgia patients. (b) This "primed" microglial state is also observed in ME/CFS and Long COVID, where it correlates with fatigue severity and cognitive dysfunction. (c) The microglial priming model provides a mechanistic explanation for why minor stressors can trigger major symptom exacerbations across all three conditions.],
    [Albrecht 2019 PET study of neuroinflammation in fibromyalgia; Albornoz 2024 Long COVID microglial activation; Honore 2026 synthesis of shared mechanisms.],
    [Microglial activation across fibromyalgia, ME/CFS, and Long COVID. TSPO PET imaging evidence. Mechanistic explanation for symptom exacerbations.],
    [Ch.3:neuroinflammation-shared],

    [Central Sensitization as Shared Pain Amplification],
    [H], [0.70],
    [(a) Quantitative sensory testing (QST) demonstrates central sensitization in fibromyalgia. (b) This phenomenon is also present in ME/CFS, independent of fibromyalgia comorbidity, with objectively demonstrable lowered pain thresholds and temporal summation of pain. (c) In Long COVID, studies identify the same dysregulation, correlated with persistent pain and sensory intolerance. (d) The failure of diffuse noxious inhibitory controls (DNIC)—the descending pain modulation system—is a shared feature across all three conditions.],
    [Meeus 2007 QST study of central sensitization in CFS; Siracusa 2021 fibromyalgia review; Fernandez 2023 Long COVID pain review.],
    [Central sensitization across fibromyalgia, ME/CFS, and Long COVID. QST evidence of lowered pain thresholds. DNIC failure.],
    [Ch.3:central-sensitization-shared],

    [Terrain + Trigger Model for Post-Infectious ME/CFS],
    [H], [0.60],
    [(a) ME/CFS follows a "terrain + trigger" model where pre-existing vulnerability factors (genetic predisposition including HLA associations, hypermobility/EDS, pre-existing dysbiosis, chronic stress/trauma, latent MCAS) create a susceptible biological substrate. (b) An acute trigger (viral infection, surgery, physical trauma, or psychological trauma) then precipitates transition from vulnerability to chronic illness. (c) The specific clinical expression—fibromyalgia, ME/CFS, or Long COVID—depends on the combination of pre-existing vulnerabilities and the nature of the trigger.],
    [Honore 2026 synthesis of terrain + trigger model; Wong 2021 systematic review of post-infectious ME/CFS triggers.],
    [Pre-existing vulnerability (genetic, hypermobility, dysbiosis, stress, MCAS) combines with acute trigger to produce chronic illness. Clinical expression depends on vulnerability + trigger combination.],
    [@sec:terrain-trigger-model],

    [HIF-1alpha-Mediated Connective Tissue Remodeling],
    [H], [0.55],
    [(a) Chronic HIF-1alpha elevation in ME/CFS may drive pathological connective tissue remodeling through ROS-mediated inhibition of prolyl hydroxylases, impairing collagen crosslinking. (b) HIF-1alpha directly alters extracellular matrix composition in tendinopathy, causing collagen matrix disorganization and altered biomechanical properties. (c) HIF-1alpha-driven VEGF expression upregulates MMP-3, reducing tendon biomechanical stability. (d) In skeletal muscle capillaries, elevated HIF-1alpha may promote basement membrane thickening and extracellular matrix overproduction, impairing capillary perfusion and diffusion.],
    [Wirth 2026 CTD-MECFS study; Moschini 2026 HIF-tendinopathy study; Sahin 2012 HIF-tendon study.],
    [ROS-HIF-1alpha connection impairs collagen crosslinking; direct ECM alteration independent of angiogenesis; MMP-3-mediated degradation; basement membrane thickening in capillaries.],
    [Ch.14a:hif1alpha-connective-tissue],
    [Chronobiological Prolyl Hydroxylase Optimization],
    [H], [0.40],
    [(a) Prolyl hydroxylases (P4H, P3H) exhibit circadian rhythms essential for collagen crosslinking. (b) ROS-mediated inhibition of these enzymes in ME/CFS impairs ligament stability, particularly in hypermobile patients. (c) Timed cofactor supplementation (ascorbic acid, alpha-ketoglutarate) at circadian peak times may maximize enzymatic activity and improve collagen crosslinking efficiency. (d) This addresses the connective tissue weakness observed in ME/CFS hypermobility through timed nutritional intervention.],
    [Wirth 2026 CTD-MECFS study on ROS-prolyl hydroxylase-HIF-1alpha connection; circadian regulation of prolyl hydroxylases in collagen synthesis literature; ascorbic acid deficiency causing scurvy via collagen crosslinking failure.],
    [Circadian optimization of prolyl hydroxylase activity to improve collagen crosslinking in hypermobile ME/CFS patients. Nutritional timing strategy to overcome ROS inhibition.],
    [Ch.14a:prolyl-hydroxylase-circadian],

    [VEGF-HIF-1α Disconnection Therapy],
    [H], [0.45],
    [(a) Moschini 2026 demonstrated that HIF-1alpha drives connective tissue pathology independently of VEGF. (b) HIF-1alpha directly promotes basement membrane thickening in capillaries and upregulates MMP-3 for collagen degradation. (c) Dimethyl fumarate (DMF) inhibits HIF-1alpha via NRF2 activation and crosses the blood-brain barrier. (d) This approach targets connective tissue pathology without affecting vascular function.],
    [Moschini 2026 HIF-tendinopathy study showing HIF-1alpha drives ECM pathology independent of VEGF; DMF inhibits HIF-1alpha in experimental models; DMF crosses BBB addressing central manifestations.],
    [HIF-1alpha inhibition as targeted therapy for connective tissue pathology using existing safe medication (DMF). Addresses both peripheral and central manifestations.],
    [Ch.14a:vegf-hif-disconnection],

    [Periostin-Targeted ECM Restoration],
    [H], [0.35],
    [(a) Periostin (POSTN) is a matricellular protein critical for collagen crosslinking and tissue remodeling. (b) ME/CFS may involve periostin deficiency or dysregulation, impairing connective tissue repair. (c) Recombinant periostin or TGF-beta modulators could restore ECM integrity in hypermobile patients. (d) This addresses the molecular basis of connective tissue weakness in ME/CFS.],
    [Periostin mutations cause connective tissue disorders; periostin-deficient mice show ligament laxity and impaired wound healing; TGF-beta dysregulation documented in ME/CFS.],
    [Targeted biological approach to connective tissue pathology using recombinant periostin or TGF-beta modulators to restore collagen crosslinking.],
    [<hyp:periostin-ecm-restoration>],

    [Mast Cell-Targeted MMP Inhibition Protocol],
    [H], [0.50],
    [(a) Mast cells activate collagen-degrading MMPs via tryptase and chymase in ME/CFS. (b) Simultaneous mast cell stabilization (cromolyn, ketotifen) and selective MMP inhibition (doxycycline at subantimicrobial doses) can break the degradation cycle. (c) This combination therapy addresses both cellular source and enzymatic effect. (d) Low-dose doxycycline (20mg BID) inhibits MMP-9 without significant antimicrobial effects for long-term use.],
    [Mast cell-MMP pathway supported by cross-disease evidence from tendinopathy and connective tissue disorders; doxycycline MMP inhibition established in rosacea and periodontal disease; mast cell activation prevalent in ME/CFS.],
    [Combination therapy targeting mast cell activation and MMP-mediated collagen degradation to improve joint stability and reduce POTS severity in mast cell-activated ME/CFS subset.],
    [Ch.07:mast-cell-mmp-inhibition],

    [Bidirectional Connective Tissue-ME/CFS Relationship],
    [H], [0.45],
    [(a) Connective tissue disorders (CTDs), particularly hypermobile Ehlers-Danlos syndrome (hEDS) and hypermobility spectrum disorders (HSD), show a bidirectional relationship with ME/CFS. (b) CTD → ME/CFS predisposition: Pre-existing connective tissue disorders may predispose to ME/CFS through: ligament laxity and craniocervical instability → mechanical strain on nervous system; autonomic dysfunction → orthostatic intolerance and fatigue; mast cell hyperactivity → inflammatory milieu; hypermobility prevalence: 30-57% in ME/CFS vs 10-15% general population. (c) ME/CFS → CTD exacerbation: ME/CFS pathophysiology may worsen connective tissue through: ROS-mediated inhibition of prolyl hydroxylases → impaired collagen crosslinking; chronic HIF-1alpha elevation → altered extracellular matrix composition; mast cell activation → MMP-mediated collagen degradation; basement membrane thickening in capillaries → impaired perfusion.],
    [Ganesh 2024 Long COVID-HSD study; Logarbo 2024 Long COVID EDS case report; Ramirez-Paesano 2023 CCI review; Berg 2026 HSD survey; Wilson 2026 hEDS wearable study; Wirth 2026 CTD-MECFS preprint.],
    [Bidirectional relationship: CTD may predispose to ME/CFS; ME/CFS may exacerbate underlying CTD pathology. Hypermobility 30-57% prevalence in ME/CFS vs 10-15% general population. Clinical screening and management implications.],
    [Ch.13:hyp:ct-mecfs-bidirectional],

    [Cold Exposure-Induced Parasympathetic Activation in ME/CFS],
    [S], [0.30],
    [(a) Cold exposure therapies (WBC, cold water immersion) produce consistent parasympathetic activation in healthy populations via increased HRV and decreased LF/HF ratio @Costa2022HRVCryotherapy. However, ME/CFS patients with autonomic dysfunction may experience adverse effects from sudden parasympathetic shifts (syncope, arrhythmias) due to pre-existing autonomic instability @Tipton2017ColdWaterSafety. Thermoregulatory dysfunction may further impair adaptive responses to cold stress @Li2021ThermoregulationCFS @Cambras2018CircadianCFS. The net effect of cold exposure in ME/CFS may be parasympathetic overload rather than beneficial activation, potentially triggering PEM through thermoregulatory pathway activation @Baraniuk2022ThermoregulationMECFS. (b) WBC benefits in healthy populations (HRV ↑, SWS ↑, pain ↓) may not translate to ME/CFS due to pathophysiological differences. (c) Sudden parasympathetic shift in ME/CFS with dysautonomia could cause vagal overactivation → syncope, arrhythmias, or autonomic instability episodes. (d) The only direct CFS WBC study (Kujawski 2023) showed high attrition (10/22, 45% dropout), suggesting poor tolerability or adverse responses. (e) Thermoregulatory impairment in ME/CFS (abnormal temperature responses, impaired adaptation during fatigue progression, disrupted heat dissipation) may prevent proper adaptive response to cold stress.],
    [Cold exposure produces parasympathetic activation in healthy populations (HRV ↑, LF/HF ↓, HR ↓). ME/CFS autonomic dysfunction may cause adverse effects from sudden parasympathetic shift. Thermoregulatory impairment limits adaptive cold response. Kujawski 2023 CFS study: high attrition (45%), poor tolerability. Baraniuk 2022: cold stress triggers PEM via thermoregulatory pathway.],
    [HRV and sleep benefits in healthy populations; Tipton 2017 contraindications for dysautonomia; Kujawski 2023 CFS high attrition; Li 2021, Cambras 2018, Baraniuk 2022 thermoregulatory dysfunction in ME/CFS; not yet replicated, no ME/CFS data, contraindicated by safety guidelines.],
    [@Douzi2018SleepCryotherapy, @Costa2022HRVCryotherapy, @Tipton2017ColdWaterSafety, @Kujawski2023CBSCFS, @Li2021ThermoregulationCFS, @Cambras2018CircadianCFS, @Baraniuk2022ThermoregulationMECFS],
    [Mechanistic inference, no ME/CFS data, contraindicated by safety guidelines. Not yet replicated.],
    [cryotherapy-sleep],

    [ME/CFS-Specific Cold Exposure Protocols: Balancing Sleep Benefits with Thermoregulatory Safety?],
    [OQ], [n/a],
    [(a) Cold exposure therapies show sleep and autonomic benefits in healthy populations (WBC: ↑SWS, ↓movements, ↑parasympathetic activity @Douzi2018SleepCryotherapy @Westerlund2006SleepCold; cold water immersion: ↑SWS duration @Westerlund2006SleepCold). However, ME/CFS patients have thermoregulatory dysfunction and autonomic instability that contraindicate standard protocols @Li2021ThermoregulationCFS @Cambras2018CircadianCFS @Tipton2017ColdWaterSafety. The only direct CFS WBC study showed high attrition and mixed results @Kujawski2023CBSCFS. Research question: What cold exposure parameters (temperature, duration, timing, body region) could provide sleep benefits without triggering adverse effects in ME/CFS? Potential protocols to investigate: (b) Gradual temperature titration (starting at 20°C, decreasing slowly). (c) Localized cold (face immersion, extremity-only) vs. whole-body. (d) Timing adjustments (morning vs. evening) based on circadian thermoregulatory patterns. (e) Pre-conditioning protocols (gradual acclimatization over weeks). (f) Patient stratification by autonomic dysfunction severity.],
    [Sleep and autonomic benefits in healthy populations; ME/CFS thermoregulatory dysfunction contraindicates standard protocols; only CFS WBC study (Kujawski 2023) showed high attrition and mixed results; no controlled trials in ME/CFS; no safety data, no protocol optimization studies.],
    [@Douzi2018SleepCryotherapy, @Westerlund2006SleepCold, @Li2021ThermoregulationCFS, @Cambras2018CircadianCFS, @Tipton2017ColdWaterSafety, @Kujawski2023CBSCFS],
    [Research gap: No controlled trials in ME/CFS; no safety data; no protocol optimization studies.],
    [cryotherapy-sleep],

= Entries added 2026-05-09: Corticosteroid Failure and Steroid-Avoidant Strategies

#table(
  columns: (auto, auto, auto, auto, auto, auto, auto, auto, auto, auto),
  stroke: (x, y) => (left: 0.5pt, right: 0.5pt, top: 0.5pt, bottom: 0.5pt),
  align: (left, center, center, left, left, left, left, left, left, left),

  // Header row
  [*Hypothesis/Speculation*, *Type*, *Certainty*, *Evidence*, *Source Citations*, *Mechanism*, *Chapter Reference*, *Testable Prediction*, *Treatment Implication*, *Limitation*],

  // Entry 1: HPA Trust-Breaking Hypothesis
  [[Corticosteroid-induced HPA "Trust-Breaking" in Post-Viral Fatigue], [H], [0.55], [Acute corticosteroid administration may disrupt endogenous HPA axis feedback in post-viral ME/CFS and Long COVID via GR downregulation and CRH suppression, creating iatrogenic dependency. Negative PoCoVIT trial suggests initial corticosteroid benefit transitions to HPA dysregulation without addressing core pathology.], [@Adam2024PoCoVIT], [Corticosteroid suppresses CRH → downregulates GR → blunts endogenous cortisol response → creates artificial dependency cycle.], [<hyp:steroid-hpa-trust-breaking>], [Longitudinal cortisol profiles pre/post corticosteroid treatment will show blunted diurnal variation and increased post-treatment fatigue severity vs baseline.], [Corticosteroids contraindicated; focus on HPA axis restoration (circadian rhythm, stress response training, low-dose hydrocortisone if CRH confirmed low).], [Mechanism inferred from negative trial; direct HPA axis measurements in corticosteroid-treated Long COVID patients not yet available.]],

  // Entry 2: Viral Reactivation via NK Suppression
  [[Corticosteroid-Induced NK Cell Suppression Facilitates Viral Reactivation], [H], [0.55], [Methylprednisolone dose-dependently suppresses NK cell cytotoxicity and IFN-γ production, potentially enabling EBV/HHV-6 reactivation in Long COVID and ME/CFS. PoCoVIT trial adverse events may reflect viral reactivation rather than pure immunosuppression.], [@Adam2024PoCoVIT], [Corticosteroids suppress NK cells → reduced viral surveillance → EBV/HHV-6 reactivation → sustained immune activation → chronic fatigue.], [<hyp:steroid-nk-viral-reactivation>], [Corticosteroid-treated patients will show increased EBV/HHV-6 viral load and decreased NK cell activity vs placebo at 3-month follow-up.], [Antiviral protocols (valacyclovir) + NK-boosting supplements (beta-glucan, medicinal mushrooms) preferred over corticosteroids.], [PoCoVIT trial did not measure viral load or NK cell activity; mechanism inferred from corticosteroid pharmacology.]],

  // Entry 3: Transcriptional Reprogramming Trap
  [[Corticosteroid-Induced Transcriptional Reprogramming Creates Pathological "Stuck State"], [H], [0.50], [Glucocorticoid receptor (GR) signaling induces rapid transcriptional reprogramming via chromatin remodeling. In post-viral contexts, acute corticosteroid exposure may lock immune cells into pathological gene expression patterns that persist after drug clearance, explaining PoCoVIT's lack of durability and adverse events.], [@Adam2024PoCoVIT], [GR binding to GREs → chromatin remodeling → persistent transcriptional "memory" even after corticosteroid clearance → pathological immune state.], [<hyp:steroid-transcriptional-lock>], [Single-cell RNA-seq of PBMCs pre/post corticosteroid treatment will show persistent gene expression changes at 6-month follow-up despite drug clearance.], [Epigenetic modulators (HDAC inhibitors, DNA methylation agents) may reverse corticosteroid-induced transcriptional locking.], [Single-cell transcriptomics not performed in PoCoVIT; mechanistic inference from GR biology.]],

  // Entry 4: GR Isoform Imbalance
  [[GR Isoform Imbalance (GRα/GRβ) Underlies Corticosteroid Resistance and Adverse Outcomes], [H], [0.45], [Chronic inflammation in Long COVID and ME/CFS may shift GR isoform expression toward GRβ (dominant-negative) and away from GRα (functional), creating corticosteroid resistance and paradoxical pro-inflammatory effects. PoCoVIT trial failure may reflect undetected GR isoform imbalance.], [@Adam2024PoCoVIT], [Inflammation → increased GRβ:GRα ratio → corticosteroid resistance → paradoxical GRβ-mediated inflammation → adverse outcomes.], [<hyp:gr-isoform-imbalance>], [GRβ:GRα mRNA ratio > 0.5 in peripheral blood monocytes will predict corticosteroid non-response and increased adverse events.], [GRα-selective agonists or GRβ silencing approaches may restore corticosteroid responsiveness; GR isoform screening before corticosteroid use.], [GR isoform expression not measured in PoCoVIT; mechanism inferred from inflammatory disease literature.]],

  [[Corticosteroids May Exacerbate T Cell Exhaustion in Post-Viral Fatigue], [H], [0.45], [Glucocorticoids modulate T cell function through GR-mediated transcriptional reprogramming, PD-1 pathway modulation, metabolic suppression, and subset-specific CD8+ preference. In ME/CFS, where CD8+ T cells already show epigenetic locking of exhaustion programs and failed metabolic reprogramming, corticosteroids may lock cells deeper into exhausted states rather than restoring function.], [@Adam2024PoCoVIT @iu2024tcell_exhaustion @Mandarano2020], [GR activation → transcriptional reprogramming + PD-1 upregulation + metabolic suppression + CD8+ preference → deeper T cell exhaustion → impaired viral clearance → worse outcomes.], [<hyp:steroid-tcell-exhaustion>], [ME/CFS/Long COVID patients receiving corticosteroids will show increased PD-1/Tim-3/CTLA-4 on CD8+ T cells, deeper transcriptional exhaustion shifts, reduced viral clearance, and in vitro dexamethasone will increase checkpoint expression more than in healthy controls.], [Corticosteroids contraindicated in post-viral fatigue; if unavoidable, combine with T cell support (checkpoint modulation, metabolic support) and monitor exhaustion markers.], [Direct evidence for corticosteroid effects on ME/CFS T cell exhaustion lacking; mechanistic inference from GR biology and negative methylprednisolone trial.]],

  [[GR Signaling Bifurcation in Post-Viral vs Acute Inflammation], [S], [0.45], [The immune response in post-viral ME/CFS and Long COVID may have bifurcated away from standard acute inflammation model that guides corticosteroid use. Altered cofactor availability, epigenetic reprogramming at GR binding sites, shifted GR isoform balance, and exhausted immune cell phenotypes may cause GR activation to produce different effects in chronic post-viral states vs acute inflammation, explaining why steroids work in acute COVID pneumonia but fail in Long COVID/ME/CFS.], [@Adam2024PoCoVIT], [Chronic inflammation → altered GR signaling context → different transrepression/transactivation ratio → unexpected steroid effects → treatment failure.], [<spec:gr-bifurcation>], [Single-cell ATAC-seq will show different chromatin accessibility at GR binding sites in ME/CFS vs acute inflammation; GR activation will produce different gene expression signatures; transrepression/transactivation ratio altered; acute inflammation biomarkers (IL-6, CRP) won't predict steroid response in post-viral fatigue.], [Corticosteroids generally contraindicated in post-viral fatigue unless compelling indication; need GR signaling phenotyping before any steroid use.], [Direct evidence for GR signaling bifurcation in ME/CFS lacking; mechanistic inference from negative methylprednisolone trial and GR biology.]],

  [[Corticosteroid Timing Paradox: Early Harm, Late Benefit], [H], [0.35], [The timing of corticosteroid administration relative to viral infection may determine outcomes. Early administration (less than 4 weeks post-infection) may impair viral clearance and immune priming, increasing chronic sequelae risk. Late administration (greater than 6 months) might provide anti-inflammatory benefits without compromising viral clearance, as viral reservoir is established and immune dysregulation is primary pathology. Explains why steroids work in acute COVID pneumonia but fail in Long COVID.], [@Adam2024PoCoVIT], [Early steroids → NK suppression + T cell priming disruption + GR reprogramming → viral reservoir establishment → chronic sequelae. Late steroids → established reservoir + chronic inflammation → anti-inflammatory benefit without viral clearance compromise.], [<hyp:steroid-timing-paradox>], [Retrospective analysis will show worse Long COVID outcomes with steroids less than 4 weeks vs greater than 6 weeks; animal models will show higher viral load/chronic sequelae with early vs late steroids; biomarker profiles differ (viral markers early, inflammation markers late).], [Steroids generally contraindicated in post-viral fatigue; timing-dependent effects uncertain; avoid unless compelling indication.], [Timing hypothesis speculative; no prospective trials comparing early vs late steroid administration in post-viral syndromes.]],

  // Entry 5: Corticosteroid Worsening Speculation
  [[Corticosteroids May Worsen Long-Term Outcomes in Post-Viral Fatigue], [S], [0.35], [Despite acute anti-inflammatory effects, corticosteroids may impair viral clearance, disrupt tissue repair, and induce endocrine dependency that prolongs recovery. PoCoVIT trial's early termination and high adverse event rate suggest net harm in Long COVID. Similar concerns apply to ME/CFS.], [@Adam2024PoCoVIT], [Corticosteroids impair viral clearance + disrupt tissue repair + induce endocrine dependency → prolonged recovery → net harm despite acute inflammation reduction.], [<spec:corticosteroid-mechanism>], [Corticosteroid-treated patients will have lower recovery rates and higher symptom burden at 12-month follow-up vs untreated controls.], [Corticosteroids contraindicated in post-viral fatigue; focus on viral clearance (antivirals) and tissue repair (growth factors, collagen support).], [Long-term outcomes not measured in PoCoVIT (trial terminated early); mechanism speculative.]],

  // Entry 6: Steroid-Sparing Anti-Inflammatory Protocol
  [[Steroid-Sparing Anti-Inflammatory Protocol for Post-Viral Fatigue], [S], [0.40], [Given corticosteroid failure, a protocol combining mast cell stabilizers (cromolyn, ketotifen), low-dose colchicine, and omega-3 fatty acids may provide anti-inflammatory benefits without HPA axis disruption. This addresses ME/CFS/Long COVID neuroinflammation while avoiding corticosteroid risks.], [@Adam2024PoCoVIT], [Mast cell stabilization + anti-fibrotic (colchicine) + anti-inflammatory (omega-3) → reduced neuroinflammation without HPA disruption.], [<spec:steroid-sparing-protocol>], [Steroid-sparing protocol will reduce inflammation markers (IL-6, TNF-α) and improve fatigue scores without altering cortisol rhythm.], [Cromolyn 100mg QID, ketotifen 1mg BID, colchicine 0.5mg daily, omega-3 2g daily for 12 weeks.], [No clinical trials of this specific combination in ME/CFS or Long COVID; individual components have mixed evidence.]],

  // Entry 7: Post-Steroid Recovery Protocol
  [[Post-Steroid Recovery Protocol for HPA Axis Restoration], [S], [0.45], [Patients who received corticosteroids for Long COVID or ME/CFS may require structured HPA axis recovery including circadian rhythm optimization, adrenal support (adaptogens, licorice), and gradual weaning of any iatrogenic dependency. PoCoVIT trial participants likely need recovery support.], [@Adam2024PoCoVIT], [Circadian alignment + adrenal support + gradual weaning → HPA axis restoration → reduced iatrogenic fatigue.], [<spec:post-steroid-recovery>], [Structured recovery protocol will improve fatigue scores and normalize cortisol rhythm in corticosteroid-exposed patients vs standard care.], [Morning light exposure, sleep schedule regularity, ashwagandha 300mg BID, licorice root 200mg AM, magnesium 400mg PM for 8 weeks.], [No trials of post-steroid recovery specifically in ME/CFS or Long COVID; protocols adapted from adrenal fatigue literature.]],

  // Entry 8: VNS as Corticosteroid Alternative
  [[Vagus Nerve Stimulation as Corticosteroid Alternative for Neuroinflammation], [S], [0.50], [Transcutaneous vagus nerve stimulation (tVNS) may provide anti-inflammatory and autonomic benefits in ME/CFS and Long COVID without HPA axis disruption. Unlike corticosteroids, VNS enhances cholinergic anti-inflammatory pathway via parasympathetic activation, addressing neuroinflammation mechanism.], [@Adam2024PoCoVIT], [tVNS → parasympathetic activation → cholinergic anti-inflammatory pathway → reduced neuroinflammation without HPA disruption.], [<spec:vns-steroid-alternative>], [tVNS 15min BID will reduce inflammation markers and improve fatigue scores without altering cortisol rhythm or causing adverse events.], [tVNS devices (gammaCore, Nemos) 15min BID on neck, targeting auricular branch for 12 weeks.], [Small pilot studies in rheumatoid arthritis and Crohn's disease show benefit; no trials in ME/CFS or Long COVID yet.]],
)
