#import "../../../../../shared/environments.typ": *

#speculation(title: [Waking Local Sleep as a Convergent Mechanism for Brain Fog])[
*Certainty: 0.35.* The phenomenon of "local sleep" — sleep-like slow waves occurring in localized cortical patches during wakefulness — provides a mechanistic bridge between the neurochemical and energy-limitation mechanisms described in this chapter and the subjective experience of cognitive dysfunction ("brain fog"). The upstream drivers converge into a tractable electrophysiological endpoint: individual cortical columns entering slow-wave oscillations (1–4 Hz delta) while the rest of the brain maintains waking activity.

*Mechanism.* In neurotypical individuals, sleep-like slow waves appear during demanding or repetitive waking tasks as a use-dependent consequence of prior cortical activity @Andrillon2023localSleepReview. These intrusions are gated by catecholamine tone: noradrenaline and dopamine suppress waking slow waves, while serotonin promotes them @Pinggal2022pharmaSlowWaves. Intracellular chloride accumulation during wake at synapses with low KCC2 expression increases the probability that local patches of cortex tip into slow-wave oscillations when metabolic or attentional demands exceed the available energy budget @Alfonsa2023chlorideLocalSleep. Systemic inflammation can trigger region-specific waking slow-wave intrusions even without the usual cognitive-load precondition @Leemburg2025LPSvigilance.

In ME/CFS, all three gatekeeping factors are disrupted simultaneously:

- *Catecholamine deficiency:* The NIH deep phenotyping study documented significant deficits in central noradrenergic signalling (reduced CSF DHPG, blunted LC response) @walitt2024deep. Without adequate noradrenergic tone, the neural circuits that normally maintain waking cortical desynchronisation lose their primary arousal support — cortical columns that would normally be held in a depolarised, information-processing state drift toward the depolarised-downstate alternation characteristic of slow-wave sleep.

- *Neuroinflammation and altered chloride homeostasis:* Chronic microglial activation (Section @sec:ch15-microglia) elevates extracellular cytokines that shift KCC2/NKCC1 transporter expression ratios, increasing intracellular chloride in cortical neurons @Alfonsa2023chlorideLocalSleep. The resultant shift in GABA reversal potential means that what should be inhibitory GABAergic input instead produces paradoxical depolarisation or fails to prevent the transition to slow-wave oscillations. This is mechanistically convergent with the KCC2 downregulation documented in neuroinflammatory states Coull et al.\ (2003, Nature).

- *Energy limitation:* The ATP synthesis deficit (Chapter @ch:energy-metabolism) and reduced cerebral blood flow (Chapter @ch:neurological) mean that the ion pumps maintaining waking membrane potentials (Na#super[+]/K#super[+]-ATPase, KCC2) operate on a depleted energy substrate. Cortical columns that in a healthy brain would sustain waking activity during a demanding task instead exhaust their local ATP budget more rapidly, triggering local slow-wave transitions at cognitive loads that would be trivially sustained by a non-ME/CFS brain @VanDongen2025localVsGlobalSleep.

- *Direct inflammation-to-local-sleep pathway:* The LPS-challenge model demonstrates that peripheral inflammation can produce region-specific waking slow-wave intrusions without requiring cognitive load @Leemburg2025LPSvigilance. In ME/CFS — where systemic inflammation markers are elevated at baseline and surge after exertion (Section @sec:ch15-cytokine-fatigue) — this pathway may operate tonically and episodically, producing both background cognitive impairment and post-exertional cognitive exacerbation.

In adults with ADHD, waking slow-wave density is significantly elevated compared to controls and mediates attentional lapses, slowed reaction times, increased response variability, and subjective sleepiness @Pinggal2026localsleepADHD. The behavioral signature — omission errors, intra-individual RT variability, task disengagement ("mind blanking") — maps precisely onto the cognitive complaints reported by ME/CFS patients as "brain fog." In post-COVID attention studies, global slowing and increased intra-individual variability — the behavioral correlate of elevated waking slow-wave activity — are characteristic findings @Ortelli2022postcovidAttention. No study has yet applied the waking slow-wave EEG paradigm to ME/CFS patients.

The local-sleep model integrates several seemingly disconnected findings from the ME/CFS sleep literature: the ultra-slow power (0.3–0.79 Hz) deficit during slow-wave sleep in CFS @Neu2015swsMECFSinsomnia — the same frequency band in which waking slow waves occur; the reduced parasympathetic activity specifically during SWS, indicating that even when patients achieve deep sleep, it is not restorative @Fatt2020parasympatheticSWS; and the paradoxical finding that ME/CFS patients can have normal or increased total SWS duration while still reporting profoundly unrefreshing sleep @Maksoud2021SleepMECFS. If the same oscillatory defect — a failure to maintain desynchronised, information-processing cortical states — occurs during both wake (as local sleep intrusions causing brain fog) and sleep (as alpha intrusion and microarousals preventing restorative slow-wave function), the mechanism becomes parsimonious: a single sleep-wake boundary dysregulation phenotype produces daytime cognitive dysfunction and non-restorative sleep through the same underlying neurochemical and metabolic substrate.

*Falsifiable prediction:* In ME/CFS patients performing a sustained attention task under EEG, waking slow-wave density (SW/min over parieto-temporal electrodes) will be significantly higher than in matched controls, and will correlate with subjective brain fog severity (MFS or CFQ), omission error rate, and RT variability. Falsified if no group difference in waking SW density, or if SW density does not correlate with cognitive performance.

*Consequence:* This provides a single testable explanatory mechanism for cognitive dysfunction in ME/CFS that bridges neuroinflammation, catecholamine deficiency, and energy metabolism. If confirmed, waking slow-wave density would become an objective electrophysiological biomarker of brain fog severity, and treatment strategies could target catecholamine support, anti-neuroinflammatory interventions, and energy-substrate optimization with a quantifiable electrophysiological endpoint rather than subjective report alone. The immediate practical consequence is to identify a specific, tractable research protocol that could disambiguate this mechanism from competing cognitive-dysfunction models within 2–3 years.

*Limitations.*
This hypothesis relies entirely on cross-disease extrapolation from ADHD, post-COVID, and animal models; zero ME/CFS waking slow-wave data exist. The behavioral signature overlap (RT slowing, variability, lapses) is circumstantial — these are generic cognitive dysfunction markers present across many neurological conditions, not specific to local sleep. Competing explanations for the same cognitive phenotype include: glymphatic failure with metabolite accumulation, reduced cerebral blood flow during upright posture (orthostatic cognitive hypoperfusion), direct cytokine effects on prefrontal function, kynurenine pathway neurotoxicity, and sleep fragmentation impairing overnight memory consolidation. These are not mutually exclusive — multiple mechanisms may converge on the same behavioral endpoint. Catecholamine deficiency in ME/CFS has been documented at the group level; intra-individual correlation between catecholamine levels and waking slow-wave density has not been measured. BDNF-TrkB signalling, which contributes to local sleep buildup in animal models @ElGrawani2024BDNFlocalSleep, shows mixed findings in ME/CFS (both elevated and reduced reported). The local-sleep framework provides a mechanistic convergence point for existing observations but does not yet explain why some ME/CFS patients have brain fog as their dominant symptom and others do not. The ADHD data were collected in medication-withdrawn patients; whether concurrent psychostimulant treatment modifies the relationship is unknown.

*Evidence note.* The core local-sleep phenomenon (slow waves during wake) is well-established in human EEG literature @Andrillon2023localSleepReview. PDE: 0.82 (review), 0.80 (ADHD primary, n=63). The link to ME/CFS is mechanistic inference only. Severity applicability: unknown — no waking slow-wave data exist in any ME/CFS severity stratum.
] <spec:ch15-local-sleep-brain-fog>
