#import "../../../../shared/environments.typ": *

==== Step D2: Respiratory supercomplex assembly failure (structural mitochondrial defect)

*Mechanism:* SC I/III/IV forms in a specific stoichiometry (I:III₂:IV) that channels electrons directly from Complex I to Complex III within the lipid bilayer — no need for ubiquinone to diffuse electrons between complexes. This channelling increases electron transfer efficiency and reduces electron leak (ROS production). WASF3 disrupts this assembly → Complex I and III must rely on ubiquinone-mediated electron transfer (slower, leakier) → electrons escape at the I-III interface → superoxide production → oxidative stress. The result: reduced ATP yield per NADH (~2.5 ATP → ~1.5 ATP) and increased ROS per unit of oxygen consumed.

*Probes for supercomplex disruption:*
- *CoQ10 (ubiquinone, 100--300 mg) + NADH (5--20 mg):* CoQ10 shuttles electrons from Complex I/II to Complex III. In SC disruption, CoQ10 + NADH flooding provides supraphysiological substrate to compensate for reduced channelling efficiency — more electrons reach Complex III because there is more electron carrier in the membrane. If CoQ10 + NADH dramatically improves symptoms (≥50% improvement) → SC disruption is partial — the remaining supercomplexes can handle increased electron flux. If CoQ10 + NADH produces only modest benefit (10--20%) → SC disruption is severe — substrate flooding cannot overcome the assembly defect; mitochondria need turnover, not cofactor supplementation. If CoQ10 + NADH produces WORSENING → electron leak at Complex I-III interface increases when substrate flux is increased → more ROS production → oxidative damage. The direction of CoQ10 response IS the SC disruption severity marker.
- *L-carnitine (500--1000 mg):* Enhances fatty acid oxidation → generates FADH₂ (enters at Complex II, electron-transferring flavoprotein → ubiquinone → Complex III). If L-carnitine improves symptoms where CoQ10 does NOT → Complex I is the specific bottleneck, and bypassing it via Complex II (FADH₂ from FAO) restores electron flux. The SC disruption is Complex I-specific — Complex II-containing supercomplexes are intact.
- *MitoQ (mitoquinone, 5--10 mg):* Ubiquinone conjugated to triphenylphosphonium cation → accumulates 100--1000× in mitochondrial matrix (driven by membrane potential). More potent than CoQ10. If MitoQ works where CoQ10 does NOT → the ubiquinone pool in the mitochondrial membrane is inaccessible to oral CoQ10 (poor bioavailability) but MitoQ reaches the matrix. MitoQ response confirms ubiquinone deficiency at the mitochondrial level.

