= Introduction

The production of a comprehensive medical reference work typically involves teams of clinicians, researchers, and scientific editors working over years with access to institutional review processes, subject-matter expertise, and peer critique. This work arises from a different starting point: a single independent author, without formal medical training, attempting to synthesize a rapidly expanding and often contradictory research literature on Myalgic Encephalomyelitis / Chronic Fatigue Syndrome.

ME/CFS presents a particular challenge for this kind of synthesis. The disease is severely underfunded relative to its prevalence and severity, producing a literature characterised by small sample sizes, limited independent replication, heterogeneous patient populations, and diagnostic criteria that have shifted across decades. At the same time, the stakes of accuracy are high: ME/CFS patients frequently encounter medical misinformation, and a reference document that misrepresents the evidence—whether by overstating certainty, confusing mechanistic hypotheses with clinical recommendations, or perpetuating outdated psychogenic models—risks direct patient harm.

This paper describes how these constraints shaped the methodology of the collaboration. The core approach is systematic human–AI collaboration: all text is written by an AI system operating under structured constraints, while the human author performs functions that AI cannot reliably perform—directing scope and priorities, providing original analytical ideas, making judgment calls about epistemic status, and applying deep familiarity with the disease to detect clinical inaccuracies. Quality assurance is achieved through a specialised agent architecture running iterative adversarial review cycles under formal convergence criteria.

The document produced by this methodology spans over 400 pages across five parts: clinical presentation, pathophysiology, treatment, research synthesis, and formal mathematical modeling of pathophysiological processes. The methodology described here has evolved alongside the document; this paper describes the system as it currently stands.
