// Generated by GeneratePathwayTable.java from ops/plans/pathway-registry.md.
// Do not edit by hand. Status legend: mapped (integrated, >=2 sources), partial,
// in-paper (minor mention), evidence-empty (searched, no qualifying), not-assessed.
#table(
  columns: (1fr, 1fr, 1fr, 1fr, 1fr, 1fr),
  [*Pathway family*], [*Mapped*], [*Partial*], [*In paper*], [*Evidence-empty*], [*Not assessed*],
  [1. Ion Channel Hypotheses (ch34 sec-01)], [ 2 ], [ 2 ], [ 1 ], [ 0 ], [ 0 ],
  [2. Mitochondrial Hypotheses (ch34 sec-02)], [ 11 ], [ 4 ], [ 2 ], [ 1 ], [ 0 ],
  [3. Autoimmune Hypotheses (ch34 sec-03)], [ 3 ], [ 2 ], [ 0 ], [ 0 ], [ 0 ],
  [4. Neuroinflammatory Hypotheses (ch34 sec-04)], [ 6 ], [ 2 ], [ 0 ], [ 0 ], [ 0 ],
  [5. Connective Tissue Hypotheses (ch34 sec-05)], [ 2 ], [ 2 ], [ 0 ], [ 0 ], [ 0 ],
  [6. Autonomic Hypotheses (ch34 sec-06)], [ 3 ], [ 2 ], [ 0 ], [ 0 ], [ 0 ],
  [7. Gerlier Skeletal Asymmetry 4-Pathway Model (ch34 sec-07)], [ 4 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ],
  [8. Integrative Models (ch34 sec-08)], [ 4 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ],
  [9. Cross-Hypothesis Convergence Patterns (ch34 sec-09)], [ 4 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ],
  [10. Endocrine & Neuroendocrine Families (cross-cutting; ch52, registry)], [ 3 ], [ 2 ], [ 2 ], [ 0 ], [ 1 ],
  [11. Neurotransmitter & Synaptic Families (ch52, Part II)], [ 7 ], [ 2 ], [ 0 ], [ 0 ], [ 0 ],
  [12. Immune Families (ch51, Part II, registry)], [ 5 ], [ 5 ], [ 0 ], [ 0 ], [ 0 ],
  [13. Vascular, Metabolic & Other Families], [ 5 ], [ 2 ], [ 6 ], [ 0 ], [ 0 ],
)
