#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Sickness Behavior as the Emotional-Interoceptive Phenotype of ME/CFS])[
The sickness behavior syndrome—fatigue, anhedonia, social withdrawal, hyperalgesia, cognitive slowing—can be reframed as the _emotional and interoceptive phenotype_ of cytokine-driven neuroinflammation. This reframes "emotional" symptoms not as comorbidities but as downstream consequences of the same immune-to-brain signaling that produces fatigue. The Dantzer model of cytokine-induced sickness behavior @Dantzer2008inflammation @Dantzer2007twenty maps directly onto the emotional processing abnormalities documented in ME/CFS: elevated alexithymia (difficulty identifying feelings — Maroti et al.\ 2017 @Maroti2017alexithymiaCFS), emotional-autonomic dissociation (blunted physiological reactivity with heightened subjective distress — Rimes et al.\ 2016 @Rimes2016emotionSuppressionCFS), and negative-affect-amplified somatic symptom reporting (Van Den Houte et al.\ 2017 @VanDenHoute2017negativeAffectSomatic).

Barrett's Theory of Constructed Emotion provides the computational framework: emotions are predictions constructed from interoceptive and exteroceptive sensory arrays, categorised using prior experience @Barrett2025ConstructedEmotion @Barrett2025moreFeeling. When the interoceptive sensory array is corrupted by inflammatory signals at vagal paraganglia and circumventricular organs, the brain's predictions about emotional state become systematically miscalibrated. What is experienced as "alexithymia" is the downstream cognitive consequence of the brain trying to construct emotion categories from degraded interoceptive input. (Origin: brainstorm)

(Certainty: 0.45. The cytokine→sickness behavior pathway is well-established; the emotional-phenotype reframing extends this established mechanism but has not been directly tested as a unified model in ME/CFS. The Barrett constructed emotion framework provides computational plausibility but relies on general-population neuroscience. *Falsification condition:* If alexithymia scores in ME/CFS do not correlate with inflammatory markers (CSF IL-1β, IL-6, TNF-α) or if anti-inflammatory interventions that reduce fatigue do not reduce alexithymia, the inflammatory etiology model for alexithymia is not supported. If emotional processing abnormalities in ME/CFS are indistinguishable in severity from matched general-population depression cohorts, the disease-specific inflammatory pathway is not supported.)
] <hyp:ch15-sickness-emotional-phenotype>
