#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Sickness Behavior Is the Emotional Face of Immune Activation])[
When you have the flu, you don't just feel tired—you lose interest in food, withdraw from social contact, feel mentally slow, and everything hurts more than it should. This coordinated package of symptoms is called sickness behavior, and it's produced by the same immune-to-brain signaling that causes fatigue. Normally it resolves when the infection clears. In ME/CFS, this program appears to get stuck in the "on" position.

The emotional symptoms that clinicians often label as separate problems—difficulty identifying feelings (alexithymia, documented in CFS by Maroti et al.\ 2017 @Maroti2017alexithymiaCFS), a gap between what the body shows and what the person feels (emotional-autonomic dissociation, found experimentally by Rimes et al.\ 2016 @Rimes2016emotionSuppressionCFS), and the way negative mood amplifies physical symptoms more in CFS than in healthy people (Van Den Houte et al.\ 2017 @VanDenHoute2017negativeAffectSomatic)—can all be understood as different expressions of the same underlying problem @Dantzer2008inflammation @Dantzer2007twenty.

Barrett's Theory of Constructed Emotion provides a framework for understanding why @Barrett2025ConstructedEmotion @Barrett2025moreFeeling. Emotions are not hardwired circuits that just "turn on"—they are predictions the brain constructs by combining body signals with past experience. If the body signals arriving at the brain are corrupted by inflammation (at the vagus nerve and the leaky spots in the blood-brain barrier), the brain's emotion predictions become systematically unreliable. What gets labeled "alexithymia" may simply be the brain trying to build an emotion from degraded raw materials. (Origin: brainstorm)

(Certainty: 0.45. The immune→sickness behavior pathway is well-established. Reframing emotional symptoms as part of this same pathway—rather than as separate psychological problems—extends the model but has not been directly tested as a unified framework in ME/CFS. The Barrett theory provides plausibility from general neuroscience. *Falsification condition:* If alexithymia scores in ME/CFS do not track inflammatory markers, or if treatments that reduce inflammation and fatigue leave alexithymia unchanged, then the emotional symptoms are not primarily driven by the immune-to-brain pathway. If emotional abnormalities in ME/CFS are indistinguishable in severity from those in matched depression patients without ME/CFS, the disease-specific pathway is not supported.)
] <hyp:ch15-sickness-emotional-phenotype>
