#import "../../../../shared/environments.typ": *

==== Step B1: TRPV1 activation on arteriolar smooth muscle

*Mechanism:* TRPV1 on vascular smooth muscle is different from TRPV1 on sensory neurons. On sensory neurons, TRPV1 activation produces pain (the burning sensation of capsaicin). On vascular smooth muscle, TRPV1 activation produces contraction (Ca²⁺ influx → myosin light chain kinase → vasoconstriction). The drug probes must distinguish these two TRPV1 populations — a drug that blocks TRPV1 on sensory neurons (reducing pain) may also block TRPV1 on vascular smooth muscle (preventing vasoconstriction — beneficial), or it may only block one population depending on tissue distribution and drug access.

*Probes:*
- *Capsaicin (topical, 0.025--0.075%, applied to painful muscles):* TRPV1 agonist at low concentration — activates then desensitizes TRPV1 on sensory C-fibers. Repeated application depletes substance P and CGRP from sensory terminals, producing prolonged analgesia. If topical capsaicin reduces localized muscle pain after exertion → the pain is TRPV1-mediated on sensory fibers. Does NOT address the vascular TRPV1 component (topical capsaicin does not reach arteriolar smooth muscle in meaningful concentrations). Capsaicin response = sensory TRPV1 confirmed. Capsaicin null = pain is not TRPV1-mediated on sensory fibers (it is from ischemia, acidosis directly, or central sensitization).
- *NEO6860 (selective TRPV1 antagonist, Phase II for osteoarthritis):* Blocks TRPV1 without the initial activation that capsaicin causes. Systemic administration would block both sensory and vascular TRPV1. If NEO6860 reduces PEM severity and duration → TRPV1 on BOTH sensory and vascular smooth muscle is rate-limiting. If NEO6860 reduces pain but not PEM duration → TRPV1 is involved in pain perception but not in the ischemic feedback loop — vascular TRPV1 is not the dominant mechanism.
- *If capsaicin works and NEO6860 is unavailable:* This is the clinical reality for most patients. Capsaicin response confirms TRPV1-mediated pain but cannot assess vascular TRPV1. The distinction matters for treatment: if pain is purely sensory TRPV1 → topical capsaicin is sufficient. If vascular TRPV1 is involved → systemic TRPV1 antagonism (NEO6860 or future drugs) would be needed for the ischemic component.
- *If capsaicin/NEO6860 does NOT reduce PEM:* TRPV1-mediated vasoconstriction is not rate-limiting. Other vasoconstrictive mediators may dominate: angiotensin II (RAAS dysregulation), endothelin-1 (endothelial dysfunction), or ischemia is from pre-capillary obstruction (microclots, RBC stiffness) rather than arteriolar constriction. Distinguish: if pyridostigmine improves PEM but capsaicin does not → the ischemia is flow/delivery-limited (microvascular), not TRPV1-mediated. If midodrine improves PEM but capsaicin does not → the ischemia is perfusion pressure-limited.
