#import "../../../../../shared/environments.typ": *

#speculation(title: [Consolidation as Loss of Methylation])[
// Geneviève Fourel (personal communication, May 2026) proposed the question: what if
// epigenetic consolidation in ME/CFS is fundamentally about loss of DNA methylation?
// The ProA/ProB repeat sequence framework is from Bonnet, Hulo, Fourel et al. (2026 bioRxiv).
// ***CORRECTION (May 2026): Geneviève has clarified that the global DNMT3B redistribution
// model (DNMT3B transfer from B to A compartment) is proposed by her for cancer and likely
// chronic stimulation, NOT for ME/CFS. For ME/CFS, her proposal is: specific loss-meCpG
// at HSAT2 (and possibly HSAT3) in certain brain cell types initially, with propagation
// to other cells. Loss of DNMT3B activity at HSAT2 is a CONSEQUENCE of HSAT2 activation,
// not the initial cause. This reverses our earlier causal framing.
// The ME/CFS extrapolations are ours and have not been endorsed by those authors.
// NOTE: This speculation is a supporting exposition of the loss-dominant subset of
// the unified vector model. The formal resolution is in Chapter 33 (@oq:consolidation-
// directionality), where the gain and loss models are unified as special cases of a
// per-locus vector formulation. This section provides the biological detail that the
// vector model's per-locus equations compress.
The directionality of ME/CFS epigenetic change is not uniformly toward hypermethylation. While one RRBS study of PBMCs (n=5 ME/CFS) found hypermethylation predominant at differentially methylated features (145 hypermethylated, 69 hypomethylated vs controls) @Peppercorn2025methylation, the broader EWAS literature documents substantial hypomethylation signals. PTPRN2 hypomethylation distinguishes patient subgroups and correlates with brain fog and cognitive symptoms @ChalderMoreau2026ptprn2. Pericentromeric hypomethylation is predicted to derepress HSAT2 satellite repeats, driving immune exhaustion (Chapters @ch:immune-dysfunction and @ch:genetics-epigenetics). Global methylation loss is documented in multiple independent EWAS cohorts @deVega2014methylation @Trivedi2018methylation @Helliwell2020methylation.

=== Scope Clarification: Cancer vs ME/CFS Mechanisms
#include "../../../../../figures/fig-load-bearing-locks.typ"

Geneviève Fourel (personal communication, May 2026) has provided an important scope correction to our earlier framing. The global DNMT3B redistribution model — the wholesale transfer of DNMT3B from the B compartment (heterochromatin) to the A compartment (euchromatin) producing coupled gain and loss — is proposed by Bonnet, Hulo, Fourel et al. for cancer and, by extension, chronic stimulation conditions, but is *not* proposed by the authors for ME/CFS at this time. For ME/CFS, Geneviève proposes a fundamentally different, more targeted mechanism:

1. *Locus-specific loss-meCpG at HSAT2.* Loss of CpG methylation is proposed to occur specifically at HSAT2 (and possibly HSAT3) pericentromeric satellite repeats, not globally across all ProB repeats.

2. *Cell-type specificity.* The initial loss is proposed to occur in certain brain cell types (see the herpesvirus neurotropism discussion below), not systemically.

3. *Propagation.* Once established in initial cell populations, the HSAT2-active state may propagate to other cells, potentially via exosomal transmission mechanisms (Chapter @ch:immune-dysfunction).

4. *Causal arrow reversal.* A critical correction: in the ME/CFS model, loss of DNMT3B activity at HSAT2 is a *consequence* of HSAT2 transcriptional activation, not the initial cause. Viral infection → centromere rearrangement / stress response → HSAT2 transcription → loss-meCpG at the HSAT2 locus → propagation. This reverses our earlier framing where DNMT3B redistribution was treated as the upstream cause.

This correction does not invalidate the vector model's mathematical framework — the per-locus vector $bold(cal(M)) in [0, 1]^n$ accommodates both global redistribution (cancer) and locus-specific loss (ME/CFS) as boundary cases. The clinical implications (methyl-donor support as safer default) remain consistent with the loss-dominant interpretation regardless of whether loss is global or HSAT2-specific.

The competing gain-model (consolidation = hypermethylation) and loss-model (consolidation = hypomethylation at ProB repeats) are not ultimately contradictory. The unified vector model developed in Chapter @ch:causal-hierarchy-formal (@oq:consolidation-directionality) shows that DNMT3B redistribution --- in cancer, a global mechanism --- produces gain at some loci and loss at others simultaneously. In ME/CFS, the loss may be more targeted (HSAT2/HSAT3-specific) and causally downstream of HSAT2 activation rather than upstream. The biological exposition below focuses on the loss-dominant subset of this unified model, now with the corrected locus specificity; for the full mathematical treatment including the irreversibility threshold $m_i^"crit"$, the derived $B_"strength"$ variable, tissue/cell-type indexing, and histone mark coupling, see @oq:consolidation-directionality.

Under the loss-dominant framing of the unified model:

- *Consolidation-as-loss:* Inflammatory and metabolic stress erode methylation at immune activation gene promoters, pericentromeric repeats, and regulatory regions. Once methylation falls below a critical threshold at a locus, the self-reinforcing maintenance loop---which requires pre-existing methyl-CpG binding proteins (MeCP2, MBD) to recruit DNMTs---breaks. Low-density CpG methylation is empirically vulnerable to maintenance disruption and DNMT1 operates via a density-dependent allosteric switch @Tiedemann2024UHRF1lowdensity @Kimura2012DNMT1review. The gene becomes stably derepressed, independent of the original trigger. The disease persists because genes that should be silenced (pro-inflammatory cytokines, retrotransposons, immune activation programs) are constitutively derepressed (see Speculation @spec:icf-methylation-parallel).

- *Treatment inversion:* If consolidation is loss, therapeutic strategy inverts from the current model. Rather than promoting demethylation (TET activation, HDAC inhibitors), the goal becomes *remethylation*---restoring methylation at lost loci via DNMT3A/B activation, methyl donor support (SAMe, methyl-folate, betaine), and sustained anti-inflammatory therapy to reduce the signals driving methylation erosion. The 18--24 month timescale in the current model for "passive demethylation" may actually reflect the slow rate of *active remethylation* at formerly demethylated loci, since de novo methylation by DNMT3A/B is kinetically unfavourable and requires both adequate SAM pools and permissive chromatin context.

- *ProB repeat sequence erosion as 3D genome mechanism:* Bonnet, Hulo, Fourel et al.\ (2026 preprint) demonstrated that CpG methylation loss disproportionately impacts ProB RepSeqs---repeat sequences that promote the B/heterochromatin compartment, including pericentromeric satellites, young LINE-1s, and selected ERVs---selectively weakening heterochromatin and causing genome-wide unfolding @BonnetFourel2026ProAB. Supplementary Data Figure 17 of that preprint shows direct experimental validation: GSATII (HSAT2) satellite repeat methylation is lost in liver cancer, confirming that satellite hypomethylation is a measurable, specific event in disease. In cancer, DNMT3B redistribution away from the B compartment drives targeted methylation erosion at these repeats, with compensatory Polycomb repression at some loci producing the characteristic "global hypo + focal hyper" bidirectional methylation pattern. For ME/CFS, Geneviève Fourel (pers. comm. May 2026) proposes a more targeted mechanism: specific loss-meCpG at HSAT2 (and possibly HSAT3) pericentromeric repeats in certain brain cell types initially, with propagation to other cells — rather than the global DNMT3B redistribution modeled for cancer. The key clarification: in this ME/CFS model, loss of DNMT3B activity at HSAT2 is a *consequence* of HSAT2 transcriptional activation, not the initial cause. What triggers HSAT2 activation? Recent work by Lahaye, Lomonte, Manel et al. (Cell 2025) demonstrates that herpesvirus proteins disrupt centromeres, triggering centromeric DNA amplification — a pathway termed VICAR (viral-induced centromeric DNA amplification and recognition) @Lahaye2025centromere. This centromere rearrangement is the proximate trigger for pericentromeric satellite transcription. The 2019 finding that HCMV IE1 and IE2 proteins are required for HSAT2 transcription @Nogalski2019HSATII is now interpretable as: IE1/IE2 are required for the centromere rearrangement, which in turn triggers HSAT2 transcription, rather than directly transactivating HSAT2.

- *ICF syndrome as Mendelian proof:* ICF syndrome (Immunodeficiency, Centromeric instability, Facial anomalies) is caused by DNMT3B mutations → pericentromeric hypomethylation → satellite repeat derepression → immune deficiency @Pappalardo2021repeats. This is a Mendelian confirmation that methylation loss at pericentromeric loci alone is sufficient to cause immune pathology. ME/CFS may represent a milder, acquired version: partial DNMT3B dysfunction (not mutation) → partial pericentromeric hypomethylation → subclinical immune exhaustion rather than overt immunodeficiency @deVega2021dna_methylation. Geneviève Fourel (pers. comm. May 2026) notes that in ME/CFS, the analogy to ICF is valid with one crucial distinction: in ICF the DNMT3B defect is the initial cause; in ME/CFS, perte d'activité DNMT3B at HSAT2 would be a *consequence* of HSAT2 activation, not the initial cause. The causal sequence in ME/CFS is: viral infection → centromere rearrangement / stress response → HSAT2 transcription → loss-meCpG at HSAT2 → propagation to other cells. The parallel to ICF lies in the shared endpoint (pericentromeric hypomethylation → immune pathology), not in the initiating mechanism.

*Certainty:* 0.45 for the bidirectional-with-loss-signal claim (multiple independent EWAS cohorts document both hyper- and hypomethylation; the dominant balance may depend on tissue and method; PTPRN2 hypomethylation survives correction @ChalderMoreau2026ptprn2; RRBS of PBMCs found 67.8% hypermethylated vs 32.2% hypomethylated in n=5 ME/CFS @Peppercorn2025methylation). 0.30 for the consolidation-as-loss *causal* claim (cross-sectional methylation data cannot establish direction; longitudinal methylation trajectories during disease progression are absent; the evidence is bidirectional, not loss-only). 0.20 for the treatment inversion (remethylation as therapeutic strategy is entirely untested in ME/CFS).

*Falsifiable prediction:* If consolidation is loss-of-methylation, then: (a) bisulfite sequencing of sorted immune cell subsets from ME/CFS patients should show progressive hypomethylation at PTPRN2, pericentromeric repeats, and immune activation loci over the first 6--12 months of disease; (b) recovered patients (symptom-free ≥12 months) should show partial remethylation at these same loci compared to patients with persistent disease; (c) DNMT3A activator treatment should reduce hypomethylation and restore immune function in ME/CFS patient cells in vitro.

*Falsification criteria:* The consolidation-as-loss hypothesis is falsified if (1) longitudinal bisulfite sequencing shows progressive _hypermethylation_ (not hypomethylation) at PTPRN2 and pericentromeric loci during the first 12 months of disease; (2) recovered and non-recovered patients show equivalent methylation levels at these loci (i.e., methylation status does not distinguish recovery outcome); or (3) DNMT3A activator treatment of ME/CFS patient cells fails to reduce derepression of target genes at hypomethylated loci despite confirmed methylation restoration.

*Clinical implication and therapeutic landscape:* If the consolidation-as-loss hypothesis is correct, the clinical value structure would be as follows.

*Direct symptom benefit.* Remethylation would re-silence constitutively derepressed inflammatory programs and retrotransposons at ProB repeats, producing modest direct symptom reduction (estimated 10--20%). Remethylation alone is not a cure---epigenetic consolidation is a load-bearing lock whose removal is necessary, but not sufficient, for recovery. After the lock is cleared, other mechanisms (autoantibodies, metabolic safe mode) must still be addressed.

*Primary clinical value: converting non-responders to responders.* The paper's model predicts that in late-stage patients, epigenetic locks block recovery even when the root cause is addressed (Section @sec:load-bearing-locks). The daratumumab trial illustrates the ceiling: 60% responded; the 40% who did not may represent patients in whom consolidation blocks recovery even after autoantibody elimination. If remethylation opens that gate---restoring epigenetic plasticity so that other therapies can take effect---patients currently at zero response become candidates for improvement, converting failed treatments into successful ones.

*Which patients would benefit.* Under the vector model, the therapeutic strategy is locus-dependent: gain-dominant patients targeting passive demethylation, loss-dominant patients targeting active remethylation at ProB repeats, and mixed patients (most typical) defaulting to methyl-donor support. Three additional factors determine whether a patient carries the loss-dominant lock: (1) *Duration.* Consolidation deepens over the first 18--24 months of disease; recent-onset patients inside the intervention window retain epigenetic plasticity and do not yet have deep ProB erosion. (2) *Entry pathway.* Patients who entered ME/CFS through viral pathways involving herpesvirus reactivation or centromere disruption (via the VICAR pathway @Lahaye2025centromere) are predicted to develop deeper HSAT2-specific hypomethylation. Patients who entered through autoantibody-dominant pathways (GPCR autoantibodies as primary trigger) may have less pericentromeric involvement and therefore less HSAT2-associated erosion. (3) *Severity.* The longest-duration, most severely affected patients---those who have already failed Tier 1 interventions and immunotherapy---are most likely to have deep consolidation. These patients have the worst prognosis and the most to gain.

*Tissue considerations.* Systemic methyl-donor therapy (SAMe, methyl-folate, betaine) affects methylation globally, but the relevant loci to remethylate (ProB repeats in immune cells) are in PBMCs accessible to systemic circulation. CNS loci (hypothalamic microglia, brainstem autonomic nuclei) are separated by the blood-brain barrier: methyl-folate and methyl-B12 cross (via reduced folate carrier and cubam receptors respectively), SAMe permeability is lower and formulation-dependent. Muscle methylation is accessible to systemic circulation but has higher cell turnover than brain, making remethylation more feasible. The treatment implications: (1) some CNS epigenetic benefit may be achieved with BBB-penetrant methyl donors; (2) overdose at hypermethylated loci is mitigated by the fact that methyl donors become incorporated only at loci with active DNMT3A/B — passive incorporation does not occur; (3) tissue sampling for monitoring is limited to blood and saliva, creating an assessment gap for CNS and muscle compartments.

*Treatments under the loss-model.* Methyl-donor support provides the safest default strategy pending resolution of the directionality question, since methyl donors support both methylation maintenance (preventing further ProB erosion) and de novo remethylation regardless of whether the pathology is gain- or loss-dominant. Mechanistic rationale: SAMe is the universal methyl donor for all DNMTs; methyl-folate and methyl-B12 bypass MTHFR polymorphisms and supply one-carbon units; betaine provides an alternative methyl donor via the BHMT pathway @Crider2012folate. Long-term methyl-donor supplementation (folic acid 400 mcg/day + B12 500 mcg/day over 2 years) has been shown to produce measurable genome-wide methylation changes in humans @Kok2015folateB12, establishing the premise that dietary methyl-donor intake can affect the methylation vector $bold(cal(M))$ in vivo — though effect sizes are modest, locus-specific, and no ME/CFS data exist. Already-listed treatments with relevant mechanisms: SAMe (methyl donor, 1600--3200 mg/day), methyl-folate + methyl-B12 (MTHFR bypass, cofactor substrates), riboflavin (MTHFR cofactor for C677T variant carriers), zinc (DNMT structural cofactor), and LDN (reduces DNMT3B-redistributing inflammatory signals). Treatments not yet listed but mechanistically consistent: betaine (alternative methyl donor via BHMT pathway, bypasses folate cycle). Treatments that are explicitly *contraindicated* if the loss-model is correct: HDAC inhibitors, TET pathway activators, 5-azacitidine, and any demethylating agent---all would worsen existing hypomethylation at ProB repeats. DNMT3A/B activators (RG-108 derivatives) and TET inhibitors (Bobcat339) are preclinical and carry oncogenic risk. Efficacy of any methylation-targeted therapy for ME/CFS symptoms remains unproven.

*Limitations:* The consolidation-as-loss framing is a hypothesis, not an established mechanism. The Bonnet, Hulo, Fourel et al.\ preprint @BonnetFourel2026ProAB is a computational genomics framework developed in cancer; the ME/CFS extrapolation is entirely ours and has not been endorsed by those authors. The Fourel paper is itself unconfirmed---also a hypothesis, not peer-reviewed validation. This makes the consolidation-as-loss directionality inference doubly provisional: the ProA/ProB framework is not yet peer-reviewed, and its applicability to ME/CFS is entirely untested.

Existing ME/CFS methylation studies used mixed cell populations (PBMCs, saliva) and cross-sectional designs; cell-type-specific and longitudinal data are absent. The Peppercorn 2025 RRBS finding that hypermethylation dominates in PBMCs (67.8%) directly challenges the loss story and cannot be dismissed. The intervention window prediction places 0.25--0.30 probability on the HSAT2-specific loss-meCpG mechanism (not the global DNMT3B redistribution cancer model) being substantially correct for ME/CFS.

*Resolution in the unified vector model.* The gain/loss tension is resolved by the per-locus vector formulation in Chapter @ch:causal-hierarchy-formal (@oq:consolidation-directionality). The vector model replaces the competing scalars $cal(M)$ (gain) and $cal(L)$ (loss) with $bold(cal(M)) in [0, 1]^n$, capturing both hyper- and hypomethylation at individual loci. Consolidation depth is $||bold(cal(M)) - bold(cal(M))^"baseline"||$ regardless of direction. DNMT3B redistribution produces coupled gain and loss (not either/or), and the therapeutic implications follow from the patient's per-locus pattern (gain-dominant, loss-dominant, or mixed) rather than from a binary model choice. The vector model's clinical recommendation --- methyl-donor support as the safe default for all patients, with direction-correct per-locus targeting as the principled ideal --- supersedes the earlier competing-model framing. Until per-locus methylation profiling is clinically available, methyl-donor support (SAMe, methyl-folate, methyl-B12, betaine) provides the lowest-risk strategy regardless of gain/loss dominance.
] <spec:methylation-loss-consolidation>
