#import "../../../../shared/environments.typ": *

=== Epigenetic Consolidation Formal Treatment
<sec:epigenetic-consolidation>

*DNMT3B zero-sum constraint.* De novo methyltransferase activity is finite per cell. In cancer, redistribution of DNMT3B away from ProB repeats toward ProA/gene regions — driven by chronic inflammation or oxidative stress — produces a coupled change: $sum_i Delta m_i = 0$ at the enzyme-allocation level. Loss at ProB repeats and gain at gene promoters (and at Alu sequences) are not independent observations; they represent one mechanism (enzyme redistribution) with two manifestations. This DNMT3B global redistribution model is proposed by Bonnet, Hulo, Fourel et al. for cancer and likely chronic stimulation, but is not proposed by those authors for ME/CFS (Geneviève Fourel, pers. comm. May 2026). For ME/CFS, the proposed mechanism is more targeted: specific loss-meCpG at HSAT2 (and possibly HSAT3) pericentromeric repeats, with loss of DNMT3B activity at these loci being a *consequence* of HSAT2 transcriptional activation, not the initial cause. The zero-sum constraint remains a structural feature of the global cancer model; its applicability to locus-specific ME/CFS methylation changes has not been established. Direct experimental evidence for DNMT3B redistribution kinetics between heterochromatin and euchromatin compartments was not retrieved in the current literature cycle (rate-limited); the constraint is mechanistically grounded in finite enzyme concentration but remains an unmeasured structural claim pending ChIP-seq or locus-specific binding data.

*Irreversibility threshold.* At each locus $i$, methylation maintenance requires a critical density $m_i^"crit"$ of methyl-CpG binding proteins (MeCP2, MBD1-4) that recruit DNMT1 for replication-coupled maintenance. If methylation falls below $m_i^"crit"$, the self-reinforcing maintenance loop breaks. Recovery at that locus then requires *de novo* remethylation by DNMT3A/3B — kinetically unfavourable and SAM-dependent — rather than passive DNMT1-mediated maintenance. Experimental support: Tiedemann et al. (2024) demonstrated that low-density CpG methylation is particularly vulnerable to disruption of UHRF1 ubiquitin ligase activity and DNMT1 ubiquitin reading — low-CpG-density regions are harder to maintain @Tiedemann2024UHRF1lowdensity. DNMT1's allosteric binary switch further corroborates: the enzyme is processive on highly methylated substrates but becomes inactivated at poorly methylated sites, creating a density-dependent maintenance barrier @Kimura2012DNMT1review. This creates a qualitative distinction in the bold(cal(M)) landscape: loci with $m_i > m_i^"crit"$ can recover passively after disease-state signals are removed; loci with $m_i < m_i^"crit"$ require active, targeted remethylation and may remain hypomethylated indefinitely without intervention.

*B compartment strength.* The 3D genome integrity depends on methylation at ProB repeats. We define a derived quantity:

$ B_"strength" = f(bold(cal(M))_"ProB") $

where $f$ is a monotonically increasing function of per-locus methylation at ProB RepSeqs. In cancer, DNMT3B redistribution → $bold(cal(M))_"ProB"$ falls → $B_"strength"$ falls → A/B compartment identity weakens → genome unfolds → genes normally silenced by heterochromatin proximity become derepressed. This derived variable connects per-locus methylation to the structural genome effect that Fourel et al.\ identify as the mechanism of methylation-loss pathology in cancer @BonnetFourel2026ProAB. For ME/CFS, the applicable mechanism is more targeted: HSAT2-specific loss-meCpG is proposed rather than global redistribution (Geneviève Fourel, pers. comm. May 2026).

*Functional form of $f$.* HP1-driven heterochromatin formation operatingally via liquid-liquid phase separation @Strom2017HP1phaseseparation @Larson2017HP1droplet. Both Drosophila HP1a and human HP1α nucleate into phase-separated droplets only above a critical concentration threshold — below this threshold, droplets fail to nucleate and the compartment dissolves. This biophysics predicts that $f$ is sigmoidal rather than linear: ProB repeat methylation must exceed a nucleation threshold to nucleate the HP1/H3K9me3 condensate that maintains B compartment identity. Near the threshold, small additional methylation loss produces disproportionate compartment weakening (the steep region of the sigmoid). Formally: $f(x) = 1 / (1 + e^(-k(x - x_0)))$ where $x_0$ is the nucleation threshold and $k$ the cooperativity parameter. $B_"strength"$ is a candidate parameter for linking the epigenomic subsystem to downstream gene expression models; both $x_0$ and $k$ are currently unconstrained for ProB repeat loci in ME/CFS.

*Provisionality.* The ProA/ProB repeat framework (Bonnet, Hulo, Fourel et al.\ 2026 preprint) is a computational genomics hypothesis developed in cancer; its extension to ME/CFS is our extrapolation, not endorsed by those authors, and the framework itself is not yet peer-reviewed. The vector model inherits this uncertainty: it provides a better mathematical container for the ProA/ProB hypothesis than the scalar model, but the hypothesis content within the container remains provisional.

