#import "../../../../shared/environments.typ": *

=== The Sodium-Calcium Overload Cascade
<sec:sodium-calcium-cascade>

Wirth and Scheibenbogen  integrated emerging evidence into a model of ion homeostasis failure in ME/CFS. The cascade begins with hypoperfusion (Section @sec:microcirculation-oxygen), which forces cells into anaerobic metabolism. Anaerobic metabolism generates protons as a byproduct. Accumulating protons increase the activity of the sodium-hydrogen exchanger (NHE1), which extrudes protons by importing sodium. Under normal aerobic conditions, the Na#super[+]/K#super[+]-ATPase can clear this sodium, but under hypoperfusion and ATP limitation, this pump becomes saturated and dysfunctional.

When the Na#super[+]/K#super[+]-ATPase fails to maintain the inward sodium gradient, the plasma membrane sodium-calcium exchanger NCX1 (SLC8A1)---which operates electrogenically in a 3 Na#super[+]:1 Ca#super[2+] exchange---reverses direction. In forward mode NCX1 imports three sodium ions to export one calcium ion; in reverse mode (driven by elevated intracellular Na#super[+]) it imports one calcium ion per cycle. The thermodynamic reversal point is set by the NCX reversal potential $E_"NCX" = 3 E_"Na" - 2 E_"Ca"$, where $E_"Na"$ and $E_"Ca"$ are the Nernst potentials for Na#super[+] and Ca#super[2+] respectively. As intracellular Na#super[+] rises, $E_"Na"$ shifts positive, lowering $E_"NCX"$ below the resting membrane potential and driving sustained reverse-mode calcium import.

Critically, the mitochondrial sodium-calcium exchanger NCLX (SLC8B1)---the primary route of calcium efflux from the mitochondrial matrix---is simultaneously impaired: NCLX imports Na#super[+] to export Ca#super[2+], so cytoplasmic sodium overload reduces its driving force. Sodium accumulation therefore traps calcium inside mitochondria via two independent routes: influx through reversed NCX1 and blocked efflux through NCLX. The combined result is mitochondrial calcium overload, direct damage to the electron transport chain, amplified ROS production, and further ATP depletion---reinforcing the original sodium overload.

Petter et al.  provided the first direct _in vivo_ quantification using #super[23]Na-MRI in ME/CFS patients ($n = 6$ per group). Baseline intracellular sodium was elevated across all five lower-leg muscle compartments (12.20 mM vs 9.38 mM in anterior extensors; $p = 0.0034$). Post-exercise sodium accumulation was greater in ME/CFS, and intracellular sodium correlated inversely with hand-grip strength ($p = 0.0319$)---a quantitative link between the ionic signature and functional impairment. Wirth et al.  extended these findings with electron microscopy showing subsarcolemmal mitochondrial damage preferentially localized at sites of calcium influx, consistent with NCLX-mediated calcium trapping.

Scheibenbogen and Wirth  synthesized accumulated histological, MRI, and proteomic data into the concept of *acquired ischemic mitochondrial myopathy* (AIMM): a disease phenotype in which post-infectious vascular dysfunction produces chronic muscle ischemia, driving the NHE1 → Na#super[+] overload → NCX1 reversal → NCLX block → calcium overload → mitochondrial damage cycle as a self-reinforcing acquired pathology, distinct from primary genetic mitochondrial diseases. Proteomics confirmed reduced expression of Na#super[+]/K#super[+]-ATPase subunits (weakened sodium clearance capacity) and upregulated ENaC expression (sodium-sensing retention), indicating the dysfunction involves sustained pathological remodeling at the protein level. The AIMM framing has a direct therapeutic implication: an acquired ionic myopathy is potentially reversible through pharmacological correction of the sodium/calcium overload, without requiring genetic intervention (see Section @sec:mdc002 in Chapter @ch:emerging-therapies).

