#import "../../../../shared/environments.typ": *

=== Circadian Disruption as an Integrative Mechanism


The circadian rhythm abnormalities documented in ME/CFS should not be viewed as isolated sleep problems but rather as disruption of a master regulatory system that normally coordinates multi-system physiology. Loss of circadian organization contributes to HPA axis dysfunction (flattened cortisol rhythm discussed earlier in this chapter), immune dysfunction (loss of circadian immune regulation), metabolic dysfunction (disrupted glucose homeostasis and lipid metabolism), autonomic dysfunction (altered cardiovascular circadian patterns discussed in Chapter @ch:cardiovascular), and thermoregulatory dysfunction (impaired circadian temperature variation).

#speculation(title: [Dual-Oscillator Decoupling: Central SCN vs Peripheral Vascular Oscillator in Thermoregulatory Circadian Failure])[
*Certainty: 0.40.* Cambras et al. demonstrated that skin temperature circadian rhythms are disrupted in ME/CFS and correlate with endothelin-1 (ET-1) levels @Cambras2023SkinTemperatureEndothelin. This suggests that circadian thermoregulation relies on two coupled oscillators: a central suprachiasmatic nucleus (SCN) oscillator driving melatonin and core body temperature rhythms, and a peripheral vascular oscillator (driven by ET-1, local endothelial clocks, and autonomic tone) controlling skin blood flow and heat dissipation. In ME/CFS, the central SCN oscillator may be relatively preserved (melatonin rhythm often normal), while the peripheral oscillator is dysregulated via ET-1 elevation and autonomic dysfunction. The resulting internal phase misalignment — the brain signaling "night" while the periphery signals metabolic activity — produces fatigue via constant error correction in hypothalamic integration centers. This model explains why melatonin alone often fails to normalize thermoregulation: it entrains the central clock but does not address the peripheral oscillator driving skin temperature dysregulation. Falsifiable: ME/CFS patients will show >4-hour phase shift between melatonin rhythm (saliva DLMO) and peripheral skin temperature rhythm minimum; melatonin administration will not re-entrain skin temperature, but ET-1 modulation (bosentan) will re-synchronize both oscillators.
] <spec:dual-oscillator-thermoreg>

#speculation(title: [Circadian Resynchronization as Multi-System Intervention])[
*Certainty: 0.30.* Interventions targeting circadian resynchronization — whether through melatonin, light therapy, behavioural scheduling, or other chronotherapeutic approaches — might provide broader benefits than expected from improving sleep alone. By restoring temporal coordination across multiple systems, circadian interventions could theoretically address multiple aspects of ME/CFS pathophysiology simultaneously.

*Testable prediction:* A chronotherapy trial (timed light + melatonin + activity scheduling) in ME/CFS patients with documented circadian disruption would improve at least two non-sleep outcome domains (e.g. immune markers, cortisol rhythm amplitude, HRV) beyond what sleep improvement alone would predict. Falsified if chronotherapy normalises sleep metrics without measurable improvement in non-sleep circadian outputs.

*Limitations:* The Castro-Marrero 2021 melatonin trial @castromarrero2021melatonin is the only RCT supporting circadian intervention in ME/CFS, combined melatonin with zinc (individual contributions inseparable), and had a modest sample size. No study has tested multi-modal chronotherapy in ME/CFS.
] <spec:circadian-resynchronization>

#speculation(title: [Metabolic-Circadian Entrainment Coupling: Leptin as a Modulator of Phase Re-alignment])[
*Certainty: 0.30.* (Raw certainty 0.55–0.75 in animal studies, from animal model → discounted to 0.28–0.38.) Preclinical work has mapped a molecular substrate by which the metabolic hormone leptin can influence the circadian system's response to light. Leptin-receptor (LepR) neurons in the dorsomedial hypothalamus (DMH) regulate diurnal feeding and metabolism @Faber2021LeptinDMHDiurnal, and DMH LepR neurons project to the suprachiasmatic nucleus (SCN), where they can shift clock phase @Tang2023LeptinDMHSCN; the clock reciprocally gates leptin signalling @OsorioMendoza2025LeptinCircadianGating — a bidirectional coupling. Building on this, an encapsulated-cell therapy delivering constitutively-produced leptin (engineered retinal pigment epithelium cells in subcutaneous alginate capsules) accelerated re-entrainment to both phase advances and phase delays in mice and diurnal cynomolgus macaques, reducing entrainment time by roughly a day in the primates without impairing sleep (increased NREM slow-wave energy) @Fleury2026LeptinCircadian. (Translation gap: animal → human. Not yet validated in ME/CFS patients.)

This suggests the principle that *a metabolic hormone such as leptin, not only light or melatonin, can modulate how quickly the circadian system re-aligns to an external schedule* — a potentially relevant lever for the circadian instability and unrefreshing sleep documented in ME/CFS. Two cautions temper this: the entrainment-acceleration effect rests on a single unreplicated animal intervention whose mechanism the authors themselves flag as unclear, and the Fleury platform delivers *constitutive* (around-the-clock, non-phasic) leptin — a lever that acts on overall level, not on restoring the shape or phase of a rhythmic signal. Falsifiable prediction: in an animal model, selective ablation of DMH LepR neurons, or of SCN LepR innervation, abolishes the entrainment-accelerating effect of systemic leptin elevation; and in humans, a timed metabolic challenge (e.g. a standardised meal or glucose load) timed against a light pulse measurably alters phase-shift magnitude.

*Limitations:* All supporting evidence is preclinical (mouse + nonhuman primate); the entrainment-speed endpoint does not translate directly to ME/CFS symptom relief (see Williams 2002 — melatonin and phototherapy produced no symptomatic improvement in CFS circadian disorder @williams2002therapy); and the Fleury et al. mechanism of action on entrainment is explicitly acknowledged by the authors as unclear. (Evidence source: animal studies — Inference target: ME/CFS circadian system. Link is indirect.)

*Consequence:* If the coupling holds in humans, it would expand the toolbox for helping ME/CFS patients re-stabilise sleep-wake timing beyond light and melatonin alone — but this is an unreplicated preclinical lead, and whether metabolic signals can do so in the ME/CFS circadian system, let alone through a constitutive (non-phasic) lever, is entirely untested.
] <spec:metabolic-circadian-entrainment>

#open-question(title: [Could Raising Leptin Ever Help ME/CFS Circadian Disruption---or Would It Be the Wrong Direction?])[
The preclinical entrainment result @Fleury2026LeptinCircadian immediately raises the question of whether a metabolic/leptin lever could aid the circadian and sleep disruption of ME/CFS. The ME/CFS-specific data do not support assuming this direction of intervention, but neither do they settle it.

    / *Leptin is not low in ME/CFS, which weakens the rationale for raising it:*: A cross-sectional cohort found higher circulating leptin in ME/CFS than controls (n = 31) @Domingo2024BiomarkersMECFSLC, and the only completed controlled measurement of plasma leptin in CFS found no significant baseline difference from matched controls — though its CFS mean was numerically ~35% higher (underpowered rather than a true null) @Cleare2001PlasmaLeptinCFS. On an amount axis, there is no evidence of a deficit to correct. It remains possible, however, that ME/CFS involves central leptin *resistance* in which more ligand is needed to achieve a normal signal (analogous to insulin resistance) — in which case raising levels could still be therapeutic — so the direction is not settled by the amount data alone.
    / *Light exposure is the strongest documented circadian correlate, not a proven "dominant" lever:*: Actigraphy-based light exposure patterns are associated with multidimensional health outcomes in ME/CFS @Cambras2026LightExposureMECFS — an associational finding, not proof that light is the most modifiable or effective input. This asymmetry matters: the same caution used to dismiss the metabolic lever (no intervention evidence in ME/CFS) applies equally to light, whose own intervention RCT (phototherapy) showed no symptomatic benefit @williams2002therapy.
    / *Direct circadian interventions have shown no symptom benefit, cautioning that entrainment speed may not translate:*: Melatonin and phototherapy produced no symptomatic improvement in CFS circadian disorders @williams2002therapy, so even a lever that speeds entrainment may not improve the sleep quality and fatigue complaints that define ME/CFS.

*Consequence:* The honest conclusion is that the metabolic-circadian coupling is worth studying in ME/CFS as a research and diagnostic direction, but there is currently no evidence that raising leptin — a hormone that is not low in this population — would help, and no circadian intervention (metabolic, light, or melatonin) has shown symptom benefit; the open question is whether the defect is a matter of amount, timing, or resistance.
] <oq:leptin-therapeutic-direction>

#open-question(title: [Is ME/CFS Leptin Altered in Timing Rather Than Amount---the Cleare-vs-Domingo Reconciliation?])[
The two direct human measurements of circulating leptin in ME/CFS are read as contradictory — no significant baseline difference from matched controls @Cleare2001PlasmaLeptinCFS versus higher circulating leptin than controls @Domingo2024BiomarkersMECFSLC — but both are single-timepoint snapshots of a hormone that is inherently circadian, and the two point numerically the same way (higher in CFS; Cleare is underpowered rather than a true null). Because a metabolic hormone such as leptin couples to the circadian system bidirectionally @OsorioMendoza2025LeptinCircadianGating, an open possibility is that the relevant abnormality is in the *circadian phase or amplitude* of the rhythm (flattened, phase-shifted, or desynchronized across tissues) — which a single spot sample can only partially detect, depending on shift magnitude and sampling time. (Origin: brainstorm.) A competing reading is that any mean elevation reflects central leptin resistance rather than a timing defect, which this timing hypothesis does not yet engage.

*Testable prediction (Certainty: 0.15):* A 24-hour serial plasma-leptin profile (e.g. hourly or 2-hourly sampling with DLMO or dim-light phase reference) in ME/CFS versus matched controls would reveal a phase-shifted, flattened, or amplitude-reduced rhythm even where single-timepoint means are indistinguishable — and would disambiguate the Cleare and Domingo readings as timing rather than amount. The hypothesis is falsified if serial profiling shows a normal circadian rhythm whose phase and amplitude are within a pre-specified effect-size margin (e.g. amplitude ratio ≥1.5-fold or phase offset ≥2 hours versus controls) — an explicit threshold, since a small underpowered cohort would otherwise default to "indistinguishable."

*Limitations:* The reconciliatory hypothesis is not yet evidenced — no serial leptin profile has been published in ME/CFS (the only systematic review on the question remains a protocol without results @Musker2021LeptinSRProtocol); both existing cohorts are small and single-timepoint, neither stratifies by severity, and neither was designed to resolve circadian timing; and a timing-only abnormality, if confirmed, would still not establish that correcting it is therapeutic, only that it is measurable. (Severity coverage: unknown — neither cohort stratifies by severity.)

*Consequence:* If confirmed, this would mean the field has been asking the wrong question about ME/CFS leptin — the relevant variable might be not how much but when — and it would provide a concrete, feasible measurement protocol to test it; but it is a research hypothesis with no current clinical application.
] <oq:leptin-timing-amplitude>

#synthesis(title: [Metabolic-Circadian Coupling: a Real Biological Lead Whose ME/CFS Direction Remains Unsettled])[
A coherent reading of the integrated evidence is that the metabolic hormone leptin can influence how quickly the circadian system re-aligns to an external schedule — the animal work identifies a molecular substrate (DMH LepR → SCN) and a delivery platform tested in mice and macaques (@spec:metabolic-circadian-entrainment) — but applying this to ME/CFS is not straightforward, and the evidence is one research programme rather than independent confirmation. On an *amount* axis, there is no case for raising a hormone that is not low in ME/CFS (@oq:leptin-therapeutic-direction). On a *timing/amplitude* axis, the productive open question is whether ME/CFS leptin is abnormal in its rhythm rather than its mean, which can only be answered by a serial 24-hour profile and which would reconcile the two single-timepoint human measurements (@oq:leptin-timing-amplitude). Critically, these two axes do not collapse into one intervention: the Fleury platform delivers constitutive (non-phasic) leptin — a lever on level, not on restoring rhythm shape or phase — so it is ill-suited to a timing defect even if one is found. What the evidence supports is that metabolic-circadian coupling is a genuine, research-relevant phenomenon for ME/CFS's circadian instability; what remains open is whether any metabolic intervention would help, and on which axis.

*Consequence:* Clinicians should not expect a "leptin factory" to treat ME/CFS circadian disruption — it is a non-phasic lever, the hormone is not low in the population, and no circadian intervention has shown symptom benefit — and the productive research question is whether a serial profile would reveal a timing-not-amount abnormality worth measuring, not treating.
] <syn:leptin-circadian-entrainment-model>

