#import "../../../../shared/environments.typ": *

#speculation(title: [Regulatory Asymmetry in Harm Monitoring for ME/CFS Psychosocial Trials])[
Drug trials routinely monitor and report adverse events as a regulatory requirement, but psychosocial intervention trials for ME/CFS — despite evidence that activation-based approaches cause harm in a substantial minority of patients — operate under far laxer standards. The general pattern of inadequate harm monitoring in GET/CBT trials is independently documented: Kindlon (2011, @Kindlon2011GET) found systematic underreporting of harms in ME/CFS psychosocial trials, and Cooper et al. (2025, @Cooper2025PacingVsGET) demonstrated via systematic review that GET carries a 3–5× higher harm rate than pacing. Schomerus et al.\ (2026) note a parallel pattern in LC psychotherapy trials: a systematic review found that most included studies provided no adverse effects information — though this specific statistic (reported as a secondary citation within the Schomerus essay) should be treated with caution pending dedicated independent verification @Schomerus2026PsycheRole. PEM, the decisive clinical parameter for safety, is frequently not assessed or not assessed differentially as an adverse outcome in psychosocial trials. Many studies lack control groups, making it impossible to distinguish therapeutic effects from spontaneous recovery or non-specific expectation effects.

This regulatory gap may reflect institutional path-dependence (different regulatory frameworks evolved for drugs vs behavioural interventions) and genuine measurement challenges (defining adverse events in psychosocial trials is inherently harder than in drug trials) rather than motivated blindness. Regardless of the cause, the consequence is the same: inadequate safety data for interventions actively prescribed to a population where harm rates in patient surveys range from 51–74% @Kindlon2011GET.

_(Certainty: 0.65. The general pattern of inadequate monitoring is independently documented by Kindlon (2011) and Cooper (2025). The specific LC psychotherapy statistic is a secondary citation within Schomerus 2026 — the general pattern is well-supported without relying on it. The regulatory-asymmetry claim (different safety standards for drug vs psychosocial trials) is a structural/regulatory fact, not an empirical hypothesis. Falsifiability: a dedicated systematic review of adverse event reporting in all published ME/CFS psychosocial intervention trials would establish the rate of adequate safety monitoring and either confirm or revise the specificity of the claim. Origin: literature — derived from Schomerus 2026's argument, with supporting evidence from Cooper 2025.)_
] <spec:harm-monitoring-gap>
