#import "../../../../shared/environments.typ": *

=== The 2025--2026 Exercise Meta-Analysis Cluster
<sec:exercise-meta-cluster>

Between 2025 and 2026, three new systematic reviews and meta-analyses of exercise therapy for ME/CFS appeared: Wei et al.\ (2025, 13 RCTs, n=1,305) @Wei2025exerciseMECFS, Liao et al.\ (2025, 20 trials, n=2,831) @Liao2025exerciseNetwork, and Zhao et al.\ (2026, 17 RCTs, n=1,944) @Zhao2026exercise. All three share the same structural features: they pool studies using broad diagnostic criteria that do not require PEM, rely exclusively on patient-reported subjective outcomes as primary endpoints, include trials where blinding of participants and therapists is impossible, and---in the case of Zhao and Wei---pool mechanistically distinct interventions (aerobic exercise, yoga, qigong, tai chi) into single analyses.
Zhao et al.\ (2026) is the most detailed and merits close examination. The review reports that exercise significantly improves fatigue (SMD = 0.85), sleep quality, quality of life, depression, and anxiety---all measured by subjective questionnaires. However, exercise produced _no significant improvement_ in cardiopulmonary function or objective functional capacity. The authors themselves applied the Risk of Bias 2.0 tool and found "prevalent high risk of bias across the included studies" @Zhao2026exercise. Despite this, they dismissed the bias as representing "inherent challenges of the field rather than fatal flaws that would completely invalidate the clinical value of these trials."
This dismissal is difficult to sustain when placed against the BRANDO evidence (Section @sec:brando-evidence). Hróbjartsson et al.\ quantified the bias from patient unblinding at a mean SMD of 0.56 for patient-reported outcomes @Hrobjartsson2014blinding. Zhao's reported fatigue effect of SMD 0.85 falls well within the range where unblinding artifact could account for most or all of the observed effect. The pattern of subjective improvement with null objective results is not a "physiological ceiling," as Zhao et al.\ propose---it is the _predicted signature_ of blinding bias, documented across 1,973 trials in the BRANDO synthesis @Savovic2012blinding. The more parsimonious explanation is that unblinded patients reported feeling better while their underlying physiology remained unchanged.
The diagnostic criteria problem compounds the blinding issue. Zhao's included studies used criteria including Oxford @Sharpe1991oxford, Fukuda @Fukuda1994, and Reeves 2005---none requiring PEM as a mandatory feature. Wormgoor and Rodenburg (2021) demonstrated that treatment effects _disappear_ when only PEM-requiring criteria are used and _disappear_ as outcome measures become more objective @Wormgoor2021physio. Zhao et al.\ did not perform this sensitivity analysis. The intervention heterogeneity further weakens the conclusions: pooling aerobic exercise protocols with yoga, qigong, and tai chi obscures fundamental differences in physiological demands and PEM risk profiles.
#warning-env(title: [The "Acknowledged-But-Discounted Bias" Pattern])[
A recurring pattern in the exercise therapy literature for ME/CFS deserves explicit identification: reviews apply formal risk-of-bias tools, find pervasive high risk of bias, and then proceed to endorse the intervention regardless. Both the updated Cochrane review @Larun2024exerciseCFS and Zhao et al.\ (2026) @Zhao2026exercise follow this template. This pattern converts a quality-assessment tool from a decision aid into a disclosure ritual: bias is documented but has no consequence for the conclusions drawn. The BRANDO evidence (Section @sec:brando-evidence) demonstrates quantitatively that the bias these reviews acknowledge is _sufficient in magnitude_ to produce the effect sizes they report.
] <warn:acknowledged-discounted-bias>
Vink and Vink-Niese have documented the subjective/objective discrepancy across multiple analyses. Their 2018 re-analysis of the Cochrane exercise review demonstrated that objective measures showed no benefit from GET @Vink2018cochrane. Their 2020 analysis established that GET does not restore the ability to work @VinkNiese2020workCFS. Most strikingly, their 2022 analysis of the PACE trial data showed that 20% of participants whose physical functioning improved on subjective questionnaires had actually _deteriorated_ on the objective six-minute walk test @VinkNiese2022NICE.
The convergence of these findings with the BRANDO quantitative framework produces a clear conclusion: the 2025--2026 exercise meta-analyses do not provide evidence that exercise improves ME/CFS. They provide evidence that unblinded patients report feeling better on questionnaires while their physiology remains unchanged---exactly what the blinding-bias literature predicts. Until exercise trials for ME/CFS include adequate blinding (or at minimum use objective primary endpoints and PEM-requiring diagnostic criteria), meta-analyses of existing trials will continue to produce the same misleading pattern.

#include "./mechanisms-beyond-classical-bl/mechanisms-beyond-classical-bl.typ"
#include "./quantifying-the-iatrogenic-har/quantifying-the-iatrogenic-har.typ"

