#import "../../../../../shared/environments.typ": *

#open-question(title: [Does the CSF:Blood Ratio of Neuronal Proteins Distinguish Inflammatory Rerouting from Obstructive Trapping?])[
Chayama et al.\ (2026) demonstrated two mechanistically distinct failure modes for brain clearance --- acute inflammation shunts proteins into blood (high blood, low border clearance), while amyloid pathology traps proteins in the parenchyma (low blood, low border clearance) @Chayama2026BrainClearance. These produce opposite predictions for the CSF:blood ratio of neuron-derived proteins (NfL, tau, amyloid-$beta$): inflammatory rerouting should produce high blood neuronal proteins relative to CSF (ratio less than 1), while obstructive trapping should produce high CSF neuronal proteins relative to blood (ratio greater than 1).

If this framework applies to ME/CFS, simultaneous CSF and blood measurement of neuronal proteins could serve as a disease-stage biomarker with direct therapeutic implications. Early disease (less than 2 years, inflammatory-dominant) would predict response to anti-inflammatory/BBB-stabilising interventions; late disease (more than 10 years, obstructive-dominant) would predict response to clearance-enhancing/SWS-restoring interventions. A flat ratio ($tilde$1) throughout disease would refute the rerouting-vs-trapping distinction and suggest a unitary impairment.

Key research questions: (a) Does the CSF:blood neuronal protein ratio shift over disease course from less-than-1 to greater-than-1 in a longitudinal post-infectious ME/CFS cohort? (b) Does this ratio predict treatment response --- anti-inflammatory agents in low-ratio patients, SWS-enhancing agents in high-ratio patients? (c) Can blood-only measurement of multiple neuronal proteins (NfL, p-tau181, GFAP) serve as a clinically accessible proxy for the full CSF:blood ratio, avoiding the need for lumbar puncture? (d) Does the ratio correlate with the specific ME/CFS mechanism (BBB integrity biomarkers for rerouting, structural degradation biomarkers for trapping)?
] <open:ch15-csf-blood-ratio>
