#import "../../../../shared/environments.typ": *

=== Complement System
<sec:complement>

The complement system consists of plasma proteins that enhance (“complement”) antibody and phagocyte function. Abnormalities in ME/CFS include:

==== Complement Activation Patterns

ME/CFS patients show elevated activation products, with increased C3a, C4a, and C5a fragments indicating ongoing complement activation . Reduced levels of C3 and C4 suggest consumption of these complement components. Additionally, abnormal levels of complement regulatory proteins point to altered regulation of the system.

Serum proteomics data from Hoel et al.\ (2026) @Hoel2026proteome confirmed and extended these findings: complement factor D (CFD) and complement component C6 were among the most significantly elevated secreted proteins in ME/CFS. Elevated CFD indicates activation of the alternative complement pathway, while elevated C6 indicates increased assembly of the membrane attack complex (MAC). The authors noted that elevated CFD and C6 are implicated in vasculitis, lupus, dermatomyositis, and autoimmune nephritis, further supporting a possible autoimmune-like complement activation pattern in ME/CFS.

==== Exercise-Induced Complement Activation and PEM
<sec:complement-pem>

A series of studies has documented an association between complement activation and post-exertional malaise. Sorensen et al.\ demonstrated significant C4a elevation at 6 hours post-exercise exclusively in CFS patients ($P < 0.01$), regardless of allergy status—the first demonstration of exercise-induced complement activation in CFS @Sorensen2003complement. Nijs et al.\ subsequently identified post-exercise C4a as a clinically important biomarker for PEM, linking complement activation to the molecular mechanism of post-exertional malaise alongside elastase and IL-1$beta$ @Nijs2010pem. Polli et al.\ extended this by demonstrating moderate associations between exercise-induced C4a changes and pain thresholds in ME/CFS ($r=0.669$, $p=0.001$), directly connecting complement activation to exercise-induced hyperalgesia @Polli2019complement.

Most recently, Glass et al.\ (2025) found upregulation of complement system proteins in extracellular vesicles post-exercise in males with ME/CFS, with ER stress response changes correlating with PEM severity @Glass2025ev. This finding is consistent with the earlier soluble C4a observations and extends them to the vesicular compartment, though the male-only sample limits generalizability.

C4a generation is consistent with activation of the lectin and/or classical complement pathways rather than the alternative pathway. This is mechanistically distinct from the CFD (factor D) elevation reported in serum proteomics @Hoel2026proteome, which indicates alternative pathway activation. The co-existence of both pathway activations suggests broad complement dysregulation rather than a single pathway defect.

==== Clinical Implications

Complement abnormalities may contribute to inflammation through anaphylatoxin (C3a, C5a) production and impair pathogen clearance . They may also promote autoimmune manifestations and trigger mast cell activation through complement fragment-induced degranulation .

#speculation(title: [Complement Dynamics During PEM: Reconciling Sorensen 2003 vs Nunes 2024])[
*Certainty: 0.45.* Sorensen et al.\ measured C4a elevation at 6 h post-exercise in CFS patients @Sorensen2003complement, establishing complement activation as an acute PEM-phase event. Nunes et al.\ found reduced complement component C4a in ME/CFS plasma at rest (not post-exercise) @Nunes2024S100A9MECFS. These findings can be reconciled by a biphasic complement model: acute activation (Sorensen: elevated 6 h post-exercise) followed by chronic consumption with supranormal fragments but reduced intact component levels in the resting state (Nunes: low C4a at rest). This pattern — activation peaks during exertion, consumption depletes the reservoir between bouts — is characteristic of a system under chronic intermittent demand.

*Time-resolved model.* Phase 1 (0–6 h post-exertion): Complement cascade activated via classical (immune complex-driven) and lectin (endothelial glycocalyx damage) pathways → C4a, C3a, C5a spike. Phase 2 (6–48 h): Anaphylatoxins drive mast cell degranulation and vascular permeability; C5b-9 (MAC) deposits on endothelium → microvascular injury. Phase 3 (48 h+ sustained): Complement component consumption (reduced C4, C3, factor B) persists if activation continues, as seen in post-COVID ME/CFS @Klein2024longcovid. If the patient rests fully, complement returns to baseline by approximately 72 h. If repeat exertion occurs before full recovery, activation sums — explaining why repeated activity without recovery produces escalating PEM severity.

*Reconciliation mechanism.* Sorensen's C4a spike at 6 h captures Phase 1 (acute activation). Nunes' low resting C4a captures the inter-exertion trough (depleted reservoir between PEM episodes). No contradiction: they measure different temporal phases. The biphasic model predicts that C4a levels vary dramatically depending on time-since-last-exertion, explaining why single-timepoint resting measures produce inconsistent complement results across ME/CFS studies.

*Falsifiable predictions.* (1) Serial complement measurements (C4a, C3a, C5b-9) before and after standardized exercise will show a triphasic pattern: baseline → spike (4–6 h) → gradual decline (24–48 h) → possible sustained elevation if recovery insufficient. (2) The magnitude of the 6 h C4a spike will predict next-day symptom severity (PEM intensity) with $r > 0.5$. (3) Patients with low resting C4a (depleted reservoir) will show the greatest post-exertion spikes, consistent with a system operating near consumption threshold. (4) Complement consumption markers (C3/C4 ratio, C4a/C4 ratio) will correlate with time-since-last-exertion better than absolute C4a levels alone.

*Limitations.* Direct time-series data in ME/CFS are absent — the model synthesizes Sorensen 2003 (6 h post-exercise) and Nunes 2024 (resting proteomics) with no study bridging the full temporal window. The 72 h recovery estimate is extrapolated from general complement biology (C4 half-life ~1–3 days), not ME/CFS-specific data. The biphasic model predicts high inter-study variability depending on sampling protocols, which would need to be confirmed by prospective time-series studies.
] <spec:complement-pem-biphasic>

==== Complement Dysregulation and Infection Susceptibility
<sec:complement-infection>

Complement deficiency—particularly of the terminal pathway (C5–C9) and properdin—is a well-established risk factor for invasive meningococcal disease, with a substantial proportion of recurrent meningococcal cases occurring in complement-deficient individuals (reviewed in standard infectious disease references). ME/CFS complement findings show dysregulation (activation with consumption) rather than genetic deficiency per se: reduced C3 and C4 levels suggest consumption of these components, while elevated activation products (C3a, C4a, C5a) indicate ongoing activation . Persistent complement consumption in Long COVID has been independently confirmed @Klein2024longcovid.

#limitation(title: [Complement Dysregulation $eq.not$ Complement Deficiency])[
The ME/CFS complement phenotype—chronic activation with component consumption—is mechanistically distinct from the genetic complement deficiencies that confer high meningococcal susceptibility. Reduced C3/C4 from consumption may transiently impair opsonization and pathogen clearance, but the terminal pathway (C5–C9 membrane attack complex) critical for killing _Neisseria meningitidis_ has not been specifically assessed in ME/CFS. Whether the exercise-induced C4a elevation @Sorensen2003complement @Glass2025ev reflects a complement system that is functionally compromised—rather than merely activated—for pathogen defense remains an open question. Extrapolating from complement dysregulation to increased meningococcal susceptibility is biologically plausible but empirically unsupported.
]

#speculation(title: [Complement-Driven Perivascular Mast Cell Amplification Loop])[
*Certainty: 0.25.* Based on complement activation evidence (Sorensen, Maya, Bragee) and mast cell biology (established C3a/C5a mechanisms). Downgraded from initial 0.45 because: the loop has never been demonstrated in ME/CFS tissue or any disease; complement and mast cell activation could equally be parallel downstream effects of a shared upstream trigger (e.g., endothelial dysfunction); the Bragee CSF evidence cited has no control group and cannot support between-group claims; multiple complement regulatory proteins (Factor H, Factor I, CD55, CD59) would need to fail simultaneously for sustained amplification, which is not addressed. -genetics @Bragée2026csf-proteome @Sorensen2003complement

The Maya et al.\ complement pQTL subgroup (high C3/low Bb) may represent individuals predisposed to a perivascular amplification loop: complement activation produces C3a/C5a anaphylatoxins → mast cell degranulation at perivascular sites → histamine, tryptase, and heparin increase vascular permeability → further complement protein leakage into perivascular tissue → alternative pathway amplification on host surfaces → more C3a/C5a → more mast cell activation. However, this loop requires: (1) sustained mast cell responsiveness (tachyphylaxis after repeated anaphylatoxin exposure is not addressed), (2) spatial confinement (no mechanism provided for why amplification would be perivascular rather than systemic), and (3) failure of complement regulatory proteins (Factor H, CD55, CD59---none of which are discussed). The simpler alternative---complement activation and mast cell activation as parallel downstream effects of systemic inflammation or endothelial dysfunction---explains the co-occurrence without requiring a novel positive feedback mechanism.

The Bragée et al.\ CSF finding of complement cascade enrichment in severe ME/CFS cases @Bragée2026csf-proteome has been cited as supporting evidence for this loop, but that study had no healthy control group (certainty 0.35) and cannot establish differential expression.

*Testable predictions:*
    + Skin blister fluid or interstitial fluid from ME/CFS patients will show C3a:C3 ratio ≥2× in tissue vs plasma, indicating local complement amplification (research technique requiring specialized collection)
    + Complement-pQTL-positive subgroup will have serum tryptase ≥20% higher and PGD2 ≥30% higher than complement-pQTL-negative patients
    + C5a receptor antagonists (e.g., avacopan) would reduce mast cell mediators by ≥50% if the loop operates; ≤20% reduction supports the parallel-activation alternative
] <spec:complement-mast-cell-loop>

#open-question(title: [Does NCS-1/InsP3R1 Amplify Mast Cell Degranulation in ME/CFS?])[
Mast cells express NCS-1 (neuronal calcium sensor protein 1), which amplifies InsP3R1 channel open probability approximately five-fold. In rat basophilic leukemia mast cells, NCS-1 regulates IgE-triggered exocytosis via PI4Kβ, a kinase that generates PIP#sub[2] substrate from PI @Kappel2003NCS1MastExocytosis. NCS-1 also stimulates ERK signaling through endocytic recycling in mast cells @Kappel2006NCS1ERK and co-regulates mast cell function alongside synaptotagmins @Kappel2007NCS1SynaptotagminMast. Lithium disrupts the NCS-1/InsP3R1 interaction at IC#sub[50] ~350 µM @schlecker2006ncs1, raising the possibility that even ultralow concentrations of Li#super[+] could dampen mast cell reactivity by reducing IP3-mediated Ca#super[2+] release. A critical gap must be acknowledged: the estimated tissue Li#super[+] concentration after 2 mg/day oral dosing is likely ~0.2–2 µM, which falls 100–1,000× below the in vitro IC#sub[50] for NCS-1/InsP3R1 disruption. Lithium is not known to concentrate preferentially in mast cells. NCS-1/InsP3R1 disruption at ultralow dose is biochemically implausible unless one of the following applies: (a) Li#super[+] has a higher-affinity binding mode at a different site on NCS-1 or InsP3R1 that is undetected in the existing binding assay; (b) chronic low-dose exposure produces cumulative effects (e.g., altered NCS-1 expression or post-translational modification) not captured by acute IC#sub[50] measurements; or (c) the relevant target is not NCS-1/InsP3R1 but another Li#super[+]-sensitive enzyme (e.g., GSK-3β, inositol monophosphatase) with different dose-response characteristics. Without evidence for any of these conditions, the concentration gap undermines the hypothesis.

The mechanistic chain linking lithium to mast cell stabilization is assembled from separate literatures and has no direct experimental support: (a) Li#super[+] disrupts NCS-1/InsP3R1 — proven in neurons @schlecker2006ncs1; (b) NCS-1 is expressed in mast cells and regulates degranulation — proven by Kappel 2003; (c) MRGPRX2, C3aR, and C5aR signal through Gαq → PLC → IP3 → Ca#super[2+] → degranulation — well-established (reviewed in Roy 2021 @Roy2021MRGPRX2Review); (d) Orai/STIM1-dependent SOCE is required for sustained MRGPRX2-mediated Ca#super[2+] responses @Chaki2022OraiMRGPRX2 — damping IP3R would reduce both the initial Ca#super[2+] spike and the sustained SOCE. The connection between (a) and (b) is entirely unattested — no study has tested lithium's effect on mast cell degranulation at any concentration. One 1978 study found LiCl did NOT cause mast cell degranulation in rat mesentery @Nahmod1978LithiumMastCellNull, consistent with a stabilizing rather than activating effect, but this is a weak negative control (n small, 1978, indirect).

If the NCS-1/InsP3R1 → mast cell degranulation link operates in ME/CFS, ultra-low-dose lithium (~2 mg/day elemental Li#super[+]) could act as a functional mast cell stabilizer via a mechanism distinct from existing agents: cromolyn (mechanism incompletely understood; calcium influx inhibition), ketotifen (H1 antagonist + mast cell stabilization; mechanism unclear), and omalizumab (IgE sequestration). Lithium would target the GPCR→PLC→IP3→Ca#super[2+] arm of mast cell activation — particularly relevant if GPCR autoantibodies (anti-M3, anti-β2AR) chronically engage this pathway in mast cells, lowering the degranulation threshold. Notably, both FcεRI (ITAM→Syk→PLCγ) and GPCR (Gαq→PLCβ) pathways converge on IP#sub[3]→InsP#sub[3]R#sub[1]→Ca#super[2+] mobilization, so NCS-1 amplification via PI4Kβ — which supplies the PIP#sub[2] substrate for both PLC isoforms — could theoretically influence either route. However, the relative dependence on NCS-1 may differ: the Gαq-PLCβ pathway may rely more heavily on PI4Kβ-mediated PIP#sub[2] resynthesis because PLCβ is more sensitive to PIP#sub[2] availability than PLCγ, which can be recruited to membrane phosphotyrosine clusters. Consequently, lithium should reduce IgE-mediated degranulation less than MRGPRX2-mediated degranulation, rather than leaving it unaffected. This partial-effect prediction is more defensible than a binary affected/unaffected claim and can be resolved experimentally by comparing the dose-response curves for both stimuli. Whether lithium ion concentrations reach mast cells in tissue at sufficient levels after 2 mg/day oral dosing is completely unknown.

*Clinical context and risk.* Currently zero clinical data exist for lithium as a mast cell stabilizer in any condition. Even at 2 mg/day, lithium carries risks including thyroid suppression (goiter, hypothyroidism, requiring TSH and fT3 monitoring), renal clearance variability (requiring serum creatinine monitoring), and potential for toxicity if clearance is impaired — standard lithium monitoring (TSH, fT3, creatinine, serum lithium at steady state) applies. Established mast cell stabilizers with extensive safety data (cromolyn sodium, ketotifen) should be trialed first before considering lithium for this indication. The NCS-1 hypothesis provides a mechanistic rationale for a trial but does not constitute a treatment recommendation.

*Testable predictions.* (1) NCS-1 expression in ME/CFS-derived mast cells (cultured from peripheral blood CD34#super[+] progenitors) will be at least 2-fold elevated vs healthy controls by qPCR (at least 1.5-fold by Western blot). Falsified if NCS-1 is not elevated. (2) Lithium at 1-10 microM pre-incubation reduces beta-hexosaminidase release from patient-derived mast cells stimulated with MRGPRX2 agonists (compound 48/80, substance P) by 30% or more. Falsified if lithium has no effect or increases release. (3) Lithium effect is graded by pathway dependence on NCS-1: GPCR-mediated degranulation (MRGPRX2 agonists compound 48/80, substance P) is reduced by ≥30%; IgE-mediated degranulation (anti-DNP-IgE + DNP-BSA) is reduced by ≥10% but ≤25% (partial effect). Falsified if the two pathways show identical reduction magnitude or if IgE-mediated reduction exceeds GPCR-mediated reduction — either outcome would indicate a NCS-1-independent mechanism. (4) In MCAS-positive ME/CFS patients, serum tryptase decreases by 20% or more after 4 weeks of lithium 2 mg/day. Falsified if tryptase unchanged. If baseline tryptase is normal (less than 11.5 ng/mL), substitute urine 11beta-PGF2alpha or serum PGD2 (25% or more reduction predicted). Falsified if neither declines. (5) PBMC lithium concentration after 2 mg/day oral dosing reaches 1 microM or more free Li#super[+] by ICP-MS, confirming tissue penetration to the in vitro-effective range. Falsified if steady-state PBMC Li#super[+] is less than 0.5 microM.
] <oq:lithium-mast-cell-ncs1>
Dendritic cells (DCs) are professional antigen-presenting cells that initiate adaptive immune responses. ME/CFS patients show altered DC maturation with abnormal expression of co-stimulatory molecules . Changed cytokine production skews toward pro-inflammatory profiles, while impaired antigen presentation may contribute to inadequate pathogen clearance. Plasmacytoid DCs display abnormalities in type I interferon production .

Petrov et al.\ found that ME/CFS patients show reduced dendritic cell frequency and impaired CCR7 expression on dendritic cells compared to healthy controls, in contrast to long COVID patients who showed dendritic cell expansion with reduced HLA-DR expression (consistent with immune exhaustion) @Petrov2026monocyteDC. This divergence — DC contraction in ME/CFS, DC expansion with exhaustion in long COVID — may reflect distinct pathophysiological processes, though it could equally represent different disease stages (years of illness in ME/CFS vs months in long COVID) rather than fundamentally distinct mechanisms. Reduced peripheral DC frequency could also reflect tissue redistribution rather than systemic depletion. Certainty: 0.50. As with the monocyte findings above, the T cell activation features from the same study caution against a uniform ''immune suppression'' characterization of the DC compartment.

