#import "../../../../../shared/environments.typ": *

#proof[
_Step 1: A positively invariant region exists._ Since $A$ and $I$ represent physical concentrations, the positive quadrant $A gt.eq 0$, $I gt.eq 0$ is preserved by the dynamics (at $A = 0$: $dot(A) = P(0) - beta_0 gt.eq 0$ when $I = 0$; at $I = 0$: $dot(I) = k_upright("act")^upright("eff")(A) dot.op I_0 > 0$ for $A > 0$). For the upper bounds, choose $A_max$ so that $P(A_max) < beta_0$ (guaranteed by PFK-1 product inhibition at high ATP) and let $I_max = k_(upright("act,0")) I_0 \/ (k_upright("exh") + d_a)$ (the $I$-nullcline plateau). Define the trapping region as the set bounded by $I = 0$, $A = A_max$, $I = I_max$, and the $A$-nullcline curve $I = (P(A) - beta_0)\/e_a$ on the left (which lies to the left of the ascending limb and satisfies $dot(A) > 0$ in its interior). On the upper boundary $I = I_max$: $dot(I) < 0$ because immune clearance $(k_upright("exh") + d_a)I$ exceeds activation at the plateau. On $A = A_max$: $dot(A) = P(A_max) - beta_0 - e_a I < 0$. On $I = 0$: $dot(I) > 0$. On the left boundary (the $A$-nullcline curve): by construction $dot(A) = 0$ on this curve and $dot(A) > 0$ immediately to its right, so trajectories cannot exit leftward. This trapping region $cal(R)$ is positively invariant and contains all three fixed points.

_Step 2: Exactly three fixed points._ Fixed points are intersections of the $I$-nullcline and $A$-nullcline. The $I$-nullcline (@eq:i-nullcline) is strictly monotone increasing (derivative always positive for $A > 0$). The $A$-nullcline (@eq:a-nullcline) is unimodal: it has exactly one local maximum (inherited from the unimodal $P(A)$) and is therefore composed of two monotone pieces---an ascending limb and a descending limb. On any interval where both curves are monotone in the same direction, they can intersect at most once (by the monotonicity of their difference). The ascending limb of the $A$-nullcline and the $I$-nullcline are both increasing, giving at most one intersection; the descending limb of the $A$-nullcline intersects the still-increasing $I$-nullcline at most once (again by monotonicity of the difference). A third intersection can occur in the transition region near the peak. Thus at most three intersections total.

The lower bound uses the intermediate value theorem on the difference $h(A) = I_upright("null")^A (A) - I^*(A)$. Near $A = 0$: $P(0) approx 0$ (the production machinery requires some ATP), so $I_upright("null")^A (0) approx -beta_0\/e_a < 0$ while $I^*(0) = 0$, giving $h(0) < 0$. As $A$ increases, $P(A)$ rises (ascending limb of the unimodal production function) and eventually $P(A) - beta_0 > e_a I^*(A)$, making $h > 0$: the $A$-nullcline rises above the $I$-nullcline. By the IVT, at least one crossing occurs on the ascending limb (the disease fixed point). On the descending limb at high $A$, $P(A)$ falls back below $beta_0$ while $I^*(A) > 0$, so $h < 0$ again: at least one crossing on the descending limb (the healthy fixed point). This gives at least two crossings. The third crossing (the saddle) arises when @eq:bistability-inequality holds: the condition ensures that near the peak of the $A$-nullcline, the $A$-nullcline slope exceeds the $I$-nullcline slope, creating a fold where the $I$-nullcline overtakes the $A$-nullcline from below, producing an additional sign change in $h$. Numerical evaluation at the stated ME/CFS parameter values (@app:mathematical-details) confirms that three crossings occur. Combined with the upper bound of three: *exactly three*.

_Step 3: Jacobian and eigenvalue classification._ At each fixed point $(A^*, I^*)$, the Jacobian is:

$ J = mat(P'(A^*), -e_a; display(frac(2 k_(upright("act,0")) I_0 K_upright("ATP")^2 A^*, (K_upright("ATP")^2 + A^(*2))^2)), -(k_upright("exh") + d_a)) equiv mat(f_A, f_I; g_A, g_I) $ <eq:jacobian-2d>

The trace is $tau = f_A + g_I = P'(A^*) - (k_upright("exh") + d_a)$ and the determinant is $Delta = f_A g_I - f_I g_A$. Since $f_I = -e_a < 0$ and $g_A > 0$ for all $A^* > 0$, the cross-coupling term $-f_I g_A = e_a g_A > 0$ always contributes positively to $Delta$.

*Healthy fixed point* $(A_H, I_H)$, on the descending limb of the $A$-nullcline: $P'(A_H) < 0$, so $f_A < 0$. The trace $tau = P'(A_H) - (k_upright("exh") + d_a) < 0$ (both terms negative). The determinant $Delta = |P'(A_H)|(k_upright("exh") + d_a) + e_a g_A > 0$. Negative trace and positive determinant: *stable* (node or spiral).

*Disease fixed point* $(A_D, I_D)$, on the ascending limb of the $A$-nullcline: $P'(A_D) > 0$, so $f_A > 0$. The determinant sign follows from the nullcline crossing geometry. At this intersection, the $I$-nullcline is steeper than the $A$-nullcline (the $I$-nullcline crosses from below as $A$ increases). In terms of Jacobian entries, this means $g_A \/ |g_I| > P'(A_D) \/ e_a$, i.e., $e_a g_A > P'(A_D)(k_upright("exh") + d_a)$, ensuring $Delta > 0$. For the trace: $tau = P'(A_D) - (k_upright("exh") + d_a) < 0$ requires $P'(A_D) < k_upright("exh") + d_a$. Both quantities have units of (time)$""^(-1)$ in the non-dimensionalised system. This condition holds when $A_D$ lies in the region where the ascending slope of $P$ is moderate, which is the case for the stated ME/CFS parameter values (verified numerically in @app:mathematical-details). Negative trace and positive determinant: *stable* (node or spiral).

*Saddle point* $(A_s, I_s)$, near the peak of the $A$-nullcline: here the $I$-nullcline is _less steep_ than the $A$-nullcline (the $A$-nullcline crosses the $I$-nullcline from below as $A$ increases---the opposite crossing direction). This gives $P'(A_s) \/ e_a > g_A \/ (k_upright("exh") + d_a)$, so $P'(A_s)(k_upright("exh") + d_a) > e_a g_A$, making $Delta = -P'(A_s)(k_upright("exh") + d_a) + e_a g_A < 0$. Negative determinant: eigenvalues have opposite signs, confirming an *unstable saddle*.

_Step 4: Index theory consistency._ By the planar fixed-point index theorem applied to the trapping region $cal(R)$ (Step 1), the sum of indices of all interior fixed points must equal $+1$. Stable nodes/spirals have index $+1$; saddles have index $-1$. Three fixed points with indices $+1, -1, +1$ sum to $+1$. $checkmark$
]
