#import "../../../shared/environments.typ": *

#speculation(title: [Passive Heat Therapy: Unvalidated Clinical Observation])[
*(Certainty: 0.35.)* Two small uncontrolled pilot studies reported that passive heat therapy may be tolerated in ME/CFS: Soejima et al. (n=10, 5×/week × 4 weeks, Waon far-infrared sauna 60°C, 15 min) reported reduced fatigue (p < 0.05) and improved mood in an uncontrolled, unblinded design — results that cannot distinguish treatment effect from placebo, regression to the mean, or Hawthorne effect @Soejima2015WaonTherapyCFS. Separately, Hochecker et al. (2025, n=9, within-subject pre-post, single center, unreplicated) reported cellular-level effects: whole-body hyperthermia (WBH, core temperature 39°C) reduced autophagy marker LC3-II by 17.84% (p=0.0065) and increased mitochondrial respiration (basal +66.60%, ATP +61.41%, maximal +97.88%, spare capacity +112.35%) in PBMCs @Hochecker2025HyperthermiaMECFS — a study with no clinical outcome measures. Whether these two observations are causally connected (cellular improvement → clinical benefit) is unknown; they may represent independent phenomena. Both studies are small, uncontrolled, from single centers, and unreplicated.

*Critical caveat — NOT a clinical recommendation:* Both studies are small (n=9–10), uncontrolled, and unreplicated. Some patients in the Hochecker study could not tolerate the full WBH protocol, confirming that heat intolerance limits feasibility. Heat therapy is a research direction only. Any thermal protocol would need to be individually titrated in a clinical trial setting, beginning with brief partial-body exposures, and immediately discontinued at any PEM signal. The risk-benefit ratio for clinical use is unknown.

*Falsifiable prediction:* A controlled crossover trial of Waon therapy (15 min, 60°C, 3×/week × 4 weeks) vs. thermoneutral rest in ME/CFS patients (n ≥ 30) will show significant improvement in fatigue (FSS) and mitochondrial respiration (Seahorse) with no increase in PEM incidence vs control.

*Limitations:* Both studies uncontrolled, unblinded, small samples. Hochecker measured only immediate cellular effects, no clinical outcomes. Soejima showed clinical benefit but had no control group. Not replicated. HSAT2 caution applies (ch17:@spec:heat-hsat2-caution): heat-shock factor 1 (HSF1) activation may amplify exosomal HSAT2 in susceptible patients.
] <spec:controlled-heat-paradox>
