#import "../../../../../shared/environments.typ": *

#open-question(title: [Is Peripheral Serotonin Depletion Causal, Epiphenomenal, or an Assay Artifact?])[
*Null hypothesis:* Peripheral serotonin depletion is either (a) an epiphenomenon of chronic inflammation — low serotonin reflects ongoing immune activation rather than contributing to pathophysiology; (b) a dietary artefact — ME/CFS-related dietary changes (restricted eating, altered food choices) reduce tryptophan intake; (c) a measurement artefact — platelet serotonin assays are technically demanding and lack standardisation (@anderson2024serotonin); (d) relevant only to the POTS/orthostatic intolerance subset, not to ME/CFS broadly; or (e) a structural parallel to the failed serotonin hypothesis of depression — the attribution of a complex multi-system disease to a single biochemical deficit (low serotonin), following the same reasoning architecture that dominated psychiatry for decades before being debunked. The serotonin hypothesis of depression proposed that depression resulted from low brain serotonin, survived for decades on the strength of its explanatory breadth (it "explained" diverse symptoms from a single molecular deficit), and collapsed when large-scale evidence showed no consistent serotonin deficit and no depletion-repletion causality. The peripheral serotonin hypothesis in ME/CFS attributes mitochondrial dysfunction, autonomic failure, immune dysregulation, gastrointestinal symptoms, and pain amplification to a single molecule — the same structural formula. The hypothesis may be correct (peripheral serotonin is genuinely pleiotropic in ways brain serotonin is not), but the historical failure mode is close enough to warrant explicit acknowledgment. (Origin: brainstorm + adversarial review)

*What would falsify the peripheral serotonin hypothesis:*
- A large (n≥200) controlled study finding no difference in platelet serotonin between ME/CFS patients and matched controls after adjusting for diet, medications, and circadian timing
- Interventional trials showing that serotonin restoration (via 5-HTP/butyrate) improves serotonin levels without improving symptoms
- Demonstration that platelet serotonin levels are fully explained by dietary tryptophan intake and inflammation markers, with zero independent association with symptom severity after adjustment

*What would support it:*
- Demonstration of a dose-response relationship: lower platelet serotonin → more severe symptoms across multiple domains (fatigue, orthostatic intolerance, cognitive dysfunction)
- Successful intervention: serotonin restoration → clinically meaningful symptom improvement in a randomised controlled trial
- Evidence that low platelet serotonin predicts PEM independently of baseline inflammation markers

*Current equipoise:* The evidence base is converging but not established. Multiple studies document serotonin pathway abnormalities, primarily in Long COVID and POTS rather than ME/CFS directly (ME/CFS-specific: Raij & Raij 2024, @raij2024serotonin, n=38; Che et al. 2025 @che2025innate, tryptophan diversion multi-omics), but none provide interventional evidence, none control for dietary tryptophan, and the largest ME/CFS-specific serotonin measurement has n=38. The hypothesis merits serious investigation but does not yet meet the standard for clinical action beyond mechanistic caution (SSRI caution in ME/CFS patients with confirmed POTS comorbidity — not a general ME/CFS SSRI contraindication).

*Consequence:* Until the null hypothesis is tested, peripheral serotonin depletion remains an attractive but unvalidated mechanistic model. It would be a mistake to build clinical protocols on this hypothesis without interventional data. For researchers, the priority is a properly controlled platelet serotonin measurement study in a large, well-characterised ME/CFS cohort with dietary, medication, and circadian controls. For patients, the SSRI caution applies only to those with confirmed POTS — most ME/CFS patients should continue standard psychiatric prescribing unchanged. (Origin: brainstorm)
] <oq:serotonin-null-hypothesis>
