#import "../../../../shared/environments.typ": *

=== Parallel Cardiovascular Findings


Long COVID patients demonstrate cardiovascular abnormalities closely mirroring those documented in ME/CFS, including POTS (affecting 30–50% of Long COVID patients with persistent symptoms), reduced exercise capacity on CPET with similar patterns of reduced VO#sub[2]peak and early anaerobic threshold, autonomic dysfunction with altered HRV and baroreflex sensitivity, and endothelial dysfunction with impaired flow-mediated dilation @Devigili2023SFN.

Small fiber neuropathy has been documented in both conditions using identical methodologies. Azcue et al.\ found that ME/CFS and post-COVID patients showed comparable patterns of heat response latencies indicating C-fiber denervation @Azcue2023sfn. The non-length-dependent pattern observed in both conditions suggests autoimmune or inflammatory etiology rather than metabolic neuropathy.

A 2026 study extended these findings from somatic to visceral autonomic fibers. Acanfora et al.\ performed gastric mucosal biopsies (fundus and antrum) in 12 Long COVID patients and 8 dyspeptic controls, quantifying nerve fiber density by 3D reconstruction of PGP 9.5 (pan-neuronal) and vasoactive intestinal peptide (VIP, a cholinergic marker) immunostaining @acanfora2026vagaldenervation. Long COVID patients showed significantly reduced mucosal innervation (fundus PGP 2.1 vs 3.9 nm/µm#super[3], $p<0.01$; antrum 1.9 vs 3.9, $p<0.05$), with a disproportionate loss of VIP-positive cholinergic fibers, most marked in the fundus. Crucially, intraepidermal nerve fiber density (skin) did *not* differ between groups, indicating that the denervation was *selectively visceral* rather than a generalized small fiber neuropathy. Gastric nerve density correlated with autonomic function (HRV LF/HF ratio $R=0.50$, $p<0.05$) and with cardiovascular-stress biomarkers (NT-proBNP $R=0.52$; D-dimer $R=0.61$); these are modest correlations on $n=12$ ($r^2 approx 0.25$–$0.37$, leaving most of the variance unexplained and consistent with many drivers of HRV and coagulation beyond nerve density), so they are best read as hypothesis-generating rather than as evidence of a tight mechanistic link. Two confounds further limit interpretation: the finding cannot distinguish vagal from enteric fibers, and deconditioning — near-universal in Long COVID — can itself reduce both HRV and, plausibly, mucosal innervation, so the denervation could be a consequence rather than a cause of the illness state. The dyspeptic control group is also a limitation: functional-dyspepsia patients may have altered baseline gastric innervation, leaving the direction of any comparison bias unknown. Whether any of this holds in ME/CFS has not been tested.

#clinical-finding(title: [First In Vivo Report of Structural Vagal Cholinergic Denervation in Long COVID (Single Unreplicated Study)])[
*Certainty: 0.45.* *Evidence type: single observational case–control study ($n=12$ vs $8$), not replicated.* Acanfora et al.\ @acanfora2026vagaldenervation report the first in vivo morphological observation that autonomic dysfunction in Long COVID may reflect an underlying structural lesion — selective loss of cholinergic (VIP+) nerve fibers in the gastric mucosa, sparing somatic skin fibers — with nerve density correlating with HRV vagal indices ($R=0.50$). This is a preliminary finding, not a settled result: certainty is held at 0.45 by the small single-center sample, dyspeptic (not healthy) controls, no recovered-asymptomatic COVID group, the inability to distinguish extrinsic vagal from intrinsic enteric fibers, the deconditioning confound, and the absence of independent replication. It has *never been demonstrated in ME/CFS*. It could be complementary to — or, alternatively, made redundant by — the *functional* CAP-blockade model proposed for GPCR autoantibodies (Chapter @ch:integrative-models, Speculation @spec:cap-autoantibody-blockade): one describes structural fiber loss, the other antibody-mediated signaling interference, and current evidence cannot establish that both (or either) operate in ME/CFS.

*Consequence:* If post-viral illness can physically destroy vagal nerve fibers (not just impair their signaling), this points toward a potentially harder-to-reverse form of autonomic damage; the distinction between structural fiber loss and reversible functional impairment is worth testing directly rather than assuming, because it bears on whether autonomic dysfunction should be treated early — but this is a Long COVID finding from one small unreplicated study, and whether the same structural loss occurs in ME/CFS remains an open and testable question.
] <ach:vagal-structural-denervation>


