#import "../../../../shared/environments.typ": *

=== Healthy Baseline and Branch Point (@eq:headroom and @eq:branch-point)

*Measurements required.* (1) Peak VO₂ and anaerobic threshold from CPET in both patients and age-matched healthy controls (why: constrains $J_(upright("production,max"))$ and enables computation of $R_(upright("headroom"))$). (2) Pre- and post-exercise mtDNA copy number at 24, 48, and 72 hours in both groups (why: directly tests $Delta M_h^(upright("net")) > 0$ in health vs. $Delta M_h^(upright("net")) < 0$ in ME/CFS). (3) Post-exercise PGC-1$alpha$ and AMPK phosphorylation in PBMCs (why: distinguishes between adequate AMPK signaling with $"NAD"^"+"$ bottleneck vs. upstream signaling failure). (4) DOMS severity and timeline via VAS in healthy controls performing eccentric exercise (why: validates the local inflammatory model timeline, @eq:doms-inflammation).

*Worked example.* A healthy individual with peak VO₂ = 35 mL/kg/min performs moderate exercise at 60% peak ($J_(upright("demand,peak")) = 0.6 dot.op J_(upright("production,max"))$). Headroom ratio: $R_(upright("headroom")) = (1 - 0.6) = 0.40$. At $alpha_(upright("CI")) = 1.0$, the ROS production factor is $(1 - 0.95) = 0.05$ (5% electron leak), well within buffering: $[upright("ROS")] < upright("ROS")_(upright("threshold"))$, $D(t) = D_0$ (no damage). Over the next 72 hours, $J_(upright("biogenesis"))$ rises (AMPK-driven) while $r_(upright("damage"))$ remains at baseline, yielding $Delta M_h^(upright("net")) > 0$: supercompensation.

Now consider a moderate ME/CFS patient with peak VO₂ = 25 mL/kg/min performing the same absolute workload. Because $J_(upright("production,max"))$ is reduced ($alpha_(upright("CI")) = 0.70$), this exercise represents 85% of capacity: $R_(upright("headroom")) = 0.15$. The ROS factor is $(1 - 0.70) = 0.30$, exceeding the threshold. Over 72 hours: $D(t) > D_0$ (cumulative damage), biogenesis is impaired ($"NAD"^"+"$ depleted, $gamma = 0.75$), and $Delta M_h^(upright("net")) < 0$: anti-supercompensation. The same absolute effort that improves the healthy individual worsens the patient.

*Inter-model dependencies.* _Inputs_: $J_(upright("production,max"))$ from ETC model, $alpha_(upright("CI"))$ from mitochondrial dysfunction parameters, ROS threshold from antioxidant model. _Outputs_: $R_(upright("headroom"))$ determines PEM triggering (@sec:pem-modeling), $Delta M_h^(upright("net"))$ sign feeds long-term trajectories (@ch:temporal-evolution), branch point informs pacing optimization (@ch:predictive-applications).

*Scope and rationale.* The healthy baseline model serves two roles: face validation (reproducing known exercise physiology timescales from the same equations used for ME/CFS) and branch-point identification (the critical $R_(upright("headroom"))$ below which adaptation becomes damage). It deliberately simplifies DOMS to its inflammatory timeline and omits the full complexity of exercise training adaptation (periodization, fiber-type specificity, neural adaptation) to focus on the metabolic branch point relevant to ME/CFS.

*Falsification criteria.* *Falsified if*: (1) the model with healthy parameters fails to reproduce the known 48--96 hour supercompensation timescale (would indicate that the biogenesis ODE timescale is miscalibrated); (2) ME/CFS patients show _positive_ $Delta M_h^(upright("net"))$ after standardized exertion (mtDNA copy number rises at 72 hours), indicating that supercompensation failure is not a feature of the disease; or (3) the branch point cannot be identified as a function of $R_(upright("headroom"))$---i.e., patients with high and low headroom show the same post-exertional response, refuting the threshold model.

*Clinical implications.* The branch-point analysis quantifies the minimum $R_(upright("headroom"))$ required for exertion to be adaptive rather than damaging. This provides a patient-specific _safe exercise threshold_: the intensity level below which the exertion response resembles healthy adaptation rather than PEM. Clinicians can estimate $R_(upright("headroom"))$ from CPET data and prescribe activity levels that stay above $R_(upright("crit"))$, potentially enabling limited exercise training in patients with sufficient reserve while protecting those without it. The model predicts that interventions increasing $J_(upright("production,max"))$ (e.g., CoQ10, $"NAD"^"+"$ precursors) would raise $R_(upright("headroom"))$ and potentially restore the supercompensation response before improving exercise tolerance directly.

