#import "../../../../shared/environments.typ": *

=== Objective Documentation of Circadian Disruption
<obs:circadian-disruption>
Cambras et al.\ (2018) employed rigorous actigraphy monitoring to objectively document circadian rhythm abnormalities in ME/CFS patients @cambras2018circadian. This case-control study of 10 women with ME/CFS and 10 matched controls revealed that daily activity levels were significantly lower in ME/CFS patients, relative amplitude of the activity rhythm (difference between peak and nadir) was reduced, indicating flattened circadian variation, and stability of the activity rhythm across days was decreased, showing less consistent day-to-day patterns. Additionally, distal skin temperature showed lower nocturnal values in winter, suggesting impaired circadian regulation of peripheral blood flow and thermoregulation.

Subsequent work by the same group (Cambras et al., 2023) demonstrated that skin temperature circadian rhythm alterations in ME/CFS are significantly associated with endothelin-1 (ET-1) levels ($p < 0.01$), linking thermoregulatory circadian disruption to vascular tone dysregulation @Cambras2023SkinTemperatureEndothelin. ET-1 is a potent vasoconstrictor peptide; its association with temperature rhythm stability and amplitude suggests that the circadian control of vascular tone — not just central hypothalamic clock output — is disrupted in ME/CFS. Self-reported symptom severity correlated with both ET-1 levels and temperature rhythm disruption, providing a direct link between vascular biomarker, circadian physiology, and patient-experienced symptoms.
These findings demonstrate that circadian disruption in ME/CFS is not merely subjective patient reports of “feeling tired at the wrong times” but rather represents measurable alterations in the fundamental 24-hour organization of physiological functions. The reduced amplitude of activity rhythms parallels the flattened cortisol rhythm discussed earlier, suggesting a coordinated loss of circadian regulation across multiple output systems.

