#import "../../../../../shared/environments.typ": *

#achievement(title: [Neuronal Protein Tracing Reveals Physiological Brain Clearance Architecture])[
Chayama et al.\ (2026) developed a genetic system (Syn-ZsG) to trace neuron-derived protein clearance from the brain to border tissues without the pressure-driven artefacts of conventional CSF tracer injections. By expressing a fluorescent reporter (ZsGreen) selectively in neurons and tracking its distribution across brain border compartments, they revealed that physiological clearance follows a fundamentally different architecture from what CSF-injected tracers suggest @Chayama2026BrainClearance.

Key findings:
- *Distinct routes from CSF tracers.* Neuron-derived proteins drain primarily to dura, skull, and nasal cavity --- with relatively low levels in superficial and deep cervical lymph nodes. By contrast, CSF-injected tracers (OVA) concentrate in cervical lymph nodes, bypassing the brain itself. This was validated using biorthogonal labeling of endogenous neuronal proteomes (Syn-PheRS), confirming that the ZsGreen distribution reflects native protein handling, not reporter artefact @Chayama2026BrainClearance.
- *Compartmentalized clearance follows a "nearest exit" principle.* By restricting ZsGreen expression to specific brain regions (forebrain, striatum, anterior olfactory), the authors demonstrated that clearance is spatially organized: proteins from each region drain preferentially to the nearest border compartment. Dorsal cortical proteins exit through dorsal dura and skull; striatal proteins drain via basal skull and nasal cavity. This implies that different brain regions have different rates of waste clearance and different failure modes in disease.
- *Border-specific clearance kinetics.* Pulse-chase experiments revealed that skull-associated borders exhibit slow outflow ($k = -0.008$), while dura, nasal cavity, and cribriform plate show rapid turnover ($k = 0.127--0.261$). Slow skull kinetics may facilitate prolonged antigen retention and immune surveillance.
- *Skull-resident B cells surveil brain antigens for immune tolerance.* Transcriptomic analysis revealed that skull B cells that sample neuronal proteins upregulate antigen processing and presentation pathways alongside tolerogenic markers (PD-L1, IL10ra, Cd1d1, Zbtb20, Ptpn22) while downregulating pro-inflammatory genes (Tnf, Il1b, type I interferon signaling). This "tolerogenic-presentation" profile suggests that skull marrow serves as a neuroimmune checkpoint --- sampling brain-derived antigens and actively suppressing inflammatory responses against them. PD-L1 protein levels were confirmed elevated on ZsGreen+ skull B cells by quantitative immunostaining.
- *Disease disrupts clearance through distinct mechanisms.* Acute inflammation (LPS) shunted neuronal proteins away from homeostatic border drainage pathways into the bloodstream via vascular leakage. By contrast, amyloid pathology (5XFAD) caused parenchymal retention and border exit obstruction --- proteins accumulated in the brain and failed to reach borders, reducing peripheral clearance. These two failure modes --- rerouting vs.\ obstruction --- have fundamentally different consequences for neuroimmune surveillance and peripheral antigen exposure @Chayama2026BrainClearance.

These findings redefine brain clearance as a compartmentalized system of organized pathways and immune niches whose dysfunction may underlie regional vulnerability in neurological disease.

(Certainty: 0.85 for the methodology and foundational mechanisms in mice. Published in Cell, July 2026, rigorous experimental design with multiple validation approaches. No direct human data beyond conservation of meningeal lymphatics between rodents and humans; precise anatomical flow patterns may differ in primates. No ME/CFS models tested.)
] <ach:ch15-brain-clearance-architecture>
