#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Dedicated Sickness and Torpor Neural Circuits as a Symptom-Generating Pathway])[
The sickness behavior driving many ME/CFS symptoms is not an unspecific diffuse response but is orchestrated by _dedicated, recently identified neural circuits_ that generate stereotyped symptom bundles when activated by neuroinflammation @KomaroffDantzer2025SymptomPersistence. In rodents, three such circuits have been mapped: a circuit originating in the area postrema and projecting to the brainstem that suppresses eating, drinking, and movement (sickness behavior); a circuit from the organum vasculosum of the lamina terminalis to the ventromedial preoptic area that produces appetite suppression, warmth seeking, and fever; and a circuit centered on the median preoptic nucleus that can induce a torpor-like hypometabolic state, sharply reducing ATP-generating metabolism @Hrvatin2020TorporNeurons @KomaroffDantzer2025SymptomPersistence. Preoptic EP3-receptor neurons may act as a two-way switch routing the organism between protective fever (hypermetabolic) and torpor (hypometabolic) states @Machado2025PreopticSwitch. Applied to ME/CFS: activation of these circuits by neuroinflammation would generate the core symptoms (fatigue, cognitive slowing, malaise) and, if the switch fails to disengage, produce a chronically low-metabolic, energy-conserving state that overlaps the metabolic-safety-mode and CNS energy crisis models (Sections @sec:root-safe-mode, @sec:cns-energy-crisis). (Certainty: 0.45. The circuits are well established in rodents; the application to chronic human ME/CFS is inferential — see translation gap below. Raw certainty 0.62 for the rodent circuit findings @Hrvatin2020TorporNeurons @Machado2025PreopticSwitch, discounted by the cross-species gap to 0.31; the review-level integration @KomaroffDantzer2025SymptomPersistence supports 0.45 as a working hypothesis.)

(Translation gap: animal (rodent) → human. The dedicated circuits and two-way preoptic switch were demonstrated in mice/rats; their chronic engagement in ME/CFS is not yet directly evidenced in patients.)

*Falsifiable prediction:* If a dedicated sickness/torpor circuit partly generates ME/CFS fatigue and post-exertional malaise, then neuroinflammation-sensitive functional imaging (e.g., TSPO-PET or task-based fMRI) of the area postrema, ventromedial preoptic area, and median preoptic nucleus should track symptom severity and rise with post-exertional provocation; and experimental interventions that quell neuroinflammation should simultaneously reduce both the circuit activation and the corresponding symptoms. Absence of any circuit-specific imaging change with symptoms would falsify the claim that a dedicated circuit (rather than diffuse inflammation) mediates the symptoms.

(Severity applicability: unknown — the review does not stratify by severity; the neural-circuit model is presented as general to ME/CFS/long COVID across severity levels.)

*Consequence:* If confirmed, this reframes ME/CFS fatigue and brain fog as the output of specific, conserved brain circuits switched on by brain inflammation — giving researchers and drug developers a concrete neural target (quelling the neuroinflammation that drives the circuits) rather than treating symptoms piecemeal.
] <hyp:ch15-sickness-torpor-circuits>
