#import "../../../../shared/environments.typ": *

=== Why Deconditioning Fails as a Primary Explanation

Multiple lines of evidence demonstrate that deconditioning cannot account for the core pathophysiology of ME/CFS:
    - *Post-exertional malaise is the hallmark feature.* Deconditioned individuals improve with progressive exercise; ME/CFS patients deteriorate. Two-day CPET protocols show reproducible day-2 performance decline in ME/CFS but not in sedentary controls or patients with other fatiguing conditions in positive studies @keller2024cpet @Lim2020, though a 2026 null replication did not find group-average VO₂ decline @Mancini2026CPET; elevated RPE and chronotropic incompetence are consistent findings across studies.
    - *VO#sub[2]peak reduction exceeds deconditioning predictions.* The NIH deep phenotyping study documented exercise impairment beyond what inactivity alone would produce, even in patients with relatively preserved activity levels @walitt2024deep. Walitt et al.\ themselves acknowledged that deconditioning is a consequence, not a cause, and that equal maximum grip strength argues against pure deconditioning.
    - *Metabolic dysfunction is cellular, not peripheral.* Impaired mitochondrial function in immune cells @Mandarano2020 and abnormal metabolite profiles persist independently of activity levels (Chapter @ch:energy-metabolism).
    - *Autonomic and immune abnormalities are independent of fitness.* Chronotropic incompetence, catecholamine deficiency @walitt2024deep, T cell exhaustion, and NK cell dysfunction are documented in ME/CFS. Chronotropic incompetence can also result from deconditioning — its presence does not discriminate between the two models — but its co-occurrence with catecholamine deficiency and immune abnormalities supports a multisystem pathology beyond deconditioning alone.
    - *GET produces harm, not recovery.* Large self-reported patient surveys report that 51% of ME/CFS patients worsened with GET @Kindlon2011GET. NICE withdrew GET from its 2021 guidelines, declaring it potentially harmful @NICE2021mecfs.
Charlton et al.\ (2026), writing in the _British Journal of Sports Medicine_, directly addressed the deconditioning narrative in the context of long COVID @Charlton2026pem. Their editorial—co-authored by Systrom (pioneer of invasive CPET demonstrating preload failure in ME/CFS) and Putrino (leading long COVID researcher at Mount Sinai)—argued that post-exertional malaise cannot be explained by cardiac deconditioning and called for rethinking the pathophysiology of exercise intolerance in post-viral illness. The publication of this argument in a mainstream sports medicine journal marks a significant shift: the deconditioning myth is now being challenged from within the exercise science community itself, not only by ME/CFS specialists and patient advocates.


