#import "../../../../../shared/environments.typ": *

#speculation(title: [Skull Bone Marrow Channel Density as a Structural Biomarker of ME/CFS Clearance Stage])[
*Certainty: 0.20.* Chayama et al.\ (2026) show that skull borders are the slowest clearance compartment ($k = -0.008$) and that skull-resident B cells maintain tolerogenic neuroimmune surveillance @Chayama2026BrainClearance. Skull bone marrow channels --- direct vascular connections between the skull marrow and the brain surface --- are the anatomical substrate for this surveillance and may remodel in disease. Eme-Scolan et al.\ (2026) demonstrated that neuroinflammation remodels skull channels to increase immune cell trafficking. 

In ME/CFS, two opposing remodeling forces may operate at different disease stages. Early disease (less than 2 years): neuroinflammation-driven channel expansion increases drainage capacity as a compensatory response to impaired clearance. Late disease (more than 10 years): perivascular fibrosis and structural degradation (Section @sec:ch15-glymphatic, ~70× recovery timescale) narrow skull channels, reducing both clearance capacity and immune surveillance. High-resolution CT or MRI quantitative channel metrics (channel density, mean diameter, total channel volume) could serve as a structural biomarker distinguishing early (compensatory) from late (decompensated) disease stages, with implications for treatment selection: vasodilatory/anti-inflammatory strategies in dilated-channel early disease, anti-fibrotic/clearance-enhancing strategies in narrowed-channel late disease.

*Falsifiable prediction:* HRCT-measured skull channel density should be elevated in early ME/CFS (less than 2 years, neuroinflammation-driven) and reduced in late ME/CFS (more than 10 years, fibrosis-driven) vs.\ age-matched controls. Channel density should correlate inversely with CSF neuronal protein accumulation (r less than $-$0.4) and directly with sleep architecture quality (SWS percentage, r greater than 0.4). A null correlation between channel density and any ME/CFS parameter would refute the structural biomarker hypothesis.

*Limitations:* No human skull channel remodeling data in ME/CFS. Eme-Scolan et al.\ is a mouse neuroinflammation study. Skull channel imaging methodology is not clinically validated. The compensatory→decompensated transition is entirely hypothetical. Channel density may vary with age, sex, and vascular risk factors unrelated to ME/CFS.
] <spec:ch15-skull-channel-biomarker>
