#import "../../../../shared/environments.typ": *

=== Other Immune Modulators

Several other immunomodulatory approaches have been tested in ME/CFS:
    - *Intravenous immunoglobulin (IVIG)*: Three RCTs in the 1990s produced mixed results. Lloyd et al.\ (1990, n=49) showed improvement; Vollmer-Conna et al.\ (1997, n=99) showed no benefit. A subset of patients—particularly those with documented immunoglobulin deficiency—may respond. High cost and limited availability restrict use
    - *Interferon-alpha*: Small studies showed modest benefit in a subgroup of patients with documented viral reactivation. Side effects (flu-like symptoms, fatigue, depression) limit tolerability in a population already suffering these symptoms
    - *Rintatolimod (Ampligen)*: A double-stranded RNA drug with immunomodulatory and antiviral properties. The largest ME/CFS-specific RCT (n=234) showed significant improvement in exercise tolerance (treadmill duration) but the FDA declined approval due to concerns about effect size and adverse event profile. Available on a cost-recovery basis in some countries
    - *Immunoadsorption*: Removal of circulating autoantibodies via extracorporeal adsorption. The Charité Berlin group progressed from a pilot (n=10, 70% rapid improvement @Scheibenbogen2018immunoadsorption), through repeat-treatment feasibility (n=5, 4/5 sustained benefit @Tolle2020immunoadsorption), to a prospective cohort (n=20, 70% responders, benefits sustained to 6 months @Stein2024immunoadsorption). Azcue et al.\ (2026) provide the strongest quantitative correlation data supporting the biological rationale for immunoadsorption: $beta_2$-adrenergic AAb titers correlate with sympathovagal imbalance in ME/CFS ($r=0.45$, $p=0.001$, $n=59$) @Azcue2026gpcr --- though whether this correlation reflects pathogenic AAbs or non-specific ELISA binding remains unresolved (Germain 2025 REAP/Luminex null @Germain2025autoantibody). An independent-centre study from Herne/Bochum (n=12 @Anft2025immunoadsorption) found autoantibodies eliminated and cytokines reduced but ME/CFS symptom scores not significantly improved, with rebound within one month—introducing uncertainty about the sufficiency of autoantibody removal alone. *Preliminary sham-controlled results (May 2026)*: IA-PACS-CFS (n=65, Charité @Pressler2024IAPACSCFSprotocol) found no statistically significant difference between immunoadsorption and sham groups on the Chalder Fatigue Scale at 60 days @Rucker2026WirthScheibenbogen. Criticism emerged that the trial did not specifically recruit antibody-positive patients, potentially diluting treatment effect. A concurrent Charité case series of 15 antibody-positive patients showed 7 responders, though this lacked a control group. EXTINCT (n=63, Hannover @EXTINCTtrial2023) and University Medical Center Mainz trial (n=40 Long COVID patients) have completed but results not yet released as of May 2026 @Rucker2026WirthScheibenbogen. The IMPACT trial (n=50, Charité @IMPACTtrial2026), recruiting since March 2026, will systematically measure memory B-cell dynamics after IA, and Scheibenbogen's group is preparing trials of beta-cell-targeting drugs to prevent renewed autoantibody production (addressing the rebound problem) @Rucker2026WirthScheibenbogen


