#import "../../../../../shared/environments.typ": *

#hypothesis(title: [AhR-Gut-Microbiome Axis: Tryptophan-Derived Ligands Modulate Intestinal Barrier and Immune Tone])[
The aryl-hydrocarbon receptor (AhR) is a ligand-activated transcription factor that senses gut-microbial tryptophan and indole metabolites (indole-3-acetic acid, indole-3-propionic acid, indole-3-aldehyde, tryptamine) as well as kynurenine-pathway metabolites @Rothhammer2019AhRImmunity @TorrelliDiljohn2026TryptophanSignaling. When activated by these endogenous ligands, AhR drives differentiation of regulatory and barrier-supporting immune cells (IL-22-producing type-3 innate lymphoid cells and IL-17/IL-22 gamma-delta T cells), reinforces the intestinal epithelial barrier, and restrains excessive Th17-driven inflammation @Rothhammer2019AhRImmunity @Thirugnanam2026DietaryIndolesAhR. In ME/CFS, disrupted indole derivative production has been documented, and elevated AhR agonist activity is specifically associated with neurocognitive symptoms rather than uniform hyperactivation across the whole population @Esteban2026AhRGutMicrobiome @Chojnacki2025IBSCFSTryptophan. The hypothesis: an altered gut-microbial tryptophan/indole/kynurenine ligand balance shifts AhR signaling in ME/CFS, contributing to impaired intestinal-barrier integrity and systemic immune dysregulation, most prominently in patients with neurocognitive symptoms.

*Falsifiable Prediction:* ME/CFS patients with neurocognitive symptoms should show elevated stool or plasma AhR-agonist activity and altered tryptophan-derived indole metabolites compared with non-cognitively-affected ME/CFS and healthy controls, and this elevation should correlate with objective cognitive-test performance and intestinal-permeability markers; the association should be absent or attenuated in ME/CFS without neurocognitive symptoms. Falsified if AhR-agonist activity does not track the neurocognitive subgroup or if it fails to correlate with barrier or immune readouts.

*Consequence:* If confirmed, this would make gut-microbial tryptophan metabolism and AhR signaling a shared upstream mechanism for both the intestinal and cognitive features of ME/CFS, pointing toward dietary or microbial interventions that restore a neuroprotective (transient) rather than neurotoxic (sustained) AhR ligand balance — though no such intervention is established for ME/CFS today.

(Raw certainty: 0.70, Esteban2026 ME/CFS direct, but subgroup-only and single study → discounted to 0.40 for a ME/CFS-specific mechanistic claim; no direct immune-readout studies in ME/CFS. Severity applicability: unknown — anchor study not stratified by severity.)
] <hyp:ahr-gut-microbiome-axis>
