#import "../../../../../shared/environments.typ": *

#speculation(title: [Longitudinal Symptom Stability Is Symptom-Specific: A Stable Fatigue Core with a Labile Emotional Component])[
BioMapAI's 3–4 year longitudinal data indicated that ME/CFS symptoms do not behave uniformly over time: fatigue was persistently and consistently severe across years, whereas emotional dysregulation was highly variable and unstable @Xiong2025BioMapAI. *A primary non-biological alternative must be stated first:* this pattern may be a measurement artifact. Fatigue is typically scored on a coarse ordinal scale that, in severe ME/CFS cohorts, sits near its ceiling — a scale at ceiling cannot fluctuate downward or upward much, so "stability" may reflect a ceiling effect, whereas emotional-symptom items have headroom in-range and therefore look more variable. The apparent decoupling could be psychometric (item wording, scale range, floor/ceiling) rather than two distinct biologies, and it is compounded by symptom-circularity (the fatigue score is partly the diagnosis itself).

If the pattern were to survive that artifact check, it would *then* suggest different biological timescales: a relatively fixed, stable driver for fatigue (e.g., a chronic metabolic or neuroimmune deficit) versus a more labile driver for emotional symptoms (e.g., fluctuating gut-metabolic state, autonomic reactivity, or state-dependent inflammatory tone). Both readings are hypotheses; the biological one is contingent on excluding the measurement one.

The methodological implication is that longitudinal sampling is needed to characterize the labile domain, and that "emotional instability" should not be conflated with the stable energy deficit. This is a study-design point, not a clinical-assessment claim.

Certainty: 0.25 — the temporal pattern is reported by the model's single US cohort, but it has not been independently replicated, and the measurement-artifact explanation (scale ceiling/coarseness, symptom-circularity) has not been excluded. Severity applicability: unknown — cohort not severity-stratified.

*Falsifiable prediction:* In a prospective longitudinal ME/CFS cohort with serial symptom scoring (e.g., monthly) over 12+ months *using continuous, range-normalized fatigue and emotional scales* (adequate headroom, no ceiling): test-retest stability (intraclass correlation over time) should be significantly higher for fatigue than for emotional items even after controlling for scale range; and a stable biological measure (e.g., a metabolomic or resting-blood marker) should correlate significantly more strongly with the time-stable fatigue score than with the fluctuating emotional score. If, after range normalization, fatigue is as labile as emotional symptoms (or if the stability vanishes under scale control), the "stable fatigue core" claim is falsified as a biological finding.

*Consequence:* If the stable-core/labile-shell pattern is real *and* survives the measurement-artifact check, it would shape trial design — supporting sparse serial sampling for the stable fatigue endpoint at the group level, with emotional symptoms requiring longitudinal capture — and would reframe "emotional symptoms in ME/CFS" as possibly a distinct, fluctuating physiology rather than a fixed psychological overlay. It is not a basis for single-visit clinical assessment of an individual patient, whose trajectory no group-level stability coefficient can certify.
] <spec:longitudinal-symptom-specific-stability>
