#import "../../../../shared/environments.typ": *

==== Menstrual Cycle as Endogenous Pharmacodiagnostic Probe <sec:menstrual-cycle-endogenous-probe>

*Applicability:* Premenopausal patients with regular, ovulation-confirmed menstrual cycles who are not on continuous hormonal contraception. Excludes postmenopausal, amenorrhoeic, and hormonally-suppressed patients. For severe/very-severe patients, daily symptom tracking is itself a cognitive exertion burden — consider reduced-frequency tracking or caregiver-assisted documentation. The entire framework in this subsection is hypothesis-generating only; no element has been validated in a prospective ME/CFS trial.

Beyond the spontaneous symptom patterns described in @sec:menstrual-cycle-dopaminergic-mast-cell-probe, the menstrual cycle can be used prospectively as a pharmacodiagnostic probe: track a drug's response across two full cycles and use the cycle-phase variation to infer which receptor system the drug acts through. Oestrogen fluctuates predictably — peak in the late follicular/ovulatory phase, nadir in the perimenstrual phase — and differentially modulates NMDA, D2, and 5-HT1A receptor signalling. Progesterone rises in the luteal phase and is metabolised to allopregnanolone, a potent positive allosteric modulator of GABA-A receptors. These receptor modulations have established mechanistic support (oestrogen rapidly potentiates NMDA via ER transactivation of MAPK/ERK and PI3K/Akt @Sellers2015estrogenSynaptic; progesterone-derived allopregnanolone enhances GABA-A tonic current, with receptor subunit composition shifting drug sensitivity @Locci2017neurosteroidGABA; oestrogen modulates serotonin synthesis, release, and receptor sensitivity @Shadani2024psychedelicsSex), though much of the evidence is preclinical — direct human menstrual-cycle functional receptor measurements are absent (see Evidence source below). Menstrual cycle hormones co-fluctuate with measurable whole-brain structural changes @Rizor2024brainArchitecture.

#speculation(title: [Menstrual Cycle as Endogenous Pharmacodiagnostic Probe])[
  *Hypothesis:* Tracking a drug's response across two full menstrual cycles and observing >30% variation in efficacy between follicular and luteal phases maps the drug's mechanism to receptor families gated by specific hormones. (Certainty: 0.20. Origin: brainstorm — pharmacodiagnostic extensions 2026.)

  - *Drug works during follicular phase (high oestrogen, days 7--14 based on ovulation-confirmed cycle dating) but not luteal:* Oestrogen-dependent mechanism — consistent with oestrogen potentiation of NMDA (via ER transactivation of MAPK/ERK and PI3K/Akt @Sellers2015estrogenSynaptic), D2 (dopamine synthesis and signalling), and 5-HT1A (serotonin synthesis, release, receptor sensitivity @Shadani2024psychedelicsSex). If a drug's benefit tracks the oestrogen peak and disappears during the luteal phase → the drug's mechanism may involve oestrogen-potentiated signalling; narrow the candidate receptor list using the drug's known pharmacology (e.g., a D2 agonist → consistent with oestrogen-D2 coupling; an SSRI → consistent with oestrogen-serotonergic coupling). However, correlation is not confirmation — these are the systems with the best mechanistic evidence for oestrogen modulation, but oestrogen also regulates immune function, vascular tone, HPA-axis reactivity, and pain processing, any of which could produce the same cycle-phase pattern without the drug's nominal target being directly oestrogen-coupled.
  - *Drug works during luteal phase (high progesterone, days 21--28) but not follicular:* Progesterone/GABA-A-dependent mechanism. Progesterone metabolite allopregnanolone enhances extrasynaptic GABA-A tonic current, and chronic progesterone exposure shifts GABA-A receptor subunit composition in ways that alter drug sensitivity (α4β2δ upregulation, benzodiazepine sensitivity reduction @Locci2017neurosteroidGABA). If a drug's benefit tracks the progesterone/allopregnanolone peak → the drug's mechanism involves GABAergic signalling. This is particularly informative for sedating or anxiolytic medications. Caveat: allopregnanolone can produce *paradoxical* negative mood/fatigue effects in susceptible individuals (PMDD model of α4βδ GABA-A dysregulation) — luteal worsening may reflect the same receptor coupling in a vulnerable subset.
  - *Flat response — less than 15% variation across two cycles after confirming ovulation via serum progesterone >3 ng/mL on day 21:* Hormone-independent mechanism, OR the pathology is severe enough that hormonal modulation is insufficient to move symptoms, OR anovulatory/low-amplitude cycle (see @oq:null-interpretability-menstrual-probe). The null does not rule out involvement of the receptor class — a D2 agonist that produces identical benefit in follicular and luteal phases after ovulation confirmation still works via D2, but D2 signalling is not oestrogen-potentiated to a clinically significant degree in this patient.
  - *Gray zone (15--30% variation):* Insufficient evidence for mechanism classification. Possible explanations include weak oestrogen coupling, insufficient cycle amplitude (anovulatory cycle, luteal phase deficiency), or noisy symptom data. Requires third cycle of tracking or confirmatory evidence from another probe before inference.
  - *Perimenstrual worsening (days 1--3) but drug still partially effective:* Both oestrogen and progesterone drop. The drug's mechanism is partially hormone-independent — it provides benefit that outlasts the hormone trough — but the underlying pathology worsens because hormone-mediated compensation is withdrawn. However, perimenstrual worsening is multiply confounded: iron loss from bleeding → transient anaemia, prostaglandin-mediated pain → sleep disruption, and dysmenorrhea-associated sympathetic activation all produce the same pattern without involving receptor biology (@lim:perimenstrual-confounds). A large perimenstrual dip despite ongoing drug is not interpretable as receptor uncoupling without controlling for haemoglobin, sleep efficiency, and pain scores.

  *Evidence source — functional sensitivity, not receptor density:* PET studies find no significant change in 5-HT1A binding potential (n=13 @Jovanovic2009serotoninPET) or striatal D2 availability (n=16 @Petersen2021D2estradiol) across the menstrual cycle — the only direct human-mechanistic evidence. These studies are underpowered to detect moderate effects, but they are the closest available data. If receptor density does not change, oestrogen and progesterone may still modulate downstream intracellular signalling cascades (G-protein coupling, second messenger efficacy, MAPK/ERK, CREB phosphorylation @Sellers2015estrogenSynaptic) without changing receptor number. No human study has measured cycle-phase D2 or 5-HT1A functional output — the functional-sensitivity mechanism is plausible from preclinical work but has zero direct human evidence. The probe rests on correlation (hormone fluctuation → response variation) plus a biochemical hypothesis that is untested in vivo in humans.

  *PK confound:* The PK-vs-PD origin of any cycle-phase drug response difference is unknown in humans. CYP450 expression appears stable across the oestrous cycle in rats @Lee2012CYPestrous, but the rodent oestrous cycle differs hormonally from the human menstrual cycle and human CYP data on oestrogen modulation is mixed @Bosch2025sexPKreview. Any probe protocol must measure drug serum levels to distinguish PK from PD contributions — without this, the probe is uninterpretable as receptor-level pharmacodynamic signal. Note: most ME/CFS-relevant drugs (LDN, low-dose aripiprazole) lack clinical serum assays with validated therapeutic ranges.

  *Missing control — drug-free baseline cycle:* ME/CFS symptoms fluctuate across the cycle with no drug at all. Without a pre-drug (or washout) baseline symptom cycle to subtract, any phase-locked change could reflect the patient's endogenous cycle rhythm rather than a drug×hormone interaction. A drug-free tracking cycle — symptom diary only, no drug — should precede any drug trial used for probe inference.

  *Severity applicability:* All for observational tracking — but daily scoring is a cognitive exertion for severe/very-severe patients. Consider reduced-frequency tracking or caregiver assistance.

  *Falsifiable prediction:* In a prospective N-of-1 trial design, premenopausal ME/CFS patients track drug efficacy across follicular and luteal phases with pre-drug baseline cycles, ovulation confirmation, and serum drug level measurement. Cycle-phase response variation >30% with follicular-phase benefit → consistent with oestrogen coupling. Falsified if (a) drug serum levels vary by cycle phase (PK confound), (b) the same variation pattern appears with placebo, or (c) the pattern disappears when perimenstrual confounds (haemoglobin, sleep efficiency, pain scores) are controlled.

  *Consequence:* Cycle-phase drug-response tracking is hypothesis-generating only — no validated clinical use exists. The primary value is methodological: it formalises an observation pattern that patients and clinicians may already notice (a drug working differently at different points in the cycle) without attributing it to coincidence. Do not use cycle-phase patterns to change drug dosing without prescriber involvement, and do not treat them as diagnostic evidence.

  *Translation gap:* No human study has directly tested cycle-phase-dependent drug response as a receptor-system probe in any disease (@Thomas2026neuroendocrinologyFramework explicitly calls for this research design). All mechanistic evidence for oestrogen → receptor modulation comes from general-population and animal studies, with mixed human PET evidence (null binding at n=13–16, underpowered). Not yet validated in ME/CFS patients.

  *Limitations:* Applies only to menstruating patients with regular, ovulation-confirmed cycles (excludes postmenopausal, on continuous hormonal contraception, prepubertal, male, amenorrhoeic). The >30% threshold is arbitrary — no dose-response calibration exists. Cycle-phase symptom patterns may be confounded by non-hormonal factors (menstrual pain, sleep disruption, iron loss from bleeding). Two-timepoint sampling misses the periovulatory oestrogen peak. Requires 2 full on-drug cycles plus a pre-drug baseline cycle — minimum 12-week commitment. No validated diary instrument is specified. Most ME/CFS-relevant drugs (LDN, low-dose aripiprazole) lack clinical serum assays.

  *Oestrogen-NMDA potentiation is bidirectional:* Oestrogen's NMDA potentiation is framed here as benefit-amplifying, but enhanced glutamatergic tone is a candidate *pathology* mechanism in ME/CFS (excitotoxicity, central sensitization). The same oestrogen-NMDA coupling could produce follicular-phase symptom *worsening* in excitotoxicity-vulnerable patients — the interpretive grid above has no row for this outcome. If a patient reports follicular worsening, oestrogen-NMDA coupling should be considered a candidate explanation alongside the listed confounds.
] <spec:menstrual-cycle-pharmacodiagnostic-probe>

*Consequence summary:* The menstrual cycle provides a predictable hormonal oscillation that may modulate drug response. Tracking this variation is hypothesis-generating, not diagnostic — the framework provides a vocabulary for describing patterns patients may already observe, but none of its derivative protocols (dosing, pacing, ratio cutoffs) are validated. The primary value is methodological: a vocabulary for cycle-phase pharmacodynamics that can be tested prospectively.

#speculation(title: [Menstrual Cycle Phase at Drug Initiation as Confound and Probe])[
  *Hypothesis:* The menstrual cycle phase at which a drug trial begins may systematically bias the outcome. A D2 agonist started during the follicular phase (high oestrogen, D2 signalling potentiated) may produce a robust initial response that fades by the luteal phase — potentially misinterpreted as tachyphylaxis when it may reflect cycle-phase oestrogen withdrawal. The same drug started during the luteal phase may produce a flat initial response and be abandoned as ineffective, when it would have been more effective in the follicular phase. (Certainty: 0.20. Origin: brainstorm — Phase 5 extension.)

  *Clinical implication:* Record cycle phase at trial initiation as a covariate and test for phase × response interaction. Scheduling initiation to a specific phase (e.g., day 1 of menses) eliminates the confound in principle but adds logistical delay — the simpler first step is recording and analyzing.

  *Severity applicability:* All menstruating patients starting drug trials.

  *Falsifiable prediction:* In a pooled analysis of N-of-1 trial data from ME/CFS patients, cycle phase at drug initiation predicts response magnitude — follicular-start trials have higher reported initial efficacy for dopaminergic drugs than luteal-start trials. Null result would suggest cycle-phase-independent initial response, though an underpowered analysis cannot rule out a small effect.

  *Consequence:* If confirmed, recording cycle phase at trial initiation adds a low-cost covariate to N-of-1 trial design. The practical action is recording, not scheduling — test for phase effect before mandating phase-specific trial starts.

  *Limitations:* No prospective data. Patients may preferentially start new drugs when symptoms are worst (perimenstrual for many), producing regression-to-the-mean effects that covary with cycle phase — a confound of the confound that only randomized initiation timing can resolve.
]

#open-question(title: [Can Cycle-Phase Drug Response Stratify Patients?])[
  Does cycle-phase-dependent drug response identify a patient subgroup whose pathophysiology is oestrogen- or progesterone-coupled? If patients whose D2 agonists work only during the follicular phase (oestrogen-dependent D2 potentiation) have a different prognosis, treatment trajectory, or biomarker profile than patients whose D2 agonists work uniformly across the cycle → cycle-phase response is not just diagnostic for the drug's mechanism, but for the patient's disease subtype. (Evidence source: none — purely inferential.)

  *Severity applicability:* Unknown — no data.

  *Consequence:* If cycle-phase response stratifies patients, a low-cost observational method could guide treatment selection — oestrogen-dependent responders might benefit from hormonal modulation or continuous-cycle contraceptives, while hormone-independent responders would waste time on hormonal strategies. Currently entirely speculative.
]

*General limitations:* None of the probes in this section have been validated in a prospective trial. Cycle-phase tracking requires at least 2 full cycles plus a pre-drug baseline (minimum 12 weeks) for reliable inference. The conceptual framework draws from well-established receptor pharmacology at the hormonal level but all clinical implications remain speculative. Because the probe is observational and low-cost, the risk of harm is negligible, but the risk of over-interpretation is real. Do not treat cycle-phase response patterns as definitive diagnostic evidence, only as hypothesis-generating signals for further targeted pharmacological testing.

// --- Phase 5 extension: Tier 2 brainstorm ideas integrated as speculation + critical categories ---

#speculation(title: [Catamenial Epilepsy and Menstrual Migraine Methodology Transfer — Validated Precedents for Cycle-Phase Pharmacodiagnostics])[
  *Hypothesis:* Cycle-phase-dependent drug response tracking in ME/CFS does not need to be invented from scratch. Several conditions have clinically recognised cycle-phase-dependent drug management: catamenial epilepsy (perimenstrual benzodiazepine/clobazam dose adjustment, 30+ years of diary-based methodology), menstrual migraine (perimenstrual frovatriptan mini-prophylaxis, guideline-level practice), and PMDD (luteal-phase intermittent SSRI dosing). Among these, catamenial epilepsy provides the most extensively validated methodology for detecting cycle-phase symptom patterns in a noisy symptom: daily diaries, cycle-phase categorisation (C1—perimenstrual, C2—periovulatory, C3—luteal), phase-specific dose adjustment, and statistical methods for identifying genuine cycle-phase variation against background fluctuation. The diary templates and phase-categorisation algorithms are directly transferable. PMDD's intermittent SSRI dosing is arguably a closer analogue (subjective symptom tracking, serotonergic mechanism). (Certainty: 0.50 for diary/phase-categorisation methodology transfer; 0.20 for mechanism extrapolation. Origin: brainstorm.)

  The methodological transfer is non-trivial: catamenial epilepsy research has developed rigorous methods for detecting cycle-phase signal in a noisy symptom — precisely the challenge the ME/CFS probe faces. Adopting their diary format, phase-categorisation logic, dual-hormone phase verification, and statistical methods for distinguishing genuine cycle-phase patterns from random fluctuation provides a replicable protocol. However, epilepsy has an objective outcome (seizure count) while ME/CFS has subjective symptom reports, so the signal-to-noise challenge is greater and the magnitude thresholds validated on seizure data may not transfer directly.

  *Severity applicability:* All menstruating patients (observational).

  *Falsifiable prediction:* A cycle-phase pharmacodiagnostic protocol adapted from catamenial epilepsy and menstrual migraine methodologies will produce interpretable cycle-phase drug response profiles in a subset of enrolled ME/CFS patients with regular, ovulation-confirmed cycles. Falsified if the protocol produces no interpretable profiles — ME/CFS symptom fluctuations are too noisy or confound-heavy for cycle-phase signal to emerge.

  *Consequence:* The diary templates, phase-categorisation logic, and statistical methods from catamenial epilepsy and menstrual migraine are field-tested and directly transferable, reducing (but not eliminating) the methodological development burden for prospective ME/CFS studies.

  *Limitations:* Epilepsy and migraine have more objective outcomes than ME/CFS subjective symptom scores — the signal-to-noise ratio is inherently lower. Diary templates transfer; magnitude thresholds require re-validation on ME/CFS symptom data. The evidence base for perimenstrual dose adjustment in catamenial epilepsy is limited to small and mixed-quality trials — the methodology is better validated than the therapeutic outcome it measures. PMDD intermittent SSRI dosing is a closer analogue and may be the more transferable precedent.
] <spec:catamenial-epilepsy-methodology-transfer>

#speculation(title: [Cycle-Synchronized Drug Dosing — Titrate Dose to Cycle Phase])[
  *Hypothesis:* If a drug's efficacy varies by cycle phase, the same information that identifies the receptor coupling could — if validated — guide therapeutic dose adjustment. A D2 agonist that is oestrogen-potentiated might require a higher luteal-phase dose to achieve the same D2 activation as the follicular phase. A GABAergic drug that is allopregnanolone-potentiated (luteal benefit) might require a *lower* dose during the luteal phase — the endogenous neurosteroid is already providing GABA-A potentiation. However, the relationship between hormone potentiation and effective dose has never been quantified in humans for any drug class; the direction and magnitude of any dose adjustment are entirely unknown. Chronic neurosteroid exposure produces GABA-A receptor subunit changes that could reverse the predicted effect direction. (Certainty: 0.25. Origin: brainstorm.)

  *Severity applicability:* All menstruating patients on cyclic drugs — but dose adjustment MUST be managed by the prescribing clinician. Self-titration without medical oversight is unsafe.

  *Falsifiable prediction:* In a clinician-supervised crossover N-of-1 trial, cycle-synchronized dosing produces greater overall symptom control with fewer side effects than fixed dosing in patients whose drug response shows >30% cycle-phase variation. Falsified if fixed and synchronized dosing produce equivalent outcomes.

  *Consequence:* If you observe that your medication's effectiveness varies predictably across your cycle, document the pattern for at least 3 cycles and discuss with your prescriber whether phase-specific dose adjustment is appropriate for your specific drug. Some drugs have narrow therapeutic windows where any dose change requires close monitoring. The optimal adjustment magnitude (if any) has never been studied — there is no evidence-based dosing protocol.

  *Limitations:* Requires at least 3 cycles of baseline data before any dose adjustment discussion. No published protocol for cycle-synchronized psychopharmacology. The direction of adjustment is speculative — chronic neurosteroid exposure produces GABA-A receptor subunit changes that could reverse the predicted effect direction for GABAergic drugs. All dose changes must be managed by the prescribing clinician. Some drugs have narrow therapeutic windows where dose adjustment is unsafe at any magnitude.
]

#speculation(title: [Luteal-to-Follicular Drug Response Ratio (LFDRR) as Patient-Level Biomarker])[
  *Hypothesis:* Each patient's drug-cycle interaction can be summarised as a single dimensionless number: LFDRR = mean drug efficacy during luteal days 21–28 divided by mean efficacy during follicular days 7–14 (both anchored to ovulation-confirmed cycle dating). LFDRR < 0.7 → oestrogen-coupled pattern. LFDRR > 1.3 → progesterone/GABA-coupled pattern. LFDRR 0.7–1.3 → indeterminate (requires additional data: serum hormone phase verification, receptor function assays, or third-cycle replication to discriminate hormone-independence from impaired receptor or anovulatory cycle — see @oq:null-interpretability-menstrual-probe). This is a standardised, descriptive number — computable from any symptom diary, comparable within patient across drugs. Two drugs with similar LFDRR in the same patient may share receptor-coupling mechanisms, though patient-level factors (cycle amplitude, symptom-reporting style, expectancy) can produce similar ratios for mechanistically unrelated drugs. (Certainty: 0.30. Origin: brainstorm.)

  The LFDRR formalises the qualitative thresholds from the base probe as a continuous variable. Values in the 0.7–1.3 range (15–30% variation relative to baseline) are indeterminate — see gray-zone discussion in the base probe.

  *Severity applicability:* All menstruating patients (computed from existing diaries).

  *Falsifiable prediction:* LFDRR test-retest reliability across two 2-cycle windows will show ICC > 0.6 (stable enough for individual-level use). LFDRR for aripiprazole will correlate with fitted receptor-hormone coupling coefficients (see @spec:cycle-phase-receptor-coupling-coefficients) with ρ > 0.7. Falsified if ICC < 0.4 or ρ < 0.5 — LFDRR is too noisy for reliable individual use.

  *Consequence:* After 2 months of tracking, one number describes whether your drug seems oestrogen-coupled, progesterone-coupled, or indeterminate — but "indeterminate" (LFDRR 0.7–1.3) does not mean "hormone-independent"; it means you need additional data to distinguish true independence from an impaired receptor or an anovulatory cycle. If LFDRR is consistently below 0.7 across multiple tracked drugs, hormonal strategies are worth discussing with your clinician; if it is consistently indeterminate, a blood test confirming ovulation is the next step, not concluding your pathophysiology is hormone-independent.

  *Limitations:* Requires regular cycles with confirmed ovulation for valid ratio computation. LFDRR stability across time has not been measured. Single-number ratio loses granularity — a patient with LFDRR 0.7 might have a response pattern masked by partial follicular benefit combined with perimenstrual worsening. Within-patient cross-drug comparisons are confounded by patient-level factors (cycle amplitude, expectancy) that affect all drugs equally.
] <spec:lfdrr>

#speculation(title: [Receptor-Hormone Coupling Coefficients — Quantitative Model from N-of-1 Tracking])[
  *Hypothesis:* Model each patient's daily drug efficacy as: E(t) = E₀ × (1 + α × ΔE2(t) + β × ΔP4(t)), where ΔE2(t) and ΔP4(t) are oestradiol and progesterone deviations from the patient's mean, and α and β are dimensionless receptor-hormone coupling coefficients. With 3+ cycles of daily efficacy data and cycle-day proxy or serum hormone estimates, fit α and β via linear regression. α > 0 → oestrogen enhances drug mechanism. α < 0 → oestrogen inhibits it. α ≈ 0 → oestrogen-independent. (Certainty: 0.40 as modelling exercise. Origin: brainstorm.)

  The quantitative model is a superset of the qualitative probe and the LFDRR (@spec:lfdrr) — it produces continuous numbers rather than ternary classifications and can detect mixed coupling (oestrogen-*and*-progesterone-dependent with opposite signs). Caveat: oestradiol and progesterone are correlated functions of cycle day, making α and β partially unidentifiable from a single 3-cycle fit; daily symptom scores are autocorrelated, so ~90 observations yield a much smaller effective sample. The model has never been fitted to any dataset.

  *Severity applicability:* All menstruating patients with regular cycles (3+ cycles for model fit).

  *Falsifiable prediction:* Fitted α and β for aripiprazole will correlate with in vitro D2 receptor cAMP response to dopamine ± oestradiol (ρ > 0.5). α and β will be stable within patient (ICC > 0.5) across two independent 3-cycle fitting windows. Falsified if in vitro correlation is absent (model captures noise) or if coefficients are unstable (not a trait).

  *Consequence:* If validated, two numbers — your oestrogen-sensitivity score (α) and progesterone-sensitivity score (β) — could characterise how your receptor biology interacts with cycle-phase hormones. The model has never been fitted to any dataset; until validated, these are conceptual constructs, not clinically actionable numbers.

  *Limitations:* Requires daily tracking × 3+ cycles (90+ data points per drug) — high patient burden. Linear model assumes additive, dose-independent coupling — real receptor biology may be non-linear with interactive α × β terms. Oestradiol and progesterone regressor collinearity makes α and β partially unidentifiable without many cycles. Daily symptom score autocorrelation reduces effective sample size. No existing data to validate or calibrate.
] <spec:cycle-phase-receptor-coupling-coefficients>

#speculation(title: [Cycle-Phase-Matched Activity Pacing — Align Exertion with Pharmacological Benefit])[
  *Hypothesis:* If a drug's benefit tracks a specific cycle phase, scheduling exertion-demanding activities within that window and protecting the other phase for rest may increase functional return from the drug without increasing total exertion. This adds zero cost and zero additional drugs — only strategic scheduling. However, the link between cycle-phase drug benefit and PEM threshold is entirely unmeasured; a drug improving mood or pain in one phase does not necessarily raise the exertion tolerance threshold in that phase. Concentrating activity in the perceived-best-feeling window risks the boom-bust cycle pacing doctrine exists to prevent. (Certainty: 0.25. Origin: brainstorm.)

  *Protocol:* After identifying the cycle phase where the patient's primary drug shows maximum benefit (2+ cycles of tracking), shift cognitively or physically demanding tasks toward that window while protecting the other phase for rest. Track PEM frequency alongside activity to detect any increase — if PEM rises, return to uniform pacing.

  *Severity applicability:* Mild–moderate patients with regular cycles and identifiable phase-benefit pattern. Not appropriate for severe/very-severe patients. Requires active PEM monitoring with a pre-defined stopping rule.

  *Falsifiable prediction:* In a 12-week crossover trial with PEM monitoring, cycle-phase-matched activity pacing produces lower PEM frequency and higher FUNCAP scores than uniform pacing. Falsified if matched and uniform pacing produce equivalent outcomes — the drug's cycle-phase benefit does not translate to a functional activity window.

  *Consequence:* If your medication helps most during week 2, shifting harder tasks to week 2 might increase functional output — but monitor PEM frequency to confirm the schedule is protective rather than destabilising. If PEM increases, return to uniform pacing regardless of perceived benefit.

  *Limitations:* No prospective trial. Requires patient to be on a stable drug with identifiable cycle-phase pattern. Mild-moderate only. Concentrating exertion in the perceived-benefit window inverts standard energy-envelope pacing logic — if the drug's benefit does not raise the PEM threshold (an unmeasured link), the protocol could increase PEM frequency. PEM monitoring and a return-to-uniform-pacing stopping rule are essential.
]

#open-question(title: [Prospective N-of-1 Trial Registry with Cycle-Phase Serum Drug-Level Normalization])[
  The most valuable research investment in cycle-phase pharmacodiagnostics is a registry where premenopausal ME/CFS patients running N-of-1 drug trials contribute: daily symptom scores, cycle day, drug dose and timing, and serum drug levels at follicular peak (ovulation-anchored, not fixed day) and luteal peak — one blood draw per phase per drug — plus serum oestradiol and progesterone at the same timepoints for phase and ovulation verification. With n ≥ 50 patients and ≥3 drugs each, the registry produces a PD map of cycle-phase drug-response variation controlling for the PK confound. The study uses N-of-1 infrastructure already described (@sec:synthesis-algorithm-extended). It answers the foundational question: in what fraction of drugs, at what magnitude, and in what fraction of patients do cycle-phase drug response differences exist after controlling for serum drug levels and perimenstrual confounds? (Origin: brainstorm.)

  *Consequence:* Whether cycle-phase pharmacodiagnostics is clinically actionable or merely conceptually elegant depends on the effect size — and the effect size is unknown. A 50-patient, 3-drug-per-patient registry would provide the first estimates, though estimates will have wide confidence intervals and definitive answers may require larger samples.

  *Severity applicability:* Mild–moderate (blood-draw tolerance required).
]

// Critical categories

#limitation(title: [Perimenstrual Confounding — Iron Loss, Sleep Disruption, and Pain Masquerade as Receptor Uncoupling])[
  Perimenstrual symptom worsening — the most commonly reported cycle-phase pattern in ME/CFS — is attributed in the pharmacodiagnostic framework to "oestrogen and progesterone both drop → unmasking of dopamine/GABA deficits." But the perimenstrual window involves non-hormonal factors that masquerade as receptor-modulation effects: (a) iron loss from menstrual bleeding → transient anaemia → reduced oxygen delivery → fatigue; (b) prostaglandin-mediated uterine cramping → pain → sleep disruption → next-day fatigue; (c) dysmenorrhea-associated sympathetic activation → beta-adrenergic tone → mimic of autonomic probe signal. A drug that fails during days 1–3 may be failing because the patient has a haemoglobin drop and 3 hours of sleep — not because the drug's receptor target lost oestrogen potentiation. The simplest explanations — blood loss, cramps, and poor sleep — may fully explain the pattern, with no need to invoke receptor biology. Without controlling for haemoglobin, sleep efficiency, and pain scores, perimenstrual drug-response dips are multiply confounded and uninterpretable as receptor-coupling signals. (Certainty: 0.45. Origin: brainstorm.)

  *Consequence:* Before concluding a drug's mechanism is oestrogen-coupled because it stops working during your period, check your iron and your sleep. The simplest explanations may fully explain the pattern.
] <lim:perimenstrual-confounds>

#open-question(title: [Null Interpretability — A Flat Cycle-Phase Drug Response Has Three Equal Explanations])[ <oq:null-interpretability-menstrual-probe>
  The pharmacodiagnostic framework treats a flat cycle-phase response (less than 15% variation after ovulation confirmation) as evidence for a hormone-independent mechanism. But the null has three distinct explanations of comparable probability: (a) the drug's mechanism truly is hormone-independent (the probe's intended inference); (b) the drug's mechanism IS hormone-dependent, but the patient's receptor system is so impaired that hormonal modulation cannot move the needle — the receptor is functionally absent, not uncoupled (e.g., D2 autoreceptors are desensitised); (c) the drug's mechanism IS hormone-dependent, but the patient's cycle lacks sufficient hormone amplitude — anovulatory cycles (progesterone less than 3 ng/mL on day 21), luteal phase deficiency, or perimenopausal erratic hormone levels. Anovulatory cycles occur in 10–30% of cycles even in regularly menstruating women and may be more common in ME/CFS through HPA-mediated GnRH suppression. Three qualitatively different inferences from one null result → the null is not interpretable without additional data: serum drug levels, serum oestradiol and progesterone confirming ovulation, and a receptor function assay. (Certainty: 0.40. Origin: brainstorm — null hypothesis assessment, category 11.)

  *Consequence:* "No change across your cycle" can mean three different things. Without a blood test confirming ovulation, you cannot distinguish "hormones don't matter for this drug" from "your target receptor is so broken that hormones can't help" from "your cycle isn't actually cycling enough to matter."

  *Severity applicability:* All menstruating patients.
]

#limitation(title: [Confirmation Bias in Patient Self-Reported Cycle-Phase Drug Response])[
  The probe requires patients to track drug efficacy daily across multiple cycles. But patients informed of a cycle-phase drug-response hypothesis (e.g., "this drug works better during your follicular phase") may unconsciously bias their symptom reporting toward the predicted pattern. Expectancy effects in symptom reporting are well-documented; cycle-phase symptom studies show women primed to expect negative premenstrual symptoms report more of them. The probe's data generation process is inherently subjective and susceptible to the very hypothesis it tests — patients are both the measurement instrument and the hypothesis audience. (Certainty: 0.35. Origin: brainstorm — evidence quality concerns, category 12.)

  *Consequence:* The probe tells patients what the data should look like while asking them to generate the data. Blinded trial designs — neutral-framing diary instructions that do not specify the predicted pattern — are required to distinguish genuine cycle-phase pharmacodynamics from expectancy effects. A practical alternative: complete a drug-free baseline diary cycle before reading the interpretation framework, so the data are generated without knowledge of the hypothesis.

  *Severity applicability:* All patients (psychological confound, not disease-specific).
]
