#import "../../../../shared/environments.typ": *
#import "/src/main/typst/lib/clinical-caution.typ": clinical-caution

==== Cascade: Central motor drive fails to up-regulate under sustained effort

#clinical-caution()

*Cascade:*
- Sustained effort demand (fatiguing grip task) → cortical motor-output computation (effort required vs effort delivered) @Bedard2026centralFatigability
- Corticospinal drive: motor-cortical and subcortical output should increase to maintain force — in ME/CFS it does not up-regulate (absent EEG-power and BOLD increase, minimal fluctuation)
- Spinal motoneuron recruitment / muscle-fiber recruitment: no compensatory increase in the Dimitrov index (unlike controls)
- Afferent feedback (corticomuscular coherence) fails to drive the output increase that would match demand
- Result: equal maximum voluntary force but earlier performance decline (fatigue onset)
- *Differential task:* distinguish central motor-drive failure (this cascade) from metabolic energy-triage (@sec:triage-cascade), dopaminergic-effort/motivation loss (@sec:gerlier-dopamine-node), and CNS neuroinflammation (@sec:microglial-cascade)

*Step C1:* Cortical motor-output computation / central drive generation
- *Mechanism:* In healthy controls, sustained effort elicits a progressive increase in motor-cortical (EEG power) and subcortical (BOLD) activity that drives muscle-fiber recruitment to hold force; ME/CFS patients instead show minimal fluctuation in these signals — the brain fails to *increase* motor output to match rising effort demand @Bedard2026centralFatigability. This is an *association* observed during a fatiguing task, not an established causal mechanism; it localizes the failure to central output generation but does not identify why (energy, dopamine/effort, neuroinflammation, or maladaptive pacing are all upstream candidates). (Evidence source: scalp EEG + fMRI BOLD during a fatiguing grip task — Inference target: cortical/subcortical motor-output up-regulation. The compartment is intracranial, measured non-invasively; the link from reduced signal to reduced spinal drive is inferred.)
- *Intercept:* Central-acting wakefulness/effort promoters as *research probes* only — modafinil/armodafinil (weak DAT/NET inhibition, histamine/orexin activation; @sec:medication-reference, @Minzenberg2008modafinil) and methylphenidate (stronger DAT/NET blockade; @sec:medication-reference). A normalized motor-drive trajectory under a central probe would support a central-output bottleneck.
#finding(claim: [Central motor-output up-regulation is the rate-limiting bottleneck], explanation: [If a central-acting probe (modafinil, methylphenidate) restores the grip-force/EEG/BOLD trajectory — later fatigue onset, normalized up-regulation — central motor-output generation is implicated as the bottleneck; the specific drug that works then localizes the sub-node (see Step C2). A null response does NOT rule out central drive, because the failure may be upstream of, or unreachable by, the probed receptor class.], certainty: [Low], level: [Hypothesis])
#finding(claim: [Motor-drive failure is NOT a dopaminergic-effort bottleneck], explanation: [If a dopamine-targeting probe fails but the ME/CFS fatigability remains (equal MVC, early decline), central drive is not rate-limited by the probed dopaminergic/effort node — weight energy-triage (@sec:triage-cascade) or neuroinflammation (@sec:microglial-cascade) as the upstream cause, or probe a non-dopaminergic node (Step C3 amantadine).], certainty: [Low], level: [Hypothesis])

*Step C2:* Dopaminergic / effort node (DAT/NET and D2/D3)
- *Mechanism:* Sustained effort engages dopaminergic circuits that convert "effort worth it" into motor output. A bottleneck here would make the brain under-prioritize sustained physical output even though maximum capability is intact (equal MVC) — matching the Bedard observation of an absent output up-regulation rather than a ceiling @Bedard2026centralFatigability. The dopaminergic-effort node is independently developed in the Gerlier four-pathway model @sec:gerlier-dopamine-node and the dopamine-convergence hypothesis; it is the most pharmacologically accessible interception point in the motor-drive cascade.
- *Intercept:* Methylphenidate (DAT blockade; @sec:medication-reference), modafinil/armodafinil (weak DAT/NET; @sec:medication-reference), amphetamines/dextroamphetamine/lisdexamfetamine (DAT/NET + VMAT2 reversal; @sec:medication-reference) probe reuptake/effort; bromocriptine/rotigotine (D2/D3 agonism; @sec:medication-reference) probe the postsynaptic receptor. Each targets a distinct sub-node, so the *pattern* of response discriminates reuptake-blockade vs postsynaptic-receptor vs release.
#finding(claim: [Dopaminergic effort-node is the motor-drive bottleneck (reuptake subtype)], explanation: [If methylphenidate restores motor-drive up-regulation (later fatigue, normalized trajectory) while a D2/D3 agonist (bromocriptine/rotigotine) does not → the bottleneck is presynaptic reuptake/effort signaling rather than postsynaptic D2/D3 responsiveness. If a D2/D3 agonist works but reuptake blockade does not → the bottleneck is postsynaptic receptor sensitivity. Pattern discrimination, per the sec-12 pharmacodiagnostic entries.], certainty: [Low], level: [Hypothesis])
#finding(claim: [Dopaminergic node NOT the bottleneck], explanation: [If neither reuptake blockade nor D2/D3 agonism changes the fatigability trajectory → the motor-drive failure is not rate-limited at the dopaminergic-effort node; probe the glutamatergic node (Step C3) or re-weight toward energy-triage/neuroinflammation.], certainty: [Low], level: [Hypothesis])

*Step C3:* Glutamatergic / release node (amantadine)
- *Mechanism:* Amantadine enhances presynaptic DA release (and NMDA modulation) rather than blocking reuptake, so it discriminates a release deficit from a reuptake bottleneck @sec:medication-reference. A release-deficit motor-drive failure would show an absent output up-regulation that amantadine (but not a reuptake blocker) restores.
- *Intercept:* Amantadine (presynaptic DA release; @sec:medication-reference).
#finding(claim: [DA-release machinery is the motor-drive bottleneck], explanation: [If amantadine restores the motor-drive trajectory but methylphenidate does not → presynaptic release (not reuptake) is the bottleneck; if methylphenidate works but amantadine does not → reuptake is the bottleneck, release machinery intact.], certainty: [Low], level: [Hypothesis])
#finding(claim: [Dopaminergic release AND reuptake both intact], explanation: [If neither amantadine nor methylphenidate alters fatigability → the presynaptic dopaminergic machinery is not the rate-limiting step; the failure is upstream (energy/neuroinflammation) or postsynaptic-but-D2/D3-unresponsive — step outside the dopaminergic-effort node.], certainty: [Low], level: [Hypothesis])

*Step C4:* Spinal motoneuron → neuromuscular → muscle-fiber recruitment
- *Mechanism:* Downstream of cortical drive, the absence of a Dimitrov-index increase indicates that spinal motoneuron recruitment / muscle-fiber recruitment does not compensate for declining force @Bedard2026centralFatigability. This is the *efferent* expression of the central failure: the muscle itself can generate maximum force (equal MVC) but is not being progressively driven to hold sub-maximal force under fatigue.
- *Intercept:* None directly at this node — peripheral ergogenic aids should NOT restore the trajectory if the bottleneck is central (a discriminating prediction). Cross-reference ch30 muscle/energy cascades for the peripheral-exhaustion alternative (@sec:triage-cascade).
#finding(claim: [Peripheral muscle is NOT the bottleneck], explanation: [If peripheral ergogenic aids (e.g., ergogenic supplements or peripheral conditioning) do not restore the fatigability trajectory, but a central-acting probe does → the bottleneck is central (this cascade). If a peripheral intervention alone restores performance → the peripheral-exhaustion model is favored, falsifying a purely central bottleneck.], certainty: [Low], level: [Hypothesis])

*Step C5:* Afferent feedback / corticomuscular coherence
- *Mechanism:* The corticomuscular-coherence (afferent) arm of the Bedard data reflects that motor output is not being corrected by sensory feedback from the fatiguing muscle; the loop that would normally up-regulate drive fails @Bedard2026centralFatigability. This is the least-falsified, least-probed node and the most speculative step of the cascade.
- *Intercept:* None established; no drug directly targets afferent-feedback gain. This node is a research-measurement target (corticomuscular coherence) rather than an interception point.
#finding(claim: [Afferent feedback failure is a distinct cascade node], explanation: [Corticomuscular-coherence changes under a central probe would indicate whether the afferent-feedback correction of drive is a separate, drug-sensitive node or simply a readout of the reduced output. Untested; measurement-only.], certainty: [Low], level: [Hypothesis])

*Consequence:* This cascade gives researchers and clinicians a triaged, drug-testable sequence to separate a brain-level failure to drive muscle (cortical output → dopaminergic-effort node → glutamatergic-release node) from peripheral muscle exhaustion, metabolic energy-triage (@sec:triage-cascade), and CNS neuroinflammation (@sec:microglial-cascade). Differential drug response is a research tool here, NOT a validated diagnostic instrument (see the caution in @sec:pharmacodiagnostic-matrix); each probe requires the monitoring, interaction, and stopping guidance in @sec:medication-reference, and none of these drugs is recommended on this associational evidence alone. Severity applicability: unknown — the Bedard 2026 NIH intramural cohort is not stratified by severity; the probes discussed (stimulants, dopamine agonists) are poorest-tolerated in severe/very-severe patients, so cross-reference ch14a before any trial.

*Origin:* /integrate-topic bedard2026-central-fatigability-cascade (gap-fill of the prior fatigue-cycle ch30-tier NONE decision; routes the already-integrated @clf:central-fatigability finding through the ch34 cascade framework without duplicating it).
