#import "../../../../shared/environments.typ": *

=== Central Motor-Drive Fatigability Cascade
  <sec:central-motor-drive-cascade>

*Certainty: 0.45.* The Bedard 2026 multimodal-neuroimaging study (n=15 ME/CFS vs n=19 controls; grip force + EMG + EEG + fMRI + corticomuscular coherence) @Bedard2026centralFatigability showed that ME/CFS patients generate equal maximum voluntary force yet fatigue earlier than controls. The key group difference was *where the output did not change*: healthy controls steadily increased muscle-fiber recruitment (Dimitrov index), cortical (EEG power), and subcortical (BOLD) activity across the sustained task and declined only slowly after exhaustion, whereas ME/CFS showed minimal fluctuation — an absent up-regulation of central motor output in the face of rising effort demand. This entry routes that evidence through the differential-diagnostic cascade framework: the earlier fatigability is modeled as a failure of the brain to *increase* motor drive to match demand (cortical output → corticospinal drive → spinal motoneuron → neuromuscular → muscle fiber → afferent feedback), rather than peripheral muscle exhaustion. It is distinguished — pharmacologically — from the metabolically-primitive energy-triage model (@sec:triage-cascade), from dopaminergic-effort loss of motivation (@sec:gerlier-dopamine-node), and from brain-only neuroinflammation (@sec:microglial-cascade), because the *association* is central-output failure, not metabolic depletion, anhedonia, or inflammation per se. The diagnostic value lies in which central-acting interception drug restores motor-drive up-regulation — the cascade is a hypothesis and a research probe, NOT an established causal mechanism (the authors explicitly disclaim causation; only TMS or a drug-intervention study could establish direction). Cross-reference the objective-measurement finding in @clf:central-fatigability and the motor-imaging background in @sec:nih-fmri.

*Consequence:* Reframing ME/CFS fatigability as a brain-level failure to drive muscle — rather than a purely peripheral muscle problem — changes which interception drugs a clinician would consider as research probes and gives a testable, drug-response framework for where in the motor path the bottleneck lies, but no drug is recommended on this associational evidence alone.

#include "subsubsec-01-cascade-central-motor-drive-cortical-output-efferent-failure.typ"

#synthesis(title: [Central Motor-Drive Failure as a Convergent Model of ME/CFS Fatigability])[
The objective-measurement finding (@clf:central-fatigability, cert 0.60) and this motor-drive cascade (cert 0.45) converge on a single framing: ME/CFS fatigability is centrally mediated — the brain fails to *increase* motor output to match rising effort demand, rather than the muscle being exhausted. The convergence is functional and not merely statistical: equal maximum voluntary force (muscle capable), earlier fatigue (performance declines sooner), and an absent up-regulation of cortical/subcortical output and muscle-fiber recruitment (the brain does not push harder) jointly argue against peripheral muscle exhaustion as the primary limiter. The same protocol's differential-drug logic then gives a research pathway to localize *why*: dopaminergic/effort-node interception (methylphenidate, modafinil, amphetamines, bromocriptine/rotigotine) and glutamatergic release (amantadine) each test a distinct cascade node, while a peripheral ergogenic aid tests the negative (central) prediction. This is a research and diagnostic-testing model, NOT a validated mechanism or a treatment basis — causation remains unestablished (the authors disclaim it), the upstream cause (energy, dopaminergic effort, neuroinflammation, or maladaptive pacing) is unresolved, and severity applicability is unknown. Its value is to give ME/CFS fatigability a central, drug-testable, falsifiable structure that separates central-drive failure from metabolic energy-triage (@sec:triage-cascade) and CNS neuroinflammation (@sec:microglial-cascade).

*Consequence:* If this convergent central-drive model holds, ME/CFS fatigability is a brain-level phenomenon whose bottleneck can be probed by which central-acting agent (if any) restores motor-drive up-regulation — a testable research direction that steers treatment research toward the central nervous system, though it changes no clinical recommendation today.
] <syn:central-motor-drive-cascade>
