#import "../../../../../shared/environments.typ": *

#achievement(title: [Inflammation Directly Modulates Interoceptive Brain Regions])[
Peripheral inflammation alters activity in the brain's core interoceptive regions—the anterior insula and anterior cingulate cortex—providing a mechanistic bridge between ME/CFS immune dysfunction and altered interoceptive processing. Harrison et al.\ (2009, n=16) demonstrated that typhoid vaccination-induced inflammation reduced activity in mid-cingulate and increased insula-ACC coupling during an emotional-interoceptive task @Harrison2009inflammationInteroception. Savitz and Harrison (2018) systematically reviewed the inflammation-interoception axis, establishing that humoral immune signals (cytokines) modulate interoceptive brain regions via two complementary routes: (1) vagal afferent signaling (cytokine receptors on paraganglia → NTS → hypothalamus → insula), and (2) direct humoral access at circumventricular organs (OVLT, area postrema) where cytokines diffuse into adjacent hypothalamic and brainstem tissue @SavitzHarrison2018interoception.

The Zhang, Wager et al.\ (2025, n=200+, _Nature Neuroscience_) 7 Tesla fMRI mapping of the allostatic-interoceptive system provides the definitive neural reference map @ZhangWager2025AllostaticInteroceptive. The system spans anterior insula, dorsal ACC, medial prefrontal cortex, hypothalamus, periaqueductal gray, amygdala, and brainstem autonomic nuclei—precisely the regions showing structural and functional abnormalities in ME/CFS neuroimaging. Baraniuk et al.\ (2025) demonstrated that tenderness (a proxy for central sensitization) and interoceptive symptom burden are strongly correlated in ME/CFS and Gulf War Illness, suggesting nociplastic and interoceptive amplification co-localise @Baraniuk2025NociplasticMECFS.

(Certainty: 0.70. (0.65→0.70: reinforced by Zhang/Wager 2025 7T fMRI allostatic-interoceptive system mapping, n=200+, _Nature Neuroscience_). Inflammation-interoception pathway well-established in experimental inflammatory challenge paradigms but NOT directly tested in ME/CFS. The allostatic-interoceptive system mapping is well-replicated in large samples and provides the definitive anatomical framework.)
] <ach:ch15-inflammation-interoception-hub>
