#import "../../../../../shared/environments.typ": *

#achievement(title: [Inflammation Changes How the Brain Senses the Body])[
When the immune system is activated, the brain regions responsible for tracking the body's internal state—particularly the insula and anterior cingulate cortex—change their activity patterns. This means the immune dysfunction documented in ME/CFS has a direct anatomical target: the same brain areas that tell you whether your heart is racing, your gut is moving, or your muscles are tense.

Harrison et al.\ (2009, n=16) gave healthy volunteers a typhoid vaccine, which triggers a brief, controlled immune response. Brain scans showed that this inflammatory signal reduced activity in the mid-cingulate and changed how the insula and anterior cingulate communicated during an emotional task @Harrison2009inflammationInteroception. In other words, inflammation alters the brain's body-sensing network within hours—in healthy people. Savitz and Harrison (2018) reviewed the full evidence and found that immune signals reach the brain through two routes: (1) the vagus nerve, which carries chemical signals from the body directly to the brainstem, and (2) leaky spots in the blood-brain barrier where immune molecules can diffuse into brain tissue @SavitzHarrison2018interoception.

Zhang, Wager et al.\ (2025, n=200+, _Nature Neuroscience_) used ultra-high-resolution 7 Tesla fMRI to map this entire body-sensing network in detail: anterior insula, dorsal anterior cingulate, medial prefrontal cortex, hypothalamus, amygdala, and brainstem autonomic nuclei @ZhangWager2025AllostaticInteroceptive. These are precisely the regions that appear abnormal in ME/CFS brain scans. Baraniuk et al.\ (2025) showed that tenderness (a measure of pain sensitivity) and body-sensing symptom burden are strongly correlated in ME/CFS and Gulf War Illness, suggesting that pain amplification and body-sensing amplification happen in the same brain regions @Baraniuk2025NociplasticMECFS.

(Certainty: 0.70. (0.65→0.70: reinforced by Zhang/Wager 2025 7T fMRI allostatic-interoceptive system mapping, n=200+, _Nature Neuroscience_). The pathway from inflammation to altered body-sensing is well-established in healthy people given a temporary immune challenge. It has NOT been directly measured in ME/CFS patients. The brain network map is well-replicated in large samples and provides the anatomical blueprint.)
] <ach:ch15-inflammation-interoception-hub>
