#import "../../../../../shared/environments.typ": *

#synthesis(title: [Tryptophan Diversion: A Multi-Branch Convergence with AhR as Receptor-Level Node])[
The tryptophan-diversion model — that inflammation and gut dysbiosis shift tryptophan away from serotonin and toward kynurenine and indole metabolites — is not a single hypothesis but a cluster of related mechanisms that converge on one substrate. The peripheral-serotonin branch (@syn:peripheral-serotonin-depletion-model; @hyp:peripheral-serotonin-convergence, cert 0.50) documents depletion driven by IDO-mediated diversion. The kynurenine branch (ch12, ch18, ch52) covers the neurotoxic/neuroprotective metabolite cascade. The gut-microbial indole branch (@hyp:ahr-gut-microbiome-axis, cert 0.40) adds the aryl-hydrocarbon receptor as a receptor-level node sensing both indole ligands and kynurenine-pathway metabolites, coupling the gut microbiome to intestinal barrier and immune tone. These are not competing explanations — they are three branches of one distributed network (Torrelli-Diljohn @TorrelliDiljohn2026TryptophanSignaling), with AhR providing a mechanistic receptor that kynurenine and indole ligands both engage.

The critical caveat is evidential asymmetry. The serotonin branch rests on cross-disease data (ME/CFS n=38, plus Long COVID/POTS/fibromyalgia) with no interventional confirmation. The kynurenine branch has the most established ME/CFS literature. The AhR branch is the weakest link: its single direct ME/CFS anchor (@ach:esteban2026-ahr-neurocognitive, @Esteban2026AhRGutMicrobiome) is cross-sectional, shows subgroup-specific (neurocognitive) rather than uniform AhR activation, has not been independently replicated, and has no direct ME/CFS immune-readout studies (IL-22, Th17/Treg). Adding AhR to the convergence therefore adds mechanistic breadth but not evidential weight — it must not be used to inflate confidence in the broader tryptophan-diversion model.

*Consequence:* Readers should treat tryptophan diversion as a plausible, multi-branch convergence in which the serotonin and kynurenine arms are better evidenced and the AhR/gut-microbiome arm is a promising but early-stage addition — useful as a unifying hypothesis and a research target, not as a basis for any treatment or clinical conclusion.
] <syn:ahr-tryptophan-diversion-convergence>
