#import "../../../../shared/environments.typ": *

==== Prerequisite and Contraindicated Combinations

Some combinations are not merely additive probes — they are prerequisites for either drug to work at all, or they are contraindicated because one drug removes the system the other depends on:

*Prerequisite combinations (drug A enables drug B):*
- *Midodrine is a prerequisite for guanfacine:* Guanfacine suppresses central sympathetic outflow → hypotension. Without midodrine to maintain peripheral vascular tone, guanfacine's cognitive benefit is inaccessible because BP crashes first. This is not synergy — it is dependency: guanfacine *requires* midodrine co-administration in sympathetically-dependent patients, as identified by the tolerability ceiling pattern (Pattern 4).
- *Mast cell stabilization (ketotifen/cromolyn) is a prerequisite for IVIG:* IVIG can trigger mast cell degranulation via complement activation (C3a/C5a → mast cell MRGPRX2 or FcεRI). In patients with active MCAS, IVIG without prior mast cell stabilization produces a severe flare that may last >7 days. The flare confirms MCAS but prevents IVIG from working. Pre-treatment with ketotifen stabilizes mast cells, allowing IVIG's autoantibody-neutralizing effect without the mast-cell-mediated worsening.
- *NAC is a prerequisite for CoQ10 in patients with low glutathione:* CoQ10 increases ETC electron flux → ROS production. Without adequate glutathione (NAC-dependent), increased ROS worsens oxidative damage → CoQ10 produces paradoxical worsening. NAC restores glutathione → CoQ10 can then improve ATP without ROS-mediated side effects. Pre-existing glutathione depletion is diagnosed by CoQ10 worsening; NAC pre-treatment is confirmed if CoQ10 works after NAC loading.
- *LDN is a prerequisite for taVNS to be interpretable:* If taVNS works without LDN → the cholinergic anti-inflammatory pathway (CAP) is intact from vagal afferent through efferent. If taVNS does NOT work → CAP is blocked (GPCR AAb-mediated). If LDN is then added and taVNS starts working → LDN reduced neuroinflammation on the afferent side, restoring CAP. If LDN is added and taVNS still does NOT work → CAP blockade is at the efferent arm (splenic β2-AR AAb), not the afferent arm. LDN plus taVNS sequentially distinguishes afferent from efferent CAP blockade.
- *Butyrate/probiotics as a prerequisite for pyridostigmine:* If pyridostigmine does not improve HRV → vagal efferent pathway is non-functional. If butyrate is then added and restores HRV → the lesion was enteric-chromaffin-vagal — butyrate restored EC serotonin, which restored 5-HT3-mediated vagal afferent firing, which enabled pyridostigmine to enhance efferent transmission. If butyrate does NOT restore pyridostigmine response → the lesion is at the ganglionic or efferent level (AChR AAb or efferent nerve damage), not the enteric level. Butyrate + pyridostigmine sequentially localizes the vagal lesion to enteric, ganglionic, or efferent level.

*Contraindicated combinations (drug A undermines drug B's mechanism):*
- *Beta-blockers + midodrine:* Midodrine relies on α1-mediated vasoconstriction. β2-AR blockade impairs the cardiac output response that is needed to deliver the vasoconstricted blood volume to tissue. The combination produces vasoconstriction without perfusion increase → BP rises, symptoms may not improve. Ivabradine + midodrine is the correct probe: HR control without β2 blockade.
- *Benzodiazepines + pyridostigmine:* Benzodiazepines enhance GABA-A signaling, which suppresses central autonomic output. Pyridostigmine enhances peripheral cholinergic tone. The central suppression from benzodiazepines may override the peripheral enhancement from pyridostigmine → the net autonomic output is reduced. If a patient on chronic benzodiazepines does not respond to pyridostigmine, the null may reflect GABAergic suppression of the central autonomic network, not peripheral vagal dysfunction.
- *Gabapentinoids + pyridostigmine:* Gabapentinoids reduce neurotransmitter release (α2δ-CaV channel block). Pyridostigmine increases ACh at the synapse. If gabapentinoids are on board, ACh release is already suppressed — pyridostigmine's AChE inhibition has less ACh to work with. Gabapentinoid co-administration reduces pyridostigmine's effect size, producing a false null — the vagal system may be intact but pharmacologically suppressed.
- *Opioids + LDN:* Full opioid agonists (morphine, oxycodone, tramadol) compete with LDN at the μ-opioid receptor. LDN's endorphin-upregulation mechanism requires intermittent opioid receptor blockade → compensatory endorphin upregulation during the blockade window. If a full agonist occupies the receptor continuously, LDN cannot produce the intermittent blockade that triggers upregulation. The null LDN response in an opioid-treated patient is uninterpretable — the opioid is blocking LDN's mechanism, not the absence of neuroinflammation. Opioids should be tapered and cleared before LDN trial.
- *Stimulants + pacing-based interventions:* Methylphenidate or amphetamines suppress the PEM warning signal — the patient exceeds their energy envelope, crashes. If a pacing protocol is started while the patient is on stimulants, the signal the patient is supposed to pace *by* (perceived exertion, fatigue onset) is pharmacologically suppressed. The pacing fails not because pacing doesn't work, but because the patient cannot feel the limit. Stimulants should be stopped or reduced before initiating pacing-based PEM prevention.
- *DORAs + pitolisant:* DORAs block orexin receptors; pitolisant releases histamine via H3 inverse agonism. If a patient is on a DORA (orexin blockade), pitolisant's histaminergic activation is acting on a system whose primary wakefulness driver (orexin) is pharmacologically suppressed — the histaminergic system may not be sufficient to maintain wakefulness without orexin tone. Pitolisant non-response in a DORA-treated patient is uninterpretable — the DORA is suppressing the arousal system pitolisant needs.
- *NSAIDs + LDN in MCAS patients:* LDN reduces microglial TLR4 signaling, which indirectly reduces COX-2 expression. If NSAIDs are co-administered, COX-1/COX-2 blockade removes the prostaglandin-mediated mast cell stabilization that was compensating for the patient's MCAS. The combination may worsen MCAS symptoms because both the microglial brake (LDN) and the prostaglandin brake (NSAID removal) are suppressed simultaneously → unopposed mast cell degranulation. MCAS patients should have mast cell stabilization (ketotifen) on board before adding NSAIDs to LDN.
- *Corticosteroids + immunoadsorption:* Corticosteroids suppress antibody production by plasma cells. If given before IA, the autoantibody titer may be artificially low → IA removes fewer AAbs → the post-IA improvement is smaller. If corticosteroids are stopped after IA, the suppressed plasma cells rebound → autoantibody production surges → post-IA benefit is lost faster than expected. Corticosteroid timing relative to IA determines the interpretability of IA response.
- *Gabapentinoids + DORAs:* Both suppress CNS neurotransmission — gabapentinoids via α2δ-CaV channel block (reducing neurotransmitter release) and DORAs via orexin receptor antagonism (reducing wakefulness drive). Combined, the CNS depressant effect is multiplicative, not additive — a patient who tolerates either drug alone may experience severe sedation or cognitive impairment when both are combined. The synergy in sedation is a probe for orexin-CaV interdependence: orexin neurons use CaV channels for burst firing, and blocking both the firing mechanism (CaV) and the downstream effector (OX1R/OX2R) collapses the arousal system from two directions simultaneously.
- *Multiple sedating antihistamines (H1) combined:* Each H1 antihistamine has different CNS penetration (cetirizine ~30% CNS, fexofenadine ~0% due to P-gp efflux, diphenhydramine >90%). If a patient on fexofenadine (non-sedating) becomes sedated after adding cetirizine → the cumulative H1 occupancy crosses the CNS threshold — CNS H1 receptors are intact and at normal density, and sedation appears when total CNS H1 occupancy exceeds ~50%. If a patient on diphenhydramine is NOT sedated → CNS H1 receptors are fully desensitized from chronic mast cell histamine exposure. Combine non-sedating + sedating antihistamines sequentially to determine the CNS H1 receptor status: sedation at low cumulative dose → intact receptors, normal sensitivity; no sedation at any dose → chronic MCAS with CNS H1 downregulation.
- *H1 + H2 antihistamine combination producing no improvement where each alone produces partial:* H1 blocks mast-cell histamine at tissue receptors; H2 blocks gastric histamine at parietal cells. If combined, histamine from both sources is blocked → MCAS symptoms should resolve completely. If combined effect is additive only (not synergistic) → mast cell degranulation releases mediators beyond histamine (tryptase, PGD2, leukotrienes, PAF) that are not blocked. The additive-only response confirms non-histamine mast cell mediators are the dominant symptom drivers. Add montelukast (leukotriene receptor antagonist) — if that adds further improvement → leukotrienes confirmed. Add aspirin (COX inhibitor) — if that helps → PGD2 confirmed. The combination builds the mast cell mediator profile one drug at a time.

*Consequence:* Drug combinations are probes, not just treatments. Synergy magnitude distinguishes independent mechanisms from shared pathways. Antagonism reveals upstream/downstream relationships. Ordering requirements reveal causal chains. Prerequisite combinations identify dependencies — some drugs are inaccessible without another drug enabling them. Contraindicated combinations identify situations where a null response is a false negative — the second drug blocked the first drug's mechanism, not the disease process.
*Origin:* mechanistic-pathway-tracing.
