#import "../../../shared/environments.typ": *

== The Psychosomatic Pattern: Historical Parallels
<sec:psychosomatic-parallels>

ME/CFS is not the first disease to be dismissed as psychosomatic before its biological basis was established. A systematic review of the history of psychosomatic medicine reveals a recurring pattern across at least ten major diseases @MECFSScience2021psychosomatic:
    - *Multiple sclerosis* was considered psychosomatic for decades; patients were told their weakness was hysterical
    - *Asthma* was attributed to the "asthma personality" and treated with psychotherapy
    - *Epilepsy* was classified as a psychological condition and patients were institutionalised
    - *Diabetes* was linked to emotional stress and treated with psychoanalysis
    - *Autism* was blamed on "refrigerator mothers" who failed to bond with their children
    - *Schizophrenia* was attributed to "schizophrenogenic mothers"
    - *Cancer* was linked to suppressed emotions and the "cancer personality"
    - *Heart disease* was attributed to the "Type A personality"
    - *Rheumatoid arthritis* was considered a psychosomatic condition driven by emotional conflicts
    - *Peptic ulcer* was treated with psychotherapy until Marshall and Warren discovered _Helicobacter pylori_ in 1982---a condition assumed to be stress-related that turned out to have a specific biological cause
    - *Irritable bowel syndrome* retains a functional diagnosis but now has validated pathophysiological subsets (bile acid malabsorption, post-infectious IBS with mast cell activation), illustrating that "functional" and "biological" are not mutually exclusive
The peptic ulcer story is particularly instructive: despite clear evidence that _H. pylori_ caused ulcers, the psychosomatic establishment resisted the biological explanation for years. Marshall famously infected himself to prove the point. The pattern---biological discovery $arrow.r$ establishment resistance $arrow.r$ eventual acceptance---has been repeated across several diseases on this list. Whether ME/CFS follows the same trajectory depends on the outcome of ongoing biological investigations, not on historical analogy alone.
This historical context does not prove that ME/CFS has a specific biological cause, but it does demonstrate that medicine has a systematic tendency to classify poorly understood diseases as psychosomatic, and that this classification has consistently been wrong when biological investigation eventually catches up. The lesson is that absence of a known mechanism is not evidence for a psychological cause.
The question then becomes: what would the equivalent of Marshall's _H. pylori_ discovery look like for ME/CFS? The Peptic Ulcer Parallel speculation (Chapter @ch:integrative-models, Speculation @spec:peptic-ulcer-parallel) identifies three candidates for the "molecular switch" that maintains ME/CFS independently of the original trigger: (1) TRPM3 ion channel dysfunction affecting calcium signalling across immune, neuronal, and metabolic cells (Chapter @ch:immune-dysfunction); (2) epigenetic methylation locks at autonomic regulatory genes that persist after the triggering infection resolves; (3) a genetic bottleneck in mitophagy capacity revealed by the DecodeME autophagy genes _FBXL4_ and _CCPG1_ (Chapter @ch:genetics-epigenetics, Hypothesis @hyp:mitophagy-vulnerability). Each candidate predicts a different "eradication therapy"---TRPM3-restoring drugs, targeted demethylation agents, or mitophagy enhancers---but all share the peptic ulcer pattern: a simple persistent factor maintaining a complex disease that was assumed to be psychosomatic.

#speculation(title: [Psychologization Lag and the Biomarker Threshold])[
Historical patterns in de-psychologization suggest a consistent ~11–16 year lag between the first compelling biological evidence and widespread clinical acceptance of a biological explanation — observed for peptic ulcer (Marshall 1984 → acceptance ~1995–2000), SLE (Hargraves 1948 LE cell → ANA standard of care ~1960s), and multiple sclerosis (MRI introduced early 1980s → psychologization declined by the late 1990s). A single sufficiently specific biomarker (ANA for SLE, H. pylori for ulcer, MRI for MS) appears sufficient to shift the equilibrium, but the shift is not instantaneous. Notably, even after biomarker availability, residual psychologization persists at approximately 10–15% — particularly for female patients, atypical presentations, and seronegative subsets.

This pattern has two implications for ME/CFS. First, it predicts that any validated biomarker (e.g., a specific autoantibody panel, a metabolomic signature, or a genetic risk score with sufficient individual-level discrimination) would reduce but not eliminate psychologization, following the same ~10–15 year lag. Second, it predicts that psychologization would decline even without a single deterministic biomarker if a convergent body of objective physiological abnormalities reaches clinical consensus — a trajectory ME/CFS may already be on, given the accumulation of immunological, metabolic, and autonomic findings documented in Chapters @ch:immune-dysfunction through @ch:cardiovascular. The post-COVID Long COVID connection may accelerate this trajectory by providing a "legitimacy spillover": a substantial fraction of LC patients — including clinicians and biomedical researchers — now experience PEM firsthand, making psychological attribution less plausible.

Fibromyalgia provides an instructive counter-example: despite accumulating biomarker evidence (small fiber neuropathy with reduced IENFD, neuroinflammation by PET, central sensitization by fMRI), the condition remains strongly psychologized. Possible reasons include: (a) no single decisive biomarker (unlike ANA for SLE), (b) 80% female skew amplifies dismissal, (c) absence of a post-infectious trigger cohort analogous to LC/ME/CFS providing "legitimacy" spillover, (d) the legacy of 1980s "psychogenic rheumatism" framing in the name itself. The comparison suggests that for ME/CFS, the post-infectious link and the severity gradient (severe/very severe patients, particularly those bedbound, are more difficult to dismiss as functional) may be protective factors that fibromyalgia lacks.

*(Certainty: 0.40. The historical lag estimates are based on the existing ch33 psychosomatic parallels list and supported by Schomerus 2026, which discusses the ulcer-to-psychology reversal as a cautionary tale. The quantitative lag estimate (11–16 years) is derived from publication-to-guideline timelines for the three comparator conditions but not from a formal systematic review of de-psychologization rates. The fibromyalgia comparison is observational and hypothesis-generating. Origin: brainstorm.)*
] <spec:psychologization-lag-biomarker>


