#import "../../../shared/environments.typ": *

== The Psychosomatic Pattern: Historical Parallels
<sec:psychosomatic-parallels>

ME/CFS is not the first disease to be dismissed as psychosomatic before its biological basis was established. A systematic review of the history of psychosomatic medicine reveals a recurring pattern across at least ten major diseases @MECFSScience2021psychosomatic:
    - *Multiple sclerosis* was considered psychosomatic for decades; patients were told their weakness was hysterical
    - *Asthma* was attributed to the "asthma personality" and treated with psychotherapy
    - *Epilepsy* was classified as a psychological condition and patients were institutionalized
    - *Diabetes* was linked to emotional stress and treated with psychoanalysis
    - *Autism* was blamed on "refrigerator mothers" who failed to bond with their children
    - *Schizophrenia* was attributed to "schizophrenogenic mothers"
    - *Cancer* was linked to suppressed emotions and the "cancer personality"
    - *Heart disease* was attributed to the "Type A personality"
    - *Rheumatoid arthritis* was considered a psychosomatic condition driven by emotional conflicts
    - *Peptic ulcer* was treated with psychotherapy until Marshall and Warren discovered _Helicobacter pylori_ in 1982---a condition assumed to be stress-related that turned out to have a specific biological cause
    - *Irritable bowel syndrome* retains a functional diagnosis but now has validated pathophysiological subsets (bile acid malabsorption, post-infectious IBS with mast cell activation), illustrating that "functional" and "biological" are not mutually exclusive
The peptic ulcer story is particularly instructive: despite clear evidence that _H. pylori_ caused ulcers, the psychosomatic establishment resisted the biological explanation for years. Marshall famously infected himself to prove the point. The pattern---biological discovery $arrow.r$ establishment resistance $arrow.r$ eventual acceptance---has been repeated across several diseases on this list. Whether ME/CFS follows the same trajectory depends on the outcome of ongoing biological investigations, not on historical analogy alone.
This historical context does not prove that ME/CFS has a specific biological cause, but it does demonstrate that medicine has a systematic tendency to classify poorly understood diseases as psychosomatic, and that this classification has consistently been wrong when biological investigation eventually catches up. The lesson is that absence of a known mechanism is not evidence for a psychological cause.
The question then becomes: what would the equivalent of Marshall's _H. pylori_ discovery look like for ME/CFS? The Peptic Ulcer Parallel speculation (Chapter @ch:integrative-models, Speculation @spec:peptic-ulcer-parallel) identifies three candidates for the "molecular switch" that maintains ME/CFS independently of the original trigger: (1) TRPM3 ion channel dysfunction affecting calcium signalling across immune, neuronal, and metabolic cells (Chapter @ch:immune-dysfunction); (2) epigenetic methylation locks at autonomic regulatory genes that persist after the triggering infection resolves; (3) a genetic bottleneck in mitophagy capacity revealed by the DecodeME autophagy genes _FBXL4_ and _CCPG1_ (Chapter @ch:genetics-epigenetics, Hypothesis @hyp:mitophagy-vulnerability). Each candidate predicts a different "eradication therapy"---TRPM3-restoring drugs, targeted demethylation agents, or mitophagy enhancers---but all share the peptic ulcer pattern: a simple persistent factor maintaining a complex disease that was assumed to be psychosomatic.

#speculation(title: [Psychologization Lag and the Biomarker Threshold])[
Historical patterns suggest that de-psychologization following biomarker discovery is real but slow: peptic ulcer (Marshall 1984), SLE (LE cell 1948 → ANA standard), and multiple sclerosis (MRI introduction 1980s) each show a multi-decade lag between first compelling biological evidence and widespread clinical acceptance. A sufficiently specific biomarker (ANA for SLE, H. pylori for ulcer, MRI for MS) appears capable of shifting the equilibrium, but not instantaneously and not completely — residual psychologization persists even post-biomarker, particularly for female patients, atypical presentations, and seronegative subsets. The precise duration of the lag and its generalizability across diseases are unknown; the three cases are illustrative, not a formal inductive sample.

This pattern has implications for ME/CFS. Any validated biomarker would likely reduce but not eliminate psychologization, following a lag whose duration cannot be predicted from three historical cases. Psychologization may also decline without a single deterministic biomarker if a convergent body of objective physiological abnormalities reaches clinical consensus — a trajectory ME/CFS may already be on, given the accumulation of immunological, metabolic, and autonomic findings documented in the pathophysiology chapters. The post-COVID Long COVID connection may accelerate this trajectory by providing a "legitimacy spillover": clinicians and researchers who develop LC and experience PEM firsthand are less likely to attribute it to psychological causes.

Fibromyalgia provides a counter-example: despite accumulating biomarker evidence (small fiber neuropathy, neuroinflammation by PET, central sensitization by fMRI), the condition remains heavily psychologized. Observational differences that may contribute include the absence of a clear post-infectious trigger cohort analogous to LC, the 80% female patient skew, and the lack of a single decisive biomarker. This is post-hoc comparison, not predictive analysis — whether ME/CFS follows the trajectory of MS/SLE (partial de-psychologization) or fibromyalgia (persistent psychologization) is unknown and depends on factors beyond biomarker discovery alone, including institutional, political, and cultural dynamics.

*(Certainty: 0.40. The core observation (biomarker discovery tends to reduce psychologization) is grounded in historical cases but the quantitative features (lag duration, residue rate, fibromyalgia comparison) are extrapolated from a small, non-systematic set of examples and should be treated as qualitative pattern recognition, not quantitative prediction. Origin: brainstorm.)*
] <spec:psychologization-lag-biomarker>


