#import "../../../../shared/environments.typ": *

=== Patient Advocacy and the Psychogenic Harm

The psychogenic model has caused measurable harm to patients:
    - *Treatment harm*: GET prescribed under the psychogenic model has worsened many patients @Kindlon2011GET
    - *Diagnostic delay*: Physicians trained to view ME/CFS as psychological often fail to diagnose or investigate the condition, resulting in years of delayed treatment. The diagnostic labyrinth is well-documented—across 12 qualitative studies, patients report navigating systems where their symptoms are repeatedly dismissed as psychological, somatoform, or not severe enough to warrant investigation @Bayliss2014BarriersPrimaryCare
    - *Insurance and disability denial*: Patients report that psychogenic framing has contributed to denial of disability benefits and insurance claims
    - *Research underfunding*: Classification as a psychological condition reduced biomedical research funding for decades
    - *Stigma*: Patients report that the psychogenic label is the single most damaging aspect of their interaction with the medical system, more distressing than the illness itself. Perceived stigma independently predicts suicidal ideation after controlling for depression @McManimen2018UnsupportiveStigma @Johnson2022SuicideRiskStigma. The healthcare dismissal experience—being disbelieved, trivialised, or labelled—is the most consistent finding across qualitative research spanning 1999–2024 @Asbring2002WomensStigma @Guise2010DiscourseDoctors @Melby2024HealthcareDissatisfaction
    - *Media reinforcement*: Content analysis of 280 UK newspaper articles found 70% emphasised psychological characterisations of ME/CFS, amplifying public stigma @Knudsen2011MediaStigma
    - *Name-based stigma*: The diagnostic label "chronic fatigue syndrome" generates more negative attributions than alternative names, indicating the illness name itself propagates stigma @Jason2002IllnessName
Patient advocacy organizations have been instrumental in challenging the psychogenic model, demanding data transparency (PACE trial reanalysis), and advocating for guideline changes. The 2021 NICE guideline revision @NICE2021mecfs, which explicitly rejected the biopsychosocial model for ME/CFS, represents a landmark victory for evidence-based medicine driven in significant part by patient advocacy.
The academic counterargument continues to build. Spanoghe, Molmans et al.\ (2026) published a peer-reviewed commentary in _Frontiers in Medicine_ directly rebutting the FSD framing proposed by Ranque and Cogan @Spanoghe2026commentary. Their critique identifies five structural weaknesses in the FSD position: (1) the original article is a narrative review without systematic evidence evaluation, risk-of-bias assessment, or GRADE-quality hierarchisation; (2) the FSD concept itself has poorly defined boundaries, heterogeneous criteria, and functions as a residual category rather than a well-delimited diagnostic entity; (3) the literature selection omits substantial biomedical evidence including viral persistence, neuroinflammation, endothelial dysfunction, skeletal muscle abnormalities, mitochondrial dysfunction, and autonomic impairment; (4) attributing primary etiological weight to psychological factors without longitudinal or causal analyses risks confusing consequences with causes; and (5) framing long COVID as predominantly psychosomatic in a context of scientific uncertainty causes measurable harm—distress, self-doubt, loss of agency, and isolation. The authors advocate instead for treating long COVID as a heterogeneous post-infectious multisystemic condition requiring biomedical sub-classification, mechanistic investigation, and targeted interventions.


