#import "../../../../shared/environments.typ": *

=== Population Generation

Virtual patients are generated by sampling parameter vectors $bold(theta)_i$ from a multivariate distribution calibrated to published ME/CFS data:

$
bold(theta)_i ~ cal(N)(bold(mu)_"ME/CFS", bold(Sigma)_"ME/CFS"), quad i = 1, dots, N_"pop"
$ <eq:virtual-population>

where $bold(mu)_"ME/CFS"$ is the mean parameter vector estimated from published biomarker studies and $bold(Sigma)_"ME/CFS"$ captures inter-patient correlations (e.g., low $alpha_"CI"$ correlates with high ROS). Each virtual patient $i$ is simulated to steady state, yielding a predicted symptom profile and attractor assignment. A population of $N_"pop" = 10,000$ virtual patients reproduces the observed subtype distribution and severity spectrum when $bold(mu)$ and $bold(Sigma)$ are appropriately calibrated.

