#import "../../../../shared/environments.typ": *

==== Step R2: Impaired vagal afferent signaling → reduced vagal efferent tone (afferent/efferent transmission)

*Probe:* Pyridostigmine (AChE inhibitor, 30--60 mg) — enhances vagal efferent transmission by increasing synaptic ACh at M2/M3 receptors on target organs; taVNS (transcutaneous auricular vagus nerve stimulation) — electrically stimulates vagal afferents → reflex vagal efferent activation; Nicotine patch (transdermal, α7nAChR agonist) — directly stimulates the CAP efferent receptor on splenic macrophages, bypassing the entire vagal arc.

*Three-level lesion mapping:*

#finding(claim: [Pyridostigmine + taVNS both work — vagal arc intact, lesion is upstream], explanation: [The vagal pathway is intact across its full arc — afferent (taVNS activates it), efferent (pyridostigmine enhances it), and postsynaptic (M2/M3 receptors respond). The lesion is upstream of the vagus: enteric level (gut dysbiosis, EC cell dysfunction) or central level (insufficient NTS/DMV activation from higher brain centres). Butyrate/5-HTP should work (enteric-level probe).], certainty: [Medium], level: [Partial root cause — upstream vagal lesion])

#finding(claim: [taVNS works but pyridostigmine does NOT — efferent ACh release deficit], explanation: [The vagal afferent→efferent reflex arc is intact, but the efferent arm has reduced ACh release capacity — AChE inhibition cannot compensate because there is insufficient ACh to potentiate. Pattern implicates reduced vesicular ACh stores (impaired choline acetyltransferase or choline deficiency) or reduced vagal efferent fibers (neuropathy). CDP-choline (citicoline, 500--1000 mg) should be trialed; if it restores pyridostigmine response, the ACh synthesis deficit is confirmed.], certainty: [Medium], level: [Partial root cause — efferent ACh synthesis deficit])

#finding(claim: [Pyridostigmine works but taVNS does NOT — afferent arm blocked or unresponsive], explanation: [The vagal efferent arm is functional but the afferent arm is blocked or unresponsive to electrical stimulation. Possibilities: (a) vagal afferent fiber damage — peripheral neuropathy affecting the auricular branch, (b) impaired central processing at NTS (neuroinflammation, GPCR AAb), or (c) inadequate stimulation parameters. NTS neuroinflammation is most likely in ME/CFS — try LDN or minocycline then retry taVNS.], certainty: [Medium], level: [Partial root cause — afferent/central vagal lesion])

#finding(claim: [Neither pyridostigmine nor taVNS works — efferent pathway non-functional at or downstream of DMV], explanation: [Three possibilities: (a) severe DMV damage — brainstem neuroinflammation has lesioned vagal motor neurons; (b) ganglionic AChR autoantibodies blocking nicotinic AChR at autonomic ganglia; (c) vagal nerve structural damage — cervical compression, surgical damage, or demyelination. Test for ganglionic (α3-β4) nicotinic AChR autoantibodies (Mayo panel).], certainty: [Medium], level: [Partial root cause — ganglionic/post-ganglionic vagal lesion])
#finding(claim: [Ganglionic AChR AAb positive — autoimmune autonomic ganglionopathy], explanation: [Null response to both pyridostigmine and taVNS with positive ganglionic (α3-β4) nicotinic AChR autoantibodies localizes the vagal lesion to the ganglion, not the nerve or brainstem. Treatment is immunomodulation (IVIG, rituximab, plasma exchange), not cholinergic enhancement.], certainty: [Medium], level: [Partial root cause — autoimmune ganglionopathy])

#finding(claim: [Nicotine patch works where pyridostigmine and taVNS both fail — CAP endpoint intact, lesion in vagal→splenic transmission], explanation: [The CAP efferent receptor (α7nAChR on macrophages) is intact and responsive — direct stimulation bypasses the entire vagal arc. The lesion is in vagal→splenic transmission (splenic nerve, T-cell ACh release) but the macrophage can still respond. CAP can be restored — treatment target is the vagal-splenic pathway, not the macrophage.], certainty: [Low to Medium], level: [Partial root cause — vagal-splenic transmission deficit])

*Consequence:* Butyrate + 5-HTP at the enteric level, taVNS at the afferent level, and pyridostigmine + CDP-choline at the efferent level distinguish three vagal lesion levels: enteric (butyrate/5-HTP-responsive), central afferent (taVNS-responsive after NTS anti-inflammatory), and ganglionic (pyridostigmine-responsive if synapses intact; neither pyridostigmine nor taVNS responsive if AChR AAb blocks). Nicotine patch probes the CAP endpoint (macrophage α7nAChR). This four-level mapping is one of the cleanest diagnostic sequences in the chapter — each probe tests a specific anatomical segment of the vagal pathway, and the pattern of responses localizes the lesion along the gut→vagus→brainstem→spleen→macrophage axis.
*Origin:* mechanistic-pathway-tracing.
