#import "../../../../shared/environments.typ": *

#open-question(title: [Per-Locus Dynamics: Vector Model for Bidirectional Methylation])[
ME/CFS methylation changes are bidirectional---both hypermethylation and hypomethylation at different loci---and the dominant direction may vary by tissue, cell type, and assay platform @Peppercorn2025methylation @ChalderMoreau2026ptprn2 @deVega2014methylation. PTPRN2 hypomethylation correlates with cognitive symptoms; pericentromeric hypomethylation may derepress HSAT2 satellite repeats driving immune exhaustion; yet RRBS of PBMCs found 67.8% hypermethylated features in n=5 ME/CFS @Peppercorn2025methylation. A scalar $cal(M)$ cannot represent this pattern faithfully.

*Resolution: the vector model.* The state variable $bold(cal(M)) in [0, 1]^n$ (defined in @sec:ode-system) replaces the scalar with a per-locus vector. Consolidation depth is $||bold(cal(M)) - bold(cal(M))^"baseline"||$, capturing deviation in either direction. The gain and loss models are not competitors but complementary manifestations of a single underlying process — DNMT3B redistribution — which produces gain at some loci and loss at others. The vector model contains both as special cases (gain-dominant vs loss-dominant locus subsets) and unifies the paper's competing formulations under one mathematical object.

*Nucleosome mobility as the unifying molecular mechanism.* The context-dependent functional effects of CpG methylation — activating transcription in gene bodies, repressing it at promoters — may all reduce to a single biophysical mechanism @BonnetFourel2026ProAB: methylation on ~200 bp DNA segments decreases nucleosome mobility. Reduced mobility at promoters prevents transcription factor access (repression); reduced mobility in gene bodies stabilises nucleosome positioning and facilitates transcription elongation (activation). This single mechanism explains why the same biochemical modification produces opposite functional outcomes depending on genomic location — consistent with a vector model where the sign of the effect $(m_i - m_i^"baseline")$ matters less than the per-locus context of the affected site. The therapeutic implication: global methylation-modifying drugs (DNMT inhibitors, methyl donors) affect nucleosome mobility at all methylated loci simultaneously, with location-dependent functional consequences that cannot be predicted from scalar methylation change alone.

*Per-locus dynamics.* Each locus $i$ evolves according to:

$ frac(d m_i, d t) = k_i^"meth" dot.op (1 - m_i) - k_i^"demeth" dot.op m_i - beta_i dot.op (m_i - m_i^"baseline") - delta_i dot.op Theta(m_i^"crit" - m_i) $

where $k_i^"meth"$ and $k_i^"demeth"$ are locus-specific methylation and demethylation rates (functions of DNMT3B allocation at ProB vs ProA vs gene-region classes), $beta_i$ is the locus-specific tendency to return to baseline (passive maintenance), and the final term models irreversibility: $Theta$ is the Heaviside step function, $delta_i$ is a penalty term that activates when $m_i$ falls below the critical density $m_i^"crit"$, representing the additional barrier to de novo remethylation. For ProB repeats, $k_i^"meth"$ is buffered by DNMT3B availability (constrained by the zero-sum redistribution across loci), so $sum_i k_i^"meth" ≤ K_"DNMT3B"^"total"$ — the locus-locus coupling constraint.

*Histone mark coupling.* At ProB repeats, CpG methylation loss is coupled to H3K9me3 loss; compensatory H3K27me3 gain (Polycomb) may partially rescue silencing but introduces a distinct chromatin state. The full state space is the tensor product $bold(cal(M)) ⊗ bold(cal(H))$ where $bold(cal(H)) = (h_1, h_2, ..., h_n)$ tracks per-locus histone marks. $B_"strength"$ depends on both methylation and histone state at ProB repeats. A full treatment exceeds current scope; the scalar histone index $cal(A)$ in @sec:epigenetic-dynamics provides a first approximation.

*Tissue/cell-type heterogeneity.* The vector model is tissue-indexed: $bold(cal(M))^"PBMC" ≠ bold(cal(M))^"CNS" ≠ bold(cal(M))^"muscle"$. Systemic interventions (methyl donors, SAMe, betaine) may differentially affect these tissue compartments. Methyl donors that penetrate the blood-brain barrier (methyl-folate, methyl-B12) may reach CNS loci; those that do not (some SAMe formulations) act only peripherally. Systemic remethylation may overshoot hypermethylated loci while correcting hypomethylated ones — a risk that per-locus targeting would avoid but current epigenetic drugs (global-acting HDAC inhibitors, DNMT inhibitors) cannot address. Tissue-specific models are desirable but data-constrained.

*Clinical implication.* The vector model replaces the binary "methyl-donors vs demethylators" therapeutic dichotomy with locus-specific targeting. The safest default strategy remains methyl-donor support (SAMe, methyl-folate, methyl-B12, betaine) — low-risk regardless of directionality — but the ultimate therapeutic goal is to restore $bold(cal(M)) → bold(cal(M))^"baseline"$ direction-correct at each locus: remethylation for hypomethylated ProB repeats (restoring heterochromatin) and demethylation for hypermethylated gene promoters (restoring expression). Current pharmacology cannot achieve this locus-specific precision, making the vector model both a more faithful representation of the biology and a call for the development of targeted epigenetic therapies.

*Certainty.* 0.55 for bidirectional pattern (documented across multiple studies). 0.40 for DNMT3B redistribution as the coupling mechanism (ProA/ProB framework @BonnetFourel2026ProAB is a preprint, unvalidated for ME/CFS; the zero-sum constraint is mechanistically plausible but unmeasured). 0.45 for the irreversibility threshold $m_i^"crit"$ (MeCP2/DNMT1 maintenance loop is well-established; Tiedemann 2024 provides direct experimental evidence that low-density CpG methylation is more vulnerable to maintenance disruption @Tiedemann2024UHRF1lowdensity; DNMT1 allosteric switch @Kimura2012DNMT1review further supports density-dependent maintenance. The *quantitative* threshold for any specific locus is unknown. 0.35→0.45: externally validated by Tiedemann 2024 NAR + Kimura 2012 review — general-population mechanistic evidence). 0.25 for the vector model providing better clinical guidance than the scalar model (direction-correct per-locus targeting is principled but pharmacologically unsupported). 0.15 for the tensor product $bold(cal(M)) ⊗ bold(cal(H))$ being operationally necessary (methylation-only models already capture the dominant signal; histone coupling may be a refinement rather than a structural requirement).

*Provisionality.* The ProA/ProB repeat framework (Bonnet, Hulo, Fourel et al.\ 2026 preprint) is a computational genomics hypothesis developed in cancer @BonnetFourel2026ProAB. Its extension to ME/CFS — including the DNMT3B redistribution mechanism, the $B_"strength"$ derived variable, and the clinical implications — is our extrapolation and has not been endorsed by those authors. The Fourel paper is itself not peer-reviewed. The vector model is a mathematical container for this hypothesis; the hypothesis itself remains provisional.
] <oq:consolidation-directionality>
