#import "../../../../../shared/environments.typ": *

#hypothesis(title: [Fibromyalgia Autoimmunity Is Not Contradicted by the Absence of an HLA Signal])[
*Certainty: 0.30.* The Kerrebijn 2026 GWAS found no significant MHC signal and no immune/glial heritability enrichment in fibromyalgia, providing genetic evidence against a primarily autoimmune (HLA-linked) architecture @Kerrebijn2026FibromyalgiaGWAS. Independent passive-transfer evidence demonstrates that IgG from fibromyalgia and long-COVID patients can reproduce symptomatology in mice, consistent with pathogenic autoantibodies (Origin: brainstorm; corpus: passive-IgG-transfer evidence in ch08 @Goebel2021passiveTransferFM).

*Reconciliation.* These are not contradictory, because germline genetic architecture (HLA/MHC) and acquired humoral autoimmunity (antibodies arising post-infection) are independent layers. An absence of HLA-linked germline risk does not rule out acquired pathogenic antibodies; conversely, the passive-IgG finding does not imply an HLA-linked architecture. This mirrors the ME/CFS situation, where DecodeME found no autoimmune genetic correlation yet passive-IgG and GPCR-autoantibody evidence exists. The possibility that a fibromyalgia antibody subset maps onto the non-HLA-linked central-sensitization architecture is a framing device — a coherent way to hold both findings — not an independently tested hypothesis.

*Falsifiable predictions:* (1) Fibromyalgia patients who respond to immunomodulation (IVIG/plasmapheresis) will cluster in an autoantibody-positive subset that shows no enrichment for the 26 GWAS loci. (2) Passive-transfer-positive fibromyalgia sera will correlate with autoantibody titers rather than with GWAS risk-score. Falsified if the GWAS loci and the autoantibody subset are the same patients (fully overlapping), which would argue for a unified HLA-linked mechanism.

*Consequence:* The no-MHC GWAS finding and the passive-IgG evidence can both be true because germline genetics and acquired antibodies are separate layers — so fibromyalgia need not be forced into an "is/isn't autoimmune" binary, and whether an antibody-defined subset exists and responds to immunomodulation remains to be tested.
] <hyp:fibromyalgia-autoimmune-reconciliation>
