project:
  type: website

bibliography:
  - references.bib

website:
  title: "Myalgic Encephalomyelitis / Chronic Fatigue Syndrome"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    html-math-method: mathjax
    cite-method: citeproc
    crossref:
      sec-prefix: Section
      fig-prefix: Figure
      tbl-prefix: Table
      eq-prefix: Equation
